steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - docker/prod/deepfilternet-runtime/Dockerfile.phase36h
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
