steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - docker/prod/qwen2-5-vl-cloud-run-gpu/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 200
timeout: 7200s
