export function buildCesiumJsLocal3DCommandPlan() {
  return {
    phase: '50E',
    defaultMode: 'static_report_only',
    executeCommand: 'GCP_PROJECT_ID=reeditpro GCP_REGION=us-central1 REEDITPRO_ENV=staging REEDITPRO_CONFIRM_CESIUMJS_LOCAL_3D_FIXTURE=true npm run activation:cesiumjs-local-3d-fixture -- --execute',
    allowedWhenConfirmed: [
      'generate synthetic Phase 50B-style 3D planning data',
      'copy the local Cesium Build/Cesium runtime into a temporary fixture directory',
      'serve a temporary 127.0.0.1 local fixture',
      'render generated point, polyline, polygon, and cylinder entities in CesiumJS',
      'launch Playwright Chromium only against the local fixture',
      'capture a 1280x720 local/offline screenshot',
      'run Sharp only on the Phase 50E screenshot',
      'upload private Phase 50E artifacts',
    ],
    blockedAlways: [
      'Cesium ion',
      'Cesium ion tokens',
      'live terrain',
      'live imagery',
      '3D Tiles',
      'live tiles',
      'public OSM tiles',
      'Mapbox provider',
      'Google Maps provider',
      'geocoding APIs',
      'routing APIs',
      'paid map providers',
      'deck.gl runtime in Phase 50E',
      'D3 runtime',
      'Three.js runtime',
      'PMTiles',
      'tile servers',
      'public artifacts',
      'signed URLs as source of truth',
      'production',
      'external beta',
      'paid production',
      'broad media',
    ],
  }
}
