import type { QwenRuntimeAdapterScenario } from '../../types'

const seeds: Array<[
  title: string,
  category: string,
  expectedStatus: QwenRuntimeAdapterScenario['expectedStatus'],
  fallbackExpected: boolean,
  qwenCallAllowed: boolean,
]> = [
  ['Runtime config loads symbolic references', 'config', 'ready_for_secret_resolution', false, true],
  ['Explicit beta flag missing blocks runtime', 'config', 'blocked_missing_beta_flag', true, false],
  ['Missing API key secret reference blocks runtime', 'config', 'blocked_missing_secret_reference', true, false],
  ['Missing Google Cloud project blocks runtime', 'config', 'blocked_missing_project', true, false],
  ['Missing base URL blocks runtime', 'config', 'blocked_missing_base_url', true, false],
  ['Missing model ID blocks runtime', 'config', 'blocked_missing_model_id', true, false],
  ['OpenAI-compatible transport selected', 'config', 'ready_for_provider_call', false, true],
  ['Generic JSON transport selected', 'config', 'ready_for_provider_call', false, true],
  ['Secret resolver resolves value without printing it', 'secret_manager', 'resolved_no_print', false, true],
  ['Secret resolver redacts diagnostics', 'secret_manager', 'resolved_no_print', false, true],
  ['Secret resolver blocks missing project', 'secret_manager', 'blocked_missing_project', true, false],
  ['Secret resolver blocks missing reference', 'secret_manager', 'blocked_missing_secret_reference', true, false],
  ['Secret resolver failure uses fallback', 'secret_manager', 'failed_redacted', true, false],
  ['Provider config validates Qwen provider', 'provider', 'ready_for_provider_call', false, true],
  ['Qwen transport builds request', 'transport', 'request_built', false, true],
  ['Qwen transport redacts authorization', 'transport', 'request_built', false, true],
  ['Qwen transport handles timeout', 'transport', 'timeout', true, true],
  ['Qwen transport handles provider error', 'transport', 'failed', true, true],
  ['Qwen transport handles invalid JSON', 'transport', 'invalid_json', true, true],
  ['Qwen transport handles empty response', 'transport', 'empty_response', true, true],
  ['Qwen transport handles rate limit', 'transport', 'rate_limited', true, true],
  ['Structured response validates valid B-roll output', 'validation', 'valid', false, true],
  ['Structured response validates clarification output', 'validation', 'valid', false, true],
  ['Structured response validates suggestion output', 'validation', 'valid', false, true],
  ['Structured response rejects missing assistantMessage', 'validation', 'invalid_missing_field', true, true],
  ['Structured response rejects unsupported action', 'validation', 'invalid_unsupported_action', true, true],
  ['Structured response rejects unsafe status', 'validation', 'invalid_unsupported_status', true, true],
  ['Structured response rejects non-array plannerHints', 'validation', 'invalid_array_field', true, true],
  ['Structured response rejects unsafe copy instruction', 'validation', 'invalid_unsafe_copy_instruction', true, true],
  ['Marker chat prompt includes marker context', 'prompt', 'ready_for_provider_call', false, true],
  ['Marker chat prompt includes attachment labels only', 'prompt', 'ready_for_provider_call', false, true],
  ['Marker chat prompt excludes file bytes', 'prompt', 'ready_for_provider_call', false, true],
  ['Marker chat prompt excludes secret values', 'prompt', 'ready_for_provider_call', false, true],
  ['Marker chat bridge maps add_broll', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge maps keep original audio', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge maps needs_asset', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge maps needs_clarification', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge maps doNotCopyNotes', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge saves assistant message', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge saves intent', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge saves confirmation', 'bridge', 'provider_response_valid', false, true],
  ['Marker chat bridge updates marker status', 'bridge', 'provider_response_valid', false, true],
  ['Runtime disabled uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, false],
  ['Secret unavailable uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, false],
  ['Provider timeout uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, true],
  ['Invalid response uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, true],
  ['Unsafe response uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, true],
  ['Rate limit uses deterministic fallback', 'fallback', 'deterministic_fallback_used', true, true],
  ['Usage estimate generated', 'usage', 'provider_response_valid', false, true],
  ['Provider usage stored if available', 'usage', 'provider_response_valid', false, true],
  ['Credits not reserved', 'safety', 'provider_response_valid', false, true],
  ['Credits not spent', 'safety', 'provider_response_valid', false, true],
  ['No render job created', 'safety', 'provider_response_valid', false, true],
  ['No worker job created', 'safety', 'provider_response_valid', false, true],
  ['No upload occurs', 'safety', 'provider_response_valid', false, true],
  ['No file bytes read', 'safety', 'provider_response_valid', false, true],
  ['No URL fetched', 'safety', 'provider_response_valid', false, true],
  ['No sound runtime invoked', 'safety', 'provider_response_valid', false, true],
  ['No DeepSeek call made', 'safety', 'provider_response_valid', false, true],
  ['Frontend does not import qwen runtime', 'frontend_boundary', 'ready_for_provider_call', false, true],
  ['Secret values absent from public payload', 'redaction', 'resolved_no_print', false, true],
  ['Secret values absent from logs', 'redaction', 'resolved_no_print', false, true],
  ['Redaction catches bearer token', 'redaction', 'resolved_no_print', false, true],
  ['Redaction catches long token', 'redaction', 'resolved_no_print', false, true],
  ['Redaction catches sk-like token', 'redaction', 'resolved_no_print', false, true],
  ['Qwen real smoke can run when runtime config present', 'smoke', 'ready_for_provider_call', false, true],
  ['Qwen real smoke fails safely when config missing', 'smoke', 'blocked_missing_beta_flag', true, false],
  ['Marker Chat beta route works with fallback when provider unavailable', 'route', 'deterministic_fallback_used', true, false],
  ['Marker Chat beta route works with Qwen when provider available', 'route', 'provider_response_valid', false, true],
  ['Qwen answer does not apply markers to plan', 'safety', 'provider_response_valid', false, true],
  ['Qwen answer does not run planner', 'safety', 'provider_response_valid', false, true],
  ['Qwen answer does not start media processing', 'safety', 'provider_response_valid', false, true],
  ['Qwen answer does not start credits', 'safety', 'provider_response_valid', false, true],
  ['Qwen response stored only after validation', 'validation', 'valid', false, true],
  ['Failed validation does not save unsafe output', 'validation', 'invalid_unsafe_copy_instruction', true, true],
  ['Status docs mention beta enabled path', 'docs', 'ready_for_provider_call', false, true],
  ['Docs mention server-only path', 'docs', 'ready_for_provider_call', false, true],
  ['Docs mention no frontend secrets', 'docs', 'ready_for_provider_call', false, true],
  ['Docs mention fallback', 'docs', 'deterministic_fallback_used', true, false],
  ['Docs mention no render/workers/credits', 'docs', 'ready_for_provider_call', false, true],
  ['Boundary smoke passes', 'smoke', 'ready_for_provider_call', false, true],
  ['Real provider smoke passes or reports gated config missing clearly', 'smoke', 'blocked_missing_beta_flag', true, false],
  ['No Supabase command run', 'safety', 'ready_for_provider_call', false, true],
]

export const MOCK_QWEN_RUNTIME_BETA_SCENARIOS: QwenRuntimeAdapterScenario[] = seeds.map(([
  title,
  category,
  expectedStatus,
  fallbackExpected,
  qwenCallAllowed,
], index) => ({
  id: `qwen-runtime-beta-${String(index + 1).padStart(2, '0')}`,
  title,
  category,
  expectedStatus,
  fallbackExpected,
  qwenCallAllowed,
  productionSideEffectsExpected: false,
}))
