import type {
  CreditLifecycleSource,
  CreditRuntimeGuardSource,
} from './credit-ui-adapter'
import type {
  CreditPackDefinition,
  CreditEstimateLineItemType,
  CreditReservationLineItemRecord,
  CreditReservationWalletBalance,
  CreditSettlementRecord,
  EditCreditCostSummary,
  EditCreditEstimatePreview,
  ExportCreditGateResult,
  ReserveMaxEstimateCreditsResponse,
  SettleCreditReservationResponse,
  StripeBillingRuntimeConfig,
  StripeBillingSafetyFlags,
  StripeConfigStatusResponse,
  StripeLiveReadinessResponse,
  StripeTestReadinessResponse,
} from '../types'

const now = '2026-07-01T12:00:00.000Z'

export const mockCreditUIPacks: readonly CreditPackDefinition[] = [
  pack('credits_100_usd_10', '100 credits = $10', 100, 1000),
  pack('credits_250_usd_25', '250 credits = $25', 250, 2500),
  pack('credits_500_usd_50', '500 credits = $50', 500, 5000),
  pack('credits_1000_usd_100', '1,000 credits = $100', 1000, 10000),
  pack('credits_2500_usd_250', '2,500 credits = $250', 2500, 25000),
]

export function createMockCreditLifecycleScenario(): CreditLifecycleSource {
  const walletBalance: CreditReservationWalletBalance = {
    availableCredits: 120,
    creditWalletId: 'wallet_credit_ui_demo',
    refundedCredits: 0,
    reservedCredits: 200,
    spentCredits: 160,
    userId: 'user_credit_ui_demo',
    walletType: 'personal',
    workspaceId: 'workspace_credit_ui_demo',
  }
  const estimatePreview = createEstimatePreview()
  const reservationResult = createReservationResult(walletBalance)
  const settlementResult = createSettlementResult()
  const exportGate = createExportGate()

  return {
    creditPacks: mockCreditUIPacks,
    estimatePreview,
    exportGate,
    outstandingCredits: exportGate.outstandingCredits,
    purchasedCredits: 100,
    recommendedPackId: 'credits_250_usd_25',
    reservationResult,
    revisionAction: {
      actionRequiredMessage: 'This edit is paused because it may exceed the credit amount you approved. No extra paid work will continue until you approve the revised estimate or choose a lower-cost option.',
      actionRequiredTitle: 'Action required: revised credit estimate needed',
      additionalExpectedCredits: 34,
      additionalHighCredits: 60,
      additionalLowCredits: 18,
      approvedMaxCredits: 200,
      createdAt: now,
      creditEstimateId: 'estimate_credit_ui_demo',
      creditReservationId: 'reservation_credit_ui_demo',
      editComputeLevel: 'premium',
      id: 'revision_action_credit_ui_demo',
      idempotencyKey: 'credit-ui-revision-action',
      metadata: { mockOnly: true },
      newMaximumEstimatedCredits: 260,
      pauseReason: 'projected_overage',
      projectId: 'project_credit_ui_demo',
      reasonSummary: 'Projected high-cost tool usage may exceed the approved maximum hold.',
      status: 'action_required',
      updatedAt: now,
      usedOrCommittedCredits: 188,
      userOptions: [
        { action: 'approve_and_continue', id: 'approve-and-continue', label: 'Approve & Continue' },
        { action: 'choose_lower_cost_option', id: 'choose-lower-cost', label: 'Choose Lower-Cost Option' },
        { action: 'cancel_extra_work', id: 'cancel-extra-work', label: 'Cancel Extra Work' },
      ],
      workspaceId: 'workspace_credit_ui_demo',
    },
    runtimeGuard: createRuntimeGuard(),
    settlementResult,
    stripeConfig: createStripeConfigStatus('test'),
    stripeLiveReadiness: createStripeLiveReadiness(),
    stripeTestReadiness: createStripeTestReadiness(),
    topUpNextSuggestedAction: 'retry_export_gate',
    topUpRequiredCredits: exportGate.outstandingCredits,
    walletBalance,
    weeklyBonusCredits: 100,
  }
}

function createEstimatePreview(): EditCreditEstimatePreview {
  return {
    estimate: {
      approvedAt: now,
      availableCreditsSnapshot: 120,
      createdAt: now,
      editPlanId: 'edit_plan_credit_ui_demo',
      estimatePayload: { mockOnly: true },
      id: 'estimate_credit_ui_demo',
      lineItems: [
        estimateLine('line_tool_cost', 'real_motion', 'premium_signature_edit', 'Visual generation and motion planning', 120),
        estimateLine('line_service_fee', 'other', 'admin', 'ReEditPro service/edit fee', 80),
      ],
      maximumEstimatedCredits: 200,
      minimumEstimatedCredits: 120,
      projectId: 'project_credit_ui_demo',
      purchasedCreditsSnapshot: 100,
      reservedCreditsSnapshot: 0,
      shownToUserAt: now,
      status: 'approved',
      totalEstimatedCredits: 160,
      updatedAt: now,
      weeklyBonusCreditsSnapshot: 100,
      workspaceId: 'workspace_credit_ui_demo',
    },
    idempotencyStatus: 'created',
    lowerCostOptions: [
      {
        action: 'downgrade_product_edit_level',
        affectedToolIds: ['video-provider'],
        description: 'Use Normal edit depth and reduce high-risk visual generation.',
        estimatedSavingsCredits: 45,
        id: 'lower_normal',
        label: 'Switch to Normal edit',
        targetProductEditLevel: 'normal',
      },
      {
        action: 'lower_render_quality',
        affectedToolIds: ['remotion'],
        description: 'Keep the plan but use lower render quality for preview-heavy passes.',
        estimatedSavingsCredits: 20,
        id: 'lower_render',
        label: 'Reduce render quality',
      },
    ],
    safetyFlags: {
      creditsReservedOrSpent: false,
      estimateOnly: true,
      ledgerWritten: false,
      providerCalled: false,
      renderOrExportStarted: false,
      reservationMutated: false,
      serviceFeeIncludedInToolCosts: false,
      supabaseWritten: false,
      walletMutated: false,
      workerRun: false,
    },
    serviceFeeEstimate: {
      creditPolicyVersion: 'rp-creditpolicy-01',
      customEstimateRequired: false,
      durationBucket: '0_5_min',
      expectedServiceFeeCredits: 50,
      expectedToolCostCredits: 110,
      finalChargeFormula: 'actual billable tool cost + ReEditPro service/edit fee',
      highServiceFeeCredits: 80,
      highToolCostCredits: 120,
      lowServiceFeeCredits: 30,
      lowToolCostCredits: 90,
      serviceFeePolicyVersion: 'rp-creditpolicy-01-service-fee',
    },
    summary: {
      canProceedToReservation: false,
      customEstimateRequired: false,
      editPlanId: 'edit_plan_credit_ui_demo',
      expectedServiceFeeCredits: 50,
      expectedToolCostCredits: 110,
      finalVideoDurationSeconds: 180,
      highServiceFeeCredits: 80,
      highToolCostCredits: 120,
      lowServiceFeeCredits: 30,
      lowToolCostCredits: 90,
      maximumEstimatedCredits: 200,
      minimumEstimatedCredits: 120,
      plannedToolCount: 3,
      productEditLevel: 'premium',
      projectId: 'project_credit_ui_demo',
      readinessStatus: 'needs_top_up',
      requiredHoldCredits: 200,
      requiredTopUpCredits: 80,
      totalEstimatedCredits: 160,
      userFacingLines: [
        { credits: 120, description: 'High estimate for billable tool usage.', label: 'Actual billable tool cost estimate' },
        { credits: 80, description: 'Separate ReEditPro service/edit fee estimate.', label: 'ReEditPro service/edit fee' },
      ],
      workspaceId: 'workspace_credit_ui_demo',
    },
    toolEstimates: [
      {
        expectedCredits: 70,
        expectedInternalCostCents: 650,
        highCredits: 90,
        highInternalCostCents: 880,
        lineItemType: 'real_motion',
        lowCredits: 45,
        lowInternalCostCents: 440,
        owner: 'provider',
        prerequisiteStatus: 'ready',
        pricingSnapshot: { mockOnly: true },
        productEditLevel: 'premium',
        qualityLevel: 'premium',
        rateCardVersion: 'tool-metering-v1-2026-06-26',
        serviceFeeIncluded: false,
        toolComputeLevel: 'premium',
        toolId: 'video-provider',
        toolName: 'Video Provider',
        usageCategory: 'premium_signature_edit',
        warnings: [],
      },
    ],
    topUpSummary: {
      availableCreditsSnapshot: 120,
      canProceedToReservation: false,
      purchasedCreditsSnapshot: 100,
      readinessStatus: 'needs_top_up',
      requiredHoldCredits: 200,
      requiredTopUpCredits: 80,
      reservedCreditsSnapshot: 0,
      weeklyBonusCreditsSnapshot: 100,
    },
    warnings: ['Mock fixture only; no estimate route was called.'],
  }
}

function createReservationResult(walletBalance: CreditReservationWalletBalance): ReserveMaxEstimateCreditsResponse {
  const lineItems = [reservationLine('reservation_line_tool', 'premium_signature_edit', 120), reservationLine('reservation_line_service', 'admin', 80)]
  return {
    availableCreditsAfterReservation: 0,
    availableCreditsBeforeReservation: 120,
    creditWallet: {
      cachedAvailableCredits: walletBalance.availableCredits,
      cachedRefundedCredits: walletBalance.refundedCredits,
      cachedReservedCredits: walletBalance.reservedCredits,
      cachedSpentCredits: walletBalance.spentCredits,
      createdAt: now,
      currencyCode: 'CREDITS',
      id: walletBalance.creditWalletId,
      name: 'Personal mock wallet',
      updatedAt: now,
      userId: walletBalance.userId,
      walletType: 'personal',
      workspaceId: walletBalance.workspaceId,
    },
    idempotencyStatus: 'created',
    requiredHoldCredits: 200,
    requiredTopUpCredits: 80,
    reservation: {
      createdAt: now,
      creditApprovalId: 'approval_credit_ui_demo',
      creditEstimateId: 'estimate_credit_ui_demo',
      creditWalletId: walletBalance.creditWalletId,
      editPlanId: 'edit_plan_credit_ui_demo',
      id: 'reservation_credit_ui_demo',
      idempotencyKey: 'credit-ui-reservation',
      projectId: 'project_credit_ui_demo',
      refundedCredits: 0,
      releasedCredits: 0,
      reservedAt: now,
      reservedCredits: 200,
      reservationReason: 'max_estimate_hold',
      spentCredits: 0,
      status: 'reserved',
      updatedAt: now,
      workspaceId: walletBalance.workspaceId,
    },
    reservationLineItems: lineItems,
    reservedCreditsAfterReservation: 200,
    safetyFlags: {
      checkoutOrTopUpStarted: false,
      creditsReserved: true,
      creditsSpent: false,
      exportUnlocked: false,
      ledgerWritten: false,
      mockOnly: true,
      providerCalled: false,
      renderOrExportStarted: false,
      requiredHoldUsesMaximumEstimate: true,
      reservationMutated: true,
      serviceFeeIncludedInToolCosts: false,
      settlementExecuted: false,
      supabaseWritten: false,
      walletMutated: true,
      workerRun: false,
    },
    status: 'insufficient_credits',
    userFacingMessage: 'Action required: add credits to continue',
    walletBalance,
    warnings: ['Fixture shows insufficient balance before a later mock top-up.'],
  }
}

function createRuntimeGuard(): CreditRuntimeGuardSource {
  return {
    approvedReservedCredits: 200,
    committedPendingHighCredits: 22,
    currentBillableToolCredits: 166,
    nextToolHighCredits: 60,
    projectedFinalCredits: 260,
    projectedServiceFeeCredits: 72,
    projectedToolCredits: 188,
    status: 'requires_revised_estimate',
    warnings: ['No extra paid work continues until the revised credit action is resolved.'],
  }
}

function createSettlementResult(): SettleCreditReservationResponse {
  const settlement = createSettlementRecord()
  const summary = createSettlementSummary(settlement)
  const lineItems = [
    { ...reservationLine('spent_tool_line', 'premium_signature_edit', 120), spentCredits: 96, releasedCredits: 24 },
    { ...reservationLine('spent_service_line', 'admin', 80), spentCredits: 64, releasedCredits: 16 },
  ]

  return {
    idempotencyStatus: 'created',
    reservation: {
      createdAt: now,
      creditApprovalId: 'approval_credit_ui_demo',
      creditEstimateId: settlement.creditEstimateId,
      creditWalletId: 'wallet_credit_ui_demo',
      editPlanId: settlement.editPlanId ?? undefined,
      id: settlement.creditReservationId,
      idempotencyKey: 'credit-ui-settlement-reservation',
      projectId: settlement.projectId,
      refundedCredits: 0,
      releasedCredits: 40,
      reservedAt: now,
      reservedCredits: 200,
      spentAt: now,
      spentCredits: 160,
      status: 'spent',
      updatedAt: now,
      workspaceId: settlement.workspaceId,
    },
    reservationLineItems: lineItems,
    safetyFlags: {
      checkoutOrTopUpStarted: false,
      creditsRefunded: false,
      creditsReleased: true,
      creditsSpent: true,
      exportUnlocked: false,
      ledgerWritten: false,
      mockOnly: true,
      productionSettlementWritten: false,
      productionWalletMutated: false,
      providerCalled: false,
      renderOrExportStarted: false,
      reservationMutated: true,
      serviceFeeIncludedInToolCosts: false,
      supabaseWritten: false,
      walletMutated: true,
      workerRun: false,
    },
    settlement,
    status: 'settled_with_absorbed_overage',
    summary,
    userFacingMessage: 'Final credit charge settled',
    userFacingTitle: 'Final credit charge settled',
    walletBalance: {
      availableCredits: 40,
      creditWalletId: 'wallet_credit_ui_demo',
      refundedCredits: 0,
      reservedCredits: 0,
      spentCredits: 160,
      userId: 'user_credit_ui_demo',
      walletType: 'personal',
      workspaceId: 'workspace_credit_ui_demo',
    },
    warnings: ['Non-billable internal cost is shown as absorbed and not charged to the user.'],
  }
}

function createExportGate(): ExportCreditGateResult {
  return {
    absorbedOverageCredits: 0,
    canExport: false,
    creditReservationId: 'reservation_credit_ui_demo',
    creditSettlementId: 'settlement_credit_ui_export_lock',
    exportLock: {
      actionRequiredMessage: 'Your edit is ready, but 30 approved credits are still needed before export can be rechecked.',
      actionRequiredTitle: 'Action required: add credits to export',
      createdAt: now,
      creditReservationId: 'reservation_credit_ui_demo',
      creditSettlementId: 'settlement_credit_ui_export_lock',
      finalChargeCredits: 230,
      id: 'export_lock_credit_ui_demo',
      idempotencyKey: 'credit-ui-export-lock',
      lockReason: 'approved_but_unfunded',
      metadata: { mockOnly: true },
      outstandingCredits: 30,
      projectId: 'project_credit_ui_demo',
      reservedCredits: 200,
      status: 'locked',
      updatedAt: now,
      workspaceId: 'workspace_credit_ui_demo',
    },
    finalChargeCredits: 230,
    idempotencyStatus: 'created',
    metadata: { mockOnly: true },
    outstandingCredits: 30,
    releasedCredits: 0,
    requiredAction: 'add_credits_to_export',
    reservedCredits: 200,
    safetyFlags: {
      checkoutOrTopUpStarted: false,
      creditsRefunded: false,
      creditsReleased: false,
      creditsSpent: false,
      exportUnlocked: false,
      ledgerWritten: false,
      mockExportLockWritten: true,
      mockOnly: true,
      productionPersistenceWritten: false,
      productionWalletMutated: false,
      providerCalled: false,
      readOnly: false,
      renderOrExportStarted: false,
      reservationMutated: false,
      serviceFeeIncludedInToolCosts: false,
      supabaseWritten: false,
      walletMutated: false,
      workerRun: false,
    },
    settlementStatus: 'requires_top_up_before_export',
    status: 'export_locked_top_up_required',
    userFacingMessage: 'Your edit is ready, but 30 approved credits are still needed before export can be rechecked.',
    userFacingTitle: 'Action required: add credits to export',
    warnings: ['Display-only export lock; no real export readiness changed.'],
  }
}

function createStripeConfigStatus(mode: StripeBillingRuntimeConfig['mode']): StripeConfigStatusResponse {
  return {
    config: createStripeRuntimeConfig(mode),
    safetyFlags: stripeSafety(),
    status: mode === 'test' ? 'test_configured' : mode === 'live' ? 'live_configured' : 'billing_disabled',
    validation: { errors: [], ok: true, warnings: [] },
    warnings: ['Stripe billing status is fixture-only in this UI.'],
  }
}

function createStripeTestReadiness(): StripeTestReadinessResponse {
  return {
    canRunTestMode: true,
    checks: [{ id: 'test_mode', label: 'Test mode configured', message: 'Test mode is ready in fixture data.', passed: true }],
    config: createStripeRuntimeConfig('test'),
    safetyFlags: stripeSafety(),
    status: 'ready',
    stripeMode: 'test',
    warnings: ['No real test call is made by the UI fixture.'],
  }
}

function createStripeLiveReadiness(): StripeLiveReadinessResponse {
  return {
    appEnvironment: 'production',
    canCreateLiveCheckoutSessions: false,
    canCreateLivePaymentIntents: false,
    canCreateLiveSetupIntents: false,
    canEnableLiveMode: true,
    canGrantLiveCredits: false,
    canProcessLiveWebhooks: false,
    checks: [
      { id: 'mode_live', label: 'Stripe mode live', message: 'Live readiness can pass structurally.', passed: true, status: 'passed' },
      { id: 'live_checkout_disabled', label: 'Live Checkout Sessions disabled', message: 'Live Checkout remains blocked.', passed: true, status: 'blocked' },
    ],
    config: createStripeRuntimeConfig('live'),
    liveModeAllowed: true,
    liveModeRequiresManualApproval: true,
    manualApprovalPresent: true,
    noChargeDryRun: true,
    safeConfigSummary: {
      canCreateLiveCheckoutSessions: false,
      canCreateLivePaymentIntents: false,
      canCreateLiveSetupIntents: false,
      canGrantLiveCredits: false,
      canProcessLiveWebhooks: false,
      noChargeDryRun: true,
      rawSecretValuesPresent: false,
    },
    safetyFlags: stripeSafety(),
    secretSource: 'google_secret_manager',
    status: 'ready_no_charge',
    stripeMode: 'live',
    webhookEndpointMode: 'live',
    warnings: ['ready_no_charge does not enable payment processing.'],
  }
}

function createStripeRuntimeConfig(mode: StripeBillingRuntimeConfig['mode']): StripeBillingRuntimeConfig {
  return {
    environment: mode === 'live' ? 'production' : 'development',
    liveModeAllowed: mode === 'live',
    liveModeRequiresManualApproval: mode === 'live',
    mockOnly: mode !== 'live',
    mode,
    publishableKeyMode: mode === 'live' ? 'live' : mode === 'test' ? 'test' : 'disabled',
    publishableKeySecretName: mode === 'disabled' ? null : `reeditpro-${mode}-publishable-ref`,
    restrictedKeyPreferred: true,
    secretKeySecretName: mode === 'disabled' ? null : `reeditpro-${mode}-api-ref`,
    secretReferences: {
      livePublishableKeySecretName: 'reeditpro-live-publishable-ref',
      liveSecretKeySecretName: 'reeditpro-live-api-ref',
      liveWebhookSigningSecretName: 'reeditpro-live-webhook-ref',
      testPublishableKeySecretName: 'reeditpro-test-publishable-ref',
      testSecretKeySecretName: 'reeditpro-test-api-ref',
      testWebhookSigningSecretName: 'reeditpro-test-webhook-ref',
    },
    secretSource: mode === 'disabled' ? 'disabled' : 'google_secret_manager',
    testModeRealCallsAllowed: false,
    warnings: [],
    webhookEndpointMode: mode === 'live' ? 'live' : mode === 'test' ? 'test' : 'disabled',
    webhookSigningSecretName: mode === 'disabled' ? null : `reeditpro-${mode}-webhook-ref`,
  }
}

function stripeSafety(): StripeBillingSafetyFlags {
  return {
    checkoutSessionCreated: false,
    creditsGranted: false,
    ledgerWritten: false,
    liveStripeCallAttempted: false,
    mockOnly: true,
    paymentIntentCreated: false,
    providerCalled: false,
    renderOrExportStarted: false,
    secretValueReturned: false,
    setupIntentCreated: false,
    stripeCallAttempted: false,
    supabaseWritten: false,
    walletMutated: false,
  }
}

function createSettlementRecord(): CreditSettlementRecord {
  return {
    absorbedOverageCredits: 30,
    actualToolCostCents: 1300,
    actualToolCostCredits: 130,
    billableToolEventCount: 3,
    createdAt: now,
    creditEstimateId: 'estimate_credit_ui_demo',
    creditPolicyVersion: 'rp-creditpolicy-01',
    creditReservationId: 'reservation_credit_ui_demo',
    editComputeLevel: 'premium',
    editPlanId: 'edit_plan_credit_ui_demo',
    finalChargeCredits: 160,
    finalVideoDurationSeconds: 180,
    id: 'settlement_credit_ui_demo',
    idempotencyKey: 'credit-ui-settlement',
    metadata: { mockOnly: true },
    nonBillableToolEventCount: 1,
    outstandingCredits: 0,
    projectId: 'project_credit_ui_demo',
    rateCardVersion: 'tool-metering-v1-2026-06-26',
    receiptPayload: { mockOnly: true },
    reeditproServiceFeeCredits: 60,
    releasedCredits: 40,
    reservedCredits: 200,
    serviceFeePolicyVersion: 'rp-creditpolicy-01-service-fee',
    settledAt: now,
    settlementPayload: { computedFinalChargeCredits: 190, mockOnly: true },
    settlementReason: 'provider_variance_absorbed',
    status: 'settled_with_absorbed_overage',
    toolCostEventIds: ['tool_cost_credit_ui_1', 'tool_cost_credit_ui_2'],
    updatedAt: now,
    workspaceId: 'workspace_credit_ui_demo',
  }
}

function createSettlementSummary(settlement: CreditSettlementRecord): EditCreditCostSummary {
  return {
    absorbedOverageCredits: settlement.absorbedOverageCredits,
    actualToolCostCents: settlement.actualToolCostCents,
    actualToolCostCredits: settlement.actualToolCostCredits,
    byUsageCategory: {
      premium_signature_edit: {
        actualInternalCostCents: 900,
        billableEventCount: 2,
        credits: 90,
        eventCount: 2,
        nonBillableEventCount: 0,
      },
      rendering: {
        actualInternalCostCents: 400,
        billableEventCount: 1,
        credits: 40,
        eventCount: 2,
        nonBillableEventCount: 1,
      },
    },
    creditEstimateId: settlement.creditEstimateId,
    creditReservationId: settlement.creditReservationId,
    creditSettlementId: settlement.id,
    editComputeLevel: settlement.editComputeLevel,
    editPlanId: settlement.editPlanId,
    finalChargeCredits: settlement.finalChargeCredits,
    finalVideoDurationSeconds: settlement.finalVideoDurationSeconds,
    nonBillableAbsorbed: {
      actualInternalCostCents: 120,
      credits: 12,
      eventCount: 1,
      reasons: ['provider_retry_absorbed'],
    },
    outstandingCredits: settlement.outstandingCredits,
    projectId: settlement.projectId,
    reeditproServiceFeeCredits: settlement.reeditproServiceFeeCredits,
    releasedCredits: settlement.releasedCredits,
    reservedCredits: settlement.reservedCredits,
    userFacingLines: [
      { credits: settlement.actualToolCostCredits, description: 'Actual billable tool usage.', label: 'Actual tool cost' },
      { credits: settlement.reeditproServiceFeeCredits, description: 'Separate ReEditPro service/edit fee.', label: 'ReEditPro service fee' },
      { credits: settlement.releasedCredits, description: 'Unused reserved credits returned.', label: 'Returned credits' },
    ],
    warnings: ['Final charge is capped by approved hold in absorbed-overage fixture.'],
    workspaceId: settlement.workspaceId,
  }
}

function pack(id: string, label: string, credits: number, priceCents: number): CreditPackDefinition {
  return {
    credits,
    currency: 'USD',
    id,
    isActive: true,
    label,
    metadata: { mockOnly: true },
    priceCents,
    retailValueCents: priceCents,
  }
}

function estimateLine(
  id: string,
  lineItemType: CreditEstimateLineItemType,
  usageCategory: 'premium_signature_edit' | 'admin',
  label: string,
  estimatedCredits: number,
) {
  return {
    createdAt: now,
    creditEstimateId: 'estimate_credit_ui_demo',
    description: label,
    estimatedCredits,
    id,
    isOptional: false,
    isPremium: usageCategory !== 'admin',
    label,
    lineItemType,
    linePayload: { mockOnly: true },
    projectId: 'project_credit_ui_demo',
    requiresUserApproval: true,
    usageCategory,
    workspaceId: 'workspace_credit_ui_demo',
  }
}

function reservationLine(id: string, usageCategory: 'premium_signature_edit' | 'admin', reservedCredits: number): CreditReservationLineItemRecord {
  return {
    createdAt: now,
    creditReservationId: 'reservation_credit_ui_demo',
    id,
    linePayload: { mockOnly: true },
    projectId: 'project_credit_ui_demo',
    refundedCredits: 0,
    releasedCredits: 0,
    reservedCredits,
    spentCredits: 0,
    updatedAt: now,
    usageCategory,
    workspaceId: 'workspace_credit_ui_demo',
  }
}
