import type {
  AudioLicenseProvenanceRecord,
  AudioUsageRecord,
  GeneratedMusicTrackRecord,
  LyriaPromptPlanRecord,
  LyriaPromptSegment,
  MusicContextAnalysisRecord,
  MusicCueRecord,
  MusicCueSheetRecord,
  MusicLanguageContextRecord,
  MusicLibraryCandidateRecord,
  MusicMixPlanRecord,
  MusicQAReportRecord,
  MusicStyleTaxonomyRecord,
  MusicTrackAnalysisRecord,
  ReferenceMusicDNARecord,
  SfxLibraryAssetRecord,
} from '../types'
import { LYRIA_PRO_FUTURE_MODEL_NAME } from '../types'

export const mockAudioMusicTimestamp = '2026-05-16T12:00:00.000Z'

const projectId = 'project_lake_como_style_001'
const editPlanId = 'edit_plan_lake_como_001'
const cueSheetId = 'music_cue_sheet_lake_como_001'
const musicContextAnalysisId = 'music_context_lake_como_001'
const referenceMusicDnaId = 'reference_music_dna_lake_como_001'
const licenseProvenanceId = 'license_lyria_project_asset_001'

export const mockMusicStyleTaxonomyRecords: MusicStyleTaxonomyRecord[] = [
  {
    id: 'music_taxonomy_french_lifestyle_pop',
    taxonomyKey: 'french_lifestyle_pop',
    genreFamily: 'french_pop',
    displayName: 'French Lifestyle Pop',
    description: 'Stylish French pop and electro-lounge influence for non-speaking lifestyle montage moments.',
    commonMoods: ['stylish', 'relaxed', 'premium'],
    commonInstruments: ['warm guitar', 'soft bass', 'tasteful electronic lounge rhythm', 'airy vocal texture'],
    goodForSceneTypes: ['lifestyle', 'vacation', 'travel_montage', 'city_walk'],
    avoidForSceneTypes: ['dialogue', 'education', 'faith_reflective'],
    speechSafetyDefault: 'montage_only',
    cultureRegion: 'france',
    examplePromptPhrases: [
      'French indie-pop inspired montage cue',
      'tasteful electronic lounge rhythm',
      'airy modern French vocal texture only in non-speaking moments',
    ],
    avoidPromptPhrases: ['accordion cliche', 'imitate an existing French pop song', 'lead vocals under dialogue'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_italian_luxury_travel',
    taxonomyKey: 'italian_luxury_travel',
    genreFamily: 'italian_inspired_pop',
    displayName: 'Italian Luxury Travel',
    description: 'Elegant European travel music for scenic movement, villas, boats, and premium vacation pacing.',
    commonMoods: ['luxury', 'romantic', 'warm'],
    commonInstruments: ['warm acoustic guitar', 'gentle piano', 'brushed drums', 'elegant bass'],
    goodForSceneTypes: ['vacation', 'travel_montage', 'boat_movement', 'luxury_showcase'],
    avoidForSceneTypes: ['talking_head', 'education'],
    speechSafetyDefault: 'needs_ducking',
    cultureRegion: 'european_luxury',
    examplePromptPhrases: ['Italian/elegant European luxury travel montage cue', 'premium lifestyle feel'],
    avoidPromptPhrases: ['aggressive EDM drops', 'tourist stereotype', 'copy reference melody'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_instrumental_dialogue_bed',
    taxonomyKey: 'instrumental_dialogue_bed',
    genreFamily: 'ambient',
    displayName: 'Instrumental Dialogue Bed',
    description: 'Voice-first instrumental bed with clean midrange space and predictable ducking behavior.',
    commonMoods: ['calm', 'clean', 'premium'],
    commonInstruments: ['soft piano', 'warm pads', 'subtle pulse', 'light texture'],
    goodForSceneTypes: ['dialogue', 'narration', 'talking_head', 'education'],
    avoidForSceneTypes: ['coming_up_teaser', 'fitness'],
    speechSafetyDefault: 'safe_under_voice',
    examplePromptPhrases: ['instrumental-only premium background bed', 'designed to sit under voice'],
    avoidPromptPhrases: ['lyrics', 'lead vocal', 'busy melody', 'heavy bass'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_cinematic_premium_real_estate',
    taxonomyKey: 'cinematic_premium_real_estate',
    genreFamily: 'cinematic',
    displayName: 'Cinematic Premium Real Estate',
    description: 'Soft cinematic polish for walkthroughs where property ambience and voice clarity matter.',
    commonMoods: ['luxury', 'calm', 'premium'],
    commonInstruments: ['soft piano', 'warm pads', 'muted pulse', 'subtle strings'],
    goodForSceneTypes: ['real_estate', 'luxury_showcase', 'ad_sales'],
    avoidForSceneTypes: ['comedy', 'food_social'],
    speechSafetyDefault: 'safe_under_voice',
    examplePromptPhrases: ['calm real estate walkthrough', 'slowly build during the property reveal'],
    avoidPromptPhrases: ['aggressive drums', 'dramatic trailer hits', 'vocals under agent voice'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_faith_reflective',
    taxonomyKey: 'faith_reflective',
    genreFamily: 'faith_reflective',
    displayName: 'Faith Reflective',
    description: 'Respectful reflective music for teaching, testimony, scripture, or pastoral storytelling.',
    commonMoods: ['hopeful', 'emotional', 'inspirational'],
    commonInstruments: ['soft piano', 'warm pads', 'gentle acoustic guitar', 'subtle strings'],
    goodForSceneTypes: ['faith_reflective', 'education', 'narration'],
    avoidForSceneTypes: ['comedy', 'ad_sales'],
    speechSafetyDefault: 'safe_under_voice',
    examplePromptPhrases: ['reflective instrumental bed', 'respectful and voice-first'],
    avoidPromptPhrases: ['performance vocals under teaching', 'overly dramatic swell'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_high_energy_social',
    taxonomyKey: 'high_energy_social',
    genreFamily: 'pop',
    displayName: 'High-Energy Social',
    description: 'Bright social momentum for teasers, reveals, and fast montages without important speech.',
    commonMoods: ['energetic', 'playful', 'stylish'],
    commonInstruments: ['punchy drums', 'bright synths', 'bass hook', 'short vocal texture'],
    goodForSceneTypes: ['coming_up_teaser', 'travel_montage', 'fitness', 'ad_sales'],
    avoidForSceneTypes: ['dialogue', 'talking_head', 'faith_reflective'],
    speechSafetyDefault: 'not_safe_under_voice',
    examplePromptPhrases: ['short teaser peak then drop', 'premium social energy'],
    avoidPromptPhrases: ['full lyrics under speech', 'harsh drums', 'unlicensed hook imitation'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_taxonomy_food_social_warmth',
    taxonomyKey: 'food_social_warmth',
    genreFamily: 'jazz',
    displayName: 'Food/Social Warmth',
    description: 'Warm lounge, acoustic, or light jazz support for meals, friends, conversation, and social texture.',
    commonMoods: ['warm', 'playful', 'relaxed'],
    commonInstruments: ['light percussion', 'muted guitar', 'upright bass', 'soft piano'],
    goodForSceneTypes: ['food_social', 'lifestyle', 'vacation'],
    avoidForSceneTypes: ['fitness', 'ad_sales'],
    speechSafetyDefault: 'needs_ducking',
    examplePromptPhrases: ['warm food and social moment', 'leave room for natural ambience'],
    avoidPromptPhrases: ['loud restaurant fake ambience', 'busy lead melody', 'lyrics over table dialogue'],
    isActive: true,
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockLakeComoReferenceMusicDNA: ReferenceMusicDNARecord = {
  id: referenceMusicDnaId,
  projectId,
  referenceUrl: 'reference-only://lake-como-lifestyle-vacation-style',
  summary:
    'Luxury lifestyle/vacation reference pattern with a coming-up teaser, scenic arrival, dialogue-safe beds, boat movement, food/social warmth, natural ambience, and soft outro resolution.',
  cueBoundaryNotes: [
    'Cue 1: coming-up teaser uses stronger energy before the story settles.',
    'Cue 2: scenic arrival opens space for lake, villa, and travel visuals.',
    'Cue 3: dialogue sections reduce music density and avoid lyrical vocals.',
    'Cue 4: boat and movement montage can carry more rhythmic energy.',
    'Cue 5: food/social section keeps warmth and lets real ambience breathe.',
    'Cue 6: outro resolves softly instead of ending on an abrupt loop.',
  ],
  musicCueCount: 6,
  genreMoodPerCue: [
    'Teaser: stylish, premium, medium-high energy.',
    'Arrival: elegant cinematic travel, medium-low energy.',
    'Dialogue: instrumental premium bed, low energy.',
    'Boat movement: Italian-inspired luxury travel groove, medium energy.',
    'Food/social: warm acoustic or lounge texture, medium-low energy.',
    'Outro: reflective warm resolve, low energy.',
  ],
  lyricsMoments: [
    'Short vocal texture can work in teaser or montage only when there is no important speech.',
    'No lyrical hooks under dialogue, narration, teaching, or group conversation.',
  ],
  instrumentalMoments: [
    'Dialogue bed remains instrumental only.',
    'Scenic breathing moments can use instrumental ambience instead of a full song.',
  ],
  dialogueDuckingBehavior:
    'Music ducks under voice, avoids lead melodies, and leaves ambience/room tone intact where it supports realism.',
  introMusicBehavior: 'Coming-up teaser may hit stronger, then drop into a calmer arrival or dialogue-safe bed.',
  montageMusicBehavior:
    'Montage sections can use more rhythmic, stylish cues with light vocal texture only during non-speaking footage.',
  chapterTitleAudioBehavior:
    'Chapter/title cards can use short music hits or owned SFX accents, never loud effects over speech.',
  outroResolveBehavior: 'Outro should fade or resolve musically, not cut off mid-loop.',
  sfxBehavior: 'Soft whooshes, light hits, and ambient bridges support transitions, title cards, and movement shots.',
  ambienceBehavior:
    'Boat, water, villa, restaurant, and group ambience should be preserved when it adds place and personality.',
  adaptationRules: [
    'Adapt cue structure, energy arcs, and ambience relationship.',
    'Use Italian or European luxury influence only when supported by footage, user intent, or audience.',
    'Keep dialogue and friendship moments voice-first.',
  ],
  doNotCopyRules: [
    'Do not copy the reference track, melody, lyrics, chord progression, or exact arrangement.',
    'Do not force mandolin or tourist stereotypes just because the scene is in Italy.',
    'Do not use vocals under important speech unless the user explicitly requests it.',
  ],
  confidence: 0.88,
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockLifestyleVacationMusicContext: MusicContextAnalysisRecord = {
  id: musicContextAnalysisId,
  projectId,
  editPlanId,
  chatSessionId: 'chat_session_lake_como_001',
  referenceAssetId: 'reference_asset_lake_como_001',
  primarySceneType: 'vacation',
  detectedSceneTypes: ['coming_up_teaser', 'vacation', 'dialogue', 'boat_movement', 'food_social', 'outro'],
  videoTopic: 'Lake Como-style luxury vacation vlog with friends, scenic travel, dialogue, food, and boat moments.',
  settingSummary: 'Lake, villa, boat, restaurant, and group social scenes with premium but casual pacing.',
  locationHints: ['Lake Como', 'Italy', 'villa', 'boat', 'waterfront restaurant'],
  cultureRegions: ['italy', 'european_luxury'],
  spokenLanguages: ['english'],
  audience: 'Lifestyle/vacation viewers who expect polished travel pacing without losing natural personality.',
  platform: 'youtube',
  musicNeedDecision: 'music_needed',
  musicCueCountDecision: 'multi_cue',
  speechPresence: 'mixed_speech_and_montage',
  dialogueHeavy: false,
  montageSectionsDetected: true,
  ambienceImportant: true,
  referenceMusicInfluence: 'moderate_style_dna',
  userMusicInstructions: ['Make it premium, cinematic, lifestyle, and not too dramatic.'],
  avoidMusicInstructions: ['No random background track', 'No lyrics under dialogue', 'Do not copy reference music.'],
  confidence: 0.91,
  notes: [
    'Multi-cue plan is stronger than one full-track bed because scene energy changes often.',
    'Boat, water, and social ambience should support the sense of place.',
  ],
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockItalianLuxuryMusicLanguageContext: MusicLanguageContextRecord = {
  id: 'music_language_context_lake_como_001',
  projectId,
  editPlanId,
  musicContextAnalysisId,
  spokenLanguage: 'english',
  visualLocation: 'Lake Como, Italy',
  cultureRegion: 'european_luxury',
  recommendedLyricLanguagePolicy: 'italian_allowed',
  allowedLyricLanguages: ['english', 'italian'],
  avoidLanguages: [],
  cultureStyleNotes: [
    'Use elegant European luxury travel influence for montage sections.',
    'Allow Italian-inspired warmth in instrumentation without making it a caricature.',
  ],
  stereotypeAvoidanceNotes: [
    'Do not force mandolin, opera, or tourist postcard cues.',
    'Culture signal must come from setting, story, user intent, and reference DNA together.',
  ],
  confidence: 0.86,
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockLakeComoMusicCueSheet: MusicCueSheetRecord = {
  id: cueSheetId,
  projectId,
  editPlanId,
  musicContextAnalysisId,
  cueCountDecision: 'multi_cue',
  summary:
    'Five-cue music strategy: teaser lift, dialogue-safe bed, boat movement montage, food/social warmth, and outro resolve.',
  overallMood: 'premium',
  overallEnergyArc: 'rise_and_resolve',
  usesMultipleCues: true,
  lyricsAllowedSomewhere: true,
  dialogueSafeRequired: true,
  referenceDnaUsed: true,
  approvalRequired: true,
  creditEstimateId: 'credit_estimate_music_lake_como_001',
  status: 'awaiting_approval',
  notes: [
    'Prompt plans must be reviewed before any future Lyria Pro generation.',
    'Lyrics or vocal textures are limited to no-speech montage/teaser/outro moments.',
  ],
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockLakeComoMusicCues: MusicCueRecord[] = [
  {
    id: 'music_cue_lake_como_001_teaser',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    cueOrder: 1,
    cueRole: 'coming_up_teaser',
    sceneType: 'coming_up_teaser',
    startTimeSeconds: 0,
    endTimeSeconds: 12,
    targetDurationSeconds: 12,
    mood: 'stylish',
    genreFamilies: ['pop', 'electronic', 'lifestyle_vlog'],
    energyLevel: 'medium_high',
    energyArc: 'teaser_peak_then_drop',
    cultureRegion: 'european_luxury',
    vocalPolicy: 'vocal_texture_only',
    lyricLanguagePolicy: 'no_lyrics',
    speechSafety: 'intro_outro_only',
    instrumentation: ['tight drums', 'soft synth pulse', 'premium bass', 'short airy vocal texture'],
    bpmTarget: 112,
    referenceInfluence: 'light_style_dna',
    promptGoal: 'Create a stylish teaser lift that previews the trip without copying any reference music.',
    negativePromptGoals: ['no full lyrics', 'no copied melody', 'no harsh EDM drop', 'no vocals under speech'],
    duckingRequired: false,
    loopableNeeded: false,
    creditImpact: 'medium',
    requiresApproval: true,
    status: 'awaiting_approval',
    notes: ['This cue should end cleanly into the calmer arrival or dialogue section.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_cue_lake_como_002_dialogue',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    cueOrder: 2,
    cueRole: 'dialogue_bed',
    sceneType: 'dialogue',
    startTimeSeconds: 12,
    endTimeSeconds: 72,
    targetDurationSeconds: 60,
    mood: 'calm',
    genreFamilies: ['ambient', 'cinematic', 'luxury_lounge'],
    energyLevel: 'low',
    energyArc: 'flat',
    cultureRegion: 'global',
    vocalPolicy: 'instrumental_only',
    lyricLanguagePolicy: 'no_lyrics',
    speechSafety: 'safe_under_voice',
    instrumentation: ['soft piano', 'warm pads', 'subtle pulse'],
    bpmTarget: 82,
    referenceInfluence: 'light_style_dna',
    promptGoal: 'Create a premium instrumental dialogue bed that leaves space for voice and natural ambience.',
    negativePromptGoals: ['no lyrics', 'no lead vocal', 'no vocal chops', 'no busy melody', 'no heavy bass'],
    duckingRequired: true,
    loopableNeeded: true,
    creditImpact: 'low',
    requiresApproval: true,
    status: 'awaiting_approval',
    notes: ['Voice clarity has priority over musical detail.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_cue_lake_como_003_boat',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    cueOrder: 3,
    cueRole: 'travel_movement',
    sceneType: 'boat_movement',
    startTimeSeconds: 72,
    endTimeSeconds: 117,
    targetDurationSeconds: 45,
    mood: 'luxury',
    genreFamilies: ['cinematic', 'luxury_lounge', 'italian_inspired_pop'],
    energyLevel: 'medium',
    energyArc: 'gentle_build',
    cultureRegion: 'european_luxury',
    vocalPolicy: 'lyrics_allowed_only_without_speech',
    lyricLanguagePolicy: 'italian_allowed',
    speechSafety: 'montage_only',
    instrumentation: ['warm acoustic guitar', 'soft brushed drums', 'elegant bass', 'gentle piano sparkle'],
    bpmTarget: 96,
    keyTarget: 'A major',
    referenceInfluence: 'moderate_style_dna',
    promptGoal: 'Create an elegant travel montage cue for boat movement and scenic Lake Como visuals.',
    negativePromptGoals: ['no aggressive EDM drops', 'no copied reference melody', 'no lyrics over speech'],
    duckingRequired: false,
    loopableNeeded: false,
    creditImpact: 'medium',
    requiresApproval: true,
    status: 'awaiting_approval',
    notes: ['Light vocal texture is acceptable only if the section has no speech.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_cue_lake_como_004_food_social',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    cueOrder: 4,
    cueRole: 'food_social_warmth',
    sceneType: 'food_social',
    startTimeSeconds: 117,
    endTimeSeconds: 152,
    targetDurationSeconds: 35,
    mood: 'warm',
    genreFamilies: ['acoustic', 'jazz', 'luxury_lounge', 'lifestyle_vlog'],
    energyLevel: 'medium_low',
    energyArc: 'flat',
    cultureRegion: 'european_luxury',
    vocalPolicy: 'instrumental_only',
    lyricLanguagePolicy: 'no_lyrics',
    speechSafety: 'needs_ducking',
    instrumentation: ['muted guitar', 'light percussion', 'soft piano', 'warm bass'],
    bpmTarget: 88,
    referenceInfluence: 'light_style_dna',
    promptGoal: 'Support food, friends, and casual luxury without masking table dialogue or ambience.',
    negativePromptGoals: ['no loud restaurant fake ambience', 'no lyrics', 'no busy lead melody'],
    duckingRequired: true,
    loopableNeeded: true,
    creditImpact: 'low',
    requiresApproval: true,
    status: 'awaiting_approval',
    notes: ['Natural laughter and restaurant ambience should remain believable.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_cue_lake_como_005_outro',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    cueOrder: 5,
    cueRole: 'outro_resolve',
    sceneType: 'outro',
    startTimeSeconds: 152,
    endTimeSeconds: 172,
    targetDurationSeconds: 20,
    mood: 'warm',
    genreFamilies: ['cinematic', 'ambient', 'acoustic'],
    energyLevel: 'low',
    energyArc: 'soft_resolve',
    cultureRegion: 'global',
    vocalPolicy: 'vocal_texture_only',
    lyricLanguagePolicy: 'no_lyrics',
    speechSafety: 'intro_outro_only',
    instrumentation: ['soft piano', 'warm pad', 'gentle acoustic texture'],
    bpmTarget: 76,
    referenceInfluence: 'light_style_dna',
    promptGoal: 'Resolve the vacation story softly and leave the ending polished.',
    negativePromptGoals: ['no abrupt ending', 'no full lyrical hook', 'no dramatic trailer swell'],
    duckingRequired: false,
    loopableNeeded: false,
    creditImpact: 'low',
    requiresApproval: true,
    status: 'awaiting_approval',
    notes: ['Fade out naturally with the final scenic or group moment.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

const teaserSegments: LyriaPromptSegment[] = [
  {
    id: 'lyria_segment_teaser_001',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_teaser_001',
    segmentOrder: 1,
    startTimeSeconds: 0,
    endTimeSeconds: 8,
    purpose: 'Open with premium teaser energy.',
    energy: 'medium_high',
    instrumentation: ['tight drums', 'soft synth pulse', 'premium bass'],
    lyricInstruction: 'No lyrics; airy vocal texture only if it does not imply words.',
    transitionInstruction: 'Peak quickly, then prepare a clean drop into the next cue.',
    promptText: 'Stylish premium teaser with short social momentum and no copied reference hook.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_segment_teaser_002',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_teaser_001',
    segmentOrder: 2,
    startTimeSeconds: 8,
    endTimeSeconds: 12,
    purpose: 'Resolve teaser into story opening.',
    energy: 'medium',
    instrumentation: ['filtered drums', 'soft synth tail'],
    lyricInstruction: 'No lyrics.',
    transitionInstruction: 'Quick musical tail that leaves room for dialogue or ambience.',
    promptText: 'Short resolve, no abrupt cutoff, no vocal hook.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

const dialogueSegments: LyriaPromptSegment[] = [
  {
    id: 'lyria_segment_dialogue_001',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_dialogue_001',
    segmentOrder: 1,
    startTimeSeconds: 0,
    endTimeSeconds: 60,
    purpose: 'Voice-first premium bed.',
    energy: 'low',
    instrumentation: ['soft piano', 'warm pads', 'subtle pulse'],
    lyricInstruction: 'No lyrics, no lead vocal, no vocal chops.',
    transitionInstruction: 'Keep texture steady and loopable under speech.',
    promptText: 'Instrumental-only bed with room for narration and natural ambience.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

const boatSegments: LyriaPromptSegment[] = [
  {
    id: 'lyria_segment_boat_001',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_boat_001',
    segmentOrder: 1,
    startTimeSeconds: 0,
    endTimeSeconds: 15,
    purpose: 'Gentle build for scenic movement.',
    energy: 'medium_low',
    instrumentation: ['warm acoustic guitar', 'elegant bass', 'gentle piano sparkle'],
    lyricInstruction: 'Light vocal texture allowed only if there is no spoken dialogue.',
    transitionInstruction: 'Start open and cinematic.',
    promptText: 'Elegant Lake Como travel cue begins with premium restraint.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_segment_boat_002',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_boat_001',
    segmentOrder: 2,
    startTimeSeconds: 15,
    endTimeSeconds: 38,
    purpose: 'Open into brighter movement groove.',
    energy: 'medium',
    instrumentation: ['soft brushed drums', 'warm acoustic guitar', 'elegant bass'],
    lyricInstruction: 'No words; texture only if no speech.',
    transitionInstruction: 'Support boat movement without aggressive drops.',
    promptText: 'Brighter premium travel groove, tasteful and modern.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_segment_boat_003',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_boat_001',
    segmentOrder: 3,
    startTimeSeconds: 38,
    endTimeSeconds: 45,
    purpose: 'Soft resolve into next scene.',
    energy: 'medium_low',
    instrumentation: ['piano sparkle', 'guitar tail', 'soft cymbal wash'],
    lyricInstruction: 'No lyrics.',
    transitionInstruction: 'Resolve softly and leave room for ambience.',
    promptText: 'Elegant resolve with no abrupt ending.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

const foodSegments: LyriaPromptSegment[] = [
  {
    id: 'lyria_segment_food_001',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_food_001',
    segmentOrder: 1,
    startTimeSeconds: 0,
    endTimeSeconds: 35,
    purpose: 'Warm support for food and social moments.',
    energy: 'medium_low',
    instrumentation: ['muted guitar', 'soft piano', 'light percussion', 'warm bass'],
    lyricInstruction: 'Instrumental only.',
    transitionInstruction: 'Keep loopable and easy to duck under table dialogue.',
    promptText: 'Warm food/social lounge cue with natural ambience space.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

const outroSegments: LyriaPromptSegment[] = [
  {
    id: 'lyria_segment_outro_001',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_outro_001',
    segmentOrder: 1,
    startTimeSeconds: 0,
    endTimeSeconds: 20,
    purpose: 'Soft emotional resolve.',
    energy: 'low',
    instrumentation: ['soft piano', 'warm pad', 'gentle acoustic texture'],
    lyricInstruction: 'No lyrics; soft vocal texture only if it feels like air, not words.',
    transitionInstruction: 'Fade cleanly into the final frame.',
    promptText: 'Warm reflective outro resolve with a polished ending.',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockLyriaPromptSegments: LyriaPromptSegment[] = [
  ...teaserSegments,
  ...dialogueSegments,
  ...boatSegments,
  ...foodSegments,
  ...outroSegments,
]

export const mockLyriaPromptPlans: LyriaPromptPlanRecord[] = [
  {
    id: 'lyria_prompt_lake_como_teaser_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_001_teaser',
    generationPurpose: 'intro_music',
    modelName: LYRIA_PRO_FUTURE_MODEL_NAME,
    providerName: 'Lyria Pro',
    prompt:
      'Create a 12-second premium lifestyle coming-up teaser cue for a Lake Como-style vacation vlog. Stylish electronic-pop pulse, tight drums, soft synth lift, premium bass, and airy vocal texture only, no lyrics. Medium-high energy that peaks quickly and drops cleanly into the story. Do not imitate any existing song or reference track.',
    negativePrompt:
      'No full lyrical vocal, no copied reference melody, no aggressive EDM drop, no harsh drums, no vocals under important speech.',
    durationSeconds: 12,
    outputFormat: 'wav',
    instrumentalOnly: false,
    lyricsAllowed: false,
    timestampedStructure: teaserSegments,
    styleConstraints: ['premium lifestyle', 'modern social teaser', 'no copied reference music'],
    timingConstraints: ['0:00-0:08 quick lift', '0:08-0:12 clean drop into next cue'],
    speechSafetyInstructions: ['Use only before speech or under non-speaking footage.'],
    cultureContextInstructions: ['Use European luxury tastefulness without location stereotypes.'],
    qualityInstructions: ['Clean ending', 'no obvious artifacts', 'broadcast-safe dynamics'],
    creditEstimateId: 'credit_estimate_music_lake_como_001',
    status: 'awaiting_approval',
    notes: ['Prompt is planned only; no Lyria Pro call is made.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_prompt_lake_como_dialogue_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_002_dialogue',
    generationPurpose: 'dialogue_bed',
    modelName: LYRIA_PRO_FUTURE_MODEL_NAME,
    providerName: 'Lyria Pro',
    prompt:
      'Create a 60-second instrumental-only premium background bed for spoken lifestyle narration. No lyrics, no lead vocal, no vocal chops. Soft piano, warm pads, subtle pulse, low energy, designed to sit under voice with clean ducking space. Avoid busy melodies, heavy bass, harsh drums, or anything that competes with dialogue.',
    negativePrompt:
      'No lyrics, no lead vocal, no vocal chops, no distracting melody, no heavy bass, no harsh percussion, no dramatic trailer swell.',
    durationSeconds: 60,
    outputFormat: 'wav',
    instrumentalOnly: true,
    lyricsAllowed: false,
    timestampedStructure: dialogueSegments,
    styleConstraints: ['instrumental only', 'premium calm', 'voice-first'],
    timingConstraints: ['steady and loopable for dialogue section'],
    speechSafetyInstructions: ['Leave midrange space for spoken voice', 'duck cleanly under speech'],
    cultureContextInstructions: ['Keep globally premium; do not force Italian stereotypes under dialogue.'],
    qualityInstructions: ['No artifacts', 'clean loop potential', 'low-energy stable bed'],
    creditEstimateId: 'credit_estimate_music_lake_como_001',
    status: 'awaiting_approval',
    notes: ['Dialogue safety is mandatory.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_prompt_lake_como_boat_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_003_boat',
    generationPurpose: 'montage_song',
    modelName: LYRIA_PRO_FUTURE_MODEL_NAME,
    providerName: 'Lyria Pro',
    prompt:
      'Create a 45-second Italian/elegant European luxury travel montage cue for a Lake Como-style vacation vlog. Warm acoustic guitar, soft brushed drums, elegant bass, gentle piano sparkle, medium-low energy, premium lifestyle feel. No aggressive EDM drops. Light vocal texture is allowed only if there is no spoken dialogue. Build gently from 0:00-0:15, open into a brighter groove from 0:15-0:38, and resolve softly from 0:38-0:45.',
    negativePrompt:
      'No aggressive EDM drops, no copied reference track, no tourist stereotype, no full lyrics over speech, no harsh synth lead.',
    durationSeconds: 45,
    outputFormat: 'wav',
    instrumentalOnly: false,
    lyricsAllowed: true,
    targetLanguage: 'italian',
    timestampedStructure: boatSegments,
    styleConstraints: ['Italian-inspired but modern', 'elegant European travel', 'premium lifestyle feel'],
    timingConstraints: ['0:00-0:15 gentle build', '0:15-0:38 brighter groove', '0:38-0:45 soft resolve'],
    speechSafetyInstructions: ['Light vocal texture only if no speech is present.'],
    cultureContextInstructions: ['Use subtle Italian/european luxury influence; avoid cliches.'],
    qualityInstructions: ['Polished travel montage dynamics', 'clean resolve', 'no artifacts'],
    creditEstimateId: 'credit_estimate_music_lake_como_001',
    status: 'awaiting_approval',
    notes: ['This is a style adaptation prompt, not a reference copy.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_prompt_lake_como_food_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_004_food_social',
    generationPurpose: 'music_cue',
    modelName: LYRIA_PRO_FUTURE_MODEL_NAME,
    providerName: 'Lyria Pro',
    prompt:
      'Create a 35-second instrumental warm food and social moment cue for a premium lifestyle vacation vlog. Muted guitar, soft piano, light percussion, warm bass, relaxed playful mood, medium-low energy. Leave room for natural laughter, table dialogue, and restaurant ambience. No lyrics and no busy lead melody.',
    negativePrompt:
      'No lyrics, no loud fake restaurant ambience, no distracting lead melody, no heavy drums, no copied reference music.',
    durationSeconds: 35,
    outputFormat: 'wav',
    instrumentalOnly: true,
    lyricsAllowed: false,
    timestampedStructure: foodSegments,
    styleConstraints: ['warm', 'relaxed', 'premium lifestyle', 'natural ambience-friendly'],
    timingConstraints: ['loopable and easy to fade around social cuts'],
    speechSafetyInstructions: ['Keep ducking space for table dialogue.'],
    cultureContextInstructions: ['Tasteful lounge warmth; do not force cultural markers.'],
    qualityInstructions: ['No artifacts', 'gentle loop point', 'clean low-frequency balance'],
    creditEstimateId: 'credit_estimate_music_lake_como_001',
    status: 'awaiting_approval',
    notes: ['Ambience should remain believable.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'lyria_prompt_lake_como_outro_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_005_outro',
    generationPurpose: 'outro_resolve',
    modelName: LYRIA_PRO_FUTURE_MODEL_NAME,
    providerName: 'Lyria Pro',
    prompt:
      'Create a 20-second warm reflective outro resolve for a luxury vacation vlog. Soft piano, warm pad, gentle acoustic texture, low energy, emotional but not dramatic. No lyrics. Optional soft vocal air texture only if it has no words. Resolve cleanly and fade naturally into the final frame.',
    negativePrompt: 'No full lyrics, no abrupt cutoff, no dramatic trailer swell, no copied reference melody.',
    durationSeconds: 20,
    outputFormat: 'wav',
    instrumentalOnly: false,
    lyricsAllowed: false,
    timestampedStructure: outroSegments,
    styleConstraints: ['warm', 'reflective', 'soft resolve'],
    timingConstraints: ['resolve cleanly by 0:20'],
    speechSafetyInstructions: ['Use only in outro or under non-speaking final visual.'],
    cultureContextInstructions: ['Keep emotion universal and not stereotyped.'],
    qualityInstructions: ['Clean ending', 'smooth fade', 'no artifact tail'],
    creditEstimateId: 'credit_estimate_music_lake_como_001',
    status: 'awaiting_approval',
    notes: ['Designed to end the story, not loop indefinitely.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockGeneratedMusicTracks: GeneratedMusicTrackRecord[] = [
  {
    id: 'generated_music_track_dialogue_001',
    projectId,
    editPlanId,
    musicCueId: 'music_cue_lake_como_002_dialogue',
    lyriaPromptPlanId: 'lyria_prompt_lake_como_dialogue_001',
    origin: 'lyria_generated',
    provider: 'Lyria Pro',
    model: LYRIA_PRO_FUTURE_MODEL_NAME,
    prompt: mockLyriaPromptPlans[1].prompt,
    negativePrompt: mockLyriaPromptPlans[1].negativePrompt,
    durationSeconds: 60,
    genreFamilies: ['ambient', 'cinematic', 'luxury_lounge'],
    mood: 'calm',
    energy: 'low',
    cultureRegion: 'global',
    vocalPolicy: 'instrumental_only',
    lyricLanguagePolicy: 'no_lyrics',
    storagePath: 'project-assets/project_lake_como_style_001/audio/dialogue-bed-preview.wav',
    reuseStatus: 'project_only',
    qaStatus: 'passed',
    licenseProvenanceId,
    notes: ['Mock generated track record; no real generation occurred.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockMusicTrackAnalyses: MusicTrackAnalysisRecord[] = [
  {
    id: 'music_track_analysis_dialogue_001',
    generatedMusicTrackId: 'generated_music_track_dialogue_001',
    bpm: 82,
    key: 'C major',
    loudnessLufs: -22,
    peakDb: -5.8,
    hasVocals: false,
    detectedLanguages: [],
    energyLevel: 'low',
    moodTags: ['calm', 'premium', 'clean'],
    instrumentTags: ['soft piano', 'warm pads', 'subtle pulse'],
    loopable: true,
    loopStartSeconds: 4,
    loopEndSeconds: 56,
    speechSafe: true,
    artifactScore: 0.03,
    qualityScore: 0.92,
    recommendedUse: 'Dialogue-safe premium bed for spoken lifestyle narration.',
    warnings: [],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_track_analysis_boat_prompt_preview_001',
    audioAssetId: 'audio_asset_future_boat_prompt_preview',
    bpm: 96,
    key: 'A major',
    loudnessLufs: -18,
    peakDb: -4.2,
    hasVocals: true,
    detectedLanguages: ['non_lexical_vocal_texture'],
    energyLevel: 'medium',
    moodTags: ['luxury', 'warm', 'stylish'],
    instrumentTags: ['acoustic guitar', 'brushed drums', 'piano sparkle', 'bass'],
    loopable: false,
    speechSafe: false,
    artifactScore: 0.06,
    qualityScore: 0.87,
    recommendedUse: 'No-speech boat montage only; duck or remove under dialogue.',
    warnings: ['Vocal texture must be verified against speech sections before use.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockMusicMixPlans: MusicMixPlanRecord[] = [
  {
    id: 'music_mix_plan_dialogue_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_002_dialogue',
    generatedMusicTrackId: 'generated_music_track_dialogue_001',
    volumeDbTarget: -24,
    duckingStrategy: 'voice_first',
    duckingAmountDb: 8,
    duckUnderSpeech: true,
    introFadeSeconds: 1.5,
    outroFadeSeconds: 2,
    crossfadeWithPreviousCue: 1,
    crossfadeWithNextCue: 1,
    beatSyncPoints: [],
    silenceMoments: [{ startSeconds: 38, endSeconds: 40 }],
    ambientBridgeNeeded: true,
    sfxRelationship: 'Avoid transition SFX during spoken punchlines; preserve water and room ambience.',
    mixNotes: ['Keep narration forward.', 'Do not strip ambience that establishes location.'],
    status: 'draft',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'music_mix_plan_boat_001',
    projectId,
    editPlanId,
    musicCueSheetId: cueSheetId,
    musicCueId: 'music_cue_lake_como_003_boat',
    volumeDbTarget: -16,
    duckingStrategy: 'beat_sensitive',
    duckingAmountDb: 4,
    duckUnderSpeech: false,
    introFadeSeconds: 0.5,
    outroFadeSeconds: 1.5,
    crossfadeWithPreviousCue: 1,
    crossfadeWithNextCue: 1,
    beatSyncPoints: [
      { startSeconds: 72, endSeconds: 72.4 },
      { startSeconds: 87, endSeconds: 87.4 },
    ],
    silenceMoments: [],
    ambientBridgeNeeded: true,
    sfxRelationship: 'Use soft whoosh only for title or location card, not every cut.',
    mixNotes: ['Let boat ambience breathe at opening.', 'Lift music after scenic reveal.'],
    status: 'draft',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockMusicQAReport: MusicQAReportRecord = {
  id: 'music_qa_report_dialogue_001',
  projectId,
  editPlanId,
  musicCueSheetId: cueSheetId,
  musicCueId: 'music_cue_lake_como_002_dialogue',
  generatedMusicTrackId: 'generated_music_track_dialogue_001',
  status: 'passed',
  overallScore: 0.92,
  speechSafetyScore: 0.96,
  contextFitScore: 0.9,
  cultureFitScore: 0.86,
  moodFitScore: 0.94,
  mixReadinessScore: 0.91,
  issues: [],
  recommendedAction: 'approve_for_project',
  requiresRegeneration: false,
  requiresMixAdjustment: false,
  approvedForProject: true,
  approvedForLibraryCandidate: true,
  notes: [
    'Instrumental-only bed fits dialogue and leaves ducking room.',
    'Library promotion still requires license/terms review.',
  ],
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockMusicLibraryCandidate: MusicLibraryCandidateRecord = {
  id: 'music_library_candidate_dialogue_001',
  generatedMusicTrackId: 'generated_music_track_dialogue_001',
  projectId,
  workspaceId: 'workspace_personal_001',
  candidateStatus: 'requires_terms_review',
  reason: 'High-quality instrumental dialogue bed may be reusable if future provider terms allow internal library use.',
  qualityScore: 0.92,
  reuseStatus: 'requires_terms_review',
  genreFamilies: ['ambient', 'cinematic', 'luxury_lounge'],
  moodTags: ['calm', 'premium', 'clean'],
  cultureRegion: 'global',
  vocalPolicy: 'instrumental_only',
  speechSafe: true,
  licenseReviewRequired: true,
  notes: ['Do not reuse across users until QA and terms review are complete.'],
  createdAt: mockAudioMusicTimestamp,
  updatedAt: mockAudioMusicTimestamp,
}

export const mockAudioLicenseProvenanceRecords: AudioLicenseProvenanceRecord[] = [
  {
    id: licenseProvenanceId,
    projectId,
    workspaceId: 'workspace_personal_001',
    audioAssetOrigin: 'lyria_generated',
    provider: 'Lyria Pro',
    model: LYRIA_PRO_FUTURE_MODEL_NAME,
    termsVersion: 'future_terms_review_required',
    licenseScope: 'requires_review',
    commercialAllowed: false,
    adsAllowed: false,
    clientWorkAllowed: false,
    reuseAcrossUsersAllowed: false,
    requiresAttribution: false,
    userProvided: false,
    licenseNotes: [
      'Mock provenance only; no provider call occurred.',
      'Reuse across users requires confirmed Lyria Pro terms and ReeditPro QA approval.',
    ],
    proofStoragePath: 'project-assets/project_lake_como_style_001/audio/provenance/dialogue-bed.json',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'license_reeditpro_owned_sfx_pack_001',
    workspaceId: 'workspace_reeditpro_internal',
    audioAssetOrigin: 'reeditpro_owned_sfx',
    provider: 'ReeditPro commissioned SFX pack',
    termsVersion: 'owned_pack_v1',
    licenseScope: 'reeditpro_library',
    commercialAllowed: true,
    adsAllowed: true,
    clientWorkAllowed: true,
    reuseAcrossUsersAllowed: true,
    requiresAttribution: false,
    userProvided: false,
    licenseNotes: ['Commissioned or bought SFX pack controlled by ReeditPro for future product use.'],
    proofStoragePath: 'internal-audio-licenses/reeditpro-owned-sfx-pack-v1.pdf',
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockAudioUsageRecords: AudioUsageRecord[] = [
  {
    id: 'audio_usage_dialogue_preview_001',
    projectId,
    editPlanId,
    generatedMusicTrackId: 'generated_music_track_dialogue_001',
    musicCueId: 'music_cue_lake_como_002_dialogue',
    licenseProvenanceId,
    usageType: 'project_preview',
    usedStartTimeSeconds: 12,
    usedEndTimeSeconds: 72,
    mixPlanId: 'music_mix_plan_dialogue_001',
    usageNotes: ['Preview-only mock usage; final export still requires approval and render QA.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockSfxLibraryAssets: SfxLibraryAssetRecord[] = [
  {
    id: 'sfx_asset_soft_whoosh_001',
    displayName: 'Soft Premium Whoosh',
    origin: 'reeditpro_owned_sfx',
    sfxUseCase: 'soft_whoosh',
    storagePath: 'internal-sfx/reeditpro-owned-pack/soft-premium-whoosh.wav',
    durationSeconds: 0.8,
    licenseProvenanceId: 'license_reeditpro_owned_sfx_pack_001',
    safeUnderVoice: true,
    volumeCategory: 'low',
    tags: ['transition', 'premium', 'soft'],
    recommendedSceneTypes: ['chapter_transition', 'travel_montage', 'luxury_showcase'],
    avoidSceneTypes: ['dialogue', 'faith_reflective'],
    supportsSignatureSystems: ['stroke_motion', 'graphic_design', 'real_motion', 'sound_sync'],
    approvedForUse: true,
    notes: ['Use sparingly; never stack on every cut.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'sfx_asset_stroke_draw_001',
    displayName: 'Stroke Motion Draw Tick',
    origin: 'reeditpro_owned_sfx',
    sfxUseCase: 'stroke_motion_draw',
    storagePath: 'internal-sfx/reeditpro-owned-pack/stroke-draw-tick.wav',
    durationSeconds: 0.35,
    licenseProvenanceId: 'license_reeditpro_owned_sfx_pack_001',
    safeUnderVoice: true,
    volumeCategory: 'low',
    tags: ['stroke_motion', 'draw', 'subtle'],
    recommendedSceneTypes: ['education', 'faith_reflective', 'talking_head'],
    avoidSceneTypes: ['food_social', 'boat_movement'],
    supportsSignatureSystems: ['stroke_motion', 'sound_sync'],
    approvedForUse: true,
    notes: ['Designed to support visual timing without distracting from speech.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
  {
    id: 'sfx_asset_chapter_light_hit_001',
    displayName: 'Chapter Light Hit',
    origin: 'reeditpro_owned_sfx',
    sfxUseCase: 'chapter_title',
    storagePath: 'internal-sfx/reeditpro-owned-pack/chapter-light-hit.wav',
    durationSeconds: 0.6,
    licenseProvenanceId: 'license_reeditpro_owned_sfx_pack_001',
    safeUnderVoice: false,
    volumeCategory: 'medium',
    tags: ['chapter', 'title', 'light_hit'],
    recommendedSceneTypes: ['chapter_transition', 'coming_up_teaser', 'outro'],
    avoidSceneTypes: ['dialogue', 'narration'],
    supportsSignatureSystems: ['graphic_design', 'sound_sync'],
    approvedForUse: true,
    notes: ['Use for title cards or chapter beats when no important speech is present.'],
    createdAt: mockAudioMusicTimestamp,
    updatedAt: mockAudioMusicTimestamp,
  },
]

export const mockFrenchMontagePromptExample =
  'Create a 35-second French indie-pop inspired montage cue for a stylish Paris lifestyle/vacation vlog. Warm guitar, tasteful electronic lounge rhythm, soft bass, airy modern French vocal texture allowed only in non-speaking moments. Premium, relaxed, fashionable mood. Avoid accordion cliches unless explicitly requested. Do not imitate any existing song.'

export const mockAudioMusicRecords = {
  styleTaxonomy: mockMusicStyleTaxonomyRecords,
  referenceMusicDNA: mockLakeComoReferenceMusicDNA,
  musicContextAnalysis: mockLifestyleVacationMusicContext,
  languageContext: mockItalianLuxuryMusicLanguageContext,
  cueSheet: mockLakeComoMusicCueSheet,
  cues: mockLakeComoMusicCues,
  lyriaPromptSegments: mockLyriaPromptSegments,
  lyriaPromptPlans: mockLyriaPromptPlans,
  generatedTracks: mockGeneratedMusicTracks,
  trackAnalyses: mockMusicTrackAnalyses,
  mixPlans: mockMusicMixPlans,
  qaReport: mockMusicQAReport,
  libraryCandidate: mockMusicLibraryCandidate,
  licenseProvenance: mockAudioLicenseProvenanceRecords,
  usageRecords: mockAudioUsageRecords,
  sfxAssets: mockSfxLibraryAssets,
  frenchMontagePromptExample: mockFrenchMontagePromptExample,
} as const
