import type {
  ID,
  Seconds,
  TimeRange,
} from '../types/shared'
import type {
  MasterTimingMapRecord,
  RenderTimingManifestRecord,
  StoryTimingQACheckRecord,
  StoryTimingSegmentRecord,
  TimingAnchorRecord,
  TimingConflictRecord,
  TimingConflictResolutionRecord,
  TimingDependencyRecord,
  TimingEventRecord,
} from '../types/storytiming'

export const MOCK_STORYTIMING_NOW = '2026-05-19T12:00:00.000Z'

export const MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID = 'master_timing_map_lake_como_lifestyle'
export const MOCK_FAITH_MASTER_TIMING_MAP_ID = 'master_timing_map_faith_teaching'

const LAKE_COMO_PROJECT_ID = 'project_lake_como_lifestyle'
const LAKE_COMO_EDIT_PLAN_ID = 'edit_plan_lake_como_signature'
const FAITH_PROJECT_ID = 'project_serious_faith_teaching'
const FAITH_EDIT_PLAN_ID = 'edit_plan_faith_voice_first'

const baseRecord = (id: ID) => ({
  id,
  createdAt: MOCK_STORYTIMING_NOW,
  updatedAt: MOCK_STORYTIMING_NOW,
})

const range = (startSeconds: Seconds, endSeconds: Seconds): TimeRange => ({
  startSeconds,
  endSeconds,
})

const frame = (seconds: Seconds, frameRate = 30): number => Math.round(seconds * frameRate)

export const mockMasterTimingMaps: MasterTimingMapRecord[] = [
  {
    ...baseRecord(MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
    workspaceId: 'workspace_demo',
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    chatSessionId: 'chat_lake_como_lifestyle',
    version: 1,
    status: 'approved',
    durationSeconds: 45,
    frameRate: 30,
    timebase: {
      frameRate: 30,
      durationSeconds: 45,
      totalFrames: 1350,
      frameRoundingMode: 'round',
      startTimecode: '00:00:00:00',
      dropFrame: false,
    },
    editComplexity: 'signature_edit',
    primaryTimingAuthority: 'visual_comprehension',
    timingHierarchy: [
      'user_instruction',
      'speech_meaning',
      'story_beat',
      'emotional_timing',
      'caption_readability',
      'visual_comprehension',
      'music_rhythm',
      'sfx_hit',
      'signature_animation',
      'platform_pacing',
    ],
    sourceSystemsIncluded: [
      'edit_plan',
      'story_beat',
      'cut_decision',
      'transition_plan',
      'caption_plan',
      'music_cue',
      'music_mix',
      'sfx_event',
      'sfx_trim',
      'sfx_alignment',
      'sfx_mix',
      'stroke_motion',
      'graphic_design',
      'real_motion',
      'render_job',
      'qa_report',
    ],
    lockedForGeneration: false,
    approvedByUserId: 'user_demo_creator',
    approvedAt: MOCK_STORYTIMING_NOW,
    summary:
      'Master timing map for a Lake Como luxury lifestyle edit with voice-safe captions, soft SoundSync polish, signature reveals, ambience preservation, and a render-ready event manifest.',
    notes: [
      'Lifestyle/vacation timing lets music, ambience, and visual rhythm share control.',
      'Speech and captions remain readable during dialogue bed sections.',
      'SFX hits are tied to title, transition, and outro timing anchors only.',
    ],
  },
  {
    ...baseRecord(MOCK_FAITH_MASTER_TIMING_MAP_ID),
    workspaceId: 'workspace_demo',
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    chatSessionId: 'chat_faith_teaching',
    version: 1,
    status: 'approved',
    durationSeconds: 32,
    frameRate: 30,
    timebase: {
      frameRate: 30,
      durationSeconds: 32,
      totalFrames: 960,
      frameRoundingMode: 'round',
      startTimecode: '00:00:00:00',
      dropFrame: false,
    },
    editComplexity: 'basic_edit',
    primaryTimingAuthority: 'speech_meaning',
    timingHierarchy: [
      'user_instruction',
      'speech_meaning',
      'story_beat',
      'emotional_timing',
      'caption_readability',
      'visual_comprehension',
      'music_rhythm',
      'sfx_hit',
      'signature_animation',
      'platform_pacing',
    ],
    sourceSystemsIncluded: [
      'edit_plan',
      'story_beat',
      'caption_plan',
      'music_cue',
      'music_mix',
      'sfx_event',
      'qa_report',
    ],
    lockedForGeneration: false,
    summary:
      'Master timing map for a serious faith teaching clip where speech meaning, emotional pauses, and voice-first captions outrank decorative timing.',
    notes: [
      'Faith/serious teaching timing preserves meaningful pauses.',
      'Music remains subtle and SFX are avoided unless a whisper-level transition is explicitly useful.',
    ],
  },
]

export const mockStoryTimingSegments: StoryTimingSegmentRecord[] = [
  {
    ...baseRecord('story_timing_segment_lake_como_teaser'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    editPlanSegmentId: 'edit_segment_lake_como_teaser',
    storyBeatId: 'story_beat_lake_como_teaser',
    segmentOrder: 1,
    sourceTimeRange: range(0, 4.8),
    outputTimeRange: range(0, 4.8),
    purpose: 'Coming-up teaser with one premium glimpse and a restrained title setup.',
    primaryAuthority: 'visual_comprehension',
    pacingStyle: 'smooth_teaser',
    hasSpeech: false,
    hasMusic: true,
    hasSFX: true,
    hasCaptions: false,
    hasSignatureOverlay: true,
    preserveEmotionalPause: false,
    notes: ['Let the location breathe before the first title hit.'],
  },
  {
    ...baseRecord('story_timing_segment_lake_como_dialogue_bed'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    editPlanSegmentId: 'edit_segment_lake_como_dialogue_bed',
    storyBeatId: 'story_beat_lake_como_dialogue',
    segmentOrder: 2,
    sourceTimeRange: range(4.8, 14),
    outputTimeRange: range(4.8, 14),
    purpose: 'Dialogue bed introducing the trip feeling with voice-first captions.',
    primaryAuthority: 'speech_meaning',
    pacingStyle: 'voice_first_lifestyle',
    hasSpeech: true,
    hasMusic: true,
    hasSFX: false,
    hasCaptions: true,
    hasSignatureOverlay: false,
    preserveEmotionalPause: true,
    notes: ['Music ducking should start before speech and recover after phrase endings.'],
  },
  {
    ...baseRecord('story_timing_segment_lake_como_chapter_title'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentOrder: 3,
    outputTimeRange: range(14, 18),
    purpose: 'Chapter/title card reveal for the premium location beat.',
    primaryAuthority: 'visual_comprehension',
    pacingStyle: 'premium_title_hold',
    hasSpeech: false,
    hasMusic: true,
    hasSFX: true,
    hasCaptions: false,
    hasSignatureOverlay: true,
    preserveEmotionalPause: false,
    notes: ['SFX title hit should land on the chapter title frame, then get out quickly.'],
  },
  {
    ...baseRecord('story_timing_segment_lake_como_boat_montage'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentOrder: 4,
    outputTimeRange: range(18, 29),
    purpose: 'Boat and movement montage where music rhythm can lead cuts.',
    primaryAuthority: 'music_rhythm',
    pacingStyle: 'smooth_montage',
    hasSpeech: false,
    hasMusic: true,
    hasSFX: true,
    hasCaptions: false,
    hasSignatureOverlay: true,
    preserveEmotionalPause: false,
    notes: ['Music beat can lead, but ambience should not feel fake or overproduced.'],
  },
  {
    ...baseRecord('story_timing_segment_lake_como_food_social'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentOrder: 5,
    outputTimeRange: range(29, 39),
    purpose: 'Food and social scene with captions kept clear of faces and plates.',
    primaryAuthority: 'visual_comprehension',
    pacingStyle: 'warm_observational',
    hasSpeech: true,
    hasMusic: true,
    hasSFX: false,
    hasCaptions: true,
    hasSignatureOverlay: true,
    preserveEmotionalPause: true,
    notes: ['Real Motion object settle should avoid face area and caption safe zone.'],
  },
  {
    ...baseRecord('story_timing_segment_lake_como_outro_resolve'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentOrder: 6,
    outputTimeRange: range(39, 45),
    purpose: 'Outro resolve with soft CTA reveal and music resolution.',
    primaryAuthority: 'music_rhythm',
    pacingStyle: 'premium_resolve',
    hasSpeech: false,
    hasMusic: true,
    hasSFX: true,
    hasCaptions: false,
    hasSignatureOverlay: true,
    preserveEmotionalPause: false,
    notes: ['CTA reveal should land on music resolve without feeling salesy.'],
  },
  {
    ...baseRecord('story_timing_segment_faith_core_teaching'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentOrder: 1,
    outputTimeRange: range(0, 18),
    purpose: 'Serious teaching section where speech meaning is the timing authority.',
    primaryAuthority: 'speech_meaning',
    pacingStyle: 'calm_teaching',
    hasSpeech: true,
    hasMusic: true,
    hasSFX: false,
    hasCaptions: true,
    hasSignatureOverlay: false,
    preserveEmotionalPause: true,
    notes: ['Captions must stay simple and voice-locked.'],
  },
  {
    ...baseRecord('story_timing_segment_faith_emotional_pause'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentOrder: 2,
    outputTimeRange: range(18, 32),
    purpose: 'Reflection section preserving an emotional pause before the closing phrase.',
    primaryAuthority: 'emotional_timing',
    pacingStyle: 'reflective_pause',
    hasSpeech: true,
    hasMusic: true,
    hasSFX: false,
    hasCaptions: true,
    hasSignatureOverlay: false,
    preserveEmotionalPause: true,
    notes: ['SFX should be avoided; a whisper-level ambience cue is optional only if requested.'],
  },
]

export const mockTimingAnchors: TimingAnchorRecord[] = [
  {
    ...baseRecord('timing_anchor_lake_como_title_hit'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_chapter_title',
    sourceSystem: 'sfx_event',
    sourceRecordId: 'sfx_event_lake_como_title_hit',
    anchorType: 'chapter_title',
    anchorLabel: 'Chapter title lands',
    anchorText: 'Lake Como, softly',
    timeSeconds: 14.2,
    frameNumber: frame(14.2),
    importance: 'high',
    primaryAuthority: 'visual_comprehension',
    syncMode: 'frame_locked',
    locked: true,
    notes: ['Title-card SFX hit and graphic reveal share this frame.'],
  },
  {
    ...baseRecord('timing_anchor_lake_como_dialogue_phrase'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_dialogue_bed',
    sourceSystem: 'caption_plan',
    sourceRecordId: 'caption_plan_lake_como_dialogue',
    anchorType: 'phrase',
    anchorLabel: 'Dialogue phrase complete',
    anchorText: 'it felt effortless',
    timeSeconds: 10.4,
    endTimeSeconds: 11.2,
    frameNumber: frame(10.4),
    importance: 'critical',
    primaryAuthority: 'speech_meaning',
    syncMode: 'phrase_locked',
    locked: true,
    notes: ['Cut and caption off should wait until this phrase completes.'],
  },
  {
    ...baseRecord('timing_anchor_lake_como_music_downbeat'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    sourceSystem: 'music_cue',
    sourceRecordId: 'music_cue_lake_como_montage',
    anchorType: 'music_downbeat',
    anchorLabel: 'Montage downbeat',
    timeSeconds: 18,
    frameNumber: frame(18),
    importance: 'high',
    primaryAuthority: 'music_rhythm',
    syncMode: 'beat_locked',
    locked: false,
    notes: ['Boat montage cuts can align to this downbeat grid.'],
  },
  {
    ...baseRecord('timing_anchor_lake_como_stroke_complete'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    sourceSystem: 'stroke_motion',
    sourceRecordId: 'stroke_motion_beat_lake_como_route_line',
    anchorType: 'stroke_motion_completion',
    anchorLabel: 'Stroke Motion route line completes',
    timeSeconds: 23.4,
    frameNumber: frame(23.4),
    importance: 'medium',
    primaryAuthority: 'signature_animation',
    syncMode: 'visual_motion_locked',
    locked: false,
    notes: ['Completion should land with the map/route meaning, not randomly.'],
  },
  {
    ...baseRecord('timing_anchor_lake_como_real_motion_settle'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_food_social',
    sourceSystem: 'real_motion',
    sourceRecordId: 'real_motion_object_limoncello_card',
    anchorType: 'real_motion_object_settle',
    anchorLabel: 'Limoncello card settles',
    timeSeconds: 34.1,
    frameNumber: frame(34.1),
    importance: 'medium',
    primaryAuthority: 'visual_comprehension',
    syncMode: 'visual_motion_locked',
    locked: false,
    notes: ['Object settle must leave captions and faces readable.'],
  },
  {
    ...baseRecord('timing_anchor_lake_como_music_resolve'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_outro_resolve',
    sourceSystem: 'music_cue',
    sourceRecordId: 'music_cue_lake_como_outro',
    anchorType: 'music_resolve',
    anchorLabel: 'Music resolve for outro CTA',
    timeSeconds: 42.8,
    frameNumber: frame(42.8),
    importance: 'high',
    primaryAuthority: 'music_rhythm',
    syncMode: 'beat_locked',
    locked: false,
    notes: ['CTA reveal and final SFX resolve can share this anchor.'],
  },
  {
    ...baseRecord('timing_anchor_faith_emotional_pause'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_faith_emotional_pause',
    sourceSystem: 'story_beat',
    sourceRecordId: 'story_beat_faith_reflection_pause',
    anchorType: 'pause',
    anchorLabel: 'Meaningful reflection pause',
    anchorText: 'pause before closing thought',
    timeSeconds: 20.2,
    endTimeSeconds: 22.1,
    frameNumber: frame(20.2),
    importance: 'critical',
    primaryAuthority: 'emotional_timing',
    syncMode: 'emotion_locked',
    locked: true,
    notes: ['Do not trim this pause for pace.'],
  },
  {
    ...baseRecord('timing_anchor_faith_sentence_end'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_faith_core_teaching',
    sourceSystem: 'caption_plan',
    sourceRecordId: 'caption_plan_faith_voice_first',
    anchorType: 'sentence',
    anchorLabel: 'Teaching sentence ends',
    anchorText: 'grace meets us there',
    timeSeconds: 16.7,
    frameNumber: frame(16.7),
    importance: 'critical',
    primaryAuthority: 'speech_meaning',
    syncMode: 'speech_locked',
    locked: true,
    notes: ['Cut after sentence end only.'],
  },
]

export const mockTimingEvents: TimingEventRecord[] = [
  {
    ...baseRecord('timing_event_lake_como_title_sfx_start'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_chapter_title',
    anchorId: 'timing_anchor_lake_como_title_hit',
    sourceSystem: 'sfx_alignment',
    sourceRecordId: 'sfx_alignment_lake_como_title_hit',
    eventType: 'sfx_start',
    trackType: 'sfx',
    label: 'Soft premium title hit starts',
    startTimeSeconds: 14,
    hitTimeSeconds: 14.2,
    endTimeSeconds: 14.72,
    durationSeconds: 0.72,
    frameStart: frame(14),
    frameHit: frame(14.2),
    frameEnd: frame(14.72),
    priority: 'high',
    syncMode: 'frame_locked',
    canShift: false,
    locked: true,
    audioLayer: 'sfx_title_hit',
    notes: ['Generated longer, trimmed so the hit lands on the title anchor.'],
  },
  {
    ...baseRecord('timing_event_lake_como_title_sfx_hit'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_chapter_title',
    anchorId: 'timing_anchor_lake_como_title_hit',
    sourceSystem: 'sfx_event',
    sourceRecordId: 'sfx_event_lake_como_title_hit',
    eventType: 'sfx_hit',
    trackType: 'sfx',
    label: 'Soft premium title hit point',
    startTimeSeconds: 14.2,
    hitTimeSeconds: 14.2,
    endTimeSeconds: 14.2,
    durationSeconds: 0,
    frameStart: frame(14.2),
    frameHit: frame(14.2),
    frameEnd: frame(14.2),
    priority: 'high',
    syncMode: 'frame_locked',
    canShift: false,
    locked: true,
    audioLayer: 'sfx_title_hit',
    notes: ['Hit point is the timing authority, not file start.'],
  },
  {
    ...baseRecord('timing_event_lake_como_title_graphic_reveal'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_chapter_title',
    anchorId: 'timing_anchor_lake_como_title_hit',
    sourceSystem: 'graphic_design',
    sourceRecordId: 'graphic_design_title_card_lake_como',
    eventType: 'graphic_reveal',
    trackType: 'graphic_design',
    label: 'Chapter title graphic reveal',
    startTimeSeconds: 14.2,
    endTimeSeconds: 17.4,
    durationSeconds: 3.2,
    frameStart: frame(14.2),
    frameEnd: frame(17.4),
    priority: 'high',
    syncMode: 'frame_locked',
    canShift: false,
    locked: true,
    visibilityLayer: 'title_card',
    signatureSystem: 'graphic_design',
    notes: ['Hold long enough for premium readability.'],
  },
  {
    ...baseRecord('timing_event_lake_como_dialogue_caption_on'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_dialogue_bed',
    anchorId: 'timing_anchor_lake_como_dialogue_phrase',
    sourceSystem: 'caption_plan',
    sourceRecordId: 'caption_plan_lake_como_dialogue',
    eventType: 'caption_on',
    trackType: 'captions',
    label: 'Dialogue caption appears',
    startTimeSeconds: 7.6,
    endTimeSeconds: 11.2,
    durationSeconds: 3.6,
    frameStart: frame(7.6),
    frameEnd: frame(11.2),
    priority: 'critical',
    syncMode: 'phrase_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'captions',
    notes: ['Caption stays in safe lower third and leaves after the phrase completes.'],
  },
  {
    ...baseRecord('timing_event_lake_como_music_duck_start'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_dialogue_bed',
    sourceSystem: 'music_mix',
    sourceRecordId: 'music_mix_lake_como_voice_first',
    eventType: 'music_duck_start',
    trackType: 'music',
    label: 'Music ducks before dialogue',
    startTimeSeconds: 7.3,
    endTimeSeconds: 11.5,
    durationSeconds: 4.2,
    frameStart: frame(7.3),
    frameEnd: frame(11.5),
    priority: 'critical',
    syncMode: 'speech_locked',
    canShift: true,
    locked: false,
    audioLayer: 'music_bed',
    notes: ['Ducking begins before the phrase and recovers after the caption leaves.'],
  },
  {
    ...baseRecord('timing_event_lake_como_montage_music_cue'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    anchorId: 'timing_anchor_lake_como_music_downbeat',
    sourceSystem: 'music_cue',
    sourceRecordId: 'music_cue_lake_como_montage',
    eventType: 'music_cue_start',
    trackType: 'music',
    label: 'Montage music cue begins',
    startTimeSeconds: 18,
    endTimeSeconds: 29,
    durationSeconds: 11,
    frameStart: frame(18),
    frameEnd: frame(29),
    priority: 'high',
    syncMode: 'beat_locked',
    canShift: false,
    locked: true,
    audioLayer: 'music_bed',
    notes: ['Montage cuts and transition whooshes can follow this beat grid.'],
  },
  {
    ...baseRecord('timing_event_lake_como_cut_to_montage'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    anchorId: 'timing_anchor_lake_como_music_downbeat',
    sourceSystem: 'cut_decision',
    sourceRecordId: 'cut_decision_lake_como_montage_entry',
    eventType: 'cut',
    trackType: 'cuts',
    label: 'Cut into boat montage',
    startTimeSeconds: 18,
    endTimeSeconds: 18,
    durationSeconds: 0,
    frameStart: frame(18),
    frameEnd: frame(18),
    priority: 'high',
    syncMode: 'beat_locked',
    canShift: true,
    locked: false,
    notes: ['Cut lands on downbeat and not over dialogue.'],
  },
  {
    ...baseRecord('timing_event_lake_como_stroke_route_start'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    sourceSystem: 'stroke_motion',
    sourceRecordId: 'stroke_motion_beat_lake_como_route_line',
    eventType: 'stroke_motion_start',
    trackType: 'stroke_motion',
    label: 'Route line Stroke Motion starts',
    startTimeSeconds: 22.2,
    endTimeSeconds: 23.4,
    durationSeconds: 1.2,
    frameStart: frame(22.2),
    frameEnd: frame(23.4),
    priority: 'medium',
    syncMode: 'visual_motion_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'route_line',
    signatureSystem: 'stroke_motion',
    notes: ['Draw line with the boat movement rather than on a random beat.'],
  },
  {
    ...baseRecord('timing_event_lake_como_stroke_route_complete'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_boat_montage',
    anchorId: 'timing_anchor_lake_como_stroke_complete',
    sourceSystem: 'stroke_motion',
    sourceRecordId: 'stroke_motion_beat_lake_como_route_line',
    eventType: 'stroke_motion_complete',
    trackType: 'stroke_motion',
    label: 'Route line Stroke Motion completes',
    startTimeSeconds: 23.4,
    endTimeSeconds: 23.4,
    durationSeconds: 0,
    frameStart: frame(23.4),
    frameEnd: frame(23.4),
    priority: 'medium',
    syncMode: 'visual_motion_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'route_line',
    signatureSystem: 'stroke_motion',
    notes: ['Completion is a reusable timing anchor for optional SFX.'],
  },
  {
    ...baseRecord('timing_event_lake_como_real_motion_settle'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_food_social',
    anchorId: 'timing_anchor_lake_como_real_motion_settle',
    sourceSystem: 'real_motion',
    sourceRecordId: 'real_motion_object_limoncello_card',
    eventType: 'real_motion_settle',
    trackType: 'real_motion',
    label: 'Limoncello card settles beside plate',
    startTimeSeconds: 33.2,
    hitTimeSeconds: 34.1,
    endTimeSeconds: 35.4,
    durationSeconds: 2.2,
    frameStart: frame(33.2),
    frameHit: frame(34.1),
    frameEnd: frame(35.4),
    priority: 'medium',
    syncMode: 'visual_motion_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'real_motion_card',
    signatureSystem: 'real_motion',
    notes: ['Avoids face and caption lanes.'],
  },
  {
    ...baseRecord('timing_event_lake_como_outro_cta_reveal'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_outro_resolve',
    anchorId: 'timing_anchor_lake_como_music_resolve',
    sourceSystem: 'graphic_design',
    sourceRecordId: 'graphic_design_lake_como_cta',
    eventType: 'cta_reveal',
    trackType: 'cta',
    label: 'Soft outro CTA reveal',
    startTimeSeconds: 42.8,
    endTimeSeconds: 45,
    durationSeconds: 2.2,
    frameStart: frame(42.8),
    frameEnd: frame(45),
    priority: 'medium',
    syncMode: 'beat_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'outro_cta',
    signatureSystem: 'graphic_design',
    notes: ['CTA lands on music resolve with a soft SFX tail.'],
  },
  {
    ...baseRecord('timing_event_lake_como_render_marker'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    sourceSystem: 'render_job',
    sourceRecordId: 'render_job_lake_como_preview',
    eventType: 'render_marker',
    trackType: 'render_markers',
    label: 'Render manifest ready marker',
    startTimeSeconds: 0,
    endTimeSeconds: 45,
    durationSeconds: 45,
    frameStart: 0,
    frameEnd: 1350,
    priority: 'high',
    syncMode: 'frame_locked',
    canShift: false,
    locked: true,
    notes: ['Worker should use manifest events, not re-time from chat.'],
  },
  {
    ...baseRecord('timing_event_faith_caption_voice_first'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_faith_core_teaching',
    anchorId: 'timing_anchor_faith_sentence_end',
    sourceSystem: 'caption_plan',
    sourceRecordId: 'caption_plan_faith_voice_first',
    eventType: 'caption_on',
    trackType: 'captions',
    label: 'Voice-first teaching caption',
    startTimeSeconds: 12.6,
    endTimeSeconds: 16.9,
    durationSeconds: 4.3,
    frameStart: frame(12.6),
    frameEnd: frame(16.9),
    priority: 'critical',
    syncMode: 'speech_locked',
    canShift: true,
    locked: false,
    visibilityLayer: 'captions',
    notes: ['Caption follows speech and avoids over-styling.'],
  },
  {
    ...baseRecord('timing_event_faith_music_bed'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    sourceSystem: 'music_mix',
    sourceRecordId: 'music_mix_faith_subtle',
    eventType: 'music_cue_start',
    trackType: 'music',
    label: 'Subtle faith teaching music bed',
    startTimeSeconds: 0,
    endTimeSeconds: 32,
    durationSeconds: 32,
    frameStart: 0,
    frameEnd: 960,
    priority: 'medium',
    syncMode: 'speech_locked',
    canShift: false,
    locked: true,
    audioLayer: 'music_bed',
    notes: ['Music is present but never the timing authority.'],
  },
  {
    ...baseRecord('timing_event_faith_pause_hold'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_faith_emotional_pause',
    anchorId: 'timing_anchor_faith_emotional_pause',
    sourceSystem: 'story_beat',
    sourceRecordId: 'story_beat_faith_reflection_pause',
    eventType: 'manual_marker',
    trackType: 'story_beats',
    label: 'Preserve emotional pause',
    startTimeSeconds: 20.2,
    endTimeSeconds: 22.1,
    durationSeconds: 1.9,
    frameStart: frame(20.2),
    frameEnd: frame(22.1),
    priority: 'critical',
    syncMode: 'emotion_locked',
    canShift: false,
    locked: true,
    notes: ['No cut, SFX, or caption rush should fill this silence.'],
  },
  {
    ...baseRecord('timing_event_faith_qa_marker'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    sourceSystem: 'qa_report',
    sourceRecordId: 'qa_report_faith_timing',
    eventType: 'qa_marker',
    trackType: 'qa_markers',
    label: 'QA checks emotional pause preservation',
    startTimeSeconds: 18,
    endTimeSeconds: 22.5,
    durationSeconds: 4.5,
    frameStart: frame(18),
    frameEnd: frame(22.5),
    priority: 'critical',
    syncMode: 'emotion_locked',
    canShift: false,
    locked: true,
    notes: ['Blocking QA marker if the pause is removed.'],
  },
]

export const mockTimingDependencies: TimingDependencyRecord[] = [
  {
    ...baseRecord('timing_dependency_title_sfx_same_frame'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    fromEventId: 'timing_event_lake_como_title_sfx_hit',
    toEventId: 'timing_event_lake_como_title_graphic_reveal',
    fromAnchorId: 'timing_anchor_lake_como_title_hit',
    toAnchorId: 'timing_anchor_lake_como_title_hit',
    dependencyType: 'hit_on_same_frame',
    minOffsetSeconds: 0,
    maxOffsetSeconds: 0,
    required: true,
    reason: 'The title hit must land exactly as the chapter title appears.',
    notes: ['This is the canonical SFX hit-to-graphic reveal dependency.'],
  },
  {
    ...baseRecord('timing_dependency_music_duck_during_dialogue'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    fromEventId: 'timing_event_lake_como_music_duck_start',
    toEventId: 'timing_event_lake_como_dialogue_caption_on',
    dependencyType: 'duck_during',
    minOffsetSeconds: -0.3,
    maxOffsetSeconds: 0.3,
    required: true,
    reason: 'Music ducking must cover spoken dialogue and its caption window.',
    notes: ['Voice clarity outranks music bed energy.'],
  },
  {
    ...baseRecord('timing_dependency_caption_not_real_motion'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    fromEventId: 'timing_event_lake_como_dialogue_caption_on',
    toEventId: 'timing_event_lake_como_real_motion_settle',
    dependencyType: 'must_not_overlap',
    required: true,
    reason: 'Captions must not collide with Real Motion overlays or faces.',
    notes: ['Future service can resolve by shifting overlay later or changing safe zone.'],
  },
  {
    ...baseRecord('timing_dependency_stroke_complete_anchor'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    fromEventId: 'timing_event_lake_como_stroke_route_complete',
    toAnchorId: 'timing_anchor_lake_como_stroke_complete',
    dependencyType: 'sync_to_anchor',
    required: true,
    reason: 'Stroke Motion completion should land on the route meaning anchor.',
    notes: ['Signature animation timing follows meaning, not random motion.'],
  },
  {
    ...baseRecord('timing_dependency_faith_preserve_pause'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    fromEventId: 'timing_event_faith_pause_hold',
    fromAnchorId: 'timing_anchor_faith_emotional_pause',
    dependencyType: 'must_not_overlap',
    required: true,
    reason: 'The emotional pause should not be covered by captions, SFX, or abrupt cuts.',
    notes: ['This guards serious teaching tone.'],
  },
]

export const mockTimingConflicts: TimingConflictRecord[] = [
  {
    ...baseRecord('timing_conflict_lake_como_caption_real_motion'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    conflictType: 'caption_overlay_collision',
    severity: 'medium',
    relatedEventIds: [
      'timing_event_lake_como_dialogue_caption_on',
      'timing_event_lake_como_real_motion_settle',
    ],
    relatedAnchorIds: ['timing_anchor_lake_como_real_motion_settle'],
    sourceSystems: ['caption_plan', 'real_motion'],
    timeRange: range(33.2, 35.4),
    description: 'A future Real Motion card could enter the caption safe lane.',
    whyItMatters: 'Caption readability and face/product visibility must stay protected.',
    recommendedAdjustment: 'shift_later',
    blocksRender: false,
    requiresUserReview: false,
    status: 'resolved',
  },
  {
    ...baseRecord('timing_conflict_faith_pause_removed'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    conflictType: 'emotional_pause_removed',
    severity: 'critical',
    relatedEventIds: ['timing_event_faith_pause_hold'],
    relatedAnchorIds: ['timing_anchor_faith_emotional_pause'],
    sourceSystems: ['story_beat', 'cut_decision'],
    timeRange: range(20.2, 22.1),
    description: 'A hypothetical pace cut would remove the reflection pause.',
    whyItMatters: 'The pause carries meaning and should not be trimmed for speed.',
    recommendedAdjustment: 'preserve_pause',
    blocksRender: true,
    requiresUserReview: true,
    status: 'open',
  },
]

export const mockTimingConflictResolutions: TimingConflictResolutionRecord[] = [
  {
    ...baseRecord('timing_resolution_lake_como_shift_real_motion'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    timingConflictId: 'timing_conflict_lake_como_caption_real_motion',
    adjustmentType: 'shift_later',
    affectedEventIds: ['timing_event_lake_como_real_motion_settle'],
    affectedAnchorIds: ['timing_anchor_lake_como_real_motion_settle'],
    timeShiftSeconds: 1.1,
    newTimeRange: range(34.3, 36.5),
    reason: 'Move the Real Motion settle after the caption-heavy phrase.',
    approved: true,
    approvedByUserId: 'user_demo_creator',
  },
  {
    ...baseRecord('timing_resolution_faith_preserve_pause'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    timingConflictId: 'timing_conflict_faith_pause_removed',
    adjustmentType: 'preserve_pause',
    affectedEventIds: ['timing_event_faith_pause_hold'],
    affectedAnchorIds: ['timing_anchor_faith_emotional_pause'],
    reason: 'Keep the reflective pause and avoid pace cuts or decorative SFX.',
    approved: false,
  },
]

export const mockStoryTimingQAChecks: StoryTimingQACheckRecord[] = [
  {
    ...baseRecord('story_timing_qa_lake_como_caption_sync'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_dialogue_bed',
    checkType: 'caption_sync',
    status: 'passed',
    score: 96,
    timeRange: range(7.6, 11.2),
    relatedEventIds: ['timing_event_lake_como_dialogue_caption_on'],
    relatedAnchorIds: ['timing_anchor_lake_como_dialogue_phrase'],
    summary: 'Caption enters and leaves with the spoken phrase.',
    blocksRender: false,
    requiresManualReview: false,
  },
  {
    ...baseRecord('story_timing_qa_lake_como_sfx_hit'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_lake_como_chapter_title',
    checkType: 'sfx_hit_alignment',
    status: 'passed',
    score: 94,
    timeRange: range(14, 14.72),
    relatedEventIds: [
      'timing_event_lake_como_title_sfx_start',
      'timing_event_lake_como_title_sfx_hit',
    ],
    relatedAnchorIds: ['timing_anchor_lake_como_title_hit'],
    summary: 'SFX hit lands on the chapter title frame and exits before it feels loud.',
    blocksRender: false,
    requiresManualReview: false,
  },
  {
    ...baseRecord('story_timing_qa_lake_como_render_manifest'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    checkType: 'render_manifest_integrity',
    status: 'passed',
    score: 98,
    timeRange: range(0, 45),
    relatedEventIds: ['timing_event_lake_como_render_marker'],
    relatedAnchorIds: [],
    summary: 'Render manifest contains track ordering, event timing, dependencies, and resolved conflicts.',
    blocksRender: false,
    requiresManualReview: false,
  },
  {
    ...baseRecord('story_timing_qa_faith_pause'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    segmentId: 'story_timing_segment_faith_emotional_pause',
    checkType: 'emotional_pause_preservation',
    status: 'requires_manual_review',
    score: 88,
    timeRange: range(20.2, 22.1),
    relatedEventIds: ['timing_event_faith_pause_hold'],
    relatedAnchorIds: ['timing_anchor_faith_emotional_pause'],
    summary: 'The pause is marked as critical and should be reviewed before any trim change.',
    recommendedFix: 'Preserve the pause unless the user explicitly approves a shorter cut.',
    blocksRender: true,
    requiresManualReview: true,
  },
]

export const mockRenderTimingManifests: RenderTimingManifestRecord[] = [
  {
    ...baseRecord('render_timing_manifest_lake_como_preview'),
    masterTimingMapId: MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
    projectId: LAKE_COMO_PROJECT_ID,
    editPlanId: LAKE_COMO_EDIT_PLAN_ID,
    renderJobId: 'render_job_lake_como_preview',
    status: 'ready_for_worker',
    durationSeconds: 45,
    frameRate: 30,
    tracks: [
      {
        id: 'render_track_lake_como_cuts',
        trackType: 'cuts',
        label: 'Cut timing',
        layerOrder: 1,
        sourceSystem: 'cut_decision',
        eventIds: ['timing_event_lake_como_cut_to_montage'],
        notes: ['Cuts are output timeline events.'],
      },
      {
        id: 'render_track_lake_como_music',
        trackType: 'music',
        label: 'Music and ducking',
        layerOrder: 2,
        sourceSystem: 'music_mix',
        eventIds: [
          'timing_event_lake_como_music_duck_start',
          'timing_event_lake_como_montage_music_cue',
        ],
        notes: ['Music timing protects speech then supports montage.'],
      },
      {
        id: 'render_track_lake_como_sfx',
        trackType: 'sfx',
        label: 'SFX hits',
        layerOrder: 3,
        sourceSystem: 'sfx_alignment',
        eventIds: [
          'timing_event_lake_como_title_sfx_start',
          'timing_event_lake_como_title_sfx_hit',
        ],
        notes: ['Only edit-layer polish SFX appear here.'],
      },
      {
        id: 'render_track_lake_como_overlays',
        trackType: 'graphic_design',
        label: 'Signature overlays',
        layerOrder: 4,
        sourceSystem: 'graphic_design',
        eventIds: [
          'timing_event_lake_como_title_graphic_reveal',
          'timing_event_lake_como_outro_cta_reveal',
        ],
        notes: ['Overlay timing follows readability and safe zones.'],
      },
    ],
    events: [
      {
        eventId: 'timing_event_lake_como_title_sfx_start',
        eventType: 'sfx_start',
        trackType: 'sfx',
        startTimeSeconds: 14,
        hitTimeSeconds: 14.2,
        endTimeSeconds: 14.72,
        sourceSystem: 'sfx_alignment',
        sourceRecordId: 'sfx_alignment_lake_como_title_hit',
        payload: {
          audioLayer: 'sfx_title_hit',
          projectOnly: true,
          gainHintDb: -18,
        },
      },
      {
        eventId: 'timing_event_lake_como_title_graphic_reveal',
        eventType: 'graphic_reveal',
        trackType: 'graphic_design',
        startTimeSeconds: 14.2,
        endTimeSeconds: 17.4,
        sourceSystem: 'graphic_design',
        sourceRecordId: 'graphic_design_title_card_lake_como',
        payload: {
          layer: 'title_card',
          safeZone: 'center_safe',
          minimumReadSeconds: 2.4,
        },
      },
      {
        eventId: 'timing_event_lake_como_dialogue_caption_on',
        eventType: 'caption_on',
        trackType: 'captions',
        startTimeSeconds: 7.6,
        endTimeSeconds: 11.2,
        sourceSystem: 'caption_plan',
        sourceRecordId: 'caption_plan_lake_como_dialogue',
        payload: {
          captionLane: 'lower_safe',
          voiceFirst: true,
        },
      },
      {
        eventId: 'timing_event_lake_como_real_motion_settle',
        eventType: 'real_motion_settle',
        trackType: 'real_motion',
        startTimeSeconds: 33.2,
        hitTimeSeconds: 34.1,
        endTimeSeconds: 35.4,
        sourceSystem: 'real_motion',
        sourceRecordId: 'real_motion_object_limoncello_card',
        payload: {
          faceSafe: true,
          avoidCaptionLane: true,
        },
      },
    ],
    dependencies: [
      'timing_dependency_title_sfx_same_frame',
      'timing_dependency_music_duck_during_dialogue',
      'timing_dependency_caption_not_real_motion',
    ],
    conflictsResolved: ['timing_resolution_lake_como_shift_real_motion'],
    readyForRender: true,
    workerNotes: [
      'Use frame numbers derived from the master map timebase.',
      'Do not reinterpret SFX hit placement from raw prompt text.',
    ],
  },
  {
    ...baseRecord('render_timing_manifest_faith_preview'),
    masterTimingMapId: MOCK_FAITH_MASTER_TIMING_MAP_ID,
    projectId: FAITH_PROJECT_ID,
    editPlanId: FAITH_EDIT_PLAN_ID,
    renderJobId: 'render_job_faith_preview',
    status: 'draft',
    durationSeconds: 32,
    frameRate: 30,
    tracks: [
      {
        id: 'render_track_faith_captions',
        trackType: 'captions',
        label: 'Voice-first captions',
        layerOrder: 1,
        sourceSystem: 'caption_plan',
        eventIds: ['timing_event_faith_caption_voice_first'],
        notes: ['Caption timing follows speech and teaching meaning.'],
      },
      {
        id: 'render_track_faith_pause_markers',
        trackType: 'story_beats',
        label: 'Meaningful pause markers',
        layerOrder: 2,
        sourceSystem: 'story_beat',
        eventIds: ['timing_event_faith_pause_hold'],
        notes: ['Pause markers block over-tight trims.'],
      },
    ],
    events: [
      {
        eventId: 'timing_event_faith_caption_voice_first',
        eventType: 'caption_on',
        trackType: 'captions',
        startTimeSeconds: 12.6,
        endTimeSeconds: 16.9,
        sourceSystem: 'caption_plan',
        sourceRecordId: 'caption_plan_faith_voice_first',
        payload: {
          voiceFirst: true,
          style: 'simple_readable',
        },
      },
      {
        eventId: 'timing_event_faith_pause_hold',
        eventType: 'manual_marker',
        trackType: 'story_beats',
        startTimeSeconds: 20.2,
        endTimeSeconds: 22.1,
        sourceSystem: 'story_beat',
        sourceRecordId: 'story_beat_faith_reflection_pause',
        payload: {
          preservePause: true,
          noSfx: true,
        },
      },
    ],
    dependencies: ['timing_dependency_faith_preserve_pause'],
    conflictsResolved: [],
    readyForRender: false,
    workerNotes: [
      'Requires manual review because emotional pause preservation is critical.',
      'No SFX or beat cut should be added over the reflection pause.',
    ],
  },
]

const byMap = <T extends { masterTimingMapId: ID }>(
  records: T[],
  masterTimingMapId: ID,
): T[] => records.filter((record) => record.masterTimingMapId === masterTimingMapId)

export const mockLakeComoStoryTimingBundle = {
  masterTimingMap: mockMasterTimingMaps[0],
  segments: byMap(mockStoryTimingSegments, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  anchors: byMap(mockTimingAnchors, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  events: byMap(mockTimingEvents, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  dependencies: byMap(mockTimingDependencies, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  conflicts: byMap(mockTimingConflicts, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  conflictResolutions: byMap(
    mockTimingConflictResolutions,
    MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
  ),
  qaChecks: byMap(mockStoryTimingQAChecks, MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID),
  renderManifest: byMap(
    mockRenderTimingManifests,
    MOCK_LAKE_COMO_MASTER_TIMING_MAP_ID,
  )[0],
}

export const mockFaithStoryTimingBundle = {
  masterTimingMap: mockMasterTimingMaps[1],
  segments: byMap(mockStoryTimingSegments, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  anchors: byMap(mockTimingAnchors, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  events: byMap(mockTimingEvents, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  dependencies: byMap(mockTimingDependencies, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  conflicts: byMap(mockTimingConflicts, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  conflictResolutions: byMap(
    mockTimingConflictResolutions,
    MOCK_FAITH_MASTER_TIMING_MAP_ID,
  ),
  qaChecks: byMap(mockStoryTimingQAChecks, MOCK_FAITH_MASTER_TIMING_MAP_ID),
  renderManifest: byMap(
    mockRenderTimingManifests,
    MOCK_FAITH_MASTER_TIMING_MAP_ID,
  )[0],
}

export const mockStoryTimingRecords = {
  masterTimingMaps: mockMasterTimingMaps,
  storyTimingSegments: mockStoryTimingSegments,
  timingAnchors: mockTimingAnchors,
  timingEvents: mockTimingEvents,
  timingDependencies: mockTimingDependencies,
  timingConflicts: mockTimingConflicts,
  timingConflictResolutions: mockTimingConflictResolutions,
  storyTimingQAChecks: mockStoryTimingQAChecks,
  renderTimingManifests: mockRenderTimingManifests,
}
