import {
  MIRELO_SFX_FUTURE_MODEL_NAME,
  MMAUDIO_FUTURE_MODEL_NAME,
} from '../types/sfx-director'
import type {
  SFXAnchorType,
  SFXCostSensitivity,
  SFXDecisionState,
  SFXGeneratedAssetRecord,
  SFXGeneratedDurationPolicy,
  SFXGenerationStatus,
  SFXLibraryCandidateRecord,
  SFXLibrarySearchPlanRecord,
  SFXMixPlanRecord,
  SFXMixPriority,
  SFXPromptAdapterTestRecord,
  SFXPromptStyle,
  SFXPromptPlanRecord,
  SFXProvider,
  SFXProviderRole,
  SFXProviderRouteRecord,
  SFXQAIssue,
  SFXQARecommendedAction,
  SFXQAReportRecord,
  SFXQAStatus,
  SFXQualityTarget,
  SFXRegenerationDecisionRecord,
  SFXReuseStatus,
  SFXSourceFootagePolicy,
  SFXTargetLayer,
  SFXTimingAlignmentRecord,
  SFXTimingPriority,
  SFXTrimPlanRecord,
  SFXUsageRecord,
  SFXVolumeProfile,
  SFXEventPlanRecord,
} from '../types/sfx-director'
import type { AudioAssetOrigin, AudioLicenseScope, SfxUseCase } from '../types/audio-music'
import type { CreditImpact, ID, Seconds } from '../types/shared'
import type { EditQualityLevel, SoundEffectType } from '../types/edit-quality'
import type { SignatureSystem } from '../types/signature-systems'

export const mockSFXDirectorTimestamp = '2026-05-19T12:00:00.000Z'

const PROJECT_ID = 'project_sfx_director_mock_001'
const EDIT_PLAN_ID = 'edit_plan_sfx_director_mock_001'
const WORKSPACE_ID = 'workspace_sfx_director_mock_001'

interface SFXDirectorScenarioSeed {
  slug: string
  eventLabel: string
  targetLayer: SFXTargetLayer
  useCase: SfxUseCase
  legacySoundEffectType?: SoundEffectType
  decisionState: SFXDecisionState
  sourceFootagePolicy: SFXSourceFootagePolicy
  reason: string
  sceneContext: string
  videoTone: string
  editLevel: EditQualityLevel
  signatureSystem?: SignatureSystem
  anchorType: SFXAnchorType
  anchorTimeSeconds: Seconds
  startTimeSeconds?: Seconds
  hitTimeSeconds?: Seconds
  endTimeSeconds?: Seconds
  timingPriority: SFXTimingPriority
  volumeProfile: SFXVolumeProfile
  mixPriority: SFXMixPriority
  creditImpact: CreditImpact
  requiresApproval: boolean
  userVisibleSummary: string
  avoidRules: string[]
  mustFollowRules: string[]
  status: SFXGenerationStatus
  recommendedProvider: SFXProvider
  providerRole: SFXProviderRole
  fallbackProvider?: SFXProvider
  routeReason: string
  useInternalLibraryFirst: boolean
  useMMAudioForDraft: boolean
  useMireloForProduction: boolean
  costSensitivity: SFXCostSensitivity
  qualityTarget: SFXQualityTarget
  modelName: string
  promptStyle: SFXPromptStyle
  prompt: string
  negativePrompt: string
  tags: string[]
  durationNeededSeconds: Seconds
  durationToGenerateSeconds: Seconds
  generatedDurationPolicy: SFXGeneratedDurationPolicy
  textureWords: string[]
  energyWords: string[]
  styleWords: string[]
  avoidWords: string[]
  timingInstructions: string[]
  mixInstructions: string[]
  promptWarnings: string[]
  generated: boolean
  origin: AudioAssetOrigin
  reuseStatus: SFXReuseStatus
  qaStatus: SFXQAStatus
  licenseScope: AudioLicenseScope
  trimStartSeconds?: Seconds
  trimEndSeconds?: Seconds
  detectedHitTimeSeconds?: Seconds
  qaRecommendedAction: SFXQARecommendedAction
  qaOverallScore: number
  qaIssues: SFXQAIssue[]
  libraryCandidate: boolean
  libraryCandidateReason?: string
}

const scenarioSeeds: SFXDirectorScenarioSeed[] = [
  {
    slug: 'luxury_transition_whoosh',
    eventLabel: 'Soft premium transition whoosh',
    targetLayer: 'transition',
    useCase: 'transition_soft_whoosh',
    legacySoundEffectType: 'soft_whoosh',
    decisionState: 'needed',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'The premium travel cut needs a soft audio bridge so the visual transition feels intentional without overpowering the music.',
    sceneContext: 'Lake Como-style luxury vacation video moving from terrace view to boat detail.',
    videoTone: 'premium travel, quiet luxury, smooth movement',
    editLevel: 'premium_signature',
    signatureSystem: 'sound_sync',
    anchorType: 'cut',
    anchorTimeSeconds: 12.42,
    startTimeSeconds: 12.09,
    hitTimeSeconds: 12.42,
    endTimeSeconds: 12.92,
    timingPriority: 'frame_accurate',
    volumeProfile: 'premium_soft',
    mixPriority: 'music_support',
    creditImpact: 'medium',
    requiresApproval: true,
    userVisibleSummary: 'Add one soft premium transition whoosh on the lake-to-boat cut.',
    avoidRules: ['no harsh riser', 'no cartoon whoosh', 'do not cover dialogue'],
    mustFollowRules: ['hit exactly on the cut', 'duck under voice if speech appears'],
    status: 'qa_passed',
    recommendedProvider: 'mirelo_sfx_v1_5',
    providerRole: 'production_final',
    fallbackProvider: 'mmaudio_v',
    routeReason: 'Mirelo is planned for production-quality premium transition polish; MMAudio can draft timing first.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: true,
    costSensitivity: 'quality_first',
    qualityTarget: 'premium',
    modelName: MIRELO_SFX_FUTURE_MODEL_NAME,
    promptStyle: 'structured_sentence',
    prompt:
      'Soft premium transition whoosh, clean airy movement, subtle luxury tone, short smooth tail, no harsh riser, no cartoon, no sci-fi.',
    negativePrompt: 'harsh riser, cartoon, sci-fi, loud impact, distorted sweep',
    tags: ['premium', 'transition', 'soft_whoosh', 'travel', 'clean_tail'],
    durationNeededSeconds: 0.55,
    durationToGenerateSeconds: 2.5,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['airy', 'smooth', 'clean'],
    energyWords: ['low', 'premium', 'subtle'],
    styleWords: ['luxury', 'travel', 'polished'],
    avoidWords: ['harsh', 'cartoon', 'sci-fi'],
    timingInstructions: ['start 8 frames before cut', 'hit exactly on cut', 'tail 12 frames after cut'],
    mixInstructions: ['premium_soft volume', 'briefly sit above music at hit', 'duck under voice'],
    promptWarnings: [],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'candidate_for_library',
    qaStatus: 'passed',
    licenseScope: 'terms_review_required',
    trimStartSeconds: 0.82,
    trimEndSeconds: 1.38,
    detectedHitTimeSeconds: 1.02,
    qaRecommendedAction: 'use',
    qaOverallScore: 96,
    qaIssues: [],
    libraryCandidate: true,
    libraryCandidateReason: 'General-purpose premium transition cue with clean QA and no private source context.',
  },
  {
    slug: 'stroke_motion_line_draw',
    eventLabel: 'Stroke Motion line draw sound',
    targetLayer: 'stroke_motion',
    useCase: 'stroke_line_trace',
    legacySoundEffectType: 'stroke_draw_sound',
    decisionState: 'needed',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'The drawn line completes a signature explanation beat and needs a quiet synchronized texture.',
    sceneContext: 'Stroke Motion draws a curved path around a key phrase in an educational short.',
    videoTone: 'clear, thoughtful, professional',
    editLevel: 'signature',
    signatureSystem: 'stroke_motion',
    anchorType: 'stroke_motion_completion',
    anchorTimeSeconds: 18.2,
    startTimeSeconds: 17.86,
    hitTimeSeconds: 18.2,
    endTimeSeconds: 18.55,
    timingPriority: 'frame_accurate',
    volumeProfile: 'subtle_polish',
    mixPriority: 'signature_sync',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Add a subtle line-trace sound to the Stroke Motion completion.',
    avoidRules: ['no loud scratch', 'no marker squeak', 'no cartoon effect'],
    mustFollowRules: ['sync to stroke completion', 'stay under speech'],
    status: 'qa_passed',
    recommendedProvider: 'mirelo_sfx_v1_5',
    providerRole: 'production_final',
    fallbackProvider: 'mmaudio_v',
    routeReason: 'The cue is a signature edit-layer sound, so production polish is preferred.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: true,
    costSensitivity: 'balanced',
    qualityTarget: 'production',
    modelName: MIRELO_SFX_FUTURE_MODEL_NAME,
    promptStyle: 'structured_sentence',
    prompt: 'Gentle stroke drawing sound, soft pencil-like line trace, light texture, no loud scratch, no cartoon effect, short clean tail.',
    negativePrompt: 'loud scratch, squeak, cartoon, harsh scrape',
    tags: ['stroke_motion', 'line_trace', 'soft_pencil', 'subtle'],
    durationNeededSeconds: 0.65,
    durationToGenerateSeconds: 2.4,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['pencil-like', 'soft', 'textured'],
    energyWords: ['low', 'gentle'],
    styleWords: ['educational', 'clean', 'signature'],
    avoidWords: ['scratchy', 'cartoon', 'loud'],
    timingInstructions: ['start before draw completion', 'hit on final stroke completion'],
    mixInstructions: ['subtle_polish volume', 'voice-first ducking'],
    promptWarnings: [],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'candidate_for_library',
    qaStatus: 'passed',
    licenseScope: 'terms_review_required',
    trimStartSeconds: 0.58,
    trimEndSeconds: 1.24,
    detectedHitTimeSeconds: 0.92,
    qaRecommendedAction: 'use',
    qaOverallScore: 94,
    qaIssues: [],
    libraryCandidate: true,
    libraryCandidateReason: 'Reusable Stroke Motion line-trace texture after provider terms review.',
  },
  {
    slug: 'graphic_card_reveal',
    eventLabel: 'Graphic Design card reveal sound',
    targetLayer: 'graphic_design',
    useCase: 'graphic_card_reveal',
    legacySoundEffectType: 'subtle_pop',
    decisionState: 'optional',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'A clean reveal tick can clarify the VisualExplain card entrance without making the edit busy.',
    sceneContext: 'A concise pricing comparison card appears beside the speaker.',
    videoTone: 'business polished, calm, useful',
    editLevel: 'pro',
    signatureSystem: 'graphic_design',
    anchorType: 'graphic_reveal',
    anchorTimeSeconds: 24.1,
    startTimeSeconds: 24.02,
    hitTimeSeconds: 24.1,
    endTimeSeconds: 24.42,
    timingPriority: 'frame_accurate',
    volumeProfile: 'subtle_polish',
    mixPriority: 'effect_moment',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Optional subtle card reveal sound for the pricing comparison.',
    avoidRules: ['do not sound like a phone notification', 'do not distract from the speaker'],
    mustFollowRules: ['keep very low under speech', 'align to card reveal'],
    status: 'qa_passed',
    recommendedProvider: 'mmaudio_v',
    providerRole: 'basic_pro_fallback',
    fallbackProvider: 'reeditpro_internal_library',
    routeReason: 'Pro edit can use a cheaper draft/fallback sound unless production polish is explicitly required.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: false,
    costSensitivity: 'balanced',
    qualityTarget: 'preview',
    modelName: MMAUDIO_FUTURE_MODEL_NAME,
    promptStyle: 'video_conditioned_short_prompt',
    prompt: 'subtle graphic reveal sound',
    negativePrompt: 'loud notification, cartoon pop, harsh click',
    tags: ['graphic_design', 'card_reveal', 'subtle_click'],
    durationNeededSeconds: 0.35,
    durationToGenerateSeconds: 2,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['clean', 'digital', 'soft'],
    energyWords: ['low'],
    styleWords: ['corporate', 'polished'],
    avoidWords: ['notification', 'cartoon', 'harsh'],
    timingInstructions: ['hit on card reveal frame'],
    mixInstructions: ['lower under speech', 'short fade-out'],
    promptWarnings: ['MMAudio prompt intentionally stays short because it is video-conditioned.'],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'approved_for_project',
    qaStatus: 'passed',
    licenseScope: 'project_only',
    trimStartSeconds: 0.35,
    trimEndSeconds: 0.78,
    detectedHitTimeSeconds: 0.45,
    qaRecommendedAction: 'use_with_mix_adjustment',
    qaOverallScore: 89,
    qaIssues: [],
    libraryCandidate: false,
  },
  {
    slug: 'real_motion_object_settle',
    eventLabel: 'Real Motion object settle sound',
    targetLayer: 'real_motion',
    useCase: 'real_motion_object_settle',
    legacySoundEffectType: 'object_whoosh',
    decisionState: 'needed',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'The generated object movement would feel empty without a low realistic settle sound.',
    sceneContext: 'A Real Motion paper note slides into the frame and settles on a desk.',
    videoTone: 'realistic, restrained, tactile',
    editLevel: 'premium_signature',
    signatureSystem: 'real_motion',
    anchorType: 'real_motion_object_settle',
    anchorTimeSeconds: 31.6,
    startTimeSeconds: 31.36,
    hitTimeSeconds: 31.6,
    endTimeSeconds: 32.05,
    timingPriority: 'frame_accurate',
    volumeProfile: 'subtle_polish',
    mixPriority: 'signature_sync',
    creditImpact: 'medium',
    requiresApproval: true,
    userVisibleSummary: 'Add a realistic soft object-settle sound for the Real Motion paper note.',
    avoidRules: ['no heavy impact', 'no cinematic boom', 'no unrealistic thud'],
    mustFollowRules: ['room-match the sound', 'hit on object settle'],
    status: 'qa_passed',
    recommendedProvider: 'mirelo_sfx_v1_5',
    providerRole: 'premium_signature',
    fallbackProvider: 'mmaudio_v',
    routeReason: 'Real Motion final polish needs a production-quality realistic object sound.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: true,
    costSensitivity: 'quality_first',
    qualityTarget: 'premium',
    modelName: MIRELO_SFX_FUTURE_MODEL_NAME,
    promptStyle: 'structured_sentence',
    prompt: 'Soft Real Motion object settle sound, realistic small paper movement, room-matched, low volume, no heavy impact, no cinematic boom.',
    negativePrompt: 'heavy impact, boom, cartoon, metallic clang',
    tags: ['real_motion', 'object_settle', 'paper', 'room_matched'],
    durationNeededSeconds: 0.7,
    durationToGenerateSeconds: 2.7,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['paper', 'soft', 'room-matched'],
    energyWords: ['low', 'realistic'],
    styleWords: ['tactile', 'restrained'],
    avoidWords: ['boom', 'heavy', 'cartoon'],
    timingInstructions: ['hit exactly as object settles'],
    mixInstructions: ['subtle_polish profile', 'match room tone'],
    promptWarnings: [],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'candidate_for_library',
    qaStatus: 'passed',
    licenseScope: 'terms_review_required',
    trimStartSeconds: 0.7,
    trimEndSeconds: 1.42,
    detectedHitTimeSeconds: 0.94,
    qaRecommendedAction: 'use',
    qaOverallScore: 95,
    qaIssues: [],
    libraryCandidate: true,
    libraryCandidateReason: 'General paper settle sound may be reusable if provider terms allow.',
  },
  {
    slug: 'chapter_title_soft_hit',
    eventLabel: 'Chapter title soft hit',
    targetLayer: 'chapter_card',
    useCase: 'transition_subtle_cut_accent',
    legacySoundEffectType: 'light_hit',
    decisionState: 'optional',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'A soft hit can mark the chapter card without breaking the calm tone.',
    sceneContext: 'Chapter title card introduces the next section of a course lesson.',
    videoTone: 'educational, calm, clear',
    editLevel: 'pro',
    signatureSystem: 'sound_sync',
    anchorType: 'chapter_card_reveal',
    anchorTimeSeconds: 44,
    startTimeSeconds: 43.9,
    hitTimeSeconds: 44,
    endTimeSeconds: 44.36,
    timingPriority: 'speech_safe',
    volumeProfile: 'whisper',
    mixPriority: 'voice_first',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Optional whisper-level chapter title hit.',
    avoidRules: ['no dramatic boom', 'do not interrupt teaching tone'],
    mustFollowRules: ['voice-first mix', 'keep whisper-level'],
    status: 'qa_passed',
    recommendedProvider: 'reeditpro_internal_library',
    providerRole: 'internal_library_first_choice',
    fallbackProvider: 'mmaudio_v',
    routeReason: 'A common chapter hit should prefer internal library reuse before generation.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: false,
    costSensitivity: 'lowest_cost',
    qualityTarget: 'preview',
    modelName: 'reeditpro-internal-library',
    promptStyle: 'library_search_tags',
    prompt: 'chapter title soft hit',
    negativePrompt: 'boom, harsh impact, cinematic trailer hit',
    tags: ['chapter_card', 'soft_hit', 'educational', 'whisper'],
    durationNeededSeconds: 0.4,
    durationToGenerateSeconds: 0,
    generatedDurationPolicy: 'custom',
    textureWords: ['soft', 'clean'],
    energyWords: ['low'],
    styleWords: ['educational', 'calm'],
    avoidWords: ['dramatic', 'loud'],
    timingInstructions: ['align to chapter card reveal'],
    mixInstructions: ['whisper profile under voice'],
    promptWarnings: ['Library search prompt only; no provider call implied.'],
    generated: false,
    origin: 'internal_library',
    reuseStatus: 'approved_internal_library',
    qaStatus: 'passed',
    licenseScope: 'approved_internal_library',
    qaRecommendedAction: 'use',
    qaOverallScore: 92,
    qaIssues: [],
    libraryCandidate: false,
  },
  {
    slug: 'cta_reveal_chime',
    eventLabel: 'CTA reveal chime',
    targetLayer: 'cta_reveal',
    useCase: 'cta_success_chime',
    legacySoundEffectType: 'success_chime',
    decisionState: 'optional',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'A clean resolve chime can support the CTA without making the ending feel salesy.',
    sceneContext: 'A final call-to-action button appears over a product demo ending.',
    videoTone: 'clean, helpful, lightly upbeat',
    editLevel: 'pro',
    signatureSystem: 'sound_sync',
    anchorType: 'cta_reveal',
    anchorTimeSeconds: 58.25,
    startTimeSeconds: 58.12,
    hitTimeSeconds: 58.25,
    endTimeSeconds: 58.92,
    timingPriority: 'frame_accurate',
    volumeProfile: 'subtle_polish',
    mixPriority: 'effect_moment',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Add a soft CTA reveal chime at the ending button.',
    avoidRules: ['no app notification tone', 'no loud sparkle'],
    mustFollowRules: ['tail should resolve cleanly', 'do not cover final spoken phrase'],
    status: 'qa_passed',
    recommendedProvider: 'mmaudio_v',
    providerRole: 'cheap_draft_fallback',
    fallbackProvider: 'reeditpro_internal_library',
    routeReason: 'A low-cost short prompt can test CTA timing before any production route.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: false,
    costSensitivity: 'balanced',
    qualityTarget: 'preview',
    modelName: MMAUDIO_FUTURE_MODEL_NAME,
    promptStyle: 'video_conditioned_short_prompt',
    prompt: 'soft success chime',
    negativePrompt: 'phone notification, loud sparkle, arcade sound',
    tags: ['cta', 'success_chime', 'soft_resolve'],
    durationNeededSeconds: 0.7,
    durationToGenerateSeconds: 2.2,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['soft', 'clean'],
    energyWords: ['light', 'positive'],
    styleWords: ['modern', 'helpful'],
    avoidWords: ['notification', 'arcade', 'loud'],
    timingInstructions: ['hit on CTA reveal'],
    mixInstructions: ['short chime under final phrase'],
    promptWarnings: ['MMAudio draft route only; production use still requires QA.'],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'approved_for_project',
    qaStatus: 'passed',
    licenseScope: 'project_only',
    trimStartSeconds: 0.44,
    trimEndSeconds: 1.15,
    detectedHitTimeSeconds: 0.57,
    qaRecommendedAction: 'use_with_mix_adjustment',
    qaOverallScore: 88,
    qaIssues: [],
    libraryCandidate: false,
  },
  {
    slug: 'montage_beat_accent',
    eventLabel: 'Montage beat accent',
    targetLayer: 'montage_hit',
    useCase: 'montage_beat_accent',
    legacySoundEffectType: 'light_hit',
    decisionState: 'needed',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'The montage beat needs a short accent to make the visual hit land cleanly.',
    sceneContext: 'Fitness social montage changes from jump rope to final transformation pose.',
    videoTone: 'energetic, confident, social',
    editLevel: 'signature',
    signatureSystem: 'sound_sync',
    anchorType: 'music_downbeat',
    anchorTimeSeconds: 36.5,
    startTimeSeconds: 36.42,
    hitTimeSeconds: 36.5,
    endTimeSeconds: 36.78,
    timingPriority: 'beat_aligned',
    volumeProfile: 'standard_social',
    mixPriority: 'effect_moment',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Add one beat accent on the fitness montage downbeat.',
    avoidRules: ['no explosion', 'no distorted bass hit'],
    mustFollowRules: ['snap to music downbeat', 'do not clip'],
    status: 'qa_passed',
    recommendedProvider: 'mmaudio_v',
    providerRole: 'cheap_draft_fallback',
    fallbackProvider: 'mirelo_sfx_v1_5',
    routeReason: 'MMAudio is a good low-cost draft route for beat-synced movement ideas.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: false,
    costSensitivity: 'balanced',
    qualityTarget: 'preview',
    modelName: MMAUDIO_FUTURE_MODEL_NAME,
    promptStyle: 'video_conditioned_short_prompt',
    prompt: 'short energetic beat accent',
    negativePrompt: 'explosion, distorted bass, trailer boom',
    tags: ['montage', 'beat_accent', 'fitness', 'standard_social'],
    durationNeededSeconds: 0.3,
    durationToGenerateSeconds: 2,
    generatedDurationPolicy: 'generate_2_to_3_seconds',
    textureWords: ['short', 'clean'],
    energyWords: ['energetic', 'tight'],
    styleWords: ['fitness', 'social'],
    avoidWords: ['explosion', 'boom', 'distorted'],
    timingInstructions: ['hit on music downbeat'],
    mixInstructions: ['briefly sit above music at hit only'],
    promptWarnings: [],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'approved_for_project',
    qaStatus: 'passed',
    licenseScope: 'project_only',
    trimStartSeconds: 0.22,
    trimEndSeconds: 0.54,
    detectedHitTimeSeconds: 0.3,
    qaRecommendedAction: 'use',
    qaOverallScore: 91,
    qaIssues: [],
    libraryCandidate: false,
  },
  {
    slug: 'ambient_bridge',
    eventLabel: 'Soft ambient bridge',
    targetLayer: 'ambient_bridge',
    useCase: 'ambient_soft_bridge',
    legacySoundEffectType: 'ambient_bridge',
    decisionState: 'optional',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'A subtle bridge can smooth the transition between two silent B-roll shots without adding fake source actions.',
    sceneContext: 'Quiet travel B-roll moves from hotel hallway to balcony view.',
    videoTone: 'calm, airy, travel',
    editLevel: 'pro',
    signatureSystem: 'sound_sync',
    anchorType: 'cut',
    anchorTimeSeconds: 15.75,
    startTimeSeconds: 14.95,
    hitTimeSeconds: 15.75,
    endTimeSeconds: 18.9,
    timingPriority: 'loose_background',
    volumeProfile: 'whisper',
    mixPriority: 'ambience_first',
    creditImpact: 'low',
    requiresApproval: true,
    userVisibleSummary: 'Add a whisper-level ambient bridge between silent B-roll shots.',
    avoidRules: ['no obvious footsteps', 'no crowd bed', 'no fake room activity'],
    mustFollowRules: ['keep nearly felt rather than heard', 'smooth fade in and out'],
    status: 'qa_passed',
    recommendedProvider: 'mmaudio_v',
    providerRole: 'basic_pro_fallback',
    fallbackProvider: 'reeditpro_internal_library',
    routeReason: 'MMAudio can cheaply draft video-synced ambience for silent B-roll.',
    useInternalLibraryFirst: true,
    useMMAudioForDraft: true,
    useMireloForProduction: false,
    costSensitivity: 'lowest_cost',
    qualityTarget: 'preview',
    modelName: MMAUDIO_FUTURE_MODEL_NAME,
    promptStyle: 'video_conditioned_short_prompt',
    prompt: 'soft ambient bridge',
    negativePrompt: 'footsteps, doors, crowd noise, loud wind',
    tags: ['ambient_bridge', 'travel', 'whisper', 'silent_broll'],
    durationNeededSeconds: 4,
    durationToGenerateSeconds: 7,
    generatedDurationPolicy: 'generate_6_to_8_seconds',
    textureWords: ['airy', 'smooth'],
    energyWords: ['very low'],
    styleWords: ['travel', 'calm'],
    avoidWords: ['footsteps', 'doors', 'crowd'],
    timingInstructions: ['start before the cut', 'continue under the next shot'],
    mixInstructions: ['whisper profile', 'fade in and out slowly'],
    promptWarnings: ['This is an ambient bridge, not automatic source-action Foley.'],
    generated: true,
    origin: 'mock_generated',
    reuseStatus: 'approved_for_project',
    qaStatus: 'passed',
    licenseScope: 'project_only',
    trimStartSeconds: 1,
    trimEndSeconds: 5.2,
    detectedHitTimeSeconds: 1.8,
    qaRecommendedAction: 'use_with_mix_adjustment',
    qaOverallScore: 90,
    qaIssues: [],
    libraryCandidate: false,
  },
  {
    slug: 'faith_teaching_avoid_sfx',
    eventLabel: 'Avoid SFX for serious faith teaching pause',
    targetLayer: 'none',
    useCase: 'none',
    decisionState: 'avoid',
    sourceFootagePolicy: 'avoid_source_action_sfx',
    reason: 'The emotional pause and serious teaching tone would feel cheapened by decorative SFX.',
    sceneContext: 'Speaker pauses after a sensitive faith teaching point.',
    videoTone: 'serious, reflective, respectful',
    editLevel: 'basic',
    signatureSystem: 'none',
    anchorType: 'manual',
    anchorTimeSeconds: 22.4,
    timingPriority: 'speech_safe',
    volumeProfile: 'none',
    mixPriority: 'voice_first',
    creditImpact: 'none',
    requiresApproval: false,
    userVisibleSummary: 'No SFX recommended for this serious teaching pause.',
    avoidRules: ['no chime', 'no whoosh', 'no emotional manipulation'],
    mustFollowRules: ['preserve pause', 'protect spoken meaning'],
    status: 'planned',
    recommendedProvider: 'no_sfx',
    providerRole: 'none',
    routeReason: 'No SFX is the professional choice for this tone.',
    useInternalLibraryFirst: false,
    useMMAudioForDraft: false,
    useMireloForProduction: false,
    costSensitivity: 'lowest_cost',
    qualityTarget: 'draft',
    modelName: 'no-sfx',
    promptStyle: 'simple_keyword',
    prompt: 'no sfx',
    negativePrompt: '',
    tags: ['avoid_sfx', 'faith_teaching', 'voice_first'],
    durationNeededSeconds: 0,
    durationToGenerateSeconds: 0,
    generatedDurationPolicy: 'custom',
    textureWords: [],
    energyWords: [],
    styleWords: ['respectful', 'serious'],
    avoidWords: ['chime', 'whoosh', 'decorative'],
    timingInstructions: ['preserve silence and room tone'],
    mixInstructions: ['voice only'],
    promptWarnings: ['No provider prompt should be sent.'],
    generated: false,
    origin: 'unknown',
    reuseStatus: 'blocked_from_reuse',
    qaStatus: 'waived',
    licenseScope: 'unknown',
    qaRecommendedAction: 'remove_sfx',
    qaOverallScore: 100,
    qaIssues: [
      {
        id: 'sfx_issue_faith_teaching_not_needed',
        issueType: 'not_needed',
        severity: 'blocking',
        description: 'Decorative SFX would distract from the serious spoken meaning.',
        recommendedFix: 'Do not add SFX; preserve natural room tone.',
        blocksUse: true,
      },
    ],
    libraryCandidate: false,
  },
  {
    slug: 'talking_head_cut_not_needed',
    eventLabel: 'Not-needed SFX for simple talking-head cut',
    targetLayer: 'none',
    useCase: 'none',
    decisionState: 'not_needed',
    sourceFootagePolicy: 'edit_layer_only_default',
    reason: 'The clean talking-head cut already works with voice continuity and does not need an accent.',
    sceneContext: 'Simple jump cut removes a small stumble in a talking-head clip.',
    videoTone: 'plain, clean, direct',
    editLevel: 'basic',
    signatureSystem: 'none',
    anchorType: 'cut',
    anchorTimeSeconds: 9.8,
    timingPriority: 'speech_safe',
    volumeProfile: 'none',
    mixPriority: 'voice_first',
    creditImpact: 'none',
    requiresApproval: false,
    userVisibleSummary: 'No SFX needed for this clean talking-head cut.',
    avoidRules: ['do not add random cut whoosh', 'do not distract from speech'],
    mustFollowRules: ['protect voice continuity'],
    status: 'planned',
    recommendedProvider: 'no_sfx',
    providerRole: 'none',
    routeReason: 'No SFX avoids unnecessary decoration and preserves clean speech editing.',
    useInternalLibraryFirst: false,
    useMMAudioForDraft: false,
    useMireloForProduction: false,
    costSensitivity: 'lowest_cost',
    qualityTarget: 'draft',
    modelName: 'no-sfx',
    promptStyle: 'simple_keyword',
    prompt: 'no sfx',
    negativePrompt: '',
    tags: ['not_needed', 'talking_head', 'voice_first'],
    durationNeededSeconds: 0,
    durationToGenerateSeconds: 0,
    generatedDurationPolicy: 'custom',
    textureWords: [],
    energyWords: [],
    styleWords: ['clean', 'direct'],
    avoidWords: ['whoosh', 'pop', 'hit'],
    timingInstructions: ['no placement needed'],
    mixInstructions: ['voice continuity only'],
    promptWarnings: ['No provider prompt should be sent.'],
    generated: false,
    origin: 'unknown',
    reuseStatus: 'blocked_from_reuse',
    qaStatus: 'waived',
    licenseScope: 'unknown',
    qaRecommendedAction: 'remove_sfx',
    qaOverallScore: 100,
    qaIssues: [],
    libraryCandidate: false,
  },
]

const baseRecord = (id: ID) => ({
  id,
  createdAt: mockSFXDirectorTimestamp,
  updatedAt: mockSFXDirectorTimestamp,
})

const eventId = (seed: SFXDirectorScenarioSeed) => `sfx_event_${seed.slug}`
const providerRouteId = (seed: SFXDirectorScenarioSeed) => `sfx_route_${seed.slug}`
const promptPlanId = (seed: SFXDirectorScenarioSeed) => `sfx_prompt_${seed.slug}`
const generatedAssetId = (seed: SFXDirectorScenarioSeed) => `sfx_asset_${seed.slug}`
const trimPlanId = (seed: SFXDirectorScenarioSeed) => `sfx_trim_${seed.slug}`
const timingAlignmentId = (seed: SFXDirectorScenarioSeed) => `sfx_timing_${seed.slug}`
const mixPlanId = (seed: SFXDirectorScenarioSeed) => `sfx_mix_${seed.slug}`
const qaReportId = (seed: SFXDirectorScenarioSeed) => `sfx_qa_${seed.slug}`

const getGeneratedSeeds = () => scenarioSeeds.filter((seed) => seed.generated)

export const mockSFXEventPlans: SFXEventPlanRecord[] = scenarioSeeds.map((seed) => ({
  ...baseRecord(eventId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  editPlanSegmentId: `edit_segment_${seed.slug}`,
  targetLayer: seed.targetLayer,
  useCase: seed.useCase,
  legacySoundEffectType: seed.legacySoundEffectType,
  decisionState: seed.decisionState,
  sourceFootagePolicy: seed.sourceFootagePolicy,
  reason: seed.reason,
  sceneContext: seed.sceneContext,
  videoTone: seed.videoTone,
  editLevel: seed.editLevel,
  signatureSystem: seed.signatureSystem,
  anchorType: seed.anchorType,
  anchorTimeSeconds: seed.anchorTimeSeconds,
  startTimeSeconds: seed.startTimeSeconds,
  hitTimeSeconds: seed.hitTimeSeconds,
  endTimeSeconds: seed.endTimeSeconds,
  timingPriority: seed.timingPriority,
  volumeProfile: seed.volumeProfile,
  mixPriority: seed.mixPriority,
  creditImpact: seed.creditImpact,
  requiresApproval: seed.requiresApproval,
  userVisibleSummary: seed.userVisibleSummary,
  avoidRules: seed.avoidRules,
  mustFollowRules: seed.mustFollowRules,
  status: seed.status,
  notes: [seed.eventLabel],
}))

export const mockSFXProviderRoutes: SFXProviderRouteRecord[] = scenarioSeeds.map((seed) => ({
  ...baseRecord(providerRouteId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  recommendedProvider: seed.recommendedProvider,
  providerRole: seed.providerRole,
  fallbackProvider: seed.fallbackProvider,
  reason: seed.routeReason,
  useInternalLibraryFirst: seed.useInternalLibraryFirst,
  useMMAudioForDraft: seed.useMMAudioForDraft,
  useMireloForProduction: seed.useMireloForProduction,
  noSfxAllowed: true,
  costSensitivity: seed.costSensitivity,
  qualityTarget: seed.qualityTarget,
  approvalRequired: seed.requiresApproval,
  notes: ['Mock route only; no provider request is executed.'],
}))

export const mockSFXLibrarySearchPlans: SFXLibrarySearchPlanRecord[] = scenarioSeeds.map((seed) => ({
  ...baseRecord(`sfx_library_search_${seed.slug}`),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  targetLayer: seed.targetLayer,
  useCase: seed.useCase,
  searchTags: seed.tags,
  avoidTags: seed.avoidWords,
  requiredLicenseScope: seed.licenseScope,
  minimumQualityScore: seed.qualityTarget === 'premium' ? 92 : 85,
  workspaceOnlyAllowed: true,
  fallbackProvider: seed.fallbackProvider ?? seed.recommendedProvider,
  resultAssetIds: seed.recommendedProvider === 'reeditpro_internal_library' ? [`library_sfx_${seed.slug}`] : [],
  noMatchReason: seed.recommendedProvider === 'reeditpro_internal_library' ? undefined : 'No approved internal library sound is assumed for this mock route.',
  status: seed.status,
  notes: ['Library search is planned metadata only.'],
}))

export const mockSFXPromptPlans: SFXPromptPlanRecord[] = scenarioSeeds.map((seed) => ({
  ...baseRecord(promptPlanId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  providerRouteId: providerRouteId(seed),
  provider: seed.recommendedProvider,
  modelName: seed.modelName,
  promptStyle: seed.promptStyle,
  prompt: seed.prompt,
  negativePrompt: seed.negativePrompt,
  librarySearchTags: seed.tags,
  durationNeededSeconds: seed.durationNeededSeconds,
  durationToGenerateSeconds: seed.durationToGenerateSeconds,
  generatedDurationPolicy: seed.generatedDurationPolicy,
  textureWords: seed.textureWords,
  energyWords: seed.energyWords,
  styleWords: seed.styleWords,
  avoidWords: seed.avoidWords,
  timingInstructions: seed.timingInstructions,
  mixInstructions: seed.mixInstructions,
  promptWarnings: seed.promptWarnings,
  status: seed.status,
  notes: ['Prompt plan only; no API call is implied.'],
}))

export const mockSFXGeneratedAssets: SFXGeneratedAssetRecord[] = getGeneratedSeeds().map((seed) => ({
  ...baseRecord(generatedAssetId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  sfxPromptPlanId: promptPlanId(seed),
  generationRequestId: `generation_request_${seed.slug}`,
  generatedAssetId: `generated_asset_${seed.slug}`,
  provider: seed.recommendedProvider,
  modelName: seed.modelName,
  origin: seed.origin,
  storagePath: `mock://reeditpro/sfx/${seed.slug}/full-generated.wav`,
  fullGeneratedDurationSeconds: seed.durationToGenerateSeconds,
  recommendedTrimStartSeconds: seed.trimStartSeconds,
  recommendedTrimEndSeconds: seed.trimEndSeconds,
  detectedHitTimeSeconds: seed.detectedHitTimeSeconds,
  reuseStatus: seed.reuseStatus,
  qaStatus: seed.qaStatus,
  licenseProvenanceId: `license_provenance_${seed.slug}`,
  licenseScope: seed.licenseScope,
  status: seed.status,
  notes: ['Mock generated asset metadata only; no audio file exists.'],
}))

export const mockSFXTrimPlans: SFXTrimPlanRecord[] = getGeneratedSeeds().map((seed) => ({
  ...baseRecord(trimPlanId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  sfxGeneratedAssetId: generatedAssetId(seed),
  generatedDurationSeconds: seed.durationToGenerateSeconds,
  neededDurationSeconds: seed.durationNeededSeconds,
  trimStartSeconds: seed.trimStartSeconds ?? 0,
  trimEndSeconds: seed.trimEndSeconds ?? seed.durationNeededSeconds,
  hitOffsetInsideTrimMs: Math.round(((seed.detectedHitTimeSeconds ?? 0) - (seed.trimStartSeconds ?? 0)) * 1000),
  fadeInMs: seed.targetLayer === 'ambient_bridge' ? 500 : 24,
  fadeOutMs: seed.targetLayer === 'ambient_bridge' ? 700 : 120,
  tailMs: Math.round(((seed.endTimeSeconds ?? seed.anchorTimeSeconds) - seed.anchorTimeSeconds) * 1000),
  reason: 'Trim selects the cleanest usable region and aligns the detected hit to the approved timing anchor.',
  requiresManualReview: false,
  status: 'trimmed',
  notes: ['Mock trim plan only; no waveform analysis was executed.'],
}))

export const mockSFXTimingAlignments: SFXTimingAlignmentRecord[] = getGeneratedSeeds().map((seed) => ({
  ...baseRecord(timingAlignmentId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  sfxTrimPlanId: trimPlanId(seed),
  anchorType: seed.anchorType,
  anchorTimeSeconds: seed.anchorTimeSeconds,
  startTimeSeconds: seed.startTimeSeconds ?? seed.anchorTimeSeconds,
  hitTimeSeconds: seed.hitTimeSeconds ?? seed.anchorTimeSeconds,
  endTimeSeconds: seed.endTimeSeconds ?? seed.anchorTimeSeconds + seed.durationNeededSeconds,
  preRollMs: Math.round((seed.anchorTimeSeconds - (seed.startTimeSeconds ?? seed.anchorTimeSeconds)) * 1000),
  tailMs: Math.round(((seed.endTimeSeconds ?? seed.anchorTimeSeconds + seed.durationNeededSeconds) - seed.anchorTimeSeconds) * 1000),
  durationNeededMs: Math.round(seed.durationNeededSeconds * 1000),
  durationGeneratedMs: Math.round(seed.durationToGenerateSeconds * 1000),
  hitOffsetInsideTrimMs: Math.round(((seed.detectedHitTimeSeconds ?? 0) - (seed.trimStartSeconds ?? 0)) * 1000),
  timingPriority: seed.timingPriority,
  frameAccurateRequired: seed.timingPriority === 'frame_accurate' || seed.timingPriority === 'beat_aligned',
  musicBeatAligned: seed.anchorType === 'music_beat' || seed.anchorType === 'music_downbeat',
  speechSafePlacement: seed.mixPriority === 'voice_first' || seed.volumeProfile === 'whisper',
  notes: ['Frame-accurate placement plan only; no render timeline was modified.'],
}))

export const mockSFXMixPlans: SFXMixPlanRecord[] = getGeneratedSeeds().map((seed) => ({
  ...baseRecord(mixPlanId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  sfxGeneratedAssetId: generatedAssetId(seed),
  volumeProfile: seed.volumeProfile,
  targetGainDb: seed.volumeProfile === 'premium_soft' ? -18 : seed.volumeProfile === 'whisper' ? -28 : -22,
  duckUnderVoice: true,
  duckUnderMusic: seed.mixPriority !== 'ambience_first',
  duckingStrategy: 'voice_first',
  sidechainToVoice: true,
  sidechainToMusic: seed.mixPriority === 'music_support',
  fadeInMs: seed.targetLayer === 'ambient_bridge' ? 500 : 24,
  fadeOutMs: seed.targetLayer === 'ambient_bridge' ? 700 : 120,
  eqNotes: ['reduce low-end buildup', 'avoid harsh high-frequency transient under speech'],
  stereoWidth: seed.targetLayer === 'ambient_bridge' ? 70 : 45,
  reverbMatch: seed.targetLayer === 'real_motion' ? 'match source room' : 'short clean tail',
  roomMatch: seed.targetLayer === 'real_motion' ? 'room-matched to object scene' : 'neutral',
  mixPriority: seed.mixPriority,
  voicePresent: true,
  musicPresent: true,
  ambienceImportant: seed.targetLayer === 'ambient_bridge' || seed.targetLayer === 'real_motion',
  notes: ['Voice-first mock mix plan; no audio processing was executed.'],
  status: 'mixed',
}))

export const mockSFXQAReports: SFXQAReportRecord[] = scenarioSeeds.map((seed) => ({
  ...baseRecord(qaReportId(seed)),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  sfxEventPlanId: eventId(seed),
  sfxGeneratedAssetId: seed.generated ? generatedAssetId(seed) : undefined,
  sfxTrimPlanId: seed.generated ? trimPlanId(seed) : undefined,
  sfxTimingAlignmentId: seed.generated ? timingAlignmentId(seed) : undefined,
  sfxMixPlanId: seed.generated ? mixPlanId(seed) : undefined,
  status: seed.qaStatus,
  overallScore: seed.qaOverallScore,
  timingScore: seed.generated ? 94 : 100,
  volumeScore: seed.volumeProfile === 'none' ? 100 : 91,
  styleFitScore: seed.decisionState === 'avoid' ? 100 : 92,
  voiceSafetyScore: 98,
  musicFitScore: seed.volumeProfile === 'none' ? 100 : 90,
  artifactScore: seed.generated ? 93 : 100,
  issues: seed.qaIssues,
  recommendedAction: seed.qaRecommendedAction,
  approvedForProject: seed.qaStatus === 'passed' || seed.qaStatus === 'waived',
  approvedForLibraryCandidate: seed.libraryCandidate,
  requiresRegeneration: false,
  requiresTrimAdjustment: false,
  requiresMixAdjustment: seed.qaRecommendedAction === 'use_with_mix_adjustment',
  notes: ['Mock QA only; no audio analyzer or render QA worker was run.'],
}))

export const mockSFXLibraryCandidates: SFXLibraryCandidateRecord[] = scenarioSeeds
  .filter((seed) => seed.libraryCandidate)
  .map((seed) => ({
    ...baseRecord(`sfx_library_candidate_${seed.slug}`),
    projectId: PROJECT_ID,
    workspaceId: WORKSPACE_ID,
    sfxGeneratedAssetId: generatedAssetId(seed),
    sfxEventPlanId: eventId(seed),
    reuseStatus: 'candidate_for_library',
    candidateReason: seed.libraryCandidateReason ?? 'Reusable sound after QA and provenance review.',
    qualityScore: seed.qaOverallScore,
    targetLayer: seed.targetLayer,
    useCase: seed.useCase,
    provider: seed.recommendedProvider,
    modelName: seed.modelName,
    generalPurpose: true,
    containsPrivateContext: false,
    licenseReviewRequired: true,
    licenseScope: seed.licenseScope,
    tags: seed.tags,
    recommendedUseCases: [seed.useCase],
    avoidUseCases: ['none'],
    notes: ['Candidate only; not approved for cross-user reuse until terms review passes.'],
  }))

export const mockSFXUsageRecords: SFXUsageRecord[] = getGeneratedSeeds().map((seed) => ({
  ...baseRecord(`sfx_usage_${seed.slug}`),
  projectId: PROJECT_ID,
  editPlanId: EDIT_PLAN_ID,
  renderId: `render_preview_${seed.slug}`,
  sfxGeneratedAssetId: generatedAssetId(seed),
  generatedAssetId: `generated_asset_${seed.slug}`,
  sfxEventPlanId: eventId(seed),
  sfxTimingAlignmentId: timingAlignmentId(seed),
  sfxMixPlanId: mixPlanId(seed),
  usageType: 'preview',
  usedStartTimeSeconds: seed.startTimeSeconds ?? seed.anchorTimeSeconds,
  usedEndTimeSeconds: seed.endTimeSeconds ?? seed.anchorTimeSeconds + seed.durationNeededSeconds,
  hitTimeSeconds: seed.hitTimeSeconds ?? seed.anchorTimeSeconds,
  volumeProfile: seed.volumeProfile,
  userKept: true,
  userRemoved: false,
  qaPassed: seed.qaStatus === 'passed',
  notes: ['Mock preview usage only; no preview render was created.'],
}))

export const mockSFXPromptAdapterTests: SFXPromptAdapterTestRecord[] = [
  {
    ...baseRecord('sfx_prompt_test_mirelo_simple_keyword'),
    provider: 'mirelo_sfx_v1_5',
    modelName: MIRELO_SFX_FUTURE_MODEL_NAME,
    promptStyle: 'simple_keyword',
    testPrompt: 'premium transition whoosh',
    expectedUseCase: 'transition_soft_whoosh',
    notes: ['Future Mirelo prompt test only.'],
    status: 'planned',
  },
  {
    ...baseRecord('sfx_prompt_test_mirelo_structured_sentence'),
    provider: 'mirelo_sfx_v1_5',
    modelName: MIRELO_SFX_FUTURE_MODEL_NAME,
    promptStyle: 'structured_sentence',
    testPrompt: 'Soft premium transition whoosh, clean airy movement, subtle luxury tone, short smooth tail, no harsh riser.',
    expectedUseCase: 'transition_soft_whoosh',
    notes: ['Future Mirelo prompt test only.'],
    status: 'planned',
  },
  {
    ...baseRecord('sfx_prompt_test_mmaudio_short'),
    provider: 'mmaudio_v',
    modelName: MMAUDIO_FUTURE_MODEL_NAME,
    promptStyle: 'video_conditioned_short_prompt',
    testPrompt: 'quiet object movement',
    expectedUseCase: 'real_motion_object_settle',
    notes: ['Future MMAudio prompt-length test only.'],
    status: 'planned',
  },
  {
    ...baseRecord('sfx_prompt_test_library_tags'),
    provider: 'reeditpro_internal_library',
    modelName: 'reeditpro-internal-library',
    promptStyle: 'library_search_tags',
    testPrompt: 'chapter_card, soft_hit, educational, whisper',
    expectedUseCase: 'transition_subtle_cut_accent',
    notes: ['Future internal library search test only.'],
    status: 'planned',
  },
]

export const mockSFXRegenerationDecisions: SFXRegenerationDecisionRecord[] = [
  {
    ...baseRecord('sfx_regen_decision_luxury_transition_whoosh'),
    projectId: PROJECT_ID,
    editPlanId: EDIT_PLAN_ID,
    sfxEventPlanId: eventId(scenarioSeeds[0]),
    sfxGeneratedAssetId: generatedAssetId(scenarioSeeds[0]),
    sfxQAReportId: qaReportId(scenarioSeeds[0]),
    shouldRegenerate: false,
    recommendedAction: 'use',
    issueTypes: [],
    providerRouteId: providerRouteId(scenarioSeeds[0]),
    preferredProvider: 'mirelo_sfx_v1_5',
    promptAdjustment: 'No adjustment needed.',
    requiresNewApproval: false,
    userVisibleSummary: 'The premium transition whoosh passed QA and can be used as planned.',
    notes: ['Mock regeneration decision only.'],
  },
  {
    ...baseRecord('sfx_regen_decision_faith_teaching_avoid_sfx'),
    projectId: PROJECT_ID,
    editPlanId: EDIT_PLAN_ID,
    sfxEventPlanId: eventId(scenarioSeeds[8]),
    sfxQAReportId: qaReportId(scenarioSeeds[8]),
    shouldRegenerate: false,
    recommendedAction: 'remove_sfx',
    issueTypes: ['not_needed'],
    providerRouteId: providerRouteId(scenarioSeeds[8]),
    preferredProvider: 'no_sfx',
    promptAdjustment: 'No prompt should be generated.',
    requiresNewApproval: false,
    userVisibleSummary: 'No SFX is the approved professional choice for this serious teaching pause.',
    notes: ['Mock no-SFX decision only.'],
  },
]

export interface MockSFXDirectorScenario {
  eventPlan: SFXEventPlanRecord
  providerRoute: SFXProviderRouteRecord
  librarySearchPlan: SFXLibrarySearchPlanRecord
  promptPlan: SFXPromptPlanRecord
  generatedAsset?: SFXGeneratedAssetRecord
  trimPlan?: SFXTrimPlanRecord
  timingAlignment?: SFXTimingAlignmentRecord
  mixPlan?: SFXMixPlanRecord
  qaReport: SFXQAReportRecord
  libraryCandidate?: SFXLibraryCandidateRecord
}

export const mockSFXDirectorScenarios: MockSFXDirectorScenario[] = scenarioSeeds.map((seed) => ({
  eventPlan: mockSFXEventPlans.find((record) => record.id === eventId(seed)) as SFXEventPlanRecord,
  providerRoute: mockSFXProviderRoutes.find((record) => record.id === providerRouteId(seed)) as SFXProviderRouteRecord,
  librarySearchPlan: mockSFXLibrarySearchPlans.find((record) => record.sfxEventPlanId === eventId(seed)) as SFXLibrarySearchPlanRecord,
  promptPlan: mockSFXPromptPlans.find((record) => record.id === promptPlanId(seed)) as SFXPromptPlanRecord,
  generatedAsset: mockSFXGeneratedAssets.find((record) => record.id === generatedAssetId(seed)),
  trimPlan: mockSFXTrimPlans.find((record) => record.id === trimPlanId(seed)),
  timingAlignment: mockSFXTimingAlignments.find((record) => record.id === timingAlignmentId(seed)),
  mixPlan: mockSFXMixPlans.find((record) => record.id === mixPlanId(seed)),
  qaReport: mockSFXQAReports.find((record) => record.id === qaReportId(seed)) as SFXQAReportRecord,
  libraryCandidate: mockSFXLibraryCandidates.find((record) => record.sfxEventPlanId === eventId(seed)),
}))
