import type {
  AmbientSoundPlanRecord,
  ChatMessageRecord,
  ChatSessionRecord,
  CreditEstimateRecord,
  CreditReservationRecord,
  EditQualityProfileRecord,
  GenerationRequestRecord,
  InlineChatCardRecord,
  IntentAnalysisRecord,
  JobDependencyRecord,
  JobRecord,
  MediaAssetRecord,
  MusicPlanRecord,
  ProjectRecord,
  QAReportItem,
  QAReportRecord,
  RenderJobRecord,
  RenderRecord,
  RevisionRequestRecord,
  SourceClipSequenceItem,
  SourceClipSequenceRecord,
  StrokeMotionBeatRecord,
  StrokeMotionCharacterRecord,
  StrokeMotionGenerationSpecRecord,
  StrokeMotionPlanRecord,
  StrokeMotionSymbolRecord,
  StrokeMotionTimingAnchorRecord,
  StrokeMotionTransitionRecord,
  TransitionPlanRecord,
} from '../types'

export const mockRecordTimestamp = '2026-05-13T12:00:00.000Z'

export const mockChatNativeProject: ProjectRecord = {
  id: 'project_reeditpro_estate_short',
  userId: 'user_creator_001',
  workspaceId: 'workspace_personal_001',
  title: 'Premium real estate short',
  description: 'Chat-native AI edit demo with plan and credit approval before generation.',
  status: 'awaiting_approval',
  currentChatSessionId: 'chat_session_estate_001',
  currentEditPlanId: 'edit_plan_estate_001',
  currentCreditEstimateId: 'credit_estimate_estate_001',
  targetPlatform: 'tiktok_reels_shorts',
  aspectRatio: '9:16',
  createdFromChat: true,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockSourceMediaAssets: MediaAssetRecord[] = [
  {
    id: 'media_clip_001',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    uploadedByUserId: 'user_creator_001',
    assetType: 'source_video',
    storageProvider: 'local_mock',
    fileName: '01-entry-living-room.mp4',
    mimeType: 'video/mp4',
    durationSeconds: 8,
    width: 1080,
    height: 1920,
    status: 'completed',
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'media_clip_002',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    uploadedByUserId: 'user_creator_001',
    assetType: 'source_video',
    storageProvider: 'local_mock',
    fileName: '02-kitchen-details.mp4',
    mimeType: 'video/mp4',
    durationSeconds: 7,
    width: 1080,
    height: 1920,
    status: 'completed',
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'media_clip_003',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    uploadedByUserId: 'user_creator_001',
    assetType: 'source_video',
    storageProvider: 'local_mock',
    fileName: '03-agent-investment-line.mp4',
    mimeType: 'video/mp4',
    durationSeconds: 10,
    width: 1080,
    height: 1920,
    status: 'completed',
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'media_clip_004',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    uploadedByUserId: 'user_creator_001',
    assetType: 'source_video',
    storageProvider: 'local_mock',
    fileName: '04-backyard-exterior.mp4',
    mimeType: 'video/mp4',
    durationSeconds: 9,
    width: 1080,
    height: 1920,
    status: 'completed',
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
]

export const mockSourceClipSequence: SourceClipSequenceRecord = {
  id: 'source_sequence_estate_001',
  projectId: mockChatNativeProject.id,
  chatSessionId: 'chat_session_estate_001',
  createdFromChatMessageId: 'chat_message_user_instruction_001',
  sequenceName: 'Uploaded source order',
  explanation:
    'Clips are kept in the order the user sent them. ReeditPro treats this as the source sequence, not automatically the final edit order.',
  lockedByUser: false,
  status: 'completed',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockSourceClipSequenceItems: SourceClipSequenceItem[] = [
  {
    id: 'source_sequence_item_001',
    sourceClipSequenceId: mockSourceClipSequence.id,
    mediaAssetId: 'media_clip_001',
    uploadedOrder: 1,
    userNotes: 'Open with natural walkthrough if no stronger hook is needed.',
    isImportant: true,
    isOptional: false,
    detectedRole: 'entry and living room walkthrough',
    possibleUses: ['opening context', 'walkthrough base layer'],
    transcriptStatus: 'completed',
    analysisStatus: 'completed',
  },
  {
    id: 'source_sequence_item_002',
    sourceClipSequenceId: mockSourceClipSequence.id,
    mediaAssetId: 'media_clip_002',
    uploadedOrder: 2,
    userNotes: 'Kitchen detail shots.',
    isImportant: true,
    isOptional: false,
    detectedRole: 'feature details',
    possibleUses: ['property highlights', 'VisualExplain detail overlay'],
    transcriptStatus: 'completed',
    analysisStatus: 'completed',
  },
  {
    id: 'source_sequence_item_003',
    sourceClipSequenceId: mockSourceClipSequence.id,
    mediaAssetId: 'media_clip_003',
    uploadedOrder: 3,
    userNotes: 'Speaker says this is a major investment.',
    isImportant: true,
    isOptional: false,
    detectedRole: 'speaker value statement',
    possibleUses: ['soft hook', 'Real Motion opportunity'],
    transcriptStatus: 'completed',
    analysisStatus: 'completed',
  },
  {
    id: 'source_sequence_item_004',
    sourceClipSequenceId: mockSourceClipSequence.id,
    mediaAssetId: 'media_clip_004',
    uploadedOrder: 4,
    userNotes: 'Exterior/backyard closing shot.',
    isImportant: false,
    isOptional: false,
    detectedRole: 'closing proof',
    possibleUses: ['result beat', 'CTA background'],
    transcriptStatus: 'completed',
    analysisStatus: 'completed',
  },
]

export const mockChatSession: ChatSessionRecord = {
  id: 'chat_session_estate_001',
  projectId: mockChatNativeProject.id,
  workspaceId: 'workspace_personal_001',
  userId: 'user_creator_001',
  status: 'waiting_approval',
  title: 'Edit this into a premium real estate short',
  startedAt: mockRecordTimestamp,
  currentInlineCardId: 'inline_card_credit_estimate_001',
  lastMessageAt: mockRecordTimestamp,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockUserInstructionMessage: ChatMessageRecord = {
  id: 'chat_message_user_instruction_001',
  chatSessionId: mockChatSession.id,
  projectId: mockChatNativeProject.id,
  role: 'user',
  actorId: 'user_creator_001',
  content: "I want to edit these clips into a premium real estate short. Keep it natural and don't make it too viral.",
  inlineCardIds: [],
  attachmentIds: mockSourceMediaAssets.map((asset) => asset.id),
  visibleToUser: true,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockAssistantPlanMessage: ChatMessageRecord = {
  id: 'chat_message_assistant_plan_001',
  chatSessionId: mockChatSession.id,
  projectId: mockChatNativeProject.id,
  role: 'assistant',
  content: 'Here is the edit plan before spending credits.',
  inlineCardIds: ['inline_card_source_sequence_001', 'inline_card_edit_plan_001', 'inline_card_credit_estimate_001'],
  attachmentIds: [],
  processingStatus: 'waiting_user_approval',
  visibleToUser: true,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockSourceSequenceCard: InlineChatCardRecord = {
  id: 'inline_card_source_sequence_001',
  chatSessionId: mockChatSession.id,
  chatMessageId: mockAssistantPlanMessage.id,
  projectId: mockChatNativeProject.id,
  cardType: 'source_sequence',
  title: 'Source sequence',
  summary: 'Four clips were sent in source order. Final edit order still requires plan approval.',
  payload: {
    source_clip_sequence_id: mockSourceClipSequence.id,
    uploaded_order_rule: 'source_sequence_not_final_edit_order',
    clips: mockSourceClipSequenceItems.map((item) => ({
      media_asset_id: item.mediaAssetId,
      uploaded_order: item.uploadedOrder,
      detected_role: item.detectedRole ?? '',
      important: item.isImportant,
      optional: item.isOptional,
    })),
  },
  status: 'completed',
  actionIds: [],
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockIntentAnalysis: IntentAnalysisRecord = {
  id: 'intent_analysis_estate_001',
  projectId: mockChatNativeProject.id,
  chatSessionId: mockChatSession.id,
  sourceChatMessageIds: [mockUserInstructionMessage.id],
  userGoalSummary: 'Create a premium real estate social short that preserves the natural walkthrough feel.',
  explicitInstructions: ['keep it natural', "don't make it too viral"],
  inferredIntent: 'Premium/luxury social performance without aggressive viral editing.',
  missingInformationQuestions: [],
  selectedWorkflowContext: 'real_estate_property_tour',
  workflowContextOnly: true,
  targetPlatform: 'tiktok_reels_shorts',
  requestedEditComplexity: 'signature_edit',
  confidence: 'high',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockBasicEditQualityProfile: EditQualityProfileRecord = {
  id: 'edit_quality_profile_basic_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  editComplexity: 'basic_edit',
  qualityLevel: 'basic',
  professionalStandard: 'clean_professional',
  professionalStandardRequired: true,
  pacingStrategy: 'Clean pauses and mistakes while preserving the walkthrough rhythm.',
  transitionPolicy: 'clean_cuts',
  captionStrategy: 'Readable captions with minimal animation.',
  audioStrategy: 'Level voice and preserve natural room tone.',
  signatureUsageBoundary: 'Avoid heavy signature generation unless the user explicitly approves extra credits.',
  notes: ['Basic is professional clean editing, not low-quality editing.'],
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockSignatureEditQualityProfile: EditQualityProfileRecord = {
  id: 'edit_quality_profile_signature_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  editComplexity: 'signature_edit',
  qualityLevel: 'signature',
  professionalStandard: 'premium_brand',
  professionalStandardRequired: true,
  pacingStrategy: 'Use a soft hook, premium pacing, and segment-level signature routing only where helpful.',
  transitionPolicy: 'premium_subtle',
  captionStrategy: 'Premium captions with safe placement and restrained emphasis.',
  audioStrategy: 'Subtle SoundSync bed, light transition polish, and voice-first ducking.',
  signatureUsageBoundary: 'Stroke Motion, VisualExplain, and Real Motion require segment-level reasons and credit approval.',
  notes: ['Real Motion remains overlay-first, face-safe, and credit-heavy.'],
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockStrokeMotionPlan: StrokeMotionPlanRecord = {
  id: 'stroke_motion_plan_joseph_mary_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  understandingMode: 'source_reading_mode',
  sourceTextType: 'scripture',
  sourceReference: 'Matthew 1:18-25',
  sourceExcerpt: 'Joseph considers Mary, receives the angel message, and accepts the call.',
  storySummary: 'A story of misunderstanding, mercy, divine reassurance, obedience, and restored commitment.',
  meaningExpansionSummary:
    'Mary and Joseph were engaged; Mary was pregnant by the Holy Spirit; Joseph did not fully understand; Joseph wanted to separate quietly; an angel appeared in a dream; the angel explained the child was from God; Joseph obeyed and accepted Mary.',
  animationGoal: 'Turn the source reading into connected visual story beats timed to the speaker words.',
  styleLevel: 'balanced',
  transitionStrategy:
    'relationship line -> holy glow -> tension/crack -> separation path -> divine message line -> repaired connection -> protective circle -> fade/underline transition out',
  timingStrategy: 'Anchor motion to spoken phrases and preserve emotional pauses.',
  approvalStatus: 'pending',
  creditEstimateId: 'credit_estimate_estate_001',
  generationStatus: 'waiting_user_approval',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockStrokeMotionCharacters: StrokeMotionCharacterRecord[] = [
  {
    id: 'stroke_character_mary',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    name: 'Mary',
    role: 'engaged mother',
    visualDescription: 'Simple respectful stroke character with soft glow nearby, not literalized.',
    emotionalState: 'vulnerable and protected',
    continuityKey: 'mary_simple_line_character',
    mustFollowRules: ['Do not make Mary look guilty.'],
    avoidRules: ['Avoid exaggerated facial emotion or blame imagery.'],
  },
  {
    id: 'stroke_character_joseph',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    name: 'Joseph',
    role: 'engaged protector',
    visualDescription: 'Simple stroke character with a thoughtful pause and repaired connection line.',
    emotionalState: 'confused, merciful, then obedient',
    continuityKey: 'joseph_simple_line_character',
    mustFollowRules: ['Show Joseph’s misunderstanding respectfully.'],
    avoidRules: ['Avoid harsh rejection imagery.'],
  },
]

export const mockStrokeMotionSymbols: StrokeMotionSymbolRecord[] = [
  {
    id: 'stroke_symbol_relationship_line',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    label: 'Relationship line',
    meaning: 'Mary and Joseph are engaged.',
    visualDescription: 'A continuous line connects the two characters.',
    symbolType: 'line',
    creditImpact: 'low',
  },
  {
    id: 'stroke_symbol_holy_glow',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    label: 'Holy glow',
    meaning: 'Pregnancy by the Holy Spirit, kept symbolic.',
    visualDescription: 'A restrained glow appears near Mary without literal depiction.',
    symbolType: 'glow',
    creditImpact: 'low',
  },
  {
    id: 'stroke_symbol_repaired_connection',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    label: 'Repaired connection',
    meaning: 'Joseph obeys and accepts Mary.',
    visualDescription: 'The cracked line reconnects into a protective circle.',
    symbolType: 'circle',
    creditImpact: 'medium',
  },
]

export const mockStrokeMotionTimingAnchors: StrokeMotionTimingAnchorRecord[] = [
  {
    id: 'stroke_anchor_mary_joseph_engaged',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    anchorType: 'phrase',
    matchedText: 'Mary and Joseph were engaged',
    timeRange: { startSeconds: 0, endSeconds: 2.5, timecode: '00:00:00' },
    confidence: 0.93,
    notes: 'Begin connected relationship line.',
  },
  {
    id: 'stroke_anchor_angel_dream',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    anchorType: 'phrase',
    matchedText: 'an angel appeared in a dream',
    timeRange: { startSeconds: 6.8, endSeconds: 9.2, timecode: '00:00:06' },
    confidence: 0.9,
    notes: 'Transition from separation path into divine message line.',
  },
]

export const mockStrokeMotionBeats: StrokeMotionBeatRecord[] = [
  {
    id: 'stroke_beat_001',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    beatOrder: 1,
    storyBeatLabel: 'Engaged relationship',
    meaning: 'Mary and Joseph are connected before the misunderstanding.',
    visualAction: 'Draw one relationship line between the two stroke characters.',
    characterIds: ['stroke_character_mary', 'stroke_character_joseph'],
    symbolIds: ['stroke_symbol_relationship_line'],
    motionPath: 'left character -> connection line -> right character',
    transitionIn: 'line draw on spoken phrase',
    transitionOut: 'line holds as holy glow appears',
    startTimeSeconds: 0,
    endTimeSeconds: 2.5,
    matchedWords: ['Mary', 'Joseph', 'engaged'],
    timingAnchorId: 'stroke_anchor_mary_joseph_engaged',
    sfxHint: 'stroke_draw_sound',
    workerNotes: ['Use one continuous stroke line through relationship and tension.'],
    mustFollowRules: ['Keep divine presence symbolic, not literal.'],
    avoidRules: ['Do not make Mary look guilty.'],
    renderStatus: 'planned',
  },
  {
    id: 'stroke_beat_002',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    beatOrder: 2,
    storyBeatLabel: 'Dream reassurance',
    meaning: 'The angel message gives Joseph understanding.',
    visualAction: 'Separation path transforms into a divine message line, then reconnects.',
    characterIds: ['stroke_character_joseph'],
    symbolIds: ['stroke_symbol_holy_glow', 'stroke_symbol_repaired_connection'],
    motionPath: 'separation path -> message line -> repaired connection',
    transitionIn: 'soft glow enters from upper safe area',
    transitionOut: 'protective circle closes gently',
    startTimeSeconds: 6.8,
    endTimeSeconds: 11.4,
    matchedWords: ['angel', 'dream', 'from God', 'accepted'],
    timingAnchorId: 'stroke_anchor_angel_dream',
    sfxHint: 'soft_whoosh',
    workerNotes: ['Preserve emotional pause before the repaired connection.'],
    mustFollowRules: ['Show Joseph’s misunderstanding respectfully.'],
    avoidRules: ['Avoid loud SFX under speech.'],
    renderStatus: 'planned',
  },
]

export const mockStrokeMotionTransitions: StrokeMotionTransitionRecord[] = [
  {
    id: 'stroke_transition_chain_001',
    strokeMotionPlanId: mockStrokeMotionPlan.id,
    fromBeatId: 'stroke_beat_001',
    toBeatId: 'stroke_beat_002',
    chainOrder: 1,
    strategy: 'connected_story_line',
    fromVisualState: 'relationship line',
    toVisualState: 'protective circle',
    description: 'One connected visual path carries the story from relationship to tension to restoration.',
    timeRange: { startSeconds: 2.5, endSeconds: 11.4, timecode: '00:00:02' },
    connectedTransitionChain: [
      'relationship line',
      'holy glow',
      'tension/crack',
      'separation path',
      'divine message line',
      'repaired connection',
      'protective circle',
      'fade/underline transition out',
    ],
  },
]

export const mockStrokeMotionGenerationSpec: StrokeMotionGenerationSpecRecord = {
  id: 'stroke_generation_spec_001',
  strokeMotionPlanId: mockStrokeMotionPlan.id,
  rendererPreference: 'remotion',
  transparentBackgroundRequired: true,
  wordLevelTimingRequired: true,
  outputResolution: '1080x1920',
  fps: 30,
  stylePrompt: 'Fast transparent 2D stroke story layer, respectful, minimal, timed to spoken words.',
  negativePrompt: 'No literal angel body, no guilt imagery, no loud effects.',
  timingConstraints: ['match phrase anchors', 'preserve emotional pause', 'transparent overlay only'],
  workerNotes: ['Prefer deterministic SVG/Lottie/Remotion-style timing over full AI video generation.'],
  status: 'waiting_user_approval',
}

export const mockMusicPlan: MusicPlanRecord = {
  id: 'music_plan_estate_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  role: 'premium_polish',
  mood: 'luxury, calm, confident',
  energyCurve: 'soft intro, steady walkthrough bed, gentle lift near exterior result shot',
  duckingStrategy: 'duck under voice and keep property ambience believable',
  startTiming: 'begin under first walkthrough frame',
  beatChangeNotes: ['avoid aggressive viral beat drops', 'use subtle lift on key property detail'],
  status: 'waiting_user_approval',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockAmbientSoundPlan: AmbientSoundPlanRecord = {
  id: 'ambient_plan_estate_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  ambientSoundType: 'real_estate_walkthrough',
  preserveNaturalRoomTone: true,
  bridgeSceneChanges: true,
  reductionStrategy: 'Reduce harsh handling noise while preserving quiet walkthrough ambience.',
  notes: ['Do not make the property feel artificially silent.'],
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockTransitionPlan: TransitionPlanRecord = {
  id: 'transition_plan_estate_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  fromSegmentId: 'edit_segment_001',
  toSegmentId: 'edit_segment_002',
  transitionType: 'soft_cut',
  transitionPolicy: 'premium_subtle',
  reason: 'Premium real estate should feel smooth and natural, not effect-heavy.',
  musicBeatAligned: true,
  emotionalTone: 'luxury calm',
  durationSeconds: 0.35,
  sfxHint: 'soft_whoosh',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockCreditEstimate: CreditEstimateRecord = {
  id: 'credit_estimate_estate_001',
  workspaceId: 'workspace_personal_001',
  projectId: mockChatNativeProject.id,
  chatMessageId: mockAssistantPlanMessage.id,
  editPlanId: 'edit_plan_estate_001',
  status: 'ready_for_approval',
  currency: 'USD',
  totalCredits: 92,
  retailValueCents: 460,
  weeklyBonusCreditsApplied: 92,
  purchasedCreditsApplied: 0,
  promotionalCreditsApplied: 0,
  lineItems: [
    {
      label: 'Captions',
      credits: 10,
      sourceType: 'weekly_bonus',
      reason: 'Readable premium captions.',
      isOptional: false,
      isPremium: false,
      relatedSignatureSystem: 'none',
    },
    {
      label: 'Basic cleanup',
      credits: 18,
      sourceType: 'weekly_bonus',
      reason: 'Clean cuts, voice leveling, and room tone preservation.',
      isOptional: false,
      isPremium: false,
      relatedSignatureSystem: 'none',
    },
    {
      label: 'Stroke Motion',
      credits: 12,
      sourceType: 'weekly_bonus',
      reason: 'Light emphasis around one key phrase.',
      isOptional: true,
      isPremium: false,
      relatedSignatureSystem: 'stroke_motion',
    },
    {
      label: 'Graphic Design / VisualExplain',
      credits: 10,
      sourceType: 'weekly_bonus',
      reason: 'Clean overlay for property detail clarity.',
      isOptional: true,
      isPremium: false,
      relatedSignatureSystem: 'graphic_design',
    },
    {
      label: 'Real Motion',
      credits: 34,
      sourceType: 'weekly_bonus',
      reason: 'Optional premium lower-right miniature house overlay, face-safe.',
      isOptional: true,
      isPremium: true,
      relatedSignatureSystem: 'real_motion',
    },
    {
      label: 'SoundSync',
      credits: 8,
      sourceType: 'weekly_bonus',
      reason: 'Subtle music, ducking, and light transition polish.',
      isOptional: false,
      isPremium: false,
      relatedSignatureSystem: 'sound_sync',
    },
  ],
  approvalStatus: 'pending',
  expiresAt: '2026-05-20T12:00:00.000Z',
  approvalRequiredBeforeGeneration: true,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockCreditReservation: CreditReservationRecord = {
  id: 'credit_reservation_estate_001',
  walletId: 'credit_wallet_personal_001',
  workspaceId: 'workspace_personal_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  creditEstimateId: mockCreditEstimate.id,
  status: 'estimated',
  reservedCredits: 92,
  spentCredits: 0,
  refundedCredits: 0,
  expiresAt: '2026-05-20T12:00:00.000Z',
  idempotencyKey: 'reserve_estate_001_v1',
  failureRefundEligible: true,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockJobChain: JobRecord[] = [
  {
    id: 'job_transcription_001',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    editPlanId: 'edit_plan_estate_001',
    jobType: 'transcription',
    status: 'completed',
    priority: 'normal',
    inputPayload: { media_asset_ids: ['media_clip_001', 'media_clip_002', 'media_clip_003', 'media_clip_004'] },
    outputPayload: { transcript_record_id: 'transcript_estate_001' },
    attemptCount: 1,
    maxAttempts: 3,
    idempotencyKey: 'job_transcription_estate_v1',
    workerType: 'media_analysis_agent',
    queuedAt: mockRecordTimestamp,
    startedAt: mockRecordTimestamp,
    completedAt: mockRecordTimestamp,
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'job_intent_analysis_001',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    editPlanId: 'edit_plan_estate_001',
    jobType: 'intent_analysis',
    status: 'completed',
    priority: 'normal',
    inputPayload: { chat_message_id: mockUserInstructionMessage.id },
    outputPayload: { intent_analysis_id: mockIntentAnalysis.id },
    attemptCount: 1,
    maxAttempts: 3,
    idempotencyKey: 'job_intent_estate_v1',
    workerType: 'chat_intent_agent',
    queuedAt: mockRecordTimestamp,
    startedAt: mockRecordTimestamp,
    completedAt: mockRecordTimestamp,
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'job_credit_estimation_001',
    workspaceId: 'workspace_personal_001',
    projectId: mockChatNativeProject.id,
    editPlanId: 'edit_plan_estate_001',
    jobType: 'credit_estimation',
    status: 'waiting_user_approval',
    priority: 'normal',
    inputPayload: { edit_plan_id: 'edit_plan_estate_001' },
    outputPayload: { credit_estimate_id: mockCreditEstimate.id },
    attemptCount: 1,
    maxAttempts: 3,
    idempotencyKey: 'job_credit_estimate_estate_v1',
    workerType: 'credit_estimation_agent',
    queuedAt: mockRecordTimestamp,
    startedAt: mockRecordTimestamp,
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
]

export const mockJobDependencies: JobDependencyRecord[] = [
  {
    id: 'job_dependency_001',
    jobId: 'job_intent_analysis_001',
    dependsOnJobId: 'job_transcription_001',
    dependencyType: 'requires_success',
    requiredStatus: 'completed',
    satisfiedAt: mockRecordTimestamp,
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
  {
    id: 'job_dependency_002',
    jobId: 'job_credit_estimation_001',
    dependsOnJobId: 'job_intent_analysis_001',
    dependencyType: 'requires_success',
    requiredStatus: 'completed',
    satisfiedAt: mockRecordTimestamp,
    createdAt: mockRecordTimestamp,
    updatedAt: mockRecordTimestamp,
  },
]

export const mockGenerationRequest: GenerationRequestRecord = {
  id: 'generation_request_real_motion_001',
  workspaceId: 'workspace_personal_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  editPlanSegmentId: 'edit_segment_003',
  signatureRouteId: 'signature_route_real_motion_001',
  providerType: 'google_cloud_worker',
  modelName: 'future-real-motion-provider-placeholder',
  signatureSystem: 'real_motion',
  generationType: 'real_motion_overlay',
  inputAssetIds: ['media_clip_003'],
  outputAssetType: 'generated_overlay',
  transparentBackgroundRequired: true,
  durationSeconds: 4,
  resolution: '1080x1920',
  prompt: 'Create a small realistic house overlay in the lower-right safe zone.',
  negativePrompt: 'Do not cover the speaker face. Do not make a full-screen cutaway.',
  styleConstraints: ['overlay-first', 'face-safe', 'premium subtle realism'],
  timingConstraints: ['align with phrase "major investment"'],
  status: 'waiting_user_approval',
  creditEstimate: 34,
  creditReservationId: mockCreditReservation.id,
  workerNotes: ['No provider call should happen before plan and credit approval.'],
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockPreviewRenderJob: RenderJobRecord = {
  id: 'render_job_preview_001',
  workspaceId: 'workspace_personal_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  renderType: 'preview',
  status: 'draft',
  inputAssetIds: mockSourceMediaAssets.map((asset) => asset.id),
  renderSettings: { aspect_ratio: '9:16', preview_only: true },
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockPreviewRender: RenderRecord = {
  id: 'render_preview_001',
  workspaceId: 'workspace_personal_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  renderJobId: mockPreviewRenderJob.id,
  renderType: 'preview',
  status: 'draft',
  durationSeconds: 24,
  width: 1080,
  height: 1920,
  creditsSpent: 0,
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockQAReportItem = (id: string, checkType: QAReportItem['checkType'], summary: string): QAReportItem => ({
  id,
  checkType,
  status: 'not_run',
  summary,
  blocker: false,
})

export const mockQAReport: QAReportRecord = {
  id: 'qa_report_preview_001',
  projectId: mockChatNativeProject.id,
  editPlanId: 'edit_plan_estate_001',
  renderId: mockPreviewRender.id,
  status: 'not_run',
  speechClarity: mockQAReportItem('qa_item_speech', 'speech_clarity', 'Voice clarity will be checked before preview is shown.'),
  cutSmoothness: mockQAReportItem('qa_item_cuts', 'cut_smoothness', 'Cut smoothness pending preview render.'),
  captionReadability: mockQAReportItem('qa_item_captions', 'caption_readability', 'Caption readability pending generated preview.'),
  musicBalance: mockQAReportItem('qa_item_music', 'music_balance', 'Music ducking pending SoundSync pass.'),
  sfxBalance: mockQAReportItem('qa_item_sfx', 'sfx_balance', 'SFX balance pending SoundSync pass.'),
  transitionQuality: mockQAReportItem('qa_item_transition', 'transition_quality', 'Premium subtle transitions pending preview.'),
  ambientConsistency: mockQAReportItem('qa_item_ambient', 'ambient_consistency', 'Room tone preservation pending audio pass.'),
  storyFlow: mockQAReportItem('qa_item_story', 'story_flow', 'Story flow pending edit assembly.'),
  signatureTiming: mockQAReportItem('qa_item_signature', 'signature_timing', 'Signature timing pending generation.'),
  creditCompliance: mockQAReportItem('qa_item_credit', 'credit_compliance', 'Credits must be approved before generation.'),
  userInstructionCompliance: mockQAReportItem(
    'qa_item_instruction',
    'user_instruction_compliance',
    'Must preserve natural premium feel and avoid aggressive viral pacing.',
  ),
  overallSummary: 'Preview QA has not run because this mock plan is still awaiting approval.',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockRevisionRequest: RevisionRequestRecord = {
  id: 'revision_request_001',
  projectId: mockChatNativeProject.id,
  chatMessageId: 'chat_message_revision_001',
  requestedChange: 'Make the Real Motion smaller and keep it away from my face.',
  affectedSegmentIds: ['edit_segment_003'],
  requiresNewGeneration: true,
  estimatedExtraCredits: 12,
  status: 'estimated',
  linkedEditPlanVersion: 1,
  linkedRenderId: mockPreviewRender.id,
  creditEstimateId: mockCreditEstimate.id,
  approvalStatus: 'pending',
  createdAt: mockRecordTimestamp,
  updatedAt: mockRecordTimestamp,
}

export const mockAiEditorRecords = {
  project: mockChatNativeProject,
  sourceMediaAssets: mockSourceMediaAssets,
  sourceClipSequence: mockSourceClipSequence,
  sourceClipSequenceItems: mockSourceClipSequenceItems,
  chatSession: mockChatSession,
  userInstructionMessage: mockUserInstructionMessage,
  assistantPlanMessage: mockAssistantPlanMessage,
  sourceSequenceCard: mockSourceSequenceCard,
  intentAnalysis: mockIntentAnalysis,
  basicEditQualityProfile: mockBasicEditQualityProfile,
  signatureEditQualityProfile: mockSignatureEditQualityProfile,
  strokeMotionPlan: mockStrokeMotionPlan,
  strokeMotionCharacters: mockStrokeMotionCharacters,
  strokeMotionSymbols: mockStrokeMotionSymbols,
  strokeMotionTimingAnchors: mockStrokeMotionTimingAnchors,
  strokeMotionBeats: mockStrokeMotionBeats,
  strokeMotionTransitions: mockStrokeMotionTransitions,
  strokeMotionGenerationSpec: mockStrokeMotionGenerationSpec,
  musicPlan: mockMusicPlan,
  ambientSoundPlan: mockAmbientSoundPlan,
  transitionPlan: mockTransitionPlan,
  creditEstimate: mockCreditEstimate,
  creditReservation: mockCreditReservation,
  jobChain: mockJobChain,
  jobDependencies: mockJobDependencies,
  generationRequest: mockGenerationRequest,
  previewRenderJob: mockPreviewRenderJob,
  previewRender: mockPreviewRender,
  qaReport: mockQAReport,
  revisionRequest: mockRevisionRequest,
} as const
