import type { ToolCategory, ToolPreset, ToolSettingDefinition, ToolSettingType } from '../types/reeditpro'

function setting(
  id: string,
  label: string,
  type: ToolSettingType,
  description: string,
  required = false,
  extra: Partial<ToolSettingDefinition> = {},
): ToolSettingDefinition {
  return {
    id,
    label,
    type,
    description,
    required,
    ...extra,
  }
}

function tierFit(basic: boolean, pro = true, premium = true) {
  return { basic, pro, premium }
}

function preset(params: ToolPreset): ToolPreset {
  return params
}

export const remotionSettings: ToolSettingDefinition[] = [
  setting('compositionWidth', 'Composition width', 'number', 'Final planned composition width in pixels.', true),
  setting('compositionHeight', 'Composition height', 'number', 'Final planned composition height in pixels.', true),
  setting('fps', 'FPS', 'number', 'Frames per second for the planned composition.', true),
  setting('durationInFrames', 'Duration in frames', 'number', 'Composition duration expressed in frames.', true),
  setting('aspectRatio', 'Aspect ratio', 'select', 'Target aspect ratio for layout planning.', true, { options: ['9:16', '16:9', '1:1', '4:5'] }),
  setting('frameTemplate', 'Frame template', 'string', 'Frame layout template or ReeditPro frame system id.', true),
  setting('speakerZone', 'Speaker zone', 'rect', 'Planned speaker rectangle for composition.', false),
  setting('visualZone', 'Visual zone', 'rect', 'Planned visual asset rectangle for composition.', false),
  setting('captionSafeZone', 'Caption safe zone', 'rect', 'Safe zone where captions should remain readable.', false),
  setting('layerZIndex', 'Layer z-index', 'number', 'Layer ordering for Remotion composition planning.', false),
  setting('startFrame', 'Start frame', 'number', 'Layer or motion start frame.', false),
  setting('endFrame', 'End frame', 'number', 'Layer or motion end frame.', false),
  setting('motionPreset', 'Motion preset', 'select', 'Motion design preset for a layer or panel.', false, { options: ['none', 'soft_reveal', 'push_in', 'route_reveal', 'caption_pop'] }),
  setting('transitionPreset', 'Transition preset', 'select', 'Transition family for layer or segment changes.', false, { options: ['clean_cut', 'soft_dissolve', 'slide', 'match_cut'] }),
  setting('assetFitMode', 'Asset fit mode', 'select', 'How an asset fits its assigned visual zone.', false, { options: ['contain', 'cover', 'fill', 'scale_down'] }),
  setting('panelBackgroundColor', 'Panel background color', 'color', 'Matching panel background color for generated assets and Remotion panels.', false, { defaultValue: '#f8fafc' }),
]

export const ffmpegSettings: ToolSettingDefinition[] = [
  setting('codec', 'Codec', 'select', 'Planned codec for encoding or transcode.', false, { options: ['h264', 'h265', 'prores', 'aac'] }),
  setting('bitrate', 'Bitrate', 'string', 'Target bitrate for planned encoding.'),
  setting('crf', 'CRF', 'number', 'Constant rate factor for quality/size tradeoff.', false, { min: 0, max: 51 }),
  setting('pixelFormat', 'Pixel format', 'select', 'Pixel format for compatibility.', false, { options: ['yuv420p', 'yuv422p', 'rgba'] }),
  setting('resolution', 'Resolution', 'string', 'Planned output resolution.'),
  setting('fps', 'FPS', 'number', 'Frame rate for processing or export.'),
  setting('trimRanges', 'Trim ranges', 'json', 'Planned source time ranges for trims.'),
  setting('scale', 'Scale', 'json', 'Scale filter planning values.'),
  setting('crop', 'Crop', 'rect', 'Crop rectangle for framing.'),
  setting('pad', 'Pad', 'json', 'Padding values for canvas fitting.'),
  setting('colorBalance', 'Color balance', 'json', 'Color balance adjustment planning.'),
  setting('colorLevels', 'Color levels', 'json', 'Levels adjustment planning.'),
  setting('lut3dPath', '3D LUT path', 'file_reference', 'Future approved LUT reference path.'),
  setting('lutStrength', 'LUT strength', 'number', 'Blend amount for LUT application.', false, { min: 0, max: 1 }),
  setting('brightness', 'Brightness', 'number', 'Brightness adjustment planning.', false, { min: -1, max: 1 }),
  setting('contrast', 'Contrast', 'number', 'Contrast adjustment planning.', false, { min: 0, max: 3 }),
  setting('saturation', 'Saturation', 'number', 'Saturation adjustment planning.', false, { min: 0, max: 3 }),
  setting('loudnessTarget', 'Loudness target', 'number', 'Integrated loudness target in LUFS.', false, { unit: 'LUFS' }),
  setting('truePeakTarget', 'True peak target', 'number', 'True peak ceiling for audio export.', false, { unit: 'dBTP' }),
  setting('audioNormalization', 'Audio normalization', 'boolean', 'Whether loudness normalization is planned.'),
  setting('silenceDetection', 'Silence detection', 'boolean', 'Whether silence/dead-space detection is planned.'),
]

export const openColorIOSettings: ToolSettingDefinition[] = [
  setting('inputColorSpace', 'Input color space', 'string', 'Input color space for source or generated asset.'),
  setting('workingColorSpace', 'Working color space', 'string', 'Working color space for color pipeline.'),
  setting('displayTransform', 'Display transform', 'string', 'Display transform for review/output.'),
  setting('viewTransform', 'View transform', 'string', 'View transform for planned output.'),
  setting('lookTransform', 'Look transform', 'string', 'Look transform or show LUT planning.'),
  setting('lutPath', 'LUT path', 'file_reference', 'Approved LUT path for future workers.'),
  setting('lutStrength', 'LUT strength', 'number', 'LUT blend strength.', false, { min: 0, max: 1 }),
  setting('outputColorSpace', 'Output color space', 'string', 'Output color space for delivery.'),
  setting('acesPipelineEnabled', 'ACES pipeline enabled', 'boolean', 'Whether ACES-style color management is planned.'),
]

export const openCVSettings: ToolSettingDefinition[] = [
  setting('faceDetectionConfidence', 'Face detection confidence', 'number', 'Future face-detection confidence threshold.', false, { min: 0, max: 1 }),
  setting('objectDetectionThreshold', 'Object detection threshold', 'number', 'Future object detection threshold.', false, { min: 0, max: 1 }),
  setting('cropSafetyMargin', 'Crop safety margin', 'number', 'Margin around protected face/object zones.', false, { unit: 'px' }),
  setting('blurThreshold', 'Blur threshold', 'number', 'Blur/softness threshold for QA planning.'),
  setting('histogramComparisonThreshold', 'Histogram comparison threshold', 'number', 'Histogram similarity threshold for quality/background checks.'),
  setting('sceneChangeThreshold', 'Scene change threshold', 'number', 'Scene-change detection threshold.'),
  setting('backgroundColorTolerance', 'Background color tolerance', 'number', 'Tolerance for background consistency.'),
  setting('panelBackgroundMatchTolerance', 'Panel background match tolerance', 'number', 'Tolerance for matching panel backgrounds.'),
  setting('templateMatchThreshold', 'Template match threshold', 'number', 'Threshold for template or layout match QA.'),
  setting('safeZoneCollisionThreshold', 'Safe zone collision threshold', 'number', 'Threshold for caption/face/visual overlap QA.'),
]

export const sharpSettings: ToolSettingDefinition[] = [
  setting('resizeWidth', 'Resize width', 'number', 'Target image width.'),
  setting('resizeHeight', 'Resize height', 'number', 'Target image height.'),
  setting('fitMode', 'Fit mode', 'select', 'Image fit mode.', false, { options: ['cover', 'contain', 'fill', 'inside', 'outside'] }),
  setting('cropPosition', 'Crop position', 'select', 'Crop gravity or anchor.', false, { options: ['center', 'top', 'bottom', 'left', 'right', 'entropy', 'attention'] }),
  setting('outputFormat', 'Output format', 'select', 'Planned output image format.', false, { options: ['png', 'jpeg', 'webp', 'avif'] }),
  setting('quality', 'Quality', 'number', 'Image quality/compression setting.', false, { min: 1, max: 100 }),
  setting('backgroundColor', 'Background color', 'color', 'Background fill color.'),
  setting('compositeLayers', 'Composite layers', 'json', 'Simple image composite layers.'),
  setting('blur', 'Blur', 'number', 'Blur radius for image prep.'),
  setting('sharpen', 'Sharpen', 'number', 'Sharpen amount for image prep.'),
  setting('metadataHandling', 'Metadata handling', 'select', 'Metadata preservation/removal policy.', false, { options: ['strip', 'preserve', 'minimal'] }),
]

export const mapLibreSettings: ToolSettingDefinition[] = [
  setting('mapStyle', 'Map style', 'string', 'Map style URL or approved style id.'),
  setting('centerCoordinates', 'Center coordinates', 'coordinates', 'Initial map center coordinates.'),
  setting('zoom', 'Zoom', 'number', 'Map zoom level.'),
  setting('bearing', 'Bearing', 'number', 'Map camera bearing.'),
  setting('pitch', 'Pitch', 'number', 'Map camera pitch.'),
  setting('cameraPath', 'Camera path', 'json', 'Planned map camera path keyframes.'),
  setting('flyDuration', 'Fly duration', 'number', 'Fly-to duration.', false, { unit: 'seconds' }),
  setting('flySpeed', 'Fly speed', 'number', 'Fly-to speed factor.'),
  setting('curve', 'Curve', 'number', 'Fly-to curve factor.'),
  setting('easing', 'Easing', 'string', 'Camera easing curve.'),
  setting('fitBounds', 'Fit bounds', 'json', 'Bounds for route or region reveal.'),
  setting('padding', 'Padding', 'json', 'Viewport padding around route/region.'),
  setting('routeLineColor', 'Route line color', 'color', 'Route line color.'),
  setting('routeLineWidth', 'Route line width', 'number', 'Route line width.', false, { unit: 'px' }),
  setting('pinStyle', 'Pin style', 'json', 'Pin marker styling.'),
  setting('labelStyle', 'Label style', 'json', 'Map label styling.'),
  setting('highlightRegion', 'Highlight region', 'json', 'Region highlight GeoJSON.'),
  setting('tileSource', 'Tile source', 'string', 'Approved tile source or provider id.'),
]

export const turfSettings: ToolSettingDefinition[] = [
  setting('routeCoordinates', 'Route coordinates', 'json', 'Route coordinate list.'),
  setting('distanceUnits', 'Distance units', 'select', 'Distance unit for route math.', false, { options: ['miles', 'kilometers', 'meters'] }),
  setting('boundingBoxPadding', 'Bounding box padding', 'number', 'Padding around computed bounds.'),
  setting('centerPoint', 'Center point', 'coordinates', 'Computed or user-selected center point.'),
  setting('bufferRadius', 'Buffer radius', 'number', 'Radius for buffered geography.'),
  setting('lineSimplification', 'Line simplification', 'number', 'Simplification tolerance for route geometry.'),
  setting('interpolationSteps', 'Interpolation steps', 'number', 'Number of interpolated route reveal steps.'),
]

export const d3Settings: ToolSettingDefinition[] = [
  setting('visualizationType', 'Visualization type', 'select', 'D3 diagram or chart type.', false, { options: ['money_flow', 'network', 'timeline', 'custom_chart'] }),
  setting('dataFields', 'Data fields', 'json', 'Fields used by the visualization.'),
  setting('scales', 'Scales', 'json', 'Scale definitions.'),
  setting('axes', 'Axes', 'json', 'Axis definitions.'),
  setting('colorScale', 'Color scale', 'json', 'Color scale planning.'),
  setting('lineSettings', 'Line settings', 'json', 'Line chart or route settings.'),
  setting('barSettings', 'Bar settings', 'json', 'Bar chart settings.'),
  setting('nodeLinkSettings', 'Node-link settings', 'json', 'Network or money-flow node/link settings.'),
  setting('transitionDuration', 'Transition duration', 'number', 'D3 transition duration.', false, { unit: 'ms' }),
  setting('easing', 'Easing', 'string', 'Transition easing.'),
  setting('labelPlacement', 'Label placement', 'json', 'Label placement rules.'),
  setting('annotationStyle', 'Annotation style', 'json', 'Annotation style rules.'),
  setting('svgWidth', 'SVG width', 'number', 'SVG width.', false, { unit: 'px' }),
  setting('svgHeight', 'SVG height', 'number', 'SVG height.', false, { unit: 'px' }),
]

export const eChartsSettings: ToolSettingDefinition[] = [
  setting('chartType', 'Chart type', 'select', 'Standard chart type.', false, { options: ['bar', 'line', 'pie', 'scatter', 'area', 'funnel'] }),
  setting('series', 'Series', 'json', 'Chart series data.'),
  setting('dataset', 'Dataset', 'json', 'Structured chart dataset.'),
  setting('xAxis', 'X axis', 'json', 'X-axis config.'),
  setting('yAxis', 'Y axis', 'json', 'Y-axis config.'),
  setting('legend', 'Legend', 'json', 'Legend config.'),
  setting('tooltip', 'Tooltip', 'json', 'Tooltip config for preview/planning.'),
  setting('grid', 'Grid', 'json', 'Chart grid layout.'),
  setting('colorPalette', 'Color palette', 'json', 'Brand-safe color palette.'),
  setting('animationDuration', 'Animation duration', 'number', 'Chart animation duration.', false, { unit: 'ms' }),
  setting('labelStyle', 'Label style', 'json', 'Label styling.'),
  setting('theme', 'Theme', 'string', 'Chart theme id.'),
  setting('responsiveSize', 'Responsive size', 'boolean', 'Whether chart should respond to panel size.'),
]

export const playwrightSettings: ToolSettingDefinition[] = [
  setting('url', 'URL', 'string', 'Approved capture URL.'),
  setting('viewportWidth', 'Viewport width', 'number', 'Browser viewport width.', false, { unit: 'px' }),
  setting('viewportHeight', 'Viewport height', 'number', 'Browser viewport height.', false, { unit: 'px' }),
  setting('deviceScaleFactor', 'Device scale factor', 'number', 'Device pixel ratio for screenshots.'),
  setting('fullPage', 'Full page', 'boolean', 'Capture full page instead of viewport.'),
  setting('selector', 'Selector', 'string', 'Target selector for capture.'),
  setting('clipRectangle', 'Clip rectangle', 'rect', 'Screenshot crop rectangle.'),
  setting('imageFormat', 'Image format', 'select', 'Screenshot format.', false, { options: ['png', 'jpeg'] }),
  setting('quality', 'Quality', 'number', 'JPEG quality.', false, { min: 1, max: 100 }),
  setting('waitTime', 'Wait time', 'number', 'Wait time before capture.', false, { unit: 'ms' }),
  setting('waitForSelector', 'Wait for selector', 'string', 'Selector to wait for before capture.'),
  setting('theme', 'Theme', 'select', 'Preferred UI theme for capture.', false, { options: ['light', 'dark', 'system'] }),
  setting('scrollPosition', 'Scroll position', 'json', 'Scroll position before capture.'),
]

export const lottieSettings: ToolSettingDefinition[] = [
  setting('animationJson', 'Animation JSON', 'json', 'Lottie animation JSON or reference.'),
  setting('loop', 'Loop', 'boolean', 'Whether the animation loops.'),
  setting('autoplay', 'Autoplay', 'boolean', 'Whether the animation autoplays.'),
  setting('speed', 'Speed', 'number', 'Playback speed multiplier.'),
  setting('segment', 'Segment', 'json', 'Frame segment to play.'),
  setting('renderer', 'Renderer', 'select', 'Lottie renderer.', false, { options: ['svg', 'canvas', 'html'] }),
  setting('scale', 'Scale', 'number', 'Scale multiplier.'),
  setting('opacity', 'Opacity', 'number', 'Layer opacity.', false, { min: 0, max: 1 }),
  setting('startFrame', 'Start frame', 'number', 'Start frame for layer playback.'),
  setting('endFrame', 'End frame', 'number', 'End frame for layer playback.'),
]

export const threeSettings: ToolSettingDefinition[] = [
  setting('sceneType', 'Scene type', 'string', '3D scene type or visual goal.'),
  setting('cameraPosition', 'Camera position', 'json', 'Camera position coordinates.'),
  setting('cameraFov', 'Camera FOV', 'number', 'Camera field of view.'),
  setting('lightingPreset', 'Lighting preset', 'select', '3D lighting style.', false, { options: ['studio', 'softbox', 'dramatic', 'neutral'] }),
  setting('objectModel', 'Object model', 'file_reference', 'Model reference for future worker or asset.'),
  setting('materialStyle', 'Material style', 'string', 'Material/look direction.'),
  setting('orbitPath', 'Orbit path', 'json', 'Camera orbit path keyframes.'),
  setting('renderSize', 'Render size', 'json', '3D render size.'),
  setting('backgroundColor', 'Background color', 'color', 'Scene background color.'),
]

export const audioAnalysisSettings: ToolSettingDefinition[] = [
  setting('sampleRate', 'Sample rate', 'number', 'Audio analysis sample rate.', false, { unit: 'Hz' }),
  setting('monoStereo', 'Mono/stereo', 'select', 'Channel mode for audio analysis.', false, { options: ['mono', 'stereo'] }),
  setting('trimStart', 'Trim start', 'number', 'Analysis trim start.', false, { unit: 'seconds' }),
  setting('trimEnd', 'Trim end', 'number', 'Analysis trim end.', false, { unit: 'seconds' }),
  setting('voiceCleanupEnabled', 'Voice cleanup enabled', 'boolean', 'Whether voice cleanup is planned.'),
  setting('noiseReduction', 'Noise reduction', 'boolean', 'Whether noise reduction is planned.'),
  setting('noiseReductionStrength', 'Noise reduction strength', 'select', 'Planned noise reduction strength.', false, { options: ['light', 'medium', 'strong'] }),
  setting('deEssing', 'De-essing', 'boolean', 'Whether de-essing is planned.'),
  setting('eqCleanup', 'EQ cleanup', 'boolean', 'Whether voice EQ cleanup is planned.'),
  setting('compression', 'Compression', 'boolean', 'Whether voice compression planning is enabled.'),
  setting('voiceLeveling', 'Voice leveling', 'boolean', 'Whether voice level consistency is planned.'),
  setting('breathReduction', 'Breath reduction', 'boolean', 'Whether breath reduction is planned.'),
  setting('fillerPauseHandling', 'Filler pause handling', 'string', 'How filler pauses and dead space should be handled.'),
  setting('silenceCleanup', 'Silence cleanup', 'boolean', 'Whether silence/dead-space cleanup is planned.'),
  setting('preserveEmotionalPauses', 'Preserve emotional pauses', 'boolean', 'Whether meaningful pauses should be protected.'),
  setting('targetVoiceLoudness', 'Target voice loudness', 'number', 'Voice loudness target.', false, { unit: 'LUFS' }),
  setting('truePeakLimit', 'True peak limit', 'number', 'True peak limiter target.', false, { unit: 'dBTP' }),
  setting('integratedLoudnessTarget', 'Integrated loudness target', 'number', 'Integrated loudness target.', false, { unit: 'LUFS' }),
  setting('loudnessRangeTarget', 'Loudness range target', 'number', 'Target loudness range.', false, { unit: 'LU' }),
  setting('normalizationMode', 'Normalization mode', 'select', 'Audio normalization planning mode.', false, { options: ['voice_first', 'platform', 'music_safe'] }),
  setting('platformTarget', 'Platform target', 'string', 'Target platform loudness context.'),
  setting('speechPriority', 'Speech priority', 'boolean', 'Whether speech takes priority over music and SFX.'),
  setting('musicPolicy', 'Music policy', 'select', 'Planned music bed policy.', false, { options: ['none', 'optional_subtle', 'required_subtle', 'energetic', 'cinematic', 'documentary_bed', 'luxury_soft', 'custom'] }),
  setting('musicStyle', 'Music style', 'string', 'Planned music style.'),
  setting('musicEnergy', 'Music energy', 'select', 'Planned music energy.', false, { options: ['clean', 'subtle', 'balanced', 'energetic', 'cinematic', 'high_impact'] }),
  setting('musicVolume', 'Music volume', 'string', 'Music bed volume planning.'),
  setting('duckingEnabled', 'Ducking enabled', 'boolean', 'Whether music ducking is planned.'),
  setting('duckingStrength', 'Ducking strength', 'select', 'Planned ducking strength.', false, { options: ['none', 'light', 'medium', 'strong'] }),
  setting('duckingAttack', 'Ducking attack', 'number', 'Ducking attack time.', false, { unit: 'seconds' }),
  setting('duckingRelease', 'Ducking release', 'number', 'Ducking release time.', false, { unit: 'seconds' }),
  setting('sfxPolicy', 'SFX policy', 'select', 'Planned SFX policy.', false, { options: ['none', 'minimal', 'support_transitions', 'support_key_moments', 'beat_synced', 'high_impact', 'custom'] }),
  setting('sfxIntensity', 'SFX intensity', 'select', 'Planned SFX intensity.', false, { options: ['none', 'subtle', 'balanced', 'strong'] }),
  setting('maxSfxPerMinute', 'Max SFX per minute', 'number', 'SFX density limit.'),
  setting('avoidRandomSfx', 'Avoid random SFX', 'boolean', 'Whether random SFX are explicitly disallowed.'),
  setting('musicMustNotOverpowerVoice', 'Music must not overpower voice', 'boolean', 'Voice-first music QA rule.'),
  setting('bpmDetection', 'BPM detection', 'boolean', 'Whether BPM detection is planned.'),
  setting('beatGridEnabled', 'Beat grid enabled', 'boolean', 'Whether a beat grid is planned.'),
  setting('beatPositions', 'Beat positions', 'json', 'Detected or planned beat positions.'),
  setting('onsetDetection', 'Onset detection', 'boolean', 'Whether onset detection is planned.'),
  setting('cutOnBeat', 'Cut on beat', 'boolean', 'Whether cuts should align to major beats.'),
  setting('visualRevealOnBeat', 'Visual reveal on beat', 'boolean', 'Whether visual reveals should align to beats.'),
  setting('captionEmphasisOnBeat', 'Caption emphasis on beat', 'boolean', 'Whether caption emphasis should align to beats.'),
  setting('emotionalPauseProtection', 'Emotional pause protection', 'boolean', 'Whether emotional pauses are protected from cleanup.'),
  setting('loudness', 'Loudness', 'json', 'Loudness analysis settings.'),
  setting('energy', 'Energy', 'json', 'Energy feature settings.'),
  setting('key', 'Key', 'string', 'Musical key or key detection setting.'),
  setting('mood', 'Mood', 'string', 'Audio mood/energy classification.'),
  setting('fadeDetection', 'Fade detection', 'boolean', 'Whether fade detection is planned.'),
]

export const commonToolSettings: ToolSettingDefinition[] = [
  setting('planningOnly', 'Planning only', 'boolean', 'Flags that this is catalog planning only; no package is installed or executed.', true, { defaultValue: true }),
  setting('requiresApproval', 'Requires approval', 'boolean', 'Tool execution can only happen after approved plan snapshot in future workers.', true, { defaultValue: true }),
  setting('licenseReviewRequired', 'License review required', 'boolean', 'Whether production use requires license review.'),
]

export const toolSettingsByCategory: Partial<Record<ToolCategory, ToolSettingDefinition[]>> = {
  audio_analysis: audioAnalysisSettings,
  browser_capture: playwrightSettings,
  charts_dataviz: [...d3Settings, ...eChartsSettings],
  color_management: openColorIOSettings,
  image_processing: sharpSettings,
  maps_geospatial: [...mapLibreSettings, ...turfSettings],
  renderer_compositor: remotionSettings,
  video_processing: ffmpegSettings,
  visual_analysis: openCVSettings,
}

export const toolPresets: ToolPreset[] = [
  preset({
    id: 'clean_social_caption_layout',
    label: 'Clean social caption layout',
    description: 'Remotion-led caption and safe-zone layout for clean social edits.',
    toolIds: ['remotion'],
    category: 'renderer_compositor',
    settings: { motionPreset: 'caption_pop', captionSafeZone: 'platform_safe', planningOnly: true },
    bestUseCases: ['Readable captions', 'Safe-zone layout', 'Social video'],
    avoidUseCases: ['Exact data charting', 'Backend rendering in frontend'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'premium_lower_panel',
    label: 'Premium lower panel',
    description: 'Compact lower visual panel planned in Remotion while speaker remains primary.',
    toolIds: ['remotion'],
    category: 'renderer_compositor',
    settings: { frameTemplate: 'lower_visual_panel', motionPreset: 'soft_reveal', planningOnly: true },
    bestUseCases: ['Short-form support visuals', 'Speaker-led explainers', 'Compact labels'],
    avoidUseCases: ['Dense evidence boards', 'Small unreadable diagrams'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'documentary_evidence_board',
    label: 'Documentary evidence board',
    description: 'Remotion evidence-board layout; GPT-Image-2 may create provider assets separately, but it is not an open-source tool.',
    toolIds: ['remotion'],
    category: 'renderer_compositor',
    settings: { frameTemplate: 'full_evidence_board', motionPreset: 'soft_reveal', planningOnly: true },
    bestUseCases: ['Evidence cards', 'Timelines', 'Neutral documentary visuals'],
    avoidUseCases: ['Treating allegations as verified facts', 'Provider generation before approval'],
    tierFit: tierFit(false),
  }),
  preset({
    id: 'money_flow_diagram',
    label: 'Money flow diagram',
    description: 'Controlled D3/Remotion money-flow diagram with ECharts fallback for simpler charts.',
    toolIds: ['d3', 'remotion'],
    category: 'charts_dataviz',
    settings: { visualizationType: 'money_flow', fallbackToolIds: ['echarts'], planningOnly: true },
    bestUseCases: ['Money flows', 'Network diagrams', 'Exact labels/arrows'],
    avoidUseCases: ['Generative AI video for exact data'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'product_feature_callout',
    label: 'Product feature callout',
    description: 'Remotion callout layout with optional chart or browser-capture support for product demos.',
    toolIds: ['remotion', 'd3', 'echarts', 'playwright'],
    category: 'renderer_compositor',
    settings: { frameTemplate: 'object_anchored_callout', motionPreset: 'soft_reveal', planningOnly: true },
    bestUseCases: ['Product feature labels', 'Dashboard highlights', 'SaaS callouts'],
    avoidUseCases: ['Unapproved object tracking execution'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'map_route_reveal',
    label: 'Map route reveal',
    description: 'MapLibre/Turf/Remotion planning for route reveal maps.',
    toolIds: ['maplibre', 'turf', 'remotion'],
    category: 'maps_geospatial',
    settings: { motionPreset: 'route_reveal', routeLineWidth: 4, planningOnly: true },
    bestUseCases: ['Travel routes', 'Location reveals', 'Documentary geography'],
    avoidUseCases: ['Imagined geography', 'AI-video map labels'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'real_estate_neighborhood_map',
    label: 'Real estate neighborhood map',
    description: 'Neighborhood map planning with pins, regions, and route-safe label spacing.',
    toolIds: ['maplibre', 'turf', 'remotion'],
    category: 'maps_geospatial',
    settings: { mapStyle: 'clean_neighborhood', pinStyle: 'property_pin', planningOnly: true },
    bestUseCases: ['Real estate areas', 'Neighborhood context', 'Local amenities'],
    avoidUseCases: ['Unverified location claims'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'browser_dashboard_capture',
    label: 'Browser dashboard capture',
    description: 'Playwright/Sharp/Remotion planning for approved browser or dashboard captures.',
    toolIds: ['playwright', 'sharp', 'remotion'],
    category: 'browser_capture',
    settings: { viewportWidth: 1440, viewportHeight: 900, imageFormat: 'png', planningOnly: true },
    bestUseCases: ['Website demos', 'SaaS dashboards', 'Article or app screenshots'],
    avoidUseCases: ['Private pages without permission', 'Frontend capture execution in this mock'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'clean_natural_color_pass',
    label: 'Clean natural color pass',
    description: 'FFmpeg color planning for clean natural footage correction.',
    toolIds: ['ffmpeg'],
    category: 'video_processing',
    settings: { contrast: 1.05, saturation: 1.03, planningOnly: true },
    bestUseCases: ['Basic/pro clean color', 'Natural creator footage'],
    avoidUseCases: ['Heavy cinematic look transforms without review'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'premium_clean_color_pass',
    label: 'Premium clean color pass',
    description: 'FFmpeg plus planned OpenColorIO review for premium clean color management.',
    toolIds: ['ffmpeg', 'opencolorio'],
    category: 'color_management',
    settings: { acesPipelineEnabled: true, lutStrength: 0.35, planningOnly: true },
    bestUseCases: ['Premium color consistency', 'Generated asset color matching'],
    avoidUseCases: ['Unreviewed LUTs', 'Frontend color processing'],
    tierFit: tierFit(false),
  }),
  preset({
    id: 'documentary_neutral_color_pass',
    label: 'Documentary neutral color pass',
    description: 'Neutral FFmpeg/OpenColorIO planning for documentary and case-study footage.',
    toolIds: ['ffmpeg', 'opencolorio'],
    category: 'color_management',
    settings: { saturation: 0.98, contrast: 1.02, acesPipelineEnabled: false, planningOnly: true },
    bestUseCases: ['Neutral evidence tone', 'Case-study restraint'],
    avoidUseCases: ['Stylizing allegations as sensational proof'],
    tierFit: tierFit(false),
  }),
  preset({
    id: 'voice_cleanup_basic',
    label: 'Voice cleanup basic',
    description: 'FFmpeg planning for light loudness and voice cleanup.',
    toolIds: ['ffmpeg'],
    category: 'video_processing',
    settings: { loudnessTarget: -16, truePeakTarget: -1.5, audioNormalization: true, planningOnly: true },
    bestUseCases: ['Voice clarity', 'Basic cleanup', 'Consistent loudness'],
    avoidUseCases: ['Music generation', 'Unapproved real processing'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'soundsync_subtle_premium',
    label: 'SoundSync subtle premium',
    description: 'Essentia/FFmpeg planning for subtle beat, energy, and loudness-aware SoundSync.',
    toolIds: ['essentia', 'ffmpeg'],
    category: 'audio_analysis',
    settings: { bpmDetection: true, onsetDetection: true, loudnessTarget: -16, planningOnly: true },
    bestUseCases: ['Subtle premium music timing', 'Beat-aware edits', 'Audio energy cues'],
    avoidUseCases: ['Frontend audio analysis', 'Generated music without Music QA'],
    tierFit: tierFit(false),
  }),
  preset({
    id: 'foreground_safe_zone_qa',
    label: 'Foreground safe-zone QA',
    description: 'OpenCV planning for face/object/caption safe-zone validation.',
    toolIds: ['opencv'],
    category: 'visual_analysis',
    settings: { cropSafetyMargin: 48, safeZoneCollisionThreshold: 0.1, planningOnly: true },
    bestUseCases: ['Face protection', 'Caption collision checks', 'Crop QA'],
    avoidUseCases: ['Claiming real detection in frontend mock'],
    tierFit: tierFit(true),
  }),
  preset({
    id: 'panel_background_match_qa',
    label: 'Panel background match QA',
    description: 'OpenCV/Sharp planning for generated asset and panel background matching.',
    toolIds: ['opencv', 'sharp'],
    category: 'qa_regression',
    settings: { panelBackgroundMatchTolerance: 0.08, backgroundColor: '#f8fafc', planningOnly: true },
    bestUseCases: ['Matching panel backgrounds', 'Generated asset QA'],
    avoidUseCases: ['Transparent AI-video default assumptions'],
    tierFit: tierFit(true),
  }),
]
