import {
  ALL_PROFESSIONAL_TOOL_CATALOG_IDS,
  NON_E2E_TOOL_CAPABILITY_IDS,
  PRODUCTION_TOOL_IDS,
} from './production-tool-types'
import type {
  NonE2EToolCapabilityProfile,
  ProfessionalToolCatalogId,
  ProfessionalToolCatalogProfile,
  ProductionCommercialUseStatus,
  ProductionLicenseFamily,
  ProductionLicenseRisk,
  ProductionModelWeightPolicy,
  ProductionRegistryWorkerType,
  ProductionToolCategory,
  ProductionToolExecutionMode,
  ProductionToolId,
  ProductionToolInputType,
  ProductionToolOutputType,
  ProductionToolProfile,
  ProductionToolStatus,
} from './production-tool-types'
import { getToolQAPolicy } from './tool-qa-policy'

type ProfileInput = {
  toolId: ProfessionalToolCatalogId
  displayName: string
  category: ProductionToolCategory
  description: string
  productionStatus: ProductionToolStatus
  workerType: ProductionRegistryWorkerType
  executionMode: ProductionToolExecutionMode
  inputTypes: ProductionToolInputType[]
  outputTypes: ProductionToolOutputType[]
  bestFor: string[]
  notBestFor: string[]
  supportedActions: string[]
  gpuRequired?: boolean
  cpuAllowed?: boolean
  installPhase?: string
  launchCore?: boolean
  requiredArtifacts?: ProductionToolInputType[]
  producedArtifacts?: ProductionToolOutputType[]
  fallbackToolIds?: ProfessionalToolCatalogId[]
  license?: string
  licenseFamily?: ProductionLicenseFamily
  licenseRisk?: ProductionLicenseRisk
  commercialUseStatus?: ProductionCommercialUseStatus
  distributionRisk?: ProductionLicenseRisk
  modelWeightPolicy?: ProductionModelWeightPolicy
  securityNotes?: string[]
  runtimeNotes?: string[]
  productionReadinessNotes?: string[]
}

const noModelWeights: ProductionModelWeightPolicy = {
  required: false,
  reviewStatus: 'not_required',
  commercialUseStatus: 'allowed',
  checkpointReviewRequired: false,
  notes: ['No separate model/checkpoint weight is required for this registry profile.'],
}

function needsModelWeightReview(notes: string[]): ProductionModelWeightPolicy {
  return {
    required: true,
    reviewStatus: 'needs_review',
    commercialUseStatus: 'needs_review',
    checkpointReviewRequired: true,
    notes: [
      'Repository/package license is not enough for production approval.',
      'Model/checkpoint/weight license must be reviewed separately before paid ReeditPro production use.',
      'Unknown or non-commercial weights are blocked until reviewed.',
      ...notes,
    ],
  }
}

function profile(input: ProfileInput): ProfessionalToolCatalogProfile {
  const qaPolicy = getToolQAPolicy(input.toolId)
  const modelWeightPolicy = input.modelWeightPolicy ?? noModelWeights

  return {
    toolId: input.toolId,
    displayName: input.displayName,
    category: input.category,
    description: input.description,
    productionStatus: input.productionStatus,
    adoptionStage: input.productionStatus,
    workerType: input.workerType,
    executionMode: input.executionMode,
    gpuRequired: input.gpuRequired ?? false,
    cpuAllowed: input.cpuAllowed ?? true,
    installPhase: input.installPhase ?? 'milestone_5_tool_readiness_or_later',
    launchCore: input.launchCore ?? input.productionStatus === 'launch_core',
    inputTypes: input.inputTypes,
    outputTypes: input.outputTypes,
    bestFor: input.bestFor,
    notBestFor: input.notBestFor,
    supportedActions: input.supportedActions,
    requiredArtifacts: input.requiredArtifacts ?? input.inputTypes,
    producedArtifacts: input.producedArtifacts ?? input.outputTypes,
    qaResponsibilities: qaPolicy.gateTypes,
    fallbackToolIds: input.fallbackToolIds ?? [],
    license: input.license ?? 'License review pending',
    licenseFamily: input.licenseFamily ?? 'unknown',
    licenseRisk: input.licenseRisk ?? 'unknown',
    commercialUseStatus: input.commercialUseStatus ?? 'needs_review',
    distributionRisk: input.distributionRisk ?? input.licenseRisk ?? 'unknown',
    modelWeightsRequired: modelWeightPolicy.required,
    modelWeightPolicy,
    securityNotes: input.securityNotes ?? ['Worker-only metadata; no package is installed or executed in Milestone 2.'],
    runtimeNotes: input.runtimeNotes ?? ['Future execution must load approved snapshot records and private storage artifacts by ID.'],
    productionReadinessNotes: input.productionReadinessNotes ?? ['Metadata only; production execution requires later worker/tool readiness milestones and approved evidence gates.'],
  }
}

const permissive = {
  licenseFamily: 'permissive' as const,
  licenseRisk: 'low' as const,
  commercialUseStatus: 'allowed' as const,
  distributionRisk: 'low' as const,
}

const reviewPermissive = {
  licenseFamily: 'permissive' as const,
  licenseRisk: 'medium' as const,
  commercialUseStatus: 'allowed_with_review' as const,
  distributionRisk: 'medium' as const,
}

const needsLicenseReview = {
  licenseFamily: 'unknown' as const,
  licenseRisk: 'unknown' as const,
  commercialUseStatus: 'needs_review' as const,
  distributionRisk: 'unknown' as const,
}

export const allProfessionalToolCatalogProfiles:
ProfessionalToolCatalogProfile[] = [
  profile({
    toolId: 'ffmpeg',
    displayName: 'FFmpeg',
    category: 'core_media',
    description: 'Core media processing boundary for proxy prep, trim/transcode, audio extraction, final mux/transcode, and export packaging.',
    productionStatus: 'launch_core',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['source_media', 'proxy_media', 'audio', 'video', 'render_manifest'],
    outputTypes: ['proxy_video', 'extracted_audio', 'processed_video', 'processed_audio', 'final_export', 'qa_report'],
    bestFor: ['Media probe support', 'Proxy generation', 'Audio extraction', 'Transcode/mux', 'Final export'],
    notBestFor: ['Creative planning decisions', 'Raw chat execution', 'Browser-side media work'],
    supportedActions: ['probe_support', 'proxy_encode', 'audio_extract', 'transcode', 'mux', 'final_export'],
    fallbackToolIds: ['pyav', 'vapoursynth'],
    license: 'LGPL/GPL configurable; production must use reviewed LGPL-safe build assumptions.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
    runtimeNotes: ['Final export path must originate from approved render manifests, never raw chat.'],
    productionReadinessNotes: ['Needs codec, patent, nonfree/GPL flag, and untrusted media review before production execution.'],
  }),
  profile({
    toolId: 'ffprobe',
    displayName: 'ffprobe',
    category: 'core_media',
    description: 'Technical media metadata and export inspection companion for FFmpeg.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'proxy_media', 'video', 'audio'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Stream metadata', 'Duration checks', 'Codec inspection', 'Export validation'],
    notBestFor: ['Semantic video understanding', 'Creative cut decisions by itself'],
    supportedActions: ['stream_probe', 'duration_check', 'codec_check', 'export_inspect'],
    fallbackToolIds: ['pyav'],
    license: 'Covered by reviewed FFmpeg build configuration.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
  }),
  profile({
    toolId: 'pyav',
    displayName: 'PyAV',
    category: 'core_media',
    description: 'Pythonic media decode/frame/audio access for future CPU analysis recipes.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'proxy_media', 'video', 'audio'],
    outputTypes: ['analysis_report', 'image_asset', 'extracted_audio'],
    bestFor: ['Frame access', 'Timestamp-safe decode', 'Thumbnail/keyframe extraction', 'Analysis-friendly media access'],
    notBestFor: ['Final mux/export ownership', 'Frontend decode'],
    supportedActions: ['decode_frames', 'extract_audio', 'sample_frames', 'timestamp_map'],
    fallbackToolIds: ['ffmpeg', 'opencv'],
    license: 'BSD-style PyAV license with FFmpeg linkage review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'opentimelineio',
    displayName: 'OpenTimelineIO',
    category: 'timeline',
    description: 'Structured timeline/edit-decision interchange between approved plans, workers, and render manifests.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['timeline_manifest', 'json_data'],
    outputTypes: ['timeline_manifest', 'json_spec', 'qa_report'],
    bestFor: ['Edit-decision interchange', 'Track/layer timing', 'Clip range validation', 'Render handoff'],
    notBestFor: ['Interactive editor UI', 'Media processing'],
    supportedActions: ['convert_timeline', 'validate_tracks', 'serialize_otio', 'read_edit_decisions'],
    fallbackToolIds: ['remotion', 'hyperframe'],
    license: 'Apache-2.0 working assumption; dependency review required.',
    ...permissive,
  }),
  profile({
    toolId: 'hyperframe',
    displayName: 'Hyperframe',
    category: 'timeline',
    description: 'Editor/timeline/interactive preview boundary for approved timeline state and render handoff.',
    productionStatus: 'launch_core',
    workerType: 'frontend_preview_only',
    executionMode: 'preview_boundary',
    inputTypes: ['timeline_manifest', 'render_manifest', 'json_data'],
    outputTypes: ['timeline_manifest', 'json_spec'],
    bestFor: ['Interactive preview coordination', 'Timeline UI boundary', 'Approved render handoff'],
    notBestFor: ['Backend media processing', 'Final export', 'Raw chat execution'],
    supportedActions: ['preview_timeline', 'timeline_handoff', 'editor_state_sync'],
    fallbackToolIds: ['remotion', 'opentimelineio'],
    license: 'Vendor/API/runtime review pending.',
    licenseFamily: 'commercial',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
    runtimeNotes: ['Frontend preview boundary only; it must not process source media or bypass approved snapshot policy.'],
    productionReadinessNotes: ['Core boundary decision, but integration details remain future milestone work.'],
  }),
  profile({
    toolId: 'streamer_render_pipeline_support',
    displayName: 'GStreamer render pipeline support',
    category: 'core_media',
    description: 'Backend-only render-pipeline capability validation for controlled GStreamer support checks.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'readiness_check',
    inputTypes: ['none', 'render_manifest'],
    outputTypes: ['qa_report', 'json_spec'],
    bestFor: ['Render pipeline support validation', 'Controlled internal capability checks', 'No-file-output synthetic pipeline readiness'],
    notBestFor: ['User-visible media processing by itself', 'Frontend execution', 'Final export ownership'],
    supportedActions: ['validate_render_pipeline_support', 'verify_gstreamer_binary_presence', 'record_private_readiness_evidence'],
    fallbackToolIds: ['remotion', 'ffmpeg'],
    license: 'GStreamer LGPL ecosystem working assumption; plugin selection and redistribution remain review-gated.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
    runtimeNotes: ['Runner probes may verify binary presence/API surface only; private media execution remains backend-gated.'],
    productionReadinessNotes: ['Ready as a backend adapter readiness activity, not as public/product media execution.'],
  }),
  profile({
    toolId: 'mkvtoolnix_container_validation',
    displayName: 'MKVToolNix container validation',
    category: 'core_media',
    description: 'Backend-only MKVToolNix packaging/container validation activity for approved private render artifacts.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['render_manifest', 'video', 'caption_segments'],
    outputTypes: ['qa_report', 'json_spec'],
    bestFor: ['Container validation', 'Subtitle/container packaging QA', 'Private packaging evidence'],
    notBestFor: ['Creative edit decisions', 'Public delivery unlock by itself', 'Frontend execution'],
    supportedActions: ['validate_container_packaging', 'verify_mkvmerge_binary_presence', 'record_private_packaging_evidence'],
    fallbackToolIds: ['ffmpeg'],
    license: 'GPL ecosystem working assumption; distribution and hosted-worker usage remain owner-review gated.',
    licenseFamily: 'gpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
    runtimeNotes: ['Requires approved private artifacts before any media packaging command can run.'],
    productionReadinessNotes: ['Callable as backend validation metadata; product delivery remains separately gated.'],
  }),
  profile({
    toolId: 'gpac_mp4box_packaging_validation',
    displayName: 'GPAC MP4Box packaging validation',
    category: 'core_media',
    description: 'Backend-only GPAC/MP4Box package presence and future private packaging validation activity.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['render_manifest', 'video', 'caption_segments'],
    outputTypes: ['qa_report', 'json_spec'],
    bestFor: ['MP4 packaging readiness', 'Container packaging provenance', 'Private packaging validation evidence'],
    notBestFor: ['Bento4 fallback selection', 'Frontend execution', 'Public delivery unlock by itself'],
    supportedActions: ['validate_mp4box_packaging_source', 'verify_mp4box_binary_presence', 'record_private_packaging_evidence'],
    fallbackToolIds: ['ffmpeg', 'mkvtoolnix_container_validation'],
    license: 'Official GPAC APT source approved for planning; package/runtime usage remains install-source and QA gated.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
    runtimeNotes: ['Bento4 remains separate/not selected; MP4Box media commands require approved private artifacts and QA.'],
    productionReadinessNotes: ['Install-source evidence is not production delivery approval; external beta/production remain gated.'],
  }),
  profile({
    toolId: 'remotion',
    displayName: 'Remotion',
    category: 'render_composition',
    description: 'Primary programmatic composition/render template engine for approved assets, captions, panels, cards, and motion graphics.',
    productionStatus: 'launch_core',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['render_manifest', 'timeline_manifest', 'image', 'audio', 'video', 'caption_segments'],
    outputTypes: ['preview_video', 'processed_video', 'render_manifest', 'qa_report'],
    bestFor: ['Deterministic composition', 'Caption/layout templates', 'Cards/panels', 'Motion graphics', 'Preview renders'],
    notBestFor: ['Final mux/transcode alone', 'Heavy AI model inference', 'Raw prompt-driven rendering'],
    supportedActions: ['compose_layers', 'render_preview', 'render_template', 'validate_layout'],
    fallbackToolIds: ['ffmpeg', 'hyperframe'],
    license: 'Remotion license and browser/runtime dependency review required.',
    ...reviewPermissive,
    runtimeNotes: ['Primary render/composition engine; final media export still routes through FFmpeg/libass where needed.'],
  }),
  profile({
    toolId: 'libass',
    displayName: 'libass',
    category: 'captions',
    description: 'Subtitle burn-in engine for ASS subtitle rendering where template-native text is not enough.',
    productionStatus: 'launch_core',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['caption_segments', 'render_manifest', 'video'],
    outputTypes: ['processed_video', 'final_export', 'qa_report'],
    bestFor: ['Subtitle burn-in', 'ASS style fidelity', 'Caption fallback rendering'],
    notBestFor: ['Caption segmentation decisions', 'Transcript generation'],
    supportedActions: ['burn_subtitles', 'validate_subtitle_style', 'render_caption_track'],
    fallbackToolIds: ['remotion', 'ffmpeg'],
    license: 'ISC-style working assumption; font/shaping/dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'sharp',
    displayName: 'Sharp + libvips',
    category: 'image_processing',
    description: 'Image and render asset preparation for thumbnails, resize/crop, overlays, alpha handling, and static asset QA.',
    productionStatus: 'launch_core',
    workerType: 'render_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['image', 'json_data'],
    outputTypes: ['image_asset', 'qa_report'],
    bestFor: ['Resize/crop', 'Thumbnails', 'Render assets', 'Alpha/background handling'],
    notBestFor: ['Final video rendering', 'AI matting by itself'],
    supportedActions: ['resize', 'crop', 'thumbnail', 'alpha_check', 'asset_prepare'],
    fallbackToolIds: ['openimageio', 'opencv'],
    license: 'Apache-2.0 package with libvips LGPL/dependency review.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
  }),
  profile({
    toolId: 'duckdb',
    displayName: 'DuckDB',
    category: 'qa',
    description: 'Local analytics/query engine for structured analysis artifacts, metrics, and QA summaries.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['json_data'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Artifact queries', 'QA aggregation', 'Metrics summaries', 'Structured local analysis'],
    notBestFor: ['Persistent production database replacement', 'Frontend analytics over private media'],
    supportedActions: ['query_artifacts', 'aggregate_metrics', 'validate_tables'],
    fallbackToolIds: ['polars'],
    license: 'MIT working assumption; dependency review required.',
    ...permissive,
  }),
  profile({
    toolId: 'polars',
    displayName: 'Polars',
    category: 'qa',
    description: 'Dataframe processing for analysis transforms, timing tables, and QA metric calculations.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['json_data'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Data transforms', 'Timing table processing', 'QA metrics', 'Fast dataframe work'],
    notBestFor: ['Long-lived storage', 'Raw media decode'],
    supportedActions: ['transform_tables', 'score_metrics', 'summarize_artifacts'],
    fallbackToolIds: ['duckdb'],
    license: 'MIT working assumption; dependency review required.',
    ...permissive,
  }),

  profile({
    toolId: 'faster_whisper',
    displayName: 'faster-whisper',
    category: 'speech_transcription',
    description: 'Production speech-to-text and timing candidate for transcript and caption source artifacts.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['audio', 'source_media'],
    outputTypes: ['transcript_json', 'caption_segments_json', 'analysis_report'],
    bestFor: ['Speech transcription', 'Word timing', 'Caption source data', 'Transcript intelligence'],
    notBestFor: ['Inventing missing speech', 'Frontend transcription'],
    supportedActions: ['transcribe', 'align_words', 'detect_language', 'score_confidence'],
    fallbackToolIds: ['whisper_cpp'],
    license: 'Package and CTranslate2/dependency review required.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['Whisper model weights must be approved for commercial paid production before use.']),
  }),
  profile({
    toolId: 'whisper_cpp',
    displayName: 'whisper.cpp',
    category: 'speech_transcription',
    description: 'Evaluation/fallback-only local transcription option if current planning references it.',
    productionStatus: 'evaluation_only',
    workerType: 'gpu_ai_worker',
    executionMode: 'evaluation_only',
    gpuRequired: true,
    cpuAllowed: true,
    inputTypes: ['audio', 'source_media'],
    outputTypes: ['transcript_json', 'caption_segments_json'],
    bestFor: ['Offline transcription evaluation', 'Fallback research', 'Benchmark comparison'],
    notBestFor: ['Launch-core production path', 'Browser transcription'],
    supportedActions: ['evaluate_transcription', 'benchmark_alignment'],
    fallbackToolIds: ['faster_whisper'],
    license: 'MIT-style code working assumption; model weights separately reviewed.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['Whisper model weights are separate from the code license and blocked until reviewed.']),
  }),
  profile({
    toolId: 'paddleocr',
    displayName: 'PaddleOCR',
    category: 'ocr',
    description: 'OCR candidate for screen recordings, UI text, documents, labels, and overlay collision planning.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['image', 'frame_sequence', 'video'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Screen OCR', 'UI text regions', 'Document/label text', 'Overlay no-cover zones'],
    notBestFor: ['Unreviewed private text capture', 'Final text truth without review'],
    supportedActions: ['detect_text_regions', 'ocr_frames', 'score_text_confidence', 'mark_no_cover_zones'],
    fallbackToolIds: ['opencv'],
    license: 'Apache-2.0 working assumption; model weights and privacy review required.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['PaddleOCR models require separate model/checkpoint review and privacy benchmark.']),
  }),

  profile({
    toolId: 'pyscenedetect',
    displayName: 'PySceneDetect',
    category: 'scene_detection',
    description: 'Shot and scene boundary candidate generator for smart cut and timeline analysis recipes.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'proxy_media', 'video'],
    outputTypes: ['analysis_report', 'timeline_manifest', 'json_spec'],
    bestFor: ['Scene boundary candidates', 'Transition candidates', 'Shot timing analysis'],
    notBestFor: ['Automatic cuts without meaning validation', 'Transcript-aware edit decisions by itself'],
    supportedActions: ['detect_scenes', 'score_boundaries', 'emit_cut_candidates'],
    fallbackToolIds: ['opencv', 'ffmpeg'],
    license: 'BSD/MIT-style working assumption; dependency review required.',
    ...permissive,
  }),
  profile({
    toolId: 'opencv',
    displayName: 'OpenCV',
    category: 'visual_analysis',
    description: 'CPU visual analysis and QA foundation for blur, safe zones, frame checks, masks, color probes, and render inspection.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'proxy_media', 'image', 'video', 'frame_sequence'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Blur checks', 'Safe zones', 'Frame sampling', 'Mask QA', 'Render/image QA'],
    notBestFor: ['Semantic truth by itself', 'Frontend source media processing'],
    supportedActions: ['sample_frames', 'detect_regions', 'score_blur', 'safe_zone_check', 'mask_qa'],
    fallbackToolIds: ['sharp', 'kornia'],
    license: 'Apache-2.0 working assumption; native dependency/security review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'mediapipe',
    displayName: 'MediaPipe',
    category: 'visual_analysis',
    description: 'Future visual landmark/tracking option for face/body/hand region support and safe-zone planning.',
    productionStatus: 'future',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['image', 'video', 'frame_sequence'],
    outputTypes: ['analysis_report', 'qa_report', 'json_spec'],
    bestFor: ['Face/body/hand landmarks', 'Region confidence', 'Safe-zone support'],
    notBestFor: ['Identity inference', 'Launch-core privacy-sensitive analysis'],
    supportedActions: ['detect_landmarks', 'track_regions', 'score_visibility'],
    fallbackToolIds: ['opencv', 'sam2'],
    license: 'Apache-2.0 working assumption; model/privacy review required.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['Bundled/related landmark models require separate review before paid production.']),
  }),
  profile({
    toolId: 'kornia',
    displayName: 'Kornia',
    category: 'mask_refinement',
    description: 'Tensor/GPU computer-vision operations for mask refinement, transforms, and artifact scoring.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    inputTypes: ['image', 'video', 'frame_sequence', 'mask'],
    outputTypes: ['mask_image', 'mask_sequence', 'qa_report', 'json_spec'],
    bestFor: ['Mask refinement', 'GPU image transforms', 'Artifact metrics', 'Feature operations'],
    notBestFor: ['Primary segmentation model', 'CPU-only launch assumptions'],
    supportedActions: ['refine_mask', 'score_edges', 'transform_frames', 'measure_artifacts'],
    fallbackToolIds: ['opencv'],
    license: 'Apache-2.0 working assumption; PyTorch/GPU dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'torch_torchvision',
    displayName: 'PyTorch + TorchVision',
    category: 'visual_analysis',
    description: 'GPU model-runtime foundation for tensor and vision adapters such as SAM2, BiRefNet, Kornia, and Real-ESRGAN.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'readiness_check',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['none'],
    outputTypes: ['qa_report', 'json_spec'],
    bestFor: ['GPU tensor runtime readiness', 'Vision model adapter foundation', 'Tool readiness checks'],
    notBestFor: ['Direct user-visible edit operations', 'Model execution without approved weights'],
    supportedActions: ['verify_tensor_runtime', 'verify_vision_runtime', 'report_gpu_runtime_capability'],
    fallbackToolIds: ['opencv'],
    license: 'BSD-style PyTorch/TorchVision working assumption; CUDA/runtime packaging review required.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview([
      'PyTorch and TorchVision package approval does not approve any model checkpoint loaded through this runtime.',
    ]),
    runtimeNotes: [
      'Foundation runtime only; user-facing edit tools must route through approved mask/enhancement adapters.',
      'No model weights are approved by this package/runtime profile.',
    ],
  }),
  profile({
    toolId: 'transformers',
    displayName: 'Transformers',
    category: 'visual_analysis',
    description: 'Model-loading/runtime foundation for future reviewed AI adapters. Package approval does not approve any model checkpoint.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'readiness_check',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['none'],
    outputTypes: ['qa_report', 'json_spec'],
    bestFor: ['Model adapter runtime readiness', 'Config/tokenizer runtime inspection', 'Future reviewed model routes'],
    notBestFor: ['Direct user-visible editing', 'Downloading or running unapproved models'],
    supportedActions: ['verify_transformers_runtime', 'report_model_runtime_capability'],
    fallbackToolIds: ['torch_torchvision'],
    license: 'Apache-2.0 working assumption; model licenses and checkpoints are separately reviewed.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview([
      'Every Transformers model, tokenizer, and checkpoint must be approved independently before paid production use.',
    ]),
    runtimeNotes: [
      'Package/runtime foundation only; every model weight remains separately gated.',
      'Adapters must disable downloads unless a later approved source/weight lane authorizes exact assets.',
    ],
  }),

  profile({
    toolId: 'birefnet',
    displayName: 'BiRefNet',
    category: 'background_removal',
    description: 'Foreground extraction/background removal candidate for high-quality image and video cutout recipes.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['image', 'video', 'frame_sequence'],
    outputTypes: ['mask_image', 'mask_sequence', 'image_asset', 'processed_video'],
    bestFor: ['Foreground extraction', 'Background removal', 'Image/video cutouts'],
    notBestFor: ['Automatic depth-aware overlays without mask QA', 'Paid production with unreviewed weights'],
    supportedActions: ['extract_foreground', 'generate_alpha', 'produce_masks', 'score_cutout'],
    fallbackToolIds: ['sam2', 'transparent_background', 'rembg', 'opencv', 'kornia'],
    license: 'Code/model ecosystem review required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['Not every BiRefNet-related model weight is commercial-safe; each selected checkpoint must be approved.']),
  }),
  profile({
    toolId: 'sam2',
    displayName: 'SAM 2',
    category: 'segmentation_tracking',
    description: 'Segmentation and tracking candidate for temporal masks, object/person identity, and text-behind-subject support.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['image', 'video', 'frame_sequence', 'json_data'],
    outputTypes: ['mask_image', 'mask_sequence', 'analysis_report', 'qa_report'],
    bestFor: ['Object segmentation', 'Temporal tracking', 'Mask refinement support'],
    notBestFor: ['Unreviewed checkpoint production', 'Replacing user review for ambiguous masks'],
    supportedActions: ['segment_object', 'track_mask', 'refine_temporal_mask', 'score_subject_coverage'],
    fallbackToolIds: ['birefnet', 'kornia', 'opencv'],
    license: 'Code may be acceptable, but checkpoint license review is required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['SAM 2 checkpoints require explicit checkpoint/license review even when code is acceptable.']),
  }),
  profile({
    toolId: 'comfyui',
    displayName: 'ComfyUI',
    category: 'image_processing',
    description: 'Evaluation-only fixed supervised SDXL still-generation host for approved Living Frame selected-scene requests.',
    productionStatus: 'evaluation_only',
    workerType: 'gpu_ai_worker',
    executionMode: 'evaluation_only',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['image', 'json_data'],
    outputTypes: ['image_asset', 'qa_report'],
    bestFor: ['Controlled private still generation', 'Fixed ControlNet conditioning', 'Fixed generic IP-Adapter conditioning'],
    notBestFor: ['Caller-authored graphs', 'Final canvas composition', 'Unreviewed models or paid production'],
    supportedActions: ['generate_controlled_image', 'report_generation_integrity'],
    fallbackToolIds: [],
    license: 'ComfyUI and the complete source/model closure require combined security, license, and paid-use review.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview([
      'The exact SDXL, ControlNet, LoRA, IP-Adapter, and CLIP Vision objects require independent checksum, compatibility, and paid-use approval.',
    ]),
    runtimeNotes: [
      'One fixed supervised GPU process represents ComfyUI plus its approved in-process conditioning capabilities.',
      'The current source bridge is non-E2E and may not enter production tool-call schemas or dispatch.',
    ],
  }),
  profile({
    toolId: 'transparent_background',
    displayName: 'transparent-background',
    category: 'background_removal',
    description: 'Evaluation/fallback image/video background-removal candidate for lower-complexity cutout cases.',
    productionStatus: 'evaluation_only',
    workerType: 'gpu_ai_worker',
    executionMode: 'evaluation_only',
    gpuRequired: true,
    inputTypes: ['image', 'video', 'frame_sequence'],
    outputTypes: ['mask_image', 'mask_sequence', 'image_asset'],
    bestFor: ['Background-removal evaluation', 'Image fallback testing'],
    notBestFor: ['Core launch mask path', 'Unreviewed paid production'],
    supportedActions: ['evaluate_cutout', 'fallback_mask'],
    fallbackToolIds: ['birefnet', 'sam2', 'rembg'],
    license: 'Package and model weight review required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['Transparent-background model weights require separate license and quality review.']),
  }),
  profile({
    toolId: 'rembg',
    displayName: 'rembg',
    category: 'background_removal',
    description: 'Lightweight background-removal fallback candidate for still images or lower-risk masks.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['image', 'frame_sequence'],
    outputTypes: ['mask_image', 'image_asset', 'qa_report'],
    bestFor: ['Still-image fallback masks', 'Lightweight background removal', 'Fallback comparison'],
    notBestFor: ['Premium video masks without QA', 'Complex contact-object preservation'],
    supportedActions: ['remove_background', 'generate_alpha', 'fallback_cutout'],
    fallbackToolIds: ['birefnet', 'sam2', 'opencv'],
    license: 'MIT code working assumption; model weights separately reviewed.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['Rembg/ONNX model weights require separate commercial-use review.']),
  }),

  profile({
    toolId: 'opencolorio',
    displayName: 'OpenColorIO',
    category: 'color_management',
    description: 'Professional color-management and transform engine for correction, display transforms, and generated asset matching.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'proxy_media', 'image', 'video'],
    outputTypes: ['analysis_report', 'processed_video', 'image_asset', 'qa_report'],
    bestFor: ['Color transforms', 'ACES/display management', 'Shot matching support', 'Generated asset color matching'],
    notBestFor: ['Creative overprocessing without user intent', 'Standalone final export'],
    supportedActions: ['apply_color_transform', 'validate_color_space', 'match_shots', 'score_skin_tone'],
    fallbackToolIds: ['ffmpeg', 'openimageio', 'opencv'],
    license: 'BSD-3-Clause working assumption; config/LUT pipeline review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'openimageio',
    displayName: 'OpenImageIO',
    category: 'image_processing',
    description: 'Professional image IO and still-frame pipeline for metadata, conversion, and color/image QA support.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['image', 'frame_sequence', 'json_data'],
    outputTypes: ['image_asset', 'analysis_report', 'qa_report'],
    bestFor: ['Professional image IO', 'Metadata handling', 'Color/image QA', 'Format conversion'],
    notBestFor: ['Simple resize where Sharp is enough', 'Browser image processing'],
    supportedActions: ['convert_image', 'read_metadata', 'validate_color', 'inspect_frames'],
    fallbackToolIds: ['sharp', 'opencv'],
    license: 'BSD-3-Clause working assumption; native dependency/security review required.',
    ...reviewPermissive,
  }),

  profile({
    toolId: 'deepfilternet',
    displayName: 'DeepFilterNet',
    category: 'audio_cleanup',
    description: 'Voice denoise/enhancement candidate for professional speech cleanup recipes.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: true,
    inputTypes: ['audio', 'source_media'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Speech denoise', 'Voice enhancement', 'Noisy source cleanup'],
    notBestFor: ['Heavy restoration without listening QA', 'Music separation'],
    supportedActions: ['denoise_voice', 'score_artifacts', 'produce_clean_audio'],
    fallbackToolIds: ['rnnoise', 'ffmpeg'],
    license: 'Package/license and model weight review required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['DeepFilterNet model weights must be approved and benchmarked for commercial production.']),
  }),
  profile({
    toolId: 'rnnoise',
    displayName: 'RNNoise',
    category: 'audio_cleanup',
    description: 'Lightweight noise-suppression fallback for voice cleanup when stronger models artifact.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Lightweight denoise', 'Fallback cleanup', 'CPU-safe suppression'],
    notBestFor: ['Difficult restoration', 'Music separation'],
    supportedActions: ['reduce_noise', 'fallback_denoise', 'score_speech_quality'],
    fallbackToolIds: ['ffmpeg'],
    license: 'BSD-style working assumption; native dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'demucs',
    displayName: 'Demucs',
    category: 'music_separation',
    description: 'Music/voice/stem separation candidate for advanced audio cleanup and music-over-voice recovery.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['audio', 'source_media'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Stem separation', 'Music/voice isolation', 'Music-over-voice recovery'],
    notBestFor: ['Simple denoise', 'Unreviewed production stems'],
    supportedActions: ['separate_stems', 'reduce_music_overlap', 'score_bleed'],
    fallbackToolIds: ['deepfilternet', 'rnnoise', 'ffmpeg'],
    license: 'MIT-style code working assumption; model weights separately reviewed.',
    ...reviewPermissive,
    modelWeightPolicy: needsModelWeightReview(['Demucs model weights require commercial-use review and audio artifact benchmarks.']),
  }),
  profile({
    toolId: 'librosa',
    displayName: 'librosa',
    category: 'audio_analysis',
    description: 'Python audio analysis/prototyping candidate for features, timing, and research metrics.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['Audio feature analysis', 'Research metrics', 'Prototype timing features'],
    notBestFor: ['Launch SoundSync default', 'Final mix/mastering'],
    supportedActions: ['extract_features', 'estimate_onsets', 'score_audio_metrics'],
    fallbackToolIds: ['audioflux'],
    license: 'ISC/BSD-style working assumption; dependency review required.',
    ...permissive,
  }),
  profile({
    toolId: 'audioread',
    displayName: 'audioread',
    category: 'audio_analysis',
    description: 'Audio decode/read boundary used to normalize source audio access for analysis-only workers.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'qa_report'],
    bestFor: ['Audio decode validation', 'Format-safe audio loading', 'Analysis input normalization'],
    notBestFor: ['Audio effects', 'Final mix/mastering', 'Media export'],
    supportedActions: ['verify_audio_decode', 'load_audio_for_analysis', 'report_audio_readiness'],
    fallbackToolIds: ['ffmpeg'],
    license: 'Permissive working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'pydub',
    displayName: 'pydub',
    category: 'audio_cleanup',
    description: 'CPU audio edit utility for simple approved trims, fades, gain staging, and bounded internal audio transforms.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Simple fades', 'Gain staging', 'Bounded audio segment assembly'],
    notBestFor: ['Final mastering without loudness QA', 'Advanced restoration', 'Stem separation'],
    supportedActions: ['apply_gain', 'apply_fade', 'assemble_audio_segments'],
    fallbackToolIds: ['ffmpeg'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'scipy',
    displayName: 'SciPy',
    category: 'audio_analysis',
    description: 'Scientific signal-processing support for deterministic audio metrics and filter prototypes.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['Signal metrics', 'Filter analysis', 'Deterministic audio QA features'],
    notBestFor: ['Provider-style audio generation', 'Final audio mastering by itself'],
    supportedActions: ['compute_signal_metrics', 'prepare_filter_analysis', 'score_audio_features'],
    fallbackToolIds: ['librosa'],
    license: 'BSD-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'resampy',
    displayName: 'resampy',
    category: 'audio_analysis',
    description: 'CPU sample-rate conversion support for analysis-normalized audio previews and QA comparisons.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Sample-rate normalization', 'Analysis prep', 'Audio comparison prep'],
    notBestFor: ['Creative stretch', 'Pitch effects', 'Final export muxing'],
    supportedActions: ['resample_audio', 'normalize_analysis_sample_rate', 'score_resample_artifacts'],
    fallbackToolIds: ['scipy', 'ffmpeg'],
    license: 'Permissive working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'pyloudnorm',
    displayName: 'pyloudnorm',
    category: 'audio_analysis',
    description: 'EBU R128-style loudness metering support for voice-first preview and final delivery QA.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'qa_report'],
    bestFor: ['Integrated loudness measurement', 'Voice-first loudness QA', 'Delivery loudness reports'],
    notBestFor: ['Denoise', 'Creative sound design', 'Stem separation'],
    supportedActions: ['measure_loudness', 'score_loudness_gate', 'report_lufs'],
    fallbackToolIds: ['ffmpeg'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'audioflux',
    displayName: 'AudioFlux',
    category: 'audio_analysis',
    description: 'Launch audio analysis candidate for onset, rhythm, feature extraction, and SoundSync timing maps.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['Onset/rhythm analysis', 'SoundSync timing cues', 'Energy curves', 'Beat/drop support'],
    notBestFor: ['Voice cleanup', 'Final audio mix'],
    supportedActions: ['extract_audio_features', 'detect_onsets', 'score_music_overlap'],
    fallbackToolIds: ['librosa'],
    license: 'MIT working assumption; production benchmark and dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'music21',
    displayName: 'music21',
    category: 'music_midi',
    description: 'Music-structure analysis support for symbolic/melodic timing evidence in SoundSync planning.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['Music structure notes', 'Symbolic timing context', 'Cue planning support'],
    notBestFor: ['Raw waveform cleanup', 'Final mix/mastering'],
    supportedActions: ['analyze_music_structure', 'prepare_symbolic_timing_notes', 'score_music_context'],
    fallbackToolIds: ['audioflux', 'librosa'],
    license: 'BSD-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'pretty_midi',
    displayName: 'pretty_midi',
    category: 'music_midi',
    description: 'MIDI parsing and timing support for approved music cue maps and beat-grid metadata.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['MIDI cue timing', 'Beat-grid metadata', 'Music structure QA'],
    notBestFor: ['Waveform denoise', 'Provider music generation'],
    supportedActions: ['inspect_midi_timing', 'prepare_music_cue_map', 'score_symbolic_alignment'],
    fallbackToolIds: ['mido', 'audioflux'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'mido',
    displayName: 'mido',
    category: 'music_midi',
    description: 'Lightweight MIDI message inspection support for approved symbolic timing inputs.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['MIDI event inspection', 'Cue map validation', 'Timing metadata checks'],
    notBestFor: ['Waveform processing', 'Final audio mastering'],
    supportedActions: ['inspect_midi_events', 'validate_midi_timing', 'report_midi_readiness'],
    fallbackToolIds: ['pretty_midi'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'noisereduce',
    displayName: 'noisereduce',
    category: 'audio_cleanup',
    description: 'CPU noise-reduction utility for bounded preview cleanup and audio-naturalness QA candidates.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Light noise reduction', 'Preview cleanup', 'Noise profile experiments'],
    notBestFor: ['Heavy restoration', 'Music separation', 'Unreviewed final mastering'],
    supportedActions: ['reduce_noise', 'score_noise_reduction', 'prepare_cleanup_preview'],
    fallbackToolIds: ['rnnoise', 'ffmpeg'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'pedalboard',
    displayName: 'pedalboard',
    category: 'audio_cleanup',
    description: 'CPU audio effect chain support for bounded voice-first polish and internal preview processing.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Bounded effect chains', 'Voice polish experiments', 'Preview audio cleanup'],
    notBestFor: ['Unapproved creative effects', 'Provider music generation', 'Final mastering without QA'],
    supportedActions: ['apply_effect_chain', 'score_audio_effects', 'prepare_voice_polish_preview'],
    fallbackToolIds: ['pydub', 'ffmpeg'],
    license: 'Permissive working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'mir_eval',
    displayName: 'mir_eval',
    category: 'audio_analysis',
    description: 'Music information retrieval metric support for timing/beat/cue QA reports.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'qa_report'],
    bestFor: ['Music timing metrics', 'Beat-grid comparison', 'Cue QA scoring'],
    notBestFor: ['Audio cleanup', 'Final mix/mastering'],
    supportedActions: ['score_music_timing', 'evaluate_beat_grid', 'report_music_metrics'],
    fallbackToolIds: ['librosa', 'audioflux'],
    license: 'MIT-style working assumption; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'pydub_effects',
    displayName: 'pydub effects',
    category: 'audio_cleanup',
    description: 'Named pydub effect recipes for approved fades, gain, compression-style preview polish, and QA handoff.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Approved simple effects', 'Preview gain/fade polish', 'Audio recipe handoff'],
    notBestFor: ['Arbitrary sound design', 'Provider SFX generation', 'Final mastering without QA'],
    supportedActions: ['apply_approved_effect_recipe', 'score_effect_artifacts', 'report_audio_recipe'],
    fallbackToolIds: ['pydub', 'ffmpeg'],
    license: 'Inherits pydub/dependency policy; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'ebu_r128_pyloudnorm',
    displayName: 'EBU R128 pyloudnorm',
    category: 'audio_analysis',
    description: 'Explicit EBU R128 loudness gate using pyloudnorm for voice-first delivery readiness reports.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'qa_report'],
    bestFor: ['EBU R128 loudness gate', 'Delivery loudness evidence', 'Voice-first audio QA'],
    notBestFor: ['Denoise', 'Music separation', 'Creative audio effects'],
    supportedActions: ['measure_ebu_r128_loudness', 'score_delivery_loudness', 'report_loudness_gate'],
    fallbackToolIds: ['pyloudnorm', 'ffmpeg'],
    license: 'Inherits pyloudnorm policy; dependency review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'signalsmith_stretch',
    displayName: 'Signalsmith Stretch',
    category: 'audio_analysis',
    description: 'Launch music time-stretch/pitch candidate for fitting music beds to approved timing.',
    productionStatus: 'launch_core',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Music time-stretch', 'Pitch adjustment', 'Music-bed timing fit'],
    notBestFor: ['Extreme stretch without QA', 'Voice cleanup'],
    supportedActions: ['stretch_audio', 'pitch_adjust', 'score_artifacts'],
    fallbackToolIds: ['soundtouch', 'ffmpeg'],
    license: 'MIT working assumption; audio quality review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'soundtouch',
    displayName: 'SoundTouch',
    category: 'audio_analysis',
    description: 'Optional/planned stretch/pitch fallback if included by future audio worker planning.',
    productionStatus: 'future',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Stretch/pitch fallback', 'CPU-friendly audio adjustment'],
    notBestFor: ['Launch default', 'High-ratio premium music timing'],
    supportedActions: ['stretch_audio', 'pitch_adjust'],
    fallbackToolIds: ['signalsmith_stretch', 'ffmpeg'],
    license: 'LGPL working assumption; license/distribution review required.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
  }),
  profile({
    toolId: 'rubber_band',
    displayName: 'Rubber Band',
    category: 'audio_analysis',
    description: 'Evaluation/license-review-only stretch/pitch option; not selected for launch.',
    productionStatus: 'needs_license_review',
    workerType: 'cpu_analysis_worker',
    executionMode: 'evaluation_only',
    inputTypes: ['audio'],
    outputTypes: ['processed_audio', 'qa_report'],
    bestFor: ['Research comparison', 'Future legal/product review'],
    notBestFor: ['Launch default', 'Paid production before license review'],
    supportedActions: ['evaluate_stretch_quality', 'benchmark_pitch'],
    fallbackToolIds: ['signalsmith_stretch', 'soundtouch'],
    license: 'GPL/commercial licensing review required.',
    licenseFamily: 'gpl',
    licenseRisk: 'high',
    commercialUseStatus: 'needs_review',
    distributionRisk: 'high',
  }),
  profile({
    toolId: 'essentia',
    displayName: 'Essentia',
    category: 'audio_analysis',
    description: 'Evaluation/license-review-only audio analysis option; AudioFlux remains launch audio analysis candidate.',
    productionStatus: 'needs_license_review',
    workerType: 'cpu_analysis_worker',
    executionMode: 'evaluation_only',
    inputTypes: ['audio'],
    outputTypes: ['analysis_report', 'json_spec', 'qa_report'],
    bestFor: ['Research comparison', 'Alternative audio features after review'],
    notBestFor: ['Launch SoundSync default', 'Paid production before review'],
    supportedActions: ['evaluate_audio_features', 'benchmark_analysis'],
    fallbackToolIds: ['audioflux', 'librosa'],
    license: 'AGPL/commercial licensing review required.',
    licenseFamily: 'agpl',
    licenseRisk: 'high',
    commercialUseStatus: 'needs_review',
    distributionRisk: 'high',
  }),

  profile({
    toolId: 'real_esrgan',
    displayName: 'Real-ESRGAN',
    category: 'enhancement',
    description: 'Image/video enhancement and upscaling candidate for approved low-quality assets.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['image', 'video', 'frame_sequence'],
    outputTypes: ['image_asset', 'processed_video', 'qa_report'],
    bestFor: ['Upscale', 'Enhancement', 'Thumbnail/detail improvement'],
    notBestFor: ['Misleading restoration', 'Face/product detail hallucination without QA'],
    supportedActions: ['upscale', 'enhance_detail', 'score_artifacts'],
    fallbackToolIds: ['sharp', 'ffmpeg'],
    license: 'Code and model weight review required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['Real-ESRGAN model weights must be approved for commercial paid production and artifact-tested.']),
  }),
  profile({
    toolId: 'film',
    displayName: 'FILM',
    category: 'frame_interpolation',
    description: 'Frame interpolation/slow-motion candidate for approved slow-motion recipes.',
    productionStatus: 'planned',
    workerType: 'gpu_ai_worker',
    executionMode: 'worker_recipe',
    gpuRequired: true,
    cpuAllowed: false,
    inputTypes: ['video', 'frame_sequence'],
    outputTypes: ['processed_video', 'qa_report'],
    bestFor: ['Frame interpolation', 'Slow-motion effects', 'Smoother motion'],
    notBestFor: ['Text-heavy footage', 'Faces/hands/product details without QA', 'Meaning-changing motion'],
    supportedActions: ['interpolate_frames', 'slow_motion', 'score_warping'],
    fallbackToolIds: ['ffmpeg'],
    license: 'Code and model weight review required.',
    ...needsLicenseReview,
    modelWeightPolicy: needsModelWeightReview(['FILM checkpoints/model weights require commercial-use review and warping benchmarks.']),
  }),

  profile({
    toolId: 'pixijs',
    displayName: 'PixiJS',
    category: 'motion_graphics',
    description: '2D graphics/effects option for future motion layers and high-performance visual elements.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'image', 'render_manifest'],
    outputTypes: ['image_asset', 'preview_video', 'json_spec'],
    bestFor: ['2D effects', 'Sprite-like motion', 'Canvas graphics', 'Particle-style layers when justified'],
    notBestFor: ['Random decoration', 'Exact final export by itself'],
    supportedActions: ['render_2d_layer', 'animate_sprite', 'prepare_motion_asset'],
    fallbackToolIds: ['remotion', 'lottie'],
    license: 'MIT working assumption; browser/runtime review required.',
    ...permissive,
  }),
  profile({
    toolId: 'three_js',
    displayName: 'Three.js',
    category: 'motion_graphics',
    description: '3D graphics option for product/explainer scenes and advanced visual layers.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'image', 'render_manifest'],
    outputTypes: ['image_asset', 'preview_video', 'json_spec'],
    bestFor: ['3D product mockups', '3D explainers', 'Camera motion', 'Premium visual layers'],
    notBestFor: ['Simple charts/diagrams', 'Unneeded spectacle'],
    supportedActions: ['render_3d_layer', 'animate_camera', 'prepare_3d_asset'],
    fallbackToolIds: ['babylon_js', 'remotion'],
    license: 'MIT working assumption; WebGL/render determinism review required.',
    ...permissive,
  }),
  profile({
    toolId: 'babylon_js',
    displayName: 'Babylon.js',
    category: 'motion_graphics',
    description: 'Future optional 3D scene engine if Three.js or Remotion primitives leave a proven gap.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'image', 'render_manifest'],
    outputTypes: ['image_asset', 'preview_video', 'json_spec'],
    bestFor: ['Advanced 3D scene evaluation', 'Alternative 3D pipeline comparison'],
    notBestFor: ['Launch core stack', 'Simple motion graphics'],
    supportedActions: ['evaluate_3d_scene', 'render_3d_asset'],
    fallbackToolIds: ['three_js', 'remotion'],
    license: 'Apache-2.0 working assumption; runtime review required.',
    ...permissive,
  }),
  profile({
    toolId: 'lottie',
    displayName: 'Lottie',
    category: 'motion_graphics',
    description: 'Vector animation asset format for icons, status motion, and reusable graphic accents.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['image_asset', 'preview_video', 'json_spec'],
    bestFor: ['Vector animation', 'Icon/status motion', 'Reusable brand motion'],
    notBestFor: ['Realistic video generation', 'Unlicensed marketplace animations'],
    supportedActions: ['render_vector_animation', 'validate_asset_provenance', 'prepare_motion_layer'],
    fallbackToolIds: ['remotion', 'pixijs'],
    license: 'Renderer license and individual animation provenance review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'animejs',
    displayName: 'Anime.js',
    category: 'motion_graphics',
    description: 'Timeline/easing helper for controlled motion-graphics layers, micro-interactions, and deterministic animation metadata.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['preview_video', 'json_spec'],
    bestFor: ['Motion timing helpers', 'Easing curves', 'Micro-animation specs', 'Layer animation metadata'],
    notBestFor: ['Final media export by itself', 'Random decorative movement'],
    supportedActions: ['prepare_animation_timeline', 'validate_easing', 'drive_motion_layer'],
    fallbackToolIds: ['remotion', 'lottie'],
    license: 'MIT working assumption; render/runtime determinism review required.',
    ...permissive,
  }),
  profile({
    toolId: 'satori',
    displayName: 'Satori',
    category: 'motion_graphics',
    description: 'React/JSX-to-SVG card and social visual renderer for exact text/layout image assets.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'html', 'css', 'render_manifest'],
    outputTypes: ['image_asset', 'json_spec'],
    bestFor: ['Exact text cards', 'Quote cards', 'Thumbnail/card SVGs', 'Clean social graphics'],
    notBestFor: ['Video composition by itself', 'Untrusted HTML rendering'],
    supportedActions: ['render_svg_card', 'validate_text_layout', 'prepare_card_asset'],
    fallbackToolIds: ['remotion', 'svg_js'],
    license: 'MPL-2.0 working assumption; font and HTML/CSS safety review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'svg_js',
    displayName: 'SVG.js',
    category: 'motion_graphics',
    description: 'Programmatic SVG construction/manipulation option for exact vector overlays and diagram assets.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['image_asset', 'chart_visual', 'json_spec'],
    bestFor: ['Exact vector overlays', 'SVG asset manipulation', 'Diagram layer prep'],
    notBestFor: ['Raster/video processing', 'Unbounded user HTML execution'],
    supportedActions: ['build_svg_asset', 'validate_vector_bounds', 'prepare_overlay_asset'],
    fallbackToolIds: ['d3', 'remotion'],
    license: 'MIT working assumption.',
    ...permissive,
  }),

  profile({
    toolId: 'playwright',
    displayName: 'Playwright',
    category: 'browser_capture',
    description: 'Browser capture and UI regression candidate for approved pages, dashboards, and app screenshots.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['url', 'html', 'css'],
    outputTypes: ['image_asset', 'qa_report', 'json_spec'],
    bestFor: ['Authorized browser screenshots', 'Dashboard capture', 'UI regression', 'Screen assets'],
    notBestFor: ['Bypassing auth/paywalls/CAPTCHAs', 'Private capture without approval'],
    supportedActions: ['capture_page', 'screenshot_dashboard', 'visual_regression', 'extract_dom_metrics'],
    fallbackToolIds: ['sharp', 'remotion'],
    license: 'Apache-2.0 working assumption; browser sandbox/security review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'maplibre',
    displayName: 'MapLibre',
    category: 'maps_geospatial',
    description: 'Controlled map visual planning/render candidate for routes, pins, labels, and geographic context.',
    productionStatus: 'planned',
    workerType: 'planning_only',
    executionMode: 'planning_metadata',
    inputTypes: ['geojson', 'json_data'],
    outputTypes: ['map_visual', 'json_spec'],
    bestFor: ['Controlled maps', 'Routes', 'Pins', 'Location context', 'Geographic labels'],
    notBestFor: ['AI-invented geography', 'Unverified exact location claims'],
    supportedActions: ['plan_map_visual', 'route_reveal', 'pin_layout', 'label_safe_zones'],
    fallbackToolIds: ['turf', 'remotion'],
    license: 'BSD-style working assumption; map data/provider terms reviewed separately.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'turf',
    displayName: 'Turf',
    category: 'maps_geospatial',
    description: 'Geospatial math for bounds, distances, route prep, and deterministic map geometry metadata.',
    productionStatus: 'planned',
    workerType: 'planning_only',
    executionMode: 'planning_metadata',
    inputTypes: ['geojson', 'json_data'],
    outputTypes: ['json_spec'],
    bestFor: ['Route geometry', 'Bounds', 'Distances', 'GeoJSON transforms'],
    notBestFor: ['Map rendering by itself', 'Unverified location truth'],
    supportedActions: ['compute_bounds', 'measure_distance', 'simplify_route', 'prepare_geometry'],
    fallbackToolIds: ['maplibre'],
    license: 'MIT working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'd3',
    displayName: 'D3',
    category: 'charts_dataviz',
    description: 'Custom chart/diagram/data-visual planning for exact labels, arrows, timelines, and money-flow visuals.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['chart_visual', 'image_asset', 'json_spec'],
    bestFor: ['Custom diagrams', 'Money flows', 'Timelines', 'Exact labels/arrows'],
    notBestFor: ['Random decorative visuals', 'AI-invented numbers'],
    supportedActions: ['plan_chart', 'build_diagram_spec', 'validate_labels'],
    fallbackToolIds: ['echarts', 'remotion'],
    license: 'ISC working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'echarts',
    displayName: 'ECharts',
    category: 'charts_dataviz',
    description: 'Standard chart visual candidate for business metrics, dashboards, and repeatable data cards.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['chart_visual', 'image_asset', 'json_spec'],
    bestFor: ['Business charts', 'Metric cards', 'Dashboard visuals', 'Standard series charts'],
    notBestFor: ['Highly custom diagrams where D3 is better'],
    supportedActions: ['plan_standard_chart', 'validate_chart_labels', 'prepare_chart_spec'],
    fallbackToolIds: ['d3', 'vega_lite'],
    license: 'Apache-2.0 working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'vega',
    displayName: 'Vega',
    category: 'charts_dataviz',
    description: 'Declarative visualization runtime for richer chart specs when Vega-Lite is not expressive enough.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['chart_visual', 'image_asset', 'json_spec'],
    bestFor: ['Rich declarative chart specs', 'Complex layered data visualizations', 'Source-linked chart rendering'],
    notBestFor: ['Simple charts where ECharts or Vega-Lite is clearer', 'AI-invented data visuals'],
    supportedActions: ['render_vega_spec', 'validate_visual_encoding', 'prepare_chart_asset'],
    fallbackToolIds: ['vega_lite', 'echarts', 'd3'],
    license: 'BSD-3-Clause working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'vega_lite',
    displayName: 'Vega-Lite',
    category: 'charts_dataviz',
    description: 'Declarative chart-spec candidate for structured, repeatable, source-linked chart visuals.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['chart_visual', 'image_asset', 'json_spec'],
    bestFor: ['Declarative chart specs', 'Repeatable chart templates', 'Source-linked dataviz'],
    notBestFor: ['Launch default chart path', 'Non-data graphics'],
    supportedActions: ['prepare_declarative_spec', 'validate_encoding'],
    fallbackToolIds: ['echarts', 'd3'],
    license: 'BSD-3-Clause working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'viz_js',
    displayName: 'Viz.js',
    category: 'charts_dataviz',
    description: 'Graphviz/DOT rendering candidate for controlled graph, hierarchy, and relationship diagrams.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['chart_visual', 'image_asset', 'json_spec'],
    bestFor: ['Graph diagrams', 'Hierarchy charts', 'Relationship maps', 'DOT-to-SVG rendering'],
    notBestFor: ['Freeform motion graphics', 'Untrusted DOT execution without sandboxing'],
    supportedActions: ['render_dot_graph', 'validate_graph_layout', 'prepare_diagram_asset'],
    fallbackToolIds: ['d3', 'svg_js', 'remotion'],
    license: 'MIT/EPL Graphviz ecosystem review required.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'deck_gl',
    displayName: 'deck.gl',
    category: 'maps_geospatial',
    description: 'Advanced geospatial/dataviz candidate for arcs, heatmaps, point clouds, and rich map overlays.',
    productionStatus: 'future',
    workerType: 'planning_only',
    executionMode: 'planning_metadata',
    inputTypes: ['geojson', 'json_data'],
    outputTypes: ['map_visual', 'chart_visual', 'json_spec'],
    bestFor: ['Advanced map overlays', 'Arcs/heatmaps', 'Geospatial data visualization'],
    notBestFor: ['Simple route/pin maps', 'Launch default'],
    supportedActions: ['plan_advanced_map_layer', 'prepare_dataviz_overlay'],
    fallbackToolIds: ['maplibre', 'd3'],
    license: 'MIT working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'cesium_js',
    displayName: 'CesiumJS',
    category: 'maps_geospatial',
    description: 'Future 3D globe/map option for premium geographic reveals when 2D map tools are insufficient.',
    productionStatus: 'future',
    workerType: 'planning_only',
    executionMode: 'planning_metadata',
    inputTypes: ['geojson', 'json_data'],
    outputTypes: ['map_visual', 'json_spec'],
    bestFor: ['3D globe', 'World-scale location context', 'Premium geographic reveals'],
    notBestFor: ['Launch default', 'Simple local maps'],
    supportedActions: ['plan_globe_scene', 'prepare_3d_map_camera'],
    fallbackToolIds: ['maplibre', 'deck_gl'],
    license: 'Apache-2.0 working assumption; terrain/tile terms reviewed separately.',
    ...reviewPermissive,
  }),
  profile({
    toolId: 'konva',
    displayName: 'Konva',
    category: 'motion_graphics',
    description: '2D canvas editing/planning option for future exact overlays, shapes, and editor interactions.',
    productionStatus: 'planned',
    workerType: 'render_worker',
    executionMode: 'render_pipeline',
    inputTypes: ['json_data', 'render_manifest'],
    outputTypes: ['json_spec', 'image_asset'],
    bestFor: ['Editable 2D overlays', 'Shape specs', 'Future design-editor interactions'],
    notBestFor: ['Final video export', 'Heavy media processing'],
    supportedActions: ['prepare_canvas_spec', 'validate_shapes', 'plan_editable_overlay'],
    fallbackToolIds: ['remotion', 'pixijs'],
    license: 'MIT working assumption.',
    ...permissive,
  }),
  profile({
    toolId: 'vapoursynth',
    displayName: 'VapourSynth',
    category: 'core_media',
    description: 'Worker-only frame/native video pipeline candidate for future scripted processing and Python-native frame flows.',
    productionStatus: 'planned',
    workerType: 'cpu_analysis_worker',
    executionMode: 'worker_recipe',
    inputTypes: ['source_media', 'video', 'frame_sequence'],
    outputTypes: ['processed_video', 'qa_report'],
    bestFor: ['Frame-level processing', 'Scripted preprocess', 'Python-native frame flows'],
    notBestFor: ['Frontend processing', 'Unreviewed plugins', 'Launch render core replacement'],
    supportedActions: ['process_frames', 'run_scripted_pipeline', 'prepare_clip'],
    fallbackToolIds: ['ffmpeg', 'pyav'],
    license: 'LGPL-2.1 working assumption; plugins separately reviewed.',
    licenseFamily: 'lgpl',
    licenseRisk: 'medium',
    commercialUseStatus: 'allowed_with_review',
    distributionRisk: 'medium',
  }),
  profile({
    toolId: 'revideo',
    displayName: 'Revideo',
    category: 'evaluation',
    description: 'Evaluation-only future optional composition framework, not core and not installed unless a proven Remotion/Hyperframe gap exists.',
    productionStatus: 'evaluation_only',
    workerType: 'planning_only',
    executionMode: 'evaluation_only',
    inputTypes: ['render_manifest', 'timeline_manifest', 'json_data'],
    outputTypes: ['json_spec', 'preview_video'],
    bestFor: ['Future gap analysis', 'Composition framework comparison', 'Research only'],
    notBestFor: ['Core render stack', 'Launch dependency', 'Production execution'],
    supportedActions: ['evaluate_render_gap', 'compare_with_remotion'],
    fallbackToolIds: ['hyperframe', 'remotion', 'ffmpeg', 'libass', 'opentimelineio'],
    license: 'Evaluation-only; dependency review only after a documented core-stack gap.',
    licenseFamily: 'unknown',
    licenseRisk: 'unknown',
    commercialUseStatus: 'unknown',
    distributionRisk: 'unknown',
    runtimeNotes: ['Blocked from core render execution. Revideo is not required, installed, or production-executable in this registry.'],
    productionReadinessNotes: ['Evaluation-only and future optional. Core stack remains Hyperframe + Remotion + FFmpeg + libass + OpenTimelineIO.'],
  }),
]

const profileById = new Map(
  allProfessionalToolCatalogProfiles.map((tool) => [tool.toolId, tool]),
)
const missingProfiles = ALL_PROFESSIONAL_TOOL_CATALOG_IDS.filter(
  (toolId) => !profileById.has(toolId),
)

if (missingProfiles.length > 0) {
  throw new Error(`Professional tool catalog profiles missing required identities: ${missingProfiles.join(', ')}`)
}

if (
  profileById.size !== ALL_PROFESSIONAL_TOOL_CATALOG_IDS.length ||
  allProfessionalToolCatalogProfiles.length !==
    ALL_PROFESSIONAL_TOOL_CATALOG_IDS.length
) {
  throw new Error('Professional tool catalog must contain exactly one profile per known identity.')
}

const productionToolIdSet = new Set<string>(PRODUCTION_TOOL_IDS)

export const productionToolProfiles: ProductionToolProfile[] =
  PRODUCTION_TOOL_IDS.map((toolId) => {
    const profile = profileById.get(toolId)!
    return {
      ...profile,
      toolId,
      fallbackToolIds: profile.fallbackToolIds.filter(
        (fallbackToolId): fallbackToolId is ProductionToolId =>
          productionToolIdSet.has(fallbackToolId),
      ),
    }
  })

export const nonE2EToolCapabilityProfiles:
NonE2EToolCapabilityProfile[] =
  NON_E2E_TOOL_CAPABILITY_IDS.map((toolId) => ({
    ...profileById.get(toolId)!,
    toolId,
  }))
