import type { ProductionQAProfile, ProductionToolId } from './production-tool-types'

const empty: ProductionQAProfile = {
  gateTypes: [],
  requiredBeforePreview: [],
  requiredBeforeFinalExport: [],
  notes: ['No direct QA gate; readiness or planning metadata only.'],
}

export const PRODUCTION_TOOL_QA_POLICIES: Record<ProductionToolId, ProductionQAProfile> = {
  ffmpeg: {
    gateTypes: ['export_codec_format', 'export_duration_sync', 'audio_loudness', 'final_delivery'],
    requiredBeforePreview: ['export_duration_sync'],
    requiredBeforeFinalExport: ['export_codec_format', 'export_duration_sync', 'final_delivery'],
    notes: ['Validates stream/container/export integrity and final delivery sync.'],
  },
  ffprobe: {
    gateTypes: ['render_asset_integrity', 'export_codec_format', 'export_duration_sync'],
    requiredBeforePreview: ['render_asset_integrity'],
    requiredBeforeFinalExport: ['export_codec_format', 'export_duration_sync'],
    notes: ['Metadata QA for inputs and final exports.'],
  },
  pyav: { ...empty, gateTypes: ['render_asset_integrity'], requiredBeforePreview: ['render_asset_integrity'] },
  opentimelineio: { ...empty, gateTypes: ['render_timeline_integrity'], requiredBeforeFinalExport: ['render_timeline_integrity'] },
  hyperframe: { ...empty, gateTypes: ['render_timeline_integrity'], requiredBeforePreview: ['render_timeline_integrity'] },
  streamer_render_pipeline_support: {
    ...empty,
    gateTypes: ['render_asset_integrity', 'render_timeline_integrity'],
    requiredBeforePreview: ['render_asset_integrity'],
    notes: ['Backend-only GStreamer render-pipeline support validation for approved internal runs.'],
  },
  mkvtoolnix_container_validation: {
    ...empty,
    gateTypes: ['export_codec_format', 'export_duration_sync', 'render_asset_integrity'],
    requiredBeforeFinalExport: ['export_codec_format', 'export_duration_sync'],
    notes: ['Backend-only MKVToolNix container validation for private packaging evidence.'],
  },
  gpac_mp4box_packaging_validation: {
    ...empty,
    gateTypes: ['export_codec_format', 'export_duration_sync', 'final_delivery'],
    requiredBeforeFinalExport: ['export_codec_format', 'export_duration_sync', 'final_delivery'],
    notes: ['Backend-only GPAC/MP4Box packaging validation; media commands remain gated by approved private artifacts.'],
  },
  remotion: {
    gateTypes: ['caption_safe_zone', 'render_asset_integrity', 'render_timeline_integrity', 'final_delivery'],
    requiredBeforePreview: ['render_asset_integrity', 'render_timeline_integrity'],
    requiredBeforeFinalExport: ['caption_safe_zone', 'render_asset_integrity', 'render_timeline_integrity', 'final_delivery'],
    notes: ['Primary programmatic composition/render template QA.'],
  },
  libass: { ...empty, gateTypes: ['caption_readability', 'caption_timing', 'caption_safe_zone'], requiredBeforeFinalExport: ['caption_readability', 'caption_timing', 'caption_safe_zone'] },
  sharp: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  duckdb: { ...empty, gateTypes: ['render_timeline_integrity'] },
  polars: { ...empty, gateTypes: ['render_timeline_integrity'] },
  faster_whisper: { ...empty, gateTypes: ['transcript_alignment', 'caption_timing'], requiredBeforePreview: ['transcript_alignment'] },
  whisper_cpp: { ...empty, gateTypes: ['transcript_alignment'], requiredBeforePreview: [] },
  paddleocr: { ...empty, gateTypes: ['ocr_text_overlap', 'caption_safe_zone'], requiredBeforePreview: ['ocr_text_overlap'] },
  pyscenedetect: { ...empty, gateTypes: ['cut_smoothness'], requiredBeforePreview: ['cut_smoothness'] },
  opencv: { ...empty, gateTypes: ['caption_safe_zone', 'mask_edge_quality', 'render_asset_integrity', 'color_exposure'], requiredBeforePreview: ['render_asset_integrity'] },
  mediapipe: { ...empty, gateTypes: ['caption_safe_zone', 'mask_subject_coverage'], requiredBeforePreview: ['caption_safe_zone'] },
  kornia: { ...empty, gateTypes: ['mask_edge_quality', 'mask_temporal_stability', 'enhancement_artifacts'], requiredBeforePreview: ['mask_edge_quality'] },
  birefnet: { ...empty, gateTypes: ['mask_edge_quality', 'mask_subject_coverage'], requiredBeforePreview: ['mask_edge_quality'], requiredBeforeFinalExport: ['mask_edge_quality', 'mask_subject_coverage'] },
  sam2: { ...empty, gateTypes: ['mask_edge_quality', 'mask_temporal_stability', 'mask_subject_coverage'], requiredBeforePreview: ['mask_temporal_stability'], requiredBeforeFinalExport: ['mask_edge_quality', 'mask_temporal_stability', 'mask_subject_coverage'] },
  transparent_background: { ...empty, gateTypes: ['mask_edge_quality', 'mask_subject_coverage'], requiredBeforePreview: ['mask_edge_quality'] },
  rembg: { ...empty, gateTypes: ['mask_edge_quality', 'mask_subject_coverage'], requiredBeforePreview: ['mask_edge_quality'] },
  opencolorio: { ...empty, gateTypes: ['color_exposure', 'color_skin_tone', 'color_export_space', 'color_shot_match'], requiredBeforePreview: ['color_exposure'], requiredBeforeFinalExport: ['color_exposure', 'color_skin_tone', 'color_export_space', 'color_shot_match'] },
  openimageio: { ...empty, gateTypes: ['color_export_space', 'render_asset_integrity'], requiredBeforeFinalExport: ['color_export_space'] },
  deepfilternet: { ...empty, gateTypes: ['audio_loudness', 'audio_naturalness', 'audio_sync'], requiredBeforePreview: ['audio_naturalness'], requiredBeforeFinalExport: ['audio_loudness', 'audio_naturalness'] },
  rnnoise: { ...empty, gateTypes: ['audio_naturalness', 'audio_loudness'], requiredBeforePreview: ['audio_naturalness'] },
  demucs: { ...empty, gateTypes: ['audio_naturalness', 'music_over_voice', 'audio_sync'], requiredBeforeFinalExport: ['music_over_voice', 'audio_naturalness'] },
  librosa: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: ['audio_sync'] },
  audioread: { ...empty, gateTypes: ['render_asset_integrity', 'audio_sync'], requiredBeforePreview: ['render_asset_integrity'] },
  pydub: { ...empty, gateTypes: ['audio_loudness', 'audio_naturalness', 'audio_sync'], requiredBeforePreview: ['audio_naturalness'] },
  scipy: { ...empty, gateTypes: ['audio_sync', 'audio_naturalness'], requiredBeforePreview: ['audio_sync'] },
  resampy: { ...empty, gateTypes: ['audio_sync', 'audio_naturalness'], requiredBeforePreview: ['audio_sync'] },
  pyloudnorm: { ...empty, gateTypes: ['audio_loudness'], requiredBeforePreview: ['audio_loudness'], requiredBeforeFinalExport: ['audio_loudness'] },
  audioflux: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: ['audio_sync'] },
  music21: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: ['audio_sync'] },
  pretty_midi: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: ['audio_sync'] },
  mido: { ...empty, gateTypes: ['audio_sync'], requiredBeforePreview: ['audio_sync'] },
  noisereduce: { ...empty, gateTypes: ['audio_naturalness', 'audio_loudness'], requiredBeforePreview: ['audio_naturalness'] },
  pedalboard: { ...empty, gateTypes: ['audio_naturalness', 'audio_loudness', 'audio_sync'], requiredBeforePreview: ['audio_naturalness'] },
  mir_eval: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: ['audio_sync'] },
  pydub_effects: { ...empty, gateTypes: ['audio_naturalness', 'audio_loudness', 'audio_sync'], requiredBeforePreview: ['audio_naturalness'] },
  ebu_r128_pyloudnorm: { ...empty, gateTypes: ['audio_loudness'], requiredBeforePreview: ['audio_loudness'], requiredBeforeFinalExport: ['audio_loudness'] },
  signalsmith_stretch: { ...empty, gateTypes: ['audio_naturalness', 'audio_sync'], requiredBeforeFinalExport: ['audio_naturalness', 'audio_sync'] },
  soundtouch: { ...empty, gateTypes: ['audio_naturalness', 'audio_sync'], requiredBeforeFinalExport: ['audio_naturalness'] },
  rubber_band: { ...empty, gateTypes: ['audio_naturalness', 'audio_sync'], requiredBeforeFinalExport: ['audio_naturalness'] },
  essentia: { ...empty, gateTypes: ['audio_sync', 'music_over_voice'], requiredBeforePreview: [] },
  real_esrgan: { ...empty, gateTypes: ['enhancement_artifacts', 'render_asset_integrity'], requiredBeforePreview: ['enhancement_artifacts'], requiredBeforeFinalExport: ['enhancement_artifacts'] },
  film: { ...empty, gateTypes: ['slow_motion_artifacts', 'export_duration_sync'], requiredBeforePreview: ['slow_motion_artifacts'], requiredBeforeFinalExport: ['slow_motion_artifacts', 'export_duration_sync'] },
  pixijs: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  three_js: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  babylon_js: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  lottie: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  animejs: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  satori: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  svg_js: { ...empty, gateTypes: ['render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  playwright: { ...empty, gateTypes: ['ocr_text_overlap', 'render_asset_integrity', 'caption_safe_zone'], requiredBeforePreview: ['render_asset_integrity'] },
  maplibre: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'], requiredBeforePreview: ['render_asset_integrity'] },
  turf: { ...empty, gateTypes: ['render_asset_integrity'] },
  d3: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'], requiredBeforePreview: ['render_asset_integrity'] },
  echarts: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'], requiredBeforePreview: ['render_asset_integrity'] },
  vega: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  vega_lite: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  viz_js: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  deck_gl: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  cesium_js: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  konva: { ...empty, gateTypes: ['caption_safe_zone', 'render_asset_integrity'] },
  torch_torchvision: { ...empty, gateTypes: ['render_asset_integrity', 'mask_edge_quality', 'enhancement_artifacts'] },
  transformers: { ...empty, gateTypes: ['render_asset_integrity', 'mask_edge_quality', 'enhancement_artifacts'] },
  vapoursynth: { ...empty, gateTypes: ['render_asset_integrity', 'export_duration_sync'], requiredBeforePreview: ['render_asset_integrity'] },
  revideo: { ...empty, gateTypes: ['render_asset_integrity', 'render_timeline_integrity'], notes: ['Evaluation-only; not a core render QA path.'] },
}

export function getToolQAPolicy(toolId: ProductionToolId): ProductionQAProfile {
  return PRODUCTION_TOOL_QA_POLICIES[toolId]
}
