import type { OfflineAiCapabilityRequest, OfflineAiCapabilityToolId } from './offline-ai-capability-protocol'

export interface OfflineAiCapabilityImageEvidence { imageTag: 'reeditpro-offline-ai-capability-execution:private-local-v1'; imageId: string; imageIdentityHash: string; pinnedBaseImage: 'python:3.13.11-slim-bookworm@sha256:20080e807bfc404f8450b185cf0fc95d553462673598549613735f70a5b4d5d0'; sourceHashes: Readonly<Record<string, string>>; imageUser: '10001:10001'; imageEntrypoint: readonly ['python', '-s', '/app/runner.py']; imageEnvironmentNames: readonly string[]; rootFilesystemLayerDigests: readonly string[]; labels: Readonly<Record<string, string>> }
export interface OfflineAiCapabilityConfinementEvidence { networkMode: 'none'; readOnlyRootFilesystem: true; capDropAll: true; noNewPrivileges: true; privileged: false; pidsLimit: 256; memoryLimitBytes: 4294967296; memoryAndSwapLimitBytes: 4294967296; nanoCpus: 2000000000; tmpfsPath: '/tmp'; tmpfsSizeBytes: 536870912; tmpfsNoExec: true; tmpfsNoSuid: true; tmpfsNoDevice: true; user: '10001:10001'; callerCommandPresent: false; callerBindsPresent: false; callerMountsPresent: false; callerEnvironmentPresent: false; secretLikeImageEnvironmentNames: readonly [] }
export interface OfflineAiCapabilityExecutionResult {
  schemaVersion: 'offline-ai-capability-execution-result-v1'; request: OfflineAiCapabilityRequest
  artifact: { mimeType: 'application/json' | 'image/png'; bytes: Buffer; byteLength: number; sha256: string }
  evidence: { packageName: string; packageVersion: string; requestEnvelopeSha256: string; image: OfflineAiCapabilityImageEvidence; confinement: OfflineAiCapabilityConfinementEvidence; semanticEvidence: Readonly<Record<string, boolean | number | string>>; containerExitCode: 0; oomKilled: false }
  attestation: { schemaVersion: 'offline-ai-capability-execution-attestation-v1'; recordId: string; completedAt: string; toolId: OfflineAiCapabilityToolId; imageIdentityHash: string; requestEnvelopeSha256: string; artifactSha256: string; confinementHash: string; attestationHash: string }
  readiness: { privateInternalOnly: true; exactStructuredPayloadOnly: true; canonicalDispatchIntegrated: false; modelWeightsLoaded: false; productReady: false; externalBetaReady: false; productionReady: false }
}
export interface OfflineAiCapabilityRuntimeAuthority { schemaVersion: 'offline-ai-capability-runtime-authority-v1'; source: 'private_local_offline_ai_capability_runtime_authority'; activatedAt: string; image: OfflineAiCapabilityImageEvidence; supportedOperations: readonly { toolId: OfflineAiCapabilityToolId; operationId: string }[]; readiness: { privateInternalExecutionReady: true; exactStructuredPayloadOnly: true; canonicalDispatchMayReference: true; modelWeightsLoaded: false; productReady: false; externalBetaReady: false; productionReady: false }; blockers: readonly string[]; authorityHash: string }
