import {
  CURRENT_MILESTONE_REQUIRED_TOOL_IDS,
  EDITING_TOOL_IDS,
  type EditingToolContract,
  type EditingToolId,
} from './editing-tool-contracts'

export const EDITING_TOOL_REGISTRY = {
  ffmpeg: {
    toolId: 'ffmpeg',
    displayName: 'FFmpeg',
    productionPurpose: 'Transcode, trim, mux, encode previews/exports, normalize audio, and generate tiny staging fixtures.',
    workerBoundary: 'staging-canary-worker',
    requiredForMilestones: ['staging_render_infrastructure_canary', 'staging_real_video_upload_preview_canary', 'staging_media_analysis_canary', 'staging_timeline_composition_canary', 'production_render_worker'],
    optionalUntil: 'Not optional for render or media-processing workers.',
    installTarget: 'worker_image',
    runtimeCheck: { runtimeCheckCommand: 'ffmpeg -version', safeCheckOnly: true },
    expectedVersionShape: 'First version line begins with ffmpeg version.',
    inputContracts: ['Local worker temp file path or approved storage object copied to worker temp.'],
    outputContracts: ['Bounded media artifact plus checksum, MIME, duration, frame, and object metadata.'],
    timeoutMs: 300000,
    memoryHint: '512Mi minimum for probes/simple transcodes; higher by approved worker profile.',
    cpuHint: '1-2 CPU for staging canaries and small previews.',
    failureMode: 'Fail the job, clean partial artifacts, record bounded error metadata, and preserve credit/refund gates.',
    licenseReviewStatus: 'approved_for_staging_smoke',
    securityReviewStatus: 'approved_for_staging_smoke',
    productionApprovalStatus: 'staging_smoke_only',
    currentReadiness: 'code_enforced_proven_staging',
  },
  ffprobe: {
    toolId: 'ffprobe',
    displayName: 'FFprobe',
    productionPurpose: 'Read duration, codec, stream, frame-rate, and container metadata before media analysis or render.',
    workerBoundary: 'media-analysis-worker',
    requiredForMilestones: ['local_basic_render_smoke', 'staging_media_analysis_canary', 'staging_timeline_composition_canary', 'production_media_analysis_worker', 'production_render_worker'],
    optionalUntil: 'Not optional for real media validation.',
    installTarget: 'worker_image',
    runtimeCheck: { runtimeCheckCommand: 'ffprobe -version', safeCheckOnly: true },
    expectedVersionShape: 'First version line begins with ffprobe version.',
    inputContracts: ['Local worker temp file path only; no signed URL canonical input.'],
    outputContracts: ['Sanitized JSON metadata summary with bounded fields.'],
    timeoutMs: 30000,
    memoryHint: '128Mi for normal probes.',
    cpuHint: 'Light CPU, bounded by file duration and probe timeout.',
    failureMode: 'Block media analysis or render preflight when metadata cannot be trusted.',
    licenseReviewStatus: 'approved_for_staging_smoke',
    securityReviewStatus: 'approved_for_staging_smoke',
    productionApprovalStatus: 'staging_smoke_only',
    currentReadiness: 'code_enforced_proven_staging',
  },
  remotion: {
    toolId: 'remotion',
    displayName: 'Remotion',
    productionPurpose: 'Compose previews, final canvas layers, captions, panels, source video layers, and approved motion briefs.',
    workerBoundary: 'render-worker',
    requiredForMilestones: ['staging_render_infrastructure_canary', 'staging_real_video_upload_preview_canary', 'staging_timeline_composition_canary', 'production_render_worker'],
    optionalUntil: 'Not optional for Remotion preview/render workers.',
    installTarget: 'cloud_run_render_image',
    runtimeCheck: { importCheck: 'resolve remotion package', safeCheckOnly: true },
    expectedVersionShape: 'Package version from remotion/package.json.',
    inputContracts: ['Approved render props plus local/static asset references; never raw bytes, secrets, or signed URLs.'],
    outputContracts: ['Video artifact plus render status, checksum, frame, duration, and storage metadata.'],
    timeoutMs: 300000,
    memoryHint: 'Staging canary profile: 2Gi with NODE_OPTIONS=--max-old-space-size=1536.',
    cpuHint: 'Staging canary profile: 2 CPU, concurrency 1.',
    failureMode: 'Fail closed with bounded error summaries, clean partial artifacts, and record failed job transition.',
    licenseReviewStatus: 'approved_for_staging_smoke',
    securityReviewStatus: 'approved_for_staging_smoke',
    productionApprovalStatus: 'staging_smoke_only',
    currentReadiness: 'code_enforced_proven_staging',
  },
  sharp_libvips: {
    toolId: 'sharp_libvips',
    displayName: 'Sharp/libvips',
    productionPurpose: 'Prepare thumbnails, resize/crop images, watermark, and generate simple image assets.',
    workerBoundary: 'image-asset-worker',
    requiredForMilestones: [],
    optionalUntil: 'Image asset worker canary.',
    installTarget: 'node_worker_image',
    runtimeCheck: { importCheck: 'resolve sharp package', safeCheckOnly: true },
    expectedVersionShape: 'Package version from sharp/package.json.',
    inputContracts: ['Approved local image file or storage object staged into worker temp.'],
    outputContracts: ['Image artifact plus dimensions, checksum, MIME, and storage metadata.'],
    timeoutMs: 60000,
    memoryHint: 'Memory-bound; cap pixels and file size before production use.',
    cpuHint: '1 CPU for normal thumbnail/resize work.',
    failureMode: 'Fail the image work item, clean partial outputs, and use approved fallback/review.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'safe_check_available',
  },
  opencv: {
    toolId: 'opencv',
    displayName: 'OpenCV',
    productionPurpose: 'Run visual QA, safe-zone checks, blur/quality checks, and future frame analysis.',
    workerBoundary: 'media-analysis-worker',
    requiredForMilestones: [],
    optionalUntil: 'Media analysis worker canary.',
    installTarget: 'python_worker_image',
    runtimeCheck: { importCheck: 'python -c "import cv2"', safeCheckOnly: true },
    expectedVersionShape: 'cv2.__version__ or unknown.',
    inputContracts: ['Sampled frames or approved local video/image files.'],
    outputContracts: ['Structured QA findings with confidence and bounded summaries.'],
    timeoutMs: 120000,
    memoryHint: 'Cap resolution, sampled frame count, and model-free analysis scope.',
    cpuHint: 'CPU-heavy; use sampled frames by default.',
    failureMode: 'Return QA warning/blocker; do not silently alter the approved plan.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'safe_check_available',
  },
  audioflux: {
    toolId: 'audioflux',
    displayName: 'AudioFlux',
    productionPurpose: 'Analyze onset, rhythm, energy, and beat/drop features for SoundSync timing maps.',
    workerBoundary: 'audio-soundsync-worker',
    requiredForMilestones: [],
    optionalUntil: 'SoundSync analysis canary.',
    installTarget: 'python_worker_image',
    runtimeCheck: { importCheck: 'python -c "import audioflux"', safeCheckOnly: true },
    expectedVersionShape: 'audioflux.__version__ or unknown.',
    inputContracts: ['Approved local audio track or audio extracted from approved media.'],
    outputContracts: ['Timing feature map with bounded confidence fields.'],
    timeoutMs: 120000,
    memoryHint: 'Cap duration, sample rate, and analysis windows.',
    cpuHint: 'CPU-bound audio analysis.',
    failureMode: 'Fall back to simpler timing or user review; do not block unrelated work.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'safe_check_available',
  },
  signalsmith_stretch: {
    toolId: 'signalsmith_stretch',
    displayName: 'Signalsmith Stretch',
    productionPurpose: 'Apply approved music time-stretching or pitch adjustment for voice-safe timing fits.',
    workerBoundary: 'audio-soundsync-worker',
    requiredForMilestones: [],
    optionalUntil: 'SoundSync processing canary.',
    installTarget: 'future_worker_image',
    runtimeCheck: { runtimeCheckCommand: 'planned Signalsmith binary/package check', safeCheckOnly: true },
    expectedVersionShape: 'Configured binary/package version when selected.',
    inputContracts: ['Approved audio stem plus bounded stretch/pitch parameters.'],
    outputContracts: ['Processed audio stem plus QA metadata.'],
    timeoutMs: 120000,
    memoryHint: 'Cap source duration and transformation amount.',
    cpuHint: 'CPU-bound audio processing.',
    failureMode: 'Fail the audio work item and use approved fallback/review.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'planned_stub',
  },
  whisper: {
    toolId: 'whisper',
    displayName: 'Whisper / faster-whisper / whisper.cpp',
    productionPurpose: 'Transcribe approved source audio with timestamps for source understanding and captions.',
    workerBoundary: 'media-analysis-worker',
    requiredForMilestones: [],
    optionalUntil: 'Media analysis worker canary selects a transcription implementation.',
    installTarget: 'future_worker_image',
    runtimeCheck: { runtimeCheckCommand: 'planned transcription runtime check', safeCheckOnly: true },
    expectedVersionShape: 'Selected implementation version when installed.',
    inputContracts: ['Approved local audio/video media staged in worker temp.'],
    outputContracts: ['Timestamped transcript segments with confidence and bounded text.'],
    timeoutMs: 300000,
    memoryHint: 'Depends on selected model; cap model size and media duration.',
    cpuHint: 'CPU/GPU profile depends on selected implementation.',
    failureMode: 'Mark transcript unavailable and request user/manual review or fallback captions.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'planned_stub',
  },
  pyscenedetect: {
    toolId: 'pyscenedetect',
    displayName: 'PySceneDetect',
    productionPurpose: 'Detect scene/shot boundaries for source analysis, trim planning, and QA.',
    workerBoundary: 'media-analysis-worker',
    requiredForMilestones: [],
    optionalUntil: 'Media analysis worker canary.',
    installTarget: 'python_worker_image',
    runtimeCheck: { importCheck: 'python -c "import scenedetect"', safeCheckOnly: true },
    expectedVersionShape: 'scenedetect package version when installed.',
    inputContracts: ['Approved local video file or sampled frame sequence.'],
    outputContracts: ['Scene boundary timecodes and confidence metadata.'],
    timeoutMs: 120000,
    memoryHint: 'Cap duration, resolution, and sampling mode.',
    cpuHint: 'CPU-bound video analysis.',
    failureMode: 'Fall back to source order/manual review; do not invent cuts.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'planned_stub',
  },
  playwright: {
    toolId: 'playwright',
    displayName: 'Playwright',
    productionPurpose: 'Capture approved web/app/dashboard screenshots and run browser visual QA.',
    workerBoundary: 'browser-capture-worker',
    requiredForMilestones: [],
    optionalUntil: 'Browser capture worker canary.',
    installTarget: 'node_worker_image',
    runtimeCheck: { importCheck: 'resolve playwright package', safeCheckOnly: true },
    expectedVersionShape: 'Package version from playwright/package.json.',
    inputContracts: ['Approved URL or local app target plus capture allowlist policy.'],
    outputContracts: ['Screenshot/video artifact and QA report.'],
    timeoutMs: 120000,
    memoryHint: 'Browser memory bounded by viewport and capture duration.',
    cpuHint: '1-2 CPU for isolated capture workers.',
    failureMode: 'Fail capture step and use approved fallback card or user review.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'safe_check_available',
  },
  vapoursynth: {
    toolId: 'vapoursynth',
    displayName: 'VapourSynth',
    productionPurpose: 'Run advanced frame/video filtering, denoise/deband/interpolation experiments, and high-end postprocessing.',
    workerBoundary: 'advanced-frame-worker',
    requiredForMilestones: [],
    optionalUntil: 'Advanced frame worker canary.',
    installTarget: 'future_worker_image',
    runtimeCheck: { importCheck: 'python -c "import vapoursynth"', safeCheckOnly: true },
    expectedVersionShape: 'vapoursynth.__version__ or unknown.',
    inputContracts: ['Approved local video plus reviewed filter graph.'],
    outputContracts: ['Processed clip plus QA metadata.'],
    timeoutMs: 300000,
    memoryHint: 'CPU/RAM-heavy; cap duration, resolution, and plugins.',
    cpuHint: 'CPU-heavy; isolated worker only.',
    failureMode: 'Fail advanced processing and use simpler FFmpeg/Remotion fallback if approved.',
    licenseReviewStatus: 'pending_review',
    securityReviewStatus: 'pending_review',
    productionApprovalStatus: 'planning_only',
    currentReadiness: 'safe_check_available',
  },
} as const satisfies Record<EditingToolId, EditingToolContract>

export function getEditingToolContract(toolId: EditingToolId): EditingToolContract {
  return EDITING_TOOL_REGISTRY[toolId]
}

export function listEditingToolContracts(): EditingToolContract[] {
  return EDITING_TOOL_IDS.map((toolId) => EDITING_TOOL_REGISTRY[toolId])
}

export function getCurrentMilestoneRequiredToolIds(): EditingToolId[] {
  return [...CURRENT_MILESTONE_REQUIRED_TOOL_IDS]
}
