import type {
  MotionStudioResearchChronologyEventV1,
  MotionStudioResearchClaimV2,
  MotionStudioResearchEvidenceFragmentV2,
  MotionStudioResearchReviewEventV1,
  MotionStudioResearchSourceVersionV2,
  MotionStudioResearchWorkspaceDto,
  MotionStudioTechniqueBlueprintV1,
  MotionStudioVisualAssetCandidateV1,
  MotionStudioVisualNeedV2,
} from '../../../types/motion-studio'

export const researchFixtureIds = Object.freeze({
  workspaceId: '10000000-0000-4000-8000-00000000a001',
  projectId: '20000000-0000-4000-8000-00000000a001',
  editSessionId: 'edit-a-ms011a',
  productionId: '31000000-0000-4000-8000-00000000a011',
  sourceId: '41000000-0000-4000-8000-00000000a011',
  sourceVersionId: '42000000-0000-4000-8000-00000000a011',
  evidenceId: '43000000-0000-4000-8000-00000000a011',
  claimId: '44000000-0000-4000-8000-00000000a011',
  chronologyId: '45000000-0000-4000-8000-00000000a011',
  visualNeedId: '46000000-0000-4000-8000-00000000a011',
  candidateId: '47000000-0000-4000-8000-00000000a011',
  selectedAssetVersionId: '48000000-0000-4000-8000-00000000a011',
  reviewEventId: '49000000-0000-4000-8000-00000000a011',
  blueprintId: '4a000000-0000-4000-8000-00000000a011',
  blueprintStepId: '4b000000-0000-4000-8000-00000000a011',
  claimArtifactId: '51000000-0000-4000-8000-00000000a011',
  claimArtifactVersionId: '52000000-0000-4000-8000-00000000a011',
  coverageArtifactId: '53000000-0000-4000-8000-00000000a011',
  coverageArtifactVersionId: '54000000-0000-4000-8000-00000000a011',
  referenceArtifactId: '55000000-0000-4000-8000-00000000a011',
  referenceArtifactVersionId: '56000000-0000-4000-8000-00000000a011',
  reviewerId: '00000000-0000-4000-8000-00000000a001',
})

const scope = {
  workspaceId: researchFixtureIds.workspaceId,
  projectId: researchFixtureIds.projectId,
  editSessionId: researchFixtureIds.editSessionId,
} as const
const createdAt = '2026-07-16T12:00:00.000Z'
const digestA = 'a'.repeat(64)
const digestB = 'b'.repeat(64)
const digestC = 'c'.repeat(64)

export const validResearchSourceVersionV2: MotionStudioResearchSourceVersionV2 = {
  ...scope,
  schemaVersion: 'motion-studio.research-source-version.v2',
  moduleId: 'storytelling',
  moduleCatalogVersion: 'motion-studio-module-catalog-v1',
  stageProfileId: 'motion-studio-storytelling-stage-profile-v1',
  productionId: researchFixtureIds.productionId,
  sourceId: researchFixtureIds.sourceId,
  sourceVersionId: researchFixtureIds.sourceVersionId,
  sourceVersionNumber: 1,
  sourceKind: 'official_record',
  retrievalMethod: 'fixture',
  locator: { locatorType: 'fixture', fixtureId: 'ms011a.official-record.v1', fixtureDigest: digestA },
  title: 'Reviewed official chronology record',
  creatorOrPublisher: 'Fixture public archive',
  publishedAt: '2020-01-01T00:00:00.000Z',
  accessedAt: createdAt,
  language: 'en',
  contentDigest: digestA,
  trustStatus: 'authoritative',
  trustRationale: 'The deterministic fixture represents an official primary record.',
  rights: {
    status: 'public_domain',
    reviewStatus: 'reviewed',
    evidenceIds: ['rights-ms011a-public-domain'],
    permittedUses: ['Documentary research and visual reference'],
    restrictions: [],
    territories: ['worldwide'],
  },
  authenticityClass: 'official_document',
  relationship: 'official',
  promptInjection: { status: 'not_detected', findings: [] },
  privacyClass: 'standard',
  retentionClass: 'project_lifetime',
  sourceContentExecutable: false,
  canApproveWork: false,
  canAuthorizeSpend: false,
  createdAt,
  immutable: true,
}

export const validResearchEvidenceFragmentV2: MotionStudioResearchEvidenceFragmentV2 = {
  ...scope,
  schemaVersion: 'motion-studio.research-evidence-fragment.v2',
  productionId: researchFixtureIds.productionId,
  evidenceFragmentId: researchFixtureIds.evidenceId,
  sourceId: researchFixtureIds.sourceId,
  sourceVersionId: researchFixtureIds.sourceVersionId,
  locator: { locatorType: 'page', pageNumber: 4 },
  normalizedParaphrase: 'The official record places the first documented event on 12 May 2020.',
  copyrightSafeExcerpt: 'The first recorded event occurred on 12 May 2020.',
  contentDigest: digestB,
  relationship: 'supports',
  extraction: { method: 'fixture', confidence: 'high' },
  reviewStatus: 'reviewed',
  qualityWarnings: [],
  sourceContentExecutable: false,
  createdAt,
  immutable: true,
}

export const validResearchClaimV2: MotionStudioResearchClaimV2 = {
  ...scope,
  schemaVersion: 'motion-studio.research-claim.v2',
  productionId: researchFixtureIds.productionId,
  claimId: researchFixtureIds.claimId,
  claimLedgerArtifactVersion: {
    artifactId: researchFixtureIds.claimArtifactId,
    versionId: researchFixtureIds.claimArtifactVersionId,
    versionNumber: 1,
    contentDigest: digestC,
  },
  claimText: 'The first documented event occurred on 12 May 2020.',
  classification: 'verified_fact',
  evidenceLinks: [{ evidenceFragmentId: researchFixtureIds.evidenceId, relationship: 'supports', weight: 'primary' }],
  namedAttributionRequired: false,
  confidence: 'high',
  confidenceRationale: 'The exact date is supported by the reviewed official record.',
  materiality: 'material',
  alternativeInterpretations: [],
  realPersonRisk: 'none',
  legalReviewRequired: false,
  disclosureRequired: false,
  safeWording: 'The official record dates the first documented event to 12 May 2020.',
  downstreamReferences: {
    scriptArtifactVersionIds: [],
    narrationSegmentIds: [],
    sceneIds: [],
    shotIds: [],
    visualNeedIds: [researchFixtureIds.visualNeedId],
    finalUseIds: [],
  },
  status: 'approved',
  reviewedBy: researchFixtureIds.reviewerId,
  reviewedAt: createdAt,
  approvedArtifactVersionId: researchFixtureIds.claimArtifactVersionId,
  approvedArtifactDigest: digestC,
  createdAt,
  immutable: true,
}

export const validResearchChronologyEventV1: MotionStudioResearchChronologyEventV1 = {
  ...scope,
  schemaVersion: 'motion-studio.research-chronology-event.v1',
  productionId: researchFixtureIds.productionId,
  chronologyEventId: researchFixtureIds.chronologyId,
  title: 'First documented event',
  description: 'The reviewed primary record establishes the first documented date.',
  timePrecision: 'day',
  startAt: '2020-05-12T00:00:00.000Z',
  participantIds: [],
  placeIds: [],
  evidenceFragmentIds: [researchFixtureIds.evidenceId],
  uncertainty: [],
  contradictionStatus: 'none',
  reviewStatus: 'approved',
  createdAt,
  immutable: true,
}

export const validVisualNeedV2: MotionStudioVisualNeedV2 = {
  ...scope,
  schemaVersion: 'motion-studio.visual-need.v2',
  productionId: researchFixtureIds.productionId,
  visualNeedId: researchFixtureIds.visualNeedId,
  visualCoverageArtifactVersion: {
    artifactId: researchFixtureIds.coverageArtifactId,
    versionId: researchFixtureIds.coverageArtifactVersionId,
    versionNumber: 1,
    contentDigest: digestB,
  },
  narrativePurpose: 'Establish the exact documented date without presenting reconstruction as archive.',
  kind: 'evidence',
  narrationSegmentIds: [],
  sceneIds: [],
  shotIds: [],
  linkedClaimIds: [researchFixtureIds.claimId],
  evidenceFragmentIds: [researchFixtureIds.evidenceId],
  requiredAuthenticity: 'official_document',
  requiredAccuracy: 'source_exact',
  acceptableTreatments: ['deterministic_map_chart_document', 'authentic_archive'],
  prohibitedTreatments: ['generated_motion', 'labeled_ai_reconstruction'],
  disclosureRules: ['Label the document source in the final factual treatment.'],
  candidateIds: [researchFixtureIds.candidateId],
  selectedAssetVersionIds: [researchFixtureIds.selectedAssetVersionId],
  recommendation: {
    route: 'existing_asset',
    editability: 'high',
    costClass: 'no_incremental_provider_cost',
    risk: 'low',
    rationale: 'Use the registered exact document asset and deterministic labels.',
  },
  status: 'approved',
  createdAt,
  immutable: true,
}

export const validVisualAssetCandidateV1: MotionStudioVisualAssetCandidateV1 = {
  ...scope,
  schemaVersion: 'motion-studio.visual-asset-candidate.v1',
  productionId: researchFixtureIds.productionId,
  candidateId: researchFixtureIds.candidateId,
  visualNeedId: researchFixtureIds.visualNeedId,
  sourceId: researchFixtureIds.sourceId,
  sourceVersionId: researchFixtureIds.sourceVersionId,
  candidateType: 'authentic_archive',
  preview: { label: 'Official record page 4', mimeType: 'image/png', pixelWidth: 1280, pixelHeight: 720 },
  authenticityClass: 'official_document',
  contentMatch: 'high',
  technicalSuitability: 'suitable',
  rights: validResearchSourceVersionV2.rights,
  privacyRisk: 'none',
  likenessRisk: 'none',
  linkedClaimIds: [researchFixtureIds.claimId],
  proposedUse: 'Crop the exact date area and add deterministic source labeling.',
  expectedIncrementalInternalCostMicros: 0,
  currency: 'USD',
  selectionStatus: 'selected',
  selectedAssetVersionId: researchFixtureIds.selectedAssetVersionId,
  createdAt,
  immutable: true,
}

export const validResearchReviewEventV1: MotionStudioResearchReviewEventV1 = {
  ...scope,
  schemaVersion: 'motion-studio.research-review-event.v1',
  productionId: researchFixtureIds.productionId,
  reviewEventId: researchFixtureIds.reviewEventId,
  reviewKind: 'visual_candidate',
  subjectType: 'visual_candidate',
  subjectId: researchFixtureIds.candidateId,
  decision: 'approved',
  rationale: 'Rights, authenticity, content match, and technical suitability are independently satisfied.',
  reviewerId: researchFixtureIds.reviewerId,
  createdAt,
  immutable: true,
}

export const validTechniqueBlueprintV1: MotionStudioTechniqueBlueprintV1 = {
  ...scope,
  schemaVersion: 'motion_studio.reference.technique-blueprint.v1',
  productionId: researchFixtureIds.productionId,
  techniqueBlueprintId: researchFixtureIds.blueprintId,
  referenceContractArtifactVersion: {
    artifactId: researchFixtureIds.referenceArtifactId,
    versionId: researchFixtureIds.referenceArtifactVersionId,
    versionNumber: 1,
    contentDigest: digestA,
  },
  sourceVersionId: researchFixtureIds.sourceVersionId,
  title: 'Reference-locked documentary motion technique',
  timestampedSteps: [{
    stepId: researchFixtureIds.blueprintStepId,
    startMilliseconds: 0,
    endMilliseconds: 4_000,
    summary: 'Establish a visual system before selecting shot-specific actions.',
    evidenceFragmentIds: [researchFixtureIds.evidenceId],
  }],
  toolsAndModelsMentioned: ['Image generation', 'Video generation', 'Remotion'],
  promptPatternSummaries: ['Keep the approved visual system stable while changing only the shot action.'],
  motionPrinciples: ['Prefer one clear movement objective per generated clip.'],
  stylePrinciples: ['Separate reusable visual language from story-specific composition.'],
  decisionRules: ['Use deterministic composition for exact text, dates, maps, and charts.'],
  failureCases: ['Fine text becomes unstable inside raw generated video.'],
  manualCorrections: ['Composite exact labels after generative motion.'],
  reusableTechniques: ['Approve a keyframe before high-cost animation.'],
  claimsRequiringVerification: [],
  sourceInstructionsExecutable: false,
  toolExecutionAllowed: false,
  spendingAuthorityAllowed: false,
  copiedPublisherIdentityAllowed: false,
  copiedExactLayoutAllowed: false,
  createdAt,
  immutable: true,
}

export const validResearchWorkspaceDto: MotionStudioResearchWorkspaceDto = {
  productionId: researchFixtureIds.productionId,
  moduleId: 'storytelling',
  moduleCatalogVersion: 'motion-studio-module-catalog-v1',
  stageProfileId: 'motion-studio-storytelling-stage-profile-v1',
  stage: 'research',
  state: 'approved',
  scope: {
    externalRetrievalAllowed: false,
    fixtureOnly: true,
    maximumAuthorizedInternalCostMicros: 0,
  },
  sources: [{
    sourceId: researchFixtureIds.sourceId,
    sourceVersionId: researchFixtureIds.sourceVersionId,
    title: validResearchSourceVersionV2.title,
    sourceKind: validResearchSourceVersionV2.sourceKind,
    displayOrigin: 'Fixture public archive',
    trustStatus: validResearchSourceVersionV2.trustStatus,
    rightsStatus: validResearchSourceVersionV2.rights.status,
    authenticityClass: validResearchSourceVersionV2.authenticityClass,
    promptInjectionStatus: validResearchSourceVersionV2.promptInjection.status,
    reviewStatus: validResearchSourceVersionV2.rights.reviewStatus,
  }],
  evidence: [{
    evidenceFragmentId: researchFixtureIds.evidenceId,
    sourceVersionId: researchFixtureIds.sourceVersionId,
    locatorLabel: 'Page 4',
    normalizedParaphrase: validResearchEvidenceFragmentV2.normalizedParaphrase,
    relationship: 'supports',
    reviewStatus: 'reviewed',
    warnings: [],
  }],
  claims: [{
    claimId: researchFixtureIds.claimId,
    claimText: validResearchClaimV2.claimText,
    classification: 'verified_fact',
    confidence: 'high',
    materiality: 'material',
    status: 'approved',
    supportCount: 1,
    contradictionCount: 0,
    disclosureRequired: false,
  }],
  chronology: [{
    chronologyEventId: researchFixtureIds.chronologyId,
    title: validResearchChronologyEventV1.title,
    timeLabel: '12 May 2020',
    contradictionStatus: 'none',
    reviewStatus: 'approved',
  }],
  visualNeeds: [{
    visualNeedId: researchFixtureIds.visualNeedId,
    narrativePurpose: validVisualNeedV2.narrativePurpose,
    kind: 'evidence',
    route: 'existing_asset',
    candidateCount: 1,
    selectedAssetCount: 1,
    status: 'approved',
  }],
  candidates: [{
    candidateId: researchFixtureIds.candidateId,
    visualNeedId: researchFixtureIds.visualNeedId,
    label: validVisualAssetCandidateV1.preview.label,
    candidateType: 'authentic_archive',
    authenticityClass: 'official_document',
    rightsStatus: 'public_domain',
    technicalSuitability: 'suitable',
    selectionStatus: 'selected',
  }],
  techniqueBlueprints: [{
    techniqueBlueprintId: researchFixtureIds.blueprintId,
    title: validTechniqueBlueprintV1.title,
    stepCount: 1,
    failureCaseCount: 1,
    sourceInstructionsExecutable: false,
  }],
  reviewQueue: [],
  summary: {
    sourceCount: 1,
    evidenceCount: 1,
    claimCount: 1,
    approvedClaimCount: 1,
    unresolvedContradictionCount: 0,
    visualNeedCount: 1,
    missingVisualCoverageCount: 0,
    rightsBlockedCandidateCount: 0,
  },
  externalEvidence: {
    state: 'not_requested',
    requestCount: 0,
    capturedRecordCount: 0,
    binaryCaptureCount: 0,
    externalSourceCount: 0,
    openQuestionCount: 0,
    openQuestions: [],
    reviewOnlyCandidateCount: 0,
    finalAssetRegistrationAllowed: false,
    timelineMutationAllowed: false,
    updatedAt: createdAt,
  },
  externalRetrievalPerformed: false,
  providerCallMade: false,
  providerCostMicros: 0,
  customerPricingIncluded: false,
  customerCreditsIncluded: false,
  localFixtureOnly: true,
  updatedAt: createdAt,
}

export const validResearchContracts = Object.freeze({
  sourceVersion: validResearchSourceVersionV2,
  evidenceFragment: validResearchEvidenceFragmentV2,
  claim: validResearchClaimV2,
  chronologyEvent: validResearchChronologyEventV1,
  visualNeed: validVisualNeedV2,
  visualCandidate: validVisualAssetCandidateV1,
  reviewEvent: validResearchReviewEventV1,
  techniqueBlueprint: validTechniqueBlueprintV1,
  workspace: validResearchWorkspaceDto,
})
