import type { MotionStudioStoryWorkspaceDto } from '../../../types/motion-studio'

const digestA = 'a'.repeat(64)
const digestB = 'b'.repeat(64)
const digestC = 'c'.repeat(64)
const digestD = 'd'.repeat(64)
const digestE = 'e'.repeat(64)

const motionStyleReview: MotionStudioStoryWorkspaceDto['motionStyleReview'] = {
  schemaVersion: 'motion-studio.storytelling-style-review.v1',
  catalogVersion: '1.0.0',
  catalogDigest: digestE,
  state: 'comparison_only',
  directions: [
    {
      styleProfile: {
        styleProfileId: 'storytelling_style.editorial_collage',
        styleProfileVersion: '1.0.0',
        styleProfileDigest: digestA,
      },
      displayName: 'Editorial Collage',
      shortDescription: 'A modern explanatory collage built from archival cutouts, restrained print texture, native maps, data, and purposeful annotations.',
      bestFor: ['data-led explainers', 'cause-and-effect stories', 'maps and comparisons'],
      constructionLabel: 'Directed hybrid',
      relativeCostTendency: 'moderate',
      editability: 'high',
    },
    {
      styleProfile: {
        styleProfileId: 'storytelling_style.cinematic_realist_documentary',
        styleProfileVersion: '1.0.0',
        styleProfileDigest: digestB,
      },
      displayName: 'Cinematic Realist Documentary',
      shortDescription: 'Evidence-led footage, photographic depth, restrained cinematic reconstruction, and explicit archive-versus-reconstruction disclosure.',
      bestFor: ['history', 'investigations', 'biographies'],
      constructionLabel: 'Directed hybrid',
      relativeCostTendency: 'higher',
      editability: 'medium',
    },
    {
      styleProfile: {
        styleProfileId: 'storytelling_style.paper_diorama_documentary',
        styleProfileVersion: '1.0.0',
        styleProfileDigest: digestC,
      },
      displayName: 'Paper Diorama Documentary',
      shortDescription: 'A tactile cinematic paper world using measured miniature depth, layered evidence, warm motivated light, and exact editable typography.',
      bestFor: ['geopolitics', 'money and power', 'historical systems'],
      constructionLabel: 'Directed hybrid',
      relativeCostTendency: 'higher',
      editability: 'high',
    },
    {
      styleProfile: {
        styleProfileId: 'storytelling_style.technical_blueprint',
        styleProfileVersion: '1.0.0',
        styleProfileDigest: digestD,
      },
      displayName: 'Technical Blueprint',
      shortDescription: 'A precise native-graphics language for processes, routes, systems, measurements, diagrams, and exact explanatory data.',
      bestFor: ['technical systems', 'operations', 'routes'],
      constructionLabel: 'Native graphics',
      relativeCostTendency: 'lower',
      editability: 'high',
    },
  ],
  decisionAuthority: 'chat_then_plan_review',
  notice: 'Compare directions here, then discuss the choice in Chat. A direction is not selected, approved, generated, or charged from this view.',
  readOnly: true,
  runtimeExecutionAuthorized: false,
}

const motionStyleDecision: MotionStudioStoryWorkspaceDto['motionStyleDecision'] = {
  schemaVersion: 'motion-studio.storytelling-style-decision.v1',
  state: 'comparison_only',
  statusLabel: 'Comparison only',
  title: 'Compare how this story could move',
  summary: motionStyleReview.notice,
  nextAction: {
    kind: 'discuss_in_chat',
    label: 'Discuss a direction in Chat',
  },
  planReviewRequired: false,
  approvedLocked: false,
  approvedDecisionPreserved: false,
  calibrationState: 'not_planned',
  calibrationScenarioCount: 0,
  decisionAuthority: 'existing_plan_review',
  readOnly: true,
  runtimeExecutionAuthorized: false,
}

const styleCalibrationReview: MotionStudioStoryWorkspaceDto['styleCalibrationReview'] = {
  schemaVersion: 'motion-studio.storytelling-style-calibration-review.v1',
  state: 'not_ready',
  statusLabel: 'Not ready',
  title: 'Choose a motion direction before calibration',
  summary: 'Compare the motion directions above, then discuss the best fit in Chat.',
  scenarios: [],
  completedScenarioCount: 0,
  acceptedScenarioCount: 0,
  needsAttentionCount: 0,
  nextAction: {
    kind: 'discuss_in_chat',
    label: 'Discuss a direction in Chat',
  },
  decisionAuthority: 'existing_chat_and_plan_review',
  privateReviewOnly: true,
  automaticSelectionAllowed: false,
  approvedPlanMutationAllowed: false,
  readOnly: true,
  runtimeExecutionAuthorized: false,
  notice: 'This is a private, read-only comparison. It never starts media work, changes an approved plan, selects a route automatically, or spends customer credits.',
}

export const validNotReadyStoryContinuityReviewDto:
MotionStudioStoryWorkspaceDto['storyContinuityReview'] = {
  schemaVersion: 'motion-studio.storytelling-story-continuity-review.v1',
  state: 'not_ready',
  statusLabel: 'Story flow not ready',
  title: 'Finish the story and timed script first',
  summary: 'Story continuity becomes available after the exact story, timed script, and motion direction are ready.',
  throughLineAppearanceCount: 0,
  revealBeatCount: 0,
  transitionCount: 0,
  rhythmBeatCount: 0,
  unresolvedUncertaintyCount: 0,
  nextAction: { kind: 'continue_in_chat', label: 'Continue shaping the story in Chat' },
  planReviewIsSoleApprovalAuthority: true,
  approvedLocked: false,
  priorApprovedVersionPreserved: true,
  approvedSnapshotMutationAllowed: false,
  readOnly: true,
  runtimeExecutionAuthorized: false,
  localCandidateOnly: true,
  notice: 'This read-only story-flow status cannot approve a plan, generate media, use credits, render, export, or deliver.',
}

export const validReadyStoryContinuityReviewDto:
MotionStudioStoryWorkspaceDto['storyContinuityReview'] = {
  schemaVersion: 'motion-studio.storytelling-story-continuity-review.v1',
  state: 'ready_for_plan_review',
  statusLabel: 'Ready for Plan Review',
  title: 'Question to resolution is prepared',
  summary: 'The opening, payoff, recurring story thread, and scene transitions are bound to the current story and timed script.',
  arcMode: 'question_resolution',
  arcLabel: 'Question to resolution',
  throughLineMode: 'recurring_motif',
  throughLineLabel: 'Paper route marker',
  throughLineAppearanceCount: 3,
  revealBeatCount: 1,
  transitionCount: 2,
  rhythmBeatCount: 2,
  unresolvedUncertaintyCount: 0,
  nextAction: { kind: 'review_plan', label: 'Review with the current plan' },
  planReviewIsSoleApprovalAuthority: true,
  approvedLocked: false,
  priorApprovedVersionPreserved: true,
  approvedSnapshotMutationAllowed: false,
  readOnly: true,
  runtimeExecutionAuthorized: false,
  localCandidateOnly: true,
  notice: 'This is draft Plan Review input. Nothing is generated, charged, rendered, exported, or delivered from this view.',
}

export const validStoryWorkspaceDto: MotionStudioStoryWorkspaceDto = {
  productionId: '81000000-0000-4000-8000-000000000001',
  projectId: 'project-story-workspace-1',
  editSessionId: 'edit-story-workspace-1',
  state: 'script_ready',
  storyBible: {
    artifactId: '82000000-0000-4000-8000-000000000001',
    currentVersion: {
      artifactId: '82000000-0000-4000-8000-000000000001',
      versionId: '83000000-0000-4000-8000-000000000001',
      versionNumber: 2,
      contentDigest: digestA,
    },
    versionState: 'in_review',
    currentApprovedVersion: {
      artifactId: '82000000-0000-4000-8000-000000000001',
      versionId: '83000000-0000-4000-8000-000000000002',
      versionNumber: 1,
      contentDigest: digestB,
    },
    premise: 'A source-led chronology reveals how one disputed decision changed the outcome.',
    narrativeAngle: 'Evidence first, then consequence',
    narratorPerspective: 'Restrained third-person documentary narrator',
    chapters: ['The setup', 'The decision', 'The consequence'],
    people: ['Lead investigator'],
    locations: ['Operations room', 'Archive'],
    events: ['The evidence is discovered', 'The decision is challenged'],
    emotionalArc: ['curiosity', 'tension', 'clarity'],
    approvedDecisionCount: 2,
  },
  preparedScript: {
    artifactId: '84000000-0000-4000-8000-000000000001',
    currentVersion: {
      artifactId: '84000000-0000-4000-8000-000000000001',
      versionId: '85000000-0000-4000-8000-000000000001',
      versionNumber: 1,
      contentDigest: digestA,
    },
    versionState: 'in_review',
    title: 'The decision in the archive',
    language: 'English',
    timing: {
      frameRate: 30,
      width: 1920,
      height: 1080,
      aspectRatio: '16:9',
      durationFrames: 900,
      timingAuthorityDigest: digestB,
    },
    chapters: [{
      order: 0,
      title: 'The setup',
      sceneCount: 1,
      narrationSegments: [{
        order: 0,
        startFrame: 0,
        endFrame: 450,
        text: 'The archive looked ordinary until one record changed the chronology.',
        meaning: 'Establish the discovery that motivates the investigation.',
        visualCue: 'Begin on the archive exterior, then reveal the reviewed record.',
        claimCount: 1,
        sourceReferenceCount: 1,
      }],
    }, {
      order: 1,
      title: 'The consequence',
      sceneCount: 1,
      narrationSegments: [{
        order: 1,
        startFrame: 450,
        endFrame: 900,
        text: 'That single discrepancy forced the team to reconstruct the decision.',
        meaning: 'Connect the evidence to the story consequence.',
        visualCue: 'Move from the document into a restrained timeline reconstruction.',
        claimCount: 1,
        sourceReferenceCount: 2,
      }],
    }],
    narrationSegmentCount: 2,
    userLockedText: true,
  },
  motionStyleReview,
  motionStyleDecision,
  storyContinuityReview: validNotReadyStoryContinuityReviewDto,
  styleCalibrationReview,
  readOnly: true,
  notice: 'The timed script is ready for review. Request changes in Chat before approval.',
  localCandidateOnly: true,
}

export const validEmptyStoryWorkspaceDto: MotionStudioStoryWorkspaceDto = {
  productionId: validStoryWorkspaceDto.productionId,
  projectId: validStoryWorkspaceDto.projectId,
  editSessionId: validStoryWorkspaceDto.editSessionId,
  state: 'empty',
  motionStyleReview,
  motionStyleDecision,
  storyContinuityReview: validNotReadyStoryContinuityReviewDto,
  styleCalibrationReview,
  readOnly: true,
  notice: 'Shape the story in Chat before a Story Bible or timed script appears here.',
  localCandidateOnly: true,
}
