import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const ADMIN_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'admin.audit.write',
    domain: 'admin',
    method: 'POST',
    path: '/api/admin/audit',
    description: 'Future backend route for admin audit entries.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'writeAuditEvent',
    notes: ['Admin writes are backend-only.'],
  },
  {
    id: 'admin.user.moderate',
    domain: 'admin',
    method: 'POST',
    path: '/api/admin/users/:userId/moderation',
    description: 'Future backend route for account moderation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'moderateUser',
    notes: ['Disabled and not exposed to frontend UI.'],
  },
  {
    id: 'admin.projectAsset.delete',
    domain: 'admin',
    method: 'DELETE',
    path: '/api/admin/project-assets',
    description: 'Future backend route for privileged asset deletion.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'deleteProjectAssetAsAdmin',
    notes: ['Destructive admin routes remain disabled in RP-FIX-08.'],
  },
]
