import type { ApiRouteDefinition } from '../api-runtime-contracts'

const snapshotBoundaryNotes = [
  'Approved snapshot routes require auth and workspace/project access checks.',
  'Workers execute approved snapshots, not raw chat.',
  'These routes must not start generation, providers, rendering, tools, jobs, storage execution, or credit mutation.',
]

export const APPROVED_SNAPSHOT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'snapshots.readiness.check',
    domain: 'planning',
    method: 'POST',
    path: '/v1/edit-plans/:editPlanId/approved-snapshots/readiness',
    description: 'Check canonical approved-snapshot readiness gates and return blockers without creating a snapshot.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'checkSnapshotReadiness',
    notes: [
      ...snapshotBoundaryNotes,
      'Validates approved plan version, approved estimate, canonical approval record, active reservation, snapshot JSON safety, timing context, QA blockers, and scoped storage object references.',
      'Returns backend_required blockers when service-role runtime is unavailable.',
    ],
  },
  {
    id: 'snapshots.approved.create',
    domain: 'planning',
    method: 'POST',
    path: '/v1/edit-plans/:editPlanId/approved-snapshots',
    description: 'Create an immutable approved plan snapshot after approval, estimate approval, and active reservation gates pass.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createApprovedSnapshot',
    notes: [
      ...snapshotBoundaryNotes,
      'Requires Idempotency-Key.',
      'Writes approved_plan_snapshots only and leaves compatibility credit_approval_id null.',
      'Does not mutate credit ledger/reservations, create jobs, or call the legacy snapshot readiness RPC because that helper is schema-era conflicted.',
    ],
  },
  {
    id: 'snapshots.approved.get',
    domain: 'planning',
    method: 'GET',
    path: '/v1/approved-snapshots/:snapshotId',
    description: 'Read scoped approved snapshot metadata after project access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getApprovedSnapshot',
    notes: [
      ...snapshotBoundaryNotes,
      'Returns scoped metadata only and must not leak service-role-only data.',
      'workspaceId query is optional but recommended for fail-closed cross-workspace checks.',
    ],
  },
  {
    id: 'snapshots.approved.listForProject',
    domain: 'planning',
    method: 'GET',
    path: '/v1/projects/:projectId/approved-snapshots',
    description: 'List approved snapshot summaries for a project after workspace membership validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listApprovedSnapshotsForProject',
    notes: [
      ...snapshotBoundaryNotes,
      'Requires workspaceId query input.',
      'Returns metadata summaries, not executable worker payloads.',
    ],
  },
  {
    id: 'snapshots.approved.verifyIntegrity',
    domain: 'planning',
    method: 'POST',
    path: '/v1/approved-snapshots/:snapshotId/verify-integrity',
    description: 'Recompute the deterministic approved snapshot hash and compare it with the stored or expected hash.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'verifyApprovedSnapshotIntegrity',
    notes: [
      ...snapshotBoundaryNotes,
      'Integrity verification is read-only.',
      'It does not make a snapshot execution-ready or start workers.',
    ],
  },
  {
    id: 'snapshots.approved.blockers',
    domain: 'planning',
    method: 'POST',
    path: '/v1/edit-plans/:editPlanId/approved-snapshots/blockers',
    description: 'Return the current approved-snapshot blockers in a review-friendly shape.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getApprovedSnapshotBlockers',
    notes: [
      ...snapshotBoundaryNotes,
      'Designed for UI/debug visibility before users approve downstream execution.',
      'Does not write records.',
    ],
  },
]
