import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const AUDIO_SEPARATION_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'audio.separation.job.create',
    domain: 'audio',
    method: 'POST',
    path: '/api/audio/separation/jobs',
    description: 'Create a mock Demucs audio separation job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockAudioSeparationJobCreate',
    futureHandlerName: 'createAudioSeparationJob',
    notes: ['Demucs is used only for vocal/music/stem separation. Runtime execution requires an approved model manifest.'],
  },
  {
    id: 'audio.separation.job.get',
    domain: 'audio',
    method: 'GET',
    path: '/api/audio/separation/jobs/:jobId',
    description: 'Get a mock Demucs audio separation job status.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockAudioSeparationJobGet',
    notes: ['No live worker or provider is called.'],
  },
  {
    id: 'audio.separation.stems.list',
    domain: 'audio',
    method: 'GET',
    path: '/api/audio/separation/jobs/:jobId/stems',
    description: 'List mock private stem artifacts for a Demucs separation job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockAudioSeparationStemsList',
    notes: ['Returns private artifact references only; no public URLs.'],
  },
  {
    id: 'audio.separation.remux.create',
    domain: 'audio',
    method: 'POST',
    path: '/api/audio/separation/jobs/:jobId/remux',
    description: 'Request a future-safe remux from separated stems.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockAudioSeparationRemuxCreate',
    notes: ['Mock remux is blocked until a reviewed media pipeline supports it.'],
  },
]
