import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const AUTH_BOOTSTRAP_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'auth.bootstrap.status',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/bootstrap/status',
    description: 'Check frontend-safe Supabase auth bootstrap status.',
    securityLevel: 'public',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleAuthBootstrapStatus',
    futureHandlerName: 'getAuthBootstrapStatus',
    notes: ['Uses anon-client helpers only and returns not-configured safely.'],
  },
  {
    id: 'auth.bootstrap.currentUser',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/bootstrap/current-user',
    description: 'Run the current auth/profile/workspace bootstrap flow.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleAuthBootstrapCurrentUser',
    futureHandlerName: 'runAuthBootstrap',
    notes: ['Profile/workspace creation may return backend-required when RLS blocks frontend inserts.'],
  },
  {
    id: 'auth.currentUser',
    domain: 'auth',
    method: 'GET',
    path: '/v1/auth/current-user',
    description: 'Return the authenticated user summary from the server auth context.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getCurrentUserSummary',
    notes: ['Server route verifies the bearer token with the anon auth client and returns no service-role data.'],
  },
  {
    id: 'auth.profile.ensure',
    domain: 'auth',
    method: 'POST',
    path: '/v1/auth/profile/ensure',
    description: 'Ensure the signed-in user has a ReeditPro profile.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'ensureUserProfile',
    notes: ['Prompt 3 server route may create or update only safe fields on the canonical profiles table.'],
  },
  {
    id: 'auth.workspace.ensure',
    domain: 'auth',
    method: 'POST',
    path: '/v1/auth/workspace/ensure',
    description: 'Ensure default workspace and membership context.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'ensureDefaultWorkspace',
    notes: ['Prompt 3 server route may create only canonical workspaces and owner workspace_members rows.'],
  },
  {
    id: 'auth.workspace.current',
    domain: 'auth',
    method: 'GET',
    path: '/v1/auth/workspace/current',
    description: 'Return the current workspace membership selected by backend workspace lookup.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getCurrentWorkspace',
    notes: ['Reads only workspaces and workspace_members; does not create projects or execution records.'],
  },
  {
    id: 'workspaces.membership.check',
    domain: 'auth',
    method: 'POST',
    path: '/v1/workspaces/membership/check',
    description: 'Check authenticated user membership in one workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'checkWorkspaceMembership',
    notes: ['Uses workspace_members as the canonical workspace authorization link.'],
  },
  {
    id: 'auth.workspaces.list',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/workspaces',
    description: 'List workspaces visible to the signed-in user.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listUserWorkspaces',
    notes: ['Anon client can read only workspaces allowed by RLS.'],
  },
]
