import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const AUTH_BOOTSTRAP_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'auth.bootstrap.status',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/bootstrap/status',
    description: 'Check frontend-safe Supabase auth bootstrap status.',
    securityLevel: 'public',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleAuthBootstrapStatus',
    futureHandlerName: 'getAuthBootstrapStatus',
    notes: ['Uses anon-client helpers only and returns not-configured safely.'],
  },
  {
    id: 'auth.bootstrap.currentUser',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/bootstrap/current-user',
    description: 'Run the current auth/profile/workspace bootstrap flow.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleAuthBootstrapCurrentUser',
    futureHandlerName: 'runAuthBootstrap',
    notes: ['Profile/workspace creation may return backend-required when RLS blocks frontend inserts.'],
  },
  {
    id: 'auth.profile.ensure',
    domain: 'auth',
    method: 'POST',
    path: '/api/auth/profile/ensure',
    description: 'Ensure the signed-in user has a ReeditPro profile.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'ensureUserProfile',
    notes: ['Frontend can try RLS-limited writes; backend fallback may be required.'],
  },
  {
    id: 'auth.workspace.ensure',
    domain: 'auth',
    method: 'POST',
    path: '/api/auth/workspace/ensure',
    description: 'Ensure default workspace and membership context.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'ensureDefaultWorkspace',
    notes: ['Workspace bootstrap may require a backend route depending on deployed RLS.'],
  },
  {
    id: 'auth.workspaces.list',
    domain: 'auth',
    method: 'GET',
    path: '/api/auth/workspaces',
    description: 'List workspaces visible to the signed-in user.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listUserWorkspaces',
    notes: ['Anon client can read only workspaces allowed by RLS.'],
  },
]
