import type { ApiRouteDefinition, ApiRouteSecurityLevel, ApiRouteStatus } from '../api-runtime-contracts'

const COMPLIANCE_FORBIDDEN_SIDE_EFFECTS = [
  'No legal advice or legal approval',
  'No production approval or beta unlock',
  'No dependency mutation or audit fix',
  'No package installation beyond npm ci validation',
  'No tool package or provider SDK installation',
  'No Secret Manager access or provider secret reads',
  'No provider calls or webhook processing',
  'No tool, worker, render, export, media, storage, Stripe, credit, or job execution',
  'No remote Supabase migration or SQL execution',
]

function complianceRoute(input: {
  id: string
  method: ApiRouteDefinition['method']
  path: string
  description: string
  routeGroup: string
  inputSchema: string
  outputSchema: string
  futureHandlerName: string
  status?: ApiRouteStatus
  securityLevel?: ApiRouteSecurityLevel
  productionReadiness?: ApiRouteDefinition['productionReadiness']
  idempotencyRequired?: boolean
  projectRequired?: boolean
  auditEvent?: string
  notes?: string[]
}): ApiRouteDefinition {
  const productionReadiness = input.productionReadiness ?? 'backend_required'
  return {
    id: input.id,
    domain: 'compliance',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: input.securityLevel ?? 'workspace_member',
    runtimeMode: productionReadiness === 'implemented' ? 'backend_required' : 'backend_required',
    status: input.status ?? 'backend_required',
    requiresSupabase: productionReadiness !== 'implemented',
    requiresServiceRole: productionReadiness !== 'implemented',
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: input.futureHandlerName,
    routeGroup: input.routeGroup,
    authRequired: true,
    workspaceRequired: true,
    projectRequired: Boolean(input.projectRequired),
    idempotencyRequired: Boolean(input.idempotencyRequired),
    serviceRoleRequired: productionReadiness !== 'implemented',
    allowedCaller: 'authenticated backend API caller',
    inputSchema: input.inputSchema,
    outputSchema: input.outputSchema,
    tablesTouched: [
      'workspaces',
      'projects',
      'tool_license_compliance',
      'dependency_review_records',
      'package_review_records',
      'license_review_records',
      'security_review_records',
      'runtime_approval_records',
      'model_provenance_review_records',
      'compliance_audit_events',
      'audit_events',
    ],
    forbiddenSideEffects: COMPLIANCE_FORBIDDEN_SIDE_EFFECTS,
    auditEvent: input.auditEvent,
    failClosedBehavior: 'Return static summaries or backend_required/blocker results until human-reviewed compliance persistence and production approval workflow exist.',
    validationLevel: 'guarded',
    productionReadiness,
    notes: [
      'Prompt 16 compliance metadata only; not legal advice and not production approval.',
      ...(input.notes ?? []),
    ],
  }
}

export const COMPLIANCE_API_ROUTES: ApiRouteDefinition[] = [
  complianceRoute({
    id: 'compliance.readiness.check',
    method: 'POST',
    path: '/v1/compliance/readiness',
    description: 'Check compliance readiness and blockers without approving runtime use.',
    routeGroup: 'readiness',
    inputSchema: 'complianceReadinessSchema',
    outputSchema: 'ComplianceResult',
    futureHandlerName: 'checkComplianceReadiness',
    idempotencyRequired: true,
    auditEvent: 'compliance.readiness_checked',
  }),
  complianceRoute({
    id: 'compliance.subjects.list',
    method: 'GET',
    path: '/v1/compliance/subjects',
    description: 'List static compliance subjects from tool, provider, and dependency metadata.',
    routeGroup: 'subjects',
    inputSchema: 'complianceSubjectsListQuerySchema',
    outputSchema: 'ComplianceResult.subjects',
    futureHandlerName: 'listComplianceSubjects',
    productionReadiness: 'implemented',
    notes: ['Static inventory only; no compliance DB read occurs.'],
  }),
  complianceRoute({
    id: 'compliance.subject.get',
    method: 'GET',
    path: '/v1/compliance/subjects/:reviewSubjectType/:reviewSubjectKey',
    description: 'Read one static compliance subject summary.',
    routeGroup: 'subjects',
    inputSchema: 'complianceSubjectGetQuerySchema + path params',
    outputSchema: 'ComplianceResult.subject',
    futureHandlerName: 'getComplianceSubject',
    productionReadiness: 'implemented',
  }),
  complianceRoute({
    id: 'compliance.review.preview',
    method: 'POST',
    path: '/v1/compliance/review/preview',
    description: 'Preview a future compliance review record without writing it.',
    routeGroup: 'reviews',
    inputSchema: 'complianceReviewPreviewSchema',
    outputSchema: 'ComplianceResult.review',
    futureHandlerName: 'previewComplianceReview',
    idempotencyRequired: true,
    auditEvent: 'compliance.review_previewed',
  }),
  complianceRoute({
    id: 'compliance.review.createBoundary',
    method: 'POST',
    path: '/v1/compliance/review/create-boundary',
    description: 'Fail-closed boundary for future append-only compliance review record creation.',
    routeGroup: 'reviews',
    inputSchema: 'complianceReviewCreateBoundarySchema',
    outputSchema: 'ComplianceResult.review',
    futureHandlerName: 'createComplianceReviewBoundary',
    idempotencyRequired: true,
    auditEvent: 'compliance.review_create_boundary',
  }),
  complianceRoute({
    id: 'compliance.review.get',
    method: 'GET',
    path: '/v1/compliance/reviews/:complianceReviewId',
    description: 'Read compliance review summary boundary.',
    routeGroup: 'reviews',
    inputSchema: 'complianceReviewGetQuerySchema + complianceReviewId',
    outputSchema: 'ComplianceResult.review',
    futureHandlerName: 'getComplianceReview',
  }),
  complianceRoute({
    id: 'compliance.review.listForSubject',
    method: 'GET',
    path: '/v1/compliance/subjects/:reviewSubjectType/:reviewSubjectKey/reviews',
    description: 'List future compliance review history for a subject boundary.',
    routeGroup: 'reviews',
    inputSchema: 'complianceReviewListForSubjectQuerySchema + path params',
    outputSchema: 'ComplianceResult.review',
    futureHandlerName: 'listComplianceReviewsForSubject',
  }),
  complianceRoute({
    id: 'compliance.blockers.list',
    method: 'POST',
    path: '/v1/compliance/blockers',
    description: 'List compliance blockers for a subject or workspace scope.',
    routeGroup: 'blockers',
    inputSchema: 'complianceBlockersSchema',
    outputSchema: 'ComplianceResult.blockers',
    futureHandlerName: 'listComplianceBlockers',
    idempotencyRequired: true,
  }),
  complianceRoute({
    id: 'compliance.license.readiness',
    method: 'POST',
    path: '/v1/compliance/license/readiness',
    description: 'Check license review readiness without approving license use.',
    routeGroup: 'license',
    inputSchema: 'complianceLicenseReadinessSchema',
    outputSchema: 'ComplianceResult.license',
    futureHandlerName: 'checkLicenseReadiness',
    idempotencyRequired: true,
  }),
  complianceRoute({
    id: 'compliance.security.readiness',
    method: 'POST',
    path: '/v1/compliance/security/readiness',
    description: 'Check security review readiness without approving runtime use.',
    routeGroup: 'security',
    inputSchema: 'complianceSecurityReadinessSchema',
    outputSchema: 'ComplianceResult.security',
    futureHandlerName: 'checkSecurityReadiness',
    idempotencyRequired: true,
  }),
  complianceRoute({
    id: 'compliance.dependency.readiness',
    method: 'POST',
    path: '/v1/compliance/dependency/readiness',
    description: 'Summarize dependency review readiness without mutating dependencies.',
    routeGroup: 'dependency',
    inputSchema: 'complianceDependencyReadinessSchema',
    outputSchema: 'ComplianceResult.dependency',
    futureHandlerName: 'checkDependencyReadiness',
    idempotencyRequired: true,
  }),
  complianceRoute({
    id: 'compliance.runtimeApproval.readiness',
    method: 'POST',
    path: '/v1/compliance/runtime-approval/readiness',
    description: 'Check runtime approval readiness while keeping execution blocked.',
    routeGroup: 'runtime_approval',
    inputSchema: 'complianceRuntimeApprovalReadinessSchema',
    outputSchema: 'ComplianceResult.runtimeApproval',
    futureHandlerName: 'checkRuntimeApprovalReadiness',
    idempotencyRequired: true,
  }),
  complianceRoute({
    id: 'compliance.productionUnlock.blocked',
    method: 'POST',
    path: '/v1/compliance/production-unlock/blocked',
    description: 'Explicitly report production/beta/broad-media unlock as blocked.',
    routeGroup: 'production_unlock',
    inputSchema: 'complianceProductionUnlockBlockedSchema',
    outputSchema: 'ComplianceResult.productionUnlock',
    futureHandlerName: 'blockProductionUnlock',
    idempotencyRequired: true,
    productionReadiness: 'blocked',
  }),
  complianceRoute({
    id: 'compliance.auditSummary.get',
    method: 'GET',
    path: '/v1/compliance/audit-summary',
    description: 'Read compliance audit summary boundary without reading audit tables.',
    routeGroup: 'audit',
    inputSchema: 'complianceAuditSummaryQuerySchema',
    outputSchema: 'ComplianceResult.audit',
    futureHandlerName: 'getComplianceAuditSummary',
  }),
]
