import type { ApiRouteDefinition } from '../api-runtime-contracts'

const creditBoundaryNotes = [
  'Prompt 6 credit routes require auth, workspace/project access, idempotency for mutations, and a future reviewed transactional backend runtime.',
  'Canonical credit records are credit_estimates, credit_estimate_items, approval_records, approved_plan_snapshots, credit_reservations, credit_ledger_entries, and refund_records.',
  'These routes must not create jobs, call providers, render media, execute tools, run Stripe, mutate storage, or start planning/generation execution.',
]

function creditRoute(
  route: Omit<ApiRouteDefinition, 'domain' | 'runtimeMode' | 'status' | 'requiresSupabase' | 'requiresServiceRole' | 'requiresProviderSecret' | 'requiresStripeSecret' | 'notes'> & {
    notes?: string[]
  },
): ApiRouteDefinition {
  return {
    ...route,
    domain: 'credits',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    routeGroup: 'credits',
    authRequired: true,
    workspaceRequired: true,
    projectRequired: route.id !== 'credits.wallet.get',
    idempotencyRequired: route.method !== 'GET' && !route.id.endsWith('.check') && route.id !== 'credits.blockers',
    serviceRoleRequired: true,
    allowedCaller: 'authenticated frontend or future backend runtime through server routes only',
    failClosedBehavior: 'Returns backend_required blockers and performs no credit mutation until a reviewed transactional runtime exists.',
    validationLevel: 'guarded',
    productionReadiness: 'backend_required',
    forbiddenSideEffects: ['Stripe', 'job creation', 'provider calls', 'rendering', 'tool execution', 'storage execution', 'credit mutation'],
    notes: [...creditBoundaryNotes, ...(route.notes ?? [])],
  }
}

export const CREDIT_API_ROUTES: ApiRouteDefinition[] = [
  creditRoute({
    id: 'credits.wallet.get',
    method: 'GET',
    path: '/v1/workspaces/:workspaceId/credit-wallet',
    description: 'Read a sanitized workspace credit ledger summary without targeting legacy wallet tables.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getCreditWallet',
    notes: ['Read-only summary derived from append-only ledger entries when backend runtime exists.'],
  }),
  creditRoute({
    id: 'credits.estimate.create',
    method: 'POST',
    path: '/v1/projects/:projectId/credit-estimates',
    description: 'Validate a requested credit estimate payload and fail closed until transactional estimate creation exists.',
    securityLevel: 'workspace_editor',
    futureHandlerName: 'createCreditEstimate',
    notes: ['Requires Idempotency-Key. Prompt 6 returns backend_required instead of writing estimate rows.'],
  }),
  creditRoute({
    id: 'credits.estimate.get',
    method: 'GET',
    path: '/v1/credit-estimates/:creditEstimateId',
    description: 'Read scoped credit estimate metadata after project access validation.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getCreditEstimate',
    notes: ['Read-only; does not approve, reserve, or spend credits.'],
  }),
  creditRoute({
    id: 'credits.estimate.approve',
    method: 'POST',
    path: '/v1/credit-estimates/:creditEstimateId/approve',
    description: 'Validate estimate approval gates and fail closed until canonical approval mutation exists.',
    securityLevel: 'workspace_editor',
    futureHandlerName: 'approveCreditEstimate',
    notes: [
      'Requires Idempotency-Key.',
      'Approval source must be the canonical approval record tied to the approved plan/snapshot, not a legacy credit-specific approval table.',
    ],
  }),
  creditRoute({
    id: 'credits.gate.check',
    method: 'POST',
    path: '/v1/credits/gate/check',
    description: 'Read-only credit execution gate check for approved estimate, approved snapshot, active reservation, and no-double-spend blockers.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'checkCreditGate',
    notes: ['Returns status, canProceed, blockers, warnings, requiredRecords, and nextAction.'],
  }),
  creditRoute({
    id: 'credits.reservation.create',
    method: 'POST',
    path: '/v1/credit-estimates/:creditEstimateId/reservations',
    description: 'Validate reservation creation gates and fail closed until transactional reservation creation exists.',
    securityLevel: 'workspace_editor',
    futureHandlerName: 'createCreditReservation',
    notes: ['Requires Idempotency-Key. Prompt 6 does not insert reservation or ledger rows.'],
  }),
  creditRoute({
    id: 'credits.reservation.get',
    method: 'GET',
    path: '/v1/credit-reservations/:creditReservationId',
    description: 'Read scoped reservation metadata after workspace/project access validation.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getCreditReservation',
    notes: ['Read-only; does not release, spend, or refund credits.'],
  }),
  creditRoute({
    id: 'credits.reservation.release',
    method: 'POST',
    path: '/v1/credit-reservations/:creditReservationId/release',
    description: 'Validate reservation release readiness and fail closed until transactional release exists.',
    securityLevel: 'workspace_editor',
    futureHandlerName: 'releaseCreditReservation',
    notes: ['Requires Idempotency-Key. Release remains backend-required and append-only-ledger-backed.'],
  }),
  creditRoute({
    id: 'credits.reservation.spend',
    method: 'POST',
    path: '/v1/credit-reservations/:creditReservationId/spend',
    description: 'Validate spend readiness and fail closed until transactional spend exists.',
    securityLevel: 'backend_service_role',
    futureHandlerName: 'spendCreditReservation',
    notes: ['Requires Idempotency-Key and must be called only by future backend execution paths after approval gates pass.'],
  }),
  creditRoute({
    id: 'credits.reservation.refund',
    method: 'POST',
    path: '/v1/credit-reservations/:creditReservationId/refund',
    description: 'Validate refund readiness and fail closed until transactional refund exists.',
    securityLevel: 'backend_service_role',
    futureHandlerName: 'refundCreditReservation',
    notes: ['Requires Idempotency-Key. Refund eligibility must be derived from canonical reservation and ledger history.'],
  }),
  creditRoute({
    id: 'credits.ledger.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/credit-ledger',
    description: 'List sanitized append-only credit ledger entries for a scoped project.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'listCreditLedgerForProject',
    notes: ['Read-only; user-facing payloads must not expose service-role-only metadata.'],
  }),
  creditRoute({
    id: 'credits.blockers',
    method: 'POST',
    path: '/v1/credits/blockers',
    description: 'Return current credit blockers in a review-friendly shape without mutating credits.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getCreditBlockers',
    notes: ['Designed for UI/debug visibility before downstream execution can proceed.'],
  }),
  creditRoute({
    id: 'credits.readiness.check',
    method: 'POST',
    path: '/v1/credits/readiness',
    description: 'Check credit runtime readiness without approving, reserving, spending, releasing, or refunding credits.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'checkCreditReadiness',
    notes: ['Returns backend_required when service-role transactional runtime is unavailable.'],
  }),
]
