import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const CREDIT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'credits.estimate.create',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/estimate',
    description: 'Create a mock credit estimate before approval.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockCreditEstimate',
    futureHandlerName: 'createCreditEstimate',
    notes: ['Estimates are safe to show before any spend or reservation. RP-FIX-09 runtime estimates remain mock-only.'],
  },
  {
    id: 'credits.estimate.approve',
    domain: 'credits',
    method: 'POST',
    path: '/v1/credit-estimates/:creditEstimateId/approve',
    description: 'Approve a credit estimate as part of signed-in edit-plan approval.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'approveCreditEstimate',
    notes: ['Reviewed /v1 backend route requires auth and idempotency; internal testing records approval without wallet, ledger, Stripe, provider, worker, render, export, or production billing mutation.'],
  },
  {
    id: 'credits.reserve',
    domain: 'credits',
    method: 'POST',
    path: '/v1/credit-estimates/:creditEstimateId/reserve',
    description: 'Reserve credits before backend edit execution starts.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'reserveCredits',
    notes: ['Reviewed /v1 backend route requires auth and idempotency; internal testing records reservation without spend, wallet, ledger, Stripe, provider, worker, render, export, or production billing mutation.'],
  },
  {
    id: 'credits.toolCost.estimate',
    domain: 'credits',
    method: 'POST',
    path: '/v1/tool-costs/estimate',
    description: 'Estimate internal tool-owner cost before backend-approved paid work.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockToolCostEstimate',
    futureHandlerName: 'estimateToolCost',
    notes: [
      'Reviewed /v1 backend route requires auth and computes internal tool cost only.',
      'No wallet, ledger, Stripe, provider, worker, render, export, or production billing mutation is authorized.',
      'ReEditPro service fees remain outside tool-owner cost estimates/events.',
    ],
  },
  {
    id: 'credits.toolCost.event.create',
    domain: 'credits',
    method: 'POST',
    path: '/v1/tool-costs/events',
    description: 'Emit an idempotent internal tool-owner cost event after backend-approved work finishes.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockToolCostEventCreate',
    futureHandlerName: 'emitToolCostEvent',
    notes: [
      'Reviewed /v1 backend route requires auth and idempotency.',
      'Mock mode stores events in memory and replays duplicate idempotency keys without double charging.',
      'Non-mock persistence remains backend-required until a metering table/RPC exists.',
      'Tool-owner events exclude ReEditPro service fees.',
    ],
  },
  {
    id: 'credits.toolCost.summary.get',
    domain: 'credits',
    method: 'GET',
    path: '/v1/projects/:projectId/tool-cost-summary',
    description: 'Read the project internal tool-cost summary for user-facing estimate/review UI.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockToolCostSummaryGet',
    futureHandlerName: 'getProjectToolCostSummary',
    notes: [
      'Reviewed /v1 backend route requires auth.',
      'Summary is read-only and excludes ReEditPro service fees from tool-owner event totals.',
      'No wallet, ledger, Stripe, provider, worker, render, export, or production billing mutation is authorized.',
    ],
  },
  {
    id: 'credits.release',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/reservations/release',
    description: 'Release an unused credit reservation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'releaseCreditReservation',
    notes: ['Backend-only ledger mutation.'],
  },
  {
    id: 'credits.refund',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/refunds',
    description: 'Refund credits after eligible failed work.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'refundCredits',
    notes: ['Backend-only ledger mutation.'],
  },
  {
    id: 'credits.gate.check',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/gate/check',
    description: 'Check the mock credit approval/reservation gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockCreditGateCheck',
    futureHandlerName: 'checkCreditApprovalGate',
    notes: ['Mock check only; real gate enforcement must run in backend runtime.'],
  },
]
