import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const CREDIT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'credits.estimate.create',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/estimate',
    description: 'Create a mock credit estimate before approval.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockCreditEstimate',
    futureHandlerName: 'createCreditEstimate',
    notes: ['Estimates are safe to show before any spend or reservation. RP-FIX-09 runtime estimates remain mock-only.'],
  },
  {
    id: 'credits.estimate.approve',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/estimate/approve',
    description: 'Approve a credit estimate as part of edit-plan approval.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'approveCreditEstimate',
    notes: ['Real approval must be auditable and tied to an approved plan version.'],
  },
  {
    id: 'credits.reserve',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/reservations',
    description: 'Reserve credits before backend work starts.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'reserveCredits',
    notes: ['Never reserve credits in frontend code.'],
  },
  {
    id: 'credits.release',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/reservations/release',
    description: 'Release an unused credit reservation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'releaseCreditReservation',
    notes: ['Backend-only ledger mutation.'],
  },
  {
    id: 'credits.refund',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/refunds',
    description: 'Refund credits after eligible failed work.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'refundCredits',
    notes: ['Backend-only ledger mutation.'],
  },
  {
    id: 'credits.gate.check',
    domain: 'credits',
    method: 'POST',
    path: '/api/credits/gate/check',
    description: 'Check the mock credit approval/reservation gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockCreditGateCheck',
    futureHandlerName: 'checkCreditApprovalGate',
    notes: ['Mock check only; real gate enforcement must run in backend runtime.'],
  },
]
