import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const EDIT_PLANNING_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'planning.intent.analyze',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/intent',
    description: 'Analyze user editing intent.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    futureHandlerName: 'analyzeIntent',
    notes: ['Mock flow uses deterministic local planning and does not call AI models.'],
  },
  {
    id: 'planning.sourceSequenceMap.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/source-sequence-map',
    description: 'Create a source sequence map from uploaded source order.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Current mock planning flow creates this as part of the chat-native plan.'],
  },
  {
    id: 'planning.editPlan.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-plan',
    description: 'Create an edit plan and credit estimate preview.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    futureHandlerName: 'createEditPlan',
    notes: ['Stops before generation and credit reservation.'],
  },
  {
    id: 'planning.editQuality.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-quality',
    description: 'Create deterministic edit quality planning records.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Quality planning is mock-only until media analysis workers exist.'],
  },
  {
    id: 'planning.signatureRoutes.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/signature-routes',
    description: 'Create signature system route planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['No provider, worker, or render execution happens in the mock route.'],
  },
  {
    id: 'planning.editPlan.approve',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-plan/approve',
    description: 'Approve an edit plan after user review.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'approveEditPlan',
    notes: ['Approval must write immutable snapshots and coordinate credit reservation in a backend runtime.'],
  },
  {
    id: 'planning.demo.chatNative.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/mock/planning/chat-native',
    description: 'Run the local chat-native planning demo.',
    securityLevel: 'public',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Useful smoke route for frontend-safe mock runtime.'],
  },
]
