import type { ApiRouteDefinition } from '../api-runtime-contracts'

const EDIT_BRIEF_PATH =
  '/v1/projects/:projectId/edit-sessions/:editSessionId/edit-brief'

const sharedNotes = [
  'The route is bearer-authenticated and bound to the exact workspace, project, and named edit.',
  'It cannot publish or approve a plan, reserve credits, execute tools, call providers, render, export, or deliver media.',
]

export const EDIT_BRIEF_AUTHORITY_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'planning.editBriefAuthority.get',
    domain: 'planning',
    method: 'GET',
    path: EDIT_BRIEF_PATH,
    description: 'Read the canonical optional Edit Brief and marker timeline for one named edit.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getCanonicalEditBriefAuthority',
    notes: sharedNotes,
  },
  {
    id: 'planning.editBriefAuthority.create',
    domain: 'planning',
    method: 'POST',
    path: EDIT_BRIEF_PATH,
    description: 'Create the canonical optional Edit Brief for one named edit.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createCanonicalEditBriefAuthority',
    notes: sharedNotes,
  },
  {
    id: 'planning.editBriefAuthority.update',
    domain: 'planning',
    method: 'PATCH',
    path: EDIT_BRIEF_PATH,
    description: 'Update canonical Edit Brief direction with exact revision and idempotency control.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'updateCanonicalEditBriefAuthority',
    notes: sharedNotes,
  },
  {
    id: 'planning.editBriefMarker.create',
    domain: 'planning',
    method: 'POST',
    path: `${EDIT_BRIEF_PATH}/markers`,
    description: 'Create one time-bound canonical Edit Brief marker.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createCanonicalEditBriefMarker',
    notes: sharedNotes,
  },
  {
    id: 'planning.editBriefMarker.update',
    domain: 'planning',
    method: 'PATCH',
    path: `${EDIT_BRIEF_PATH}/markers/:markerId`,
    description: 'Update one canonical Edit Brief marker and reset stale confirmation.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'updateCanonicalEditBriefMarker',
    notes: sharedNotes,
  },
  ...(['confirm', 'archive', 'reopen'] as const).map((action): ApiRouteDefinition => ({
    id: `planning.editBriefMarker.${action}`,
    domain: 'planning',
    method: 'POST',
    path: `${EDIT_BRIEF_PATH}/markers/:markerId/${action}`,
    description: `${action[0].toUpperCase()}${action.slice(1)} one canonical Edit Brief marker.`,
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: `${action}CanonicalEditBriefMarker`,
    notes: sharedNotes,
  })),
  {
    id: 'planning.editBriefMarker.message.create',
    domain: 'planning',
    method: 'POST',
    path: `${EDIT_BRIEF_PATH}/markers/:markerId/messages`,
    description: 'Append one user-authored message to the exact marker discussion.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'appendCanonicalEditBriefMarkerMessage',
    notes: [
      ...sharedNotes,
      'The public route can append only a user message. Model responses remain a separate server-owned reasoning boundary.',
    ],
  },
]
