import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const EDIT_PLANNING_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'planning.canonicalHandoff.create',
    domain: 'planning',
    method: 'POST',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/canonical-planning-handoff',
    description: 'Persist the exact authenticated planning inputs for one named edit.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createCanonicalPlanningHandoff',
    notes: [
      'Reviewed /v1 backend route revalidates private source media, exact edit preferences, optional preference DNA, Edit Brief authority, output frame, and cleanup confirmation.',
      'This create-only handoff publishes no plan, reserves no credits, executes no tools, calls no provider, and renders nothing.',
    ],
  },
  {
    id: 'planning.canonicalPublicationRequest.create',
    domain: 'planning',
    method: 'POST',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/canonical-planning-handoffs/:handoffId/publication-requests',
    description: 'Persist an exact canonical plan publication candidate for internal revalidation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createCanonicalPlanPublicationRequest',
    notes: [
      'Reviewed /v1 backend route stores a private tenant-scoped candidate only when it matches the persisted handoff hash and canonical components.',
      'The browser cannot publish the candidate; internal-service publication and full revalidation remain separate authority gates.',
    ],
  },
  {
    id: 'planning.canonicalJourney.get',
    domain: 'planning',
    method: 'GET',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/canonical-journey',
    description: 'Recover the authenticated canonical edit journey for one named edit.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getCanonicalEditJourney',
    notes: [
      'Reviewed /v1 backend route is inspection-only and returns bounded workflow summaries plus one exact next safe action.',
      'The browser must translate the response into user-facing workflow state and must not execute the returned route as authority.',
    ],
  },
  {
    id: 'planning.intent.analyze',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/intent',
    description: 'Analyze user editing intent.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    futureHandlerName: 'analyzeIntent',
    notes: ['Mock flow uses deterministic local planning and does not call AI models.'],
  },
  {
    id: 'planning.sourceSequenceMap.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/source-sequence-map',
    description: 'Create a source sequence map from uploaded source order.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Current mock planning flow creates this as part of the chat-native plan.'],
  },
  {
    id: 'planning.editPlan.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-plan',
    description: 'Create an edit plan and credit estimate preview.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    futureHandlerName: 'createEditPlan',
    notes: ['Stops before generation and credit reservation.'],
  },
  {
    id: 'planning.editQuality.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-quality',
    description: 'Create deterministic edit quality planning records.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Quality planning is mock-only until media analysis workers exist.'],
  },
  {
    id: 'planning.signatureRoutes.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/signature-routes',
    description: 'Create signature system route planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['No provider, worker, or render execution happens in the mock route.'],
  },
  {
    id: 'planning.editPlan.approve',
    domain: 'planning',
    method: 'POST',
    path: '/api/planning/edit-plan/approve',
    description: 'Approve an edit plan after user review.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'approveEditPlan',
    notes: ['Approval must write immutable snapshots and coordinate credit reservation in a backend runtime.'],
  },
  {
    id: 'planning.approvedSnapshot.create',
    domain: 'planning',
    method: 'POST',
    path: '/v1/edit-plans/:editPlanId/approved-snapshots',
    description: 'Create an immutable approved plan snapshot after plan and credit approval.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createApprovedSnapshot',
    notes: ['Reviewed /v1 backend route requires auth, idempotency, approved plan evidence, and credit reservation evidence.'],
  },
  {
    id: 'planning.approvedSnapshot.get',
    domain: 'planning',
    method: 'GET',
    path: '/v1/approved-snapshots/:snapshotId',
    description: 'Read approved plan snapshot metadata for signed-in execution lineage checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getApprovedSnapshot',
    notes: ['Reviewed /v1 backend route requires auth and returns approved snapshot metadata without exposing service-role access.'],
  },
  {
    id: 'planning.demo.chatNative.create',
    domain: 'planning',
    method: 'POST',
    path: '/api/mock/planning/chat-native',
    description: 'Run the local chat-native planning demo.',
    securityLevel: 'public',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Useful smoke route for frontend-safe mock runtime.'],
  },
]
