import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const GENERATION_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'generation.creditGate.check',
    domain: 'generation',
    method: 'POST',
    path: '/api/generation/credit-gate',
    description: 'Check whether generation can pass the credit approval/reservation gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockGenerationCreditGate',
    futureHandlerName: 'checkGenerationCreditGate',
    notes: ['Does not call providers or queue generation.'],
  },
  {
    id: 'generation.request.create',
    domain: 'generation',
    method: 'POST',
    path: '/api/generation/requests',
    description: 'Create a generation request from an approved plan.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'createGenerationRequest',
    notes: ['Real generation calls are disabled until backend provider routing exists.'],
  },
  {
    id: 'generation.workerJob.create',
    domain: 'generation',
    method: 'POST',
    path: '/api/generation/worker-jobs',
    description: 'Create a worker job for generation or processing.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'createGenerationWorkerJob',
    notes: ['Does not exist in mock runtime.'],
  },
  {
    id: 'generation.jobRuntime.queueMock',
    domain: 'generation',
    method: 'POST',
    path: '/api/generation/jobs/mock',
    description: 'Queue a mock generation job through the RP-FIX-10 job runtime.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobQueue',
    futureHandlerName: 'queueGenerationJob',
    notes: ['Mock route only; provider execution remains backend-required.'],
  },
  {
    id: 'generation.runtime.transportMock',
    domain: 'generation',
    method: 'POST',
    path: '/api/generation/runtime/transport/mock',
    description: 'Create and send a mock backend runtime envelope for a generation worker.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRuntimeTransportSend',
    futureHandlerName: 'sendGenerationRuntimeEnvelope',
    notes: ['Provider execution and real worker dispatch remain backend-required.'],
  },
  {
    id: 'generation.status.get',
    domain: 'generation',
    method: 'GET',
    path: '/api/generation/requests/:requestId/status',
    description: 'Check generation status.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getGenerationStatus',
    notes: ['Future route should expose sanitized user-safe status only.'],
  },
]
