import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const INTERNAL_BETA_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'internalBeta.session.create',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/sessions',
    description: 'Create the backend-owned internal beta project/session shell after authenticated workspace checks.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createInternalBetaSession',
    notes: [
      'Contract only; frontend must not perform service-role project/session mutations.',
      'Must audit workspace membership and idempotency before any write.',
    ],
  },
  {
    id: 'internalBeta.approvedPlan.commit',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/approved-plans',
    description: 'Persist an immutable approved plan snapshot tied to the approved credit estimate and reservation.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'commitInternalBetaApprovedPlan',
    notes: [
      'Must reject raw chat execution and require frozen plan, source sequence, timing, QA, and credit hashes.',
      'Workers execute approved snapshots only.',
    ],
  },
  {
    id: 'internalBeta.creditReservation.create',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/credit-reservations',
    description: 'Create an internal beta credit reservation ledger entry after user approval.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createInternalBetaCreditReservation',
    notes: [
      'No Stripe checkout, webhook, payment processing, or paid production billing is enabled by this contract.',
      'Reservation, release, and refund must be append-only/audited before worker enqueue.',
    ],
  },
  {
    id: 'internalBeta.job.enqueue',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/jobs',
    description: 'Enqueue backend work items from an approved snapshot and valid credit reservation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'enqueueInternalBetaJob',
    notes: [
      'Must use idempotency keys, approved snapshot IDs, dependency graph, and structured job categories.',
      'Does not dispatch workers, providers, tools, rendering, or media processing in this milestone.',
    ],
  },
  {
    id: 'internalBeta.job.status.get',
    domain: 'internalBeta',
    method: 'GET',
    path: '/api/internal-beta/jobs/:jobId/status',
    description: 'Read sanitized internal beta job status and worker events for the project workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getInternalBetaJobStatus',
    notes: [
      'Readback must be scoped by workspace/project membership and must never expose service-role internals.',
      'Progress does not imply final export readiness.',
    ],
  },
  {
    id: 'internalBeta.artifactManifest.write',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/artifact-manifests',
    description: 'Write backend-owned artifact manifest and manifest item records for worker outputs.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'writeInternalBetaArtifactManifest',
    notes: [
      'Manifest writes are service-role only; authenticated users receive read-scoped metadata through RLS.',
      'No generated artifact or storage object is created by this route contract.',
    ],
  },
  {
    id: 'internalBeta.privateArtifactAccess.create',
    domain: 'internalBeta',
    method: 'POST',
    path: '/api/internal-beta/artifacts/private-access',
    description: 'Create a scoped private artifact access response after artifact manifest and membership checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createInternalBetaPrivateArtifactAccess',
    notes: [
      'Disabled until a guarded private-artifact-access milestone approves exact signed URL policy and TTL.',
      'No public artifacts or final delivery unlocks are authorized by this contract.',
    ],
  },
  {
    id: 'internalBeta.qaReport.read',
    domain: 'internalBeta',
    method: 'GET',
    path: '/api/internal-beta/qa-reports/:qaReportId',
    description: 'Read sanitized QA report metadata tied to an approved snapshot and artifact manifest.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readInternalBetaQaReport',
    notes: [
      'Readback only; QA execution remains a future worker/runtime milestone.',
      'Must not expose private storage paths beyond policy-approved metadata.',
    ],
  },
]
