import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const JOB_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'jobs.batch.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/batches',
    description: 'Create a backend job batch from an approved plan.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createJobBatch',
    notes: ['Real jobs start only after plan approval and credit reservation.'],
  },
  {
    id: 'jobs.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs',
    description: 'Create a backend work item.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createJob',
    notes: ['Worker orchestration remains disabled in RP-FIX-08.'],
  },
  {
    id: 'jobs.queue',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/queue/mock',
    description: 'Create a mock-safe queue item after job runtime gate checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobQueue',
    futureHandlerName: 'queueJob',
    notes: ['Mock queue only; no Cloud Run, provider, render, or Supabase mutation occurs.'],
  },
  {
    id: 'jobs.gate.check',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/gate',
    description: 'Check worker/job gates before dispatch.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobGateCheck',
    futureHandlerName: 'checkJobRuntimeGates',
    notes: ['Checks local mock records only.'],
  },
  {
    id: 'jobs.dependencies.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/dependencies/mock',
    description: 'Create a mock dependency chain for music, SFX, render, or signature jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobDependencies',
    futureHandlerName: 'createJobDependencyChain',
    notes: ['Dependency chain is local metadata only.'],
  },
  {
    id: 'jobs.dispatch.mock',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/dispatch/mock',
    description: 'Dispatch a mock worker job after local gates pass.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobDispatch',
    futureHandlerName: 'dispatchWorkerJob',
    notes: ['Mock dispatch can call only local Lyria/SFX/generic placeholders. Real dispatch remains backend-required.'],
  },
  {
    id: 'jobs.status.get',
    domain: 'jobs',
    method: 'GET',
    path: '/api/jobs/:jobId/status',
    description: 'Read job status for user-visible progress.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobStatus',
    futureHandlerName: 'getJobStatus',
    notes: ['Mock status is local only. Future read route must filter by project/workspace membership.'],
  },
  {
    id: 'jobs.events.list',
    domain: 'jobs',
    method: 'GET',
    path: '/api/jobs/:jobId/events',
    description: 'List job events for progress and recovery UI.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobEvents',
    futureHandlerName: 'listJobEvents',
    notes: ['Mock events are human-readable status events only. Future route should avoid exposing backend logs or secrets.'],
  },
  {
    id: 'jobs.retry.schedule',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/:jobId/retry',
    description: 'Schedule a mock retry after a failed job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobRetry',
    futureHandlerName: 'scheduleJobRetry',
    notes: ['Retry is mock-only and must re-check gates before future real execution.'],
  },
  {
    id: 'jobs.cancel',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/:jobId/cancel',
    description: 'Cancel a mock job before dispatch.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobCancel',
    futureHandlerName: 'cancelJob',
    notes: ['Mock cancellation only; real cancellation belongs behind backend runtime.'],
  },
  {
    id: 'runtime.envelope.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/runtime/envelopes/mock',
    description: 'Create a mock backend runtime envelope for future worker/API transport.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRuntimeEnvelopeCreate',
    futureHandlerName: 'createBackendRuntimeEnvelope',
    notes: ['Envelope creation is metadata only; real transport remains backend-required.'],
  },
  {
    id: 'runtime.transport.mockSend',
    domain: 'jobs',
    method: 'POST',
    path: '/api/runtime/transport/mock',
    description: 'Send a mock runtime envelope through the local mock transport.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRuntimeTransportSend',
    futureHandlerName: 'sendBackendRuntimeEnvelope',
    notes: ['No HTTP, Supabase Edge, Cloud Run, Pub/Sub, provider, or worker call occurs.'],
  },
  {
    id: 'jobs.qwen2_5_vl.privateInvoke.dryRun',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/qwen2-5-vl/private-invoke/dry-run/mock',
    description: 'Run the Qwen2.5-VL private-invoke dry-run coordinator without transport.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockQwenPrivateInvokeDryRun',
    futureHandlerName: 'runQwenPrivateInvokeDryRun',
    notes: [
      'Composes approved-snapshot queue validation, private-invoke envelope shaping, and response classification only.',
      'No service URL, auth header, identity token, Cloud Run request, inference, worker dispatch, Supabase mutation, credit mutation, generated asset, public artifact, or signed URL occurs.',
      'Raw prompt body fields are rejected before the dry-run coordinator is called.',
    ],
  },
  {
    id: 'worker.lease.claim',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/claim/mock',
    description: 'Claim a mock worker lease for a queued mock job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseClaim',
    futureHandlerName: 'claimWorkerLease',
    notes: ['Real worker lease claims must be backend-only and transactional.'],
  },
  {
    id: 'worker.lease.heartbeat',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/heartbeat/mock',
    description: 'Send a mock heartbeat for a claimed worker lease.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseHeartbeat',
    futureHandlerName: 'heartbeatWorkerLease',
    notes: ['Real heartbeat updates require backend/service-role runtime.'],
  },
  {
    id: 'worker.lease.renew',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/renew/mock',
    description: 'Renew a mock worker lease.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRenew',
    futureHandlerName: 'renewWorkerLease',
    notes: ['Real renewal must verify lease token and worker identity on the backend.'],
  },
  {
    id: 'worker.lease.release',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/release/mock',
    description: 'Release a mock worker lease without completing the job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRelease',
    futureHandlerName: 'releaseWorkerLease',
    notes: ['Real release is backend-required.'],
  },
  {
    id: 'worker.lease.complete',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/complete/mock',
    description: 'Complete a mock worker lease after mock job success.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseComplete',
    futureHandlerName: 'completeWorkerLease',
    notes: ['Real completion must be idempotent and backend-only.'],
  },
  {
    id: 'worker.lease.fail',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/fail/mock',
    description: 'Fail a mock worker lease after mock worker error.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseFail',
    futureHandlerName: 'failWorkerLease',
    notes: ['Failed provider-like work must verify idempotency before retry in production.'],
  },
  {
    id: 'worker.lease.recoverStale',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/recover-stale/mock',
    description: 'Detect and recover stale mock worker leases.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRecoverStale',
    futureHandlerName: 'recoverStaleWorkerLease',
    notes: ['Real stale recovery requires backend idempotency and provider side-effect checks.'],
  },
  {
    id: 'worker.runtime.registry',
    domain: 'jobs',
    method: 'GET',
    path: '/api/workers/runtime-registry',
    description: 'Read mock worker runtime registry metadata.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerRuntimeRegistry',
    futureHandlerName: 'getWorkerRuntimeRegistry',
    notes: ['Registry is metadata only; it does not start workers.'],
  },
]
