import type { ApiRouteDefinition } from '../api-runtime-contracts'

const RAW_JOB_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'jobs.batch.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/batches',
    description: 'Create a backend job batch from an approved plan.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createJobBatch',
    notes: ['Real jobs start only after plan approval and credit reservation.'],
  },
  {
    id: 'jobs.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs',
    description: 'Create a backend work item.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createJob',
    notes: ['Worker orchestration remains disabled in RP-FIX-08.'],
  },
  {
    id: 'jobs.queue',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/queue/mock',
    description: 'Create a mock-safe queue item after job runtime gate checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobQueue',
    futureHandlerName: 'queueJob',
    notes: ['Mock queue only; no Cloud Run, provider, render, or Supabase mutation occurs.'],
  },
  {
    id: 'jobs.gate.check',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/gate',
    description: 'Check worker/job gates before dispatch.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobGateCheck',
    futureHandlerName: 'checkJobRuntimeGates',
    notes: ['Checks local mock records only.'],
  },
  {
    id: 'editExecution.canonicalPackageRequest.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/approved-snapshots/:snapshotId/canonical-execution-package',
    description: 'Request a bounded private execution handoff receipt from an exact approved snapshot.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'requestCanonicalExecutionPackage',
    notes: [
      'Available only in the explicit local/private runtime and requires exact workspace, project, edit, snapshot, and hash authority.',
      'Returns a bounded receipt only; raw execution package, jobs, tool manifest, worker authority, paths, and credentials remain backend-only.',
      'Does not start the work graph, workers, jobs, tools, providers, rendering, billing, wallet mutation, or public delivery.',
    ],
  },
  {
    id: 'editExecution.canonicalPrivateEditPreparation.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/packages/:packageRecordId/canonical-private-edit-preparation',
    description: 'Advance one exact approved package through bounded private edit preparation and review assembly.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'prepareCanonicalPrivateEditReview',
    notes: [
      'Available only in the explicit local/private runtime after exact approved snapshot, reservation, and package authority exist.',
      'The browser may submit exact identity and hashes only; jobs, tools, commands, paths, URLs, credentials, providers, and prices are server-derived or rejected.',
      'Returns bounded progress or private-review readiness; raw job/tool authority, public delivery, production rendering, provider calls, billing, settlement, wallet mutation, and deployment remain disabled.',
    ],
  },
  {
    id: 'editExecution.canonicalPrivateReviewMedia.read',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/private-review-assemblies/:reviewAssemblyId/media',
    description: 'Read the verified MP4 for one exact completed canonical private review.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readCanonicalPrivateReviewMedia',
    notes: [
      'Available only in the explicit local/private runtime and requires exact workspace, project, edit, package, review-manifest, and final-artifact hash authority.',
      'Artifact, job, expected-output, storage, and filesystem identities are derived and reverified by the backend and are never accepted from the browser.',
      'Returns private no-store MP4 bytes only; signed URLs, public delivery, production rendering, providers, billing, settlement, wallet mutation, and deployment remain disabled.',
    ],
  },
  {
    id: 'editExecution.canonicalPrivateReviewDecision.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-review-assemblies/:reviewAssemblyId/canonical-decision',
    description: 'Record one exact private-review acceptance or structured revision request.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'recordCanonicalPrivateReviewDecision',
    notes: [
      'Available only in the explicit local/private runtime and revalidates the immutable completed review before recording one create-only decision.',
      'Returns a bounded decision receipt; raw decision manifests, approved-plan authority, artifact identities, jobs, tools, paths, and credentials remain backend-only.',
      'Acceptance does not authorize public delivery, and revision requires a fresh plan, estimate, approval, execution pass, and private review.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryDiscovery.read',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/professional-long-form-customer-delivery',
    description: 'Discover the exact private long-form customer-delivery package and bounded progress for one named edit.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'discoverProfessionalLongFormCustomerDelivery',
    notes: [
      'The browser supplies exact workspace, project, edit, and approved snapshot identity; the backend resolves the package identity through a tenant-scoped immutable pointer.',
      'The response exposes bounded progress and the strict review receipt only when ready. Raw package, queue, jobs, leases, attempts, internal cost, paths, credentials, and storage authority remain server-only.',
      'Discovery is inspection-only and starts no job, render, provider, second export estimate, customer charge, credit prompt, wallet mutation, public delivery, billing, or deployment action.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryQualityReview.read',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/professional-long-form/customer-delivery-packages/:packageRecordId/quality-review',
    description: 'Read the browser-safe quality-review contract for one exact private long-form customer delivery.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readProfessionalLongFormCustomerDeliveryQualityReview',
    notes: [
      'Available only in the explicit private/local runtime and requires exact workspace, approved snapshot, and customer-delivery package identity.',
      'Returns a strict browser receipt only; queue, lease, attempt, worker, tool, internal-cost, storage, filesystem, credential, and raw authority fields remain server-only.',
      'No provider, render, public delivery, second export estimate, customer charge, credit prompt, wallet mutation, billing, or deployment starts.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryQualityReviewMedia.read',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/professional-long-form/customer-delivery-packages/:packageRecordId/quality-review/media',
    description: 'Stream authenticated byte ranges from the exact private long-form master before its quality decision.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readProfessionalLongFormCustomerDeliveryQualityReviewMedia',
    notes: [
      'The exact immutable review packet and master hashes are required before any no-store MP4 bytes are streamed.',
      'Authenticated bounded ranges support long-form playback without downloading the complete master into browser memory.',
      'This review stream does not authorize the separate download job, public delivery, provider calls, rendering, billing, credit mutation, or deployment.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryWatchCheckpoint.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/professional-long-form/customer-delivery-packages/:packageRecordId/quality-review/watch-checkpoints',
    description: 'Record or replay one bounded server-validated playback checkpoint for the exact private long-form review master.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'recordProfessionalLongFormCustomerDeliveryWatchCheckpoint',
    notes: [
      'The checkpoint is bound to exact workspace, approved snapshot, review packet, master checksum, predecessor hash, sequence, and merged frame intervals.',
      'Server-observed elapsed time and the 2x playback ceiling reject instant or implausible whole-program completion; browser-reported completion is never trusted directly.',
      'The private/local hash chain is not distributed production durability and starts no provider, render, public delivery, second estimate, charge, credit, wallet, billing, or deployment action.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryQualityDecision.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/professional-long-form/customer-delivery-packages/:packageRecordId/quality-decision',
    description: 'Record or replay one exact authenticated long-form delivery acceptance or structured revision request.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'recordProfessionalLongFormCustomerDeliveryQualityDecision',
    notes: [
      'Acceptance requires explicit whole-program video, audio/sync, known-QA-item, approved-intent, and speech-disposition attestations bound to exact hashes.',
      'Only acceptance can authorize the separate one-use private-download reconciliation; revision closes download and requires a fresh plan, estimate, and approval.',
      'The browser receives a bounded receipt only. Public delivery, a second export estimate or charge, credits, wallet, billing, provider calls, and deployment remain closed.',
    ],
  },
  {
    id: 'editExecution.professionalLongFormCustomerDeliveryPrivateDownload.read',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/professional-long-form/customer-delivery-packages/:packageRecordId/private-download/file',
    description: 'Stream authenticated byte ranges from an accepted and reconciled private long-form customer delivery.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readProfessionalLongFormCustomerDeliveryPrivateDownload',
    notes: [
      'Requires the exact accepted decision hash and exact private master checksum after one-use download reconciliation completes.',
      'The response is authenticated, no-store, range-capable MP4 bytes; no public or signed URL is created.',
      'The original approved 4K estimate and reservation are reused. No second estimate, charge, credit prompt, wallet mutation, billing, provider, render, or deployment action occurs.',
    ],
  },
  {
    id: 'editExecution.package.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/packages',
    description: 'Create a mock-safe approved edit execution package from an approved snapshot.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionPackageCreate',
    futureHandlerName: 'createApprovedEditExecutionPackage',
    notes: [
      'Requires approved snapshot and credit reservation evidence.',
      'Does not dispatch workers, execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.package.get',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/packages/:packageRecordId',
    description: 'Read a reviewed approved edit execution package by record ID.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getApprovedEditExecutionPackage',
    notes: [
      'Reviewed /v1 backend route requires auth and returns execution package metadata only.',
      'It does not dispatch workers, execute tools, process media, render, bill users, create signed URLs, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.boundedAdapterExecutionGate.get',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/packages/:packageRecordId/bounded-adapter-execution-gate',
    description: 'Read the server-owned bounded adapter execution gate for an approved edit execution package.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionBoundedAdapterExecutionGateRead',
    futureHandlerName: 'getApprovedEditExecutionBoundedAdapterExecutionGate',
    notes: [
      'Returns gate evidence only; client package/model readiness hints are not source truth.',
      'Does not dispatch workers, execute tools, import packages, process media, render, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.boundedAdapterSourceTruthReview.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/packages/:packageRecordId/bounded-adapter-source-truth-review',
    description: 'Record backend-owned package/model readiness evidence for bounded edit activity execution.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionBoundedAdapterSourceTruthReview',
    futureHandlerName: 'reviewApprovedEditExecutionBoundedAdapterSourceTruth',
    notes: [
      'Requires approved snapshot lineage, credit reservation, idempotency, and backend-owned package/model evidence.',
      'Does not dispatch workers, execute tools, import packages, process media, render, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
      'Client package/model readiness hints remain untrusted; this route records source-truth evidence only.',
    ],
  },
  {
    id: 'editExecution.boundedAdapterExecutionRun.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/packages/:packageRecordId/bounded-adapter-execution-runs',
    description: 'Create a private manifest handoff for backend bounded edit activity runner execution.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionBoundedAdapterExecutionRun',
    futureHandlerName: 'createApprovedEditExecutionBoundedAdapterExecutionRun',
    notes: [
      'Requires a ready backend source-truth review and credit reservation before private result manifests are prepared.',
      'Creates private manifest contracts only; actual package/library execution remains a later registered backend runner gate.',
      'Does not process media, render, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.registeredAdapterRunnerProbe.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/bounded-adapter-execution-runs/:boundedAdapterExecutionRunId/registered-runner-probe',
    description: 'Probe registered backend adapter runner package availability without processing media.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionRegisteredAdapterRunnerProbe',
    futureHandlerName: 'runApprovedEditExecutionRegisteredAdapterRunners',
    notes: [
      'Requires a completed bounded adapter private manifest handoff and importProbeOnly=true.',
      'Import probes verify backend package availability only; they do not process media or create artifacts.',
      'Does not render, call providers, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.registeredAdapterPrivateMediaRunner.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/registered-runner-runs/:registeredRunnerRunId/private-media-runner-execution',
    description: 'Record private runner manifests after backend adapter runner import probes pass.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionRegisteredAdapterPrivateMediaRunner',
    futureHandlerName: 'runApprovedEditExecutionRegisteredAdapterPrivateMediaRunner',
    notes: [
      'Requires completed registered runner import probes, approved snapshot lineage, credit reservation, and privateMediaExecutionOnly=true.',
      'Records private runner manifest lineage for adapter-specific QA; media-transform execution remains a later worker implementation gate.',
      'Does not render, call providers, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.registeredAdapterPrivateMediaRunnerQa.review',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-media-runner-runs/:privateMediaRunnerRunId/qa-review',
    description: 'Persist private QA evidence for registered adapter private runner manifests.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionRegisteredAdapterPrivateMediaRunnerQaReview',
    futureHandlerName: 'reviewApprovedEditExecutionRegisteredAdapterPrivateMediaRunnerQa',
    notes: [
      'Requires a completed registered adapter private runner manifest run, matching approved snapshot lineage, credit reservation, and qaReviewOnly=true.',
      'Records private JSON QA artifacts for adapter result evidence; final render integration still requires a later backend gate.',
      'Does not process media, render, call providers, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.adapterWorkerArtifactIntegration.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-runner-qa-reviews/:privateMediaRunnerQaReviewId/adapter-worker-artifact-integration',
    description: 'Verify private adapter QA artifacts and attach them to the private render-preview integration path.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionAdapterWorkerArtifactIntegration',
    futureHandlerName: 'createApprovedEditExecutionAdapterWorkerArtifactIntegration',
    notes: [
      'Requires a passed registered adapter private runner QA review, matching approved snapshot lineage, credit reservation, and integrationOnly=true.',
      'Verifies private QA artifact file/checksum evidence and records one private render integration manifest.',
      'Does not execute adapter media transforms, render, call providers, bill users, create signed URLs, write Supabase/GCS, or approve public delivery.',
    ],
  },
  {
    id: 'editExecution.privateInternalTestRun.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-internal-test-runs',
    description: 'Run the approved edit execution package chain through private internal download readiness for testing.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionPrivateInternalTestRun',
    futureHandlerName: 'createApprovedEditExecutionPrivateInternalTestRun',
    notes: [
      'Requires approved snapshot, credit reservation, and private uploaded source-media bindings.',
      'Runs only internal/mock-safe edit execution stages and returns a private internal download route for review.',
      'Does not create public artifacts, signed URLs, Supabase/GCS delivery records, external beta access, production release, or billing mutations.',
    ],
  },
  {
    id: 'editExecution.privateInternalDownload.file.get',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/private-internal-downloads/:privateInternalDownloadDeliveryId/file',
    description: 'Stream a QA-passed private final edit candidate through authenticated backend transport.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getPrivateInternalDownloadFile',
    notes: [
      'Reviewed /v1 route streams only private internal testing files from a persisted delivery registry.',
      'It does not create public artifacts, signed URLs, external beta access, production release, or billing mutations.',
    ],
  },
  {
    id: 'editExecution.privateInternalDownload.manifest.get',
    domain: 'jobs',
    method: 'GET',
    path: '/v1/edit-executions/private-internal-downloads/:privateInternalDownloadDeliveryId/manifest',
    description: 'Stream the private edit-decision manifest for a QA-passed internal edit candidate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getPrivateInternalDownloadManifestFile',
    notes: [
      'Reviewed /v1 route streams source-of-truth manifest JSON through authenticated backend transport.',
      'It does not expose raw prompts, secrets, signed URLs, public artifacts, external beta, production, or billing mutations.',
    ],
  },
  {
    id: 'editExecution.jobBatchPlan.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/packages/:packageRecordId/job-batch-plan',
    description: 'Create a mock-safe dry-run worker job batch plan from an approved edit execution package.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionJobBatchPlanCreate',
    futureHandlerName: 'createApprovedEditExecutionJobBatchPlan',
    notes: [
      'Preserves approved snapshot, credit reservation, dependency, output, and QA metadata for future queue creation.',
      'Does not claim workers, execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.mockQueue.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/job-batch-plans/:jobBatchPlanId/mock-queue',
    description: 'Create a mock-only queue from ready approved edit execution jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionQueueCreate',
    futureHandlerName: 'createApprovedEditExecutionQueue',
    notes: [
      'Queues ready job metadata only; worker dispatch and leases remain separate backend gates.',
      'Does not execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.dispatchReadiness.check',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/mock-queues/:mockQueueId/dispatch-readiness',
    description: 'Audit queued approved edit jobs for worker dispatch readiness without claiming workers.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionDispatchReadiness',
    futureHandlerName: 'checkApprovedEditExecutionDispatchReadiness',
    notes: [
      'Runs mock gate checks only and reports whether queued jobs are eligible for a later worker claim.',
      'Does not claim workers, execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.mockWorkerClaims.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/dispatch-readiness/:dispatchReadinessId/mock-worker-claims',
    description: 'Create mock-only worker claim leases from dispatch-ready approved edit jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionWorkerClaims',
    futureHandlerName: 'createApprovedEditExecutionWorkerClaims',
    notes: [
      'Claims metadata leases only after dispatch readiness has passed.',
      'Does not start worker handlers, execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.handlerDryRun.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/mock-worker-claims/:mockWorkerClaimsId/handler-dry-run',
    description: 'Create deterministic mock handler result metadata from claimed approved edit jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionHandlerDryRun',
    futureHandlerName: 'createApprovedEditExecutionHandlerDryRun',
    notes: [
      'Builds result, private artifact placeholder, and QA handoff metadata only.',
      'Does not start real handlers, execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.resultReconciliation.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/handler-dry-runs/:handlerDryRunId/result-reconciliation',
    description: 'Reconcile approved edit handler dry-run results into manifest and QA readiness metadata.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionResultReconciliation',
    futureHandlerName: 'createApprovedEditExecutionResultReconciliation',
    notes: [
      'Marks dry-run artifact refs as non-final placeholders and keeps QA/final render blocked.',
      'Does not execute tools, process media, render, bill users, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.localWorkerOutput.persist',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/result-reconciliations/:resultReconciliationId/local-worker-output',
    description: 'Persist private local worker-output metadata after approved edit dry-run result reconciliation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionLocalWorkerOutput',
    futureHandlerName: 'persistApprovedEditExecutionLocalWorkerOutput',
    notes: [
      'Writes private local metadata records for internal review only; no media output is produced.',
      'Does not execute tools, process media, render, bill users, create signed URLs, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.localWorkerOutputQa.review',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/local-worker-outputs/:localWorkerOutputId/qa-review',
    description: 'Review private local worker-output metadata before uploaded-media worker execution.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionLocalWorkerOutputQaReview',
    futureHandlerName: 'reviewApprovedEditExecutionLocalWorkerOutputQa',
    notes: [
      'Accepts private metadata integrity only; media output QA and render/export readiness remain blocked.',
      'Does not execute tools, process media, render, bill users, create signed URLs, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.workflowRehearsal.run',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/local-worker-outputs/:localWorkerOutputId/workflow-rehearsal',
    description: 'Run the approved edit production workflow rehearsal after private local output metadata exists.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionWorkflowRehearsal',
    futureHandlerName: 'runApprovedEditExecutionWorkflowRehearsal',
    notes: [
      'Runs dry-run production workflow stage orchestration only; uploaded media worker execution remains separate.',
      'Does not execute tools, process media, render, bill users, create signed URLs, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.uploadedMediaWorkerExecution.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/workflow-rehearsals/:workflowRehearsalId/uploaded-media-worker-execution',
    description: 'Bind uploaded source media references to private worker-output metadata after workflow rehearsal.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionUploadedMediaWorkerExecution',
    futureHandlerName: 'createApprovedEditExecutionUploadedMediaWorkerExecution',
    notes: [
      'Persists source-bound private worker-output metadata only; no uploaded media bytes are decoded or transformed.',
      'Does not execute tools, process media, render, bill users, create signed URLs, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.privateWorkerArtifactQa.review',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/uploaded-media-worker-executions/:uploadedMediaWorkerExecutionId/private-artifact-qa-review',
    description: 'Review source-bound private worker artifact metadata before real media processing.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionPrivateWorkerArtifactQaReview',
    futureHandlerName: 'reviewApprovedEditExecutionPrivateWorkerArtifactQa',
    notes: [
      'Accepts private metadata integrity only; real media processing, media QA, preview, and export remain blocked.',
      'Does not execute tools, process media, render, bill users, create signed URLs, or write Supabase/GCS.',
    ],
  },
  {
    id: 'editExecution.localMediaProcessingExecution.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-worker-artifact-qa-reviews/:privateWorkerArtifactQaReviewId/local-media-processing-execution',
    description: 'Create bounded private media artifacts from approved uploaded source media in local storage.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionLocalMediaProcessingExecution',
    futureHandlerName: 'createApprovedEditExecutionLocalMediaProcessingExecution',
    notes: [
      'Runs only local/private bounded media processing and keeps private media artifact QA, render preview, and final export blocked.',
      'Does not call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.privateMediaArtifactQa.review',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/local-media-processing-executions/:localMediaProcessingExecutionId/private-media-artifact-qa-review',
    description: 'Review private processed media artifacts before render preview assembly.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionPrivateMediaArtifactQaReview',
    futureHandlerName: 'reviewApprovedEditExecutionPrivateMediaArtifactQa',
    notes: [
      'Accepts private processed media artifact QA only; render preview assembly, user review, and final export remain separate gates.',
      'Does not process media, call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.renderPreviewAssembly.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/private-media-artifact-qa-reviews/:privateMediaArtifactQaReviewId/render-preview-assembly',
    description: 'Assemble QA-passed private media artifacts into a private render preview manifest.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionRenderPreviewAssembly',
    futureHandlerName: 'createApprovedEditExecutionRenderPreviewAssembly',
    notes: [
      'Creates a private internal preview manifest only; user preview review and final export remain separate gates.',
      'Does not process media, call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.userPreviewReview.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/render-preview-assemblies/:renderPreviewAssemblyId/user-preview-review',
    description: 'Record an internal/private preview review decision before final render readiness.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionUserPreviewReview',
    futureHandlerName: 'createApprovedEditExecutionUserPreviewReview',
    notes: [
      'Records approval or requested changes for the private preview only; final render/export remains separate.',
      'Does not process media, call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.finalRenderReadinessReview.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/user-preview-reviews/:userPreviewReviewId/final-render-readiness-review',
    description: 'Review an approved private preview for bounded final render execution readiness.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionFinalRenderReadinessReview',
    futureHandlerName: 'createApprovedEditExecutionFinalRenderReadinessReview',
    notes: [
      'Marks an approved private preview ready for a later final render execution gate only.',
      'Does not run render/export, process media, call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.finalRenderExecution.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/final-render-readiness-reviews/:finalRenderReadinessReviewId/final-render-execution',
    description: 'Create a private final-render candidate from approved private preview clips.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionFinalRenderExecution',
    futureHandlerName: 'createApprovedEditExecutionFinalRenderExecution',
    notes: [
      'Creates a private final-render candidate only; delivery QA and public/export release remain separate gates.',
      'Does not call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve production delivery.',
    ],
  },
  {
    id: 'editExecution.finalDeliveryQa.review',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/final-render-executions/:finalRenderExecutionId/final-delivery-qa-review',
    description: 'QA a private final-render candidate for internal testing download readiness.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionFinalDeliveryQaReview',
    futureHandlerName: 'createApprovedEditExecutionFinalDeliveryQaReview',
    notes: [
      'Approves only private internal download/testing readiness; public delivery and production remain blocked.',
      'Does not call providers, write Supabase/GCS, create signed URLs/public artifacts, bill users, or approve external beta/production delivery.',
    ],
  },
  {
    id: 'editExecution.privateInternalDownloadDelivery.create',
    domain: 'jobs',
    method: 'POST',
    path: '/v1/edit-executions/final-delivery-qa-reviews/:finalDeliveryQaReviewId/private-internal-download-delivery',
    description: 'Create an authenticated private internal download delivery record for a QA-passed final render.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockApprovedEditExecutionPrivateInternalDownloadDelivery',
    futureHandlerName: 'createApprovedEditExecutionPrivateInternalDownloadDelivery',
    notes: [
      'Creates only an authenticated private internal download route for testing.',
      'Does not create public artifacts, signed URLs, Supabase/GCS delivery records, external beta access, production release, or billing mutations.',
    ],
  },
  {
    id: 'jobs.dependencies.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/dependencies/mock',
    description: 'Create a mock dependency chain for music, SFX, render, or signature jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobDependencies',
    futureHandlerName: 'createJobDependencyChain',
    notes: ['Dependency chain is local metadata only.'],
  },
  {
    id: 'jobs.dispatch.mock',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/dispatch/mock',
    description: 'Dispatch a mock worker job after local gates pass.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobDispatch',
    futureHandlerName: 'dispatchWorkerJob',
    notes: ['Mock dispatch can call only local Lyria/SFX/generic placeholders. Real dispatch remains backend-required.'],
  },
  {
    id: 'jobs.status.get',
    domain: 'jobs',
    method: 'GET',
    path: '/api/jobs/:jobId/status',
    description: 'Read job status for user-visible progress.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobStatus',
    futureHandlerName: 'getJobStatus',
    notes: ['Mock status is local only. Future read route must filter by project/workspace membership.'],
  },
  {
    id: 'jobs.events.list',
    domain: 'jobs',
    method: 'GET',
    path: '/api/jobs/:jobId/events',
    description: 'List job events for progress and recovery UI.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobEvents',
    futureHandlerName: 'listJobEvents',
    notes: ['Mock events are human-readable status events only. Future route should avoid exposing backend logs or secrets.'],
  },
  {
    id: 'jobs.retry.schedule',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/:jobId/retry',
    description: 'Schedule a mock retry after a failed job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobRetry',
    futureHandlerName: 'scheduleJobRetry',
    notes: ['Retry is mock-only and must re-check gates before future real execution.'],
  },
  {
    id: 'jobs.cancel',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/:jobId/cancel',
    description: 'Cancel a mock job before dispatch.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockJobCancel',
    futureHandlerName: 'cancelJob',
    notes: ['Mock cancellation only; real cancellation belongs behind backend runtime.'],
  },
  {
    id: 'runtime.envelope.create',
    domain: 'jobs',
    method: 'POST',
    path: '/api/runtime/envelopes/mock',
    description: 'Create a mock backend runtime envelope for future worker/API transport.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRuntimeEnvelopeCreate',
    futureHandlerName: 'createBackendRuntimeEnvelope',
    notes: ['Envelope creation is metadata only; real transport remains backend-required.'],
  },
  {
    id: 'runtime.transport.mockSend',
    domain: 'jobs',
    method: 'POST',
    path: '/api/runtime/transport/mock',
    description: 'Send a mock runtime envelope through the local mock transport.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRuntimeTransportSend',
    futureHandlerName: 'sendBackendRuntimeEnvelope',
    notes: ['No HTTP, Supabase Edge, Cloud Run, Pub/Sub, provider, or worker call occurs.'],
  },
  {
    id: 'worker.lease.claim',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/claim/mock',
    description: 'Claim a mock worker lease for a queued mock job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseClaim',
    futureHandlerName: 'claimWorkerLease',
    notes: ['Real worker lease claims must be backend-only and transactional.'],
  },
  {
    id: 'worker.lease.heartbeat',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/heartbeat/mock',
    description: 'Send a mock heartbeat for a claimed worker lease.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseHeartbeat',
    futureHandlerName: 'heartbeatWorkerLease',
    notes: ['Real heartbeat updates require backend/service-role runtime.'],
  },
  {
    id: 'worker.lease.renew',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/renew/mock',
    description: 'Renew a mock worker lease.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRenew',
    futureHandlerName: 'renewWorkerLease',
    notes: ['Real renewal must verify lease token and worker identity on the backend.'],
  },
  {
    id: 'worker.lease.release',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/release/mock',
    description: 'Release a mock worker lease without completing the job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRelease',
    futureHandlerName: 'releaseWorkerLease',
    notes: ['Real release is backend-required.'],
  },
  {
    id: 'worker.lease.complete',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/complete/mock',
    description: 'Complete a mock worker lease after mock job success.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseComplete',
    futureHandlerName: 'completeWorkerLease',
    notes: ['Real completion must be idempotent and backend-only.'],
  },
  {
    id: 'worker.lease.fail',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/:leaseId/fail/mock',
    description: 'Fail a mock worker lease after mock worker error.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseFail',
    futureHandlerName: 'failWorkerLease',
    notes: ['Failed provider-like work must verify idempotency before retry in production.'],
  },
  {
    id: 'worker.lease.recoverStale',
    domain: 'jobs',
    method: 'POST',
    path: '/api/workers/leases/recover-stale/mock',
    description: 'Detect and recover stale mock worker leases.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerLeaseRecoverStale',
    futureHandlerName: 'recoverStaleWorkerLease',
    notes: ['Real stale recovery requires backend idempotency and provider side-effect checks.'],
  },
  {
    id: 'worker.runtime.registry',
    domain: 'jobs',
    method: 'GET',
    path: '/api/workers/runtime-registry',
    description: 'Read mock worker runtime registry metadata.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWorkerRuntimeRegistry',
    futureHandlerName: 'getWorkerRuntimeRegistry',
    notes: ['Registry is metadata only; it does not start workers.'],
  },
]

const LEGACY_MOCK_ONLY_EDIT_EXECUTION_ROUTE_IDS = new Set([
  'editExecution.package.create',
  'editExecution.boundedAdapterExecutionGate.get',
  'editExecution.boundedAdapterSourceTruthReview.create',
  'editExecution.boundedAdapterExecutionRun.create',
  'editExecution.registeredAdapterRunnerProbe.create',
  'editExecution.registeredAdapterPrivateMediaRunner.create',
  'editExecution.registeredAdapterPrivateMediaRunnerQa.review',
  'editExecution.adapterWorkerArtifactIntegration.create',
  'editExecution.privateInternalTestRun.create',
  'editExecution.jobBatchPlan.create',
  'editExecution.mockQueue.create',
  'editExecution.dispatchReadiness.check',
  'editExecution.mockWorkerClaims.create',
  'editExecution.handlerDryRun.create',
  'editExecution.resultReconciliation.create',
  'editExecution.localWorkerOutput.persist',
  'editExecution.localWorkerOutputQa.review',
  'editExecution.workflowRehearsal.run',
  'editExecution.uploadedMediaWorkerExecution.create',
  'editExecution.privateWorkerArtifactQa.review',
  'editExecution.localMediaProcessingExecution.create',
  'editExecution.privateMediaArtifactQa.review',
  'editExecution.renderPreviewAssembly.create',
  'editExecution.userPreviewReview.create',
  'editExecution.finalRenderReadinessReview.create',
  'editExecution.finalRenderExecution.create',
  'editExecution.finalDeliveryQa.review',
  'editExecution.privateInternalDownloadDelivery.create',
])

const LEGACY_BACKEND_REQUIRED_EDIT_EXECUTION_READ_ROUTE_IDS = new Set([
  'editExecution.package.get',
  'editExecution.privateInternalDownload.file.get',
  'editExecution.privateInternalDownload.manifest.get',
])

export const JOB_API_ROUTES: ApiRouteDefinition[] = RAW_JOB_API_ROUTES.map((route) => {
  if (LEGACY_BACKEND_REQUIRED_EDIT_EXECUTION_READ_ROUTE_IDS.has(route.id)) {
    return {
      ...route,
      runtimeMode: 'backend_required',
      status: 'backend_required',
      notes: [
        ...route.notes,
        'This historical read contract has no deterministic mock handler and is not a deployed browser route. Use the canonical browser-safe private review surfaces.',
      ],
    }
  }

  return LEGACY_MOCK_ONLY_EDIT_EXECUTION_ROUTE_IDS.has(route.id)
    ? {
        ...route,
        runtimeMode: 'mock',
        status: 'mock_ready',
        notes: [
          ...route.notes,
          'This historical execution-stage contract is mock-only. A deployed browser must use the canonical package-request, private-preparation, private-review media, and canonical-decision routes.',
        ],
      }
    : route
})
