import type { ApiRouteDefinition } from '../api-runtime-contracts'

const JOB_FORBIDDEN_SIDE_EFFECTS = [
  'worker execution',
  'Cloud Run/PubSub/Cloud Tasks dispatch',
  'provider calls',
  'rendering',
  'tool execution',
  'media analysis',
  'credit mutation',
  'storage upload/download execution',
  'production queue mutation without transactional backend runtime',
]

function jobRoute(input: Omit<ApiRouteDefinition, 'domain' | 'requiresProviderSecret' | 'requiresStripeSecret' | 'notes'> & { notes?: string[] }): ApiRouteDefinition {
  return {
    ...input,
    domain: 'jobs',
    routeGroup: 'jobs',
    authRequired: true,
    workspaceRequired: true,
    projectRequired: true,
    allowedCaller: input.allowedCaller ?? 'authenticated backend API caller',
    failClosedBehavior: input.failClosedBehavior ?? 'Return backend_required blockers when transactional queue runtime is unavailable.',
    validationLevel: input.validationLevel ?? 'guarded',
    productionReadiness: input.productionReadiness ?? 'backend_required',
    forbiddenSideEffects: input.forbiddenSideEffects ?? JOB_FORBIDDEN_SIDE_EFFECTS,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    notes: [
      'Prompt 8 job routes are route/service boundaries only; they do not execute jobs or workers.',
      ...(input.notes ?? []),
    ],
  }
}

export const JOB_API_ROUTES: ApiRouteDefinition[] = [
  jobRoute({
    id: 'jobs.readiness.check',
    method: 'POST',
    path: '/v1/jobs/readiness',
    description: 'Check job creation and execution gates without creating a job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'jobReadinessSchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_estimates', 'credit_reservations'],
    futureHandlerName: 'checkJobReadiness',
  }),
  jobRoute({
    id: 'jobs.batch.create',
    method: 'POST',
    path: '/v1/job-batches',
    description: 'Prepare a job batch creation boundary from approved snapshot and credit records.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'createJobBatchSchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['job_batches', 'api_idempotency_keys'],
    futureHandlerName: 'createJobBatch',
  }),
  jobRoute({
    id: 'jobs.queue.create',
    method: 'POST',
    path: '/v1/jobs/queue',
    description: 'Prepare a job queue creation boundary without starting work.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'createJobSchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'api_idempotency_keys'],
    futureHandlerName: 'queueJob',
  }),
  jobRoute({
    id: 'jobs.get',
    method: 'GET',
    path: '/v1/jobs/:jobId',
    description: 'Read sanitized job status metadata after project access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'jobReadQuerySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'projects', 'workspace_members'],
    futureHandlerName: 'getJob',
  }),
  jobRoute({
    id: 'jobs.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/jobs',
    description: 'List sanitized project-scoped job summaries.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'listProjectJobsQuerySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'projects', 'workspace_members'],
    futureHandlerName: 'listJobsForProject',
  }),
  jobRoute({
    id: 'jobs.dependencies.create',
    method: 'POST',
    path: '/v1/jobs/:jobId/dependencies',
    description: 'Prepare a dependency creation boundary without mutating job dependency state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'createJobDependencySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['job_dependencies', 'api_idempotency_keys'],
    futureHandlerName: 'createJobDependency',
  }),
  jobRoute({
    id: 'jobs.dependencies.get',
    method: 'GET',
    path: '/v1/jobs/:jobId/dependencies',
    description: 'Read sanitized dependency metadata for a project-scoped job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'jobDependencyQuerySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'job_dependencies', 'projects', 'workspace_members'],
    futureHandlerName: 'getJobDependencies',
  }),
  jobRoute({
    id: 'jobs.events.append',
    method: 'POST',
    path: '/v1/jobs/:jobId/events',
    description: 'Prepare append-only job event payload without writing event state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'appendJobEventSchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['job_events', 'api_idempotency_keys'],
    auditEvent: 'jobs.job_event_append.backend_required',
    futureHandlerName: 'appendJobEvent',
  }),
  jobRoute({
    id: 'jobs.events.list',
    method: 'GET',
    path: '/v1/jobs/:jobId/events',
    description: 'Read sanitized job event timeline after project access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'jobReadQuerySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'job_events', 'projects', 'workspace_members'],
    futureHandlerName: 'listJobEvents',
  }),
  jobRoute({
    id: 'jobs.status.get',
    method: 'GET',
    path: '/v1/jobs/:jobId/status',
    description: 'Read sanitized job status for progress UI.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'jobReadQuerySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'projects', 'workspace_members'],
    futureHandlerName: 'getJobStatus',
  }),
  jobRoute({
    id: 'jobs.retry.schedule',
    method: 'POST',
    path: '/v1/jobs/:jobId/retry',
    description: 'Prepare retry scheduling blockers without mutating job state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'jobRetrySchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'job_events', 'api_idempotency_keys'],
    futureHandlerName: 'scheduleJobRetry',
  }),
  jobRoute({
    id: 'jobs.cancel.request',
    method: 'POST',
    path: '/v1/jobs/:jobId/cancel',
    description: 'Prepare cancellation blockers without mutating job state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'jobCancelSchema',
    outputSchema: 'JobRuntimeResult',
    tablesTouched: ['jobs', 'job_events', 'api_idempotency_keys'],
    futureHandlerName: 'requestJobCancel',
  }),
]
