import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const MEDIA_UPLOAD_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'media.uploadPlan.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload-plan',
    description: 'Validate upload input and create a storage upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleCreateUploadPlan',
    futureHandlerName: 'createUploadPlan',
    notes: ['Does not upload a file. It only validates and builds bucket/path intent.'],
  },
  {
    id: 'media.uploadIntent.create',
    domain: 'media',
    method: 'POST',
    path: '/v1/projects/:projectId/upload-intents',
    description: 'Create an authenticated private upload intent for source media.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createUploadIntent',
    notes: [
      'Reviewed /v1 backend route requires auth and idempotency.',
      'Canonical source truth is bucket/object/checksum metadata; temporary upload targets are not persisted as signed URL source truth.',
    ],
  },
  {
    id: 'media.uploadIntent.localObject.put',
    domain: 'media',
    method: 'PUT',
    path: '/v1/upload-intents/:uploadIntentId/local-object',
    description: 'Upload private source bytes to a local backend upload target for internal testing.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'uploadLocalObject',
    notes: [
      'Reviewed /v1 route accepts raw source bytes only when the backend storage mode is local.',
      'No public artifact, signed delivery URL, tool execution, worker dispatch, or render starts from this upload route.',
    ],
  },
  {
    id: 'media.uploadIntent.finalize',
    domain: 'media',
    method: 'POST',
    path: '/v1/upload-intents/:uploadIntentId/finalize',
    description: 'Finalize an uploaded private source object into canonical storage and media-asset metadata.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'finalizeUploadIntent',
    notes: [
      'Reviewed /v1 backend route verifies size/checksum before creating media-asset metadata.',
      'Finalization records private source metadata only; it does not approve editing, processing, sharing, beta, production, or billing.',
    ],
  },
  {
    id: 'media.storageObject.get',
    domain: 'media',
    method: 'GET',
    path: '/v1/storage-objects/:storageObjectRecordId',
    description: 'Read canonical private storage object metadata for a workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getStorageObjectRecord',
    notes: ['Reviewed /v1 backend route returns canonical bucket/object metadata, not temporary signed URLs.'],
  },
  {
    id: 'media.storageObject.downloadTarget.create',
    domain: 'media',
    method: 'POST',
    path: '/v1/storage-objects/:storageObjectRecordId/download-target',
    description: 'Create a temporary authenticated download target from canonical private storage metadata.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createDownloadTarget',
    notes: [
      'Reviewed /v1 route may create a temporary target, but signed URLs remain event metadata and are never source-of-truth artifacts.',
      'Public delivery, external beta, production, and billing remain separately gated.',
    ],
  },
  {
    id: 'media.storageObject.localObject.get',
    domain: 'media',
    method: 'GET',
    path: '/v1/storage-objects/:storageObjectRecordId/local-object',
    description: 'Stream a private local storage object through authenticated backend transport for internal testing.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createLocalObjectStream',
    notes: [
      'Reviewed /v1 route is local-storage internal testing only.',
      'It does not expose a public object path, signed URL, provider call, worker dispatch, render/export, beta, production, or billing mutation.',
    ],
  },
  {
    id: 'media.upload.validate',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload/validate',
    description: 'Validate upload file metadata and workspace/project context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleValidateUpload',
    futureHandlerName: 'validateUpload',
    notes: ['Validation is local and mock-safe.'],
  },
  {
    id: 'media.sourceSequence.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/source-sequence',
    description: 'Create local source sequence records from upload plans.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSourceSequenceUploadFlow',
    notes: ['Preserves uploaded order as source context, not final edit order.'],
  },
  {
    id: 'media.asset.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/assets',
    description: 'Create a mock media asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMediaAssetCreate',
    notes: ['Mock record only; no database insert occurs.'],
  },
  {
    id: 'media.reference.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/reference-assets',
    description: 'Create a mock reference asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockReferenceAssetCreate',
    notes: ['Mock record only; reference DNA analysis remains separate.'],
  },
]
