import type { ApiRouteDefinition } from '../api-runtime-contracts'

const MEDIA_READINESS_FORBIDDEN_SIDE_EFFECTS = [
  'real user-media processing',
  'FFmpeg/ffprobe execution from route handlers',
  'worker execution or worker claims',
  'job creation or queue mutation',
  'provider calls',
  'rendering or export execution',
  'tool execution',
  'AI transcription/OCR/VLM/audio/visual analysis',
  'credit mutation',
  'storage upload/download execution',
  'approved snapshot mutation',
  'planning/generation execution',
]

function mediaReadinessRoute(
  input: Omit<ApiRouteDefinition, 'domain' | 'requiresProviderSecret' | 'requiresStripeSecret' | 'notes'> & { notes?: string[] },
): ApiRouteDefinition {
  return {
    ...input,
    domain: input.id.startsWith('timing.') ? 'storytiming' : 'media',
    routeGroup: 'media-readiness',
    authRequired: true,
    workspaceRequired: true,
    projectRequired: true,
    allowedCaller: input.allowedCaller ?? 'authenticated backend API caller',
    failClosedBehavior: input.failClosedBehavior ?? 'Return backend_required blockers when media worker/tool/runtime is unavailable.',
    validationLevel: input.validationLevel ?? 'guarded',
    productionReadiness: input.productionReadiness ?? 'backend_required',
    forbiddenSideEffects: input.forbiddenSideEffects ?? MEDIA_READINESS_FORBIDDEN_SIDE_EFFECTS,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    notes: [
      'Prompt 9 media readiness routes are route/service boundaries only; they do not process media or execute workers.',
      ...(input.notes ?? []),
    ],
  }
}

export const MEDIA_READINESS_API_ROUTES: ApiRouteDefinition[] = [
  mediaReadinessRoute({
    id: 'media.readiness.check',
    method: 'POST',
    path: '/v1/media/readiness',
    description: 'Check media, storage, source, transcript, observation, and timing readiness without executing analysis.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets', 'storage_object_records', 'uploaded_clips', 'source_sequence_items'],
    futureHandlerName: 'checkMediaReadiness',
  }),
  mediaReadinessRoute({
    id: 'media.source.get',
    method: 'GET',
    path: '/v1/media-sources/:mediaAssetId',
    description: 'Read sanitized media source metadata after project access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaSourceReadQuerySchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets', 'storage_object_records'],
    futureHandlerName: 'getMediaSource',
  }),
  mediaReadinessRoute({
    id: 'media.source.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/media-sources',
    description: 'List sanitized project-scoped media sources.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaSourceQuerySchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets'],
    futureHandlerName: 'listMediaSourcesForProject',
  }),
  mediaReadinessRoute({
    id: 'media.sourceSequence.readiness',
    method: 'POST',
    path: '/v1/projects/:projectId/source-sequence/readiness',
    description: 'Check source sequence readiness without changing uploaded order or starting planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'sourceSequenceReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'uploaded_clips', 'source_sequence_items'],
    futureHandlerName: 'checkSourceSequenceReadiness',
  }),
  mediaReadinessRoute({
    id: 'media.probe.readiness',
    method: 'POST',
    path: '/v1/media/probe/readiness',
    description: 'Check media probe prerequisites without running ffprobe or creating jobs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaProbeReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets', 'storage_object_records'],
    futureHandlerName: 'checkMediaProbeReadiness',
  }),
  mediaReadinessRoute({
    id: 'media.probe.request',
    method: 'POST',
    path: '/v1/media/probe/request',
    description: 'Validate a future probe request payload without creating a job or executing media tooling.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'mediaProbeRequestSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets', 'storage_object_records', 'api_idempotency_keys'],
    auditEvent: 'media.probe_request.backend_required',
    futureHandlerName: 'requestMediaProbe',
  }),
  mediaReadinessRoute({
    id: 'media.probe.result.get',
    method: 'GET',
    path: '/v1/media/probe-results/:mediaAssetId',
    description: 'Read probe-result placeholder metadata; Prompt 9 produces no persisted probe result.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaProbeResultQuerySchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets', 'storage_object_records'],
    futureHandlerName: 'getMediaProbeResult',
  }),
  mediaReadinessRoute({
    id: 'media.transcript.readiness',
    method: 'POST',
    path: '/v1/media/transcript/readiness',
    description: 'Check transcript alignment readiness without running transcription.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'transcriptReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets', 'storage_object_records'],
    futureHandlerName: 'checkTranscriptReadiness',
  }),
  mediaReadinessRoute({
    id: 'media.transcript.placeholder.get',
    method: 'GET',
    path: '/v1/media/transcript-placeholder/:mediaAssetId',
    description: 'Return transcript placeholder metadata for planning UI without transcription.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'mediaSourceReadQuerySchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets'],
    futureHandlerName: 'getTranscriptPlaceholder',
  }),
  mediaReadinessRoute({
    id: 'media.visualObservation.readiness',
    method: 'POST',
    path: '/v1/media/visual-observation/readiness',
    description: 'Check visual observation readiness without OCR, VLM, object, or face analysis.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'observationReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets', 'storage_object_records'],
    futureHandlerName: 'checkVisualObservationReadiness',
  }),
  mediaReadinessRoute({
    id: 'media.audioObservation.readiness',
    method: 'POST',
    path: '/v1/media/audio-observation/readiness',
    description: 'Check audio observation readiness without audio analysis.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'observationReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['media_assets', 'storage_object_records'],
    futureHandlerName: 'checkAudioObservationReadiness',
  }),
  mediaReadinessRoute({
    id: 'timing.seed.readiness',
    method: 'POST',
    path: '/v1/timing/seed/readiness',
    description: 'Check timing seed prerequisites without creating master timing records.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'timingSeedReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets', 'master_timing_maps'],
    futureHandlerName: 'checkTimingSeedReadiness',
  }),
  mediaReadinessRoute({
    id: 'timing.seed.placeholder.get',
    method: 'GET',
    path: '/v1/timing/seed-placeholder/:projectId',
    description: 'Return timing seed placeholder metadata without persistence.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'timingSeedPlaceholderQuerySchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members'],
    futureHandlerName: 'getTimingSeedPlaceholder',
  }),
  mediaReadinessRoute({
    id: 'timing.validation.readiness',
    method: 'POST',
    path: '/v1/timing/validation/readiness',
    description: 'Check timing validation readiness without running frame-accurate timing QA.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'timingValidationReadinessSchema',
    outputSchema: 'MediaReadinessResult',
    tablesTouched: ['projects', 'workspace_members', 'media_assets', 'master_timing_maps'],
    futureHandlerName: 'checkTimingValidationReadiness',
  }),
]
