import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const MEDIA_UPLOAD_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'media.uploadPlan.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload-plan',
    description: 'Validate upload input and create a storage upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleCreateUploadPlan',
    futureHandlerName: 'createUploadPlan',
    notes: ['Does not upload a file. It only validates and builds bucket/path intent.'],
  },
  {
    id: 'media.upload.validate',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload/validate',
    description: 'Validate upload file metadata and workspace/project context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleValidateUpload',
    futureHandlerName: 'validateUpload',
    notes: ['Validation is local and mock-safe.'],
  },
  {
    id: 'media.sourceSequence.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/source-sequence',
    description: 'Create local source sequence records from upload plans.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSourceSequenceUploadFlow',
    notes: ['Preserves uploaded order as source context, not final edit order.'],
  },
  {
    id: 'media.asset.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/assets',
    description: 'Create a mock media asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMediaAssetCreate',
    notes: ['Mock record only; no database insert occurs.'],
  },
  {
    id: 'media.reference.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/reference-assets',
    description: 'Create a mock reference asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockReferenceAssetCreate',
    notes: ['Mock record only; reference DNA analysis remains separate.'],
  },
]
