import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const MEDIA_UPLOAD_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'media.sourceUpload.plan',
    domain: 'media',
    method: 'POST',
    path: '/v1/projects/:projectId/upload-intents',
    description: 'Plan a private source media upload through the backend-gated storage upload intent route.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createUploadIntent',
    notes: [
      'Media upload planning is an alias for storage.uploadIntent.create when uploadPurpose is source_media.',
      'It must not start transcript, media probe, visual observation, planning, credits, jobs, providers, rendering, or tools.',
    ],
  },
  {
    id: 'media.sourceUpload.finalize',
    domain: 'media',
    method: 'POST',
    path: '/v1/upload-intents/:uploadIntentId/finalize',
    description: 'Finalize source media upload boundary records after backend validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'finalizeUploadIntent',
    notes: [
      'Creates canonical storage/source media boundary records only.',
      'No media analysis, transcript alignment, source sequence mutation after approval, planning, credits, jobs, workers, providers, rendering, or tools are enabled.',
    ],
  },
  {
    id: 'media.sourceSequence.preview',
    domain: 'media',
    method: 'GET',
    path: '/v1/projects/:projectId/source-sequence/preview',
    description: 'Preview upload-order source sequence metadata without starting analysis or planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'previewSourceSequence',
    notes: [
      'Future route only; source order preview must remain read-only and must not trigger edit planning.',
      'Blocked until storage/upload schema validation and media boundary cleanup are complete.',
    ],
  },
  {
    id: 'media.uploadPlan.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload-plan',
    description: 'Validate upload input and create a storage upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleCreateUploadPlan',
    futureHandlerName: 'createUploadPlan',
    notes: ['Does not upload a file. It only validates and builds bucket/path intent.', 'Legacy mock-safe helper; production upload intent creation uses media.sourceUpload.plan/storage.uploadIntent.create.'],
  },
  {
    id: 'media.upload.validate',
    domain: 'media',
    method: 'POST',
    path: '/api/media/upload/validate',
    description: 'Validate upload file metadata and workspace/project context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleValidateUpload',
    futureHandlerName: 'validateUpload',
    notes: ['Validation is local and mock-safe.', 'Does not write upload intents, storage object records, or media records.'],
  },
  {
    id: 'media.sourceSequence.create',
    domain: 'media',
    method: 'POST',
    path: '/api/media/source-sequence',
    description: 'Create local source sequence records from upload plans.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSourceSequenceUploadFlow',
    notes: ['Preserves uploaded order as source context, not final edit order.', 'Mock-only; production source sequence creation remains blocked outside Prompt 4 route/service boundary.'],
  },
  {
    id: 'media.asset.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/assets',
    description: 'Create a mock media asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMediaAssetCreate',
    notes: ['Mock record only; no database insert occurs.'],
  },
  {
    id: 'media.reference.mockCreate',
    domain: 'media',
    method: 'POST',
    path: '/api/mock/media/reference-assets',
    description: 'Create a mock reference asset record from an upload plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockReferenceAssetCreate',
    notes: ['Mock record only; reference DNA analysis remains separate.'],
  },
]
