import type { ApiRouteDefinition } from '../api-runtime-contracts'

const common = {
  domain: 'motion_studio' as const,
  securityLevel: 'workspace_editor' as const,
  runtimeMode: 'frontend_safe' as const,
  status: 'frontend_safe_ready' as const,
  requiresSupabase: true,
  requiresServiceRole: false,
  requiresProviderSecret: false,
  requiresStripeSecret: false,
}

export const MOTION_STUDIO_API_ROUTES: ApiRouteDefinition[] = [
  {
    ...common,
    id: 'motionStudio.production.create',
    method: 'POST',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/motion-studio',
    description: 'Create one explicitly selected active Motion Studio module production on an existing named edit.',
    futureHandlerName: 'createMotionStudioProduction',
    notes: ['Catalog v1 accepts Storytelling only; creation has no provider, worker, render, billing, or customer-price authority.'],
  },
  {
    ...common,
    id: 'motionStudio.production.get',
    method: 'GET',
    path: '/v1/projects/:projectId/edit-sessions/:editSessionId/motion-studio',
    description: 'Read one Motion Studio production through the authenticated backend.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioProduction',
    notes: ['Returns a safe DTO and never exposes workspace authority or service credentials.'],
  },
  {
    ...common,
    id: 'motionStudio.artifactVersion.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/artifact-versions',
    description: 'Create one initial immutable Motion Studio artifact version.',
    futureHandlerName: 'createMotionStudioArtifactVersion',
    notes: ['Actor, timestamps, hashes, and immutable digest authority are server/database derived.'],
  },
  {
    ...common,
    id: 'motionStudio.artifact.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/artifacts/:artifactId',
    description: 'Read exact current Motion Studio artifact-version and approval identities.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioArtifact',
    notes: ['Readback is exact-version metadata and safe structured payload only.'],
  },
  {
    ...common,
    id: 'motionStudio.command.apply',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/artifacts/:artifactId/commands',
    description: 'Compile and atomically apply one exact-base Motion Studio command.',
    futureHandlerName: 'applyMotionStudioCommand',
    notes: ['The browser supplies intent only; server compilation and database CAS remain authoritative.'],
  },
  {
    ...common,
    id: 'motionStudio.artifact.approve',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/artifacts/:artifactId/approvals',
    description: 'Approve one exact in-review artifact through shared plan-and-credit snapshot authority.',
    futureHandlerName: 'approveMotionStudioArtifact',
    notes: ['This reuses approval_records and approved_plan_snapshots; no parallel approval authority exists.'],
  },
  {
    ...common,
    id: 'motionStudio.workGraph.authorize',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/work-graph-authorizations',
    description: 'Derive one durable work graph from an exact approved snapshot and authorized internal-cost estimate.',
    futureHandlerName: 'authorizeMotionStudioWorkGraph',
    notes: ['The browser supplies only exact authority IDs; jobs, dependencies, scope, budgets, and payloads are server/database derived.'],
  },
  {
    ...common,
    id: 'motionStudio.workGraph.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/work-graph',
    description: 'Read the browser-safe durable work-graph projection without worker credentials or internal cost amounts.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioWorkGraph',
    notes: ['Opaque lease IDs, nonces, hashes, worker identities, payloads, and raw budget events are omitted.'],
  },
  {
    ...common,
    id: 'motionStudio.sceneWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/scene-workspace',
    description: 'Read exact scene artifact summaries, deterministic proposal history, and readiness blockers.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioSceneWorkspace',
    notes: ['No raw worker, provider, credential, customer-price, or renderer authority crosses this projection.'],
  },
  {
    ...common,
    id: 'motionStudio.researchWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/research-workspace',
    description: 'Read one sanitized Storytelling Research workspace with exact source, claim, chronology, visual-coverage, rights, and Technique Blueprint review state.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioResearchWorkspace',
    notes: ['Raw source locators, excerpts, source instructions, provider data, costs, credentials, signed URLs, and write authority remain service-only.'],
  },
  {
    ...common,
    id: 'motionStudio.storyWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/story-workspace',
    description: 'Read the exact current Story Bible and Prepared Script as one browser-safe, read-only Story workspace.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioStoryWorkspace',
    notes: ['Changes return through Chat; this projection cannot approve, spend, generate, mutate the timeline, render, export, or deliver.'],
  },
  {
    ...common,
    id: 'motionStudio.storytellingStylePlanPreparation.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/storytelling-style-plan-preparations',
    description: 'Compile one explicit Chat-authored Storytelling motion direction into the existing Plan Review and approved-snapshot authority.',
    futureHandlerName: 'prepareStorytellingMotionStylePlan',
    notes: ['Creates or reuses planning-only Motion DNA. It cannot approve, call a provider, spend credits, generate, render, export, or deliver.'],
  },
  {
    ...common,
    id: 'motionStudio.storyContinuityPreparation.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/story-continuity-preparations',
    description: 'Validate one cross-scene story arc, recurring motif, reveal, transition, and rhythm proposal against exact approved Storytelling authority and version it inside Motion DNA.',
    futureHandlerName: 'prepareStorytellingStoryContinuity',
    notes: ['Uses the existing Motion DNA command/version path and Plan Review. It cannot approve, call providers or tools, spend credits, render, export, or deliver.'],
  },
  {
    ...common,
    id: 'motionStudio.canonicalStorytellingPlanningPreparation.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/canonical-storytelling-planning-preparations',
    description: 'Re-read the exact approved Prepared Script, SceneDocuments, Voice Bible, style, timing, and internal-cost ceiling before canonical idea-first Storytelling planning.',
    futureHandlerName: 'prepareCanonicalStorytellingPlanning',
    notes: ['Controlled-local, source-verified and fail-closed. It creates no upload, approval, provider request, queue claim, render, credit mutation, billing action, deployment, or delivery.'],
  },
  {
    ...common,
    id: 'motionStudio.audioWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/audio-workspace',
    description: 'Read the exact review-only Storytelling voice, music, cue, stem, and mix authority.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioAudioWorkspace',
    notes: ['No browser write, provider/media execution, prompt, secret, raw payload, internal-cost amount, customer price, credit, timeline, render, or delivery authority crosses this projection.'],
  },
  {
    ...common,
    id: 'motionStudio.voiceCastingWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/voice-casting-workspace',
    description: 'Read browser-safe narrator names and traits plus the exact editable Voice Bible planning state.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioVoiceCastingWorkspace',
    notes: ['Provider voice IDs, preview URLs, credentials, private catalog evidence, provider execution, plan approval, credits, and customer pricing remain server-only or absent.'],
  },
  {
    ...common,
    id: 'motionStudio.voiceCastingSelection.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/voice-casting-selections',
    description: 'Apply one explicit narrator planning choice to the exact current Voice Bible draft through canonical command/CAS authority.',
    futureHandlerName: 'selectMotionStudioNarratorForPlanning',
    notes: ['This creates a Voice Bible draft version only; it does not approve a plan, call a provider, generate speech, mutate credits, render, export, or deliver.'],
  },
  {
    ...common,
    id: 'motionStudio.audioMixWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/audio-mix-workspace',
    description: 'Read exact private Storytelling audio-mix bindings, resumable job state, QA, and review-only artifact metadata.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioAudioMixWorkspace',
    notes: ['Worker credentials, upload authority, private object identities, raw bytes, provider cost, customer price, credits, timeline, render, and public delivery remain omitted.'],
  },
  {
    ...common,
    id: 'motionStudio.audioSelection.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/audio-selections',
    description: 'Persist one explicit human audio selection after canonical candidate, review, QA, rights, cost, snapshot, and timing revalidation.',
    futureHandlerName: 'createMotionStudioAudioSelection',
    notes: ['The browser supplies candidate decisions only. The server compiles immutable evidence and never auto-selects, mixes, charges, mutates the timeline, renders, exports, or delivers from selection alone.'],
  },
  {
    ...common,
    id: 'motionStudio.audioIntegrationBinding.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/audio-integration-bindings',
    description: 'Bind one current immutable audio selection to the canonical narration-assembly then integrated-mix durable work graph.',
    futureHandlerName: 'createMotionStudioAudioIntegrationBinding',
    notes: ['The canonical backend revalidates the exact selection and existing reservation, then creates only the two approved jobs in the one package queue; no provider, timeline, mux, render, export, billing, or public-delivery authority is added.'],
  },
  {
    ...common,
    id: 'motionStudio.audioMixBinding.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/audio-mix-bindings',
    description: 'Bind four exact finalized private PCM uploads to one approved speech-safe mix plan and durable local job.',
    futureHandlerName: 'createMotionStudioAudioMixBinding',
    notes: ['The backend re-verifies finalized media bytes, approved cue/rights authority, work, lease, and bounded internal CPU cost before execution.'],
  },
  {
    ...common,
    id: 'motionStudio.audioMixArtifact.read',
    method: 'GET',
    path: '/v1/motion-studio/audio-mix-artifacts/:artifactId/content',
    description: 'Read checksum-verified private PCM WAV mix bytes through owner-scoped bearer authentication.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'readMotionStudioPrivateAudioMixArtifact',
    notes: ['Returns private review bytes only; no filesystem path, signed URL, object identity, timeline, final-export, or public delivery authority.'],
  },
  {
    ...common,
    id: 'motionStudio.audioCandidate.read',
    method: 'GET',
    path: '/v1/motion-studio/audio-candidates/:candidateReference/content',
    description: 'Read one checksum-verified private music or synchronized-sound candidate after exact canonical runtime and current-review-context verification.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'readMotionStudioPrivateAudioCandidate',
    notes: ['The mounted handler remains fail-closed until a released canonical review-reader adapter projects the exact current candidate; it returns no provider, queue, cost, path, signed URL, selection, mix, timeline, render, or delivery authority.'],
  },
  {
    ...common,
    id: 'motionStudio.generationWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/generation-workspace',
    description: 'Read exact generated-media bindings, provider-protocol state, and private review-candidate metadata.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioGenerationWorkspace',
    notes: ['Projection is protocol-simulator-only and omits credentials, private object identities, paths, raw internal costs, and provider secrets.'],
  },
  {
    ...common,
    id: 'motionStudio.liveGenerationWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/live-generation-workspace',
    description: 'Read owner-scoped real-provider lifecycle, immutable private media facts, and human-review state.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioLiveGenerationWorkspace',
    notes: ['Excludes provider identities, adapter details, credentials, raw payloads, temporary URLs, internal costs, customer price, and billing authority.'],
  },
  {
    ...common,
    id: 'motionStudio.liveCandidateReview.create',
    method: 'POST',
    path: '/v1/motion-studio/live-candidates/:candidateId/human-reviews',
    description: 'Record one explicit owner review while the backend derives technical evidence, QA artifact lineage, approval, and conditional fallback authority.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'reviewMotionStudioLiveCandidate',
    notes: ['The browser authors only human assessments, decision, category, and notes; it cannot author technical QA, provider usage, costs, fallback IDs, or submission authority.'],
  },
  {
    ...common,
    id: 'motionStudio.generationBinding.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/generation-bindings',
    description: 'Compile and bind one exact approved scene/proposal to an existing approved generated-media simulator job.',
    futureHandlerName: 'createMotionStudioGenerationBinding',
    notes: ['The server derives ShotSpec, tier routing, exact timing, deterministic-overlay exclusions, work authority, and cost authority.'],
  },
  {
    ...common,
    id: 'motionStudio.generatedMedia.read',
    method: 'GET',
    path: '/v1/motion-studio/media-asset-versions/:assetVersionId/content',
    description: 'Read checksum-verified private PNG or MP4 simulator or live-candidate bytes through owner-scoped bearer authentication.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'readMotionStudioPrivateGeneratedMedia',
    notes: ['Returns private review bytes only; no provider output, path, signed URL, credential, final-export authority, or public delivery URL.'],
  },
  {
    ...common,
    id: 'motionStudio.previewWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/preview-workspace',
    description: 'Read immutable private preview bindings, truthful durable-job state, and passed artifact metadata.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioPreviewWorkspace',
    notes: ['Private object identities, paths, worker credentials, internal cost amounts, and service authority are omitted.'],
  },
  {
    ...common,
    id: 'motionStudio.renderBinding.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/render-bindings',
    description: 'Bind one exact approved SceneDocument and timeline proposal to an existing approved preview job.',
    futureHandlerName: 'createMotionStudioRenderBinding',
    notes: ['The backend derives timing, dimensions, registered composition props, work authority, and cost authority.'],
  },
  {
    ...common,
    id: 'motionStudio.layeredWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/layered-workspace',
    description: 'Read immutable four-plane assemblies, durable cutout/render states, and safe private artifact metadata.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioLayeredWorkspace',
    notes: ['Private object identities, bytes, paths, credentials, raw cost, layer code, and customer pricing remain server-only.'],
  },
  {
    ...common,
    id: 'motionStudio.layeredAssembly.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/layered-assemblies',
    description: 'Derive one immutable fixed-fixture four-plane assembly from exact approved scene, proposal, dependency, and job authority.',
    futureHandlerName: 'createMotionStudioLayeredAssembly',
    notes: ['The browser supplies exact existing identities only; layer definitions, media, render props, worker payloads, and cost quantities are server-derived.'],
  },
  {
    ...common,
    id: 'motionStudio.animaticWorkspace.get',
    method: 'GET',
    path: '/v1/motion-studio/productions/:productionId/animatic-workspace',
    description: 'Read prepared-script animatic assemblies, immutable bindings, durable status, and private artifact metadata.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'getMotionStudioAnimaticWorkspace',
    notes: ['No uploaded bytes, private object identities, worker credentials, raw internal cost, or public URLs cross this projection.'],
  },
  {
    ...common,
    id: 'motionStudio.animaticAssembly.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/animatic-assemblies',
    description: 'Compile review-only Voice Bible, storyboard, and animatic candidates from exact approved script, scene, timing, and uploaded narration authority.',
    futureHandlerName: 'assembleMotionStudioAnimatic',
    notes: ['The backend reads committed narration bytes and derives all candidate payloads; placeholders remain final-ineligible.'],
  },
  {
    ...common,
    id: 'motionStudio.animaticBinding.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/animatic-bindings',
    description: 'Bind exact approved prepared-script, voice, storyboard, and animatic versions to one authorized animatic job.',
    futureHandlerName: 'createMotionStudioAnimaticBinding',
    notes: ['Frame, scene, narration, registered profile, work-item, and internal-cost authority are server/database derived.'],
  },
  {
    ...common,
    id: 'motionStudio.animaticArtifact.read',
    method: 'GET',
    path: '/v1/motion-studio/animatic-artifacts/:artifactId/content',
    description: 'Read checksum-verified private prepared animatic MP4 bytes through owner-scoped bearer authentication.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'readMotionStudioPrivateAnimaticArtifact',
    notes: ['Returns bytes only; no filesystem path, signed URL, object identity, worker credential, or final-export authority.'],
  },
  {
    ...common,
    id: 'motionStudio.previewArtifact.read',
    method: 'GET',
    path: '/v1/motion-studio/preview-artifacts/:artifactId/content',
    description: 'Read checksum-verified private preview MP4 bytes through owner-scoped bearer authentication.',
    securityLevel: 'workspace_member',
    futureHandlerName: 'readMotionStudioPrivatePreviewArtifact',
    notes: ['Returns bytes, never a filesystem path, signed URL, object identity, worker credential, or public delivery URL.'],
  },
  {
    ...common,
    id: 'motionStudio.sceneDraft.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/scene-drafts',
    description: 'Author one exact Scene Graph, LayerPlan, Scene Recipe, SceneDocument, and frozen recipe instantiation.',
    futureHandlerName: 'createMotionStudioSceneDraft',
    notes: ['Requires an immutable approved snapshot and exact Motion Language/Narrative Function versions.'],
  },
  {
    ...common,
    id: 'motionStudio.timelineProposal.create',
    method: 'POST',
    path: '/v1/motion-studio/productions/:productionId/timeline-proposals',
    description: 'Compile and persist deterministic proposal operations against the existing TimelineManifest.',
    futureHandlerName: 'createMotionStudioTimelineProposal',
    notes: ['Proposal-only; does not mutate timeline authority, render media, dispatch workers, or call providers.'],
  },
  {
    ...common,
    id: 'motionStudio.job.cancel',
    method: 'POST',
    path: '/v1/motion-studio/jobs/:jobId/cancellation',
    description: 'Request cancellation while preserving incurred cost and releasing only unused internal authorization.',
    futureHandlerName: 'cancelMotionStudioJob',
    notes: ['Running work enters cancel_requested until the exact lease acknowledges cancellation.'],
  },
]
