import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const MUSIC_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'music.creditGate.check',
    domain: 'music',
    method: 'POST',
    path: '/api/music/credit-gate',
    description: 'Check whether music generation can pass the credit gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockGenerationCreditGate',
    futureHandlerName: 'checkMusicGenerationCreditGate',
    notes: ['Does not call music providers.'],
  },
  {
    id: 'music.jobRuntime.queueMock',
    domain: 'music',
    method: 'POST',
    path: '/api/music/jobs/mock',
    description: 'Queue and optionally dispatch a mock music worker job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicJobRuntime',
    futureHandlerName: 'queueMusicWorkerJob',
    notes: ['Uses local mock Lyria worker skeleton only; no Lyria API is called.'],
  },
  {
    id: 'music.directorPlan.create',
    domain: 'music',
    method: 'POST',
    path: '/api/music/director-plan',
    description: 'Create a mock SoundSync music director plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicPlan',
    notes: ['Planning only; no music provider call.'],
  },
  {
    id: 'music.cueSheet.create',
    domain: 'music',
    method: 'POST',
    path: '/api/music/cue-sheet',
    description: 'Create a mock reference-to-music cue sheet.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicPlan',
    notes: ['Uses deterministic reference-DNA mock planning only.'],
  },
  {
    id: 'music.lyriaPrompt.create',
    domain: 'music',
    method: 'POST',
    path: '/api/music/prompt-plan',
    description: 'Create a mock music prompt plan without provider execution.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicPlan',
    notes: ['Prompt planning remains local and does not call a music API.'],
  },
  {
    id: 'music.qa.run',
    domain: 'music',
    method: 'POST',
    path: '/api/music/qa',
    description: 'Run mock music QA checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicQA',
    notes: ['No real audio analysis is performed.'],
  },
  {
    id: 'music.mixPlan.create',
    domain: 'music',
    method: 'POST',
    path: '/api/music/mix-plan',
    description: 'Create a mock music mix plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicMixPlan',
    notes: ['No real audio mixing is performed.'],
  },
]
