import type { ApiRouteDefinition, ApiRouteSecurityLevel, ApiRouteStatus } from '../api-runtime-contracts'

const OBSERVABILITY_FORBIDDEN_SIDE_EFFECTS = [
  'No external telemetry integration or alert transport',
  'No production audit persistence',
  'No production rate-limit enforcement or persistence',
  'No abuse-prevention enforcement or persistence',
  'No paid billing, Stripe checkout, webhooks, or payment processing',
  'No provider calls or provider secret reads',
  'No tool, worker, render, export, media, storage, credit, or job execution',
  'No Cloud Run, Pub/Sub, Cloud Tasks, deployment, or remote Supabase execution',
  'No production, beta, broad-media, or admin override unlock',
]

function observabilityRoute(input: {
  id: string
  method: ApiRouteDefinition['method']
  path: string
  description: string
  routeGroup: string
  inputSchema: string
  outputSchema: string
  futureHandlerName: string
  status?: ApiRouteStatus
  securityLevel?: ApiRouteSecurityLevel
  productionReadiness?: ApiRouteDefinition['productionReadiness']
  idempotencyRequired?: boolean
  workspaceRequired?: boolean
  projectRequired?: boolean
  auditEvent?: string
  notes?: string[]
}): ApiRouteDefinition {
  const productionReadiness = input.productionReadiness ?? 'backend_required'
  return {
    id: input.id,
    domain: 'observability',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: input.securityLevel ?? 'workspace_member',
    runtimeMode: 'backend_required',
    status: input.status ?? 'backend_required',
    requiresSupabase: productionReadiness !== 'implemented',
    requiresServiceRole: productionReadiness !== 'implemented',
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: input.futureHandlerName,
    routeGroup: input.routeGroup,
    authRequired: true,
    workspaceRequired: input.workspaceRequired ?? true,
    projectRequired: Boolean(input.projectRequired),
    idempotencyRequired: Boolean(input.idempotencyRequired),
    serviceRoleRequired: productionReadiness !== 'implemented',
    allowedCaller: 'authenticated backend API caller',
    inputSchema: input.inputSchema,
    outputSchema: input.outputSchema,
    tablesTouched: [
      'workspaces',
      'projects',
      'audit_events',
      'backend_runtime_messages',
      'api_idempotency_keys',
      'job_events',
      'provider_request_attempts',
      'worker_job_claims',
      'worker_leases',
      'signed_url_events',
      'rate_limit_events',
      'abuse_prevention_events',
      'usage_metering_records',
      'cost_control_records',
      'operational_alert_records',
      'runtime_health_snapshots',
      'audit_event_summaries',
    ],
    forbiddenSideEffects: OBSERVABILITY_FORBIDDEN_SIDE_EFFECTS,
    auditEvent: input.auditEvent,
    failClosedBehavior: 'Return static summaries or backend_required/blocker results until reviewed audit/rate-limit/abuse/cost-control persistence exists.',
    validationLevel: 'guarded',
    productionReadiness,
    notes: [
      'Prompt 17 operational safety boundary only; not external telemetry, enforcement, billing, or production unlock.',
      ...(input.notes ?? []),
    ],
  }
}

export const OBSERVABILITY_API_ROUTES: ApiRouteDefinition[] = [
  observabilityRoute({
    id: 'observability.readiness.check',
    method: 'POST',
    path: '/v1/observability/readiness',
    description: 'Check observability/audit/rate-limit/cost-control readiness and blockers.',
    routeGroup: 'observability',
    inputSchema: 'observabilityReadinessSchema',
    outputSchema: 'ObservabilityResult',
    futureHandlerName: 'checkObservabilityReadiness',
    idempotencyRequired: true,
    auditEvent: 'observability.readiness_checked',
  }),
  observabilityRoute({
    id: 'observability.runtime.status',
    method: 'GET',
    path: '/v1/observability/runtime-status',
    description: 'Return safe static runtime and route summary without external telemetry.',
    routeGroup: 'observability',
    inputSchema: 'observabilityRuntimeStatusQuerySchema',
    outputSchema: 'ObservabilityResult.runtime',
    futureHandlerName: 'getObservabilityRuntimeStatus',
    productionReadiness: 'implemented',
    workspaceRequired: false,
    notes: ['Static summary only; no telemetry is sent and no persistence is read.'],
  }),
  observabilityRoute({
    id: 'observability.requestTrace.get',
    method: 'GET',
    path: '/v1/observability/request-traces/:requestId',
    description: 'Return current request trace summary or backend_required for historical trace lookup.',
    routeGroup: 'request_trace',
    inputSchema: 'observabilityRequestTraceQuerySchema + requestId',
    outputSchema: 'ObservabilityResult.requestTrace',
    futureHandlerName: 'getRequestTraceBoundary',
    productionReadiness: 'backend_required',
    workspaceRequired: false,
  }),
  observabilityRoute({
    id: 'observability.routeRisk.summary',
    method: 'GET',
    path: '/v1/observability/route-risk-summary',
    description: 'Summarize static route risk from API route metadata.',
    routeGroup: 'route_risk',
    inputSchema: 'observabilityRouteRiskSummaryQuerySchema',
    outputSchema: 'ObservabilityResult.routeRisk',
    futureHandlerName: 'getRouteRiskSummary',
    productionReadiness: 'implemented',
    workspaceRequired: false,
    notes: ['Uses static route metadata only.'],
  }),
  observabilityRoute({
    id: 'audit.event.preview',
    method: 'POST',
    path: '/v1/audit/event/preview',
    description: 'Preview a sanitized audit event payload without writing it.',
    routeGroup: 'audit',
    inputSchema: 'auditEventPreviewSchema',
    outputSchema: 'ObservabilityResult.audit',
    futureHandlerName: 'previewAuditEvent',
    idempotencyRequired: true,
    auditEvent: 'audit.event_previewed',
  }),
  observabilityRoute({
    id: 'audit.event.createBoundary',
    method: 'POST',
    path: '/v1/audit/event/create-boundary',
    description: 'Fail-closed boundary for future append-only audit event creation.',
    routeGroup: 'audit',
    inputSchema: 'auditEventCreateBoundarySchema',
    outputSchema: 'ObservabilityResult.audit',
    futureHandlerName: 'createAuditEventBoundary',
    idempotencyRequired: true,
    auditEvent: 'audit.event_create_boundary',
  }),
  observabilityRoute({
    id: 'audit.event.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/audit-events',
    description: 'Boundary for future project-scoped audit event listing.',
    routeGroup: 'audit',
    inputSchema: 'auditEventListForProjectQuerySchema + projectId',
    outputSchema: 'ObservabilityResult.audit',
    futureHandlerName: 'listAuditEventsForProject',
    projectRequired: true,
  }),
  observabilityRoute({
    id: 'audit.event.listForWorkspace',
    method: 'GET',
    path: '/v1/workspaces/:workspaceId/audit-events',
    description: 'Boundary for future workspace-scoped audit event listing.',
    routeGroup: 'audit',
    inputSchema: 'auditEventListForWorkspaceQuerySchema + workspaceId',
    outputSchema: 'ObservabilityResult.audit',
    futureHandlerName: 'listAuditEventsForWorkspace',
  }),
  observabilityRoute({
    id: 'audit.summary.get',
    method: 'GET',
    path: '/v1/audit/summary',
    description: 'Boundary for future audit summary aggregates.',
    routeGroup: 'audit',
    inputSchema: 'auditSummaryQuerySchema',
    outputSchema: 'ObservabilityResult.audit',
    futureHandlerName: 'getAuditSummary',
    workspaceRequired: false,
  }),
  observabilityRoute({
    id: 'rateLimit.readiness.check',
    method: 'POST',
    path: '/v1/rate-limit/readiness',
    description: 'Check rate-limit readiness without enforcing limits.',
    routeGroup: 'rate_limit',
    inputSchema: 'rateLimitReadinessSchema',
    outputSchema: 'ObservabilityResult.rateLimit',
    futureHandlerName: 'checkRateLimitReadiness',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'rateLimit.policy.preview',
    method: 'POST',
    path: '/v1/rate-limit/policy/preview',
    description: 'Preview a static rate-limit policy without persistence or enforcement.',
    routeGroup: 'rate_limit',
    inputSchema: 'rateLimitPolicyPreviewSchema',
    outputSchema: 'ObservabilityResult.rateLimit',
    futureHandlerName: 'previewRateLimitPolicy',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'rateLimit.checkBoundary',
    method: 'POST',
    path: '/v1/rate-limit/check-boundary',
    description: 'Fail-closed boundary for future persisted rate-limit checks.',
    routeGroup: 'rate_limit',
    inputSchema: 'rateLimitCheckBoundarySchema',
    outputSchema: 'ObservabilityResult.rateLimit',
    futureHandlerName: 'checkRateLimitBoundary',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'abuse.readiness.check',
    method: 'POST',
    path: '/v1/abuse/readiness',
    description: 'Check abuse-prevention readiness without enforcement.',
    routeGroup: 'abuse_prevention',
    inputSchema: 'abuseReadinessSchema',
    outputSchema: 'ObservabilityResult.abuse',
    futureHandlerName: 'checkAbuseReadiness',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'abuse.policy.preview',
    method: 'POST',
    path: '/v1/abuse/policy/preview',
    description: 'Preview abuse-prevention policy signals without persistence or blocking.',
    routeGroup: 'abuse_prevention',
    inputSchema: 'abusePolicyPreviewSchema',
    outputSchema: 'ObservabilityResult.abuse',
    futureHandlerName: 'previewAbusePolicy',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'abuse.checkBoundary',
    method: 'POST',
    path: '/v1/abuse/check-boundary',
    description: 'Fail-closed boundary for future abuse checks.',
    routeGroup: 'abuse_prevention',
    inputSchema: 'abuseCheckBoundarySchema',
    outputSchema: 'ObservabilityResult.abuse',
    futureHandlerName: 'checkAbuseBoundary',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'costControl.readiness.check',
    method: 'POST',
    path: '/v1/cost-control/readiness',
    description: 'Check cost-control readiness without billing or credit mutation.',
    routeGroup: 'cost_control',
    inputSchema: 'costControlReadinessSchema',
    outputSchema: 'ObservabilityResult.cost',
    futureHandlerName: 'checkCostControlReadiness',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'costControl.policy.preview',
    method: 'POST',
    path: '/v1/cost-control/policy/preview',
    description: 'Preview cost-control policy without enforcement or billing.',
    routeGroup: 'cost_control',
    inputSchema: 'costControlPolicyPreviewSchema',
    outputSchema: 'ObservabilityResult.cost',
    futureHandlerName: 'previewCostControlPolicy',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'costControl.usageSummary.preview',
    method: 'POST',
    path: '/v1/cost-control/usage-summary/preview',
    description: 'Preview usage/cost summary from request metadata only.',
    routeGroup: 'cost_control',
    inputSchema: 'costControlUsageSummaryPreviewSchema',
    outputSchema: 'ObservabilityResult.usage',
    futureHandlerName: 'previewUsageSummary',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'costControl.executionBlocked',
    method: 'POST',
    path: '/v1/cost-control/execution-blocked',
    description: 'Explicitly report cost-control execution as blocked.',
    routeGroup: 'cost_control',
    inputSchema: 'costControlExecutionBlockedSchema',
    outputSchema: 'ObservabilityResult.cost',
    futureHandlerName: 'reportCostControlExecutionBlocked',
    idempotencyRequired: true,
    productionReadiness: 'blocked',
    status: 'disabled',
  }),
  observabilityRoute({
    id: 'operationalAlert.readiness.check',
    method: 'POST',
    path: '/v1/operational-alert/readiness',
    description: 'Check operational alert readiness without sending alerts.',
    routeGroup: 'operational_alert',
    inputSchema: 'operationalAlertReadinessSchema',
    outputSchema: 'ObservabilityResult.operationalAlert',
    futureHandlerName: 'checkOperationalAlertReadiness',
    idempotencyRequired: true,
  }),
  observabilityRoute({
    id: 'operationalAlert.preview',
    method: 'POST',
    path: '/v1/operational-alert/preview',
    description: 'Preview an operational alert payload without persistence or external transport.',
    routeGroup: 'operational_alert',
    inputSchema: 'operationalAlertPreviewSchema',
    outputSchema: 'ObservabilityResult.operationalAlert',
    futureHandlerName: 'previewOperationalAlert',
    idempotencyRequired: true,
  }),
]
