import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const PROJECT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'projects.list',
    domain: 'projects',
    method: 'GET',
    path: '/api/projects',
    description: 'List projects for the current workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listProjects',
    notes: ['Future route should respect workspace membership and project RLS.'],
  },
  {
    id: 'projects.get',
    domain: 'projects',
    method: 'GET',
    path: '/api/projects/:projectId',
    description: 'Get one project with workspace ownership context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getProject',
    notes: ['Future route should never bypass project membership checks in frontend code.'],
  },
  {
    id: 'projects.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/projects',
    description: 'Create a project in a workspace.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProject',
    notes: ['Real project creation needs audited workspace membership and may need backend writes.'],
  },
  {
    id: 'projects.update',
    domain: 'projects',
    method: 'PATCH',
    path: '/api/projects/:projectId',
    description: 'Update project metadata.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'updateProject',
    notes: ['Real route should keep RLS and audit history authoritative.'],
  },
  {
    id: 'projects.chatSession.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/projects/:projectId/chat-sessions',
    description: 'Create a chat session for a project.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProjectChatSession',
    notes: ['Mock chat-native planning creates local sessions without real persistence.'],
  },
  {
    id: 'projects.demo.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/mock/projects/demo',
    description: 'Create a local mock project through the chat-native planning flow.',
    securityLevel: 'public',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Local mock route only; no database, provider, worker, or render call occurs.'],
  },
]
