import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const PROJECT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'projects.list',
    domain: 'projects',
    method: 'GET',
    path: '/api/projects',
    description: 'List projects for the current workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listProjects',
    notes: ['Future route should respect workspace membership and project RLS.'],
  },
  {
    id: 'projects.get',
    domain: 'projects',
    method: 'GET',
    path: '/v1/projects/:projectId',
    description: 'Get one project with workspace ownership context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getProject',
    notes: ['Prompt 3 route returns a project only after checking canonical workspace_members membership.'],
  },
  {
    id: 'projects.create',
    domain: 'projects',
    method: 'POST',
    path: '/v1/projects',
    description: 'Disabled broad project creation compatibility route.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProject',
    notes: [
      'Prompt 3A keeps this route fail-closed and performs no project-create body validation or database write.',
      'Project creation needs a later scoped prompt.',
    ],
  },
  {
    id: 'projects.access.check',
    domain: 'projects',
    method: 'POST',
    path: '/v1/projects/access/check',
    description: 'Check authenticated user access to one project through workspace membership.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'checkProjectAccess',
    notes: ['Uses canonical projects.workspace_id and workspace_members; IDs are UUID-validated and no chat/media/execution tables are touched.'],
  },
  {
    id: 'projects.update',
    domain: 'projects',
    method: 'PATCH',
    path: '/api/projects/:projectId',
    description: 'Update project metadata.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'updateProject',
    notes: ['Real route should keep RLS and audit history authoritative.'],
  },
  {
    id: 'projects.chatSession.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/projects/:projectId/chat-sessions',
    description: 'Create a chat session for a project.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProjectChatSession',
    notes: ['Mock chat-native planning creates local sessions without real persistence.'],
  },
  {
    id: 'projects.demo.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/mock/projects/demo',
    description: 'Create a local mock project through the chat-native planning flow.',
    securityLevel: 'public',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Local mock route only; no database, provider, worker, or render call occurs.'],
  },
]
