import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const PROJECT_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'projects.list',
    domain: 'projects',
    method: 'GET',
    path: '/v1/projects',
    description: 'List projects for the current workspace.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listProjects',
    notes: ['Reviewed /v1 backend route requires auth and returns current-user project metadata for internal testing recovery.'],
  },
  {
    id: 'projects.get',
    domain: 'projects',
    method: 'GET',
    path: '/v1/projects/:projectId',
    description: 'Get one project with workspace ownership context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getProject',
    notes: ['Reviewed /v1 backend route requires auth and keeps project reads behind backend ownership checks.'],
  },
  {
    id: 'projects.create',
    domain: 'projects',
    method: 'POST',
    path: '/v1/projects',
    description: 'Create a project in a workspace.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProject',
    notes: ['Reviewed /v1 backend route requires auth; internal testing may use local backend project persistence until real project tables are approved.'],
  },
  {
    id: 'projects.update',
    domain: 'projects',
    method: 'PATCH',
    path: '/api/projects/:projectId',
    description: 'Update project metadata.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'updateProject',
    notes: ['Real route should keep RLS and audit history authoritative.'],
  },
  {
    id: 'projects.internalEditState.save',
    domain: 'projects',
    method: 'PUT',
    path: '/v1/projects/:projectId/internal-edit-state',
    description: 'Save private internal edit handoff state for signed-in testing readback.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'saveInternalEditState',
    notes: ['Reviewed /v1 backend route requires auth and stores private internal-testing handoff metadata only.'],
  },
  {
    id: 'projects.internalEditState.get',
    domain: 'projects',
    method: 'GET',
    path: '/v1/projects/:projectId/internal-edit-state',
    description: 'Read one private internal edit handoff state for signed-in testing readback.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getInternalEditState',
    notes: ['Reviewed /v1 backend route requires auth and returns only private internal-testing handoff metadata.'],
  },
  {
    id: 'projects.internalEditState.migrateMotionStudioStorytelling',
    domain: 'projects',
    method: 'POST',
    path: '/v1/projects/:projectId/internal-edit-state/migrate-motion-studio-storytelling',
    description: 'Migrate one retained pre-discriminator Storytelling handoff after exact production revalidation.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'migrateRetainedStorytellingWorkflow',
    notes: [
      'Authorization precedes idempotency and the backend re-reads the exact Motion Studio production before persisting the explicit workflow discriminator.',
      'The route does not create a production or start planning, providers, rendering, billing, or delivery.',
    ],
  },
  {
    id: 'projects.internalEditState.list',
    domain: 'projects',
    method: 'GET',
    path: '/v1/internal-edit-states',
    description: 'List private internal edit handoff states for signed-in testing project recovery.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'listInternalEditStates',
    notes: ['Reviewed /v1 backend route requires auth and lists private internal-testing state from the local registry.'],
  },
  {
    id: 'projects.chatSession.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/projects/:projectId/chat-sessions',
    description: 'Create a chat session for a project.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createProjectChatSession',
    notes: ['Mock chat-native planning creates local sessions without real persistence.'],
  },
  {
    id: 'projects.demo.create',
    domain: 'projects',
    method: 'POST',
    path: '/api/mock/projects/demo',
    description: 'Create a local mock project through the chat-native planning flow.',
    securityLevel: 'public',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockChatNativePlanning',
    notes: ['Local mock route only; no database, provider, worker, or render call occurs.'],
  },
]
