import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const PROVIDER_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'providers.openai.planningRequest',
    domain: 'providers',
    method: 'POST',
    path: '/api/providers/planning-requests',
    description: 'Future backend route for AI planning requests.',
    securityLevel: 'provider_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'createProviderPlanningRequest',
    notes: ['Metadata-only skeleton; no provider module is imported or called.'],
  },
  {
    id: 'providers.lyria.generateMusic',
    domain: 'providers',
    method: 'POST',
    path: '/api/providers/music-generation',
    description: 'Future backend route for music generation.',
    securityLevel: 'provider_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'generateMusicAsset',
    notes: ['Disabled until provider credentials and worker runtime are backend-only.'],
  },
  {
    id: 'providers.mirelo.generateSfx',
    domain: 'providers',
    method: 'POST',
    path: '/api/providers/sfx-generation',
    description: 'Future backend route for premium SFX generation.',
    securityLevel: 'provider_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'generateSfxAsset',
    notes: ['Disabled and metadata-only in RP-FIX-08.'],
  },
  {
    id: 'providers.mmaudio.generateSfx',
    domain: 'providers',
    method: 'POST',
    path: '/api/providers/draft-sfx-generation',
    description: 'Future backend route for draft/video-synced SFX generation.',
    securityLevel: 'provider_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'generateDraftSfxAsset',
    notes: ['Disabled and metadata-only in RP-FIX-08.'],
  },
  {
    id: 'providers.aiVideo.generate',
    domain: 'providers',
    method: 'POST',
    path: '/api/providers/ai-video-generation',
    description: 'Future backend route for AI video asset generation.',
    securityLevel: 'provider_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: true,
    requiresStripeSecret: false,
    futureHandlerName: 'generateAiVideoAsset',
    notes: ['Disabled until approved-plan, credit, and tier policy enforcement exist in backend.'],
  },
]
