import type { ApiRouteDefinition, ApiRouteSecurityLevel, ApiRouteStatus } from '../api-runtime-contracts'

const PROVIDER_FORBIDDEN_SIDE_EFFECTS = [
  'No real provider calls',
  'No provider SDK installation',
  'No Secret Manager access',
  'No provider secret reads',
  'No external provider HTTP requests',
  'No webhook processing against real provider payloads',
  'No generated asset creation',
  'No worker/job execution',
  'No render/export execution',
  'No tool execution',
  'No media processing',
  'No credit mutation',
  'No storage transfer',
]

function providerRoute(input: {
  id: string
  method: ApiRouteDefinition['method']
  path: string
  description: string
  securityLevel?: ApiRouteSecurityLevel
  status?: ApiRouteStatus
  productionReadiness?: ApiRouteDefinition['productionReadiness']
  routeGroup: string
  idempotencyRequired?: boolean
  inputSchema: string
  outputSchema: string
  tablesTouched?: string[]
  auditEvent?: string
  futureHandlerName: string
  requiresProviderSecret?: boolean
  notes?: string[]
}): ApiRouteDefinition {
  return {
    id: input.id,
    domain: 'providers',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: input.securityLevel ?? 'workspace_member',
    runtimeMode: 'backend_required',
    status: input.status ?? 'backend_required',
    requiresSupabase: input.productionReadiness !== 'implemented',
    requiresServiceRole: input.productionReadiness !== 'implemented',
    requiresProviderSecret: input.requiresProviderSecret ?? input.productionReadiness !== 'implemented',
    requiresStripeSecret: false,
    futureHandlerName: input.futureHandlerName,
    routeGroup: input.routeGroup,
    authRequired: true,
    workspaceRequired: true,
    projectRequired: !['catalog', 'models'].includes(input.routeGroup),
    idempotencyRequired: Boolean(input.idempotencyRequired),
    serviceRoleRequired: input.productionReadiness !== 'implemented',
    allowedCaller: 'authenticated backend API caller',
    inputSchema: input.inputSchema,
    outputSchema: input.outputSchema,
    tablesTouched: input.tablesTouched ?? [
      'projects',
      'workspaces',
      'workspace_members',
      'generation_providers',
      'generation_provider_models',
      'provider_request_attempts',
      'provider_webhook_events',
    ],
    forbiddenSideEffects: PROVIDER_FORBIDDEN_SIDE_EFFECTS,
    auditEvent: input.auditEvent,
    failClosedBehavior: 'Return provider gateway backend_required/blocker results until provider transport, secrets, worker runtime, and service-role persistence are explicitly implemented.',
    validationLevel: 'guarded',
    productionReadiness: input.productionReadiness ?? 'backend_required',
    notes: [
      'Prompt 15 metadata only; provider execution remains blocked.',
      ...(input.notes ?? []),
    ],
  }
}

export const PROVIDER_API_ROUTES: ApiRouteDefinition[] = [
  providerRoute({
    id: 'providers.readiness.check',
    method: 'POST',
    path: '/v1/providers/readiness',
    description: 'Check provider gateway readiness without transport or secret access.',
    routeGroup: 'readiness',
    idempotencyRequired: true,
    inputSchema: 'providerReadinessSchema',
    outputSchema: 'ProviderGatewayResult',
    auditEvent: 'provider_gateway.readiness_checked',
    futureHandlerName: 'checkProviderGatewayReadiness',
  }),
  providerRoute({
    id: 'providers.catalog.list',
    method: 'GET',
    path: '/v1/providers/catalog',
    description: 'List static provider catalog metadata.',
    status: 'backend_required',
    productionReadiness: 'implemented',
    routeGroup: 'catalog',
    inputSchema: 'providerCatalogListQuerySchema',
    outputSchema: 'ProviderGatewayResult.providerCatalog',
    futureHandlerName: 'listProviderCatalog',
    notes: ['Read-only static metadata; does not inspect provider credentials.'],
  }),
  providerRoute({
    id: 'providers.catalog.get',
    method: 'GET',
    path: '/v1/providers/catalog/:providerKey',
    description: 'Read static provider catalog metadata for one provider.',
    status: 'backend_required',
    productionReadiness: 'implemented',
    routeGroup: 'catalog',
    inputSchema: 'providerCatalogGetQuerySchema + providerKey',
    outputSchema: 'ProviderGatewayResult.providerCatalog',
    futureHandlerName: 'getProviderCatalogEntry',
    notes: ['Read-only static metadata; does not inspect provider credentials.'],
  }),
  providerRoute({
    id: 'providers.models.list',
    method: 'GET',
    path: '/v1/providers/models',
    description: 'List static provider model policy metadata.',
    status: 'backend_required',
    productionReadiness: 'implemented',
    routeGroup: 'models',
    inputSchema: 'providerModelsListQuerySchema',
    outputSchema: 'ProviderGatewayResult.providerCatalog',
    futureHandlerName: 'listProviderModels',
    notes: ['Read-only static model metadata; does not route a provider request.'],
  }),
  providerRoute({
    id: 'providers.model.get',
    method: 'GET',
    path: '/v1/providers/models/:providerModelKey',
    description: 'Read static provider model policy metadata.',
    status: 'backend_required',
    productionReadiness: 'implemented',
    routeGroup: 'models',
    inputSchema: 'providerModelGetQuerySchema + providerModelKey',
    outputSchema: 'ProviderGatewayResult.providerModel',
    futureHandlerName: 'getProviderModel',
    notes: ['Read-only static model metadata; does not route a provider request.'],
  }),
  providerRoute({
    id: 'providers.secretReference.check',
    method: 'POST',
    path: '/v1/providers/secret-reference/check',
    description: 'Validate provider secret-reference readiness without reading a secret value.',
    securityLevel: 'provider_secret_required',
    routeGroup: 'secrets',
    idempotencyRequired: true,
    inputSchema: 'providerSecretReferenceSchema',
    outputSchema: 'ProviderGatewayResult.providerSecretReference',
    auditEvent: 'provider_gateway.secret_reference_checked',
    futureHandlerName: 'checkProviderSecretReference',
  }),
  providerRoute({
    id: 'providers.route.preview',
    method: 'POST',
    path: '/v1/providers/route/preview',
    description: 'Preview provider route/model policy without provider transport.',
    routeGroup: 'routing',
    idempotencyRequired: true,
    inputSchema: 'providerRoutePreviewSchema',
    outputSchema: 'ProviderGatewayResult.providerRoutePreview',
    auditEvent: 'provider_gateway.route_previewed',
    futureHandlerName: 'previewProviderRoute',
  }),
  providerRoute({
    id: 'providers.requestEnvelope.validate',
    method: 'POST',
    path: '/v1/providers/request-envelope/validate',
    description: 'Validate provider request envelope shape and dependency references.',
    routeGroup: 'envelope',
    idempotencyRequired: true,
    inputSchema: 'providerRequestEnvelopeSchema',
    outputSchema: 'ProviderGatewayResult.providerRequestEnvelope',
    auditEvent: 'provider_gateway.request_envelope_validated',
    futureHandlerName: 'validateProviderRequestEnvelope',
  }),
  providerRoute({
    id: 'providers.requestAttempt.readiness',
    method: 'POST',
    path: '/v1/providers/request-attempt/readiness',
    description: 'Check provider request attempt readiness without creating a row or request.',
    routeGroup: 'attempts',
    idempotencyRequired: true,
    inputSchema: 'providerRequestAttemptReadinessSchema',
    outputSchema: 'ProviderGatewayResult.providerAttempt',
    auditEvent: 'provider_gateway.request_attempt_readiness_checked',
    futureHandlerName: 'checkProviderAttemptReadiness',
  }),
  providerRoute({
    id: 'providers.requestAttempt.createBoundary',
    method: 'POST',
    path: '/v1/providers/request-attempt/create-boundary',
    description: 'Fail-closed boundary for future provider request attempt creation.',
    securityLevel: 'provider_secret_required',
    routeGroup: 'attempts',
    idempotencyRequired: true,
    inputSchema: 'providerRequestAttemptCreateBoundarySchema',
    outputSchema: 'ProviderGatewayResult.providerAttempt',
    auditEvent: 'provider_gateway.request_attempt_create_boundary',
    futureHandlerName: 'createProviderAttemptBoundary',
  }),
  providerRoute({
    id: 'providers.requestAttempt.get',
    method: 'GET',
    path: '/v1/providers/request-attempts/:providerAttemptId',
    description: 'Read provider attempt summary boundary.',
    routeGroup: 'attempts',
    inputSchema: 'providerAttemptGetQuerySchema + providerAttemptId',
    outputSchema: 'ProviderGatewayResult.providerAttempt',
    futureHandlerName: 'getProviderAttemptSummary',
  }),
  providerRoute({
    id: 'providers.requestAttempt.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/provider-request-attempts',
    description: 'List provider attempt summaries for a project boundary.',
    routeGroup: 'attempts',
    inputSchema: 'providerAttemptListQuerySchema + projectId',
    outputSchema: 'ProviderGatewayResult.providerAttempt',
    futureHandlerName: 'listProviderAttemptsForProject',
  }),
  providerRoute({
    id: 'providers.webhook.readiness',
    method: 'POST',
    path: '/v1/providers/webhook/readiness',
    description: 'Check provider webhook readiness without verification or processing.',
    securityLevel: 'provider_secret_required',
    routeGroup: 'webhooks',
    idempotencyRequired: true,
    inputSchema: 'providerWebhookReadinessSchema',
    outputSchema: 'ProviderGatewayResult.providerWebhook',
    auditEvent: 'provider_gateway.webhook_readiness_checked',
    futureHandlerName: 'checkProviderWebhookReadiness',
  }),
  providerRoute({
    id: 'providers.webhook.receiveBoundary',
    method: 'POST',
    path: '/v1/providers/webhooks/:provider/receive-boundary',
    description: 'Fail-closed boundary for future provider webhook receive handling.',
    securityLevel: 'provider_secret_required',
    routeGroup: 'webhooks',
    idempotencyRequired: true,
    inputSchema: 'providerWebhookReceiveBoundarySchema',
    outputSchema: 'ProviderGatewayResult.providerWebhook',
    auditEvent: 'provider_gateway.webhook_receive_boundary',
    futureHandlerName: 'receiveProviderWebhookBoundary',
  }),
  providerRoute({
    id: 'providers.webhook.summary.get',
    method: 'GET',
    path: '/v1/providers/webhooks/:providerWebhookEventId/summary',
    description: 'Read sanitized provider webhook summary boundary.',
    routeGroup: 'webhooks',
    inputSchema: 'providerWebhookSummaryQuerySchema + providerWebhookEventId',
    outputSchema: 'ProviderGatewayResult.providerWebhook',
    futureHandlerName: 'getProviderWebhookSummary',
  }),
  providerRoute({
    id: 'providers.output.readiness',
    method: 'POST',
    path: '/v1/providers/output/readiness',
    description: 'Check provider output storage/readiness boundaries without writing assets.',
    routeGroup: 'outputs',
    idempotencyRequired: true,
    inputSchema: 'providerOutputReadinessSchema',
    outputSchema: 'ProviderGatewayResult.providerOutput',
    auditEvent: 'provider_gateway.output_readiness_checked',
    futureHandlerName: 'checkProviderOutputReadiness',
  }),
  providerRoute({
    id: 'providers.execution.blocked',
    method: 'POST',
    path: '/v1/providers/execution/blocked',
    description: 'Report explicit provider execution blockers.',
    routeGroup: 'execution',
    idempotencyRequired: true,
    inputSchema: 'providerExecutionBlockedSchema',
    outputSchema: 'ProviderGatewayResult.providerAttempt',
    auditEvent: 'provider_gateway.execution_blocked',
    futureHandlerName: 'getProviderExecutionBlocked',
  }),
  providerRoute({
    id: 'providers.blockers',
    method: 'POST',
    path: '/v1/providers/blockers',
    description: 'List provider gateway blockers for a project/provider boundary.',
    routeGroup: 'blockers',
    idempotencyRequired: true,
    inputSchema: 'providerBlockersSchema',
    outputSchema: 'ProviderGatewayResult',
    auditEvent: 'provider_gateway.blockers_listed',
    futureHandlerName: 'listProviderGatewayBlockers',
  }),
]
