import type { ApiMethod, ApiRouteDefinition } from '../api-runtime-contracts'

const QA_REVISION_FORBIDDEN_SIDE_EFFECTS = [
  'execute QA workers',
  'inspect or process real media',
  'regenerate assets',
  'call providers',
  'execute Remotion or FFmpeg',
  'create render/export jobs',
  'claim workers',
  'execute tools',
  'mutate credits',
  'upload or download storage objects',
  'mutate approved snapshots',
  'start planning/generation',
  'store signed URLs',
]

function route(input: {
  id: string
  method: ApiMethod
  path: string
  description: string
  routeGroup: string
  idempotencyRequired?: boolean
  productionReadiness: 'implemented' | 'backend_required' | 'blocked'
  tablesTouched: string[]
  notes: string[]
}): ApiRouteDefinition {
  return {
    id: input.id,
    domain: 'qa',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    routeGroup: input.routeGroup,
    authRequired: true,
    workspaceRequired: true,
    projectRequired: true,
    idempotencyRequired: input.idempotencyRequired ?? false,
    serviceRoleRequired: true,
    allowedCaller: 'authenticated workspace/project member through backend API only',
    inputSchema: 'server/validation/qa-revision-schemas.ts',
    outputSchema: 'QaRevisionResult',
    tablesTouched: input.tablesTouched,
    forbiddenSideEffects: QA_REVISION_FORBIDDEN_SIDE_EFFECTS,
    failClosedBehavior: 'Return backend_required/blockers when QA/revision/fallback worker, transactional database runtime, or service-role runtime is unavailable.',
    validationLevel: 'guarded',
    productionReadiness: input.productionReadiness,
    futureHandlerName: input.id,
    auditEvent: input.idempotencyRequired ? `${input.id}.backend_required` : undefined,
    notes: input.notes,
  }
}

export const QA_REVISION_API_ROUTES: ApiRouteDefinition[] = [
  route({
    id: 'qa.readiness.check',
    method: 'POST',
    path: '/v1/qa/readiness',
    description: 'Check QA readiness against approved snapshot, render, media, credit, and blocker dependencies.',
    routeGroup: 'qa',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'renders', 'qa_reports', 'qa_check_results'],
    notes: ['Readiness-only boundary; no QA worker or media inspection is started.'],
  }),
  route({
    id: 'qa.report.create',
    method: 'POST',
    path: '/v1/qa/reports',
    description: 'Validate a future QA report creation boundary without writing QA worker results.',
    routeGroup: 'qa',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'renders', 'qa_reports', 'qa_check_results', 'api_idempotency_keys'],
    notes: ['Returns backend_required until transactional QA report writes and QA workers are implemented.'],
  }),
  route({
    id: 'qa.report.get',
    method: 'GET',
    path: '/v1/qa/reports/:qaReportId',
    description: 'Read sanitized QA report metadata.',
    routeGroup: 'qa',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports'],
    notes: ['Read-only and project-scoped.'],
  }),
  route({
    id: 'qa.report.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/qa-reports',
    description: 'List sanitized QA reports for a project.',
    routeGroup: 'qa',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports'],
    notes: ['No QA artifacts or private media are exposed.'],
  }),
  route({
    id: 'qa.blockers.list',
    method: 'POST',
    path: '/v1/qa/blockers',
    description: 'List project-scoped QA blockers without resolving or executing repair.',
    routeGroup: 'qa',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports', 'qa_check_results'],
    notes: ['Blocking QA can prevent final export readiness.'],
  }),
  route({
    id: 'qa.blockers.resolveBoundary',
    method: 'POST',
    path: '/v1/qa/blockers/resolve-boundary',
    description: 'Validate a future QA blocker resolution boundary without mutating QA rows.',
    routeGroup: 'qa',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports', 'qa_check_results', 'api_idempotency_keys'],
    notes: ['Does not mark blockers resolved in Prompt 11.'],
  }),
  route({
    id: 'preview.review.create',
    method: 'POST',
    path: '/v1/preview/reviews',
    description: 'Validate a preview review creation boundary.',
    routeGroup: 'preview',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders', 'preview_reviews', 'api_idempotency_keys'],
    notes: ['Does not persist preview review rows until a later backend write milestone.'],
  }),
  route({
    id: 'preview.review.get',
    method: 'GET',
    path: '/v1/preview/reviews/:previewReviewId',
    description: 'Read sanitized preview review metadata.',
    routeGroup: 'preview',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'preview_reviews'],
    notes: ['Read-only and private by default.'],
  }),
  route({
    id: 'preview.review.listForRender',
    method: 'GET',
    path: '/v1/renders/:renderId/preview-reviews',
    description: 'List sanitized preview reviews for a render.',
    routeGroup: 'preview',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders', 'preview_reviews'],
    notes: ['Does not generate signed preview URLs.'],
  }),
  route({
    id: 'review.comment.create',
    method: 'POST',
    path: '/v1/review/comments',
    description: 'Validate a review comment creation boundary.',
    routeGroup: 'review',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'preview_reviews', 'review_comments', 'api_idempotency_keys'],
    notes: ['Does not persist review comments in Prompt 11.'],
  }),
  route({
    id: 'review.comment.list',
    method: 'GET',
    path: '/v1/preview/reviews/:previewReviewId/comments',
    description: 'List sanitized review comments for a preview review.',
    routeGroup: 'review',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'preview_reviews', 'review_comments'],
    notes: ['Read-only and project-scoped.'],
  }),
  route({
    id: 'revision.request.create',
    method: 'POST',
    path: '/v1/revision/requests',
    description: 'Validate a revision request boundary without starting revision execution.',
    routeGroup: 'revision',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'renders', 'revision_requests', 'api_idempotency_keys'],
    notes: ['Material revisions still require a new estimate, approval, snapshot, and future execution path.'],
  }),
  route({
    id: 'revision.request.get',
    method: 'GET',
    path: '/v1/revision/requests/:revisionRequestId',
    description: 'Read sanitized revision request metadata.',
    routeGroup: 'revision',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'revision_requests'],
    notes: ['Read-only; no replanning or regeneration is started.'],
  }),
  route({
    id: 'revision.request.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/revision-requests',
    description: 'List sanitized revision requests for a project.',
    routeGroup: 'revision',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'revision_requests'],
    notes: ['Project-scoped listing only.'],
  }),
  route({
    id: 'revision.estimate.readiness',
    method: 'POST',
    path: '/v1/revision/estimate/readiness',
    description: 'Check whether a revision needs a new credit estimate before approval.',
    routeGroup: 'revision',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'revision_requests', 'credit_estimates'],
    notes: ['Does not create or approve credit estimates.'],
  }),
  route({
    id: 'revision.approval.required',
    method: 'POST',
    path: '/v1/revision/approval/required',
    description: 'Check whether revision scope requires new user approval.',
    routeGroup: 'revision',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'revision_requests', 'approval_records', 'approved_plan_snapshots'],
    notes: ['Does not create approval records or mutate snapshots.'],
  }),
  route({
    id: 'fallback.readiness.check',
    method: 'POST',
    path: '/v1/fallback/readiness',
    description: 'Check fallback readiness without choosing or executing fallback work.',
    routeGroup: 'fallback',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'qa_reports', 'qa_check_results'],
    notes: ['Fallback options remain planning metadata only.'],
  }),
  route({
    id: 'fallback.decision.plan',
    method: 'POST',
    path: '/v1/fallback/decisions/plan',
    description: 'Validate a fallback decision plan boundary without execution.',
    routeGroup: 'fallback',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports', 'qa_check_results', 'revision_requests', 'api_idempotency_keys'],
    notes: ['Does not retry, regenerate, repair, render, or create jobs.'],
  }),
  route({
    id: 'fallback.decision.get',
    method: 'GET',
    path: '/v1/fallback/decisions/:fallbackDecisionId',
    description: 'Read sanitized fallback decision metadata when available.',
    routeGroup: 'fallback',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'qa_check_results'],
    notes: ['Uses QA check result compatibility metadata until a later cleanup chooses a dedicated fallback table.'],
  }),
  route({
    id: 'repair.plan.readiness',
    method: 'POST',
    path: '/v1/repair/plan/readiness',
    description: 'Check repair-plan readiness without scheduling repair work.',
    routeGroup: 'repair',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'qa_reports', 'qa_check_results', 'revision_requests'],
    notes: ['Repair planning is a boundary only; no repair execution starts.'],
  }),
  route({
    id: 'export.blockers.check',
    method: 'POST',
    path: '/v1/export/blockers',
    description: 'Check final export blockers from QA/revision/fallback state.',
    routeGroup: 'export',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'renders', 'final_exports', 'qa_reports', 'qa_check_results', 'revision_requests'],
    notes: ['Final export remains blocked when QA/revision blockers exist.'],
  }),
]
