import type { ApiMethod, ApiRouteDefinition } from '../api-runtime-contracts'

const RENDER_FORBIDDEN_SIDE_EFFECTS = [
  'execute Remotion',
  'execute FFmpeg',
  'create render jobs',
  'create export jobs',
  'claim workers',
  'call providers',
  'execute tools',
  'process user media',
  'mutate credits',
  'upload or download storage objects',
  'mutate approved snapshots',
  'store signed URLs',
]

function route(input: {
  id: string
  method: ApiMethod
  path: string
  description: string
  idempotencyRequired?: boolean
  productionReadiness: 'implemented' | 'backend_required' | 'blocked'
  tablesTouched: string[]
  notes: string[]
}): ApiRouteDefinition {
  return {
    id: input.id,
    domain: 'render',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    routeGroup: input.id.startsWith('export.') ? 'export' : 'render',
    authRequired: true,
    workspaceRequired: true,
    projectRequired: true,
    idempotencyRequired: input.idempotencyRequired ?? false,
    serviceRoleRequired: true,
    allowedCaller: 'authenticated workspace/project member through backend API only',
    inputSchema: 'server/validation/render-schemas.ts',
    outputSchema: 'RenderFoundationResult',
    tablesTouched: input.tablesTouched,
    forbiddenSideEffects: RENDER_FORBIDDEN_SIDE_EFFECTS,
    failClosedBehavior: 'Return backend_required/blockers when render worker, Remotion, FFmpeg, storage, QA, or service-role runtime is unavailable.',
    validationLevel: 'guarded',
    productionReadiness: input.productionReadiness,
    futureHandlerName: input.id,
    auditEvent: input.idempotencyRequired ? `${input.id}.backend_required` : undefined,
    notes: input.notes,
  }
}

export const RENDER_API_ROUTES: ApiRouteDefinition[] = [
  route({
    id: 'render.readiness.check',
    method: 'POST',
    path: '/v1/render/readiness',
    description: 'Check render readiness against approved snapshot, credit reservation, media/storage, timing, and QA dependencies.',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'media_assets', 'storage_object_records', 'master_timing_maps', 'qa_reports'],
    notes: ['Readiness-only boundary; no render job, worker, Remotion, FFmpeg, or export is started.'],
  }),
  route({
    id: 'render.manifest.readiness',
    method: 'POST',
    path: '/v1/render/manifest/readiness',
    description: 'Check whether a render manifest can be built from approved record references.',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'media_assets', 'storage_object_records', 'master_timing_maps'],
    notes: ['Validates manifest readiness but does not persist or render a manifest.'],
  }),
  route({
    id: 'render.manifest.build',
    method: 'POST',
    path: '/v1/render/manifest/build',
    description: 'Validate and prepare a render manifest DTO without executing Remotion or persisting render state.',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'media_assets', 'storage_object_records', 'master_timing_maps'],
    notes: ['Mutation-style boundary is idempotent and fail-closed until a reviewed backend render runtime exists.'],
  }),
  route({
    id: 'render.preview.readiness',
    method: 'POST',
    path: '/v1/render/preview/readiness',
    description: 'Check preview-render readiness without requesting a render.',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'media_assets', 'storage_object_records', 'qa_reports'],
    notes: ['Reports blockers only; no preview artifact is generated.'],
  }),
  route({
    id: 'render.preview.request',
    method: 'POST',
    path: '/v1/render/preview/request',
    description: 'Validate a preview render request boundary.',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'render_jobs', 'render_job_inputs', 'renders'],
    notes: ['Returns backend_required until render job creation and worker execution are implemented in a later prompt.'],
  }),
  route({
    id: 'render.preview.status',
    method: 'GET',
    path: '/v1/render/preview/:renderId/status',
    description: 'Read sanitized preview render status by render ID.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders'],
    notes: ['Read-only status summary; no worker polling or storage download is performed.'],
  }),
  route({
    id: 'render.get',
    method: 'GET',
    path: '/v1/renders/:renderId',
    description: 'Read sanitized render metadata.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders'],
    notes: ['Render reads are backend-gated and project-scoped.'],
  }),
  route({
    id: 'render.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/renders',
    description: 'List sanitized render metadata for a project.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders'],
    notes: ['Project list is read-only and sanitized.'],
  }),
  route({
    id: 'render.blockers',
    method: 'POST',
    path: '/v1/render/blockers',
    description: 'Return render/export blocker status without starting execution.',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'media_assets', 'storage_object_records', 'qa_reports'],
    notes: ['Explicitly reports worker, Remotion, FFmpeg, provider, and tool execution blocks.'],
  }),
  route({
    id: 'render.events.list',
    method: 'GET',
    path: '/v1/renders/:renderId/events',
    description: 'List sanitized append-style render events.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'renders', 'render_events'],
    notes: ['Events are read-only in Prompt 10; no event append route is enabled.'],
  }),
  route({
    id: 'export.readiness.check',
    method: 'POST',
    path: '/v1/export/readiness',
    description: 'Check final export readiness against render, QA, snapshot, credit, and storage dependencies.',
    productionReadiness: 'implemented',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'renders', 'qa_reports', 'final_exports'],
    notes: ['Final export is blocked when QA/runtime dependencies are missing.'],
  }),
  route({
    id: 'export.request',
    method: 'POST',
    path: '/v1/export/request',
    description: 'Validate a final export request boundary.',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'approved_plan_snapshots', 'credit_reservations', 'renders', 'final_exports'],
    notes: ['Returns backend_required; no FFmpeg, storage write, or export artifact is created.'],
  }),
  route({
    id: 'export.status',
    method: 'GET',
    path: '/v1/export/:exportId/status',
    description: 'Read sanitized final export status.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'final_exports'],
    notes: ['Status-only route; no signed download URL is generated.'],
  }),
  route({
    id: 'export.get',
    method: 'GET',
    path: '/v1/exports/:exportId',
    description: 'Read sanitized final export metadata.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'final_exports'],
    notes: ['No public export delivery policy is enabled.'],
  }),
  route({
    id: 'export.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/exports',
    description: 'List sanitized final export metadata for a project.',
    productionReadiness: 'backend_required',
    tablesTouched: ['projects', 'workspace_members', 'final_exports'],
    notes: ['Project export listing is read-only and private by default.'],
  }),
]
