import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const RENDER_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'render.creditGate.check',
    domain: 'render',
    method: 'POST',
    path: '/api/render/credit-gate',
    description: 'Check whether preview/final render can pass the credit gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRenderCreditGate',
    futureHandlerName: 'checkRenderCreditGate',
    notes: ['Does not render media or queue render workers.'],
  },
  {
    id: 'render.timingManifest.create',
    domain: 'render',
    method: 'POST',
    path: '/api/render/timing-manifest',
    description: 'Create a mock render timing manifest from planned timing records.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingPlan',
    futureHandlerName: 'createRenderTimingManifest',
    notes: ['Creates planning data only; no render is started.'],
  },
  {
    id: 'render.preview.create',
    domain: 'render',
    method: 'POST',
    path: '/api/render/previews',
    description: 'Request a preview render.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createPreviewRender',
    notes: ['Real rendering is backend/worker-only and remains disabled.'],
  },
  {
    id: 'render.jobRuntime.queueMock',
    domain: 'render',
    method: 'POST',
    path: '/api/render/jobs/mock',
    description: 'Queue a mock render job through the RP-FIX-10 job runtime.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRenderJobQueue',
    futureHandlerName: 'queueRenderJob',
    notes: ['Generic mock render placeholder only; no render worker skeleton exists yet.'],
  },
  {
    id: 'render.workerLease.claimMock',
    domain: 'render',
    method: 'POST',
    path: '/api/render/workers/leases/claim/mock',
    description: 'Claim a mock lease for a generic render worker placeholder.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockRenderWorkerLease',
    futureHandlerName: 'claimRenderWorkerLease',
    notes: ['Render worker skeleton is missing; real render leasing remains backend-required.'],
  },
  {
    id: 'render.readiness.check',
    domain: 'render',
    method: 'POST',
    path: '/api/render/readiness',
    description: 'Check whether required assets and QA gates are ready for render.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingQA',
    futureHandlerName: 'checkRenderReadiness',
    notes: ['Mock readiness does not inspect real media files.'],
  },
  {
    id: 'render.previewStatus.get',
    domain: 'render',
    method: 'GET',
    path: '/api/render/previews/:renderId/status',
    description: 'Get preview render status.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'not_implemented',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getPreviewRenderStatus',
    notes: ['Future route should expose sanitized progress only.'],
  },
]
