import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const SFX_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'sfx.project.plan',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/plan',
    description: 'Create project-level mock SFX plans from an approved edit plan context.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXPlan',
    futureHandlerName: 'createEditProjectSFXPlan',
    notes: ['Project SFX integration is mock-only; no Mirelo or MMAudio call is made.'],
  },
  {
    id: 'sfx.project.providerRoutes',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/provider-routes',
    description: 'Return project-level SFX provider routing for internal library, Mirelo, MMAudio, and no-SFX decisions.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXProviderRoutes',
    futureHandlerName: 'getEditProjectSFXProviderRoutes',
    notes: ['Provider routes are planning records only.'],
  },
  {
    id: 'sfx.project.prompts',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/prompts',
    description: 'Create project-level SFX prompt plans for approved provider routes.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXPrompts',
    futureHandlerName: 'createEditProjectSFXPrompts',
    notes: ['Prompt plans do not execute providers.'],
  },
  {
    id: 'sfx.project.creditEstimate',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/credit-estimate',
    description: 'Create project-level SFX credit estimate lines before mock generation can queue.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXCreditEstimate',
    futureHandlerName: 'createEditProjectSFXCreditEstimate',
    notes: ['No Stripe or real credit transaction occurs.'],
  },
  {
    id: 'sfx.project.queueMockGeneration',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/queue-mock-generation',
    description: 'Queue mock project SFX generation jobs after approval and reservation gates pass.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXQueueGeneration',
    futureHandlerName: 'queueEditProjectSFXGeneration',
    notes: ['Queues local mock job metadata only.'],
  },
  {
    id: 'sfx.project.runMockWorker',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/project/run-mock-worker',
    description: 'Run the mock project SFX worker flow through the mock provider adapter.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXWorker',
    futureHandlerName: 'runEditProjectSFXWorker',
    notes: ['Uses mock worker/provider adapter only; real providers remain disabled.'],
  },
  {
    id: 'sfx.project.status',
    domain: 'sfx',
    method: 'GET',
    path: '/api/sfx/project/status',
    description: 'Summarize project-level SFX status for chat-native editor UI.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockEditProjectSFXStatus',
    futureHandlerName: 'getEditProjectSFXStatus',
    notes: ['Returns mock status and provider strategy text for the editor chat.'],
  },
  {
    id: 'sfx.creditGate.check',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/credit-gate',
    description: 'Check whether SFX generation can pass the credit gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockGenerationCreditGate',
    futureHandlerName: 'checkSFXGenerationCreditGate',
    notes: ['Does not call SFX providers.'],
  },
  {
    id: 'sfx.jobRuntime.queueMock',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/jobs/mock',
    description: 'Queue and optionally dispatch a mock SFX worker job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSFXJobRuntime',
    futureHandlerName: 'queueSFXWorkerJob',
    notes: ['Uses local mock SFX worker skeleton only; no Mirelo or MMAudio API is called.'],
  },
  {
    id: 'sfx.directorPlan.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/director-plan',
    description: 'Create a mock SoundSync SFX Director plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxDirectorPlan',
    notes: ['Planning only; no SFX provider call.'],
  },
  {
    id: 'sfx.prompt.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/prompt-plan',
    description: 'Create a mock SFX prompt plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxPromptPlan',
    notes: ['Prompt planning only; no provider execution.'],
  },
  {
    id: 'sfx.timingTrim.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/timing-trim',
    description: 'Create mock SFX timing and trim plans.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxTimingPlan',
    notes: ['No real waveform analysis is performed.'],
  },
  {
    id: 'sfx.mixPlan.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/mix-plan',
    description: 'Create a mock SFX mix plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxMixPlan',
    notes: ['No real audio processing is performed.'],
  },
  {
    id: 'sfx.qa.run',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/qa',
    description: 'Run mock SFX QA checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxQA',
    notes: ['No real provider or audio QA service is called.'],
  },
  {
    id: 'sfx.libraryCandidate.evaluate',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/library-candidates/evaluate',
    description: 'Evaluate a mock SFX library candidate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxLibraryCandidate',
    notes: ['Library growth remains mock-only until provenance review is backed by runtime services.'],
  },
]
