import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const SFX_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'sfx.creditGate.check',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/credit-gate',
    description: 'Check whether SFX generation can pass the credit gate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockGenerationCreditGate',
    futureHandlerName: 'checkSFXGenerationCreditGate',
    notes: ['Does not call SFX providers.'],
  },
  {
    id: 'sfx.jobRuntime.queueMock',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/jobs/mock',
    description: 'Queue and optionally dispatch a mock SFX worker job.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSFXJobRuntime',
    futureHandlerName: 'queueSFXWorkerJob',
    notes: ['Uses local mock SFX worker skeleton only; no Mirelo or MMAudio API is called.'],
  },
  {
    id: 'sfx.directorPlan.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/director-plan',
    description: 'Create a mock SoundSync SFX Director plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxDirectorPlan',
    notes: ['Planning only; no SFX provider call.'],
  },
  {
    id: 'sfx.prompt.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/prompt-plan',
    description: 'Create a mock SFX prompt plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxPromptPlan',
    notes: ['Prompt planning only; no provider execution.'],
  },
  {
    id: 'sfx.timingTrim.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/timing-trim',
    description: 'Create mock SFX timing and trim plans.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxTimingPlan',
    notes: ['No real waveform analysis is performed.'],
  },
  {
    id: 'sfx.mixPlan.create',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/mix-plan',
    description: 'Create a mock SFX mix plan.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxMixPlan',
    notes: ['No real audio processing is performed.'],
  },
  {
    id: 'sfx.qa.run',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/qa',
    description: 'Run mock SFX QA checks.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxQA',
    notes: ['No real provider or audio QA service is called.'],
  },
  {
    id: 'sfx.libraryCandidate.evaluate',
    domain: 'sfx',
    method: 'POST',
    path: '/api/sfx/library-candidates/evaluate',
    description: 'Evaluate a mock SFX library candidate.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockSfxLibraryCandidate',
    notes: ['Library growth remains mock-only until provenance review is backed by runtime services.'],
  },
]
