import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const STORYTIMING_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'storytiming.masterTimingMap.create',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/master-map',
    description: 'Create a mock MasterTimingMap.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingPlan',
    notes: ['Timing records are deterministic mock planning data.'],
  },
  {
    id: 'storytiming.captionCut.run',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/caption-cut',
    description: 'Run mock caption and cut timing planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockCaptionCutTiming',
    notes: ['No real transcript alignment is performed.'],
  },
  {
    id: 'storytiming.musicSfx.run',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/music-sfx',
    description: 'Run mock music/SFX timing planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockMusicSfxTiming',
    notes: ['No real audio analysis is performed.'],
  },
  {
    id: 'storytiming.signature.run',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/signature',
    description: 'Run mock signature timing planning.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingPlan',
    notes: ['No real animation/rendering is performed.'],
  },
  {
    id: 'storytiming.qa.run',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/qa',
    description: 'Run mock timing QA.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingQA',
    notes: ['Mock QA only; no frame-accurate media analysis is performed.'],
  },
  {
    id: 'storytiming.renderManifest.create',
    domain: 'storytiming',
    method: 'POST',
    path: '/api/storytiming/render-manifest',
    description: 'Create a mock render timing manifest.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockStoryTimingPlan',
    notes: ['Creates planning data only.'],
  },
]
