import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const STORAGE_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'storage.client.status',
    domain: 'storage',
    method: 'GET',
    path: '/api/storage/status',
    description: 'Report frontend-safe Supabase Storage client readiness.',
    securityLevel: 'public',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleStorageClientStatus',
    notes: ['Reads only public client configuration status.'],
  },
  {
    id: 'storage.uploadPlan.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/upload-plan',
    description: 'Create an upload plan with bucket and object path.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleCreateUploadPlan',
    notes: ['Alias for media.uploadPlan.create.'],
  },
  {
    id: 'storage.upload.validate',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/upload/validate',
    description: 'Validate upload metadata without writing to storage.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleValidateUpload',
    notes: ['Local validation only.'],
  },
  {
    id: 'storage.objectPath.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/object-path',
    description: 'Create a structured storage object path for a planned asset.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleStorageObjectPathCreate',
    notes: ['Path building is deterministic and does not upload.'],
  },
  {
    id: 'storage.signedUrl.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/signed-download-url',
    description: 'Create a signed download URL for private storage objects.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createSignedDownloadUrl',
    notes: ['Anon-client signed URLs may work with RLS, but production delivery likely needs a backend route.'],
  },
  {
    id: 'storage.signedUpload.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/signed-upload',
    description: 'Create a signed upload target when direct RLS uploads are insufficient.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createSignedUploadTarget',
    notes: ['Backend-only until storage policies and upload signing are reviewed.'],
  },
  {
    id: 'storage.object.delete',
    domain: 'storage',
    method: 'DELETE',
    path: '/api/storage/objects',
    description: 'Delete a private storage object.',
    securityLevel: 'workspace_owner_admin',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'deleteStorageObject',
    notes: ['Deletes are blocked from mock/frontend-safe API runtime.'],
  },
]
