import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const STORAGE_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'storage.uploadIntent.create',
    domain: 'storage',
    method: 'POST',
    path: '/v1/projects/:projectId/upload-intents',
    description: 'Create a backend-validated upload intent and upload target for private project storage.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createUploadIntent',
    notes: [
      'Requires auth, project access through workspace membership, and an idempotency key.',
      'Production runtime must store canonical bucket/path records only and must not persist signed URL values.',
      'Local/mock runtime may return backend-required or local-only upload targets when Supabase/storage credentials are unavailable.',
    ],
  },
  {
    id: 'storage.uploadIntent.get',
    domain: 'storage',
    method: 'GET',
    path: '/v1/upload-intents/:uploadIntentId',
    description: 'Read a scoped upload intent summary after workspace access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getUploadIntent',
    notes: [
      'Requires workspaceId query input and must fail closed for cross-workspace reads.',
      'Does not expose service-role-only data or signed URL values.',
    ],
  },
  {
    id: 'storage.localObject.upload',
    domain: 'storage',
    method: 'PUT',
    path: '/v1/upload-intents/:uploadIntentId/local-object',
    description: 'Upload bytes through the local/mock storage adapter for development validation only.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'uploadLocalObject',
    notes: [
      'Local-only route; not a production signed upload route.',
      'Validates upload intent ownership, MIME type, size, and purpose before writing local bytes.',
      'Production direct uploads must use backend-issued short-lived signed targets.',
    ],
  },
  {
    id: 'storage.upload.finalize',
    domain: 'storage',
    method: 'POST',
    path: '/v1/upload-intents/:uploadIntentId/finalize',
    description: 'Finalize an upload intent into canonical storage object and source media boundary records.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'finalizeUploadIntent',
    notes: [
      'Requires idempotency and project/workspace access validation.',
      'May create media/source-upload boundary records only; it must not start analysis, planning, credits, jobs, providers, rendering, or tools.',
    ],
  },
  {
    id: 'storage.signedUrlEvent.record',
    domain: 'storage',
    method: 'POST',
    path: '/v1/upload-intents/:uploadIntentId/signed-url-events',
    description: 'Record a sanitized signed URL lifecycle event without persisting the signed URL value.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'recordSignedUrlEvent',
    notes: [
      'Requires idempotency and scoped upload intent, storage object, project, or workspace access.',
      'Metadata must not contain signed URLs, provider keys, service-role keys, tokens, or secrets.',
    ],
  },
  {
    id: 'storage.objectRecord.get',
    domain: 'storage',
    method: 'GET',
    path: '/v1/storage-objects/:storageObjectRecordId',
    description: 'Read a canonical storage object record by bucket/path after workspace access validation.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getStorageObjectRecord',
    notes: [
      'Requires workspaceId query input.',
      'Returns canonical bucket/path metadata only and never returns long-lived signed URLs.',
    ],
  },
  {
    id: 'storage.signedDownload.create',
    domain: 'storage',
    method: 'POST',
    path: '/v1/storage-objects/:storageObjectRecordId/download-target',
    description: 'Create a backend-gated short-lived private download target for a canonical storage object.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createDownloadTarget',
    notes: [
      'Requires idempotency and workspace access validation.',
      'Signed URL lifecycle events may be recorded, but signed URL values must remain temporary response data only.',
    ],
  },
  {
    id: 'storage.localObject.read',
    domain: 'storage',
    method: 'GET',
    path: '/v1/storage-objects/:storageObjectRecordId/local-object',
    description: 'Stream bytes from the local/mock storage adapter for development validation only.',
    securityLevel: 'workspace_member',
    runtimeMode: 'mock',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'createLocalObjectStream',
    notes: [
      'Local-only route; not a production private download route.',
      'Still requires auth and workspace-scoped storage object lookup.',
    ],
  },
  {
    id: 'storage.client.status',
    domain: 'storage',
    method: 'GET',
    path: '/api/storage/status',
    description: 'Report frontend-safe Supabase Storage client readiness.',
    securityLevel: 'public',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleStorageClientStatus',
    notes: ['Reads only public client configuration status.', 'Legacy frontend-safe metadata; production upload runtime uses backend-gated /v1 routes.'],
  },
  {
    id: 'storage.uploadPlan.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/upload-plan',
    description: 'Create an upload plan with bucket and object path.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleCreateUploadPlan',
    notes: ['Alias for media.uploadPlan.create.', 'Legacy planning helper only; production upload intent creation uses storage.uploadIntent.create.'],
  },
  {
    id: 'storage.upload.validate',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/upload/validate',
    description: 'Validate upload metadata without writing to storage.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleValidateUpload',
    notes: ['Local validation only.', 'Does not create upload intents, signed targets, or storage object records.'],
  },
  {
    id: 'storage.objectPath.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/object-path',
    description: 'Create a structured storage object path for a planned asset.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleStorageObjectPathCreate',
    notes: ['Path building is deterministic and does not upload.', 'Backend runtime remains authoritative for canonical storage object records.'],
  },
  {
    id: 'storage.signedUrl.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/signed-download-url',
    description: 'Create a signed download URL for private storage objects.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createSignedDownloadUrl',
    notes: ['Legacy route metadata. Production download targets use storage.signedDownload.create and must not persist signed URL values.'],
  },
  {
    id: 'storage.signedUpload.create',
    domain: 'storage',
    method: 'POST',
    path: '/api/storage/signed-upload',
    description: 'Create a signed upload target when direct RLS uploads are insufficient.',
    securityLevel: 'workspace_editor',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'createSignedUploadTarget',
    notes: ['Legacy route metadata. Production upload targets are created through storage.uploadIntent.create after project access validation.'],
  },
  {
    id: 'storage.object.delete',
    domain: 'storage',
    method: 'DELETE',
    path: '/api/storage/objects',
    description: 'Delete a private storage object.',
    securityLevel: 'workspace_owner_admin',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'deleteStorageObject',
    notes: ['Deletes are blocked from mock/frontend-safe API runtime.'],
  },
]
