import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const STRIPE_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'stripe.checkout.create',
    domain: 'stripe',
    method: 'POST',
    path: '/api/stripe/checkout',
    description: 'Future backend route for checkout session creation.',
    securityLevel: 'stripe_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'createCheckoutSession',
    notes: [
      'Metadata-only skeleton; no payment SDK is imported or called.',
      'RP-STRIPE-FOUNDATION-01 adds /v1/billing/stripe/checkout-sessions/mock for config/mock contract checks only.',
      'RP-STRIPE-TESTMODE-01 adds /v1/billing/stripe/checkout-sessions/test for Stripe test-mode credit-pack checkout only.',
    ],
  },
  {
    id: 'stripe.webhook.handle',
    domain: 'stripe',
    method: 'POST',
    path: '/api/stripe/webhook',
    description: 'Future backend route for payment webhooks.',
    securityLevel: 'stripe_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'handlePaymentWebhook',
    notes: [
      'Webhook validation is backend-only and disabled here.',
      'Future live Stripe webhooks must mount before JSON parsing so raw request body is available for signature verification.',
      'RP-STRIPE-TESTMODE-01 mounts /v1/billing/stripe/webhooks/test before JSON parsing for test-mode webhook verification only.',
    ],
  },
  {
    id: 'stripe.subscription.get',
    domain: 'stripe',
    method: 'GET',
    path: '/api/stripe/subscription',
    description: 'Future backend route for subscription status.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'getSubscriptionStatus',
    notes: ['Disabled until billing runtime and account mapping exist; RP-STRIPE-FOUNDATION-01 adds customer/payment method link contracts only.'],
  },
]
