import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const STRIPE_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'stripe.checkout.create',
    domain: 'stripe',
    method: 'POST',
    path: '/api/stripe/checkout',
    description: 'Future backend route for checkout session creation.',
    securityLevel: 'stripe_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'createCheckoutSession',
    notes: ['Metadata-only skeleton; no payment SDK is imported or called.'],
  },
  {
    id: 'stripe.webhook.handle',
    domain: 'stripe',
    method: 'POST',
    path: '/api/stripe/webhook',
    description: 'Future backend route for payment webhooks.',
    securityLevel: 'stripe_secret_required',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'handlePaymentWebhook',
    notes: ['Webhook validation is backend-only and disabled here.'],
  },
  {
    id: 'stripe.subscription.get',
    domain: 'stripe',
    method: 'GET',
    path: '/api/stripe/subscription',
    description: 'Future backend route for subscription status.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: true,
    futureHandlerName: 'getSubscriptionStatus',
    notes: ['Disabled until billing runtime and account mapping exist.'],
  },
]
