import type { ApiMethod, ApiRouteDefinition } from '../api-runtime-contracts'

const TOOL_CALL_FORBIDDEN_SIDE_EFFECTS = [
  'install tool packages',
  'execute tools',
  'run FFmpeg, Remotion, browser capture, image, video, audio, OCR, VLM, or QA tooling',
  'process media',
  'call providers',
  'create jobs or claim workers',
  'render/export media',
  'mutate credits',
  'upload or download storage objects',
  'generate signed URLs',
  'mutate approved snapshots',
  'deploy runtimes',
  'run remote Supabase migrations',
]

const TOOL_CALL_TABLES = [
  'projects',
  'workspace_members',
  'approved_plan_snapshots',
  'credit_estimates',
  'credit_reservations',
  'media_assets',
  'storage_object_records',
  'renders',
  'qa_reports',
  'tool_catalog',
  'tool_profiles',
  'tool_capabilities',
  'tool_chain_templates',
  'tool_call_intents',
  'tool_call_executions',
  'tool_runtime_checks',
  'api_idempotency_keys',
]

function route(input: {
  id: string
  method: ApiMethod
  path: string
  description: string
  routeGroup: string
  idempotencyRequired?: boolean
  productionReadiness: 'implemented' | 'mock_only' | 'backend_required' | 'blocked' | 'future'
  tablesTouched?: string[]
  notes: string[]
}): ApiRouteDefinition {
  return {
    id: input.id,
    domain: 'tools',
    method: input.method,
    path: input.path,
    description: input.description,
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: input.productionReadiness === 'mock_only' ? 'mock_ready' : 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    routeGroup: input.routeGroup,
    authRequired: true,
    workspaceRequired: true,
    projectRequired: input.routeGroup !== 'catalog',
    idempotencyRequired: input.idempotencyRequired ?? false,
    serviceRoleRequired: true,
    allowedCaller: 'authenticated workspace/project member through backend API only',
    inputSchema: 'server/validation/tool-call-schemas.ts',
    outputSchema: 'ToolCallResult',
    tablesTouched: input.tablesTouched ?? TOOL_CALL_TABLES,
    forbiddenSideEffects: TOOL_CALL_FORBIDDEN_SIDE_EFFECTS,
    failClosedBehavior: 'Return backend_required/blockers when canonical tool catalog, tool-call intent persistence, worker runtime, or service-role runtime is unavailable.',
    validationLevel: 'guarded',
    productionReadiness: input.productionReadiness,
    futureHandlerName: input.id,
    auditEvent: input.idempotencyRequired ? `${input.id}.backend_required` : undefined,
    notes: input.notes,
  }
}

export const TOOL_CALL_API_ROUTES: ApiRouteDefinition[] = [
  route({
    id: 'tools.catalog.readiness',
    method: 'GET',
    path: '/v1/tools/catalog/readiness',
    description: 'Report tool catalog readiness without installing, probing, or executing tools.',
    routeGroup: 'catalog',
    productionReadiness: 'backend_required',
    tablesTouched: ['tool_catalog', 'tool_profiles', 'tool_capabilities', 'tool_runtime_checks'],
    notes: ['Static planning catalog exists; canonical catalog/runtime records remain backend-required.'],
  }),
  route({
    id: 'tools.catalog.list',
    method: 'GET',
    path: '/v1/tools/catalog',
    description: 'List static planning-only tool catalog placeholders.',
    routeGroup: 'catalog',
    productionReadiness: 'mock_only',
    tablesTouched: ['tool_catalog', 'tool_profiles', 'tool_capabilities'],
    notes: ['Does not imply packages are installed or tools can execute.'],
  }),
  route({
    id: 'tools.catalog.get',
    method: 'GET',
    path: '/v1/tools/catalog/:toolId',
    description: 'Read one static planning-only tool catalog placeholder.',
    routeGroup: 'catalog',
    productionReadiness: 'mock_only',
    tablesTouched: ['tool_catalog', 'tool_profiles', 'tool_capabilities'],
    notes: ['Tool runtime availability is not probed.'],
  }),
  route({
    id: 'tools.chains.list',
    method: 'GET',
    path: '/v1/tools/chains',
    description: 'List static planning-only tool-chain templates.',
    routeGroup: 'chains',
    productionReadiness: 'mock_only',
    tablesTouched: ['tool_chain_templates', 'tool_catalog'],
    notes: ['No chain execution or worker planning is started.'],
  }),
  route({
    id: 'tools.chains.get',
    method: 'GET',
    path: '/v1/tools/chains/:toolChainId',
    description: 'Read one static planning-only tool-chain template.',
    routeGroup: 'chains',
    productionReadiness: 'mock_only',
    tablesTouched: ['tool_chain_templates', 'tool_catalog'],
    notes: ['No tool package or runtime is touched.'],
  }),
  route({
    id: 'tools.decision.readiness',
    method: 'POST',
    path: '/v1/tools/decision/readiness',
    description: 'Check tool-decision dependencies against approved snapshot, credit, media, render, QA, and runtime blockers.',
    routeGroup: 'decision',
    productionReadiness: 'backend_required',
    notes: ['Readiness-only boundary; tool execution remains blocked.'],
  }),
  route({
    id: 'tools.decision.preview',
    method: 'POST',
    path: '/v1/tools/decision/preview',
    description: 'Preview a schema-only tool selection decision from an approved context envelope.',
    routeGroup: 'decision',
    productionReadiness: 'mock_only',
    notes: ['Does not persist an intent, create a job, execute a worker, or call a provider.'],
  }),
  route({
    id: 'tools.callIntent.readiness',
    method: 'POST',
    path: '/v1/tools/call-intents/readiness',
    description: 'Check future tool-call intent creation readiness.',
    routeGroup: 'call_intents',
    productionReadiness: 'backend_required',
    notes: ['Requires approved snapshot plus credit estimate/reservation evidence before any future execution.'],
  }),
  route({
    id: 'tools.callIntent.create',
    method: 'POST',
    path: '/v1/tools/call-intents',
    description: 'Validate future tool-call intent creation boundary without writing an intent row.',
    routeGroup: 'call_intents',
    idempotencyRequired: true,
    productionReadiness: 'backend_required',
    notes: ['Returns backend_required until canonical transactional writes and RLS are implemented.'],
  }),
  route({
    id: 'tools.callIntent.get',
    method: 'GET',
    path: '/v1/tools/call-intents/:toolCallIntentId',
    description: 'Read a future sanitized tool-call intent reference.',
    routeGroup: 'call_intents',
    productionReadiness: 'backend_required',
    notes: ['Fail-closed until canonical tool_call_intents table/RLS is available.'],
  }),
  route({
    id: 'tools.callIntent.listForProject',
    method: 'GET',
    path: '/v1/projects/:projectId/tool-call-intents',
    description: 'List future sanitized tool-call intents for a project.',
    routeGroup: 'call_intents',
    productionReadiness: 'backend_required',
    notes: ['Fail-closed and project-scoped.'],
  }),
  route({
    id: 'tools.callIntent.blockers',
    method: 'POST',
    path: '/v1/tools/call-intents/blockers',
    description: 'Report blockers that prevent tool-call intent persistence or execution.',
    routeGroup: 'call_intents',
    productionReadiness: 'backend_required',
    notes: ['No blocker rows are written in Prompt 12.'],
  }),
  route({
    id: 'tools.callIntent.validateContext',
    method: 'POST',
    path: '/v1/tools/call-intents/validate-context',
    description: 'Validate the tool-call context envelope schema without persistence or execution.',
    routeGroup: 'context',
    productionReadiness: 'mock_only',
    tablesTouched: ['approved_plan_snapshots', 'credit_estimates', 'credit_reservations', 'media_assets', 'storage_object_records', 'renders', 'qa_reports'],
    notes: ['Schema-only context validation path.'],
  }),
  route({
    id: 'tools.callIntent.qaRequirements',
    method: 'POST',
    path: '/v1/tools/call-intents/qa-requirements',
    description: 'Summarize future QA requirements for a tool-call intent.',
    routeGroup: 'qa',
    productionReadiness: 'mock_only',
    tablesTouched: ['qa_reports', 'qa_check_results', 'tool_call_intents'],
    notes: ['Does not run QA tools or inspect media.'],
  }),
  route({
    id: 'tools.execution.readiness',
    method: 'POST',
    path: '/v1/tools/execution/readiness',
    description: 'Confirm tool execution is blocked until a future reviewed worker runtime exists.',
    routeGroup: 'execution',
    productionReadiness: 'backend_required',
    notes: ['Always fail-closed for execution in Prompt 12.'],
  }),
  route({
    id: 'tools.execution.blocked',
    method: 'POST',
    path: '/v1/tools/execution/blocked',
    description: 'Return explicit blocked execution reasons for the provided tool-call context.',
    routeGroup: 'execution',
    productionReadiness: 'blocked',
    notes: ['No bypass or provider fallback is available.'],
  }),
  route({
    id: 'tools.runtime.readiness',
    method: 'POST',
    path: '/v1/tools/runtime/readiness',
    description: 'Report future tool runtime readiness blockers without probing local or remote packages.',
    routeGroup: 'runtime',
    productionReadiness: 'backend_required',
    tablesTouched: ['tool_runtime_checks', 'tool_catalog', 'tool_profiles'],
    notes: ['No version command, import check, Docker build, or worker run is executed.'],
  }),
  route({
    id: 'tools.license.readiness',
    method: 'POST',
    path: '/v1/tools/license/readiness',
    description: 'Report future license/security review blockers for a tool.',
    routeGroup: 'license',
    productionReadiness: 'backend_required',
    tablesTouched: ['tool_catalog', 'tool_profiles', 'tool_capabilities'],
    notes: ['License readiness does not approve production use in Prompt 12.'],
  }),
]
