import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const TRACKB_MEDIA_OSS_TOOL_CALL_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'trackbMediaOss.toolCall.validate',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/trackb-media-oss/tool-calls/validate',
    description: 'Validate a future Track B media OSS tool-call payload without executing tools.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'validateTrackBMediaOssToolCallPayload',
    notes: [
      'Disabled until Track B beta-readiness rerun accepts callable worker contracts.',
      'Future handler must fail without approvedSnapshotId, editPlanId, idempotencyKey, creditReservationId, private artifact refs, QA gates, fallback policy, and sanitized result schema.',
    ],
  },
  {
    id: 'trackbMediaOss.toolCall.queue',
    domain: 'jobs',
    method: 'POST',
    path: '/api/jobs/trackb-media-oss/tool-calls',
    description: 'Queue a future Track B media OSS tool-call worker job after all gates pass.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'queueTrackBMediaOssToolCall',
    notes: [
      'No current route can queue or execute Track B tools.',
      'Future route must create backend worker jobs only after approved snapshot, credit, private artifact, QA, fallback, and idempotency gates pass.',
    ],
  },
  {
    id: 'trackbMediaOss.toolCall.status',
    domain: 'jobs',
    method: 'GET',
    path: '/api/jobs/trackb-media-oss/tool-calls/:toolCallId/status',
    description: 'Read sanitized future Track B media OSS tool-call status.',
    securityLevel: 'workspace_member',
    runtimeMode: 'backend_required',
    status: 'disabled',
    requiresSupabase: true,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'getTrackBMediaOssToolCallStatus',
    notes: [
      'Status route is disabled until beta-readiness rerun accepts sanitized status/result schema.',
      'Future reads must expose sanitized status only and must not expose logs, signed URLs, public artifacts, or private payloads.',
    ],
  },
]
