import {
  VISUAL_INTELLIGENCE_AUTHENTICATED_READ_ROUTE,
  VISUAL_INTELLIGENCE_AUTHENTICATED_READ_ROUTE_ID,
  VISUAL_INTELLIGENCE_EXECUTION_ROUTE,
  VISUAL_INTELLIGENCE_EXECUTION_ROUTE_ID,
  VISUAL_INTELLIGENCE_INSPECTION_ROUTE,
  VISUAL_INTELLIGENCE_INSPECTION_ROUTE_ID,
  VISUAL_INTELLIGENCE_PLANNING_OPERATION_ROUTE,
  VISUAL_INTELLIGENCE_PLANNING_OPERATION_ROUTE_ID,
} from '../../../types/visual-intelligence'
import {
  ORCHESTRA_VISUAL_INTELLIGENCE_JOB_ROUTE,
  ORCHESTRA_VISUAL_INTELLIGENCE_JOB_ROUTE_ID,
} from '../../../types/orchestra-skill-capability'
import type { ApiRouteDefinition } from '../api-runtime-contracts'
import {
  CAPTION_RENDERED_VISUAL_REVIEW_AUTHENTICATED_READ_ROUTE,
  CAPTION_RENDERED_VISUAL_REVIEW_AUTHENTICATED_READ_ROUTE_ID,
} from '../../../types/caption-direction-visual-review-authenticated-read'

export const VISUAL_INTELLIGENCE_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: CAPTION_RENDERED_VISUAL_REVIEW_AUTHENTICATED_READ_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: CAPTION_RENDERED_VISUAL_REVIEW_AUTHENTICATED_READ_ROUTE,
    description:
      'Read the Caption-owned projection of canonical postrender visual-QA lifecycle evidence for exact confirmed outputs.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readCaptionPostrenderVisualQaProjection',
    notes: [
      'The backend authenticates the principal, rereads the immutable snapshot and canonical lifecycle record, then recomputes the Caption projection digest.',
      'Not-found and pending are valid reload-safe states; the browser cannot persist or promote completed provider or QA evidence.',
      'This read route cannot dispatch Qwen, mutate the edit, approve QA, repair assets, charge credits, deliver publicly, or grant production authority.',
    ],
  },
  {
    id: ORCHESTRA_VISUAL_INTELLIGENCE_JOB_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: ORCHESTRA_VISUAL_INTELLIGENCE_JOB_ROUTE,
    description:
      'Execute one immutable Orchestra-dispatched Visual Intelligence skill job and return its result only to Orchestra.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'cloud_run',
    status: 'backend_required',
    requiresSupabase: false,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'executeOrchestraVisualIntelligenceJob',
    notes: [
      'The exact call, manifest, qualification, budgets, media evidence, and compilation evidence must already exist in the create-only Orchestra dispatch store.',
      'The closed request always carries consumerBindingRequest. It is null for ordinary jobs; reference_preference_analysis requires the exact digest-bound Edit Reference scope so the consumer result binding is persisted after dispatch-package validation and before any provider execution.',
      'Peer skills may request support only through Orchestra; browsers, users, and skills cannot invoke this route directly or supply prompts, provider credentials, paths, URLs, or media bytes.',
      'The immutable result returns to Orchestra and cannot mutate timeline or artifacts, expand scope, approve QA, deliver publicly, or grant production authority.',
    ],
  },
  {
    id: VISUAL_INTELLIGENCE_PLANNING_OPERATION_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: VISUAL_INTELLIGENCE_PLANNING_OPERATION_ROUTE,
    description:
      'Retired direct planning-operation entrypoint; Orchestra now owns every Visual Intelligence invocation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'cloud_run',
    status: 'disabled',
    requiresSupabase: false,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'executeVisualIntelligencePlanningOperation',
    notes: [
      'This path is deliberately not mounted. New work must use the exact immutable Orchestra skill-job route.',
      'The backend owner independently rereads each immutable upstream request, artifact authority, evidence package, allowance, and account-effective pricing authority.',
      'Callers select only a registered operation/profile and, for query_range, one bounded question; arbitrary provider prompts, admissions, costs, paths, URLs, media bytes, credentials, tools, and model choices are forbidden.',
      'The result is immutable planning evidence only and cannot mutate the edit, dispatch editing work, render, approve QA, export, deliver, or grant production authority.',
    ],
  },
  {
    id: VISUAL_INTELLIGENCE_EXECUTION_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: VISUAL_INTELLIGENCE_EXECUTION_ROUTE,
    description:
      'Retired raw Visual Intelligence request entrypoint; Orchestra now owns every active dispatch.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'cloud_run',
    status: 'disabled',
    requiresSupabase: false,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'executeVisualIntelligenceRequest',
    notes: [
      'This path is deliberately not mounted. Possessing a request record is not Orchestra dispatch authority.',
      'The request is byte-free and must already be admitted by its canonical source or approved-edit owner.',
      'Google Application Default Credentials remain backend-only; caller-selected models, prompts, tools, credentials, URLs, and Qwen fallback are forbidden.',
      'Execution may persist immutable private evidence and settle the exact account-effective model cost, but it cannot mutate the edit, approve QA, export, deliver, or grant production authority.',
    ],
  },
  {
    id: VISUAL_INTELLIGENCE_INSPECTION_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: VISUAL_INTELLIGENCE_INSPECTION_ROUTE,
    description:
      'Retired direct inspection entrypoint; approved inspections now run only as exact Orchestra skill jobs.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'cloud_run',
    status: 'disabled',
    requiresSupabase: false,
    requiresServiceRole: true,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'executeApprovedVisualIntelligenceInspection',
    notes: [
      'This path is deliberately not mounted. An owning skill returns a support request to Orchestra instead of dispatching Visual Intelligence.',
      'The backend rereads the exact approved snapshot, private preview, confirmed output frame, work graph, timeline, estimate, reservation, and expected-outcome lineage before provider execution.',
      'Deterministic evidence must use the admitted GPU release; sampled Gemini evidence remains separate from complete-time deterministic QA and canonical private review.',
      'Findings route to the owning skill for at most two approved repair cycles. The route cannot mutate the timeline, approve QA, export, deliver, or grant production authority.',
    ],
  },
  {
    id: VISUAL_INTELLIGENCE_AUTHENTICATED_READ_ROUTE_ID,
    domain: 'visual_intelligence',
    method: 'POST',
    path: VISUAL_INTELLIGENCE_AUTHENTICATED_READ_ROUTE,
    description:
      'Authenticated reread of one exact immutable provider-neutral Visual Intelligence report.',
    securityLevel: 'workspace_member',
    runtimeMode: 'frontend_safe',
    status: 'frontend_safe_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    futureHandlerName: 'readVisualIntelligenceReport',
    notes: [
      'Success uses { ok:true, data:{ authenticatedRead }, warnings }.',
      'The route recomputes request/result digests, rereads the exact immutable report, and rejects cross-workspace, cross-edit, cross-snapshot, or browser-promoted completion.',
      'Historical Qwen records remain separately readable under their exact historical schema and can never satisfy this route.',
    ],
  },
]
