import type { ApiRouteDefinition } from '../api-runtime-contracts'

export const WEB_SEARCH_API_ROUTES: ApiRouteDefinition[] = [
  {
    id: 'webSearch.internal.status',
    domain: 'web_search',
    method: 'GET',
    path: '/v1/internal/web-search/status',
    description: 'Internal status route for web search/capture UI/API gate readiness.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWebSearchUiApiStatus',
    notes: ['Gate-only route metadata; no live search, capture, extraction, provider, or storage operation runs in mock mode.'],
  },
  {
    id: 'webSearch.internal.plan',
    domain: 'web_search',
    method: 'POST',
    path: '/v1/internal/web-search/plans',
    description: 'Internal route for creating a validated web search/capture gate-only plan snapshot.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWebSearchUiApiPlan',
    notes: ['Accepts only private fixture provider mode and blocked execution flags in Phase 49I.'],
  },
  {
    id: 'webSearch.internal.runControlled',
    domain: 'web_search',
    method: 'POST',
    path: '/v1/internal/web-search/run-controlled',
    description: 'Internal gate-only run envelope for web search/capture UI/API validation.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWebSearchUiApiRunControlled',
    notes: ['Gate-only; no SearXNG query, Playwright capture, Sharp processing, Readability extraction, or storage upload.'],
  },
  {
    id: 'webSearch.internal.runStatus',
    domain: 'web_search',
    method: 'GET',
    path: '/v1/internal/web-search/runs/:runId',
    description: 'Internal gate-only run status route for web search/capture validation envelopes.',
    securityLevel: 'authenticated',
    runtimeMode: 'frontend_safe',
    status: 'mock_ready',
    requiresSupabase: false,
    requiresServiceRole: false,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    mockHandlerName: 'handleMockWebSearchUiApiRunStatus',
    notes: ['Mock status only; live transport and runtime artifacts remain backend-gated.'],
  },
]
