import type { ApiRouteDefinition } from '../api-runtime-contracts'

const WORKER_FORBIDDEN_SIDE_EFFECTS = [
  'real worker execution',
  'worker claim/lease mutation without transactional backend runtime',
  'Cloud Run/PubSub/Cloud Tasks dispatch',
  'provider calls',
  'rendering',
  'tool execution',
  'media analysis',
  'credit mutation',
  'storage upload/download execution',
]

function workerRoute(input: Omit<ApiRouteDefinition, 'domain' | 'requiresProviderSecret' | 'requiresStripeSecret' | 'notes'> & { notes?: string[] }): ApiRouteDefinition {
  return {
    ...input,
    domain: 'workers',
    routeGroup: 'workers',
    authRequired: true,
    workspaceRequired: input.workspaceRequired ?? true,
    projectRequired: input.projectRequired ?? true,
    allowedCaller: input.allowedCaller ?? 'backend API or future worker runtime',
    failClosedBehavior: input.failClosedBehavior ?? 'Return backend_required blockers when worker claim/lease runtime is unavailable.',
    validationLevel: input.validationLevel ?? 'guarded',
    productionReadiness: input.productionReadiness ?? 'backend_required',
    forbiddenSideEffects: input.forbiddenSideEffects ?? WORKER_FORBIDDEN_SIDE_EFFECTS,
    requiresProviderSecret: false,
    requiresStripeSecret: false,
    notes: [
      'Prompt 8 worker routes are route/service boundaries only; they do not claim or execute real workers.',
      ...(input.notes ?? []),
    ],
  }
}

export const WORKER_API_ROUTES: ApiRouteDefinition[] = [
  workerRoute({
    id: 'workers.claim.readiness',
    method: 'POST',
    path: '/v1/jobs/:jobId/claim/readiness',
    description: 'Check worker claim gates without creating a claim or lease.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'claimWorkerReadinessSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['jobs', 'worker_job_claims', 'worker_leases'],
    futureHandlerName: 'checkWorkerClaimReadiness',
  }),
  workerRoute({
    id: 'workers.claim.create',
    method: 'POST',
    path: '/v1/jobs/:jobId/claim',
    description: 'Prepare worker claim creation blockers without claiming the job.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'claimWorkerJobSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_job_claims', 'worker_leases', 'job_claim_attempts', 'api_idempotency_keys'],
    futureHandlerName: 'claimWorkerJob',
  }),
  workerRoute({
    id: 'workers.claim.get',
    method: 'GET',
    path: '/v1/workers/claims/:workerClaimId',
    description: 'Read sanitized worker claim metadata after project access validation.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: false,
    serviceRoleRequired: true,
    inputSchema: 'workerClaimQuerySchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_job_claims', 'projects', 'workspace_members'],
    futureHandlerName: 'getWorkerClaim',
  }),
  workerRoute({
    id: 'workers.heartbeat',
    method: 'POST',
    path: '/v1/jobs/:jobId/heartbeat',
    description: 'Prepare heartbeat blockers without updating worker claim state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'workerHeartbeatSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_job_claims', 'worker_leases', 'api_idempotency_keys'],
    futureHandlerName: 'heartbeatWorker',
  }),
  workerRoute({
    id: 'workers.lease.renew',
    method: 'POST',
    path: '/v1/workers/leases/:leaseId/renew',
    description: 'Prepare lease renewal blockers without mutating lease state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'workerLeaseMutationSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_leases', 'worker_job_claims', 'api_idempotency_keys'],
    futureHandlerName: 'renewWorkerLease',
  }),
  workerRoute({
    id: 'workers.lease.release',
    method: 'POST',
    path: '/v1/workers/leases/:leaseId/release',
    description: 'Prepare lease release blockers without mutating lease state.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'workerLeaseMutationSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_leases', 'worker_job_claims', 'api_idempotency_keys'],
    futureHandlerName: 'releaseWorkerLease',
  }),
  workerRoute({
    id: 'workers.complete',
    method: 'POST',
    path: '/v1/workers/leases/:leaseId/complete',
    description: 'Prepare completion blockers without completing a job or lease.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'workerCompleteSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['jobs', 'worker_leases', 'worker_job_claims', 'job_events', 'api_idempotency_keys'],
    futureHandlerName: 'completeWorkerLease',
  }),
  workerRoute({
    id: 'workers.fail',
    method: 'POST',
    path: '/v1/workers/leases/:leaseId/fail',
    description: 'Prepare failure blockers without failing a job or lease.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'workerFailSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['jobs', 'worker_leases', 'worker_job_claims', 'job_events', 'api_idempotency_keys'],
    futureHandlerName: 'failWorkerLease',
  }),
  workerRoute({
    id: 'workers.recoverStale',
    method: 'POST',
    path: '/v1/workers/claims/recover-stale',
    description: 'Prepare stale claim recovery blockers without mutating claims or jobs.',
    securityLevel: 'backend_service_role',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: true,
    requiresServiceRole: true,
    idempotencyRequired: true,
    serviceRoleRequired: true,
    inputSchema: 'recoverStaleWorkerSchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: ['worker_job_claims', 'worker_leases', 'job_claim_attempts', 'api_idempotency_keys'],
    futureHandlerName: 'recoverStaleWorkerClaims',
  }),
  workerRoute({
    id: 'workers.runtime.registry',
    method: 'GET',
    path: '/v1/workers/runtime-registry',
    description: 'Read static worker runtime capability metadata without running readiness checks.',
    securityLevel: 'authenticated',
    runtimeMode: 'backend_required',
    status: 'backend_required',
    requiresSupabase: false,
    requiresServiceRole: false,
    idempotencyRequired: false,
    serviceRoleRequired: false,
    inputSchema: 'runtimeRegistryQuerySchema',
    outputSchema: 'WorkerRuntimeResult',
    tablesTouched: [],
    futureHandlerName: 'getWorkerRuntimeRegistry',
    projectRequired: false,
    workspaceRequired: false,
    notes: ['Static metadata only; no runtime checks, binaries, worker tools, or records are executed.'],
  }),
]
