import { z } from 'zod'

import {
  createCanonicalSam31GcpGpuRuntimeReleasePublicationCoordinator,
} from '../services/canonical-sam3_1-gpu-runtime-release-publication-coordinator'

const CONFIRMATION =
  'publish-one-weeditpro-sam31-route-runtime-release-v1' as const
const safeId = z.string().trim().min(1).max(512)
  .regex(/^[A-Za-z0-9][A-Za-z0-9._:/+-]*$/u)
  .refine((value) => !value.includes('..'))
const sha256 = z.string().regex(/^[a-f0-9]{64}$/u)
const routeId = z.enum([
  'a100_80gb_heavy_primary',
  'l4_heavy_fallback',
])
const environment = z.object({
  WEEDITPRO_SAM31_GPU_RUNTIME_RELEASE_CONFIRMATION: z.literal(CONFIRMATION),
  WEEDITPRO_SAM31_GPU_RUNTIME_ROUTE_ID: routeId,
  WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_ID: safeId,
  WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_SHA256: sha256,
  WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_ID: safeId,
  WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_ID: safeId,
  WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_ID: safeId,
  WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_ID: safeId,
  WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_ID: safeId,
  WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_ID: safeId,
  WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_ID: safeId,
  WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_SHA256: sha256,
  WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_ID: safeId,
  WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_SHA256: sha256,
}).strict().parse({
  WEEDITPRO_SAM31_GPU_RUNTIME_RELEASE_CONFIRMATION:
    process.env.WEEDITPRO_SAM31_GPU_RUNTIME_RELEASE_CONFIRMATION,
  WEEDITPRO_SAM31_GPU_RUNTIME_ROUTE_ID:
    process.env.WEEDITPRO_SAM31_GPU_RUNTIME_ROUTE_ID,
  WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_ID:
    process.env.WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_ID,
  WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_SHA256:
    process.env.WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_SHA256,
  WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_ID:
    process.env.WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_ID,
  WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_SHA256:
    process.env.WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_SHA256,
  WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_ID:
    process.env.WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_ID,
  WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_SHA256,
  WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_ID:
    process.env.WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_ID,
  WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_SHA256,
  WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_ID:
    process.env.WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_ID,
  WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_SHA256,
  WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_ID:
    process.env.WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_ID,
  WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_SHA256,
  WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_ID:
    process.env.WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_ID,
  WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_SHA256,
  WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_ID:
    process.env.WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_ID,
  WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_SHA256,
  WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_ID:
    process.env.WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_ID,
  WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_SHA256:
    process.env.WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_SHA256,
})

const result = await
createCanonicalSam31GcpGpuRuntimeReleasePublicationCoordinator().publish({
  routeId: environment.WEEDITPRO_SAM31_GPU_RUNTIME_ROUTE_ID,
  sourceCheckpointQualificationRef: {
    ...ref(
      environment.WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_ID,
      environment.WEEDITPRO_SAM31_SOURCE_CHECKPOINT_QUALIFICATION_SHA256,
    ),
    schemaVersion:
      'canonical-sam3_1-source-checkpoint-compatibility-qualification-v1',
  },
  imageSupplyChainReleaseRef: ref(
    environment.WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_ID,
    environment.WEEDITPRO_SAM31_PRODUCTION_IMAGE_SUPPLY_CHAIN_RELEASE_SHA256,
  ),
  serviceIdentityRef: ref(
    environment.WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_ID,
    environment.WEEDITPRO_SAM31_GPU_SERVICE_IDENTITY_REF_SHA256,
  ),
  scaleToZeroConfigurationRef: ref(
    environment.WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_ID,
    environment.WEEDITPRO_SAM31_GPU_SCALE_ZERO_CONFIGURATION_REF_SHA256,
  ),
  privateNetworkAndArtifactTransportRef: ref(
    environment.WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_ID,
    environment.WEEDITPRO_SAM31_GPU_PRIVATE_TRANSPORT_REF_SHA256,
  ),
  componentEvidenceRefs: {
    driverAndCudaRef: ref(
      environment.WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_ID,
      environment.WEEDITPRO_SAM31_GPU_DRIVER_COMPONENT_SHA256,
    ),
    deterministicRunSetRef: ref(
      environment.WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_ID,
      environment.WEEDITPRO_SAM31_GPU_DETERMINISTIC_COMPONENT_SHA256,
    ),
    eightMinutePerformanceRef: ref(
      environment.WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_ID,
      environment.WEEDITPRO_SAM31_GPU_PERFORMANCE_COMPONENT_SHA256,
    ),
    independentTemporalQualityRef: ref(
      environment.WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_ID,
      environment.WEEDITPRO_SAM31_GPU_TEMPORAL_QUALITY_COMPONENT_SHA256,
    ),
  },
})

process.stdout.write(`${JSON.stringify(result)}\n`)

function ref(id: string, digest: string) {
  return {
    id,
    version: 1 as const,
    contentHash: `sha256:${digest}` as const,
  }
}
