import type { ProjectEditBriefAttachmentScenario } from '../../types/project-edit-brief-attachments'

const scenarioRows = [
  ['kind-broll-video', 'Kind registry lists broll_video.', 'broll_video', true, 'safe_metadata_only'],
  ['kind-image', 'Kind registry lists image.', 'image', true, 'safe_metadata_only'],
  ['kind-music-track', 'Kind registry lists music_track.', 'music_track', true, 'safe_metadata_only'],
  ['kind-soundtrack', 'Kind registry lists soundtrack.', 'soundtrack', true, 'safe_metadata_only'],
  ['kind-sfx', 'Kind registry lists sfx.', 'sfx', true, 'safe_metadata_only'],
  ['kind-voiceover', 'Kind registry lists voiceover.', 'voiceover', true, 'safe_metadata_only'],
  ['kind-document', 'Kind registry lists document.', 'document', true, 'safe_metadata_only'],
  ['kind-reference-label', 'Kind registry lists reference_label.', 'reference_label', true, 'safe_metadata_only'],
  ['kind-reference-url', 'Kind registry lists reference_url_metadata_only.', 'reference_url_metadata_only', true, 'safe_metadata_only'],
  ['metadata-label-allowed', 'Metadata label input is allowed.', 'metadata_label', true, 'safe_metadata_only'],
  ['metadata-url-allowed', 'Metadata reference URL input is allowed without fetch.', 'metadata_reference_url', true, 'safe_metadata_only'],
  ['future-upload-blocked', 'Future upload placeholder is blocked.', 'future_upload_placeholder', false, 'blocked_upload_gate'],
  ['file-bytes-blocked', 'File bytes safety blocks.', 'file_bytes', false, 'blocked_file_bytes'],
  ['external-fetch-blocked', 'External fetch safety blocks.', 'external_fetch', false, 'blocked_external_fetch'],
  ['media-processing-blocked', 'Media processing safety blocks.', 'media_processing', false, 'blocked_media_processing'],
  ['sound-runtime-music-blocked', 'Sound runtime safety blocks for music.', 'music_track', true, 'safe_metadata_only'],
  ['sound-runtime-sfx-blocked', 'Sound runtime safety blocks for SFX.', 'sfx', true, 'safe_metadata_only'],
  ['draft-broll', 'B-roll attachment draft created.', 'broll_video', true, 'safe_metadata_only'],
  ['draft-image', 'Image attachment draft created.', 'image', true, 'safe_metadata_only'],
  ['draft-music', 'Music attachment draft created.', 'music_track', true, 'safe_metadata_only'],
  ['draft-soundtrack', 'Soundtrack attachment draft created.', 'soundtrack', true, 'safe_metadata_only'],
  ['draft-sfx', 'SFX attachment draft created.', 'sfx', true, 'safe_metadata_only'],
  ['draft-voiceover', 'Voiceover attachment draft created.', 'voiceover', true, 'safe_metadata_only'],
  ['draft-document', 'Document attachment draft created.', 'document', true, 'safe_metadata_only'],
  ['draft-reference-label', 'Reference label draft created.', 'reference_label', true, 'safe_metadata_only'],
  ['draft-reference-url', 'Reference URL metadata draft created.', 'reference_url_metadata_only', true, 'safe_metadata_only'],
  ['url-redaction', 'Reference URL redaction summary works.', 'https://example.com/video?id=secret', true, 'safe_metadata_only'],
  ['chip-video', 'Attachment chip model created for video.', 'broll_video', true, 'safe_metadata_only'],
  ['chip-image', 'Attachment chip model created for image.', 'image', true, 'safe_metadata_only'],
  ['chip-music', 'Attachment chip model created for music.', 'music_track', true, 'safe_metadata_only'],
  ['chip-sfx', 'Attachment chip model created for SFX.', 'sfx', true, 'safe_metadata_only'],
  ['panel-model', 'Attachment panel model includes chips.', 'panel', true, 'safe_metadata_only'],
  ['detail-card', 'Attachment detail card model works.', 'detail', true, 'safe_metadata_only'],
  ['readable-summary', 'Attachment readable summary works.', 'summary', true, 'safe_metadata_only'],
  ['debug-summary', 'Attachment debug summary works.', 'debug', true, 'safe_metadata_only'],
  ['bridge-provided-id', 'Intent bridge adds provided asset id.', 'bridge', true, 'safe_metadata_only'],
  ['bridge-blocking-needs', 'Intent bridge updates blocking needs.', 'bridge', true, 'safe_metadata_only'],
  ['bridge-conservative-status', 'Intent bridge keeps status conservative.', 'bridge', true, 'safe_metadata_only'],
  ['bridge-no-ready-for-plan', 'Intent bridge does not mark ready_for_plan.', 'bridge', true, 'safe_metadata_only'],
  ['validation-metadata', 'Validation passes metadata attachment.', 'validation', true, 'safe_metadata_only'],
  ['validation-empty-label', 'Validation blocks empty label.', '', false, 'failed_validation'],
  ['validation-file-byte', 'Validation blocks file-byte attempt.', 'file', false, 'blocked_file_bytes'],
  ['validation-external-fetch', 'Validation blocks external fetch attempt.', 'fetch', false, 'blocked_external_fetch'],
  ['validation-media-processing', 'Validation blocks media processing flag.', 'media', false, 'blocked_media_processing'],
  ['ui-load-panel', 'UI adapter loads attachment panel.', 'ui', true, 'safe_metadata_only'],
  ['ui-create-draft', 'UI adapter creates draft.', 'ui', true, 'safe_metadata_only'],
  ['ui-save-metadata', 'UI adapter saves metadata attachment via API.', 'ui', true, 'safe_metadata_only'],
  ['ui-remove', 'UI adapter removes attachment via API.', 'ui', true, 'safe_metadata_only'],
  ['ui-chip-models', 'UI adapter creates chip models.', 'ui', true, 'safe_metadata_only'],
  ['drawer-panel', 'Marker drawer can show attachment panel.', 'drawer', true, 'safe_metadata_only'],
  ['broll-satisfy', 'B-roll missing asset can be satisfied metadata-only where conservative.', 'broll_video', true, 'safe_metadata_only'],
  ['music-metadata-only', 'Music attachment remains metadata-only.', 'music_track', true, 'safe_metadata_only'],
  ['sfx-metadata-only', 'SFX attachment remains metadata-only.', 'sfx', true, 'safe_metadata_only'],
  ['url-metadata-only', 'Reference URL remains metadata-only.', 'reference_url_metadata_only', true, 'safe_metadata_only'],
  ['no-real-upload', 'No real upload occurs.', 'boundary', true, 'safe_metadata_only'],
  ['no-file-bytes', 'No file bytes read.', 'boundary', true, 'safe_metadata_only'],
  ['no-external-url-fetch', 'No external URL fetched.', 'boundary', true, 'safe_metadata_only'],
  ['no-media-processing', 'No media processing started.', 'boundary', true, 'safe_metadata_only'],
  ['no-provider-call', 'No provider call made.', 'boundary', true, 'safe_metadata_only'],
  ['no-sound-runtime', 'No sound runtime/worker started.', 'boundary', true, 'safe_metadata_only'],
  ['no-render-credit', 'No render/credit side effect.', 'boundary', true, 'safe_metadata_only'],
  ['no-supabase-write', 'No Supabase write made.', 'boundary', true, 'safe_metadata_only'],
] as const

export const MOCK_PROJECT_EDIT_BRIEF_ATTACHMENT_SCENARIOS: ProjectEditBriefAttachmentScenario[] = scenarioRows.map((row, index) => ({
  id: `rp_editbrief_08_attachment_${String(index + 1).padStart(2, '0')}_${row[0]}`,
  title: row[1],
  input: row[2],
  expectedOk: row[3],
  expectedSafetyStatus: row[4],
  expectedSideEffectsFalse: true,
  mockOnly: true,
}))

export function listMockProjectEditBriefAttachmentScenarios(): ProjectEditBriefAttachmentScenario[] {
  return [...MOCK_PROJECT_EDIT_BRIEF_ATTACHMENT_SCENARIOS]
}
