export const DESKTOP_CAPABILITY_PRIVACY_POLICY = {
  persistentDeviceIdentifier: 'blocked',
  hostname: 'blocked',
  username: 'blocked',
  macAddresses: 'blocked',
  rawNetworkInterfaces: 'blocked',
  exactCpuModelString: 'blocked_or_redacted',
  exactGpuAdapterIds: 'blocked',
  exactDiskPathList: 'blocked',
  directoryScanning: 'blocked',
  environmentVariableDump: 'blocked',
  processList: 'blocked',
  installedAppScan: 'blocked',
  localFileInventory: 'blocked',
  networkSpeedTest: 'blocked',
  heavyBenchmarks: 'blocked',
  telemetryUpload: 'blocked',
  localPersistenceByDefault: 'blocked',
  liveProfileUpload: 'blocked_until_future_explicit_phase',
  sessionTempOnly: true,
  routePlanningHintsOnly: true,
} as const
