import type { DesktopCapabilityFixture } from './desktopCapabilityProfileTypes'

const GIB = 1024 * 1024 * 1024

export const DESKTOP_CAPABILITY_FIXTURES: DesktopCapabilityFixture[] = [
  {
    fixtureId: 'fixture-desktop-high-local',
    description: 'High-capability Node desktop runtime with coarse CPU/memory/storage buckets and media helper commands present.',
    rawSignals: {
      runtimeKind: 'node_only',
      osPlatform: 'darwin',
      osArch: 'arm64',
      packagedAppStatus: 'dev',
      availableParallelism: 12,
      totalMemoryBytes: 32 * GIB,
      freeMemoryBytes: 12 * GIB,
      processCpuUsageAvailable: true,
      ffmpegAvailable: true,
      ffprobeAvailable: true,
      sharpAvailable: true,
      pythonAvailable: true,
      nodeVersionMajor: 22,
      tempDirWritable: true,
      estimatedFreeDiskBytes: 75 * GIB,
    },
    expectedHints: ['local_processing_candidate_but_execution_blocked', 'desktop_route_possible_future'],
    expectedWarnings: [],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-desktop-mid-no-ffmpeg',
    description: 'Mid-capability desktop where ffmpeg/ffprobe are unavailable, so media extraction remains server-worker preferred.',
    rawSignals: {
      runtimeKind: 'node_only',
      osPlatform: 'linux',
      osArch: 'x64',
      packagedAppStatus: 'dev',
      availableParallelism: 6,
      totalMemoryBytes: 16 * GIB,
      freeMemoryBytes: 5 * GIB,
      processCpuUsageAvailable: true,
      ffmpegAvailable: false,
      ffprobeAvailable: false,
      pythonAvailable: true,
      nodeVersionMajor: 22,
      tempDirWritable: true,
      estimatedFreeDiskBytes: 25 * GIB,
    },
    expectedHints: ['media_extraction_blocked_ffmpeg_unavailable'],
    expectedWarnings: ['media_extraction_tools_unavailable'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-desktop-low-resource',
    description: 'Low-resource desktop profile that should avoid local heavy processing and prefer server worker planning.',
    rawSignals: {
      runtimeKind: 'node_only',
      osPlatform: 'win32',
      osArch: 'x64',
      packagedAppStatus: 'dev',
      availableParallelism: 2,
      totalMemoryBytes: 4 * GIB,
      freeMemoryBytes: 750 * 1024 * 1024,
      processCpuUsageAvailable: true,
      ffmpegAvailable: 'unknown',
      ffprobeAvailable: 'unknown',
      nodeVersionMajor: 20,
      tempDirWritable: true,
      estimatedFreeDiskBytes: 8 * GIB,
    },
    expectedHints: ['low_resource_avoid_local_heavy_processing', 'server_worker_preferred'],
    expectedWarnings: ['low_parallelism_capacity', 'low_memory_capacity', 'low_free_memory'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-electron-sandboxed-renderer',
    description: 'Future Electron renderer profile where sandboxing requires a main-process bridge for any local capability expansion.',
    rawSignals: {
      runtimeKind: 'electron_renderer',
      osPlatform: 'darwin',
      osArch: 'arm64',
      packagedAppStatus: 'packaged',
      sandboxedRenderer: true,
      contextIsolation: true,
      availableParallelism: 8,
      totalMemoryBytes: 16 * GIB,
      freeMemoryBytes: 4 * GIB,
      ffmpegAvailable: 'unknown',
      ffprobeAvailable: 'unknown',
      nodeVersionMajor: 22,
      electronVersionMajor: 32,
      tempDirWritable: true,
      estimatedFreeDiskBytes: 20 * GIB,
    },
    expectedHints: ['renderer_sandbox_requires_main_process_bridge'],
    expectedWarnings: ['renderer_sandbox_requires_main_process_bridge'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-unknown-desktop',
    description: 'Unknown runtime/platform profile that must fail closed for route planning.',
    rawSignals: {
      runtimeKind: 'unknown',
      osPlatform: undefined,
      osArch: undefined,
      availableParallelism: undefined,
      totalMemoryBytes: undefined,
      freeMemoryBytes: undefined,
      tempDirWritable: 'unknown',
    },
    expectedHints: ['unknown_capability_fail_closed'],
    expectedWarnings: [],
    expectedBlockedReasons: ['unknown_desktop_runtime', 'unknown_os_platform', 'unknown_os_architecture', 'unknown_parallelism', 'unknown_memory'],
  },
]
