import type {
  ProjectEditBriefQAFindingType,
  ProjectEditBriefQAReadinessStatus,
  ProjectEditBriefQAScenario,
} from '../../types/project-edit-brief-qa'
import {
  PROJECT_EDIT_BRIEF_QA_SAFETY_FLAGS,
} from '../../lib/project-edit-brief-qa-rules'

const scenarioSeeds: Array<{
  title: string
  readiness: ProjectEditBriefQAReadinessStatus
  finding: ProjectEditBriefQAFindingType
}> = [
  { title: 'QA policy priority summary exists', readiness: 'not_checked', finding: 'policy_warning' },
  { title: 'Passed marker gets passed status', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Missing B-roll asset detected', readiness: 'blocked_by_missing_asset', finding: 'missing_asset' },
  { title: 'Missing music asset detected', readiness: 'blocked_by_missing_asset', finding: 'missing_asset' },
  { title: 'Missing SFX asset detected', readiness: 'blocked_by_missing_asset', finding: 'missing_asset' },
  { title: 'Missing voiceover asset detected', readiness: 'blocked_by_missing_asset', finding: 'missing_asset' },
  { title: 'Existing B-roll attachment satisfies requirement', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Existing music attachment satisfies requirement metadata-only', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Existing SFX attachment satisfies requirement metadata-only', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Vague marker needs clarification', readiness: 'needs_user_review', finding: 'needs_clarification' },
  { title: 'Low-confidence general instruction needs clarification', readiness: 'needs_user_review', finding: 'needs_clarification' },
  { title: 'Invalid negative start time blocked', readiness: 'failed_validation', finding: 'invalid_time_range' },
  { title: 'Invalid range end before start blocked', readiness: 'failed_validation', finding: 'invalid_time_range' },
  { title: 'Zero-length range warning', readiness: 'ready_with_warnings_mock', finding: 'invalid_time_range' },
  { title: 'Cut marker overlaps B-roll marker conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Cut marker overlaps keep marker conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Do-not-use marker overlaps action marker conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Music marker conflicts with no music marker', readiness: 'blocked_by_conflict', finding: 'audio_conflict' },
  { title: 'SFX marker conflicts with no fake sounds marker', readiness: 'blocked_by_conflict', finding: 'audio_conflict' },
  { title: 'Exact copy request copy-risk detected', readiness: 'blocked_by_copy_risk', finding: 'copy_risk' },
  { title: 'Exact reference recreation copy-risk detected', readiness: 'blocked_by_copy_risk', finding: 'copy_risk' },
  { title: 'Reference URL copy-risk warning detected', readiness: 'needs_user_review', finding: 'copy_risk' },
  { title: 'Caption marker with safe area disabled warning', readiness: 'ready_with_warnings_mock', finding: 'export_warning' },
  { title: 'Vertical caption-heavy marker with wide export warning', readiness: 'ready_with_warnings_mock', finding: 'export_warning' },
  { title: 'Custom export missing resolution warning', readiness: 'ready_with_warnings_mock', finding: 'export_warning' },
  { title: 'Brief with no markers not checked', readiness: 'not_checked', finding: 'policy_warning' },
  { title: 'Brief with all passed markers ready for plan mock', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Brief with warnings ready with warnings mock', readiness: 'ready_with_warnings_mock', finding: 'export_warning' },
  { title: 'Brief with needs asset blocked by missing asset', readiness: 'blocked_by_missing_asset', finding: 'missing_asset' },
  { title: 'Brief with conflict blocked by conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Brief with copy risk blocked by copy risk', readiness: 'blocked_by_copy_risk', finding: 'copy_risk' },
  { title: 'Marker QA package created', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Brief QA package created', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Conflict records created from findings', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Conflict record blocksPlan true for blocking conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'Conflict record requiresUserReview true', readiness: 'needs_user_review', finding: 'copy_risk' },
  { title: 'Readable QA summary works', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Marker QA summary works', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Finding summary works', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Debug summary works', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Validation passes valid finding', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Validation passes marker QA package', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Validation passes brief QA package', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Validation blocks provider flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'Validation blocks media processing flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'Validation blocks worker flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'Validation blocks generation flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'Validation blocks render flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'Validation blocks credit flag', readiness: 'failed_validation', finding: 'policy_warning' },
  { title: 'UI adapter loads QA package', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'UI adapter runs Brief QA', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'UI adapter runs marker QA', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'UI adapter saves conflicts via API', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'UI adapter updates marker QA status via API', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'QA summary model created', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Marker QA panel model created', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'QA badge model works for passed', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'QA badge model works for warning', readiness: 'ready_with_warnings_mock', finding: 'export_warning' },
  { title: 'QA badge model works for conflict', readiness: 'blocked_by_conflict', finding: 'overlap_conflict' },
  { title: 'QA badge model works for blocked', readiness: 'blocked_by_copy_risk', finding: 'copy_risk' },
  { title: 'Marker drawer shows QA panel', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Brief summary shows QA summary', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'Timeline marker shows QA badge', readiness: 'ready_with_warnings_mock', finding: 'policy_warning' },
  { title: 'No Qwen call made', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No DeepSeek call made', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No embeddings/vector DB used', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No provider call made', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No sound runtime/worker started', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No file bytes read', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No external URL fetched', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No media processing started', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No render/credit side effect', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'No Supabase write made', readiness: 'ready_for_plan_mock', finding: 'passed' },
  { title: 'Markers are not applied to plan', readiness: 'ready_for_plan_mock', finding: 'passed' },
]

export function listMockProjectEditBriefQAScenarios(): ProjectEditBriefQAScenario[] {
  return scenarioSeeds.map((seed, index) => ({
    id: `project-edit-brief-qa-scenario-${(index + 1).toString().padStart(2, '0')}`,
    title: seed.title,
    input: seed.title,
    expectedOk: seed.readiness !== 'failed_validation',
    expectedReadinessStatus: seed.readiness,
    expectedFindingType: seed.finding,
    expectedSideEffectsFalse: true,
    mockOnly: true,
    ...PROJECT_EDIT_BRIEF_QA_SAFETY_FLAGS,
  }))
}
