import { z } from 'zod'

import { canonicalPrivateToolDispatchCredentialSchema } from './canonical-private-tool-dispatch-schemas'
import { canonicalWorkerLeaseCredentialSchema } from './canonical-worker-lease-authority-schemas'

const identity = z.string().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._:-]*$/).refine((value) => value === value.trim() && !value.includes('..'))
const sha256 = z.string().regex(/^[a-f0-9]{64}$/); const timestamp = z.string().datetime({ offset: true }); const packageIdentity = z.string().min(1).max(120).regex(/^[A-Za-z0-9@/._+-]+$/)
const idempotencyKey = z.string().min(8).max(240).refine((value) => value === value.trim() && Array.from(value).every((character) => character.charCodeAt(0) > 31 && character.charCodeAt(0) !== 127))
export const runCanonicalPrivateContainerPackagingValidationSchema = z.object({ workspaceId: identity, projectId: identity, editSessionId: identity, jobId: identity, grantId: identity, purpose: z.literal('execute_canonical_private_container_packaging_validation'), idempotencyKey }).strict()
export const canonicalPrivateContainerPackagingValidationAuthoritySchema = z.object({ leaseId: identity, leaseCredential: canonicalWorkerLeaseCredentialSchema, dispatchCredential: canonicalPrivateToolDispatchCredentialSchema }).strict()
export const canonicalPrivateContainerPackagingValidationResponseSchema = z.object({
  schemaVersion: z.literal('canonical-private-container-packaging-validation-execution-response-v1'), source: z.literal('canonical_private_container_packaging_validation_execution_coordinator'), purpose: z.literal('execute_canonical_private_container_packaging_validation'),
  identity: z.object({ workspaceId: identity, projectId: identity, editSessionId: identity, snapshotId: identity, jobId: identity, approvedWorkItemId: identity, expectedAssetId: identity, dispatchGrantId: identity }).strict(),
  tool: z.object({ canonicalToolId: z.enum(['mkvtoolnix_container_validation', 'gpac_mp4box_packaging_validation']), operationId: identity, actualPackageEntrypointCompleted: z.literal(true), approvedServerOwnedFixtureOnly: z.literal(true), licenseReviewStillRequiredForProduction: z.literal(true), providerCallMade: z.literal(false), sourceObjectRead: z.literal(false), renderExecuted: z.literal(false), finalExportExecuted: z.literal(false) }).strict(),
  lease: z.object({ leaseId: identity, attemptNumber: z.number().int().positive().max(10), immutableLeaseHash: sha256, executionAttemptId: identity, runnerClass: z.literal('offline_container_packaging_validation_execution_v1'), executionStartedAt: timestamp, executionCommitAuthorizedAt: timestamp, executionCompletedAt: timestamp, credentialReturned: z.literal(false), credentialHashReturned: z.literal(false) }).strict(),
  runtime: z.object({ runtimeAuthorityHash: sha256, imageIdentityHash: sha256, executionAttestationHash: sha256, requestEnvelopeSha256: sha256, packageName: packageIdentity, packageVersion: packageIdentity, debianSnapshot: z.literal('20260623T000000Z'), zeroNetworkVerified: z.literal(true), privateInternalOnly: z.literal(true), productReady: z.literal(false), externalBetaReady: z.literal(false), productionReady: z.literal(false) }).strict(),
  result: z.object({ artifactId: identity, qaEvaluationId: identity, reconciliationId: identity, artifactVersion: z.number().int().positive(), contentType: z.literal('application/json'), sha256, byteLength: z.number().int().min(2).max(1024 * 1024), container: z.enum(['mkv', 'mp4']), trackCount: z.literal(3), videoTrackVerified: z.literal(true), audioTrackVerified: z.literal(true), captionTrackVerified: z.literal(true), privateObjectIdentityHash: sha256, qaOutcome: z.literal('passed'), reconciliationDecision: z.literal('test_merged_not_live_authorized'), privateTestDependencySatisfied: z.literal(true), liveRuntimeDependencySatisfied: z.literal(false), finalRenderAuthorized: z.literal(false) }).strict(),
  replay: z.object({ dispatchConsumptionReplayed: z.boolean(), executionFenceBeginReplayed: z.boolean(), executionFenceCompleteReplayed: z.boolean(), artifactRecordReplayed: z.boolean(), qaRecordReplayed: z.boolean(), reconciliationReplayed: z.boolean(), sameIdempotentAttemptOnly: z.literal(true) }).strict(),
  permissions: z.object({ furtherWorkerDispatch: z.literal(false), providerCall: z.literal(false), sourceObjectRead: z.literal(false), render: z.literal(false), creditSpend: z.literal(false), walletMutation: z.literal(false), settlement: z.literal(false), delivery: z.literal(false) }).strict(),
  persistence: z.object({ privateLocalCreateOnlyArtifact: z.literal(true), contentAddressedArtifactAuthority: z.literal(true), actualRunEvidenceVerified: z.literal(true), actualQaEvidenceVerified: z.literal(true), checksumProtectedAuthority: z.literal(true), distributedAuthority: z.literal(false), productionAuthority: z.literal(false) }).strict(),
  completedAt: timestamp, responseHash: sha256, testOnly: z.literal(true),
}).strict()
export type RunCanonicalPrivateContainerPackagingValidationInput = z.infer<typeof runCanonicalPrivateContainerPackagingValidationSchema>
export type CanonicalPrivateContainerPackagingValidationAuthority = z.infer<typeof canonicalPrivateContainerPackagingValidationAuthoritySchema>
export type CanonicalPrivateContainerPackagingValidationResponse = z.infer<typeof canonicalPrivateContainerPackagingValidationResponseSchema>
