import { z } from 'zod'
import {
  TOOL_COST_COMPUTE_LEVELS,
  TOOL_COST_FAILURE_CATEGORIES,
  TOOL_COST_PROVIDER_TYPES,
  TOOL_COST_QUALITY_LEVELS,
  TOOL_COST_USAGE_CATEGORIES,
} from '../tool-cost-metering/types'
import { idSchema } from './common-schemas'

const nullableStringSchema = z.string().min(1).nullable().optional()
const nonnegativeNumberSchema = z.number().finite().nonnegative()
const metadataSchema = z.record(z.string(), z.unknown()).optional()

export const toolCostEstimateSchema = z.object({
  toolId: z.string().min(1),
  toolName: z.string().min(1),
  usageCategory: z.enum(TOOL_COST_USAGE_CATEGORIES),
  computeLevel: z.enum(TOOL_COST_COMPUTE_LEVELS),
  providerType: z.enum(TOOL_COST_PROVIDER_TYPES),
  providerName: nullableStringSchema,
  modelName: nullableStringSchema,
  qualityLevel: z.enum(TOOL_COST_QUALITY_LEVELS),
  inputVideoSeconds: nonnegativeNumberSchema.optional(),
  outputVideoSeconds: nonnegativeNumberSchema.optional(),
  inputAudioSeconds: nonnegativeNumberSchema.optional(),
  outputAudioSeconds: nonnegativeNumberSchema.optional(),
  imageCount: z.number().int().nonnegative().optional(),
  estimatedRuntimeSeconds: nonnegativeNumberSchema.optional(),
  resolution: z.string().min(1).optional(),
  frameRate: nonnegativeNumberSchema.optional(),
  inputTokens: z.number().int().nonnegative().optional(),
  outputTokens: z.number().int().nonnegative().optional(),
  renderDurationSeconds: nonnegativeNumberSchema.optional(),
  vcpuCount: nonnegativeNumberSchema.optional(),
  memoryGiB: nonnegativeNumberSchema.optional(),
  gpuType: nullableStringSchema,
  gpuCount: z.number().int().nonnegative().optional(),
  temporaryStorageGiBHours: nonnegativeNumberSchema.optional(),
  outputStorageGiBHours: nonnegativeNumberSchema.optional(),
  networkEgressMiB: nonnegativeNumberSchema.optional(),
  approvedReservationRemainingCredits: z.number().int().nonnegative().optional(),
  providerOptions: z.array(z.string().min(1)).optional(),
  assumptions: z.array(z.string().min(1)).optional(),
  metadata: metadataSchema,
}).strict()

export const toolCostEventSchema = z.object({
  id: z.string().min(1).optional(),
  workspaceId: idSchema,
  projectId: idSchema,
  editPlanId: idSchema.nullable().optional(),
  jobId: idSchema.nullable().optional(),
  jobBatchId: idSchema.nullable().optional(),
  generationRequestId: idSchema.nullable().optional(),
  renderJobId: idSchema.nullable().optional(),
  creditEstimateId: idSchema.nullable().optional(),
  creditReservationId: idSchema.nullable().optional(),
  toolId: z.string().min(1),
  toolName: z.string().min(1),
  usageCategory: z.enum(TOOL_COST_USAGE_CATEGORIES),
  providerType: z.enum(TOOL_COST_PROVIDER_TYPES),
  providerName: nullableStringSchema,
  modelName: nullableStringSchema,
  qualityLevel: z.enum(TOOL_COST_QUALITY_LEVELS),
  startedAt: z.string().min(1),
  completedAt: z.string().min(1),
  wallClockMs: nonnegativeNumberSchema,
  billableMs: nonnegativeNumberSchema.optional(),
  vcpuCount: nonnegativeNumberSchema.optional(),
  memoryGiB: nonnegativeNumberSchema.optional(),
  gpuType: nullableStringSchema,
  gpuCount: z.number().int().nonnegative().optional(),
  inputTokens: z.number().int().nonnegative().optional(),
  outputTokens: z.number().int().nonnegative().optional(),
  inputVideoSeconds: nonnegativeNumberSchema.optional(),
  outputVideoSeconds: nonnegativeNumberSchema.optional(),
  inputAudioSeconds: nonnegativeNumberSchema.optional(),
  outputAudioSeconds: nonnegativeNumberSchema.optional(),
  imageCount: z.number().int().nonnegative().optional(),
  renderDurationSeconds: nonnegativeNumberSchema.optional(),
  outputResolution: z.string().min(1).nullable().optional(),
  outputFrameRate: nonnegativeNumberSchema.optional(),
  estimatedInternalCostCents: z.number().int().nonnegative().optional(),
  retryAttempt: z.number().int().nonnegative().optional(),
  retryReason: nullableStringSchema,
  failureCategory: z.enum(TOOL_COST_FAILURE_CATEGORIES).optional(),
  billableToUser: z.boolean().optional(),
  approvedReservationRemainingCredits: z.number().int().nonnegative().optional(),
  temporaryStorageGiBHours: nonnegativeNumberSchema.optional(),
  outputStorageGiBHours: nonnegativeNumberSchema.optional(),
  networkEgressMiB: nonnegativeNumberSchema.optional(),
  metadata: metadataSchema,
}).strict()
