import { z } from 'zod'
import { idSchema } from './common-schemas'
import { productionToolIdSchema } from './tool-cost-schemas'

export const trackbAgentToolExecutionSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  jobId: idSchema,
  agentInvocationId: z.string().regex(/^trackb\.media_oss\.[a-z0-9_]+$/),
  toolId: productionToolIdSchema.optional(),
  action: z.string().min(1),
  approvedSnapshotId: idSchema,
  toolExecutionPlanId: idSchema,
  editPlanId: idSchema.optional(),
  mediaAssetId: idSchema.optional(),
  mediaAnalysisReportId: idSchema.optional(),
  mode: z.enum(['mock_safe_worker_dispatch', 'frontend_preview_boundary', 'deployed_live_execution']).optional(),
  requestedRecipeIds: z.array(z.string().min(1)).optional(),
  storageReferenceIds: z.array(z.string().min(1)).optional(),
  approvedPreviewStateReference: z.string().min(1).optional(),
  requiredQualityGateIds: z.array(z.string().min(1)).optional(),
  requiredQualityGateTypes: z.array(z.enum([
    'caption_readability',
    'caption_timing',
    'caption_safe_zone',
    'cut_smoothness',
    'transcript_alignment',
    'audio_loudness',
    'audio_sync',
    'audio_naturalness',
    'music_over_voice',
    'color_exposure',
    'color_skin_tone',
    'color_export_space',
    'color_shot_match',
    'mask_edge_quality',
    'mask_temporal_stability',
    'mask_subject_coverage',
    'ocr_text_overlap',
    'enhancement_artifacts',
    'slow_motion_artifacts',
    'render_asset_integrity',
    'render_timeline_integrity',
    'export_codec_format',
    'export_duration_sync',
    'final_delivery',
  ])).optional(),
  renderMode: z.enum(['preview', 'final_export', 'qa_probe']).optional(),
  workerInstanceId: z.string().min(1).optional(),
  attempt: z.number().int().positive().optional(),
  maxAttempts: z.number().int().positive().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
}).strict()
