import { z } from 'zod'
import { idSchema } from './common-schemas'

export const claimWorkerJobSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema.optional(),
  workerType: z.string().min(1),
  workerInstanceId: z.string().min(1),
  leaseExpiresAt: z.string().min(1),
})

export const releaseWorkerJobSchema = z.object({
  workspaceId: idSchema.optional(),
  claimStatus: z.enum(['released', 'completed', 'failed', 'expired', 'cancelled']).default('released'),
})

export const recordToolRuntimeCheckSchema = z.object({
  workspaceId: idSchema,
  workerType: z.string().min(1),
  runtimeRegion: z.enum(['us-east1', 'europe-west1']).optional(),
  toolName: z.enum(['ffmpeg', 'ffprobe', 'remotion', 'sharp_libvips', 'audioflux', 'signalsmith_stretch', 'opencv', 'vapoursynth', 'playwright']),
  toolVersion: z.string().optional(),
  checkStatus: z.enum(['passed', 'warning', 'failed', 'missing', 'blocked']),
  checkSummary: z.string().min(1),
  binaryPath: z.string().optional(),
  capabilitiesJson: z.record(z.string(), z.unknown()).optional(),
})

export const toolReadinessCheckSchema = z.object({
  workspaceId: idSchema.optional(),
  workerType: z.string().min(1).optional(),
  toolName: z.enum(['ffmpeg', 'ffprobe', 'remotion', 'sharp_libvips', 'audioflux', 'signalsmith_stretch', 'opencv', 'vapoursynth', 'playwright']).optional(),
  recordResults: z.boolean().optional(),
}).strict()

export const runWorkerJobSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema.optional(),
  workerType: z.string().min(1),
  workerInstanceId: z.string().min(1).optional(),
  idempotencyKey: z.string().min(1),
  dryRun: z.boolean().optional(),
  jobType: z.string().min(1).optional(),
  approvedPlanSnapshotId: idSchema.optional(),
  creditReservationId: idSchema.optional(),
  mediaAssetId: idSchema.optional(),
  storageObjectRecordId: idSchema.optional(),
  payloadJson: z.record(z.string(), z.unknown()).optional(),
}).strict()

export const probeMediaJobSchema = runWorkerJobSchema.extend({
  workerType: z.string().min(1).default('media_probe_worker'),
  jobType: z.string().min(1).default('media_analysis'),
}).strict()

const gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates = [
  'gst_fakesrc_fakesink_no_media_healthcheck_v1',
  'gst_controlled_generated_fixture_pipeline_v1',
  'mkvmerge_generated_subtitle_only_package_v1',
  'mkvmerge_identify_generated_subtitle_only_v1',
] as const

const gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates =
  gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates

const gpacMp4boxGeneratedFixtureCommandTemplates = [
  'mp4box_add_generated_subtitle_only_v1',
  'mp4box_info_generated_subtitle_only_v1',
  'mp4box_package_validation_metadata_v1',
] as const

const gpacMp4boxExecutionReadyRouteWorkerBridgeCommandTemplates = [
  'mp4box_add_generated_subtitle_only_v1',
  'mp4box_info_generated_subtitle_only_v1',
] as const

export const gstreamerMkvtoolnixNarrowExecutionReadyRouteWorkerBridgeSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvalRecordId: idSchema,
  creditOrNoSpendPolicyId: idSchema,
  jobId: idSchema,
  workerLeaseId: idSchema,
  workerEnvelopeId: idSchema,
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  runtimeExecutionMode: z.literal('controlled_generated_fixture_runtime_execution'),
  fixtureScope: z.literal('generated_srt_and_generated_subtitle_only_mkv_fixture'),
  routeOwner: z.literal('backend_service_role_only'),
  routeBridgeMode: z.literal('delegates_existing_guarded_runtime_packet'),
  commandTemplates: z.tuple([
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[0]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[1]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[2]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[3]),
  ]),
  privateInputManifestId: idSchema,
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  nonPublicArtifactPolicyId: idSchema,
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gpacMp4boxExecutionReadyRouteWorkerBridgeSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvalRecordId: idSchema,
  creditOrNoSpendPolicyId: idSchema,
  jobId: idSchema,
  workerLeaseId: idSchema,
  workerEnvelopeId: idSchema,
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  runtimeExecutionMode: z.literal('controlled_generated_fixture_runtime_execution'),
  fixtureScope: z.literal('generated_srt_to_subtitle_only_mp4_fixture'),
  routeOwner: z.literal('backend_service_role_only'),
  routeBridgeMode: z.literal('delegates_existing_gpac_mp4box_generated_fixture_runtime_packet'),
  commandTemplates: z.tuple([
    z.literal(gpacMp4boxExecutionReadyRouteWorkerBridgeCommandTemplates[0]),
    z.literal(gpacMp4boxExecutionReadyRouteWorkerBridgeCommandTemplates[1]),
  ]),
  privateInputManifestId: idSchema,
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  nonPublicArtifactPolicyId: idSchema,
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotJobQueueHandoffSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvedSnapshotStatus: z.literal('approved'),
  approvalRecordId: idSchema,
  approvalRecordStatus: z.literal('approved'),
  creditOrNoSpendPolicyId: idSchema,
  creditPolicyMode: z.literal('no_spend_generated_fixture_policy'),
  jobId: idSchema,
  queueId: idSchema,
  queueIdempotencyKey: z.string().min(1),
  routeIdempotencyKey: z.string().min(1),
  workerLeaseId: idSchema,
  workerEnvelopeId: idSchema,
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  fixtureScope: z.literal('generated_srt_and_generated_subtitle_only_mkv_fixture'),
  queueHandoffMode: z.literal('local_mock_queue_handoff_only'),
  routeOwner: z.literal('backend_service_role_only'),
  routeBridgeMode: z.literal('queued_handoff_to_existing_guarded_runtime_route'),
  commandTemplates: z.tuple([
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[0]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[1]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[2]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[3]),
  ]),
  privateInputManifestId: idSchema,
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  nonPublicArtifactPolicyId: idSchema,
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  runtimeRouteExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  gstreamerExecutionRequestedNow: z.boolean().optional(),
  mkvtoolnixExecutionRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  remotionExecutionRequestedNow: z.boolean().optional(),
  mediaProcessingRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema =
  gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotJobQueueHandoffSchema.extend({
    invocationId: idSchema,
    invocationIdempotencyKey: z.string().min(1),
    invocationMode: z.literal('queued_job_payload_to_existing_runtime_route_delegate'),
    runtimeRouteInvocationConfirmed: z.boolean(),
  }).strict()

export const gstreamerMkvtoolnixPersistedJobRuntimeHandoffSchema =
  gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema.extend({
    persistedHandoffId: idSchema,
    persistedJobHandoffMode: z.literal('backend_job_service_handoff_no_runtime_execution'),
    persistedJobWriteConfirmed: z.boolean(),
    jobBatchName: z.string().optional(),
    persistedJobWriteRequestedNow: z.boolean().optional(),
    runtimeRouteInvocationRequestedNow: z.boolean().optional(),
  }).strict()

const gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema = z.object({
  persistedHandoffId: idSchema,
  packet: z.literal('RP-EXTERNAL-BETA-GSTREAMER-MKVTOOLNIX-PERSISTED-JOB-RUNTIME-HANDOFF-1'),
  persistedJobPayloadKind: z.literal('gstreamer_mkvtoolnix_generated_fixture_runtime').optional(),
  runtimeInvocationRoutePath: z.literal('/v1/external-beta/gstreamer-mkvtoolnix/narrow-agent/generated-fixture-runtime/approved-snapshot/jobs/invoke'),
  runtimeInvocationIdempotencyKey: z.string().min(1),
  runtimeInvocationBody: gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema,
  queueHandoff: z.record(z.string(), z.unknown()).optional(),
  safety: z.record(z.string(), z.unknown()).optional(),
}).strict()

export const gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  persistedInvocationId: idSchema,
  persistedJobId: idSchema,
  persistedJobType: z.literal('quality_check'),
  persistedJobPayloadMode: z.literal('persisted_job_payload_to_existing_runtime_route_delegate'),
  persistedJobPayloadJson: gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema,
  persistedJobRuntimeRouteInvocationConfirmed: z.boolean(),
  routeIdempotencyKey: z.string().min(1),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gpacMp4boxGuardedRuntimeDispatchRouteEnablementSourceSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvedSnapshotStatus: z.literal('approved'),
  approvalRecordId: idSchema,
  approvalRecordStatus: z.literal('approved'),
  creditReservationId: idSchema,
  creditReservationStatus: z.literal('approved'),
  jobId: idSchema,
  jobStatus: z.enum(['planned', 'approved']),
  workerLeaseId: idSchema,
  workerLeaseStatus: z.literal('active'),
  sourceSequenceMapId: idSchema,
  compiledIntentId: idSchema,
  modelRoutingPolicyId: idSchema,
  qaPolicyId: idSchema,
  cleanupPolicyId: idSchema,
  cleanupPolicyStatus: z.literal('approved'),
  cleanupStatus: z.enum(['cleanup_verified', 'cleanup_required']),
  auditRecordId: idSchema,
  privateInputManifestId: idSchema,
  privateInputManifestSourceClass: z.literal('generated_fixture'),
  privateInputStorageObjectPath: z.string().min(1),
  privateInputChecksumSha256: z.string().min(32),
  privateInputByteCount: z.number().int().positive(),
  privateArtifactManifestId: idSchema,
  privateArtifactStorageObjectPrefix: z.string().min(1),
  privateArtifactExpectedOutputFileNames: z.array(z.string().min(1)).min(1),
  privateArtifactChecksumId: idSchema,
  toolRuntimePolicyId: idSchema,
  gpacMp4boxWorkerContractId: idSchema,
  gpacMp4boxRouteContractId: idSchema,
  commandTemplateId: z.enum(gpacMp4boxGeneratedFixtureCommandTemplates),
  routeIdempotencyKey: z.string().min(1),
  routeSourceMode: z.literal('guarded_route_source_to_mock_queue_handoff_only'),
  routeOwner: z.literal('backend_service_role_only'),
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  frontendFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  gpacMp4boxExecutionRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  remotionExecutionRequestedNow: z.boolean().optional(),
  mediaProcessingRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  storageTransferRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixPersistedJobWorkerDispatchClaimLeaseSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  persistedInvocationId: idSchema,
  persistedJobId: idSchema,
  persistedJobType: z.literal('quality_check'),
  persistedJobPayloadMode: z.literal('persisted_job_payload_to_worker_claim_lease'),
  persistedJobPayloadJson: gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema,
  persistedJobWorkerClaimLeaseConfirmed: z.boolean(),
  remoteWorkerClaimLeaseConfirmed: z.boolean().optional(),
  workerType: z.literal('gstreamer_mkvtoolnix_generated_fixture_worker'),
  workerInstanceId: z.string().min(1),
  leaseExpiresAt: z.string().min(1),
  claimLeaseMode: z.enum([
    'local_mock_claim_lease_no_worker_execution',
    'remote_supabase_worker_claim_lease_no_worker_execution',
  ]),
  routeIdempotencyKey: z.string().min(1),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  gstreamerExecutionRequestedNow: z.boolean().optional(),
  mkvtoolnixExecutionRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  remotionExecutionRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const threeToolExternalAgentPersistedJobRuntimeHandoffSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  editSessionId: idSchema,
  approvedSnapshotId: idSchema,
  approvedSnapshotStatus: z.literal('approved'),
  approvalRecordId: idSchema,
  approvalRecordStatus: z.literal('approved'),
  creditPolicyRef: idSchema,
  creditPolicyMode: z.enum(['no_spend_fixture_policy', 'credit_reservation']),
  creditPolicyStatus: z.enum(['approved', 'reserved']),
  jobId: idSchema,
  jobStatus: z.enum(['queued', 'leased', 'planned']),
  workerLeaseId: idSchema,
  workerLeaseStatus: z.enum(['claimed', 'disabled', 'planned']),
  routeIdempotencyKey: z.string().min(1),
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  privateInputManifestId: idSchema,
  privateInputManifestSha256: z.string().min(32),
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  auditEventParentId: idSchema,
  combinedExecutionRunId: z.literal('2026-07-02T23-06-37-783Z-735edf80'),
  combinedExecutionQaMergeSha: z.literal('13c922b3cc8d40223920c45bb800729dbbe3e7b5'),
  gstreamerMkvtoolnixRunId: z.literal('2026-07-02T23-06-37-953Z-ee1ebbec'),
  gpacMp4boxRunId: z.literal('2026-07-02T23-06-42-095Z-21ff9b93'),
  gstreamerMkvtoolnixCommandTemplates: z.tuple([
    z.literal('gst_fakesrc_fakesink_no_media_healthcheck_v1'),
    z.literal('gst_controlled_generated_fixture_pipeline_v1'),
    z.literal('mkvmerge_generated_subtitle_only_package_v1'),
    z.literal('mkvmerge_identify_generated_subtitle_only_v1'),
  ]),
  gpacMp4boxCommandTemplates: z.tuple([
    z.literal('mp4box_add_generated_subtitle_only_v1'),
    z.literal('mp4box_info_generated_subtitle_only_v1'),
  ]),
  confirmation: z.boolean(),
  persistedHandoffId: idSchema,
  persistedJobHandoffMode: z.literal('local_mock_job_service_handoff_no_remote_mutation'),
  persistedJobWriteConfirmed: z.boolean(),
  jobBatchName: z.string().optional().nullable(),
  approvedSnapshotJobExecutionRunId: z.literal('2026-07-03T03-41-30-494Z-41a3b873'),
  approvedSnapshotJobExecutionChildRunId: z.literal('2026-07-03T03-41-30-650Z-41ce5185'),
  approvedSnapshotJobExecutionDecision: z.literal('completed_three_tool_external_agent_approved_snapshot_job_execution'),
  approvedSnapshotJobExecutionRecordPath: z.literal(
    'docs/external-beta/tracka-three-tool-external-agent-approved-snapshot-job-execution-1/tracka-three-tool-external-agent-approved-snapshot-job-execution-1-record.json',
  ),
  rawCommandString: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  publicUrlSourceOfTruth: z.string().optional().nullable(),
  signedUrlSourceOfTruth: z.string().optional().nullable(),
  arbitraryPrivateMediaRef: z.string().optional().nullable(),
  ffmpegFfprobeExpansionRequested: z.boolean().optional(),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  gstreamerExecutionRequestedNow: z.boolean().optional(),
  mkvtoolnixExecutionRequestedNow: z.boolean().optional(),
  gpacMp4boxExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  dockerPushDeployRequestedNow: z.boolean().optional(),
  remotionRenderRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaExpansionRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
  packageInstallationRequestedNow: z.boolean().optional(),
  dependencyMutationRequestedNow: z.boolean().optional(),
}).strict()
