import { z } from 'zod'
import { idSchema } from './common-schemas'

export const claimWorkerJobSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema.optional(),
  workerType: z.string().min(1),
  workerInstanceId: z.string().min(1),
  leaseExpiresAt: z.string().min(1),
})

export const releaseWorkerJobSchema = z.object({
  workspaceId: idSchema.optional(),
  claimStatus: z.enum(['released', 'completed', 'failed', 'expired', 'cancelled']).default('released'),
})

export const recordToolRuntimeCheckSchema = z.object({
  workspaceId: idSchema,
  workerType: z.string().min(1),
  runtimeRegion: z.enum(['us-east1', 'europe-west1']).optional(),
  toolName: z.enum(['ffmpeg', 'ffprobe', 'remotion', 'sharp_libvips', 'audioflux', 'signalsmith_stretch', 'opencv', 'vapoursynth', 'playwright']),
  toolVersion: z.string().optional(),
  checkStatus: z.enum(['passed', 'warning', 'failed', 'missing', 'blocked']),
  checkSummary: z.string().min(1),
  binaryPath: z.string().optional(),
  capabilitiesJson: z.record(z.string(), z.unknown()).optional(),
})

export const toolReadinessCheckSchema = z.object({
  workspaceId: idSchema.optional(),
  workerType: z.string().min(1).optional(),
  toolName: z.enum(['ffmpeg', 'ffprobe', 'remotion', 'sharp_libvips', 'audioflux', 'signalsmith_stretch', 'opencv', 'vapoursynth', 'playwright']).optional(),
  recordResults: z.boolean().optional(),
}).strict()

export const runWorkerJobSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema.optional(),
  workerType: z.string().min(1),
  workerInstanceId: z.string().min(1).optional(),
  idempotencyKey: z.string().min(1),
  dryRun: z.boolean().optional(),
  jobType: z.string().min(1).optional(),
  approvedPlanSnapshotId: idSchema.optional(),
  creditReservationId: idSchema.optional(),
  mediaAssetId: idSchema.optional(),
  storageObjectRecordId: idSchema.optional(),
  payloadJson: z.record(z.string(), z.unknown()).optional(),
}).strict()

export const probeMediaJobSchema = runWorkerJobSchema.extend({
  workerType: z.string().min(1).default('media_probe_worker'),
  jobType: z.string().min(1).default('media_analysis'),
}).strict()

const gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates = [
  'gst_fakesrc_fakesink_no_media_healthcheck_v1',
  'gst_controlled_generated_fixture_pipeline_v1',
  'mkvmerge_generated_subtitle_only_package_v1',
  'mkvmerge_identify_generated_subtitle_only_v1',
] as const

const gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates =
  gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates

export const gstreamerMkvtoolnixNarrowExecutionReadyRouteWorkerBridgeSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvalRecordId: idSchema,
  creditOrNoSpendPolicyId: idSchema,
  jobId: idSchema,
  workerLeaseId: idSchema,
  workerEnvelopeId: idSchema,
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  runtimeExecutionMode: z.literal('controlled_generated_fixture_runtime_execution'),
  fixtureScope: z.literal('generated_srt_and_generated_subtitle_only_mkv_fixture'),
  routeOwner: z.literal('backend_service_role_only'),
  routeBridgeMode: z.literal('delegates_existing_guarded_runtime_packet'),
  commandTemplates: z.tuple([
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[0]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[1]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[2]),
    z.literal(gstreamerMkvtoolnixNarrowExecutionReadyCommandTemplates[3]),
  ]),
  privateInputManifestId: idSchema,
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  nonPublicArtifactPolicyId: idSchema,
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotJobQueueHandoffSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  approvedSnapshotStatus: z.literal('approved'),
  approvalRecordId: idSchema,
  approvalRecordStatus: z.literal('approved'),
  creditOrNoSpendPolicyId: idSchema,
  creditPolicyMode: z.literal('no_spend_generated_fixture_policy'),
  jobId: idSchema,
  queueId: idSchema,
  queueIdempotencyKey: z.string().min(1),
  routeIdempotencyKey: z.string().min(1),
  workerLeaseId: idSchema,
  workerEnvelopeId: idSchema,
  runtimePacketId: idSchema,
  runtimeExecutionId: idSchema,
  fixtureScope: z.literal('generated_srt_and_generated_subtitle_only_mkv_fixture'),
  queueHandoffMode: z.literal('local_mock_queue_handoff_only'),
  routeOwner: z.literal('backend_service_role_only'),
  routeBridgeMode: z.literal('queued_handoff_to_existing_guarded_runtime_route'),
  commandTemplates: z.tuple([
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[0]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[1]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[2]),
    z.literal(gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotHandoffCommandTemplates[3]),
  ]),
  privateInputManifestId: idSchema,
  outputManifestSchemaId: idSchema,
  qaReportSchemaId: idSchema,
  cleanupPolicyId: idSchema,
  retentionPolicyId: idSchema,
  failurePolicyId: idSchema,
  nonPublicArtifactPolicyId: idSchema,
  confirmation: z.boolean(),
  rawCommand: z.string().optional().nullable(),
  rawChat: z.string().optional().nullable(),
  arbitraryFilePath: z.string().optional().nullable(),
  privateMediaPath: z.string().optional().nullable(),
  userMediaPath: z.string().optional().nullable(),
  publicUrl: z.string().optional().nullable(),
  signedUrl: z.string().optional().nullable(),
  runtimeRouteExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  gstreamerExecutionRequestedNow: z.boolean().optional(),
  mkvtoolnixExecutionRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  remotionExecutionRequestedNow: z.boolean().optional(),
  mediaProcessingRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema =
  gstreamerMkvtoolnixGeneratedFixtureApprovedSnapshotJobQueueHandoffSchema.extend({
    invocationId: idSchema,
    invocationIdempotencyKey: z.string().min(1),
    invocationMode: z.literal('queued_job_payload_to_existing_runtime_route_delegate'),
    runtimeRouteInvocationConfirmed: z.boolean(),
  }).strict()

export const gstreamerMkvtoolnixPersistedJobRuntimeHandoffSchema =
  gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema.extend({
    persistedHandoffId: idSchema,
    persistedJobHandoffMode: z.literal('backend_job_service_handoff_no_runtime_execution'),
    persistedJobWriteConfirmed: z.boolean(),
    jobBatchName: z.string().optional(),
    persistedJobWriteRequestedNow: z.boolean().optional(),
    runtimeRouteInvocationRequestedNow: z.boolean().optional(),
  }).strict()

const gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema = z.object({
  persistedHandoffId: idSchema,
  packet: z.literal('RP-EXTERNAL-BETA-GSTREAMER-MKVTOOLNIX-PERSISTED-JOB-RUNTIME-HANDOFF-1'),
  runtimeInvocationRoutePath: z.literal('/v1/external-beta/gstreamer-mkvtoolnix/narrow-agent/generated-fixture-runtime/approved-snapshot/jobs/invoke'),
  runtimeInvocationIdempotencyKey: z.string().min(1),
  runtimeInvocationBody: gstreamerMkvtoolnixGeneratedFixtureQueuedJobRuntimeRouteInvocationSchema,
  queueHandoff: z.record(z.string(), z.unknown()).optional(),
  safety: z.record(z.string(), z.unknown()).optional(),
}).strict()

export const gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  persistedInvocationId: idSchema,
  persistedJobId: idSchema,
  persistedJobType: z.literal('gstreamer_mkvtoolnix_generated_fixture_runtime'),
  persistedJobPayloadMode: z.literal('persisted_job_payload_to_existing_runtime_route_delegate'),
  persistedJobPayloadJson: gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema,
  persistedJobRuntimeRouteInvocationConfirmed: z.boolean(),
  routeIdempotencyKey: z.string().min(1),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  workerLeaseClaimRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()

export const gstreamerMkvtoolnixPersistedJobWorkerDispatchClaimLeaseSchema = z.object({
  workspaceId: idSchema,
  projectId: idSchema,
  approvedSnapshotId: idSchema,
  persistedInvocationId: idSchema,
  persistedJobId: idSchema,
  persistedJobType: z.literal('gstreamer_mkvtoolnix_generated_fixture_runtime'),
  persistedJobPayloadMode: z.literal('persisted_job_payload_to_worker_claim_lease'),
  persistedJobPayloadJson: gstreamerMkvtoolnixPersistedJobRuntimeRouteInvocationPayloadSchema,
  persistedJobWorkerClaimLeaseConfirmed: z.boolean(),
  workerType: z.literal('gstreamer_mkvtoolnix_generated_fixture_worker'),
  workerInstanceId: z.string().min(1),
  leaseExpiresAt: z.string().min(1),
  claimLeaseMode: z.literal('local_mock_claim_lease_no_worker_execution'),
  routeIdempotencyKey: z.string().min(1),
  routeExecutionRequestedNow: z.boolean().optional(),
  workerDispatchRequestedNow: z.boolean().optional(),
  workerExecutionRequestedNow: z.boolean().optional(),
  workerProcessStartRequestedNow: z.boolean().optional(),
  persistentJobQueueWriteRequestedNow: z.boolean().optional(),
  privateMediaProcessingRequestedNow: z.boolean().optional(),
  userMediaProcessingRequestedNow: z.boolean().optional(),
  gstreamerExecutionRequestedNow: z.boolean().optional(),
  mkvtoolnixExecutionRequestedNow: z.boolean().optional(),
  ffmpegFfprobeExecutionRequestedNow: z.boolean().optional(),
  dockerExecutionRequestedNow: z.boolean().optional(),
  remotionExecutionRequestedNow: z.boolean().optional(),
  supabaseMutationRequestedNow: z.boolean().optional(),
  sqlExecutionRequestedNow: z.boolean().optional(),
  secretPayloadAccessRequestedNow: z.boolean().optional(),
  serviceRoleSecretPayloadAccessRequestedNow: z.boolean().optional(),
  signedUrlCreationRequestedNow: z.boolean().optional(),
  publicArtifactRequestedNow: z.boolean().optional(),
  finalRenderExportRequestedNow: z.boolean().optional(),
  externalBetaUnlockRequestedNow: z.boolean().optional(),
  paidProductionUnlockRequestedNow: z.boolean().optional(),
  productionUnlockRequestedNow: z.boolean().optional(),
}).strict()
