import { expect, test } from '@playwright/test'
import { expectNoHorizontalOverflow, setViewport } from './helpers/layout'
import { gotoRoute } from './helpers/routes'

test.describe('Project Edit Brief internal testing entrypoint', () => {
  test('opens the internal testing console and launches the Edit Brief route safely', async ({ page }) => {
    await setViewport(page, 1440)
    await gotoRoute(page, '/internal-testing')

    await expect(page.getByTestId('internal-testing-page')).toBeVisible()
    await expect(page.getByTestId('internal-testing-status-card')).toContainText('Repeated internal testing is wired')
    await expect(page.getByTestId('internal-testing-boundary-card')).toContainText('No runtime side effects')
    await expect(page.getByTestId('internal-testing-boundary-list')).toContainText('Local preview ready')
    await expect(page.getByTestId('internal-testing-boundary-list')).toContainText('Backend upload gated')
    await expect(page.getByTestId('internal-testing-boundary-list')).toContainText('No provider')
    await expect(page.getByTestId('internal-testing-boundary-list')).toContainText('No worker')
    await expect(page.getByTestId('internal-testing-boundary-list')).toContainText('No credits')
    await expect(page.getByTestId('internal-testing-scenario-summary')).toContainText('mock local')
    await expect(page.getByTestId('internal-testing-scenario-summary')).toContainText('blocked')
    await expect(page.getByTestId('internal-testing-scenario-summary')).toContainText('0')
    await expect(page.getByTestId('internal-testing-preference-video-limits')).toContainText('Preference Video limits')
    await expect(page.getByTestId('internal-testing-preference-video-limits')).toContainText('Mock-local Preference DNA')
    await expect(page.getByTestId('internal-testing-preference-video-limits')).toContainText('Still blocked until later gates')
    await expect(page.getByTestId('internal-testing-preference-video-limits')).toContainText('Open /edit-preferences')
    await expect(page.getByTestId('internal-testing-approval-credit-gates')).toContainText('Approval and credit gates')
    await expect(page.getByTestId('internal-testing-approval-credit-gate-list')).toContainText('approvedPlanSnapshotId')
    await expect(page.getByTestId('internal-testing-approval-credit-gate-list')).toContainText('creditEstimateId')
    await expect(page.getByTestId('internal-testing-approval-credit-gate-list')).toContainText('creditReservationId')
    await expect(page.getByTestId('internal-testing-credit-lifecycle-readiness')).toContainText('Credit lifecycle')
    await expect(page.getByTestId('internal-testing-credit-lifecycle-list')).toContainText('Spend reserved credits')
    await expect(page.getByTestId('internal-testing-credit-lifecycle-list')).toContainText('Release reservation')
    await expect(page.getByTestId('internal-testing-credit-lifecycle-list')).toContainText('Refund credits')
    await expect(page.getByTestId('internal-testing-credit-lifecycle-boundaries')).toContainText('No silent billing')
    await expect(page.getByTestId('internal-testing-repeated-local-operator-harness')).toContainText('Operator harness')
    await expect(page.getByTestId('internal-testing-operator-sequence')).toContainText('npm run qa:internal-testing')
    await expect(page.getByTestId('internal-testing-operator-sequence')).toContainText('Approval IDs and credit lifecycle')
    await expect(page.getByTestId('internal-testing-operator-boundaries')).toContainText('No tool execution')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Source video test path')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Signed local loop')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('VITE_REEDITPRO_INTERNAL_TEST_AUTH=true')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Browser-local source video preview')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Backend-local upload records canonical bucket/object metadata only')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Run local edit preview')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Qwen 3.7 Max Marker Chat readiness')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('VITE_REEDITPRO_SOURCE_VIDEO_BACKEND_UPLOAD=true')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('Sign in then open Brief')
    await expect(page.getByTestId('internal-testing-source-video-flow')).toContainText('/sign-in?redirect=')
    await expect(page.getByTestId('internal-testing-tool-routing-readiness')).toContainText('Edit activity routing')
    await expect(page.getByTestId('internal-testing-tool-routing-readiness')).toContainText('Source preparation')
    await expect(page.getByTestId('internal-testing-tool-routing-readiness')).toContainText('Speech and captions')
    await expect(page.getByTestId('internal-testing-tool-routing-readiness')).toContainText('Private review build')
    await expect(page.getByTestId('internal-testing-tool-routing-boundaries')).toContainText('Approved snapshot required')
    await expect(page.getByTestId('internal-testing-tool-routing-boundaries')).toContainText('No frontend execution')
    await expect(page.getByTestId('internal-testing-tool-routing-boundaries')).toContainText('No worker dispatch')
    await expect(page.getByTestId('internal-testing-tool-routing-readiness')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review')).toContainText('Approved route review')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review')).toContainText('Source upload finalized')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review')).toContainText('Plan and credits approved')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review')).toContainText('Private artifact manifest')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review-boundaries')).toContainText('No worker dispatch')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review-boundaries')).toContainText('No media processing')
    await expect(page.getByTestId('internal-testing-approved-snapshot-route-review')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run')).toContainText('Worker payload dry run')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run')).toContainText('Payload shape')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run')).toContainText('Private storage lineage')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run')).toContainText('Idempotent job keys')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run-boundaries')).toContainText('No tool execution')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run-boundaries')).toContainText('No credit spend')
    await expect(page.getByTestId('internal-testing-worker-payload-dry-run')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review')).toContainText('Mock worker queue review')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review')).toContainText('Mock queue gates')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review')).toContainText('Idempotent replay')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review')).toContainText('No claim boundary')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review-boundaries')).toContainText('No worker claim')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review-boundaries')).toContainText('No worker dispatch')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review-boundaries')).toContainText('No tool execution')
    await expect(page.getByTestId('internal-testing-mock-worker-queue-review')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run')).toContainText('Worker claim dry run')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run')).toContainText('Lease eligibility')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run')).toContainText('Duplicate claim block')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run')).toContainText('Lease cleanup')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run-boundaries')).toContainText('No worker dispatch')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run-boundaries')).toContainText('No worker execution')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run-boundaries')).toContainText('No tool execution')
    await expect(page.getByTestId('internal-testing-worker-claim-dry-run')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness')).toContainText('Mock worker execution harness')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness')).toContainText('Metadata completion')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness')).toContainText('Lease completion')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness')).toContainText('Private manifest only')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness-boundaries')).toContainText('No worker dispatch')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness-boundaries')).toContainText('No real worker execution')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness-boundaries')).toContainText('No media processing')
    await expect(page.getByTestId('internal-testing-mock-worker-execution-harness')).not.toContainText(/ffmpeg|ffprobe|librosa|opencolorio|openimageio|gpac|mp4box/i)
    await expect(page.getByTestId('internal-testing-auth-project-access-readiness')).toContainText('Auth and project access')
    await expect(page.getByTestId('internal-testing-auth-status')).toContainText(/Supabase|Auth|Checking/)
    await expect(page.getByTestId('internal-testing-auth-project-routes')).toContainText('mock-project-edit-chat-foundation')
    await expect(page.getByTestId('internal-testing-auth-project-routes')).toContainText('edit-session-youtube-wide')
    await expect(page.getByTestId('internal-testing-auth-boundaries')).toContainText('No service-role')
    await expect(page.getByTestId('internal-testing-auth-boundaries')).toContainText('No provider/model calls')
    await expect(page.getByTestId('internal-testing-auth-project-session-membership-policy')).toContainText('Membership policy')
    await expect(page.getByTestId('internal-testing-membership-required-evidence')).toContainText('workspace membership verified')
    await expect(page.getByTestId('internal-testing-membership-route-surfaces')).toContainText('Edit Brief access policy')
    await expect(page.getByTestId('internal-testing-membership-boundaries')).toContainText('No Supabase Data API table access')
    await expect(page.getByTestId('internal-testing-durable-auth-project-session-backend-persistence-plan')).toContainText('Backend persistence plan')
    await expect(page.getByTestId('internal-testing-durable-backend-required-gates')).toContainText('workspace membership verified by workspace members')
    await expect(page.getByTestId('internal-testing-durable-backend-route-contracts')).toContainText('/projects/:projectId')
    await expect(page.getByTestId('internal-testing-durable-backend-tables')).toContainText('workspace_members')
    await expect(page.getByTestId('internal-testing-mock-safe-durable-project-session-backend-skeleton')).toContainText('Backend skeleton')
    await expect(page.getByTestId('internal-testing-backend-skeleton-decision')).toContainText('Route integration ready')
    await expect(page.getByTestId('internal-testing-backend-skeleton-decision')).toContainText(
      'internal_testing_mock_safe_durable_project_session_backend_skeleton_passed_ready_for_backend_route_integration',
    )
    await expect(page.getByTestId('internal-testing-backend-skeleton-required-evidence')).toContainText('explicit data api grants')
    await expect(page.getByTestId('internal-testing-backend-skeleton-boundaries')).toContainText('Durable Supabase access still fails closed')
    await expect(page.getByTestId('internal-testing-durable-project-session-backend-route-integration')).toContainText('Route integration')
    await expect(page.getByTestId('internal-testing-route-integration-decision')).toContainText(
      'internal_testing_durable_project_session_backend_route_integration_passed_ready_for_readback_qa',
    )
    await expect(page.getByTestId('internal-testing-route-integration-families')).toContainText('Project Edit Session mock routes')
    await expect(page.getByTestId('internal-testing-route-integration-families')).toContainText('Project Edit Brief mock routes')
    await expect(page.getByTestId('internal-testing-route-integration-boundaries')).toContainText('Durable Supabase access remains false')
    await expect(page.getByTestId('internal-testing-durable-project-session-backend-readback-qa')).toContainText('Readback QA')
    await expect(page.getByTestId('internal-testing-readback-qa-decision')).toContainText(
      'internal_testing_durable_project_session_backend_readback_qa_passed_ready_for_durable_supabase_route_contract_plan',
    )
    await expect(page.getByTestId('internal-testing-readback-qa-envelope-kinds')).toContainText('success and failure responses')
    await expect(page.getByTestId('internal-testing-readback-qa-boundaries')).toContainText('No durable Supabase')
    await expect(page.getByTestId('internal-testing-durable-project-session-supabase-route-contract-plan')).toContainText('Supabase route contract')
    await expect(page.getByTestId('internal-testing-supabase-route-contract-decision')).toContainText(
      'internal_testing_durable_project_session_supabase_route_contract_plan_passed_ready_for_schema_rls_draft',
    )
    await expect(page.getByTestId('internal-testing-supabase-route-contract-families')).toContainText('/projects/:projectId')
    await expect(page.getByTestId('internal-testing-supabase-route-contract-families')).toContainText('workspace_members')
    await expect(page.getByTestId('internal-testing-supabase-route-contract-grants')).toContainText('schema usage granted')
    await expect(page.getByTestId('internal-testing-supabase-route-contract-boundaries')).toContainText('No Supabase migration')
    await expect(page.getByTestId('internal-testing-durable-project-session-supabase-schema-rls-draft')).toContainText('Schema/RLS draft')
    await expect(page.getByTestId('internal-testing-supabase-schema-rls-draft-decision')).toContainText(
      'internal_testing_durable_project_session_supabase_schema_rls_draft_passed_ready_for_migration_sql_draft',
    )
    await expect(page.getByTestId('internal-testing-supabase-schema-rls-draft-tables')).toContainText('workspace_members')
    await expect(page.getByTestId('internal-testing-supabase-schema-rls-draft-tables')).toContainText('edit_sessions')
    await expect(page.getByTestId('internal-testing-supabase-schema-rls-draft-verification')).toContainText('non member project read denied')
    await expect(page.getByTestId('internal-testing-supabase-schema-rls-draft-boundaries')).toContainText('No migration SQL')
    await expect(page.getByTestId('internal-testing-durable-project-session-supabase-migration-sql-draft')).toContainText('Migration SQL draft')
    await expect(page.getByTestId('internal-testing-supabase-migration-sql-draft-decision')).toContainText(
      'internal_testing_durable_project_session_supabase_migration_sql_draft_passed_ready_for_migration_review',
    )
    await expect(page.getByTestId('internal-testing-supabase-migration-sql-draft-statements')).toContainText('rls_policy')
    await expect(page.getByTestId('internal-testing-supabase-migration-sql-draft-review-checks')).toContainText('migration review required')
    await expect(page.getByTestId('internal-testing-supabase-migration-sql-draft-boundaries')).toContainText('No executable migration')
    await expect(page.getByTestId('internal-testing-durable-project-session-supabase-migration-review')).toContainText('Migration review')
    await expect(page.getByTestId('internal-testing-supabase-migration-review-decision')).toContainText(
      'internal_testing_durable_project_session_supabase_migration_review_passed_ready_for_local_migration_dry_run_plan',
    )
    await expect(page.getByTestId('internal-testing-supabase-migration-review-findings')).toContainText('route-data-hardening')
    await expect(page.getByTestId('internal-testing-supabase-migration-review-dry-run')).toContainText('verify member project session')
    await expect(page.getByTestId('internal-testing-supabase-migration-review-boundaries')).toContainText('No local Supabase reset')
    await expect(page.getByTestId('internal-testing-durable-project-session-supabase-local-migration-dry-run-plan')).toContainText(
      'Local migration dry-run plan',
    )
    await expect(page.getByTestId('internal-testing-supabase-local-dry-run-plan-decision')).toContainText(
      'internal_testing_durable_project_session_supabase_local_migration_dry_run_plan_passed_ready_for_local_migration_dry_run_execution',
    )
    await expect(page.getByTestId('internal-testing-supabase-local-dry-run-plan-commands')).toContainText('local-only')
    await expect(page.getByTestId('internal-testing-supabase-local-dry-run-plan-fixtures')).toContainText('member can select project session')
    await expect(page.getByTestId('internal-testing-supabase-local-dry-run-plan-boundaries')).toContainText('No Supabase command is run')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Edit Brief')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Source Video: select local primary video')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Source Video: local video preview appears')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Source Video: timeline syncs to playback time')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Edit Brief Marker Chat: Qwen readiness label')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Edit Brief Visual Context: analyze sampled frames')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Approved snapshot + credit gate readiness')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Mock worker queue review')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Worker claim dry run')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Mock worker execution harness')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Credit lifecycle readiness')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Repeated local operator harness')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Auth + project access readiness')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Authenticated project/session membership policy')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable auth project/session backend persistence plan')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Mock-safe durable project/session backend skeleton')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session backend route integration')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session backend readback QA')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session Supabase route contract plan')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session Supabase schema/RLS draft')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session Supabase migration SQL draft')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session Supabase migration review')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Durable project/session Supabase local migration dry-run plan')
    await expect(page.getByTestId('internal-testing-scenarios')).toContainText('Preference Video mock-only limits')
    const editBriefStart = page.getByTestId('internal-testing-start-edit-brief')
    await expect(editBriefStart).toContainText('Edit Brief')
    await expect(page.getByTestId('internal-testing-start-source-video')).toContainText('Source video test')

    await editBriefStart.getByRole('link', { name: /^Open$/ }).click()
    await expect(page).toHaveURL(/\/projects\/mock-project-edit-chat-foundation\/edits\/edit-session-youtube-wide\/brief$/)
    await expect(page.getByTestId('project-edit-brief-workspace')).toBeVisible()
    await expect(page.getByTestId('project-edit-brief-boundary')).toContainText('mock/local')
    await expect(page.getByTestId('project-edit-session-access-policy')).toContainText('Project/session access policy')
    await expect(page.getByTestId('project-edit-session-access-policy-facts')).toContainText('Mock route access')
    await expect(page.getByTestId('project-edit-session-access-policy-facts')).toContainText('Durable access')
    await expect(page.getByTestId('project-edit-session-access-policy-facts')).toContainText('pending evidence')
    await expect(page.getByTestId('project-edit-session-access-policy-missing')).toContainText('workspace membership verified')
    await expect(page.getByTestId('generation-progress-card')).toHaveCount(0)
    await expect(page.getByTestId('preview-ready-card')).toHaveCount(0)
    await expect(page.getByText(/credit reserved|render started|provider call made|upload started/i)).toHaveCount(0)
    await expectNoHorizontalOverflow(page)
  })

  test('records browser-local feedback and exposes JSON export', async ({ page }) => {
    await setViewport(page, 1280)
    await gotoRoute(page, '/internal-testing')

    await expect(page.getByTestId('internal-testing-feedback-form')).toBeVisible()
    await page.getByLabel('Result').selectOption('needs_review')
    await page.getByPlaceholder('What did you verify, what failed, or what should the next PR fix?').fill('Route loaded and no runtime work started.')
    await page.getByRole('button', { name: /Save local note/i }).click()

    await expect(page.getByText('Feedback saved in this browser only')).toBeVisible()
    await expect(page.getByTestId('internal-testing-feedback-list')).toContainText('Route loaded and no runtime work started.')
    await expect(page.getByTestId('internal-testing-feedback-export')).toContainText('Route loaded and no runtime work started.')
    await expect(page.getByTestId('internal-testing-feedback-export')).toContainText('providerCalls')

    await page.getByRole('button', { name: /Clear local notes/i }).click()
    await expect(page.getByText('Local feedback cleared from this browser.')).toBeVisible()
    await expect(page.getByTestId('internal-testing-feedback-list')).toContainText('No feedback saved')
    await expectNoHorizontalOverflow(page)
  })
})
