import type { ProductionMetricDefinition } from './observability-types'

export const productionMetricsCatalog: ProductionMetricDefinition[] = [
  metric('worker_job_count', 'Worker jobs created by type/status.', 'count', ['workerType', 'status']),
  metric('worker_job_duration_ms', 'Worker job duration.', 'ms', ['workerType']),
  metric('worker_job_failure_count', 'Worker job failures.', 'count', ['workerType', 'category']),
  metric('worker_retry_count', 'Worker retry attempts.', 'count', ['workerType']),
  metric('worker_blocked_count', 'Worker jobs blocked by policy/readiness/QA.', 'count', ['workerType', 'reason']),
  metric('qa_gate_failure_count', 'Failed or blocked QA gates.', 'count', ['gateType']),
  metric('final_export_count', 'Private final exports created.', 'count', ['workspaceId']),
  metric('render_duration_ms', 'Render/export duration.', 'ms', ['renderEngine']),
  metric('gpu_job_count', 'GPU jobs attempted.', 'count', ['toolId']),
  metric('gpu_job_duration_ms', 'GPU job duration.', 'ms', ['toolId']),
  metric('estimated_gpu_cost', 'Estimated GPU spend.', 'usd', ['workspaceId', 'gpuType']),
  metric('model_weight_blocked_count', 'Model weight policy blockers.', 'count', ['toolId']),
  metric('readiness_blocker_count', 'Readiness blockers by type.', 'count', ['severity']),
  metric('artifact_storage_bytes', 'Private artifact storage footprint.', 'bytes', ['bucketPurpose']),
  metric('private_export_count', 'Private final export count.', 'count', ['workspaceId']),
  metric('deletion_request_count', 'Deletion requests.', 'count', ['status']),
  metric('signed_url_generated_count', 'Temporary signed URLs generated by delivery policy.', 'count', ['purpose']),
  metric('secret_safety_violation_count', 'Secret/log safety violations.', 'count', ['surface']),
  metric('tool_cost_event_write_count', 'Tool cost events recorded by tool and billing status.', 'count', ['workspaceId', 'toolId', 'billableToUser', 'failureCategory']),
  metric('tool_cost_event_replay_count', 'Idempotent tool cost event replays.', 'count', ['workspaceId', 'toolId']),
  metric('tool_cost_persistent_write_failure_count', 'Persistent tool cost event write failures.', 'count', ['workspaceId', 'reason']),
  metric('tool_cost_wallet_settlement_count', 'Tool cost wallet settlements by status and type.', 'count', ['workspaceId', 'status', 'settlementType']),
  metric('tool_cost_wallet_settlement_credit_delta', 'Tool cost wallet settlement credit deltas.', 'credits', ['workspaceId', 'status', 'settlementType']),
  metric('tool_cost_wallet_settlement_failure_count', 'Tool cost wallet settlement failures.', 'count', ['workspaceId', 'reason']),
  metric('tool_cost_rls_readback_failure_count', 'Tool cost billing RLS/member readback failures.', 'count', ['workspaceId', 'tableName']),
  metric('beta_platform_billing_qa_run_count', 'Beta platform billing QA runs.', 'count', ['workspaceId', 'status']),
  metric('beta_platform_billing_qa_missing_evidence_count', 'Missing platform billing evidence items from QA.', 'count', ['workspaceId', 'evidenceType']),
  metric('stripe_call_attempted_count', 'Stripe call attempts from surfaces where Stripe must remain isolated.', 'count', ['surface']),
]

function metric(metricName: string, description: string, unit: ProductionMetricDefinition['unit'], labels: string[]): ProductionMetricDefinition {
  return { metricName, description, unit, labels }
}
