import assert from 'node:assert/strict'
import { buildAutonomousEditPlanApprovalModel } from '../../src/lib/autonomous-edit-plan-approval'
import { createApprovedLocalEditPlanSchema } from '../validation/project-edit-plan-schemas'
import type { AutonomousEditPlanDraft } from '../../src/types'

const draft: AutonomousEditPlanDraft = {
  version: 'autonomous-edit-plan-v1',
  planId: 'autonomous-plan-contract-smoke',
  workspaceId: 'workspace-smoke',
  projectId: 'project-smoke',
  editSessionId: 'edit-smoke',
  status: 'ready_for_approval',
  title: 'Source-aware story edit',
  summary: 'Shape the strongest source ideas into a concise professional story.',
  userIntentSummary: 'Create a concise vertical story with readable captions.',
  storyStrategy: 'Open on the strongest claim, preserve its explanation, then land the takeaway.',
  sourceOrderPolicy: 'preserve_unless_evidence_supports_change',
  outputFrame: {
    aspectRatio: '9:16',
    platformTarget: 'instagram_reel',
    width: 540,
    height: 960,
    confirmed: true,
  },
  segments: [{
    id: 'segment-hook',
    role: 'hook',
    sourceStartSeconds: 0,
    sourceEndSeconds: 4.2,
    objective: 'Open on the speaker\'s strongest supported statement.',
    narrativeReason: 'The transcript begins with the clearest concise promise.',
    transcriptEvidence: ['transcript-segment-1: concise opening promise'],
    visualEvidence: ['representative-1: speaker centered in a medium shot'],
    operations: [{
      operationId: 'timeline.trim',
      instruction: 'Trim only the silence before the first complete phrase.',
      rationale: 'Starts immediately without changing the statement.',
      skillKeys: ['clean_cuts'],
      sourceEvidenceRefs: ['transcript-segment-1', 'representative-1'],
      requiredQaChecks: ['meaning_preserved', 'speech_boundary_safe'],
    }, {
      operationId: 'caption.style',
      instruction: 'Use short phrase groups with restrained emphasis on the key noun.',
      rationale: 'Supports fast comprehension without covering the face.',
      skillKeys: ['caption_design', 'caption_readability_qa'],
      sourceEvidenceRefs: ['transcript-segment-1', 'representative-1'],
      requiredQaChecks: ['caption_readable', 'face_not_occluded'],
      executionSpec: {
        kind: 'caption', placement: 'auto_face_safe', typography: 'clean_bold', textCase: 'sentence',
        emphasis: 'keyword_color_and_scale', animation: 'keyword_pop', accentColor: '#62e6ff',
        maxWordsPerCue: 6, maxLines: 2, emphasisTerms: ['promise'],
      },
    }],
    captionDirection: 'Use two-line maximum phrase groups below the face-safe region.',
    visualDirection: 'Keep the speaker primary; no unsupported graphic is needed.',
    audioDirection: 'Preserve natural voice and remove only measured background noise.',
    transitionDirection: 'Use a direct cut into the next complete idea.',
    requiredQaChecks: ['meaning_preserved', 'caption_readable'],
  }],
  skillSelections: [{
    skillKey: 'clean_cuts',
    reason: 'The opening contains removable leading silence.',
    required: true,
    segmentIds: ['segment-hook'],
    operationIds: ['timeline.trim'],
  }, {
    skillKey: 'caption_design',
    reason: 'The requested short-form output benefits from readable phrase captions.',
    required: true,
    segmentIds: ['segment-hook'],
    operationIds: ['caption.style'],
  }],
  globalQaChecks: ['user_intent_satisfied', 'private_artifacts_only'],
  clarificationQuestions: [],
  blockers: [],
  sourceEvidence: {
    evidenceVersion: 'autonomous-edit-source-evidence-v1',
    sourceStorageObjectRecordId: 'storage-smoke',
    sourceChecksumSha256: 'a'.repeat(64),
    probe: {
      durationSeconds: 32,
      width: 1920,
      height: 1080,
      frameRate: 30,
      videoStreamCount: 1,
      audioStreamCount: 1,
    },
    transcript: {
      status: 'completed',
      language: 'en',
      segmentCount: 8,
      wordCount: 94,
      transcriptArtifactId: 'transcript-smoke',
      wordTimestampArtifactId: 'words-smoke',
    },
    audio: { status: 'completed', integratedLufs: -19, truePeakDb: -2, clippingDetected: false, noiseCondition: 'moderate', silenceRanges: [], analysisMethods: ['ffmpeg_loudnorm_measurement'], blockers: [] },
    visualRhythm: { status: 'completed', detectedCutTimesSeconds: [], detectedCutCount: 0, averageShotDurationSeconds: 32, pacingClass: 'slow', threshold: 0.32, analysisMethods: ['ffmpeg_scene_change_measurement'], blockers: [] },
    color: { status: 'completed', sampledFrameCount: 4, averageLuma: 120, exposureCondition: 'balanced', contrastCondition: 'balanced', analysisMethods: ['ffmpeg_signalstats_measurement'], blockers: [] },
    visualUnderstanding: {
      status: 'completed',
      sampledFrameCount: 4,
      summary: 'A presenter speaks to camera in a stable medium shot.',
      visibleSubjects: ['presenter'],
      visibleObjects: ['desk'],
      screenTextRegions: [],
      compositionRisks: ['face occupies upper center'],
      brollOpportunities: ['desk setup'],
      captionObservations: [],
      styleObservations: ['stable medium talking-head framing'],
      frameEvidence: [],
      evidenceArtifactIds: ['representative-1', 'representative-2'],
    },
    privateArtifactIds: ['transcript-smoke', 'words-smoke', 'representative-1', 'representative-2'],
    blockers: [],
  },
  runtime: {
    plannerSource: 'qwen_live',
    providerCallMade: true,
    qwenCallMade: true,
    mediaAnalysisRun: true,
    transcriptionRun: true,
    visualUnderstandingRun: true,
    deterministicCreativeFallbackUsed: false,
    rawPromptStored: false,
    workerExecutionStarted: false,
    renderStarted: false,
    creditReservedOrSpent: false,
  },
  approvalRequired: true,
  approved: false,
  createdAt: '2026-07-09T18:00:00.000Z',
  warnings: [],
}

const sourceVideoUploadResult = {
  status: 'uploaded' as const,
  uploadIntentId: 'upload-smoke',
  storageObjectRecordId: 'storage-smoke',
  mediaAssetId: 'asset-smoke',
  bucketName: 'source-media',
  objectPath: 'workspace/project/source.mp4',
  fileName: 'source.mp4',
  mimeType: 'video/mp4',
  sizeBytes: 1024,
  checksumSha256: 'a'.repeat(64),
  uploadedAt: '2026-07-09T17:59:00.000Z',
  backendLocalUploadMade: true as const,
  browserFileBytesSent: true as const,
  fileBytesReadByBackend: true as const,
  storageWriteMade: true as const,
  supabaseWriteMade: false as const,
  gcsWriteMade: false as const,
  mediaProcessingStarted: false as const,
  workerJobCreated: false as const,
  providerCallMade: false as const,
  renderJobCreated: false as const,
  exportJobCreated: false as const,
  creditReservedOrSpent: false as const,
  productReady: false as const,
  warnings: [],
}

const model = buildAutonomousEditPlanApprovalModel({
  attemptId: 'attempt-smoke',
  draft,
  directionSource: 'chat_prompt',
  sourceVideoUploadResult,
})
assert.equal(model.canApprove, true)
assert.equal(model.operationManifest.version, 'project-edit-operation-manifest-v2')
assert.equal(model.operationManifest.mediaIntelligenceStatus, 'analyzed_private_source_evidence')
assert.equal(model.planningEvidence?.plannerSource, 'qwen_live')
assert.equal(model.operationManifest.operations.every((operation) => Boolean(operation.sourceEvidenceRefs?.length)), true)
assert.equal(model.skillPlan.exposesInternalToolNames, false)

const parsed = createApprovedLocalEditPlanSchema.safeParse({
  workspaceId: draft.workspaceId,
  planId: model.planId,
  title: model.title,
  summary: model.summary,
  steps: model.steps,
  operationManifest: model.operationManifest,
  planningEvidence: model.planningEvidence,
  directionSource: model.directionSource,
  skillPlan: model.skillPlan,
  creditEstimate: model.creditEstimate,
  briefLineage: {
    briefId: 'prompt-direction-smoke',
    revisionNumber: 1,
    briefFingerprint: 'brief-fnv1a-smoke',
  },
  source: {
    storageObjectRecordId: sourceVideoUploadResult.storageObjectRecordId,
    mediaAssetId: sourceVideoUploadResult.mediaAssetId,
    bucketName: sourceVideoUploadResult.bucketName,
    objectPath: sourceVideoUploadResult.objectPath,
    fileName: sourceVideoUploadResult.fileName,
    mimeType: sourceVideoUploadResult.mimeType,
    sizeBytes: sourceVideoUploadResult.sizeBytes,
    checksumSha256: sourceVideoUploadResult.checksumSha256,
  },
})
assert.equal(parsed.success, true, parsed.success ? undefined : JSON.stringify(parsed.error.flatten()))

console.log(JSON.stringify({
  ok: true,
  decision: 'autonomous_edit_plan_approval_bridge_passed',
  operationCount: model.operationManifest.operations.length,
  selectedSkillCount: model.skillPlan.selectedSkillKeys.length,
  evidenceArtifactCount: model.planningEvidence?.privateArtifactIds.length,
}, null, 2))
