import assert from 'node:assert/strict'

import { prepareOfflineNativeAudioProcessingDockerRuntime } from '../tool-execution/native-audio-processing-execution/offline-native-audio-processing-docker-runtime'
import { OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS, OFFLINE_NATIVE_AUDIO_PROCESSING_PACKAGE_IDENTITIES, OFFLINE_NATIVE_AUDIO_PROCESSING_TOOL_IDS, validateOfflineNativeAudioProcessingRequest } from '../tool-execution/native-audio-processing-execution/offline-native-audio-processing-protocol'
import { activatePrivateOfflineNativeAudioProcessingRuntime, openPrivateOfflineNativeAudioProcessingRuntime, readPersistedOfflineNativeAudioProcessingRuntimeAuthority } from '../tool-execution/native-audio-processing-execution/offline-native-audio-processing-service'

const requests = [
  validateOfflineNativeAudioProcessingRequest({ schemaVersion: 'offline-native-audio-processing-execution-v1', toolId: 'rnnoise', operationId: OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS.rnnoise, payload: { sampleRate: 48000, channelMode: 'mono', processingProfileId: 'approved_voice_denoise_v1', strength: 1, preserveVoice: true, fixtureProfileId: 'approved_noisy_voice_fixture_v1' } }),
  validateOfflineNativeAudioProcessingRequest({ schemaVersion: 'offline-native-audio-processing-execution-v1', toolId: 'signalsmith_stretch', operationId: OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS.signalsmith_stretch, payload: { stretchProfileId: 'approved_music_bed_fit_v1', speedRatio: 1.25, pitchSemitones: 0, preserveVoice: false, fixtureProfileId: 'approved_music_tone_fixture_v1' } }),
] as const
for (const invalid of [{ ...requests[0], command: 'whoami' }, { ...requests[0], payload: { ...requests[0].payload, inputPath: '/tmp/evil.wav' } }, { ...requests[0], payload: { ...requests[0].payload, strength: 0.5 } }, { ...requests[0], payload: { ...requests[0].payload, sampleRate: 44100 } }, { ...requests[1], payload: { ...requests[1].payload, outputUrl: 'https://example.test/a.wav' } }, { ...requests[1], payload: { ...requests[1].payload, speedRatio: 4 } }, { ...requests[1], payload: { ...requests[1].payload, pitchSemitones: 12 } }]) assert.throws(() => validateOfflineNativeAudioProcessingRequest(invalid), /unsupported/)
await prepareOfflineNativeAudioProcessingDockerRuntime(); const activated = await activatePrivateOfflineNativeAudioProcessingRuntime(); const authority = await readPersistedOfflineNativeAudioProcessingRuntimeAuthority(); assert.ok(authority); assert.deepEqual(authority.supportedOperations.map((operation) => operation.toolId), OFFLINE_NATIVE_AUDIO_PROCESSING_TOOL_IDS); assert.equal(authority.readiness.privateInternalExecutionReady, true); assert.equal(authority.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(authority.readiness.productReady, false)
const reopened = await openPrivateOfflineNativeAudioProcessingRuntime(); assert.equal(reopened.image.imageIdentityHash, activated.image.imageIdentityHash)
const artifacts: Record<string, { sha256: string; byteLength: number; mimeType: string }> = {}
for (const request of requests) { const first = await reopened.execute(request); const replay = await reopened.execute(request); const expected = OFFLINE_NATIVE_AUDIO_PROCESSING_PACKAGE_IDENTITIES[request.toolId]; assert.equal(first.artifact.mimeType, 'audio/wav'); assert.equal(first.artifact.sha256, replay.artifact.sha256); assert.equal(first.evidence.packageName, expected.packageName); assert.equal(first.evidence.packageVersion, expected.version); assert.equal(first.evidence.confinement.networkMode, 'none'); assert.equal(first.evidence.confinement.readOnlyRootFilesystem, true); assert.equal(first.evidence.confinement.capDropAll, true); assert.equal(first.evidence.confinement.noNewPrivileges, true); assert.equal(first.evidence.confinement.user, '10001:10001'); assert.equal(first.evidence.semanticEvidence.actualPackageEntrypointExecuted, true); assert.equal(first.evidence.semanticEvidence.zeroNetworkRuntimeRequired, true); assert.equal(first.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(first.readiness.productReady, false); artifacts[request.toolId] = { sha256: first.artifact.sha256, byteLength: first.artifact.byteLength, mimeType: first.artifact.mimeType } }
assert.equal(artifacts.rnnoise?.sha256, 'ad2e8fff94b1826c7c4672fb568a007ff2a983b94b9a5f9c3ede447c25c27293')
assert.equal(artifacts.signalsmith_stretch?.sha256, '0b8013e193cf24760f97d24275da6e17819c0eb5bf1cefa3d17a1db98584805d')
console.log(JSON.stringify({ smoke: 'offline_native_audio_processing_execution', status: 'passed', toolCount: requests.length, proofs: ['two_exact_tool_and_operation_identities_validated', 'pinned_rnnoise_release_official_build_fix_embedded_model_and_signalsmith_source_verified', 'deterministic_fixed_seed_signalsmith_adapter_source_hash_verified', 'caller_paths_urls_commands_and_extra_fields_rejected', 'checksum_protected_runtime_authority_persisted_and_reopened', 'network_none_read_only_non_root_cap_drop_no_new_privileges_confinement_verified', 'actual_rnnoise_and_signalsmith_library_entrypoints_executed', 'rnnoise_latency_noise_reduction_and_voice_energy_checks_verified', 'signalsmith_exact_length_time_stretch_verified', 'deterministic_replay_and_golden_artifact_hashes_verified', 'license_review_and_product_external_beta_production_gates_remain_blocked'], artifacts }, null, 2))
