import assert from 'node:assert/strict'

import { prepareOfflineVapourSynthFramePipelineDockerRuntime } from '../tool-execution/vapoursynth-frame-pipeline-execution/offline-vapoursynth-frame-pipeline-docker-runtime'
import { OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS, OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_PACKAGE_IDENTITIES, OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_TOOL_IDS, validateOfflineVapourSynthFramePipelineRequest } from '../tool-execution/vapoursynth-frame-pipeline-execution/offline-vapoursynth-frame-pipeline-protocol'
import { activatePrivateOfflineVapourSynthFramePipelineRuntime, openPrivateOfflineVapourSynthFramePipelineRuntime, readPersistedOfflineVapourSynthFramePipelineRuntimeAuthority } from '../tool-execution/vapoursynth-frame-pipeline-execution/offline-vapoursynth-frame-pipeline-service'

const requests = [
  validateOfflineVapourSynthFramePipelineRequest({ schemaVersion: 'offline-vapoursynth-frame-pipeline-execution-v1', toolId: 'vapoursynth', operationId: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS.vapoursynth, payload: { pipelineProfileId: 'approved_frame_preprocess_v1', pluginPackProfileId: 'reviewed_builtin_plugins_v1', frameRate: 24, callerScriptAllowed: false } }),
] as const
for (const invalid of [{ ...requests[0], command: 'whoami' }, { ...requests[0], payload: { ...requests[0].payload, inputPath: '/tmp/evil.vpy' } }, { ...requests[0], payload: { ...requests[0].payload, callerScriptAllowed: true } }, { ...requests[0], payload: { ...requests[0].payload, frameRate: 60 } }, { ...requests[0], payload: { ...requests[0].payload, pluginPackProfileId: 'unreviewed_plugins' } }]) assert.throws(() => validateOfflineVapourSynthFramePipelineRequest(invalid), /unsupported/)
await prepareOfflineVapourSynthFramePipelineDockerRuntime(); const activated = await activatePrivateOfflineVapourSynthFramePipelineRuntime(); const authority = await readPersistedOfflineVapourSynthFramePipelineRuntimeAuthority(); assert.ok(authority); assert.deepEqual(authority.supportedOperations.map((operation) => operation.toolId), OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_TOOL_IDS); assert.equal(authority.readiness.privateInternalExecutionReady, true); assert.equal(authority.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(authority.readiness.productReady, false)
const reopened = await openPrivateOfflineVapourSynthFramePipelineRuntime(); assert.equal(reopened.image.imageIdentityHash, activated.image.imageIdentityHash)
const artifacts: Record<string, { sha256: string; byteLength: number; mimeType: string }> = {}
for (const request of requests) { const first = await reopened.execute(request); const replay = await reopened.execute(request); const expected = OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_PACKAGE_IDENTITIES[request.toolId]; assert.equal(first.artifact.mimeType, 'application/json'); assert.equal(first.artifact.sha256, replay.artifact.sha256); assert.equal(first.evidence.packageName, expected.packageName); assert.equal(first.evidence.packageVersion, expected.version); assert.equal(first.evidence.confinement.networkMode, 'none'); assert.equal(first.evidence.confinement.readOnlyRootFilesystem, true); assert.equal(first.evidence.confinement.capDropAll, true); assert.equal(first.evidence.confinement.noNewPrivileges, true); assert.equal(first.evidence.confinement.user, '10001:10001'); assert.equal(first.evidence.semanticEvidence.actualPackageEntrypointExecuted, true); assert.equal(first.evidence.semanticEvidence.zeroNetworkRuntimeRequired, true); assert.equal(first.evidence.semanticEvidence.firstAndLastFrameVerified, true); assert.equal(first.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(first.readiness.productReady, false); artifacts[request.toolId] = { sha256: first.artifact.sha256, byteLength: first.artifact.byteLength, mimeType: first.artifact.mimeType } }
assert.equal(artifacts.vapoursynth?.sha256, '282aff15af11983ab205979c2e30675bd287dcc5eaa6bdbb0e7761df3ad2ff36')
console.log(JSON.stringify({ smoke: 'offline_vapoursynth_frame_pipeline_execution', status: 'passed', toolCount: requests.length, proofs: ['exact_tool_and_operation_identity_validated', 'official_r77_arm64_wheel_hash_verified', 'caller_scripts_paths_plugins_and_extra_fields_rejected', 'checksum_protected_runtime_authority_persisted_and_reopened', 'network_none_read_only_non_root_cap_drop_no_new_privileges_confinement_verified', 'actual_blank_crop_and_resize_frame_pipeline_executed', 'first_and_last_frame_plane_hashes_verified', 'deterministic_replay_and_golden_json_artifact_hash_verified', 'multi_arch_license_and_product_external_beta_production_gates_remain_blocked'], artifacts }, null, 2))
