import assert from 'node:assert/strict'

import { prepareOfflineContainerPackagingValidationDockerRuntime } from '../tool-execution/container-packaging-validation-execution/offline-container-packaging-validation-docker-runtime'
import { OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS, OFFLINE_CONTAINER_PACKAGING_VALIDATION_PACKAGE_IDENTITIES, OFFLINE_CONTAINER_PACKAGING_VALIDATION_TOOL_IDS, validateOfflineContainerPackagingValidationRequest } from '../tool-execution/container-packaging-validation-execution/offline-container-packaging-validation-protocol'
import { activatePrivateOfflineContainerPackagingValidationRuntime, openPrivateOfflineContainerPackagingValidationRuntime, readPersistedOfflineContainerPackagingValidationRuntimeAuthority } from '../tool-execution/container-packaging-validation-execution/offline-container-packaging-validation-service'

const requests = [
  validateOfflineContainerPackagingValidationRequest({ schemaVersion: 'offline-container-packaging-validation-execution-v1', toolId: 'mkvtoolnix_container_validation', operationId: OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS.mkvtoolnix_container_validation, payload: { validationProfileId: 'approved_private_packaging_validation_v1', expectedContainer: 'mkv', requireAudioVideoSync: true, requireCaptionIntegrity: true } }),
  validateOfflineContainerPackagingValidationRequest({ schemaVersion: 'offline-container-packaging-validation-execution-v1', toolId: 'gpac_mp4box_packaging_validation', operationId: OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS.gpac_mp4box_packaging_validation, payload: { validationProfileId: 'approved_private_packaging_validation_v1', expectedContainer: 'mp4', requireAudioVideoSync: true, requireCaptionIntegrity: true } }),
] as const
for (const invalid of [{ ...requests[0], command: 'whoami' }, { ...requests[0], payload: { ...requests[0].payload, inputPath: '/tmp/evil.mp4' } }, { ...requests[0], payload: { ...requests[0].payload, expectedContainer: 'mp4' } }, { ...requests[0], payload: { ...requests[0].payload, requireCaptionIntegrity: false } }, { ...requests[1], payload: { ...requests[1].payload, outputUrl: 'https://example.test/a.mp4' } }, { ...requests[1], payload: { ...requests[1].payload, expectedContainer: 'mkv' } }, { ...requests[1], payload: { ...requests[1].payload, requireAudioVideoSync: false } }]) assert.throws(() => validateOfflineContainerPackagingValidationRequest(invalid), /unsupported/)
await prepareOfflineContainerPackagingValidationDockerRuntime(); const activated = await activatePrivateOfflineContainerPackagingValidationRuntime(); const authority = await readPersistedOfflineContainerPackagingValidationRuntimeAuthority(); assert.ok(authority); assert.deepEqual(authority.supportedOperations.map((operation) => operation.toolId), OFFLINE_CONTAINER_PACKAGING_VALIDATION_TOOL_IDS); assert.equal(authority.readiness.privateInternalExecutionReady, true); assert.equal(authority.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(authority.readiness.productReady, false)
const reopened = await openPrivateOfflineContainerPackagingValidationRuntime(); assert.equal(reopened.image.imageIdentityHash, activated.image.imageIdentityHash)
const artifacts: Record<string, { sha256: string; byteLength: number; mimeType: string }> = {}
for (const request of requests) { const first = await reopened.execute(request); const replay = await reopened.execute(request); const expected = OFFLINE_CONTAINER_PACKAGING_VALIDATION_PACKAGE_IDENTITIES[request.toolId]; assert.equal(first.artifact.mimeType, 'application/json'); assert.equal(first.artifact.sha256, replay.artifact.sha256); assert.equal(first.evidence.packageName, expected.packageName); assert.equal(first.evidence.packageVersion, expected.version); assert.equal(first.evidence.confinement.networkMode, 'none'); assert.equal(first.evidence.confinement.readOnlyRootFilesystem, true); assert.equal(first.evidence.confinement.capDropAll, true); assert.equal(first.evidence.confinement.noNewPrivileges, true); assert.equal(first.evidence.confinement.user, '10001:10001'); assert.equal(first.evidence.semanticEvidence.actualPackageEntrypointExecuted, true); assert.equal(first.evidence.semanticEvidence.zeroNetworkRuntimeRequired, true); assert.equal(first.evidence.semanticEvidence.captionTrackVerified, true); assert.equal(first.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(first.readiness.productReady, false); artifacts[request.toolId] = { sha256: first.artifact.sha256, byteLength: first.artifact.byteLength, mimeType: first.artifact.mimeType } }
assert.equal(artifacts.mkvtoolnix_container_validation?.sha256, '170b3ceef387209a658618ee6da9a69fa1ab150ddef1fb1abf0caa633f292b12')
assert.equal(artifacts.gpac_mp4box_packaging_validation?.sha256, '1236af49ab88b27995cc112264a35b138d43d44d67cdf0b18bcf19c78b56dca3')
console.log(JSON.stringify({ smoke: 'offline_container_packaging_validation_execution', status: 'passed', toolCount: requests.length, proofs: ['two_exact_tool_and_operation_identities_validated', 'pinned_mkvtoolnix_debian_snapshot_and_gpac_source_hash_verified', 'gpac_network_disabled_minimal_filter_build_verified', 'caller_paths_urls_commands_and_extra_fields_rejected', 'checksum_protected_runtime_authority_persisted_and_reopened', 'network_none_read_only_non_root_cap_drop_no_new_privileges_confinement_verified', 'actual_mkvmerge_and_mp4box_packaging_and_identification_entrypoints_executed', 'video_audio_caption_tracks_verified', 'deterministic_replay_and_golden_json_artifact_hashes_verified', 'license_review_and_product_external_beta_production_gates_remain_blocked'], artifacts }, null, 2))
