import assert from 'node:assert/strict'

import { prepareOfflineNativeImagePipelineDockerRuntime } from '../tool-execution/native-image-pipeline-execution/offline-native-image-pipeline-docker-runtime'
import { OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS, OFFLINE_NATIVE_IMAGE_PIPELINE_PACKAGE_IDENTITIES, OFFLINE_NATIVE_IMAGE_PIPELINE_TOOL_IDS, validateOfflineNativeImagePipelineRequest } from '../tool-execution/native-image-pipeline-execution/offline-native-image-pipeline-protocol'
import { activatePrivateOfflineNativeImagePipelineRuntime, openPrivateOfflineNativeImagePipelineRuntime, readPersistedOfflineNativeImagePipelineRuntimeAuthority } from '../tool-execution/native-image-pipeline-execution/offline-native-image-pipeline-service'

const requests = [
  validateOfflineNativeImagePipelineRequest({ schemaVersion: 'offline-native-image-pipeline-execution-v1', toolId: 'opencolorio', operationId: OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS.opencolorio, payload: { transformProfileId: 'approved_srgb_to_rec709_v1', inputColorSpace: 'srgb', outputColorSpace: 'rec709', strength: 1, preserveSkinTone: true, fixtureProfileId: 'approved_color_chart_v1' } }),
  validateOfflineNativeImagePipelineRequest({ schemaVersion: 'offline-native-image-pipeline-execution-v1', toolId: 'openimageio', operationId: OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS.openimageio, payload: { transformProfileId: 'approved_sequence_resize_v1', outputFormat: 'png', outputWidth: 64, outputHeight: 64, preserveMetadata: false, fixtureProfileId: 'approved_two_frame_sequence_v1' } }),
  validateOfflineNativeImagePipelineRequest({ schemaVersion: 'offline-native-image-pipeline-execution-v1', toolId: 'streamer_render_pipeline_support', operationId: OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS.streamer_render_pipeline_support, payload: { probeProfileId: 'approved_av_pipeline_probe_v1', requireVideoPipeline: true, requireAudioPipeline: true } }),
] as const
for (const invalid of [{ ...requests[0], command: 'whoami' }, { ...requests[0], payload: { ...requests[0].payload, lutPath: '/tmp/evil.cube' } }, { ...requests[0], payload: { ...requests[0].payload, strength: 0.5 } }, { ...requests[1], payload: { ...requests[1].payload, outputWidth: 8192 } }, { ...requests[1], payload: { ...requests[1].payload, sourceUrl: 'https://example.test/a.png' } }, { ...requests[2], payload: { ...requests[2].payload, pipeline: 'tcpclientsrc host=example.test' } }, { ...requests[2], payload: { ...requests[2].payload, requireAudioPipeline: false } }]) assert.throws(() => validateOfflineNativeImagePipelineRequest(invalid), /unsupported/)
await prepareOfflineNativeImagePipelineDockerRuntime(); const activated = await activatePrivateOfflineNativeImagePipelineRuntime(); const authority = await readPersistedOfflineNativeImagePipelineRuntimeAuthority(); assert.ok(authority); assert.deepEqual(authority.supportedOperations.map((operation) => operation.toolId), OFFLINE_NATIVE_IMAGE_PIPELINE_TOOL_IDS); assert.equal(authority.readiness.privateInternalExecutionReady, true); assert.equal(authority.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(authority.readiness.productReady, false)
const reopened = await openPrivateOfflineNativeImagePipelineRuntime(); assert.equal(reopened.image.imageIdentityHash, activated.image.imageIdentityHash)
const artifacts: Record<string, { sha256: string; byteLength: number; mimeType: string }> = {}
for (const request of requests) { const first = await reopened.execute(request); const replay = await reopened.execute(request); const expected = OFFLINE_NATIVE_IMAGE_PIPELINE_PACKAGE_IDENTITIES[request.toolId]; assert.equal(first.artifact.mimeType, request.toolId === 'streamer_render_pipeline_support' ? 'application/json' : 'image/png'); assert.equal(first.artifact.sha256, replay.artifact.sha256); assert.equal(first.evidence.packageName, expected.packageName); assert.equal(first.evidence.packageVersion, expected.version); assert.equal(first.evidence.confinement.networkMode, 'none'); assert.equal(first.evidence.confinement.readOnlyRootFilesystem, true); assert.equal(first.evidence.confinement.capDropAll, true); assert.equal(first.evidence.confinement.noNewPrivileges, true); assert.equal(first.evidence.confinement.user, '10001:10001'); assert.equal(first.evidence.semanticEvidence.actualPackageEntrypointExecuted, true); assert.equal(first.evidence.semanticEvidence.zeroNetworkRuntimeRequired, true); assert.equal(first.readiness.licenseReviewStillRequiredForProduction, true); assert.equal(first.readiness.productReady, false); artifacts[request.toolId] = { sha256: first.artifact.sha256, byteLength: first.artifact.byteLength, mimeType: first.artifact.mimeType } }
console.log(JSON.stringify({ smoke: 'offline_native_image_pipeline_execution', status: 'passed', toolCount: requests.length, proofs: ['three_exact_tool_and_operation_identities_validated', 'date_pinned_debian_snapshot_and_exact_direct_package_versions_verified', 'caller_paths_urls_commands_luts_pipelines_and_extra_fields_rejected', 'checksum_protected_runtime_authority_persisted_and_reopened', 'network_none_read_only_non_root_cap_drop_no_new_privileges_confinement_verified', 'actual_opencolorio_openimageio_and_gstreamer_entrypoints_executed', 'deterministic_replay_hashes_verified', 'license_review_and_product_external_beta_production_gates_remain_blocked'], artifacts }, null, 2))
