import type { MockProjectEditSessionPreferenceScenario, ProjectEditSessionPreferenceApplicationStatus } from '../../types/project-edit-session-preference'

const baseScenarios: Array<[string, string, ProjectEditSessionPreferenceApplicationStatus]> = [
  ['list-options', 'List preference options.', 'not_selected'],
  ['none-option-exists', 'No preference option exists.', 'not_selected'],
  ['legacy-option-exists', 'Legacy no-DNA option exists.', 'legacy_preference_applied'],
  ['dna-backed-option-exists', 'DNA-backed option exists.', 'dna_applied_mock'],
  ['reference-option-exists', 'Created-from-reference option exists if fixture available.', 'dna_applied_mock'],
  ['state-no-preference', 'Preference state from session with no preference.', 'not_selected'],
  ['state-legacy', 'Preference state from legacy no-DNA session.', 'legacy_preference_applied'],
  ['state-dna', 'Preference state from DNA-backed session.', 'dna_applied_mock'],
  ['qa-approved', 'DNA QA approved maps to dna_applied_mock.', 'dna_applied_mock'],
  ['qa-warnings', 'DNA QA approved with warnings maps to dna_applied_with_warnings_mock.', 'dna_applied_with_warnings_mock'],
  ['qa-review', 'DNA QA requires review maps to dna_requires_user_review.', 'dna_requires_user_review'],
  ['qa-copy-risk', 'DNA QA blocked copy risk maps to dna_blocked_by_qa.', 'dna_blocked_by_qa'],
  ['do-not-copy', 'Do-not-copy rules created for DNA session.', 'dna_applied_mock'],
  ['legacy-plan', 'Application plan for legacy preference created.', 'legacy_preference_applied'],
  ['dna-plan', 'Application plan for DNA preference created.', 'dna_applied_mock'],
  ['review-plan', 'Application plan for review-required DNA created.', 'dna_requires_user_review'],
  ['blocked-plan', 'Application plan for blocked DNA blocks application.', 'dna_blocked_by_qa'],
  ['clear-plan', 'Application plan for clearing preference created.', 'cleared'],
  ['replace-plan', 'Replace preference plan created.', 'dna_applied_mock'],
  ['session-update-id', 'Session update includes selected preference ID.', 'dna_applied_mock'],
  ['session-update-handle', 'Session update includes selected handle.', 'dna_applied_mock'],
  ['session-update-dna-status', 'Session update includes DNA status label.', 'dna_applied_mock'],
  ['session-update-dna-qa', 'Session update includes DNA QA label.', 'dna_applied_mock'],
  ['session-update-do-not-copy', 'Session update sets doNotCopyRulesActive true for DNA.', 'dna_applied_mock'],
  ['session-clear-fields', 'Session update clears fields on clear.', 'cleared'],
  ['memory-preference', 'Memory update created for preference memory.', 'legacy_preference_applied'],
  ['memory-dna', 'Memory update created for DNA application memory.', 'dna_applied_mock'],
  ['memory-legacy', 'Memory update created for legacy fallback.', 'legacy_preference_applied'],
  ['memory-cleared', 'Memory update created for preference cleared.', 'cleared'],
  ['event-applied', 'History event created for preference applied.', 'dna_applied_mock'],
  ['event-cleared', 'History event created for preference cleared.', 'cleared'],
  ['event-replaced', 'History event created for preference replaced.', 'dna_applied_mock'],
  ['snapshot-applied', 'Snapshot summary created for preference applied.', 'dna_applied_mock'],
  ['panel-none', 'Panel model created for no preference.', 'not_selected'],
  ['panel-legacy', 'Panel model created for legacy no-DNA.', 'legacy_preference_applied'],
  ['panel-dna', 'Panel model created for DNA applied.', 'dna_applied_mock'],
  ['panel-review', 'Panel model created for review warning.', 'dna_requires_user_review'],
  ['panel-blocked', 'Panel model created for blocked DNA.', 'dna_blocked_by_qa'],
  ['validate-option', 'Validation passes for valid option.', 'dna_applied_mock'],
  ['validate-state', 'Validation passes for valid state.', 'dna_applied_mock'],
  ['validate-plan', 'Validation passes for valid application plan.', 'dna_applied_mock'],
  ['validate-provider', 'Validation blocks provider flag.', 'failed_validation'],
  ['validate-media', 'Validation blocks media processing flag.', 'failed_validation'],
  ['validate-worker', 'Validation blocks worker flag.', 'failed_validation'],
  ['validate-generation', 'Validation blocks generation request flag.', 'failed_validation'],
  ['validate-render', 'Validation blocks render job flag.', 'failed_validation'],
  ['validate-credit', 'Validation blocks credit flag.', 'failed_validation'],
  ['ui-options', 'UI adapter lists options.', 'not_selected'],
  ['ui-panel', 'UI adapter loads panel.', 'not_selected'],
  ['ui-apply', 'UI adapter applies preference via API.', 'dna_applied_mock'],
  ['ui-clear', 'UI adapter clears preference via API.', 'cleared'],
  ['new-edit-selection', 'New Edit selection can persist preference metadata.', 'dna_applied_mock'],
  ['home-card-dna', 'Project home card reflects DNA badge after apply.', 'dna_applied_mock'],
  ['chat-context-apply', 'Chat context reflects selected preference after apply.', 'dna_applied_mock'],
  ['legacy-fallback', 'Legacy no-DNA fallback still works.', 'legacy_preference_applied'],
  ['distinct-objects', 'ProjectEditSession remains distinct from EditPreference.', 'dna_applied_mock'],
  ['no-qwen', 'No Qwen call made.', 'dna_applied_mock'],
  ['no-deepseek', 'No DeepSeek call made.', 'dna_applied_mock'],
  ['no-side-effects', 'No provider/worker/render/credit side effect.', 'dna_applied_mock'],
  ['no-supabase-write', 'No Supabase write made.', 'dna_applied_mock'],
]

export const MOCK_PROJECT_EDIT_SESSION_PREFERENCE_SCENARIOS: MockProjectEditSessionPreferenceScenario[] =
  baseScenarios.map(([id, title, expectedStatus]) => ({
    id: `project-edit-session-preference-${id}`,
    title,
    input: { milestone: 'RP-EDITSESSION-10' },
    expectedOk: expectedStatus !== 'failed_validation',
    expectedStatus,
    expectedSideEffectsFalse: true,
    mockOnly: true,
  }))

export function listMockProjectEditSessionPreferenceScenarios(): MockProjectEditSessionPreferenceScenario[] {
  return [...MOCK_PROJECT_EDIT_SESSION_PREFERENCE_SCENARIOS]
}
