import type { ProductionModelWeightManifestTemplate } from './model-weight-manifest-types'

const basePath = '/opt/reeditpro/model-weights'

export const GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES: ProductionModelWeightManifestTemplate[] = [
  {
    id: 'faster_whisper_model',
    toolId: 'faster_whisper',
    modelName: 'faster-whisper model checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/faster-whisper/`,
    source: 'model source placeholder; must be filled by approved model-weight review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Whisper model/checkpoint license must be reviewed separately from faster-whisper and CTranslate2 code licenses.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'birefnet_model',
    toolId: 'birefnet',
    modelName: 'BiRefNet checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/birefnet/`,
    source: 'model source placeholder; not every related checkpoint is commercial-safe',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['BiRefNet-related weights vary; each selected checkpoint must prove commercial paid-production permission.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'sam2_checkpoint',
    toolId: 'sam2',
    modelName: 'SAM 2 checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/sam2/`,
    source: 'model source placeholder; checkpoint license review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['SAM 2 code/license assumptions do not approve checkpoint use.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'transparent_background_model',
    toolId: 'transparent_background',
    modelName: 'transparent-background checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/transparent-background/`,
    source: 'model source placeholder; transparent-background model/cache policy must be reviewed',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['transparent-background model weights/cache behavior require commercial-use and quality review before paid production.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'rembg_model',
    toolId: 'rembg',
    modelName: 'rembg ONNX model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/rembg/`,
    source: 'model source placeholder; rembg model/cache policy must be reviewed',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['rembg ONNX/model cache behavior must pass commercial-use, provenance, and cutout-quality review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'deepfilternet_model',
    toolId: 'deepfilternet',
    modelName: 'DeepFilterNet model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/deepfilternet/`,
    source: 'model source placeholder; must be reviewed before voice cleanup execution',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Audio cleanup model weights must pass commercial-use, quality, and naturalness review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'demucs_model',
    toolId: 'demucs',
    modelName: 'Demucs model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/demucs/`,
    source: 'model source placeholder; stem separation weights must be reviewed',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Demucs must not be used as a default cleanup path and needs separate model-weight review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'real_esrgan_model',
    toolId: 'real_esrgan',
    modelName: 'Real-ESRGAN model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/real-esrgan/`,
    source: 'model source placeholder; enhancement weights require review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Enhancement weights must pass commercial-use and artifact/hallucination review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'film_model',
    toolId: 'film',
    modelName: 'FILM frame interpolation checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/film/`,
    source: 'model source placeholder; interpolation checkpoint review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['FILM weights must pass commercial-use and warping/temporal artifact review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'paddleocr_model',
    toolId: 'paddleocr',
    modelName: 'PaddleOCR detection/recognition model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/paddleocr/`,
    source: 'model source placeholder; OCR model review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['OCR model weights must pass commercial-use, privacy, and accuracy review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
]

export function listGpuModelWeightManifestTemplates(): ProductionModelWeightManifestTemplate[] {
  return [...GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES]
}

export function getGpuModelWeightManifestTemplate(
  id: ProductionModelWeightManifestTemplate['id'],
): ProductionModelWeightManifestTemplate | undefined {
  return GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES.find((template) => template.id === id)
}
