import type { ProductionModelWeightManifestTemplate } from './model-weight-manifest-types'

const basePath = '/opt/reeditpro/model-weights'

export const GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES: ProductionModelWeightManifestTemplate[] = [
  {
    id: 'rembg_u2netp_model',
    toolId: 'rembg',
    modelName: 'rembg U2NetP background-removal model',
    modelVersion: 'placeholder-needs-production-review',
    expectedPath: `${basePath}/rembg/`,
    source: 'exact private runner model exists; production GPU mount still requires reviewed manifest promotion',
    license: 'Apache-2.0-upstream-observed-needs-production-review',
    commercialUseAllowed: false,
    commercialUseStatus: 'needs_review',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: [
      'Private canonical runner evidence does not authorize the production GPU image or model mount.',
      'The production manifest must independently bind the exact U2NetP revision, checksum, size, license review, and read-only mount.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'faster_whisper_model',
    toolId: 'faster_whisper',
    modelName: 'faster-whisper model checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/faster-whisper/`,
    source: 'model source placeholder; must be filled by approved model-weight review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Whisper model/checkpoint license must be reviewed separately from faster-whisper and CTranslate2 code licenses.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'birefnet_model',
    toolId: 'birefnet',
    modelName: 'BiRefNet checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/birefnet/`,
    source: 'model source placeholder; not every related checkpoint is commercial-safe',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['BiRefNet-related weights vary; each selected checkpoint must prove commercial paid-production permission.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'sam3_1_checkpoint',
    toolId: 'sam3_1',
    modelName: 'SAM 3.1 Object Multiplex checkpoint',
    modelVersion: 'facebook/sam3.1@daa63191845a41281374e725f4c9e51c7a824460',
    expectedPath: `${basePath}/sam3_1/sam3.1_multiplex.pt`,
    source: 'official manually gated facebook/sam3.1 repository; canonical private ingest pending authorized human terms acceptance',
    license: 'SAM License; legal/commercial-use review and authorized human terms acceptance pending',
    commercialUseAllowed: false,
    commercialUseStatus: 'needs_review',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: [
      'Automated terms acceptance and third-party mirror substitution are forbidden.',
      'The exact official checkpoint bytes, length, SHA-256, generation, ETag, malware scan, and license approval must be canonically reread.',
      'A100 and L4 immutable runtimes require separate quality, performance, cost, and temporal-mask qualification before dispatch.',
      'CPU execution, job-time downloads, quantization, resolution reduction, and SAM 2 fallback are forbidden for new work.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'deepfilternet_model',
    toolId: 'deepfilternet',
    modelName: 'DeepFilterNet model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/deepfilternet/`,
    source: 'model source placeholder; must be reviewed before voice cleanup execution',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Audio cleanup model weights must pass commercial-use, quality, and naturalness review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'demucs_model',
    toolId: 'demucs',
    modelName: 'Demucs model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/demucs/`,
    source: 'model source placeholder; stem separation weights must be reviewed',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Demucs must not be used as a default cleanup path and needs separate model-weight review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'torch_torchvision_model',
    toolId: 'torch_torchvision',
    modelName: 'TorchVision/downstream approved checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/torch-torchvision/`,
    source: 'model source placeholder; framework package does not approve pretrained checkpoints',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Torch/TorchVision package approval is separate from every pretrained checkpoint or downstream model artifact.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'transformers_model',
    toolId: 'transformers',
    modelName: 'Transformers model repository/checkpoint/tokenizer',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/transformers/`,
    source: 'model source placeholder; each Hugging Face or local model snapshot needs owner approval',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Transformers package approval does not approve remote downloads, tokenizers, checkpoints, or model repositories.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'real_esrgan_model',
    toolId: 'real_esrgan',
    modelName: 'Real-ESRGAN model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/real-esrgan/`,
    source: 'model source placeholder; enhancement weights require review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Enhancement weights must pass commercial-use and artifact/hallucination review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'film_model',
    toolId: 'film',
    modelName: 'FILM frame interpolation checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/film/`,
    source: 'model source placeholder; interpolation checkpoint review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['FILM weights must pass commercial-use and warping/temporal artifact review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'paddleocr_model',
    toolId: 'paddleocr',
    modelName: 'PaddleOCR detection/recognition model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/paddleocr/`,
    source: 'model source placeholder; OCR model review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['OCR model weights must pass commercial-use, privacy, and accuracy review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
]

export function listGpuModelWeightManifestTemplates(): ProductionModelWeightManifestTemplate[] {
  return [...GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES]
}

export function getGpuModelWeightManifestTemplate(
  id: ProductionModelWeightManifestTemplate['id'],
): ProductionModelWeightManifestTemplate | undefined {
  return GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES.find((template) => template.id === id)
}
