import type { ProductionModelWeightManifestTemplate } from './model-weight-manifest-types'

const basePath = '/opt/reeditpro/model-weights'

export const GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES: ProductionModelWeightManifestTemplate[] = [
  {
    id: 'faster_whisper_model',
    toolId: 'faster_whisper',
    modelName: 'faster-whisper model checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/faster-whisper/`,
    source: 'model source placeholder; must be filled by approved model-weight review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Whisper model/checkpoint license must be reviewed separately from faster-whisper and CTranslate2 code licenses.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'birefnet_model',
    toolId: 'birefnet',
    modelName: 'BiRefNet checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/birefnet/`,
    source: 'model source placeholder; not every related checkpoint is commercial-safe',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['BiRefNet-related weights vary; each selected checkpoint must prove commercial paid-production permission.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'sam2_checkpoint',
    toolId: 'sam2',
    modelName: 'SAM 2 checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/sam2/`,
    source: 'model source placeholder; checkpoint license review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['SAM 2 code/license assumptions do not approve checkpoint use.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'deepfilternet_model',
    toolId: 'deepfilternet',
    modelName: 'DeepFilterNet model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/deepfilternet/`,
    source: 'model source placeholder; must be reviewed before voice cleanup execution',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Audio cleanup model weights must pass commercial-use, quality, and naturalness review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'demucs_model',
    toolId: 'demucs',
    modelName: 'Demucs model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/demucs/`,
    source: 'model source placeholder; stem separation weights must be reviewed',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Demucs must not be used as a default cleanup path and needs separate model-weight review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'real_esrgan_model',
    toolId: 'real_esrgan',
    modelName: 'Real-ESRGAN model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/real-esrgan/`,
    source: 'model source placeholder; enhancement weights require review',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['Enhancement weights must pass commercial-use and artifact/hallucination review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'film_model',
    toolId: 'film',
    modelName: 'FILM frame interpolation checkpoint',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/film/`,
    source: 'model source placeholder; interpolation checkpoint review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['FILM weights must pass commercial-use and warping/temporal artifact review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'wan_video_model',
    toolId: 'wan_video',
    modelName: 'Wan/Wan2.1 video generation model',
    modelVersion: 'Wan-AI/Wan2.1-T2V-1.3B@37ec512624d61f7aa208f7ea8140a131f93afc9a',
    expectedPath: `${basePath}/ai-video-broll/wan2.1-t2v-1.3b/`,
    source: 'Controlled cache evidence: docs/ai-video-broll-generation-controlled-model-weight-download-manifest.md; private cache outside repo; production mount path still needs owner approval',
    license: 'Apache-2.0 evidence recorded in controlled Wan/Wan2.1 manifest; commercial runtime use still needs model-weight owner approval',
    commercialUseAllowed: false,
    commercialUseStatus: 'needs_review',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: [
      'Primary AI B-roll candidate has controlled source/cache evidence, but no runtime mount, inference, generated video, beta, or production use is approved by this template.',
      'The controlled manifest records file-level checksums outside this template; milestone storage policy forbids claiming template checksum coverage before runtime owner approval.',
      'Worker execution still requires approved model-weight review, private mount/path acceptance, GPU quota, source install review, approved snapshot, QA, and billing evidence.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'ltx_video_model',
    toolId: 'ltx_video',
    modelName: 'LTX-Video model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/ai-video-broll/ltx-video/`,
    source: 'LTX-Video model source placeholder; version-specific model-card and checkpoint evidence required',
    license: 'Repository/model-card terms require version-specific commercial review',
    commercialUseAllowed: false,
    commercialUseStatus: 'needs_review',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: [
      'Secondary fast-preview and image-to-video candidate; version split and weight provenance must be reviewed before use.',
      'No local fixture, preview generation, keyframe animation, or beta claim is approved by this template.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'mochi_video_model',
    toolId: 'mochi_video',
    modelName: 'Mochi 1 video generation model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/ai-video-broll/mochi-1/`,
    source: 'Mochi 1 model source placeholder; exact checkpoint, license, and LoRA/research path evidence required',
    license: 'Apache/permissive claim requires checkpoint-level review',
    commercialUseAllowed: false,
    commercialUseStatus: 'needs_review',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: [
      'Fallback/research candidate only until quality, GPU cost, provenance, and checkpoint licensing are accepted.',
      'No generated video, LoRA training, model download, or production route is approved by this template.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'hunyuan_video_model',
    toolId: 'hunyuan_video',
    modelName: 'HunyuanVideo model',
    modelVersion: 'blocked-legal-territory-commercial-review',
    expectedPath: `${basePath}/ai-video-broll/hunyuanvideo/`,
    source: 'HunyuanVideo model source placeholder; legal, territory, commercial, and GPU review required before any download planning',
    license: 'Custom HunyuanVideo terms; blocked until legal review accepts commercial and territory constraints',
    commercialUseAllowed: false,
    commercialUseStatus: 'blocked',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'blocked',
    riskNotes: [
      'Optional premium-gated candidate only; blocked before weight download, inference, fallback, beta, or production routing.',
      'Requires legal, territory, commercial, GPU, billing, and provider/runtime owner acceptance before reconsideration.',
    ],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
  {
    id: 'paddleocr_model',
    toolId: 'paddleocr',
    modelName: 'PaddleOCR detection/recognition model',
    modelVersion: 'placeholder-needs-review',
    expectedPath: `${basePath}/paddleocr/`,
    source: 'model source placeholder; OCR model review required',
    license: 'unknown',
    commercialUseAllowed: false,
    commercialUseStatus: 'unknown',
    redistributionAllowed: false,
    requiresAttribution: false,
    reviewStatus: 'needs_review',
    riskNotes: ['OCR model weights must pass commercial-use, privacy, and accuracy review.'],
    requiredForProduction: true,
    blocksProductionIfMissing: true,
  },
]

export function listGpuModelWeightManifestTemplates(): ProductionModelWeightManifestTemplate[] {
  return [...GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES]
}

export function getGpuModelWeightManifestTemplate(
  id: ProductionModelWeightManifestTemplate['id'],
): ProductionModelWeightManifestTemplate | undefined {
  return GPU_MODEL_WEIGHT_MANIFEST_TEMPLATES.find((template) => template.id === id)
}
