import type { SpecialistAgentRole } from './shared-agent-tool-architecture-types'

const baseForbiddenActions = [
  'execute tools directly',
  'authorize raw prompt execution',
  'call providers',
  'mutate GCP or production resources',
  'create public artifacts',
  'bypass approved plan snapshot policy',
]

export const agentRoleRegistry: SpecialistAgentRole[] = [
  {
    agentId: 'director',
    displayName: 'Director Agent',
    purpose: 'Owns story, creative intent, audience, emotional direction, and final edit purpose.',
    allowedEvidence: ['compiled user intent', 'workflow context', 'source sequence map', 'reference DNA', 'agent findings'],
    allowedIntentTypes: ['creative_direction', 'audience_positioning', 'story_priority', 'tone_adjustment'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['story priority', 'emotional direction', 'creative tradeoffs', 'final edit purpose'],
    downstreamToolFamilies: ['editorial_planning', 'graphics_design', 'visual_video', 'audio', 'map_geospatial', 'web_search'],
    readinessDependencies: ['compiled intent', 'approval gate', 'Producer scope check', 'QA/Safety policy check'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'editor',
    displayName: 'Editor Agent',
    purpose: 'Owns pacing, sequence structure, hooks, dead space, timeline rhythm, and cut logic.',
    allowedEvidence: ['timeline evidence', 'shot evidence', 'speech/transcript evidence', 'Track A/Track B findings'],
    allowedIntentTypes: ['cut_pacing', 'sequence_structure', 'hook_refinement', 'dead_space_removal'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['cut candidates', 'sequence pacing', 'rhythm adjustments', 'trim review needs'],
    downstreamToolFamilies: ['track_a_visual_video', 'track_b_audio_data', 'remotion_render_validation'],
    readinessDependencies: ['timeline evidence', 'meaning preservation policy', 'approved timing plan'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'cinematographer',
    displayName: 'Cinematographer Agent',
    purpose: 'Owns framing, camera angle, movement, composition, and shot quality.',
    allowedEvidence: ['VLM/video understanding evidence', 'FFprobe evidence', 'motion evidence', 'depth/mask evidence'],
    allowedIntentTypes: ['shot_quality', 'composition_adjustment', 'camera_movement', 'framing_review'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['shot quality assessment', 'composition needs', 'camera movement recommendations'],
    downstreamToolFamilies: ['track_a_visual_video', 'track_b_vlm_when_approved', 'map_geospatial_when_location_visual'],
    readinessDependencies: ['Track A readiness', 'VLM exclusion policy until resolved', 'source footage privacy policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'colorist',
    displayName: 'Colorist Agent',
    purpose: 'Owns exposure, contrast, color mood, look, and visual consistency.',
    allowedEvidence: ['OpenColorIO evidence', 'OpenImageIO evidence', 'Kornia metrics', 'FFmpeg signal evidence'],
    allowedIntentTypes: ['conservative_color_adjustment', 'look_consistency', 'exposure_balance', 'shot_match'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['color look intent', 'skin-tone preservation needs', 'shot match priority'],
    downstreamToolFamilies: ['track_a_visual_video', 'track_b_image_processing_consumed'],
    readinessDependencies: ['Track A readiness', 'color QA policy', 'approved plan snapshot'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'compositor_vfx',
    displayName: 'Compositor/VFX Agent',
    purpose: 'Owns masks, subject separation, backgrounds, foreground layers, text-behind-subject, and overlays.',
    allowedEvidence: ['SAM2 evidence', 'BiRefNet evidence', 'depth/mask evidence', 'Track A visual tools'],
    allowedIntentTypes: ['text_behind_subject_preview', 'mask_refinement', 'overlay_composition', 'background_treatment'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['compositing need', 'mask risk level', 'overlay placement', 'fallback to safer layout'],
    downstreamToolFamilies: ['track_a_visual_video', 'track_b_sharp_libvips_consumed', 'ai_tools_graphics_when_design_asset'],
    readinessDependencies: ['Track A readiness', 'mask QA policy', 'approved artifact scope'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'motion',
    displayName: 'Motion Agent',
    purpose: 'Owns slow motion, motion quality, artifacts, interpolation candidates, and camera movement.',
    allowedEvidence: ['FILM evidence', 'motion/flow evidence', 'FFprobe evidence', 'timeline evidence'],
    allowedIntentTypes: ['slow_motion_segment', 'motion_artifact_review', 'camera_motion_plan', 'interpolation_candidate'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['slow-motion candidates', 'motion risk', 'interpolation scope', 'motion fallback'],
    downstreamToolFamilies: ['track_a_visual_video', 'ai_tools_motion_graphics_when_graphic'],
    readinessDependencies: ['FILM scope policy', 'Track A readiness', 'timing approval policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'audio',
    displayName: 'Audio Agent',
    purpose: 'Owns speech clarity, noise, music, voiceover, dubbing, and timing-safe audio decisions.',
    allowedEvidence: ['Track B audio evidence', 'DeepFilterNet evidence', 'speech evidence', 'SoundSync timing plans'],
    allowedIntentTypes: ['noise_cleanup', 'voiceover_generation', 'music_ducking', 'audio_timing_adjustment'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['speech clarity priority', 'noise cleanup intent', 'music/ducking intent', 'voiceover need'],
    downstreamToolFamilies: ['track_b_audio', 'sound_sync_planning'],
    readinessDependencies: ['Track B audio readiness', 'credit approval', 'voice-first mix policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'search_research',
    displayName: 'Search/Research Agent',
    purpose: 'Owns source discovery, citations, web context, and planning research.',
    allowedEvidence: ['source manifests', 'capture manifests', 'extraction manifests', 'provider readiness reports'],
    allowedIntentTypes: ['web_research_planning_context', 'source_citation_request', 'capture_plan_candidate'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['source confidence', 'citation needs', 'research scope', 'provider fallback recommendation'],
    downstreamToolFamilies: ['web_search_capture'],
    readinessDependencies: ['Phase 49P web-search internal beta candidate readiness', 'provider storage policy', 'artifact privacy policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'map_location',
    displayName: 'Map/Location Agent',
    purpose: 'Owns location planning, map candidates, route/area reasoning, and geospatial visual plans.',
    allowedEvidence: ['planning source records', 'location candidates', 'GeoJSON', 'Turf calculations', 'map render manifests'],
    allowedIntentTypes: ['route_map_overlay', 'location_context_card', 'area_context_map', 'map_scene_plan'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['map scene need', 'location certainty', 'route/area reasoning', 'geospatial source-of-truth manifests'],
    downstreamToolFamilies: ['map_geospatial'],
    readinessDependencies: ['Phase 50G controlled internal readiness', 'no live tile/geocoding/routing policy', 'source-of-truth policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'graphics_design',
    displayName: 'Graphics/Design Agent',
    purpose: 'Owns graphic asset requests and motion/design briefs while routing implementation to AI Tools.',
    allowedEvidence: ['graphic intent', 'brand direction', 'design briefs', 'AI Tools capability manifests'],
    allowedIntentTypes: ['motion_graphics_lower_third', 'brand_card', 'infographic_brief', 'animated_callout'],
    forbiddenActions: [...baseForbiddenActions, 'claim direct ownership of AI Tools implementations'],
    ownedDecisions: ['graphic brief', 'design intent', 'visual card need', 'motion graphic request'],
    downstreamToolFamilies: ['ai_tools_graphics_design'],
    readinessDependencies: ['AI Tools capability manifest', 'brand/style policy', 'approved plan snapshot'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'producer',
    displayName: 'Producer Agent',
    purpose: 'Owns runtime cost, scope, permissions, beta readiness, tool availability, and privacy constraints.',
    allowedEvidence: ['capability manifests', 'readiness state', 'cost policies', 'privacy policies', 'approval gates'],
    allowedIntentTypes: ['scope_adjustment', 'go_no_go', 'cost_control', 'readiness_blocker'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['scope/cost feasibility', 'readiness go/no-go', 'privacy limits', 'manual action required'],
    downstreamToolFamilies: ['all_capability_manifests'],
    readinessDependencies: ['current readiness reports', 'credit policy', 'privacy policy', 'blocked features policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
  {
    agentId: 'qa_safety',
    displayName: 'QA/Safety Agent',
    purpose: 'Owns technical validation, artifact privacy, blocked features, hallucination risk, and output QA.',
    allowedEvidence: ['agent findings', 'candidate plans', 'artifact manifests', 'QA reports', 'policy gates'],
    allowedIntentTypes: ['qa_blocker', 'safety_review', 'artifact_privacy_check', 'policy_rejection'],
    forbiddenActions: baseForbiddenActions,
    ownedDecisions: ['policy pass/fail', 'hallucination risk', 'artifact privacy status', 'blocked feature enforcement'],
    downstreamToolFamilies: ['qa_policy', 'capability_manifests'],
    readinessDependencies: ['all relevant QA gates', 'approved plan snapshot policy', 'artifact privacy policy'],
    cannotExecuteToolsDirectly: true,
    cannotAuthorizeRawPromptExecution: true,
    structuredFindingsAndIntentsOnly: true,
    mustRespectApprovedPlanSnapshotPolicy: true,
  },
]
