import type { SchemaDefinition } from './shared-agent-tool-architecture-types'

export const approvedPlanSnapshotSchema: SchemaDefinition = {
  schemaId: 'approved_plan_snapshot_v1',
  description: 'Immutable executable contract for future workers after policy, approval, budget, and QA gates.',
  requiredFields: [
    'planId',
    'planVersion',
    'createdAt',
    'sourceRequestId',
    'approvedByPolicy',
    'rawPromptExecution',
    'inputArtifactScope',
    'outputArtifactScope',
    'selectedToolRoutes',
    'selectedIntents',
    'rejectedIntents',
    'safetyFlags',
    'budgetLimits',
    'privacyLimits',
    'runtimeLimits',
    'allowedBuckets',
    'allowedPrefixes',
    'publicArtifactAllowed',
    'providerCallsAllowed',
    'productionReadyAllowed',
    'externalBetaAllowed',
    'broadMediaAllowed',
    'qaRequirements',
    'rollbackPolicy',
  ],
  requiredDefaults: {
    rawPromptExecution: false,
    publicArtifactAllowed: false,
    productionReadyAllowed: false,
    externalBetaAllowed: false,
    broadMediaAllowed: false,
  },
  policyNotes: [
    'Raw chat is never a worker instruction.',
    'The approved plan snapshot is the executable contract.',
    'Workers must reject unknown scope, tool, action, bucket, or prefix.',
    'Signed URLs are not source of truth.',
    'Public artifacts are blocked unless a later phase explicitly approves them.',
  ],
}
