import type { ToolOwnershipMap } from './shared-agent-tool-architecture-types'

export const toolOwnershipMap: ToolOwnershipMap = {
  mapId: 'phase52a-tool-ownership-map',
  groups: [
    {
      ownerId: 'this_chat',
      displayName: 'This chat / system integration track',
      owns: [
        'SearXNG',
        'Brave Search API optional fallback policy',
        'Playwright for controlled search/map capture usage',
        'Sharp consumed for screenshot processing only',
        'Mozilla Readability',
        'source/capture/extraction manifests',
        'MapLibre',
        'Turf',
        'deck.gl',
        'CesiumJS',
        'OpenStreetMap/open map data policy',
        'PMTiles/TileServer GL/Martin future-scoped',
        'Nominatim/Photon/Pelias future-scoped',
        'OSRM/Valhalla future-scoped',
        'shared agent architecture',
        'system integration/readiness',
      ],
      consumerNotes: ['Consumes Sharp screenshot derivatives without claiming Track B general Sharp/libvips ownership.'],
      forbiddenClaims: ['AI Tools creative graphics implementation', 'Track B general compute/media tooling', 'Track A visual-video core runtime'],
    },
    {
      ownerId: 'ai_tools_chat',
      displayName: 'AI Tools chat',
      owns: [
        'Remotion creative graphics',
        'D3.js',
        'Three.js',
        'PixiJS',
        'Anime.js',
        'Lottie-web',
        'SVG.js',
        'Apache ECharts',
        'Vega/Vega-Lite',
        'Viz.js/Graphviz',
        'Satori',
        '@resvg/resvg-js',
        'motion graphics',
        'animated overlays',
        'title cards',
        'lower thirds',
        'infographics',
        'charts',
        'diagrams',
        'SVG graphics',
        'brand-style visual cards',
        'animated callouts',
        'timeline graphics',
        'data visualization',
        'UI-style animations',
        '3D visual elements',
        'canvas effects',
        'Lottie overlays',
        'graph/network diagrams',
        'render-ready graphic assets',
        'transparent overlays',
        'social video graphics',
      ],
      consumerNotes: ['Other tracks route graphics/design requests through AI Tools capability manifests.'],
      forbiddenClaims: ['Map/geospatial renderer ownership', 'web search provider ownership', 'Track B audio/OCR/VLM ownership'],
    },
    {
      ownerId: 'track_b',
      displayName: 'Track B / audio OCR data compute',
      owns: [
        'PaddleOCR',
        'PaddlePaddle',
        'OpenCV',
        'PyAV',
        'PySceneDetect',
        'Sharp/libvips as general image-processing capability',
        'DuckDB',
        'Polars',
        'DeepFilterNet',
        'Signalsmith Stretch',
        'Demucs',
        'Qwen3-VL',
        'vLLM',
        'web capability profiler',
        'desktop capability profiler',
        'local worker sidecar planning',
        'cost estimator',
        'tool route manifest integration',
      ],
      consumerNotes: ['VLM remains excluded from initial internal testing; Demucs remains blocked pending model provenance.'],
      forbiddenClaims: ['AI Tools creative graphics ownership', 'map/geospatial ownership', 'web search provider ownership'],
    },
    {
      ownerId: 'track_a_visual_video',
      displayName: 'Track A / visual-video core',
      owns: [
        'FFmpeg',
        'FFprobe',
        'libass',
        'Remotion render validation path',
        'OpenTimelineIO',
        'OpenColorIO',
        'OpenImageIO',
        'Kornia',
        'BiRefNet',
        'SAM2',
        'Real-ESRGAN scoped path',
        'FILM',
        'full visual-video private E2E',
      ],
      consumerNotes: ['Track A is internally ready for private visual-video testing from prior phases.'],
      forbiddenClaims: ['web search provider ownership', 'map/geospatial ownership', 'AI Tools creative graphics ownership'],
    },
  ],
  rules: [
    'No chat claims another chat track tool without an explicit integration phase.',
    'Shared consumers consume capabilities through manifests.',
    'A consumer does not own the tool it consumes.',
    'Workers execute approved plan snapshots only.',
  ],
}
