import type { SchemaDefinition } from './shared-agent-tool-architecture-types'

export const toolCapabilityManifestSchema: SchemaDefinition = {
  schemaId: 'tool_capability_manifest_v1',
  description: 'Canonical manifest for tool ownership, readiness, runtime requirements, artifact policy, and allowed consumers.',
  requiredFields: [
    'manifestVersion',
    'track',
    'toolId',
    'displayName',
    'owner',
    'status',
    'internalTestingReady',
    'internalBetaCandidateReady',
    'productionReady',
    'capabilities',
    'inputs',
    'outputs',
    'artifactPolicy',
    'runtimeRequirements',
    'dependencyRequirements',
    'secretsRequired',
    'modelArtifactsRequired',
    'privacyConstraints',
    'costConstraints',
    'failureModes',
    'blockedUses',
    'allowedConsumers',
    'readinessEvidence',
    'supabaseMilestoneRefs',
    'testCommands',
    'lastValidatedPhase',
    'lastValidatedRunId',
  ],
  policyNotes: [
    'Manifest consumers do not become owners.',
    'Production-ready must remain false unless a later production gate approves it.',
    'Secrets and model artifacts are declared by name/path policy only, never by secret value.',
  ],
  examples: [
    {
      manifestVersion: '1.0',
      track: 'map_geospatial',
      toolId: 'maplibre',
      displayName: 'MapLibre GL JS',
      owner: 'this_chat',
      status: 'controlled_internal_local_offline_ready',
      internalTestingReady: true,
      internalBetaCandidateReady: false,
      productionReady: false,
      capabilities: ['local/offline map rendering from generated GeoJSON and local style manifests'],
      blockedUses: ['live tiles', 'public OSM tile hotlinking', 'Mapbox/Google Maps provider calls'],
      allowedConsumers: ['Map/Location Agent', 'Producer Agent', 'QA/Safety Agent'],
      lastValidatedPhase: '50G',
    },
    {
      manifestVersion: '1.0',
      track: 'web_search',
      toolId: 'searxng',
      displayName: 'SearXNG',
      owner: 'this_chat',
      status: 'internal_beta_candidate_ready',
      internalTestingReady: true,
      internalBetaCandidateReady: true,
      productionReady: false,
      capabilities: ['private controlled search provider'],
      blockedUses: ['public SearXNG instances', 'broad crawling', 'production search'],
      allowedConsumers: ['Search/Research Agent', 'Producer Agent', 'QA/Safety Agent'],
      lastValidatedPhase: '49P',
    },
    {
      manifestVersion: '1.0',
      track: 'web_search',
      toolId: 'brave_search',
      displayName: 'Brave Search API',
      owner: 'this_chat',
      status: 'optional_paid_fallback_budget_secret_storage_gated',
      internalTestingReady: true,
      internalBetaCandidateReady: false,
      productionReady: false,
      capabilities: ['one-call controlled confidence booster when explicitly enabled'],
      blockedUses: ['automatic fallback', 'raw response storage', 'snippet storage by default'],
      allowedConsumers: ['Search/Research Agent', 'Producer Agent', 'QA/Safety Agent'],
      lastValidatedPhase: '49L',
    },
    {
      manifestVersion: '1.0',
      track: 'ai_tools_chat',
      toolId: 'ai_tools_remotion_graphics',
      displayName: 'AI Tools Remotion Graphics',
      owner: 'ai_tools_chat',
      status: 'owned_by_ai_tools_manifest_required',
      internalTestingReady: false,
      internalBetaCandidateReady: false,
      productionReady: false,
      capabilities: ['motion graphics', 'lower thirds', 'title cards', 'data visualizations'],
      blockedUses: ['direct execution by shared agents'],
      allowedConsumers: ['Graphics/Design Agent via manifest only'],
      lastValidatedPhase: '52A',
    },
    {
      manifestVersion: '1.0',
      track: 'track_b',
      toolId: 'track_b_sharp_libvips',
      displayName: 'Sharp/libvips',
      owner: 'track_b',
      status: 'general_image_processing_owned_by_track_b',
      internalTestingReady: false,
      internalBetaCandidateReady: false,
      productionReady: false,
      capabilities: ['image metadata and derivative processing'],
      blockedUses: ['ownership transfer to web-search/map tracks'],
      allowedConsumers: ['This chat may consume screenshot derivatives through approved manifests only'],
      lastValidatedPhase: '52A',
    },
    {
      manifestVersion: '1.0',
      track: 'track_b',
      toolId: 'track_b_qwen_vlm_vllm',
      displayName: 'Qwen3-VL + vLLM',
      owner: 'track_b',
      status: 'excluded_for_initial_internal_testing',
      reason: 'L4/vLLM CUDA OOM during approved Phase 39C safe profiles',
      futureRequiredAction: 'smaller approved model, quantized artifact, runtime redesign, or approved hardware profile',
      internalTestingReady: false,
      internalBetaCandidateReady: false,
      productionReady: false,
      blockedUses: ['initial internal testing', 'real media VLM inference'],
      allowedConsumers: ['No runtime consumers until a later VLM resolution phase'],
      lastValidatedPhase: '47B',
    },
    {
      manifestVersion: '1.0',
      track: 'track_b',
      toolId: 'demucs',
      displayName: 'Demucs',
      owner: 'track_b',
      status: 'blocked_pending_model_provenance',
      requiredBeforeRuntime: 'approved model artifact, license/provenance review, checksum manifest, private artifact path, runtime QA',
      internalTestingReady: false,
      internalBetaCandidateReady: false,
      productionReady: false,
      blockedUses: ['vocal/music/stem separation runtime'],
      allowedConsumers: ['No runtime consumers until model provenance clears'],
      lastValidatedPhase: '36G',
    },
  ],
}
