import type { EditLevel } from '../../types/reeditpro'
import type {
  ProfessionalSkillBackendIntent,
  ProfessionalSkillDefinition,
  ProfessionalSkillExecutionMode,
  ProfessionalSkillFamily,
  ProfessionalSkillInputKind,
  ProfessionalSkillOutputKind,
} from '../../types/professional-skills'

type SkillInput = Omit<ProfessionalSkillDefinition, 'supportedEditLevels' | 'userVisible' | 'requiresPrivateArtifacts'> & {
  supportedEditLevels?: EditLevel[]
  userVisible?: boolean
  requiresPrivateArtifacts?: boolean
}

const allLevels: EditLevel[] = ['basic', 'pro', 'premium']
const planOnly: ProfessionalSkillExecutionMode[] = ['plan_only']
const dryRunBounded: ProfessionalSkillExecutionMode[] = ['plan_only', 'dry_run', 'bounded_execution']
const backendPlanningGates = [
  'approved_plan_snapshot_required',
  'approved_credit_estimate_required',
  'active_credit_reservation_required',
  'backend_worker_only',
  'idempotency_required',
] as const

function modelRoleIntent(input: {
  intentId: string
  userFacingActivity: string
  providerRoute: string
  providerModel: string
  modelRoleId: ProfessionalSkillBackendIntent['modelRoleId']
  requestedModelUse: ProfessionalSkillBackendIntent['requestedModelUse']
}): ProfessionalSkillBackendIntent {
  return {
    intentKind: 'model_role',
    executionBoundary: 'backend_approved_after_snapshot',
    hiddenAdapterToolNames: [],
    requiredApprovalGates: [...backendPlanningGates],
    ...input,
  }
}

function providerAssetIntent(input: {
  intentId: string
  userFacingActivity: string
  providerRoute: string
  providerModel: string
  generationType: string
  outputAssetType: string
}): ProfessionalSkillBackendIntent {
  return {
    intentKind: 'provider_asset',
    executionBoundary: 'backend_approved_after_snapshot',
    hiddenAdapterToolNames: [],
    requiredApprovalGates: [...backendPlanningGates, 'private_artifact_manifest_required'],
    ...input,
  }
}

function skill(input: SkillInput): ProfessionalSkillDefinition {
  return {
    ...input,
    supportedEditLevels: input.supportedEditLevels ?? allLevels,
    userVisible: input.userVisible ?? true,
    requiresPrivateArtifacts: input.requiresPrivateArtifacts ?? (
      input.requiredInputs.includes('source_video') ||
      input.requiredInputs.includes('source_audio')
    ),
  }
}

function inputs(...values: ProfessionalSkillInputKind[]) {
  return values
}

function outputs(...values: ProfessionalSkillOutputKind[]) {
  return values
}

const coreProfessionalSkillDefinitions: ProfessionalSkillDefinition[] = [
  skill({
    id: 'intent.compile_prompt_direction',
    family: 'intent_direction',
    userFacingName: 'Understand edit direction',
    userFacingActivity: 'Understand the edit request and turn it into clear direction',
    plannerDescription: 'Compile natural chat, setup choices, and optional brief details into structured editing intent.',
    triggerKeywords: ['edit', 'make', 'turn this', 'create', 'fix', 'polish', 'clean'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('compiled_intent'),
    hiddenAdapterToolNames: [],
    backendIntents: [
      modelRoleIntent({
        intentId: 'intent.compile_prompt_direction.kimi_primary_edit_agent',
        userFacingActivity: 'Understand the edit request and turn it into clear direction',
        providerRoute: 'kimi_k3_provider_boundary',
        providerModel: 'kimi-k3',
        modelRoleId: 'kimi_k3_main_edit_agent',
        requestedModelUse: 'edit_planning',
      }),
      modelRoleIntent({
        intentId: 'intent.compile_prompt_direction.terra_first_fallback',
        userFacingActivity: 'Understand the edit request and turn it into clear direction',
        providerRoute: 'gpt_5_6_terra_provider_boundary',
        providerModel: 'gpt-5.6-terra',
        modelRoleId: 'gpt_5_6_terra_fallback_edit_agent',
        requestedModelUse: 'edit_planning',
      }),
      modelRoleIntent({
        intentId: 'intent.compile_prompt_direction.deepseek_final_fallback',
        userFacingActivity: 'Understand the edit request and turn it into clear direction',
        providerRoute: 'deepseek_v4_pro_tool_code_boundary',
        providerModel: 'deepseek-v4-pro',
        modelRoleId: 'deepseek_v4_tool_code_agent',
        requestedModelUse: 'edit_planning',
      }),
    ],
    qaGates: ['intent_matches_user_request', 'no_raw_prompt_execution', 'approval_before_generation'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.review_sequence_and_structure',
    family: 'source_structure',
    userFacingName: 'Review source structure',
    userFacingActivity: 'Prepare source order, structure, and story flow for planning',
    plannerDescription: 'Use uploaded source order and clean assembly context to propose a professional edit structure.',
    triggerKeywords: ['source order', 'story', 'structure', 'cut down', 'shorten', 'make it flow', 'rough cut'],
    requiredInputs: inputs('source_video', 'source_order'),
    optionalInputs: inputs('planning_context', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: [],
    backendIntents: [
      modelRoleIntent({
        intentId: 'source.review_sequence_and_structure.qwen_visual_understanding',
        userFacingActivity: 'Prepare source order, structure, and story flow for planning',
        providerRoute: 'qwen2_5_vl_7b_instruct_provider_boundary',
        providerModel: 'Qwen2.5-VL-7B-Instruct',
        modelRoleId: 'qwen2_5_vl_visual_understanding',
        requestedModelUse: 'visual_understanding',
      }),
    ],
    qaGates: ['source_order_preserved_as_context', 'meaning_preservation', 'no_random_cuts'],
    executionModes: planOnly,
  }),
  skill({
    id: 'captions.clean_readable_captions',
    family: 'captions',
    userFacingName: 'Plan clean captions',
    userFacingActivity: 'Prepare readable captions that support the spoken message',
    plannerDescription: 'Plan caption style, placement, readability, and speech-safe timing.',
    triggerKeywords: ['caption', 'subtitle', 'subtitles', 'words on screen', 'text on screen'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('source_audio', 'edit_brief', 'edit_cues'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['caption_readability', 'caption_speech_alignment', 'caption_safe_zone'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.clean_voice',
    family: 'audio_cleanup',
    userFacingName: 'Clean voice audio',
    userFacingActivity: 'Prepare voice cleanup while preserving a natural sound',
    plannerDescription: 'Plan speech-first audio cleanup and avoid over-processing.',
    triggerKeywords: ['clean audio', 'voice audio', 'voice clearer', 'fix audio', 'background noise', 'noise', 'echo', 'hiss', 'audio cleanup'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan'),
    hiddenAdapterToolNames: ['pydub', 'noisereduce', 'pedalboard', 'deepfilternet', 'rnnoise'],
    qaGates: ['speech_clarity', 'natural_voice_preserved', 'no_audio_artifacts'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.loudness_delivery_check',
    family: 'audio_cleanup',
    userFacingName: 'Check loudness',
    userFacingActivity: 'Prepare loudness and voice-level checks for private review',
    plannerDescription: 'Plan delivery loudness checks and voice-safe leveling.',
    triggerKeywords: ['loudness', 'volume', 'too quiet', 'too loud', 'levels', 'normalize'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan', 'qa_report'),
    hiddenAdapterToolNames: ['pyloudnorm', 'ebu_r128_pyloudnorm', 'scipy'],
    qaGates: ['voice_loudness_safe', 'music_ducking_safe', 'delivery_loudness_trace'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'music.timing_and_energy_cues',
    family: 'music_sound',
    userFacingName: 'Plan music timing',
    userFacingActivity: 'Prepare rhythm, music, and energy timing cues',
    plannerDescription: 'Plan beat/energy-aware timing without overriding speech clarity.',
    triggerKeywords: ['music', 'beat', 'rhythm', 'sync', 'soundtrack', 'song', 'sound design', 'sfx'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('source_audio', 'edit_brief', 'edit_cues'),
    outputArtifacts: outputs('music_timing_plan'),
    hiddenAdapterToolNames: ['audioflux', 'librosa', 'music21', 'pretty_midi', 'mido', 'mir_eval'],
    qaGates: ['speech_clarity_over_beat_sync', 'sfx_has_story_reason', 'music_timing_trace'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.visual_explain_layer',
    family: 'visual_graphics',
    userFacingName: 'Plan visual explanation',
    userFacingActivity: 'Prepare clean visual explanation layers where they help the story',
    plannerDescription: 'Plan cards, callouts, diagrams, and explanatory overlays based on meaning.',
    triggerKeywords: ['explain', 'graphic', 'diagram', 'callout', 'overlay', 'visual explain', 'visualexplain', 'text card'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js', 'konva'],
    qaGates: ['visual_supports_meaning', 'safe_zone_preserved', 'no_clutter'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.chart_or_data_visual',
    family: 'data_visuals',
    userFacingName: 'Plan chart visual',
    userFacingActivity: 'Prepare precise chart or data visual layers',
    plannerDescription: 'Plan exact charts, diagrams, and data visuals when labels and source truth matter.',
    triggerKeywords: ['chart', 'graph', 'data', 'numbers', 'timeline', 'money flow', 'framework', 'diagram'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('data_visual_plan'),
    hiddenAdapterToolNames: ['d3', 'echarts', 'vega_lite', 'vega', 'viz_js'],
    qaGates: ['data_label_readability', 'source_truth_preserved', 'chart_not_misleading'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.living_frame_storytelling',
    family: 'motion_design',
    userFacingName: 'Plan Living Frame storytelling',
    userFacingActivity: 'Plan selective in-frame storytelling only where it helps the explanation',
    plannerDescription: 'Select the Living Frame composite planning direction from explicit editing intent while keeping scene construction, timing, tools, providers, approval, and execution closed.',
    triggerKeywords: [
      'living frame',
      'living a roll',
      'in frame explainer',
      'in frame explanation',
      'selective motion',
      'limited animation',
      'animated documentary still',
      'animation aware illustration',
      'photo animation',
      'still image animation',
      'still photo animation',
    ],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('visual_layer_plan', 'motion_plan', 'mask_plan'),
    hiddenAdapterToolNames: [],
    qaGates: [
      'living_frame_component_required_before_approval',
      'living_frame_non_use_allowed',
      'canonical_timing_revalidation_required',
      'alpha_provenance_verification_required',
    ],
    executionModes: planOnly,
  }),
  skill({
    id: 'motion.controlled_2d_motion',
    family: 'motion_design',
    userFacingName: 'Plan controlled motion',
    userFacingActivity: 'Prepare controlled motion design that supports the edit',
    plannerDescription: 'Plan reusable vector and canvas motion without random decoration.',
    triggerKeywords: ['motion', 'animate', 'animation', 'lottie', 'kinetic', 'smooth movement', 'premium motion'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    hiddenAdapterToolNames: ['lottie_web', 'animejs', 'pixi_js', 'konva'],
    qaGates: ['motion_supports_story', 'no_random_animation', 'timing_matches_meaning'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.controlled_3d_layer',
    family: 'motion_design',
    userFacingName: 'Plan 3D layer',
    userFacingActivity: 'Prepare a controlled 3D visual layer when it is worth the complexity',
    plannerDescription: 'Plan bounded 3D layers for product, explainer, or premium visual moments.',
    triggerKeywords: ['3d', 'three dimensional', 'product mockup', '3d chart', '3d scene'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['three', 'babylonjs'],
    qaGates: ['3d_layer_has_story_reason', 'performance_safe', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'color.image_consistency',
    family: 'color_image',
    userFacingName: 'Plan color consistency',
    userFacingActivity: 'Prepare color and image consistency checks',
    plannerDescription: 'Plan color/image QA and generated asset matching without claiming runtime color processing.',
    triggerKeywords: ['color', 'colour', 'grade', 'cinematic', 'match the look', 'clean look', 'premium look'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan', 'qa_report'),
    hiddenAdapterToolNames: ['opencolorio', 'openimageio', 'kornia'],
    qaGates: ['color_consistency', 'generated_asset_match', 'skin_tone_safe'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'mask.foreground_and_background',
    family: 'mask_enhancement',
    userFacingName: 'Plan foreground treatment',
    userFacingActivity: 'Prepare foreground, background, and mask treatment only when needed',
    plannerDescription: 'Plan cutout, background, and mask work behind strict model-weight and QA gates.',
    triggerKeywords: ['remove background', 'remove the background', 'background removal', 'cutout', 'mask', 'behind subject', 'foreground'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('mask_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['rembg', 'kornia'],
    qaGates: ['model_weight_approved', 'mask_edges_safe', 'meaning_preserved'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'enhancement.private_quality_pass',
    family: 'mask_enhancement',
    userFacingName: 'Plan quality enhancement',
    userFacingActivity: 'Prepare private quality-enhancement checks for low-quality source moments',
    plannerDescription: 'Plan enhancement only for justified source quality issues.',
    triggerKeywords: ['enhance', 'upscale', 'low quality', 'blurry', 'sharpen', 'fix quality'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['kornia', 'opencv'],
    qaGates: ['enhancement_not_overclaiming', 'artifact_review', 'model_weight_approved'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'render.private_review_packaging',
    family: 'render_packaging',
    userFacingName: 'Plan private review packaging',
    userFacingActivity: 'Prepare private review packaging and delivery validation',
    plannerDescription: 'Plan backend-only render/container validation after approval without public delivery.',
    triggerKeywords: ['export', 'review', 'download', 'package', 'deliver', 'mp4'],
    requiredInputs: inputs('approved_snapshot', 'private_artifact_manifest'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: ['mkvtoolnix_container_validation', 'gpac_mp4box_packaging_validation'],
    qaGates: ['private_artifact_only', 'container_integrity', 'no_public_delivery'],
    executionModes: dryRunBounded,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'qa.private_review_readiness',
    family: 'qa_review',
    userFacingName: 'Check private review readiness',
    userFacingActivity: 'Check the plan against intent, privacy, timing, and approval gates',
    plannerDescription: 'Add a final QA pass before any private review output is prepared.',
    triggerKeywords: ['qa', 'review', 'make sure', 'check', 'test', 'ready'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['approved_snapshot_required', 'credit_gate_required', 'privacy_artifact_policy', 'user_intent_match'],
    executionModes: planOnly,
  }),
]

const expandedProfessionalSkillDefinitions: ProfessionalSkillDefinition[] = [
  skill({
    id: 'source.detect_story_beats',
    family: 'source_structure',
    userFacingName: 'Find story beats',
    userFacingActivity: 'Identify the strongest story beats in the source',
    plannerDescription: 'Find opening, setup, proof, payoff, and closing moments without changing source truth.',
    triggerKeywords: ['story beats', 'best moments', 'strongest parts', 'key moments', 'find the story'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('planning_context', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: ['ffprobe', 'pyscenedetect'],
    qaGates: ['story_beats_support_intent', 'source_truth_preserved', 'no_random_reorder'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'source.preserve_meaning',
    family: 'source_structure',
    userFacingName: 'Preserve meaning',
    userFacingActivity: 'Protect the meaning of the source while tightening the edit',
    plannerDescription: 'Guard against misleading cuts, missing context, and accidental meaning changes.',
    triggerKeywords: ['preserve meaning', 'do not change meaning', 'keep context', 'do not mislead', 'faithful'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['meaning_preservation', 'context_not_removed', 'user_review_for_risky_cuts'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.trim_silence_and_dead_air',
    family: 'source_structure',
    userFacingName: 'Tighten dead air',
    userFacingActivity: 'Plan cleaner pacing by removing dead air safely',
    plannerDescription: 'Plan silence and pause cleanup while preserving speech clarity and natural timing.',
    triggerKeywords: ['dead air', 'long pauses', 'trim silence', 'remove silence', 'tighten pauses'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('source_sequence_plan', 'audio_plan'),
    hiddenAdapterToolNames: ['ffmpeg', 'librosa', 'pydub'],
    qaGates: ['speech_clarity', 'meaning_preservation', 'natural_pacing'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'source.remove_filler_words_carefully',
    family: 'source_structure',
    userFacingName: 'Clean filler words',
    userFacingActivity: 'Plan careful filler-word cleanup without making speech unnatural',
    plannerDescription: 'Plan filler cleanup as reviewable trim decisions rather than blind removal.',
    triggerKeywords: ['filler words', 'ums', 'uhs', 'remove ums', 'clean speech'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: ['ffmpeg'],
    qaGates: ['speech_still_natural', 'meaning_preserved', 'review_risky_cuts'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'source.retake_selection',
    family: 'source_structure',
    userFacingName: 'Choose best takes',
    userFacingActivity: 'Plan best-take selection across repeats and retakes',
    plannerDescription: 'Select stronger takes with reasons and confidence instead of blindly removing repeats.',
    triggerKeywords: ['retake', 'best take', 'repeated takes', 'repeats', 'choose the best'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('planning_context', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'qa_report'),
    hiddenAdapterToolNames: ['ffprobe'],
    qaGates: ['retake_reason_recorded', 'meaning_preservation', 'user_review_for_ambiguity'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'source.hook_candidate_selection',
    family: 'source_structure',
    userFacingName: 'Choose hook candidate',
    userFacingActivity: 'Plan a strong opening only when it fits the user request',
    plannerDescription: 'Select or avoid hooks based on user intent, workflow, and platform.',
    triggerKeywords: ['hook', 'opening', 'first 3 seconds', 'grab attention', 'intro'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['hook_policy_matches_intent', 'no_forced_hook', 'platform_fit'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.source_order_review',
    family: 'source_structure',
    userFacingName: 'Review source order',
    userFacingActivity: 'Review uploaded order before planning the final structure',
    plannerDescription: 'Treat uploaded order as source context and separate it from final edit order.',
    triggerKeywords: ['source order', 'clip order', 'uploaded order', 'keep order', 'reorder'],
    requiredInputs: inputs('source_video', 'source_order'),
    optionalInputs: inputs('edit_cues'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['uploaded_order_recorded', 'final_order_explained', 'approval_before_reorder'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.reference_dna_extraction',
    family: 'source_structure',
    userFacingName: 'Study reference style',
    userFacingActivity: 'Extract reference style without copying shot-for-shot',
    plannerDescription: 'Summarize pacing, captions, transitions, visual feel, and adaptation boundaries.',
    triggerKeywords: ['reference video', 'like this video', 'match this style', 'reference dna', 'inspired by'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('compiled_intent', 'source_sequence_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['reference_not_copied', 'style_adaptation_explained', 'source_truth_preserved'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.platform_cutdown',
    family: 'source_structure',
    userFacingName: 'Plan platform cutdown',
    userFacingActivity: 'Plan a platform-fit cutdown from the source',
    plannerDescription: 'Create a platform-aware structure while preserving essential context.',
    triggerKeywords: ['shorts', 'reels', 'tiktok', 'cutdown', 'short version', 'clip this'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['platform_fit', 'meaning_preservation', 'duration_target_reasonable'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.chapter_structure',
    family: 'source_structure',
    userFacingName: 'Plan chapters',
    userFacingActivity: 'Plan clear sections for longer source material',
    plannerDescription: 'Create section/chapter structure for lessons, podcasts, walkthroughs, and explainers.',
    triggerKeywords: ['chapters', 'sections', 'segments', 'lesson', 'walkthrough', 'course'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['section_flow_clear', 'required_steps_preserved', 'labels_readable'],
    executionModes: planOnly,
  }),

  skill({
    id: 'captions.speech_aligned_subtitles',
    family: 'captions',
    userFacingName: 'Align captions to speech',
    userFacingActivity: 'Plan captions that follow speech timing clearly',
    plannerDescription: 'Plan speech-aligned captions with frame-safe timing policy.',
    triggerKeywords: ['speech captions', 'align captions', 'caption timing', 'subtitle timing'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['caption_speech_alignment', 'frame_accurate_caption_plan', 'readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.small_premium_subtitles',
    family: 'captions',
    userFacingName: 'Plan premium subtitles',
    userFacingActivity: 'Prepare small premium subtitles with safe placement',
    plannerDescription: 'Plan quiet, premium caption styling for clean edits.',
    triggerKeywords: ['small captions', 'premium subtitles', 'small subtitles', 'minimal captions'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['caption_readability', 'safe_zone_preserved', 'style_matches_intent'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.bold_social_captions',
    family: 'captions',
    userFacingName: 'Plan bold social captions',
    userFacingActivity: 'Prepare bold social captions without covering important visuals',
    plannerDescription: 'Plan stronger caption styling for short-form videos while preserving safe zones.',
    triggerKeywords: ['bold captions', 'big captions', 'viral captions', 'social captions'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['caption_safe_zone', 'face_product_not_covered', 'readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.keyword_emphasis',
    family: 'captions',
    userFacingName: 'Highlight key words',
    userFacingActivity: 'Plan keyword emphasis for important spoken moments',
    plannerDescription: 'Highlight only meaningful words, not random decoration.',
    triggerKeywords: ['highlight keywords', 'keyword captions', 'emphasize words', 'important words'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_cues'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['keyword_emphasis_matches_meaning', 'no_random_highlights', 'caption_readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.lower_third_labels',
    family: 'captions',
    userFacingName: 'Plan lower thirds',
    userFacingActivity: 'Prepare clean lower-third labels when names or context matter',
    plannerDescription: 'Plan lower thirds for people, places, proof, or case-study context.',
    triggerKeywords: ['lower third', 'name label', 'person label', 'location label', 'speaker label'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('caption_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js', 'libass'],
    qaGates: ['label_source_truth', 'readability', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.accessibility_review',
    family: 'captions',
    userFacingName: 'Check caption accessibility',
    userFacingActivity: 'Check caption readability and accessibility for private review',
    plannerDescription: 'Review contrast, size, timing, placement, and reading speed.',
    triggerKeywords: ['accessible captions', 'readable captions', 'caption qa', 'accessibility'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('caption_plan', 'qa_report'),
    hiddenAdapterToolNames: ['libass'],
    qaGates: ['contrast_readable', 'reading_speed_safe', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'captions.multilingual_placeholder_policy',
    family: 'captions',
    userFacingName: 'Plan translation boundary',
    userFacingActivity: 'Record caption translation needs without pretending translation ran',
    plannerDescription: 'Keep multilingual captions as planning metadata unless a translation lane is approved.',
    triggerKeywords: ['translate captions', 'spanish captions', 'french captions', 'subtitles in'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['translation_not_overclaimed', 'language_target_recorded', 'approval_required'],
    executionModes: planOnly,
  }),
  skill({
    id: 'captions.no_caption_policy',
    family: 'captions',
    userFacingName: 'Respect no-caption request',
    userFacingActivity: 'Respect the request to avoid captions unless accessibility requires review',
    plannerDescription: 'Record explicit no-caption direction and avoid adding captions randomly.',
    triggerKeywords: ['no captions', 'no subtitles', 'without captions', 'do not add captions'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('caption_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['explicit_no_caption_respected', 'accessibility_exception_review', 'no_random_text'],
    executionModes: planOnly,
  }),

  skill({
    id: 'audio.noise_reduction',
    family: 'audio_cleanup',
    userFacingName: 'Reduce background noise',
    userFacingActivity: 'Prepare background-noise cleanup while preserving voice',
    plannerDescription: 'Plan noise reduction with conservative settings and artifact QA.',
    triggerKeywords: ['background noise', 'remove noise', 'noisy', 'hiss', 'hum', 'noise reduction'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan', 'qa_report'),
    hiddenAdapterToolNames: ['noisereduce', 'pydub', 'scipy', 'deepfilternet', 'rnnoise'],
    qaGates: ['speech_clarity', 'no_audio_artifacts', 'natural_voice_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.declip_and_level_safety',
    family: 'audio_cleanup',
    userFacingName: 'Check clipping and levels',
    userFacingActivity: 'Prepare clipping and level safety checks',
    plannerDescription: 'Detect risky peaks and plan safe level handling before approval.',
    triggerKeywords: ['clipping', 'distorted audio', 'peaking', 'too loud', 'blown out audio'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('audio_plan', 'qa_report'),
    hiddenAdapterToolNames: ['scipy', 'pyloudnorm', 'pydub'],
    qaGates: ['peak_safety', 'voice_loudness_safe', 'artifact_review'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.duck_music_under_voice',
    family: 'audio_cleanup',
    userFacingName: 'Plan music ducking',
    userFacingActivity: 'Prepare voice-safe music ducking',
    plannerDescription: 'Plan music/SFX ducking that protects speech clarity.',
    triggerKeywords: ['duck music', 'music under voice', 'music too loud', 'voice over music', 'lower music'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan', 'music_timing_plan'),
    hiddenAdapterToolNames: ['pyloudnorm', 'ebu_r128_pyloudnorm', 'pydub', 'pedalboard'],
    qaGates: ['speech_clarity', 'music_ducking_safe', 'no_sfx_over_speech'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.remove_room_tone_risk',
    family: 'audio_cleanup',
    userFacingName: 'Control room tone',
    userFacingActivity: 'Prepare room-tone cleanup without creating unnatural gaps',
    plannerDescription: 'Plan room-tone cleanup with natural continuity and no hard silence artifacts.',
    triggerKeywords: ['room tone', 'echoey room', 'room noise', 'background room', 'hollow audio'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan'),
    hiddenAdapterToolNames: ['noisereduce', 'pedalboard', 'pydub'],
    qaGates: ['natural_room_tone', 'no_hard_silence', 'speech_clarity'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.equalization_voice_presence',
    family: 'audio_cleanup',
    userFacingName: 'Improve voice presence',
    userFacingActivity: 'Prepare voice-presence and EQ cleanup notes',
    plannerDescription: 'Plan safe voice presence settings without harshness.',
    triggerKeywords: ['voice presence', 'eq', 'equalizer', 'make voice pop', 'clearer voice'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan'),
    hiddenAdapterToolNames: ['pedalboard', 'pydub', 'scipy'],
    qaGates: ['natural_voice_preserved', 'no_harsh_eq', 'speech_clarity'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.resample_normalize_source',
    family: 'audio_cleanup',
    userFacingName: 'Normalize source audio format',
    userFacingActivity: 'Prepare sample-rate and format normalization checks',
    plannerDescription: 'Plan sample-rate handling and source audio normalization for worker safety.',
    triggerKeywords: ['sample rate', 'resample', 'audio format', 'normalize audio format'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('audio_plan'),
    hiddenAdapterToolNames: ['resampy', 'audioread', 'pydub', 'scipy'],
    qaGates: ['sample_rate_recorded', 'no_pitch_drift', 'source_integrity'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'music.beat_grid_planning',
    family: 'music_sound',
    userFacingName: 'Plan beat grid',
    userFacingActivity: 'Prepare beat-grid timing for music-aware edits',
    plannerDescription: 'Plan beat grid and transitions without harming speech clarity.',
    triggerKeywords: ['beat grid', 'on beat', 'cut to beat', 'beat sync', 'music sync'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('music_timing_plan'),
    hiddenAdapterToolNames: ['audioflux', 'librosa', 'mir_eval'],
    qaGates: ['speech_clarity_over_beat_sync', 'beat_grid_trace', 'transition_timing_safe'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'music.energy_curve',
    family: 'music_sound',
    userFacingName: 'Plan energy curve',
    userFacingActivity: 'Prepare an energy curve for pacing and sound',
    plannerDescription: 'Plan where the edit should rise, settle, and land emotionally.',
    triggerKeywords: ['energy', 'build up', 'drop', 'emotional arc', 'make it engaging'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('source_audio', 'edit_brief'),
    outputArtifacts: outputs('music_timing_plan', 'source_sequence_plan'),
    hiddenAdapterToolNames: ['audioflux', 'librosa'],
    qaGates: ['energy_matches_story', 'speech_clarity', 'no_random_sfx'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'music.sfx_cue_direction',
    family: 'music_sound',
    userFacingName: 'Plan SFX cues',
    userFacingActivity: 'Prepare sound effect cues only where story moments justify them',
    plannerDescription: 'Plan SFX cue timing and restraint around visual/story cues.',
    triggerKeywords: ['sfx', 'sound effects', 'whoosh', 'impact sound', 'transition sound'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_cues'),
    outputArtifacts: outputs('music_timing_plan'),
    hiddenAdapterToolNames: ['pydub', 'pedalboard'],
    qaGates: ['sfx_has_story_reason', 'no_sfx_over_speech', 'timing_matches_visual_cue'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'music.midi_symbolic_timing',
    family: 'music_sound',
    userFacingName: 'Plan symbolic music timing',
    userFacingActivity: 'Prepare symbolic music timing cues when MIDI or structured music is relevant',
    plannerDescription: 'Plan MIDI/symbolic timing metadata for future music-aware edits.',
    triggerKeywords: ['midi', 'music notes', 'song structure', 'chord', 'melody'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_audio'),
    outputArtifacts: outputs('music_timing_plan'),
    hiddenAdapterToolNames: ['music21', 'pretty_midi', 'mido'],
    qaGates: ['symbolic_timing_trace', 'music_structure_recorded', 'no_runtime_overclaim'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'music.bed_selection_policy',
    family: 'music_sound',
    userFacingName: 'Plan music bed',
    userFacingActivity: 'Prepare music-bed direction without selecting unapproved copyrighted music',
    plannerDescription: 'Plan music mood, ducking, and constraints without public asset claims.',
    triggerKeywords: ['music bed', 'background music', 'soundtrack', 'add music', 'music mood'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('music_timing_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['music_rights_not_overclaimed', 'voice_first_ducking', 'mood_matches_intent'],
    executionModes: planOnly,
  }),
  skill({
    id: 'music.soundscape_balance',
    family: 'music_sound',
    userFacingName: 'Balance soundscape',
    userFacingActivity: 'Prepare balanced voice, music, and sound-design direction',
    plannerDescription: 'Plan mix relationships and emotional polish without hiding speech.',
    triggerKeywords: ['soundscape', 'sound design', 'mix', 'audio polish', 'cinematic sound'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('source_audio', 'edit_brief'),
    outputArtifacts: outputs('audio_plan', 'music_timing_plan'),
    hiddenAdapterToolNames: ['pyloudnorm', 'pedalboard', 'pydub'],
    qaGates: ['speech_clarity', 'mix_balance', 'sfx_has_story_reason'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'graphics.title_card',
    family: 'visual_graphics',
    userFacingName: 'Plan title card',
    userFacingActivity: 'Prepare a clean title card when the edit needs an opening label',
    plannerDescription: 'Plan a title card with safe typography and no clutter.',
    triggerKeywords: ['title card', 'opening title', 'intro card', 'headline card'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js'],
    qaGates: ['text_readability', 'safe_zone_preserved', 'brand_tone_match'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.callout_labels',
    family: 'visual_graphics',
    userFacingName: 'Plan callouts',
    userFacingActivity: 'Prepare precise callout labels for important source moments',
    plannerDescription: 'Plan callout placement, label density, and timing tied to meaning.',
    triggerKeywords: ['callout', 'label this', 'point to', 'highlight this', 'arrow'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_cues'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['svg_js', 'satori', 'konva'],
    qaGates: ['callout_points_to_correct_subject', 'label_readability', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.evidence_board',
    family: 'visual_graphics',
    userFacingName: 'Plan evidence board',
    userFacingActivity: 'Prepare evidence-board visuals without overstating claims',
    plannerDescription: 'Plan documentary/case-study evidence visuals with fact-safety constraints.',
    triggerKeywords: ['evidence board', 'proof', 'case study', 'documentary evidence', 'receipts'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('visual_layer_plan', 'qa_report'),
    hiddenAdapterToolNames: ['d3', 'satori', 'svg_js'],
    qaGates: ['fact_safety', 'claim_source_trace', 'no_defamation_overclaim'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.step_by_step_cards',
    family: 'visual_graphics',
    userFacingName: 'Plan step cards',
    userFacingActivity: 'Prepare step-by-step visual cards for tutorials or explainers',
    plannerDescription: 'Plan readable step cards while preserving required tutorial steps.',
    triggerKeywords: ['steps', 'step by step', 'tutorial card', 'process', 'how to'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js'],
    qaGates: ['required_steps_preserved', 'text_readability', 'timing_allows_reading'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.product_feature_cards',
    family: 'visual_graphics',
    userFacingName: 'Plan product feature cards',
    userFacingActivity: 'Prepare product feature cards with clean hierarchy',
    plannerDescription: 'Plan feature cards and proof points for product/business edits.',
    triggerKeywords: ['product feature', 'feature card', 'benefit card', 'show features'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js'],
    qaGates: ['product_claim_source_truth', 'text_hierarchy_clear', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.map_route_visual',
    family: 'visual_graphics',
    userFacingName: 'Plan map visual',
    userFacingActivity: 'Prepare map or route visuals only when geography matters',
    plannerDescription: 'Plan exact map/location visuals and avoid AI-generated fake geography.',
    triggerKeywords: ['map', 'location', 'route', 'neighborhood', 'travel route', 'where it is'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['map_label_accuracy', 'route_truth_preserved', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.browser_capture_plan',
    family: 'visual_graphics',
    userFacingName: 'Plan browser capture',
    userFacingActivity: 'Prepare safe browser capture or screen evidence planning',
    plannerDescription: 'Plan approved browser/screen capture targets without fetching arbitrary private pages.',
    triggerKeywords: ['website screenshot', 'browser capture', 'screen capture', 'show webpage', 'dashboard'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('visual_layer_plan', 'qa_report'),
    hiddenAdapterToolNames: ['playwright'],
    qaGates: ['capture_target_approved', 'no_secret_capture', 'source_truth_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.brand_safe_visual_style',
    family: 'visual_graphics',
    userFacingName: 'Plan brand-safe visuals',
    userFacingActivity: 'Prepare visual style that follows brand and reference notes',
    plannerDescription: 'Plan colors, typography tone, and visual restraint from optional brand/brief notes.',
    triggerKeywords: ['brand', 'brand kit', 'on brand', 'brand colors', 'style guide'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['satori', 'svg_js'],
    qaGates: ['brand_tone_match', 'text_readability', 'no_clutter'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'dataviz.metric_card',
    family: 'data_visuals',
    userFacingName: 'Plan metric card',
    userFacingActivity: 'Prepare a clean metric card for key numbers',
    plannerDescription: 'Plan numerical cards with readable hierarchy and source-truth notes.',
    triggerKeywords: ['metric', 'number', 'stat', 'statistic', 'kpi'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('data_visual_plan'),
    hiddenAdapterToolNames: ['satori', 'd3'],
    qaGates: ['number_source_trace', 'label_readability', 'not_misleading'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'dataviz.timeline_visual',
    family: 'data_visuals',
    userFacingName: 'Plan timeline visual',
    userFacingActivity: 'Prepare a timeline visual for chronology or process',
    plannerDescription: 'Plan timeline visuals with accurate ordering and readable labels.',
    triggerKeywords: ['timeline', 'chronology', 'sequence of events', 'history', 'roadmap'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('data_visual_plan'),
    hiddenAdapterToolNames: ['d3', 'vega_lite', 'svg_js'],
    qaGates: ['timeline_order_correct', 'label_readability', 'source_truth_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'dataviz.comparison_chart',
    family: 'data_visuals',
    userFacingName: 'Plan comparison chart',
    userFacingActivity: 'Prepare a comparison chart when contrast helps understanding',
    plannerDescription: 'Plan bar/table/comparison visuals with clear labels and no distorted scale.',
    triggerKeywords: ['compare', 'comparison', 'versus', 'vs', 'before and after', 'difference'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('data_visual_plan'),
    hiddenAdapterToolNames: ['echarts', 'vega_lite', 'd3'],
    qaGates: ['axis_scale_honest', 'label_readability', 'comparison_not_misleading'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'dataviz.money_flow',
    family: 'data_visuals',
    userFacingName: 'Plan money-flow visual',
    userFacingActivity: 'Prepare money-flow or relationship visuals with source-truth checks',
    plannerDescription: 'Plan flow/network visuals for business, finance, or evidence explanations.',
    triggerKeywords: ['money flow', 'flow chart', 'network', 'relationship graph', 'how money moves'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('data_visual_plan'),
    hiddenAdapterToolNames: ['d3', 'viz_js', 'vega'],
    qaGates: ['relationship_source_trace', 'not_misleading', 'label_readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'dataviz.chart_animation_timing',
    family: 'data_visuals',
    userFacingName: 'Plan chart animation',
    userFacingActivity: 'Prepare chart animation timing tied to the spoken point',
    plannerDescription: 'Plan chart reveal timing so labels remain readable and meaningful.',
    triggerKeywords: ['animate chart', 'chart animation', 'reveal graph', 'animated graph'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('data_visual_plan', 'motion_plan'),
    hiddenAdapterToolNames: ['d3', 'echarts', 'animejs'],
    qaGates: ['timing_matches_meaning', 'labels_readable_during_motion', 'no_random_animation'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'dataviz.diagram_layout',
    family: 'data_visuals',
    userFacingName: 'Plan diagram layout',
    userFacingActivity: 'Prepare a clean diagram layout for concepts or systems',
    plannerDescription: 'Plan diagram nodes, arrows, and hierarchy without visual clutter.',
    triggerKeywords: ['diagram', 'system', 'architecture', 'framework', 'explain the system'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('data_visual_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['d3', 'viz_js', 'svg_js'],
    qaGates: ['diagram_relationships_clear', 'label_readability', 'no_clutter'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'motion.stroke_motion_storytelling',
    family: 'motion_design',
    userFacingName: 'Plan Stroke Motion',
    userFacingActivity: 'Prepare Stroke Motion storytelling for moments that need visual explanation',
    plannerDescription: 'Plan stroke-style motion only where it supports spoken meaning.',
    triggerKeywords: ['stroke motion', 'drawn animation', 'hand drawn', 'sketch animation', 'storytelling motion'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief', 'edit_cues'),
    outputArtifacts: outputs('motion_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['svg_js', 'animejs', 'lottie_web'],
    qaGates: ['motion_supports_story', 'timing_matches_meaning', 'no_random_animation'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.kinetic_text',
    family: 'motion_design',
    userFacingName: 'Plan kinetic text',
    userFacingActivity: 'Prepare kinetic text only for meaningful emphasis',
    plannerDescription: 'Plan tasteful kinetic typography for key phrases and transitions.',
    triggerKeywords: ['kinetic text', 'moving text', 'animated text', 'text animation'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan', 'caption_plan'),
    hiddenAdapterToolNames: ['animejs', 'lottie_web', 'satori'],
    qaGates: ['text_readability', 'timing_matches_speech', 'no_random_animation'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.transition_language',
    family: 'motion_design',
    userFacingName: 'Plan transitions',
    userFacingActivity: 'Prepare transition language that fits pacing and meaning',
    plannerDescription: 'Plan cuts/transitions from story and timing rules, not random effects.',
    triggerKeywords: ['transition', 'transitions', 'smooth cuts', 'scene change', 'cut style'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    hiddenAdapterToolNames: ['remotion', 'animejs'],
    qaGates: ['transition_not_over_words', 'timing_matches_meaning', 'pacing_matches_intent'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.particle_or_glow_restrained',
    family: 'motion_design',
    userFacingName: 'Plan restrained effects',
    userFacingActivity: 'Prepare restrained effects only when they support the scene',
    plannerDescription: 'Plan subtle effects with restraint and performance safety.',
    triggerKeywords: ['particles', 'glow', 'effect', 'visual effect', 'spark'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    hiddenAdapterToolNames: ['pixi_js', 'animejs'],
    qaGates: ['effect_has_story_reason', 'performance_safe', 'no_visual_clutter'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.product_3d_mockup',
    family: 'motion_design',
    userFacingName: 'Plan 3D product mockup',
    userFacingActivity: 'Prepare a controlled 3D product mockup when helpful',
    plannerDescription: 'Plan 3D product visuals with safe framing and complexity limits.',
    triggerKeywords: ['3d product', 'product mockup', 'spin product', '3d mockup'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['three', 'babylonjs'],
    qaGates: ['3d_layer_has_story_reason', 'product_not_misrepresented', 'performance_safe'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.lottie_status_animation',
    family: 'motion_design',
    userFacingName: 'Plan reusable status animation',
    userFacingActivity: 'Prepare reusable vector animation for simple status moments',
    plannerDescription: 'Plan small Lottie-style status animations without bespoke AI video.',
    triggerKeywords: ['checkmark animation', 'status animation', 'icon animation', 'lottie'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('motion_plan'),
    hiddenAdapterToolNames: ['lottie_web'],
    qaGates: ['animation_reusable', 'no_random_decoration', 'timing_matches_meaning'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'color.clean_natural_grade',
    family: 'color_image',
    userFacingName: 'Plan clean natural color',
    userFacingActivity: 'Prepare a clean natural color direction',
    plannerDescription: 'Plan natural color and tone without claiming worker color processing.',
    triggerKeywords: ['natural color', 'clean color', 'make color nice', 'fix color'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan'),
    hiddenAdapterToolNames: ['opencolorio', 'openimageio'],
    qaGates: ['skin_tone_safe', 'color_consistency', 'no_overgrade'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'color.cinematic_contrast',
    family: 'color_image',
    userFacingName: 'Plan cinematic color',
    userFacingActivity: 'Prepare cinematic contrast while keeping source believable',
    plannerDescription: 'Plan cinematic color with exposure and skin-tone safety.',
    triggerKeywords: ['cinematic color', 'cinematic grade', 'cinematic contrast', 'movie look'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['opencolorio', 'openimageio'],
    qaGates: ['skin_tone_safe', 'exposure_safe', 'style_matches_intent'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'color.generated_asset_match',
    family: 'color_image',
    userFacingName: 'Match generated asset color',
    userFacingActivity: 'Prepare generated asset color matching',
    plannerDescription: 'Plan generated image/video asset color matching to source footage and panels.',
    triggerKeywords: ['match generated assets', 'match source color', 'asset color', 'consistent look'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan', 'qa_report'),
    hiddenAdapterToolNames: ['opencolorio', 'openimageio', 'kornia'],
    qaGates: ['generated_asset_match', 'panel_background_match', 'color_consistency'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'color.low_light_recovery_plan',
    family: 'color_image',
    userFacingName: 'Plan low-light recovery',
    userFacingActivity: 'Prepare low-light cleanup strategy without overclaiming recovery',
    plannerDescription: 'Plan conservative low-light enhancement and QA limits.',
    triggerKeywords: ['low light', 'dark footage', 'too dark', 'underexposed'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan', 'qa_report'),
    hiddenAdapterToolNames: ['openimageio', 'kornia'],
    qaGates: ['no_overclaim_recovery', 'artifact_review', 'exposure_safe'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'color.thumbnail_still_prep',
    family: 'color_image',
    userFacingName: 'Plan thumbnail still prep',
    userFacingActivity: 'Prepare thumbnail or still-image polish direction',
    plannerDescription: 'Plan safe still prep for thumbnails or cards without changing runtime behavior.',
    triggerKeywords: ['thumbnail', 'still image', 'cover frame', 'poster frame'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['sharp', 'openimageio', 'satori'],
    qaGates: ['thumbnail_source_truth', 'text_readability', 'no_public_delivery'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'mask.text_behind_subject',
    family: 'mask_enhancement',
    userFacingName: 'Plan text behind subject',
    userFacingActivity: 'Prepare text-behind-subject treatment with mask-risk review',
    plannerDescription: 'Plan depth-aware text with mask risk, contact object policy, and fallback layouts.',
    triggerKeywords: ['text behind subject', 'behind me text', 'behind person', 'depth text'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('mask_plan', 'visual_layer_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['rembg', 'kornia'],
    qaGates: ['model_weight_approved', 'mask_edges_safe', 'contact_object_policy'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'mask.subject_cutout_overlay',
    family: 'mask_enhancement',
    userFacingName: 'Plan subject cutout',
    userFacingActivity: 'Prepare subject cutout overlays only when the edit benefits',
    plannerDescription: 'Plan subject cutout treatment with safer fallback when masks are risky.',
    triggerKeywords: ['cut me out', 'subject cutout', 'person cutout', 'remove background from person'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('mask_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['rembg', 'kornia'],
    qaGates: ['mask_edges_safe', 'meaning_preserved', 'model_weight_approved'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'mask.object_anchor_callout',
    family: 'mask_enhancement',
    userFacingName: 'Plan object-anchored callout',
    userFacingActivity: 'Prepare object-anchored graphics with tracking-risk review',
    plannerDescription: 'Plan callouts anchored to objects only when tracking is reliable and useful.',
    triggerKeywords: ['track object', 'object callout', 'follow this object', 'anchor label'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_cues'),
    outputArtifacts: outputs('mask_plan', 'visual_layer_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['opencv', 'kornia'],
    qaGates: ['tracking_risk_review', 'label_points_to_correct_subject', 'fallback_layout_available'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'enhancement.upscale_preview_candidate',
    family: 'mask_enhancement',
    userFacingName: 'Plan upscale candidate',
    userFacingActivity: 'Prepare upscale candidate review for low-resolution source',
    plannerDescription: 'Plan enhancement only as private candidate evidence until model gates pass.',
    triggerKeywords: ['upscale', 'higher resolution', 'make sharper', 'enhance resolution'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['opencv', 'kornia'],
    qaGates: ['model_weight_approved', 'artifact_review', 'no_overclaim_recovery'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'enhancement.blur_artifact_review',
    family: 'mask_enhancement',
    userFacingName: 'Review blur risk',
    userFacingActivity: 'Prepare blur and artifact review for source quality decisions',
    plannerDescription: 'Plan source quality QA and fallback decisions for blurry source moments.',
    triggerKeywords: ['blurry', 'soft footage', 'out of focus', 'blur'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: ['opencv', 'kornia'],
    qaGates: ['blur_risk_recorded', 'do_not_overclaim_fix', 'fallback_review'],
    executionModes: dryRunBounded,
  }),

  skill({
    id: 'render.private_review_manifest',
    family: 'render_packaging',
    userFacingName: 'Plan private review manifest',
    userFacingActivity: 'Prepare private artifact input and output manifests',
    plannerDescription: 'Plan source, generated, and review artifacts as private manifest records.',
    triggerKeywords: ['artifact manifest', 'private review', 'review file', 'private output'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('approved_snapshot'),
    outputArtifacts: outputs('private_review_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['private_artifact_only', 'no_signed_url_source_truth', 'manifest_complete'],
    executionModes: planOnly,
  }),
  skill({
    id: 'render.container_integrity_validation',
    family: 'render_packaging',
    userFacingName: 'Plan container validation',
    userFacingActivity: 'Prepare private container validation for review output',
    plannerDescription: 'Plan backend-only container validation for private review packaging.',
    triggerKeywords: ['container validation', 'mp4 validation', 'package validation', 'mux'],
    requiredInputs: inputs('approved_snapshot', 'private_artifact_manifest'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: ['mkvtoolnix_container_validation', 'gpac_mp4box_packaging_validation'],
    qaGates: ['container_integrity', 'private_artifact_only', 'no_public_delivery'],
    executionModes: dryRunBounded,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'render.pipeline_support_validation',
    family: 'render_packaging',
    userFacingName: 'Plan render pipeline support',
    userFacingActivity: 'Prepare render pipeline support validation before private review',
    plannerDescription: 'Plan render pipeline readiness checks without running public export.',
    triggerKeywords: ['render pipeline', 'render support', 'private render', 'review render'],
    requiredInputs: inputs('approved_snapshot', 'private_artifact_manifest'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: ['remotion'],
    qaGates: ['render_pipeline_private_only', 'approved_snapshot_required', 'no_public_delivery'],
    executionModes: dryRunBounded,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'render.safe_export_boundary',
    family: 'render_packaging',
    userFacingName: 'Preserve export boundary',
    userFacingActivity: 'Keep export and public delivery blocked until approval gates pass',
    plannerDescription: 'Record export/public delivery blockers as product safety metadata.',
    triggerKeywords: ['export', 'publish', 'public link', 'download', 'share'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('approved_snapshot'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['no_public_delivery', 'approval_required', 'credit_gate_required'],
    executionModes: planOnly,
  }),

  skill({
    id: 'qa.intent_match_review',
    family: 'qa_review',
    userFacingName: 'Check intent match',
    userFacingActivity: 'Check that the plan matches the user request',
    plannerDescription: 'Compare selected activities, plan structure, and constraints to compiled intent.',
    triggerKeywords: ['matches my request', 'make sure it follows', 'intent', 'what i asked'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['user_intent_match', 'must_follow_rules_preserved', 'avoid_rules_preserved'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.privacy_artifact_review',
    family: 'qa_review',
    userFacingName: 'Check privacy boundary',
    userFacingActivity: 'Check private artifact and privacy boundaries',
    plannerDescription: 'Validate private-only artifacts, no public URLs, and no signed URL source truth.',
    triggerKeywords: ['privacy', 'private', 'safe', 'not public', 'secure'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('private_artifact_manifest'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['private_artifact_only', 'no_signed_url_source_truth', 'no_public_delivery'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.credit_approval_review',
    family: 'qa_review',
    userFacingName: 'Check approval and credits',
    userFacingActivity: 'Check plan approval and credit gates before any work starts',
    plannerDescription: 'Ensure expensive work remains behind plan approval and cost reservation gates.',
    triggerKeywords: ['credits', 'cost', 'approval', 'estimate', 'budget'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('approved_snapshot'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['approved_snapshot_required', 'credit_gate_required', 'no_silent_billing'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.timing_readability_review',
    family: 'qa_review',
    userFacingName: 'Check timing and readability',
    userFacingActivity: 'Check timing, captions, and visual readability before review',
    plannerDescription: 'Review frame/timing/safe-zone constraints across captions and visual layers.',
    triggerKeywords: ['timing qa', 'readability', 'safe zone', 'too fast', 'hard to read'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: ['opencv', 'playwright'],
    qaGates: ['timing_matches_meaning', 'caption_readability', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'qa.source_truth_review',
    family: 'qa_review',
    userFacingName: 'Check source truth',
    userFacingActivity: 'Check source truth and avoid misleading edits',
    plannerDescription: 'Validate claims, source sequence, and meaning-preservation constraints.',
    triggerKeywords: ['source truth', 'fact check', 'not misleading', 'accurate', 'proof'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_cues'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['source_truth_preserved', 'meaning_preservation', 'fact_safety'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.professional_finish_review',
    family: 'qa_review',
    userFacingName: 'Check professional finish',
    userFacingActivity: 'Check professional finish before private review',
    plannerDescription: 'Review polish, clutter, pacing, readability, audio, and private artifact boundaries.',
    triggerKeywords: ['professional finish', 'polish', 'quality check', 'qa', 'final check'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['professional_standard', 'no_clutter', 'speech_clarity', 'private_artifact_only'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.documentary_fact_safety',
    family: 'source_structure',
    userFacingName: 'Protect factual context',
    userFacingActivity: 'Protect factual context and avoid misleading claims',
    plannerDescription: 'Plan documentary/case-study edits with fact-safety, evidence, and context preservation.',
    triggerKeywords: ['documentary', 'case study', 'claim', 'evidence', 'proof', 'allegation', 'fact'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['fact_safety', 'source_truth_preserved', 'context_not_removed'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.tutorial_step_preservation',
    family: 'source_structure',
    userFacingName: 'Preserve tutorial steps',
    userFacingActivity: 'Preserve required tutorial steps while tightening the edit',
    plannerDescription: 'Protect required how-to steps from accidental trimming or reordering.',
    triggerKeywords: ['tutorial', 'how to', 'step by step', 'walkthrough', 'lesson', 'instructions'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['required_steps_preserved', 'meaning_preservation', 'source_order_preserved_as_context'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.product_demo_preservation',
    family: 'source_structure',
    userFacingName: 'Preserve product demo flow',
    userFacingActivity: 'Preserve required product demo moments',
    plannerDescription: 'Plan product demos with feature steps, proof points, and source context intact.',
    triggerKeywords: ['product demo', 'demo', 'feature', 'screen walkthrough', 'show the product'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['required_steps_preserved', 'product_context_preserved', 'no_misleading_cuts'],
    executionModes: planOnly,
  }),
  skill({
    id: 'source.user_marked_priority_review',
    family: 'source_structure',
    userFacingName: 'Respect priority moments',
    userFacingActivity: 'Respect source moments the user marks as important',
    plannerDescription: 'Keep user-marked clips, notes, or moments visible unless a new approval changes them.',
    triggerKeywords: ['must include', 'important part', 'keep this', 'do not cut', 'priority'],
    requiredInputs: inputs('user_prompt', 'source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('source_sequence_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['user_marked_moments_preserved', 'approval_before_removal', 'meaning_preservation'],
    executionModes: planOnly,
  }),
  skill({
    id: 'audio.sfx_story_cue_policy',
    family: 'music_sound',
    userFacingName: 'Plan story-based sound cues',
    userFacingActivity: 'Plan sound cues only where the story or visuals justify them',
    plannerDescription: 'Plan SFX cue timing, restraint, and speech-safe placement.',
    triggerKeywords: ['sound effects', 'sfx', 'whoosh', 'hit sound', 'sound cue'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('source_audio', 'edit_brief'),
    outputArtifacts: outputs('music_timing_plan', 'audio_plan'),
    hiddenAdapterToolNames: ['pydub_effects', 'pedalboard'],
    backendIntents: [
      providerAssetIntent({
        intentId: 'audio.sfx_story_cue_policy.mirelo_sfx',
        userFacingActivity: 'Plan sound cues only where the story or visuals justify them',
        providerRoute: 'mirelo_sfx_v1_5',
        providerModel: 'Mirelo SFX V1.5',
        generationType: 'sfx_asset',
        outputAssetType: 'generated_audio',
      }),
      providerAssetIntent({
        intentId: 'audio.sfx_story_cue_policy.mmaudio_fallback',
        userFacingActivity: 'Plan sound cues only where the story or visuals justify them',
        providerRoute: 'mmaudio_v2',
        providerModel: 'MMAudio V2',
        generationType: 'sfx_asset',
        outputAssetType: 'generated_audio',
      }),
    ],
    qaGates: ['sfx_has_story_reason', 'no_sfx_over_speech', 'timing_matches_meaning'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'audio.music_rights_boundary',
    family: 'music_sound',
    userFacingName: 'Check music boundary',
    userFacingActivity: 'Check music-use boundaries before planning a soundtrack',
    plannerDescription: 'Record when music is user-supplied, generated later, or blocked pending rights/source approval.',
    triggerKeywords: ['use this song', 'music rights', 'copyright music', 'licensed music', 'soundtrack'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_audio', 'edit_brief'),
    outputArtifacts: outputs('music_timing_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['music_source_approved', 'no_unapproved_public_music', 'approval_required'],
    executionModes: planOnly,
  }),
  skill({
    id: 'audio.voiceover_mix_policy',
    family: 'audio_cleanup',
    userFacingName: 'Plan voiceover mix',
    userFacingActivity: 'Prepare a voiceover-safe mix plan',
    plannerDescription: 'Plan dialogue, voiceover, music, and SFX balance with speech clarity as the top priority.',
    triggerKeywords: ['voiceover', 'voice over', 'narration', 'talking over music', 'mix voice'],
    requiredInputs: inputs('source_video', 'source_audio'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('audio_plan', 'music_timing_plan'),
    hiddenAdapterToolNames: ['pyloudnorm', 'ebu_r128_pyloudnorm', 'pedalboard'],
    qaGates: ['speech_clarity', 'music_ducking_safe', 'voice_loudness_safe'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.evidence_annotation',
    family: 'visual_graphics',
    userFacingName: 'Plan evidence annotations',
    userFacingActivity: 'Prepare evidence annotations without overstating the source',
    plannerDescription: 'Plan labels, arrows, source notes, and evidence callouts with fact-safety.',
    triggerKeywords: ['annotation', 'evidence', 'proof label', 'point out', 'highlight evidence'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief', 'edit_cues'),
    outputArtifacts: outputs('visual_layer_plan', 'qa_report'),
    hiddenAdapterToolNames: ['satori', 'svg_js', 'konva'],
    qaGates: ['source_truth_preserved', 'label_source_truth', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.screen_highlight_plan',
    family: 'visual_graphics',
    userFacingName: 'Plan screen highlights',
    userFacingActivity: 'Prepare screen highlights for demos or walkthroughs',
    plannerDescription: 'Plan cursor-free highlights, focus boxes, and step callouts for screen-based source.',
    triggerKeywords: ['screen highlight', 'screen recording', 'click highlight', 'browser highlight', 'focus box'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('visual_layer_plan'),
    hiddenAdapterToolNames: ['playwright', 'satori', 'svg_js'],
    qaGates: ['important_ui_not_covered', 'label_readability', 'source_truth_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'graphics.before_after_comparison',
    family: 'visual_graphics',
    userFacingName: 'Plan before-and-after',
    userFacingActivity: 'Prepare before-and-after comparison visuals',
    plannerDescription: 'Plan comparison layout, labels, and timing without misleading contrast.',
    triggerKeywords: ['before after', 'before-and-after', 'comparison', 'compare', 'split screen'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('visual_layer_plan', 'qa_report'),
    hiddenAdapterToolNames: ['satori', 'konva', 'svg_js'],
    qaGates: ['comparison_not_misleading', 'label_readability', 'safe_zone_preserved'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'data_visuals.source_backed_metric_policy',
    family: 'data_visuals',
    userFacingName: 'Check metric source',
    userFacingActivity: 'Check that metric visuals have a clear source',
    plannerDescription: 'Require source notes and confidence for numbers before chart planning.',
    triggerKeywords: ['metric', 'kpi', 'revenue', 'percentage', 'number', 'data source'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('data_visual_plan', 'qa_report'),
    hiddenAdapterToolNames: ['d3', 'echarts', 'vega_lite'],
    qaGates: ['source_truth_preserved', 'chart_not_misleading', 'data_label_readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'data_visuals.map_location_context',
    family: 'data_visuals',
    userFacingName: 'Plan location context',
    userFacingActivity: 'Prepare location context only when it helps the edit',
    plannerDescription: 'Plan map/location visuals with confidence, label density, and privacy boundaries.',
    triggerKeywords: ['map', 'location', 'route', 'city', 'neighborhood', 'where this happened'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('data_visual_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['location_confidence_recorded', 'privacy_boundary_preserved', 'label_readability'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.frame_layout_animation',
    family: 'motion_design',
    userFacingName: 'Plan layout motion',
    userFacingActivity: 'Prepare motion that respects the chosen frame layout',
    plannerDescription: 'Plan frame-safe motion for panels, speaker/visual layout, and lower sections.',
    triggerKeywords: ['layout motion', 'move panels', 'animated layout', 'frame layout', 'lower panel'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('motion_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['remotion', 'animejs', 'konva'],
    qaGates: ['safe_zone_preserved', 'motion_supports_story', 'confirmed_frame_required'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'motion.renderer_layer_brief',
    family: 'motion_design',
    userFacingName: 'Prepare renderer brief',
    userFacingActivity: 'Prepare a renderer-ready motion brief after approval',
    plannerDescription: 'Describe animation layers for the backend renderer without starting rendering.',
    triggerKeywords: ['renderer brief', 'motion brief', 'remotion', 'animate the edit', 'final composition'],
    requiredInputs: inputs('approved_snapshot', 'planning_context'),
    optionalInputs: inputs('private_artifact_manifest'),
    outputArtifacts: outputs('motion_plan', 'private_review_plan'),
    hiddenAdapterToolNames: ['remotion'],
    backendIntents: [
      modelRoleIntent({
        intentId: 'motion.renderer_layer_brief.kimi_primary_remotion_draft',
        userFacingActivity: 'Prepare a renderer-ready motion brief after approval',
        providerRoute: 'kimi_k3_provider_boundary',
        providerModel: 'kimi-k3',
        modelRoleId: 'kimi_k3_main_edit_agent',
        requestedModelUse: 'remotion_draft',
      }),
      modelRoleIntent({
        intentId: 'motion.renderer_layer_brief.terra_fallback_remotion_draft',
        userFacingActivity: 'Prepare a renderer-ready motion brief after approval',
        providerRoute: 'gpt_5_6_terra_provider_boundary',
        providerModel: 'gpt-5.6-terra',
        modelRoleId: 'gpt_5_6_terra_fallback_edit_agent',
        requestedModelUse: 'remotion_draft',
      }),
      modelRoleIntent({
        intentId: 'motion.renderer_layer_brief.deepseek_final_fallback_remotion_draft',
        userFacingActivity: 'Prepare a renderer-ready motion brief after approval',
        providerRoute: 'deepseek_v4_pro_tool_code_boundary',
        providerModel: 'deepseek-v4-pro',
        modelRoleId: 'deepseek_v4_tool_code_agent',
        requestedModelUse: 'remotion_draft',
      }),
    ],
    qaGates: ['approved_snapshot_required', 'timing_matches_meaning', 'no_public_delivery'],
    executionModes: dryRunBounded,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'color.skin_tone_protection',
    family: 'color_image',
    userFacingName: 'Protect skin tones',
    userFacingActivity: 'Protect natural skin tones during color planning',
    plannerDescription: 'Plan color work with skin-tone safety, generated-asset matching, and restraint.',
    triggerKeywords: ['skin tone', 'natural skin', 'too orange', 'too green', 'face color'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('color_plan', 'qa_report'),
    hiddenAdapterToolNames: ['kornia', 'opencolorio'],
    qaGates: ['skin_tone_safe', 'color_consistency', 'generated_asset_match'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'color.brand_palette_match',
    family: 'color_image',
    userFacingName: 'Match brand palette',
    userFacingActivity: 'Prepare brand-safe color matching',
    plannerDescription: 'Plan palette, accent color, and visual asset consistency from user-provided brand notes.',
    triggerKeywords: ['brand colors', 'brand palette', 'match brand', 'brand look', 'brand style'],
    requiredInputs: inputs('user_prompt'),
    optionalInputs: inputs('source_video', 'edit_brief'),
    outputArtifacts: outputs('color_plan', 'visual_layer_plan'),
    hiddenAdapterToolNames: ['opencolorio', 'openimageio', 'satori'],
    qaGates: ['brand_reference_recorded', 'color_consistency', 'generated_asset_match'],
    executionModes: dryRunBounded,
  }),
  skill({
    id: 'mask.person_product_safe_zone',
    family: 'mask_enhancement',
    userFacingName: 'Protect subject and product',
    userFacingActivity: 'Protect the subject, product, and contact objects during foreground planning',
    plannerDescription: 'Plan mask/depth work with contact-object and product-safe constraints.',
    triggerKeywords: ['product in hand', 'contact object', 'behind person', 'subject overlay', 'foreground depth'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('mask_plan', 'qa_report'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['rembg', 'kornia'],
    qaGates: ['contact_object_preserved', 'mask_edges_safe', 'meaning_preserved'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'mask.depth_aware_overlay_policy',
    family: 'mask_enhancement',
    userFacingName: 'Plan depth-aware overlay',
    userFacingActivity: 'Plan depth-aware overlays only when the source can support them',
    plannerDescription: 'Keep depth-aware compositing as an advanced planned treatment with mask-risk review.',
    triggerKeywords: ['depth overlay', 'text behind subject', 'depth aware', 'behind the person', 'foreground mask'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('mask_plan', 'visual_layer_plan'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['rembg', 'kornia'],
    qaGates: ['mask_risk_review', 'safe_zone_preserved', 'caption_above_masks'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'enhancement.source_quality_triage',
    family: 'mask_enhancement',
    userFacingName: 'Triage source quality',
    userFacingActivity: 'Check which source moments need quality help',
    plannerDescription: 'Plan enhancement candidates based on source quality, not decoration.',
    triggerKeywords: ['bad footage', 'low resolution', 'soft footage', 'grainy', 'quality issue'],
    requiredInputs: inputs('source_video'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    supportedEditLevels: ['pro', 'premium'],
    hiddenAdapterToolNames: ['opencv', 'kornia'],
    qaGates: ['enhancement_has_reason', 'artifact_review', 'model_weight_approved'],
    executionModes: ['plan_only', 'dry_run', 'blocked_until_model_weight_ready'],
  }),
  skill({
    id: 'render.private_preview_watermark_policy',
    family: 'render_packaging',
    userFacingName: 'Plan private preview markings',
    userFacingActivity: 'Plan private preview markings and review-only boundaries',
    plannerDescription: 'Record private-preview labeling and no-public-delivery boundaries.',
    triggerKeywords: ['preview watermark', 'private preview', 'review copy', 'draft review'],
    requiredInputs: inputs('approved_snapshot', 'private_artifact_manifest'),
    optionalInputs: inputs('planning_context'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: ['remotion'],
    qaGates: ['private_artifact_only', 'no_public_delivery', 'approved_snapshot_required'],
    executionModes: dryRunBounded,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'render.review_download_preflight',
    family: 'render_packaging',
    userFacingName: 'Check review download',
    userFacingActivity: 'Check private review download readiness without public delivery',
    plannerDescription: 'Validate private artifact availability, naming, expiry, and no signed URL source truth.',
    triggerKeywords: ['download preview', 'review download', 'private link', 'download draft'],
    requiredInputs: inputs('private_artifact_manifest'),
    optionalInputs: inputs('approved_snapshot', 'planning_context'),
    outputArtifacts: outputs('private_review_plan', 'qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['private_artifact_only', 'no_signed_url_source_truth', 'no_public_delivery'],
    executionModes: planOnly,
    requiresPrivateArtifacts: true,
  }),
  skill({
    id: 'qa.license_model_boundary_review',
    family: 'qa_review',
    userFacingName: 'Check license and model boundary',
    userFacingActivity: 'Check package, license, and model-weight boundaries before any execution',
    plannerDescription: 'Review package/source/model-weight readiness without claiming execution readiness.',
    triggerKeywords: ['license', 'model weights', 'checkpoint', 'package approval', 'source approval'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('edit_brief'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['license_source_approved', 'model_weight_approved', 'no_unapproved_package_execution'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.revision_safety_review',
    family: 'qa_review',
    userFacingName: 'Check revision safety',
    userFacingActivity: 'Check whether a revision needs a new plan and approval',
    plannerDescription: 'Ensure revisions that change scope invalidate stale plans and require approval.',
    triggerKeywords: ['revise', 'change the plan', 'new version', 'redo', 'make changes'],
    requiredInputs: inputs('planning_context'),
    optionalInputs: inputs('approved_snapshot', 'edit_brief'),
    outputArtifacts: outputs('qa_report'),
    hiddenAdapterToolNames: [],
    qaGates: ['stale_plan_invalidated', 'new_approval_required', 'credit_gate_required'],
    executionModes: planOnly,
  }),
  skill({
    id: 'qa.final_artifact_manifest_review',
    family: 'qa_review',
    userFacingName: 'Check artifact manifest',
    userFacingActivity: 'Check that private review artifacts are tracked before delivery',
    plannerDescription: 'Require manifest entries, versions, privacy, and cleanup policy for private artifacts.',
    triggerKeywords: ['artifact manifest', 'asset manifest', 'files ready', 'review assets', 'final files'],
    requiredInputs: inputs('private_artifact_manifest'),
    optionalInputs: inputs('approved_snapshot'),
    outputArtifacts: outputs('qa_report', 'private_review_plan'),
    hiddenAdapterToolNames: [],
    qaGates: ['manifest_complete', 'private_artifact_only', 'asset_versions_tracked'],
    executionModes: planOnly,
    requiresPrivateArtifacts: true,
  }),
]

export const professionalSkillDefinitions: ProfessionalSkillDefinition[] = [
  ...coreProfessionalSkillDefinitions,
  ...expandedProfessionalSkillDefinitions,
]

export function listProfessionalSkillDefinitions(): ProfessionalSkillDefinition[] {
  return [...professionalSkillDefinitions]
}

export function getProfessionalSkillDefinition(skillId: string): ProfessionalSkillDefinition | undefined {
  return professionalSkillDefinitions.find((definition) => definition.id === skillId)
}

export function listProfessionalSkillFamilies(): ProfessionalSkillFamily[] {
  return Array.from(new Set(professionalSkillDefinitions.map((definition) => definition.family)))
}

export function listProfessionalSkillHiddenAdapterNames(): string[] {
  return Array.from(new Set(professionalSkillDefinitions.flatMap((definition) => definition.hiddenAdapterToolNames)))
}
