import { proColorImageApprovalPolicy } from './pro-color-image-approval-policy'
import type { ProColorImageToolEvidence } from './pro-color-image-approval-types'

export const proColorImageToolEvidence: ProColorImageToolEvidence[] = [
  {
    toolId: 'opencolorio',
    displayName: 'OpenColorIO',
    toolFamily: 'professional color management / LUT / ACES-aware color transforms',
    intendedCapability: 'reproducible professional color management, LUT/look transforms, OCIO config validation, and ACES/config-aware color-space transforms',
    upstreamRepo: proColorImageApprovalPolicy.openColorIORepoUrl,
    officialReadmeUrl: proColorImageApprovalPolicy.openColorIOReadmeUrl,
    officialLicenseUrl: proColorImageApprovalPolicy.openColorIOLicenseUrl,
    licenseName: 'BSD-3-Clause',
    recommendedPhase40Role: 'Primary professional color-management engine for future generated fixture planning.',
    sourceEvidence: [
      {
        evidenceId: 'opencolorio-official-aswf-repo',
        toolId: 'opencolorio',
        sourceName: 'OpenColorIO official ASWF GitHub repository',
        sourceUrl: proColorImageApprovalPolicy.openColorIORepoUrl,
        sourceType: 'github',
        evidenceSummary: 'Official ASWF repository for OpenColorIO, a color-management solution for motion-picture production, VFX, and animation pipelines.',
        confidence: 'high',
        notes: [
          'Evidence supports planning only; no dependency was installed or executed.',
          'OpenColorIO is scoped to professional color management, not media decode or final export.',
        ],
      },
      {
        evidenceId: 'opencolorio-readme-color-management-aces-lut',
        toolId: 'opencolorio',
        sourceName: 'OpenColorIO README',
        sourceUrl: proColorImageApprovalPolicy.openColorIOReadmeUrl,
        sourceType: 'readme',
        evidenceSummary: 'README identifies OCIO as motion-picture color management with ACES compatibility and LUT-format agnostic operation.',
        confidence: 'high',
        notes: [
          'Phase 40B must use generated color fixtures before any controlled real-video sample.',
          'OCIO config and LUT provenance must be recorded before runtime use.',
        ],
      },
      {
        evidenceId: 'opencolorio-bsd-3-license',
        toolId: 'opencolorio',
        sourceName: 'OpenColorIO LICENSE',
        sourceUrl: proColorImageApprovalPolicy.openColorIOLicenseUrl,
        sourceType: 'license',
        evidenceSummary: 'Official OpenColorIO repository license text is BSD-style/BSD-3-Clause.',
        confidence: 'high',
        notes: ['License evidence is clear enough for staging planning only.'],
      },
    ],
    noInstallPerformed: true,
    noRuntimeExecuted: true,
    noMediaProcessed: true,
  },
  {
    toolId: 'openimageio',
    displayName: 'OpenImageIO',
    toolFamily: 'professional image I/O / metadata / frame validation',
    intendedCapability: 'robust image and frame-sequence I/O, metadata inspection, decode/write validation, and image/color format compatibility checks',
    upstreamRepo: proColorImageApprovalPolicy.openImageIORepoUrl,
    officialReadmeUrl: proColorImageApprovalPolicy.openImageIOReadmeUrl,
    officialLicenseUrl: proColorImageApprovalPolicy.openImageIOLicenseUrl,
    licenseName: 'Apache-2.0',
    recommendedPhase40Role: 'Primary professional image/frame I/O and metadata verification tool for future generated fixture planning.',
    sourceEvidence: [
      {
        evidenceId: 'openimageio-official-aswf-repo',
        toolId: 'openimageio',
        sourceName: 'OpenImageIO official ASWF GitHub repository',
        sourceUrl: proColorImageApprovalPolicy.openImageIORepoUrl,
        sourceType: 'github',
        evidenceSummary: 'Official ASWF repository for OpenImageIO, a VFX/animation image I/O and manipulation toolset.',
        confidence: 'high',
        notes: [
          'Evidence supports planning only; no dependency was installed or executed.',
          'OpenImageIO is scoped to image/frame validation and metadata, not video stream extraction.',
        ],
      },
      {
        evidenceId: 'openimageio-readme-image-io-metadata-tools',
        toolId: 'openimageio',
        sourceName: 'OpenImageIO README',
        sourceUrl: proColorImageApprovalPolicy.openImageIOReadmeUrl,
        sourceType: 'readme',
        evidenceSummary: 'README identifies format-agnostic VFX/animation image I/O APIs, metadata tools, and command-line image utilities such as oiiotool, iinfo, iconvert, and idiff.',
        confidence: 'high',
        notes: [
          'Phase 40B must verify only generated fixtures before real-video-derived frames.',
          'OIIO metadata output must be sanitized before docs or PR summaries.',
        ],
      },
      {
        evidenceId: 'openimageio-apache-2-license',
        toolId: 'openimageio',
        sourceName: 'OpenImageIO LICENSE.md',
        sourceUrl: proColorImageApprovalPolicy.openImageIOLicenseUrl,
        sourceType: 'license',
        evidenceSummary: 'Official OpenImageIO repository license is Apache-2.0 for original code.',
        confidence: 'high',
        notes: ['License evidence is clear enough for staging planning only.'],
      },
    ],
    noInstallPerformed: true,
    noRuntimeExecuted: true,
    noMediaProcessed: true,
  },
  {
    toolId: 'kornia',
    displayName: 'Kornia',
    toolFamily: 'PyTorch differentiable image processing / metrics / visual QA helpers',
    intendedCapability: 'local image-processing helpers, image metrics, frame-difference/quality helpers, and generated-fixture visual QA utilities',
    upstreamRepo: proColorImageApprovalPolicy.korniaRepoUrl,
    officialReadmeUrl: proColorImageApprovalPolicy.korniaReadmeUrl,
    officialLicenseUrl: proColorImageApprovalPolicy.korniaLicenseUrl,
    licenseName: 'Apache-2.0',
    recommendedPhase40Role: 'Generated-fixture visual QA helper; model/provider-style Kornia features remain blocked.',
    sourceEvidence: [
      {
        evidenceId: 'kornia-official-repo',
        toolId: 'kornia',
        sourceName: 'Kornia official GitHub repository',
        sourceUrl: proColorImageApprovalPolicy.korniaRepoUrl,
        sourceType: 'github',
        evidenceSummary: 'Official Kornia repository for PyTorch-based computer vision and image processing components.',
        confidence: 'high',
        notes: [
          'Evidence supports planning only; no dependency was installed or executed.',
          'Kornia is not approved for model/provider features in Phase 40A.',
        ],
      },
      {
        evidenceId: 'kornia-readme-image-processing-metrics',
        toolId: 'kornia',
        sourceName: 'Kornia README',
        sourceUrl: proColorImageApprovalPolicy.korniaReadmeUrl,
        sourceType: 'readme',
        evidenceSummary: 'README and module table identify PyTorch-based image processing areas including color, filters, enhance, morphology, geometry, losses, features, and metrics.',
        confidence: 'high',
        notes: [
          'Phase 40B must pin a minimal runtime scope and avoid model downloads.',
          'Kornia metrics may support generated fixture QA only until later approved phases.',
        ],
      },
      {
        evidenceId: 'kornia-apache-2-license',
        toolId: 'kornia',
        sourceName: 'Kornia LICENSE',
        sourceUrl: proColorImageApprovalPolicy.korniaLicenseUrl,
        sourceType: 'license',
        evidenceSummary: 'Official Kornia repository license is Apache-2.0.',
        confidence: 'high',
        notes: ['License evidence is clear enough for staging planning only.'],
      },
    ],
    noInstallPerformed: true,
    noRuntimeExecuted: true,
    noMediaProcessed: true,
  },
]

export function getProColorImageToolEvidence(toolId: ProColorImageToolEvidence['toolId']) {
  return proColorImageToolEvidence.find((tool) => tool.toolId === toolId)
}
