export const TRACK_ALL_ACCEPTED_ARTIFACT_TYPES = [
  'track_all_assignment_v1',
  'track_all_target_specification_v1',
  'source_inventory_v1',
  'master_timing_plan_v1',
  'source_frame_authority_v1',
  'visual_ownership_manifest_v1',
  'track_all_scene_context_v1',
  'track_all_preflight_observation_v1',
  'visual_intelligence_target_evidence_v1',
  'visual_intelligence_tracking_qa_v1',
  'approved_user_selection_v1',
  'approved_reference_image_v1',
  'approved_brush_mask_v1',
  'track_graph_v1',
  'track_graph_v2',
  'caption_reserved_zones_v1',
  'edit_preference_snapshot_v1',
  'privacy_policy_snapshot_v1',
  'prior_track_repair_evidence_v1',
  'source_media_artifact_v1',
  'track_all_sam3_1_approved_session_plan_set_v1',
] as const

export const TRACK_ALL_PRODUCED_ARTIFACT_TYPES = [
  'track_all_context_manifest_v1',
  'track_all_plan_v1',
  'track_all_planning_qa_report_v1',
  'track_all_sam3_1_runtime_profile_v2',
  'track_all_work_graph_v1',
  'track_graph_v1',
  'track_graph_v2',
  'track_sample_sequence_v1',
  'track_box_sequence_v1',
  'track_mask_sequence_v1',
  'track_mask_chunk_manifest_v1',
  'track_landmark_sequence_v1',
  'track_anchor_graph_v1',
  'camera_motion_graph_v1',
  'planar_track_graph_v1',
  'track_occlusion_event_log_v1',
  'track_identity_lineage_v1',
  'tracked_redaction_plan_v1',
  'tracked_redaction_result_v1',
  'tracked_focus_plan_v1',
  'tracked_focus_result_v1',
  'tracked_reframe_plan_v1',
  'tracked_reframe_result_v1',
  'track_all_target_qa_report_v1',
  'track_all_temporal_qa_report_v1',
  'track_all_mask_qa_report_v1',
  'track_all_privacy_qa_report_v1',
  'track_all_chunk_seam_qa_report_v1',
  'track_all_identity_qa_report_v1',
  'track_all_integration_qa_report_v1',
  'track_all_repair_receipt_v1',
  'track_all_cross_skill_handoff_v1',
  'track_all_result_receipt_v1',
  'track_all_atomic_execution_evidence_v1',
  'track_all_public_work_projection_evidence_v1',
  'track_all_atomic_execution_evidence_v2',
  'track_all_public_work_projection_evidence_v2',
  'track_all_sam3_1_approved_session_plan_set_v1',
  'track_all_sam3_1_real_private_session_receipt_v1',
  'track_all_sam3_1_masklet_attempt_evidence_v2',
  'track_all_sam3_1_masklet_output_manifest_v2',
  'track_all_sam3_1_masklet_manifest_set_v1',
  'track_all_normalized_masklet_observation_set_v1',
] as const

export type TrackAllAcceptedArtifactType =
  (typeof TRACK_ALL_ACCEPTED_ARTIFACT_TYPES)[number]
export type TrackAllProducedArtifactType =
  (typeof TRACK_ALL_PRODUCED_ARTIFACT_TYPES)[number]
