import {
  buildSoundMusicAudioAccessSafety,
  buildSoundMusicAudioCueGroups,
  buildSoundMusicAudioHandoffItems,
  buildSoundMusicAudioLyriaPlanningMetadata,
  buildSoundMusicAudioPlanSummary,
  buildSoundMusicAudioProviderSummaries,
  buildSoundMusicAudioQaNotes,
  buildSoundMusicAudioRuntimeSummaries,
  buildSoundMusicAudioSoundSyncNotes,
  type SoundMusicAudioPlanCardProps,
} from './buildSoundMusicAudioPlanCardProps'
import { buildSoundMusicAudioHandoffEvidenceReview } from './buildSoundMusicAudioHandoffEvidenceReview'
import type {
  PrivateAudioArtifactManifest,
  SoundAgentPlan,
  SoundBlockedUseReason,
  SoundCuePlan,
  SoundExecutionGateResult,
  SoundHandoffReadiness,
  SoundHandoffReadinessCheck,
  SoundProviderPolicy,
  SoundRuntimePolicy,
  SoundToolRequest,
  TimingAwareSoundCueManifest,
} from '../../../types/audio-music'

export interface MockSoundMusicAudioChatCardOptions {
  approvedPreview?: boolean
  removedCueIds?: string[]
}

const workspaceId = 'mock-sound-chat-workspace'
const projectId = 'mock-sound-chat-project'
const editPlanId = 'mock-sound-chat-edit-plan'

const mockBlockedUses: SoundBlockedUseReason[] = [
  'real_provider_call_blocked',
  'provider_generation_disabled',
  'approved_snapshot_required',
  'credit_approval_required',
  'credit_reservation_required',
  'worker_execution_not_allowed',
  'generated_asset_not_allowed',
  'storage_object_not_allowed',
  'public_artifact_blocked',
  'signed_url_blocked',
  'secret_blocked',
  'supabase_mutation_blocked',
  'final_render_export_not_owned',
  'provider_gateway_handoff_required',
  'worker_runtime_handoff_required',
]

const mockSoundProviderPolicies: SoundProviderPolicy[] = [
  {
    providerId: 'mock_sfx_provider',
    status: 'mock_only',
    generationEnabled: false,
    commercialExportAllowed: false,
    runtimeDefault: 'mock_only',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'not_applicable_mock',
      commercialUseStatus: 'commercial_export_blocked',
      commercialExportAllowed: false,
      notes: ['Mock SFX metadata only. No audio file, provider call, or reusable library asset is created.'],
    },
    defaultFor: ['action_foley_sfx', 'transition_sound', 'whoosh_hit_riser', 'ambient_everyday_soundscape'],
    notes: ['Used only to display chat planning state for action, foley, transition, and ambience cues.'],
  },
  {
    providerId: 'mirelo_sfx_mock',
    status: 'mock_only_real_client_placeholder_fail_closed',
    generationEnabled: false,
    commercialExportAllowed: false,
    runtimeDefault: 'external_provider_gateway',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'review_required',
      commercialUseStatus: 'pending_review',
      commercialExportAllowed: false,
      requiresLicenseGate: true,
      notes: ['Future SFX transport requires Provider Gateway, worker runtime, approval, credit, storage, QA, and license evidence.'],
    },
    defaultFor: ['action_foley_sfx', 'transition_sound', 'whoosh_hit_riser'],
    ownerBoundary: 'PROVIDER_GATEWAY_MODELS for real transport',
    notes: ['Displayed as fail-closed SFX planning metadata. It is not invoked by the chat renderer.'],
  },
  {
    providerId: 'dasheng_audiogen_candidate',
    status: 'candidate_requires_license_dependency_model_card_runtime_quality_review',
    generationEnabled: false,
    commercialExportAllowed: 'pending_review',
    runtimeDefault: 'gpu_cloud_run_job_l4',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'apache_2_candidate',
      commercialUseStatus: 'pending_review',
      commercialExportAllowed: 'pending_review',
      requiresLicenseGate: true,
      notes: ['Candidate status only. Model/license/runtime/quality evidence is required before any real use.'],
    },
    fallbackFor: ['action_foley_sfx', 'ambient_everyday_soundscape'],
    realExecutionOwnerBoundary: 'PROVIDER_GATEWAY_MODELS plus WORKER_RUNTIME_JOBS',
    notes: ['Future GPU metadata only; not selected for this chat mock preview.'],
  },
  {
    providerId: 'stable_audio_open_license_gated',
    status: 'conditional_license_gated_optional',
    generationEnabled: false,
    commercialExportAllowed: 'conditional_pending_license_review',
    runtimeDefault: 'gpu_cloud_run_job_l4',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'stability_ai_community_license_conditional',
      commercialUseStatus: 'conditional_pending_license_review',
      commercialExportAllowed: 'conditional_pending_license_review',
      requiresLicenseGate: true,
      notes: ['Optional ambience/music candidate metadata only. License gate and Provider Gateway handoff are required.'],
    },
    fallbackFor: ['ambient_everyday_soundscape', 'audio_bed', 'ambience_match'],
    realExecutionOwnerBoundary: 'PROVIDER_GATEWAY_MODELS plus WORKER_RUNTIME_JOBS',
    notes: ['Displayed as license-gated planning status, not as an enabled generator.'],
  },
  {
    providerId: 'lyria_mock',
    status: 'mock_only_real_client_placeholder_fail_closed',
    generationEnabled: false,
    commercialExportAllowed: false,
    runtimeDefault: 'external_provider_gateway',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'review_required',
      commercialUseStatus: 'commercial_export_blocked',
      commercialExportAllowed: false,
      requiresLicenseGate: true,
      notes: ['Google Lyria is music/song/soundtrack planning metadata only in this UI path.'],
    },
    defaultFor: ['music_cue', 'soundtrack_layer', 'audio_mood_design'],
    ownerBoundary: 'PROVIDER_GATEWAY_MODELS for real transport',
    notes: ['Provider Gateway is required before any real Lyria transport. Generation is disabled.'],
  },
  {
    providerId: 'audioflux_analysis_only',
    status: 'analysis_processing_only_not_generation_provider',
    generationEnabled: false,
    commercialExportAllowed: false,
    runtimeDefault: 'cpu_cloud_run_job',
    allowedForPlanning: true,
    licensePolicy: {
      licenseStatus: 'analysis_processing_only',
      commercialUseStatus: 'analysis_only_not_generation',
      commercialExportAllowed: 'pending_review',
      notes: ['Analysis metadata only. It is not a sound generation provider.'],
    },
    notes: ['Future SoundSync analysis candidate only; no model download or worker dispatch occurs.'],
  },
]

const mockSoundRuntimePolicies: SoundRuntimePolicy[] = [
  {
    policyKey: 'mock_chat_cpu_planning_metadata',
    runtimeTarget: 'cpu_service',
    executionMode: 'planning_only',
    planningAllowed: true,
    generationAllowed: false,
    requiresApprovedSnapshot: true,
    requiresCreditGate: true,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
    requiredHandoffs: ['SUPABASE_RLS_STORAGE_DATABASE', 'OBSERVABILITY_AUDIT_COST'],
    requiredEvidence: ['approved plan snapshot storage boundary', 'audit evidence plan'],
    blockedReasons: ['approved_snapshot_required', 'credit_approval_required', 'supabase_mutation_blocked'],
  },
  {
    policyKey: 'mock_chat_cpu_qa_mix_metadata',
    runtimeTarget: 'cpu_cloud_run_job',
    executionMode: 'planning_only',
    planningAllowed: true,
    generationAllowed: false,
    requiresApprovedSnapshot: true,
    requiresCreditGate: true,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
    requiredHandoffs: ['TRACK_B_MEDIA_PROCESSING', 'WORKER_RUNTIME_JOBS', 'OBSERVABILITY_AUDIT_COST'],
    requiredEvidence: ['audio QA job contract', 'worker claim and event evidence', 'speech ducking QA report'],
    blockedReasons: ['worker_execution_not_allowed', 'worker_runtime_handoff_required'],
  },
  {
    policyKey: 'mock_chat_future_gpu_generation_metadata',
    runtimeTarget: 'gpu_cloud_run_job_l4',
    executionMode: 'blocked',
    planningAllowed: true,
    generationAllowed: false,
    requiresApprovedSnapshot: true,
    requiresCreditGate: true,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
    requiredHandoffs: ['PROVIDER_GATEWAY_MODELS', 'WORKER_RUNTIME_JOBS', 'SUPABASE_RLS_STORAGE_DATABASE', 'OBSERVABILITY_AUDIT_COST'],
    requiredEvidence: ['provider contract', 'worker runtime config', 'private storage path policy', 'cost evidence'],
    blockedReasons: ['provider_gateway_handoff_required', 'worker_runtime_handoff_required', 'generated_asset_not_allowed'],
  },
  {
    policyKey: 'mock_chat_provider_gateway_disabled',
    runtimeTarget: 'external_provider_gateway',
    executionMode: 'blocked',
    planningAllowed: true,
    generationAllowed: false,
    requiresApprovedSnapshot: true,
    requiresCreditGate: true,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
    requiredHandoffs: ['PROVIDER_GATEWAY_MODELS', 'WORKER_RUNTIME_JOBS', 'SUPABASE_RLS_STORAGE_DATABASE'],
    requiredEvidence: ['provider-gateway transport review', 'secret handling review', 'retry/fallback policy'],
    blockedReasons: ['real_provider_call_blocked', 'provider_generation_disabled', 'secret_blocked'],
  },
  {
    policyKey: 'mock_chat_local_preview_only',
    runtimeTarget: 'mock_only',
    executionMode: 'mock_preview_only',
    planningAllowed: true,
    generationAllowed: false,
    requiresApprovedSnapshot: false,
    requiresCreditGate: false,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
    requiredHandoffs: [],
    requiredEvidence: ['local mock UI state only'],
    blockedReasons: ['runtime_target_mock_only'],
  },
]

const mockSoundCuePlans: SoundCuePlan[] = [
  {
    cueId: 'mock-chat-transition-whoosh',
    family: 'whoosh_hit_riser',
    role: 'whoosh',
    toolId: 'action_foley_sfx_tool',
    startTimeSeconds: 3.2,
    endTimeSeconds: 3.55,
    durationSeconds: 0.35,
    anchorType: 'transition',
    anchorId: 'cut-003',
    visualOrStoryReason: 'Subtle whoosh supports a fast cut into the title card without covering dialogue.',
    promptIntent: 'Short airy transition whoosh with soft tail, aligned to the cut.',
    negativePromptIntent: 'No loud impact, no cartoon sound, no synthetic vocal texture.',
    speechOverlap: 'possible',
    duckingRequired: true,
    intensity: 'subtle',
    providerCandidate: 'mock_sfx_provider',
    providerPolicyStatus: 'mock_only',
    providerBlockedReasons: ['provider_generation_disabled'],
    licenseEvidenceRequired: ['future reusable SFX license evidence before export'],
    runtimeTarget: 'mock_only',
    runtimePolicyKey: 'mock_chat_local_preview_only',
    approvalState: 'not_required',
    creditGateState: 'not_required',
    qaStatus: 'warning',
    blockedReasons: ['real_provider_call_blocked', 'generated_asset_not_allowed'],
  },
  {
    cueId: 'mock-chat-title-card-hit',
    family: 'transition_sound',
    role: 'title_card_accent',
    toolId: 'sfx_director_tool',
    startTimeSeconds: 5,
    endTimeSeconds: 5.42,
    durationSeconds: 0.42,
    anchorType: 'title_card',
    anchorId: 'title-card-001',
    visualOrStoryReason: 'Clean low hit marks the title-card reveal and should remain below speech-safe loudness.',
    promptIntent: 'Warm cinematic title-card accent with restrained transient and quick decay.',
    negativePromptIntent: 'No boom, no trailer slam, no aggressive riser.',
    speechOverlap: 'none',
    duckingRequired: false,
    intensity: 'medium',
    providerCandidate: 'mirelo_sfx_mock',
    providerPolicyStatus: 'mock_only_real_client_placeholder_fail_closed',
    providerBlockedReasons: ['provider_gateway_handoff_required', 'provider_generation_disabled'],
    licenseEvidenceRequired: ['Provider Gateway terms review', 'SFX provider license evidence'],
    runtimeTarget: 'external_provider_gateway',
    runtimePolicyKey: 'mock_chat_provider_gateway_disabled',
    approvalState: 'blocked',
    creditGateState: 'blocked',
    qaStatus: 'blocked',
    blockedReasons: ['real_provider_call_blocked', 'worker_execution_not_allowed', 'credit_reservation_required'],
  },
  {
    cueId: 'mock-chat-cafe-room-tone',
    family: 'ambient_everyday_soundscape',
    role: 'background_bed',
    toolId: 'ambient_everyday_soundscape_tool',
    startTimeSeconds: 7,
    endTimeSeconds: 15,
    durationSeconds: 8,
    anchorType: 'timeline_time',
    anchorId: 'segment-ambience-001',
    visualOrStoryReason: 'Soft cafe room tone smooths a dialogue section while keeping the speaker first.',
    promptIntent: 'Subtle cafe ambience bed with low crowd texture and gentle room tone.',
    negativePromptIntent: 'No foreground chatter, no clinking peaks, no attention-grabbing motion.',
    speechOverlap: 'speech_first_ducking_required',
    duckingRequired: true,
    intensity: 'subtle',
    providerCandidate: 'mock_sfx_provider',
    providerPolicyStatus: 'mock_only',
    providerBlockedReasons: ['provider_generation_disabled'],
    licenseEvidenceRequired: ['ambience provenance evidence before Track A handoff'],
    runtimeTarget: 'mock_only',
    runtimePolicyKey: 'mock_chat_local_preview_only',
    approvalState: 'not_required',
    creditGateState: 'not_required',
    qaStatus: 'warning',
    blockedReasons: ['public_artifact_blocked', 'storage_object_not_allowed'],
  },
  {
    cueId: 'mock-chat-lyria-music-bed',
    family: 'music_cue',
    role: 'music_mood_layer',
    toolId: 'music_cue_planner',
    startTimeSeconds: 0,
    endTimeSeconds: 18,
    durationSeconds: 18,
    anchorType: 'music_beat',
    anchorId: 'music-phrase-001',
    visualOrStoryReason: 'Instrumental music bed gives the edit a premium lift while ducking below dialogue.',
    promptIntent: 'Instrumental warm cinematic lifestyle cue, light pulse, no lyrical lead, designed for speech-first ducking.',
    negativePromptIntent: 'No vocals under dialogue, no copyrighted reference imitation, no hard drop over speech.',
    speechOverlap: 'speech_first_ducking_required',
    duckingRequired: true,
    intensity: 'subtle',
    providerCandidate: 'lyria_mock',
    providerPolicyStatus: 'mock_only_real_client_placeholder_fail_closed',
    providerBlockedReasons: ['provider_gateway_handoff_required', 'provider_generation_disabled', 'secret_blocked'],
    licenseEvidenceRequired: ['Lyria provider gateway review', 'music license and commercial export evidence'],
    runtimeTarget: 'external_provider_gateway',
    runtimePolicyKey: 'mock_chat_provider_gateway_disabled',
    approvalState: 'blocked',
    creditGateState: 'blocked',
    qaStatus: 'blocked',
    blockedReasons: ['real_provider_call_blocked', 'worker_execution_not_allowed', 'credit_reservation_required'],
  },
]

function buildReadinessCheck(
  checkName: SoundHandoffReadinessCheck['checkName'],
  status: SoundHandoffReadinessCheck['status'],
  handoffStatus: SoundHandoffReadinessCheck['handoffStatus'],
  requiredEvidence: string[],
  notes: string[],
  blockedReasons: SoundBlockedUseReason[] = [],
): SoundHandoffReadinessCheck {
  return {
    checkName,
    status,
    handoffStatus,
    blockedReasons,
    requiredEvidence,
    notes,
  }
}

function createMockSoundHandoffReadiness(cueIds: string[]): SoundHandoffReadiness {
  return {
    readinessId: 'mock-sound-chat-readiness',
    workstreamId: 'SOUND_MUSIC_AUDIO',
    workspaceId,
    projectId,
    privateAudioArtifactManifestIds: ['mock-sound-chat-private-manifest'],
    timingAwareCueManifestIds: ['mock-sound-chat-timing-manifest'],
    audioReadinessStatus: 'mock_safe',
    blockedUses: mockBlockedUses,
    requiredValidationEvidence: [
      'speech/ducking QA evidence',
      'provider license evidence',
      'private storage evidence',
      'worker runtime execution evidence',
      'observability and cost evidence',
    ],
    handoffTargets: [
      'TRACK_A_RENDER_EXPORT',
      'TRACK_B_MEDIA_PROCESSING',
      'PROVIDER_GATEWAY_MODELS',
      'WORKER_RUNTIME_JOBS',
      'SUPABASE_RLS_STORAGE_DATABASE',
      'OBSERVABILITY_AUDIT_COST',
    ],
    trackAStatus: 'handoff_required',
    trackBStatus: 'handoff_required',
    providerGatewayStatus: 'handoff_required',
    workerRuntimeStatus: 'blocked',
    supabaseStatus: 'blocked',
    observabilityStatus: 'handoff_required',
    billingStatus: 'handoff_required',
    readinessChecks: [
      buildReadinessCheck('planning', 'mock_safe', 'metadata_ready', ['typed mock card props'], ['Chat renderer displays planning metadata only.']),
      buildReadinessCheck('approval', 'blocked', 'blocked', ['future approved plan snapshot'], ['This UI approval is local preview state only.'], ['approved_snapshot_required']),
      buildReadinessCheck('credit_estimate', 'blocked', 'handoff_required', ['future approved credit estimate'], ['No credit rows, approvals, reservations, spend, or refund path exists here.'], ['credit_approval_required']),
      buildReadinessCheck('provider_license', 'blocked', 'handoff_required', ['Provider Gateway review', 'license and commercial export evidence'], ['Real transport and fallback belong to Provider Gateway.'], ['provider_gateway_handoff_required']),
      buildReadinessCheck('worker_execution', 'blocked', 'blocked', ['worker runtime contract', 'claim/lease/event evidence'], ['No worker dispatch or generated asset creation is allowed.'], ['worker_runtime_handoff_required']),
      buildReadinessCheck('audio_qa', 'planning_ready', 'handoff_required', ['speech ducking QA report', 'loudness evidence'], ['Audio QA is required before Track A handoff.']),
      buildReadinessCheck('private_artifact_manifest', 'mock_safe', 'metadata_ready', cueIds, ['Private manifest is metadata-only and has no storage object.']),
      buildReadinessCheck('timing_cue_manifest', 'mock_safe', 'metadata_ready', cueIds, ['Timing-aware cue manifest is metadata-only and SoundSync-coordinated.']),
      buildReadinessCheck('track_a_final_composition_handoff', 'blocked', 'handoff_required', ['final mix/mux validation evidence'], ['Track A owns final composition readiness.'], ['final_render_export_not_owned']),
      buildReadinessCheck('track_b_processing_handoff', 'blocked', 'handoff_required', ['audio processing contract'], ['Track B owns real media/audio processing execution.'], ['worker_runtime_handoff_required']),
      buildReadinessCheck('supabase_mutation', 'blocked', 'blocked', ['RLS/storage mutation policy'], ['No database mutation, storage write, public artifact, or signed access is created.'], ['supabase_mutation_blocked']),
      buildReadinessCheck('observability_audit_cost', 'blocked', 'handoff_required', ['audit event schema', 'cost evidence'], ['Observability and cost evidence are needed before beta or production.']),
      buildReadinessCheck('beta_production_readiness', 'blocked', 'blocked', ['go/no-go evidence'], ['This mock chat renderer does not unlock beta, production, or paid production.']),
    ],
    productionReadinessStatus: 'blocked',
  }
}

function createMockPrivateArtifactManifest(cueIds: string[]): PrivateAudioArtifactManifest {
  return {
    manifestId: 'mock-sound-chat-private-manifest',
    workspaceId,
    projectId,
    artifactKind: 'private_audio_artifact_manifest',
    metadataOnly: true,
    sourceCueIds: cueIds,
    generationRequestIds: [],
    generatedAssetIds: [],
    mediaAssetIds: [],
    timingMapIds: ['mock-sound-chat-timing-manifest'],
    storageScope: 'private',
    publicArtifactAllowed: false,
    licensePolicy: {
      licenseStatus: 'not_applicable_mock',
      commercialUseStatus: 'commercial_export_blocked',
      commercialExportAllowed: false,
      notes: ['Metadata-only chat manifest. No storage object, generated asset, provider output, or public artifact exists.'],
    },
    provenanceSummary: 'Mock chat planning manifest only. No audio file, storage write, generated asset, provider output, public artifact, or signed access exists.',
    qaEvidenceIds: [],
    blockedUses: mockBlockedUses,
    handoffTargets: ['TRACK_A_RENDER_EXPORT', 'TRACK_B_MEDIA_PROCESSING', 'PROVIDER_GATEWAY_MODELS', 'WORKER_RUNTIME_JOBS', 'SUPABASE_RLS_STORAGE_DATABASE', 'OBSERVABILITY_AUDIT_COST'],
    trackAHandoffStatus: 'handoff_required',
    providerGatewayHandoffStatus: 'handoff_required',
    workerRuntimeHandoffStatus: 'blocked',
  }
}

function createMockTimingManifest(cues: SoundCuePlan[]): TimingAwareSoundCueManifest {
  return {
    cueManifestId: 'mock-sound-chat-timing-manifest',
    workspaceId,
    projectId,
    editPlanId,
    version: 'SOUND-1F-mock-chat',
    metadataOnly: true,
    cues,
    timingAnchors: ['timeline_time', 'cut', 'transition', 'title_card', 'music_beat'],
    sourceReasoning: [
      'Transition cue snaps to the cut and title-card reveal.',
      'Ambience bed starts after the title card and stays background under speech.',
      'Music cue is phrase-aware planning metadata only; no beat detection or music generation has run.',
    ],
    speechDuckingNotes: [
      'Whoosh and ambience are marked subtle where speech may overlap.',
      'Music bed requires speech-first ducking before Track A handoff.',
      'Loud SFX under speech must be removed or downgraded during audio QA.',
    ],
    moodNotes: [
      'Soundtrack layer targets warm premium lift without vocals under dialogue.',
      'Every cue needs a visual, cut, gesture, title, ambience, or story reason.',
    ],
    providerPolicyIds: mockSoundProviderPolicies.map((provider) => provider.providerId),
    runtimeTargets: ['mock_only', 'cpu_service', 'cpu_cloud_run_job', 'external_provider_gateway', 'gpu_cloud_run_job_l4'],
    blockedUses: mockBlockedUses,
    qaReadiness: 'mock_safe',
    trackAHandoffStatus: 'handoff_required',
    trackBHandoffStatus: 'handoff_required',
    trackAFinalRenderReady: false,
    providerExecutionReady: false,
    workerExecutionReady: false,
    generatedAssetIds: [],
  }
}

function createMockToolRequests(cueIds: string[]): SoundToolRequest[] {
  return [
    {
      toolRequestId: 'mock-sound-chat-soundsync-request',
      toolId: 'soundsync_planner',
      workspaceId,
      projectId,
      editPlanId,
      cueIds,
      executionMode: 'planning_only',
      runtimeTarget: 'cpu_service',
      approvalState: 'not_required',
      creditGateState: 'not_required',
      metadata: {
        source: 'frontend_mock_fixture',
        rawChatAsWorkerPlan: false,
        metadataOnly: true,
      },
    },
    {
      toolRequestId: 'mock-sound-chat-private-manifest-request',
      toolId: 'private_audio_artifact_manifest_builder',
      workspaceId,
      projectId,
      editPlanId,
      cueIds,
      executionMode: 'planning_only',
      runtimeTarget: 'cpu_service',
      approvalState: 'not_required',
      creditGateState: 'not_required',
      metadata: {
        storageScope: 'private',
        publicArtifactAllowed: false,
        metadataOnly: true,
      },
    },
    {
      toolRequestId: 'mock-sound-chat-timing-manifest-request',
      toolId: 'timing_aware_cue_manifest_builder',
      workspaceId,
      projectId,
      editPlanId,
      cueIds,
      executionMode: 'planning_only',
      runtimeTarget: 'cpu_service',
      approvalState: 'not_required',
      creditGateState: 'not_required',
      metadata: {
        soundSyncCoordinationOnly: true,
        metadataOnly: true,
      },
    },
  ]
}

function createMockExecutionGateResults(): SoundExecutionGateResult[] {
  return mockSoundRuntimePolicies.map((runtime) => ({
    allowed: runtime.executionMode === 'mock_preview_only',
    allowedMode: runtime.executionMode === 'mock_preview_only' ? 'mock' : 'blocked',
    blockedReasons: runtime.blockedReasons,
    requiredHandoffs: runtime.requiredHandoffs,
    requiredEvidence: runtime.requiredEvidence,
    mayCreateGeneratedAsset: false,
    mayDispatchWorker: false,
    mayCallProvider: false,
  }))
}

function createMockHandoffMetadata(): SoundMusicAudioPlanCardProps['handoffMetadata'] {
  return {
    AI_TOOLS_CREATIVE_GRAPHICS: {
      affected: false,
      duplicateRisk: 'none',
      notes: ['No graphic design, image, or visual asset tool behavior is changed.'],
    },
    TRACK_A_RENDER_EXPORT: {
      handoffRequired: true,
      finalRenderReady: false,
      finalMuxReady: false,
      notes: ['Track A final composition remains not ready.'],
    },
    TRACK_B_MEDIA_PROCESSING: {
      handoffRequired: true,
      processingExecutionReady: false,
      notes: ['Track B handoff is metadata-only until real audio/media processing is approved.'],
    },
    PROVIDER_GATEWAY_MODELS: {
      handoffRequired: true,
      mayCallProvider: false,
      realTransportReady: false,
      notes: ['Provider Gateway is required before real Lyria, SFX, or fallback transport.'],
    },
    WORKER_RUNTIME_JOBS: {
      handoffRequired: true,
      mayDispatchWorker: false,
      executionReady: false,
      notes: ['Worker runtime is blocked in this chat renderer path.'],
    },
    SUPABASE_RLS_STORAGE_DATABASE: {
      handoffRequired: true,
      mutationAllowed: false,
      storageWriteAllowed: false,
      publicArtifactAllowed: false,
      notes: ['No Supabase mutation or storage upload happens from this UI.'],
    },
    OBSERVABILITY_AUDIT_COST: {
      handoffRequired: true,
      betaEvidenceReady: false,
      costEvidenceReady: false,
      notes: ['Audit and cost evidence are future handoffs.'],
    },
    BILLING_STRIPE_CREDITS: {
      handoffRequired: true,
      creditRowsCreated: false,
      approvalRowsCreated: false,
      reservationRowsCreated: false,
      notes: ['No billing, Stripe, credit estimate, approval, reservation, spend, or refund behavior is created.'],
    },
  }
}

export function createMockSoundMusicAudioChatCardProps(
  options: MockSoundMusicAudioChatCardOptions = {},
): SoundMusicAudioPlanCardProps {
  const removedCueIds = new Set(options.removedCueIds ?? [])
  const cuePlans = mockSoundCuePlans.filter((cue) => !removedCueIds.has(cue.cueId))
  const cueIds = cuePlans.map((cue) => cue.cueId)
  const handoffReadiness = createMockSoundHandoffReadiness(cueIds)
  const plan: SoundAgentPlan = {
    planId: 'mock-sound-chat-plan',
    workstreamId: 'SOUND_MUSIC_AUDIO',
    workspaceId,
    projectId,
    editPlanId,
    cuePlans,
    providerPolicies: mockSoundProviderPolicies,
    runtimePolicies: mockSoundRuntimePolicies,
    blockedUses: mockBlockedUses,
    readiness: handoffReadiness,
    warnings: [
      'Mock chat renderer preview only: real generation remains blocked.',
      'No provider calls, worker dispatch, generated assets, storage writes, public artifacts, signed access, or Supabase mutations are allowed.',
      ...(options.approvedPreview ? ['Preview approval is local chat UI state only and creates no approval record.'] : []),
    ],
  }
  const timingManifest = createMockTimingManifest(cuePlans)
  const privateArtifactManifest = createMockPrivateArtifactManifest(cueIds)
  const cueGroups = buildSoundMusicAudioCueGroups(plan)
  const providerSummaries = buildSoundMusicAudioProviderSummaries(plan)
  const runtimeSummaries = buildSoundMusicAudioRuntimeSummaries(plan)
  const toolRequests = createMockToolRequests(cueIds)
  const executionGateResults = createMockExecutionGateResults()
  const handoffMetadata = createMockHandoffMetadata()
  const qaNotes = buildSoundMusicAudioQaNotes({
    plan,
    qaWarnings: [
      'Speech safety: music and ambience stay below dialogue until real audio QA exists.',
      'No-random-SFX policy: each cue must support an edit event, visual motion, ambience need, or soundtrack purpose.',
    ],
  })
  const soundSyncNotes = buildSoundMusicAudioSoundSyncNotes({
    timingManifest,
    toolRequests,
  })
  const accessSafety = buildSoundMusicAudioAccessSafety(privateArtifactManifest)
  const summary = buildSoundMusicAudioPlanSummary({
    plan,
    cueGroups,
    privateArtifactManifest,
  })
  const evidenceReview = buildSoundMusicAudioHandoffEvidenceReview({
    plan,
    timingManifest,
    privateArtifactManifest,
    handoffReadiness,
    summary,
    providerSummaries,
    runtimeSummaries,
    executionGateResults,
    handoffMetadata,
    qaNotes,
    accessSafety,
  })

  return {
    plan,
    timingManifest,
    privateArtifactManifest,
    handoffReadiness,
    toolRequests,
    executionGateResults,
    handoffMetadata,
    mode: 'mock_preview_only',
    cueGroups,
    summary,
    providerSummaries,
    runtimeSummaries,
    lyriaPlanning: buildSoundMusicAudioLyriaPlanningMetadata({ cueGroups, providerSummaries }),
    handoffItems: buildSoundMusicAudioHandoffItems(handoffReadiness),
    qaNotes,
    soundSyncNotes,
    accessSafety,
    evidenceReview,
  }
}
