import type { MapGeospatialToolEvidence } from './map-geospatial-approval-types'

export function buildMapGeospatialToolEvidence(): MapGeospatialToolEvidence[] {
  return [
    {
      toolId: 'maplibre-gl-js',
      displayName: 'MapLibre GL JS',
      role: 'Default browser map renderer for interactive planning maps, styles, layers, camera/view state, and future controlled map screenshots.',
      category: 'browser_map_renderer',
      defaultStack: true,
      futureScoped: false,
      requiresApiKeyByDefault: false,
      paidProviderDependencyByDefault: false,
      runtimeAllowedInPhase50A: false,
      sourceUrls: ['https://github.com/maplibre/maplibre-gl-js', 'https://maplibre.org/maplibre-gl-js/docs/', 'https://maplibre.org/projects/gl-js/'],
      license: 'BSD-3-Clause',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['interactive planning maps', 'map styles and layers', 'vector-tile display planning', 'camera/view state planning', 'future controlled screenshot planning'],
      runtimeNotes: ['Frontend renderer only in future approved phases.', 'No secret map keys by default.', 'Use open, generated, or self-hosted tiles when possible.'],
      limitations: ['Runtime rendering is blocked in Phase 50A.', 'Paid tiles and arbitrary tile endpoints remain blocked.'],
    },
    {
      toolId: 'turf-js',
      displayName: 'Turf.js',
      role: 'GeoJSON and geospatial calculation helper for distance, bounds, buffers, areas, predicates, and transforms.',
      category: 'geospatial_calculation',
      defaultStack: true,
      futureScoped: false,
      requiresApiKeyByDefault: false,
      paidProviderDependencyByDefault: false,
      runtimeAllowedInPhase50A: false,
      sourceUrls: ['https://github.com/Turfjs/turf', 'https://turfjs.org/'],
      license: 'MIT',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['distance planning', 'bbox planning', 'buffer/radius planning', 'area planning', 'polygon predicates', 'GeoJSON transforms'],
      runtimeNotes: ['Pure calculations can run server-side or frontend-side in later phases depending on sensitivity.', 'No network is required for pure calculation fixtures.'],
      limitations: ['Not a renderer.', 'No Phase 50A runtime execution.'],
    },
    {
      toolId: 'deck-gl',
      displayName: 'deck.gl',
      role: 'Advanced WebGL overlay and high-volume geospatial visualization candidate.',
      category: 'advanced_overlay_visualization',
      defaultStack: true,
      futureScoped: false,
      requiresApiKeyByDefault: false,
      paidProviderDependencyByDefault: false,
      runtimeAllowedInPhase50A: false,
      sourceUrls: ['https://github.com/visgl/deck.gl', 'https://deck.gl/'],
      license: 'MIT',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['point layers', 'arc/flow layers', 'path overlays', 'heatmaps', 'animated routes', 'high-volume geospatial visual layers'],
      runtimeNotes: ['Use only when MapLibre layers are insufficient.', 'Frontend-only unless a later server-side capture phase approves it.'],
      limitations: ['WebGL/browser compatibility and performance need fixture QA.', 'No Phase 50A runtime execution.'],
    },
    {
      toolId: 'cesium-js',
      displayName: 'CesiumJS',
      role: 'Optional OSS 3D globe, terrain, 3D Tiles, and cinematic geospatial camera path planning candidate.',
      category: 'three_d_geospatial',
      defaultStack: true,
      futureScoped: false,
      requiresApiKeyByDefault: false,
      paidProviderDependencyByDefault: false,
      runtimeAllowedInPhase50A: false,
      sourceUrls: ['https://github.com/CesiumGS/cesium', 'https://cesium.com/platform/cesiumjs/'],
      license: 'Apache-2.0',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['3D globe planning', 'terrain planning', '3D Tiles planning', 'camera path planning', 'premium location preview planning'],
      runtimeNotes: ['OSS CesiumJS planning is allowed.', 'Cesium ion paid assets/services remain blocked until separate approval.'],
      limitations: ['Memory/performance and 3D asset provenance require future fixture QA.', 'No Cesium ion dependency in Phase 50A.'],
    },
    {
      toolId: 'openstreetmap-open-data',
      displayName: 'OpenStreetMap / open map data',
      role: 'Preferred open map-data source for future map planning, attribution, and open-data policy.',
      category: 'open_map_data',
      defaultStack: true,
      futureScoped: false,
      requiresApiKeyByDefault: false,
      paidProviderDependencyByDefault: false,
      runtimeAllowedInPhase50A: false,
      sourceUrls: ['https://www.openstreetmap.org/copyright', 'https://operations.osmfoundation.org/policies/tiles/'],
      license: 'ODbL-1.0 for OSM data; tile service policies vary',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['open map-data policy', 'attribution planning', 'future self-host/open tile strategy planning'],
      runtimeNotes: ['Attribution is required.', 'Self-hosted/open tile strategy is preferred for beta/production.'],
      limitations: ['Public OSM tile hotlinking for beta/production is blocked.', 'Tile usage policy must be reviewed before any live tile dependency.'],
    },
    futureTool('pmtiles', 'PMTiles', 'future_tile_infrastructure', 'Static archive format candidate for private/generated map fixtures and future tile distribution.', ['https://github.com/protomaps/PMTiles']),
    futureTool('tileserver-gl', 'TileServer GL', 'future_tile_infrastructure', 'Future self-hosted vector/raster tile service candidate.', ['https://github.com/maptiler/tileserver-gl', 'https://tileserver.org/']),
    futureTool('martin', 'Martin', 'future_tile_infrastructure', 'Future self-hosted tile server candidate for PostGIS/MBTiles/PMTiles workflows.', ['https://github.com/maplibre/martin']),
    futureTool('nominatim', 'Nominatim', 'future_geocoding', 'Future self-hosted/private geocoding candidate; public heavy use remains blocked.', ['https://nominatim.org/', 'https://github.com/osm-search/Nominatim']),
    futureTool('photon', 'Photon', 'future_geocoding', 'Future self-hosted/private geocoding candidate.', ['https://github.com/komoot/photon']),
    futureTool('pelias', 'Pelias', 'future_geocoding', 'Future self-hosted/private geocoding candidate.', ['https://github.com/pelias/pelias']),
    futureTool('osrm', 'OSRM', 'future_routing', 'Future self-hosted/private routing candidate.', ['https://github.com/Project-OSRM/osrm-backend']),
    futureTool('valhalla', 'Valhalla', 'future_routing', 'Future self-hosted/private routing candidate.', ['https://github.com/valhalla/valhalla']),
  ]
}

function futureTool(
  toolId: MapGeospatialToolEvidence['toolId'],
  displayName: string,
  category: MapGeospatialToolEvidence['category'],
  role: string,
  sourceUrls: string[],
): MapGeospatialToolEvidence {
  return {
    toolId,
    displayName,
    role,
    category,
    defaultStack: false,
    futureScoped: true,
    requiresApiKeyByDefault: false,
    paidProviderDependencyByDefault: false,
    runtimeAllowedInPhase50A: false,
    sourceUrls,
    license: 'future_review_required',
    licenseStatus: 'future_scope_pending_evidence',
    approvedPlanningUses: ['future architecture planning only'],
    runtimeNotes: ['Requires a later evidence, fixture, and runtime approval phase.'],
    limitations: ['Not installed or executed in Phase 50A.', 'No public service dependency is approved.'],
  }
}
