import type { WebSearchToolEvidence } from './web-search-capture-approval-types'

export function buildWebSearchToolEvidence(): WebSearchToolEvidence[] {
  return [
    {
      toolId: 'searxng',
      displayName: 'SearXNG',
      role: 'Default self-hosted metasearch provider for source and citation candidate discovery.',
      category: 'free_open_source_search_infrastructure',
      defaultStack: true,
      optionalPaidProvider: false,
      disabledByDefault: false,
      requiresSecret: false,
      notOpenSourceDefault: false,
      notRequiredForInitialInternalTesting: false,
      providerAllowed: false,
      futureApprovalRequired: true,
      sourceUrls: ['https://github.com/searxng/searxng', 'https://docs.searxng.org/'],
      license: 'AGPL-3.0-or-later',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['query discovery', 'source discovery', 'planning research search', 'citation candidate discovery'],
      runtimeNotes: ['Prefer a private ReeditPro-controlled instance.', 'Public SearXNG instances are not source of truth.'],
      limitations: ['Upstream engine reliability varies.', 'Rate limits and CAPTCHA risk must be handled without bypass.', 'AGPL obligations require production legal review before hosted runtime exposure.'],
    },
    {
      toolId: 'playwright',
      displayName: 'Playwright',
      role: 'Browser capture, dynamic page render, screenshot validation, and rendered-page metadata collection.',
      category: 'browser_automation_capture',
      defaultStack: true,
      optionalPaidProvider: false,
      disabledByDefault: false,
      requiresSecret: false,
      notOpenSourceDefault: false,
      notRequiredForInitialInternalTesting: false,
      providerAllowed: false,
      futureApprovalRequired: true,
      sourceUrls: ['https://github.com/microsoft/playwright', 'https://playwright.dev/'],
      license: 'Apache-2.0',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['page screenshot capture planning', 'rendered page validation planning', 'title and DOM metadata planning'],
      runtimeNotes: ['Server/worker-side only.', 'Future phases must start with local or generated fixtures before public web access.'],
      limitations: ['No login bypass.', 'No CAPTCHA bypass.', 'No paywall bypass.', 'No robots or terms bypass.', 'No public internet capture in Phase 49A.'],
    },
    {
      toolId: 'sharp',
      displayName: 'Sharp',
      role: 'Screenshot and image post-processing for resizing, thumbnails, contact sheets, metadata, and format conversion.',
      category: 'image_processing',
      defaultStack: true,
      optionalPaidProvider: false,
      disabledByDefault: false,
      requiresSecret: false,
      notOpenSourceDefault: false,
      notRequiredForInitialInternalTesting: false,
      providerAllowed: false,
      futureApprovalRequired: true,
      sourceUrls: ['https://github.com/lovell/sharp', 'https://sharp.pixelplumbing.com/'],
      license: 'Apache-2.0',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['resize planning', 'crop planning', 'thumbnail planning', 'contact sheet planning', 'metadata planning', 'format conversion planning'],
      runtimeNotes: ['Worker-side screenshot/image processing only after fixture/runtime phases.'],
      limitations: ['No untrusted upload processing without future worker safety limits.', 'No Phase 49A screenshot processing runtime.'],
    },
    {
      toolId: 'mozilla-readability',
      displayName: 'Mozilla Readability',
      role: 'Article/content extraction after safe fetch or render.',
      category: 'html_article_extraction',
      defaultStack: true,
      optionalPaidProvider: false,
      disabledByDefault: false,
      requiresSecret: false,
      notOpenSourceDefault: false,
      notRequiredForInitialInternalTesting: false,
      providerAllowed: false,
      futureApprovalRequired: true,
      sourceUrls: ['https://github.com/mozilla/readability'],
      license: 'Apache-2.0',
      licenseStatus: 'clear_for_planning',
      approvedPlanningUses: ['title extraction planning', 'content text extraction planning', 'byline/excerpt/published-time metadata planning'],
      runtimeNotes: ['Extraction must follow safe fetch/render policy and sanitize output before display/storage.'],
      limitations: ['Avoid storing full copyrighted content unless policy allows.', 'No script execution from extracted HTML.', 'No Phase 49A extraction runtime.'],
    },
    optionalPaidProvider('brave-search-api', 'Brave Search API', ['https://brave.com/search/api/']),
    optionalPaidProvider('tavily', 'Tavily', ['https://www.tavily.com/']),
    optionalPaidProvider('exa', 'Exa', ['https://exa.ai/']),
    optionalPaidProvider('firecrawl', 'Firecrawl', ['https://www.firecrawl.dev/']),
    optionalPaidProvider('browserless-browserbase', 'Browserless / Browserbase', ['https://www.browserless.io/', 'https://www.browserbase.com/']),
  ]
}

function optionalPaidProvider(toolId: WebSearchToolEvidence['toolId'], displayName: string, sourceUrls: string[]): WebSearchToolEvidence {
  return {
    toolId,
    displayName,
    role: 'Optional paid provider candidate; disabled and not required for initial internal testing.',
    category: 'optional_paid_provider',
    defaultStack: false,
    optionalPaidProvider: true,
    disabledByDefault: true,
    requiresSecret: true,
    notOpenSourceDefault: true,
    notRequiredForInitialInternalTesting: true,
    providerAllowed: false,
    futureApprovalRequired: true,
    sourceUrls,
    license: 'provider_terms_review_required',
    licenseStatus: 'review_required_before_runtime',
    approvedPlanningUses: ['future comparison only'],
    runtimeNotes: ['Not required for the free/open-source default stack.', 'Requires a separate provider approval phase, secret policy, cost controls, and legal review.'],
    limitations: ['Disabled by default.', 'No API key is added.', 'No Phase 49A provider calls.'],
  }
}
