export function buildDeckGlLocalOverlayCommandPlan() {
  return {
    phase: '50D',
    defaultMode: 'static_report_only',
    executeCommand: 'GCP_PROJECT_ID=reeditpro GCP_REGION=us-central1 REEDITPRO_ENV=staging REEDITPRO_CONFIRM_DECKGL_LOCAL_OVERLAY_FIXTURE=true npm run activation:deckgl-local-overlay-fixture -- --execute',
    allowedWhenConfirmed: [
      'generate synthetic Phase 50B-style GeoJSON',
      'generate deterministic deck.gl overlay records',
      'build a local/offline MapLibre style JSON',
      'copy local MapLibre and deck.gl bundles into a temporary fixture directory',
      'serve a temporary 127.0.0.1 local fixture',
      'launch Playwright Chromium only against the local fixture',
      'render deck.gl ScatterplotLayer, PathLayer, PolygonLayer, and ArcLayer through MapboxOverlay',
      'capture a 1280x720 local/offline screenshot',
      'run Sharp only on the Phase 50D screenshot',
      'upload private Phase 50D artifacts',
    ],
    blockedAlways: [
      'live tiles',
      'public OSM tiles',
      'remote glyphs/sprites/images',
      'Mapbox provider',
      'Google Maps',
      'Cesium ion',
      'geocoding APIs',
      'routing APIs',
      'paid map providers',
      'CesiumJS runtime',
      'D3 runtime',
      'Three.js runtime',
      'PMTiles',
      'tile servers',
      'public artifacts',
      'signed URLs as source of truth',
      'production',
      'external beta',
      'paid production',
      'broad media',
    ],
  }
}
