export type SupabaseCleanStagingBranchExecutionBlocker =
  | 'pr280_clean_staging_approval_missing'
  | 'clean_staging_branch_execute_not_confirmed'
  | 'clean_staging_branch_create_not_confirmed'
  | 'persistent_branch_create_not_confirmed'
  | 'branching_cost_acceptance_not_confirmed'
  | 'clean_staging_no_production_data_not_confirmed'
  | 'clean_staging_migration_apply_not_confirmed'
  | 'clean_staging_schema_verify_not_confirmed'
  | 'temp_cli_exec_not_confirmed'
  | 'access_token_secret_injection_not_confirmed'
  | 'preinjected_access_token_not_confirmed'
  | 'forbidden_confirmation_set'
  | 'secret_manager_metadata_discovery_unavailable'
  | 'supabase_access_token_secret_reference_missing'
  | 'supabase_access_token_secret_payload_access_denied'
  | 'supabase_access_token_secret_payload_invalid'
  | 'supabase_access_token_unavailable'
  | 'temp_npm_supabase_cli_unavailable'
  | 'clean_staging_branch_list_failed'
  | 'clean_staging_branch_metadata_unsafe'
  | 'branch_region_or_size_required'
  | 'clean_staging_branch_create_failed'
  | 'clean_staging_branch_health_unavailable'
  | 'clean_branch_migration_apply_transport_unavailable'
  | 'clean_branch_migration_dry_run_failed'
  | 'clean_branch_migration_apply_failed'
  | 'clean_branch_migration_history_verify_failed'
  | 'clean_branch_schema_rls_verify_unavailable'
  | 'clean_branch_schema_rls_verify_failed'
  | 'trackb_backfill_preflight_blocked'
  | 'sensitive_payload_pattern_detected'

export type SupabaseCleanStagingBranchExecutionStatus =
  | 'passed'
  | 'blocked'
  | 'skipped'
  | 'planned'

export type SupabaseCleanStagingBranchAction =
  | 'created'
  | 'reused'
  | 'not_run'
  | 'blocked'
