import type { MultiAgentDryRunScenario } from './multi-agent-dry-run-types'

export const multiAgentDryRunScenarios: MultiAgentDryRunScenario[] = [
  {
    scenarioId: 'visual_video_private_review_improvement',
    title: 'Private visual/video review improvement',
    requestedOutcome: 'Review an internal private edit plan and propose candidate-only visual improvements without media processing.',
    evidenceRefs: ['52A:agent_role_registry', '52B:track_a_visual_video_capabilities'],
    participatingAgents: ['director', 'editor', 'cinematographer', 'colorist', 'compositor_vfx', 'motion', 'producer', 'qa_safety'],
    requestedIntentTypes: ['conservative_color_adjustment', 'caption_burnin_preview', 'text_behind_subject_preview', 'slow_motion_segment'],
    constraints: ['no media processing', 'no worker execution', 'approved snapshot required before any later runtime'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
  {
    scenarioId: 'research_backed_video_planning',
    title: 'Research-backed video planning',
    requestedOutcome: 'Use existing web-search readiness evidence to propose a planning context candidate without live search.',
    evidenceRefs: ['52A:search_research_agent', '52B:web_search_capabilities', '49P:web_search_internal_beta_candidate'],
    participatingAgents: ['director', 'search_research', 'producer', 'qa_safety'],
    requestedIntentTypes: ['web_research_planning_context'],
    constraints: ['no live search', 'no provider call', 'source manifests remain source of truth'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
  {
    scenarioId: 'map_location_context_card',
    title: 'Map/location context card',
    requestedOutcome: 'Create a generated/local location card plan from existing map/geospatial evidence.',
    evidenceRefs: ['52A:map_location_agent', '52B:map_geospatial_capabilities', '50G:map_geospatial_internal_readiness'],
    participatingAgents: ['director', 'map_location', 'graphics_design', 'producer', 'qa_safety'],
    requestedIntentTypes: ['route_map_overlay', 'location_context_card'],
    constraints: ['no live geocoding', 'no routing API', 'no live tiles', 'screenshots are QA artifacts only'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
  {
    scenarioId: 'motion_graphics_lower_third_request',
    title: 'Motion graphics lower-third request',
    requestedOutcome: 'Route a lower-third design request through ownership gates without executing AI Tools.',
    evidenceRefs: ['52A:tool_ownership_map', '52B:ai_tools_placeholders'],
    participatingAgents: ['director', 'graphics_design', 'motion', 'producer', 'qa_safety'],
    requestedIntentTypes: ['motion_graphics_lower_third'],
    constraints: ['AI Tools owns creative graphics runtime', 'no direct tool execution by this chat'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
  {
    scenarioId: 'audio_noise_cleanup_and_voice_request',
    title: 'Audio noise cleanup and voice request',
    requestedOutcome: 'Evaluate audio cleanup and stem separation candidates against Track B readiness constraints.',
    evidenceRefs: ['52A:audio_agent', '52B:track_b_capabilities'],
    participatingAgents: ['director', 'audio', 'producer', 'qa_safety'],
    requestedIntentTypes: ['noise_cleanup', 'demucs_stem_separation_request'],
    constraints: ['no audio processing', 'Track B owns audio runtime', 'model provenance blockers remain binding'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
  {
    scenarioId: 'vlm_video_understanding_request',
    title: 'VLM video understanding request',
    requestedOutcome: 'Route a visual-understanding request and prove the VLM exclusion blocks candidate execution.',
    evidenceRefs: ['52A:cinematographer_agent', '52B:track_b_vlm_records', '39C:vlm_exclusion'],
    participatingAgents: ['director', 'cinematographer', 'editor', 'producer', 'qa_safety'],
    requestedIntentTypes: ['qwen_vlm_visual_understanding_request'],
    constraints: ['VLM excluded for initial internal testing', 'no model inference', 'no runtime fallback'],
    runtimeExecutionAllowed: false,
    candidatePlanOnly: true,
  },
]
