import { MODEL_APPROVAL_REVIEWED_AT } from './model-candidate-registry'
import type { ModelLicenseEvidence } from './model-approval-types'

export const modelLicenseEvidenceRegistry: ModelLicenseEvidence[] = [
  {
    evidenceId: 'systran_faster_whisper_tiny_hf_model_card',
    modelCandidateId: 'systran_faster_whisper_tiny',
    sourceName: 'Hugging Face model card: Systran/faster-whisper-tiny',
    sourceUrl: 'https://huggingface.co/Systran/faster-whisper-tiny',
    sourceType: 'huggingface',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Preserve MIT license notice and model source attribution in review records.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'high',
    notes: [
      'Direct model page lists License: mit.',
      'Model card states this is a conversion of openai/whisper-tiny to CTranslate2 format.',
      'This evidence supports staging speech/caption only, not production approval.',
    ],
  },
  {
    evidenceId: 'systran_faster_whisper_tiny_revision_tree',
    modelCandidateId: 'systran_faster_whisper_tiny',
    sourceName: 'Hugging Face file tree revision: Systran/faster-whisper-tiny',
    sourceUrl: 'https://huggingface.co/Systran/faster-whisper-tiny/tree/d90ca5fe260221311c53c58e660288d3deb8d356',
    sourceType: 'huggingface',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Record revision before any future download and preserve license notices.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'medium',
    notes: [
      'Revision evidence records model tree identity for future checksum/download review.',
      'Checksums remain missing until an explicit download/load phase.',
    ],
  },
  {
    evidenceId: 'systran_faster_whisper_tiny_en_hf_model_card',
    modelCandidateId: 'systran_faster_whisper_tiny_en',
    sourceName: 'Hugging Face model card: Systran/faster-whisper-tiny.en',
    sourceUrl: 'https://huggingface.co/Systran/faster-whisper-tiny.en',
    sourceType: 'huggingface',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Preserve MIT license notice and model source attribution if later approved.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'medium',
    notes: ['Candidate only; not approved by Phase 26.'],
  },
  {
    evidenceId: 'openai_whisper_github_mit',
    modelCandidateId: 'openai_whisper_tiny_upstream',
    sourceName: 'OpenAI Whisper GitHub repository',
    sourceUrl: 'https://github.com/openai/whisper',
    sourceType: 'github',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Preserve MIT license notice.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'high',
    notes: ['OpenAI repository states Whisper code and model weights are released under the MIT License.'],
  },
  {
    evidenceId: 'openai_whisper_tiny_hf_apache_discrepancy',
    modelCandidateId: 'openai_whisper_tiny_upstream',
    sourceName: 'Hugging Face model card: openai/whisper-tiny',
    sourceUrl: 'https://huggingface.co/openai/whisper-tiny',
    sourceType: 'huggingface',
    licenseClaim: 'apache-2.0',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Record Apache-2.0 metadata discrepancy and preserve notices if upstream artifact is ever used directly.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'medium',
    notes: [
      'Hugging Face metadata for openai/whisper-tiny lists apache-2.0.',
      'This conflicts with OpenAI GitHub MIT evidence and is recorded for manual review traceability.',
      'OpenAI upstream artifact is not the direct Phase 28 execution artifact.',
    ],
  },
  {
    evidenceId: 'faster_whisper_pypi_runtime',
    modelCandidateId: 'systran_faster_whisper_tiny',
    sourceName: 'PyPI package: faster-whisper',
    sourceUrl: 'https://pypi.org/project/faster-whisper/',
    sourceType: 'package_registry',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Preserve MIT package license notice.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'high',
    notes: [
      'Runtime/package evidence only; package license does not approve model weights by itself.',
      'PyPI describes faster-whisper as a reimplementation of OpenAI Whisper using CTranslate2.',
    ],
  },
  {
    evidenceId: 'ctranslate2_pypi_runtime',
    modelCandidateId: 'systran_faster_whisper_tiny',
    sourceName: 'PyPI package: ctranslate2',
    sourceUrl: 'https://pypi.org/project/ctranslate2/',
    sourceType: 'package_registry',
    licenseClaim: 'mit',
    commercialUseClaim: 'likely_allowed',
    redistributionClaim: 'likely_allowed',
    attributionRequirements: ['Preserve MIT package license notice.'],
    fetchedAt: MODEL_APPROVAL_REVIEWED_AT,
    reviewedAt: MODEL_APPROVAL_REVIEWED_AT,
    confidence: 'high',
    notes: ['Runtime/package evidence only; model checkpoint approval is separately recorded.'],
  },
]

export function listModelLicenseEvidence(): ModelLicenseEvidence[] {
  return [...modelLicenseEvidenceRegistry]
}

export function evidenceForCandidate(candidateId: string): ModelLicenseEvidence[] {
  return modelLicenseEvidenceRegistry.filter((evidence) => evidence.modelCandidateId === candidateId)
}
