import type {
  ProjectEditBriefPlanInstructionKind,
  ProjectEditBriefPlanReadinessStatus,
  ProjectEditBriefPlanScenario,
} from '../../types/project-edit-brief-plan'
import { PROJECT_EDIT_BRIEF_PLAN_SAFETY_FLAGS } from '../../lib/project-edit-brief-plan-rules'

type ScenarioSeed = [
  string,
  ProjectEditBriefPlanReadinessStatus,
  ProjectEditBriefPlanInstructionKind | undefined,
  boolean,
]

const seeds: ScenarioSeed[] = [
  ['Priority policy exists', 'ready_for_mock_plan_hints', undefined, true],
  ['Confirmed QA-passed B-roll marker is eligible', 'ready_for_mock_plan_hints', 'broll_insert', true],
  ['Confirmed QA-passed caption marker is eligible', 'ready_for_mock_plan_hints', 'caption_or_text', true],
  ['Confirmed QA-passed cut marker is eligible', 'ready_for_mock_plan_hints', 'cut_or_remove', true],
  ['Confirmed QA-passed music marker is eligible as metadata-only hint', 'ready_with_warnings_mock', 'music_or_soundtrack_hint', true],
  ['Confirmed QA-passed SFX marker is eligible as metadata-only hint', 'ready_with_warnings_mock', 'sfx_hint', true],
  ['Confirmed QA-passed do-not-use marker becomes restriction', 'ready_for_mock_plan_hints', 'restriction', true],
  ['Draft marker skipped not confirmed', 'needs_user_review', undefined, true],
  ['Missing intent marker skipped', 'needs_user_review', undefined, true],
  ['Needs asset marker skipped', 'blocked_by_missing_asset', undefined, true],
  ['Needs clarification marker skipped', 'needs_user_review', undefined, true],
  ['Conflict marker skipped', 'blocked_by_qa', undefined, true],
  ['Copy-risk marker skipped', 'blocked_by_copy_risk', undefined, true],
  ['Invalid time range marker skipped', 'blocked_by_qa', undefined, true],
  ['Warning marker included with warning', 'ready_with_warnings_mock', 'general_note', true],
  ['add_broll maps to broll_insert', 'ready_for_mock_plan_hints', 'broll_insert', true],
  ['remove_or_cut maps to cut_or_remove', 'ready_for_mock_plan_hints', 'cut_or_remove', true],
  ['keep_or_emphasize maps to keep_or_emphasize', 'ready_for_mock_plan_hints', 'keep_or_emphasize', true],
  ['add_caption_or_text maps to caption_or_text', 'ready_for_mock_plan_hints', 'caption_or_text', true],
  ['add_graphic_or_ui_card maps to graphic_or_card', 'ready_for_mock_plan_hints', 'graphic_or_card', true],
  ['add_music_or_soundtrack maps to music_or_soundtrack_hint', 'ready_with_warnings_mock', 'music_or_soundtrack_hint', true],
  ['add_sfx maps to sfx_hint', 'ready_with_warnings_mock', 'sfx_hint', true],
  ['add_voiceover maps to voiceover_hint', 'ready_with_warnings_mock', 'voiceover_hint', true],
  ['add_transition maps to transition_hint', 'ready_for_mock_plan_hints', 'transition_hint', true],
  ['adjust_speed_or_pacing maps to pacing_adjustment', 'ready_for_mock_plan_hints', 'pacing_adjustment', true],
  ['adjust_color_or_tone maps to color_tone_adjustment', 'ready_for_mock_plan_hints', 'color_tone_adjustment', true],
  ['avoid_or_do_not_use maps to restriction', 'ready_for_mock_plan_hints', 'restriction', true],
  ['general_instruction maps to general_note', 'ready_for_mock_plan_hints', 'general_note', true],
  ['Plan instruction preserves time range', 'ready_for_mock_plan_hints', 'general_note', true],
  ['Plan instruction preserves provided assets', 'ready_for_mock_plan_hints', 'broll_insert', true],
  ['Plan instruction preserves do-not-copy notes', 'ready_for_mock_plan_hints', 'restriction', true],
  ['Plan instruction preserves warnings', 'ready_with_warnings_mock', 'general_note', true],
  ['Plan instruction includes QA status', 'ready_for_mock_plan_hints', 'general_note', true],
  ['Planner package includes export settings', 'ready_for_mock_plan_hints', undefined, true],
  ['Planner package includes eligible markers', 'ready_for_mock_plan_hints', undefined, true],
  ['Planner package includes skipped markers', 'ready_with_warnings_mock', undefined, true],
  ['Planner package includes QA summary', 'ready_for_mock_plan_hints', undefined, true],
  ['Planner package includes priority policy', 'ready_for_mock_plan_hints', undefined, true],
  ['Planner package says plannerExecuted false', 'ready_for_mock_plan_hints', undefined, true],
  ['Planner package says editPlanCreated false', 'ready_for_mock_plan_hints', undefined, true],
  ['Application result includes package', 'ready_for_mock_plan_hints', undefined, true],
  ['Application result includes application log payload', 'ready_for_mock_plan_hints', undefined, true],
  ['Application log summary readable', 'ready_for_mock_plan_hints', undefined, true],
  ['Plan panel model created', 'ready_for_mock_plan_hints', undefined, true],
  ['Plan panel model includes readiness', 'ready_for_mock_plan_hints', undefined, true],
  ['Plan panel model includes instructions', 'ready_for_mock_plan_hints', undefined, true],
  ['Plan panel model includes skipped markers', 'ready_with_warnings_mock', undefined, true],
  ['Readiness ready_for_mock_plan_hints works', 'ready_for_mock_plan_hints', undefined, true],
  ['Readiness ready_with_warnings_mock works', 'ready_with_warnings_mock', undefined, true],
  ['Readiness needs_user_review works', 'needs_user_review', undefined, true],
  ['Readiness blocked_by_qa works', 'blocked_by_qa', undefined, true],
  ['Readiness blocked_by_missing_asset works', 'blocked_by_missing_asset', undefined, true],
  ['Readiness blocked_by_copy_risk works', 'blocked_by_copy_risk', undefined, true],
  ['Instruction summary readable', 'ready_for_mock_plan_hints', 'general_note', true],
  ['Skipped marker summary readable', 'needs_user_review', undefined, true],
  ['Debug summary readable', 'ready_for_mock_plan_hints', undefined, true],
  ['Validation passes valid instruction', 'ready_for_mock_plan_hints', 'general_note', true],
  ['Validation passes valid package', 'ready_for_mock_plan_hints', undefined, true],
  ['Validation passes application result', 'ready_for_mock_plan_hints', undefined, true],
  ['Validation blocks plannerExecuted true', 'failed_validation', undefined, false],
  ['Validation blocks editPlanCreated true', 'failed_validation', undefined, false],
  ['Validation blocks provider flag', 'failed_validation', undefined, false],
  ['Validation blocks media processing flag', 'failed_validation', undefined, false],
  ['Validation blocks worker flag', 'failed_validation', undefined, false],
  ['Validation blocks generation request flag', 'failed_validation', undefined, false],
  ['Validation blocks render flag', 'failed_validation', undefined, false],
  ['Validation blocks credit flag', 'failed_validation', undefined, false],
  ['UI adapter loads panel', 'ready_for_mock_plan_hints', undefined, true],
  ['UI adapter prepares plan hints', 'ready_for_mock_plan_hints', undefined, true],
  ['UI adapter appends application log via API', 'ready_for_mock_plan_hints', undefined, true],
  ['UI adapter does not write to Edit Plan repository', 'ready_for_mock_plan_hints', undefined, true],
  ['No Qwen call made', 'ready_for_mock_plan_hints', undefined, true],
  ['No DeepSeek call made', 'ready_for_mock_plan_hints', undefined, true],
  ['No provider call made', 'ready_for_mock_plan_hints', undefined, true],
  ['No sound runtime/worker started', 'ready_for_mock_plan_hints', undefined, true],
  ['No file bytes read', 'ready_for_mock_plan_hints', undefined, true],
  ['No external URL fetched', 'ready_for_mock_plan_hints', undefined, true],
  ['No media processing started', 'ready_for_mock_plan_hints', undefined, true],
  ['No render/credit side effect', 'ready_for_mock_plan_hints', undefined, true],
  ['No Supabase write made', 'ready_for_mock_plan_hints', undefined, true],
]

export function listMockProjectEditBriefPlanScenarios(): ProjectEditBriefPlanScenario[] {
  return seeds.map(([title, readiness, instructionKind, ok], index) => ({
    id: `project-edit-brief-plan-scenario-${String(index + 1).padStart(2, '0')}`,
    title,
    input: title.toLowerCase(),
    expectedOk: ok,
    expectedReadinessStatus: readiness,
    expectedInstructionKind: instructionKind,
    expectedSideEffectsFalse: true,
    mockOnly: true,
    ...PROJECT_EDIT_BRIEF_PLAN_SAFETY_FLAGS,
  }))
}
