import type { OfflineRembgBackgroundRemovalRequest, OfflineRembgBackgroundRemovalToolId } from './offline-rembg-background-removal-protocol'

export interface OfflineRembgBackgroundRemovalImageEvidence { imageTag: 'reeditpro-offline-rembg-background-removal-execution:private-local-v1'; imageId: string; imageIdentityHash: string; pinnedBaseImage: 'python:3.13.11-slim-bookworm@sha256:20080e807bfc404f8450b185cf0fc95d553462673598549613735f70a5b4d5d0'; debianSnapshot: '20260623T000000Z'; sourceHashes: Readonly<Record<string, string>>; imageUser: '10001:10001'; imageEntrypoint: readonly ['python', '-s', '/app/runner.py']; imageEnvironmentNames: readonly string[]; rootFilesystemLayerDigests: readonly string[]; labels: Readonly<Record<string, string>> }
export interface OfflineRembgBackgroundRemovalConfinementEvidence { networkMode: 'none'; readOnlyRootFilesystem: true; capDropAll: true; noNewPrivileges: true; privileged: false; pidsLimit: 128; memoryLimitBytes: 2147483648; memoryAndSwapLimitBytes: 2147483648; nanoCpus: 2000000000; tmpfsPath: '/tmp'; tmpfsSizeBytes: 268435456; tmpfsNoExec: true; tmpfsNoSuid: true; tmpfsNoDevice: true; user: '10001:10001'; callerCommandPresent: false; callerBindsPresent: false; callerMountsPresent: false; callerEnvironmentPresent: false; secretLikeImageEnvironmentNames: readonly [] }
export interface OfflineRembgBackgroundRemovalExecutionResult {
  schemaVersion: 'offline-rembg-background-removal-execution-result-v1'; request: OfflineRembgBackgroundRemovalRequest
  artifact: { mimeType: 'image/png'; bytes: Buffer; byteLength: number; sha256: string }
  evidence: { packageName: string; packageVersion: string; onnxRuntimeVersion: string; modelId: string; modelSha256: string; modelByteLength: number; modelUpstreamLicense: string; requestEnvelopeSha256: string; image: OfflineRembgBackgroundRemovalImageEvidence; confinement: OfflineRembgBackgroundRemovalConfinementEvidence; semanticEvidence: Readonly<Record<string, boolean | number | string>>; containerExitCode: 0; oomKilled: false }
  attestation: { schemaVersion: 'offline-rembg-background-removal-execution-attestation-v1'; recordId: string; completedAt: string; toolId: OfflineRembgBackgroundRemovalToolId; imageIdentityHash: string; requestEnvelopeSha256: string; artifactSha256: string; confinementHash: string; attestationHash: string }
  readiness: { privateInternalOnly: true; exactStructuredPayloadOnly: true; canonicalDispatchIntegrated: false; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }
}
export interface OfflineRembgBackgroundRemovalRuntimeAuthority { schemaVersion: 'offline-rembg-background-removal-runtime-authority-v1'; source: 'private_local_offline_rembg_background_removal_runtime_authority'; activatedAt: string; image: OfflineRembgBackgroundRemovalImageEvidence; supportedOperations: readonly { toolId: OfflineRembgBackgroundRemovalToolId; operationId: string }[]; readiness: { privateInternalExecutionReady: true; exactStructuredPayloadOnly: true; canonicalDispatchMayReference: true; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }; blockers: readonly string[]; authorityHash: string }
