import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineRembgBackgroundRemovalDockerRuntime, runOfflineRembgBackgroundRemovalContainer } from './offline-rembg-background-removal-docker-runtime'
import { OFFLINE_REMBG_BACKGROUND_REMOVAL_CONTAINER_PROTOCOL, OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY, OFFLINE_REMBG_BACKGROUND_REMOVAL_OPERATIONS, OFFLINE_REMBG_BACKGROUND_REMOVAL_PACKAGE_IDENTITIES, OFFLINE_REMBG_BACKGROUND_REMOVAL_TOOL_IDS, offlineRembgBackgroundRemovalRequestSha256, validateOfflineRembgBackgroundRemovalRequest } from './offline-rembg-background-removal-protocol'
import type { OfflineRembgBackgroundRemovalExecutionResult, OfflineRembgBackgroundRemovalImageEvidence, OfflineRembgBackgroundRemovalRuntimeAuthority } from './offline-rembg-background-removal-types'

export const OFFLINE_REMBG_BACKGROUND_REMOVAL_STORAGE_ROOT = '/tmp/reeditpro-offline-rembg-background-removal-execution' as const
export const OFFLINE_REMBG_BACKGROUND_REMOVAL_AUTHORITY_PATH = 'runtime-authority/offline-rembg-background-removal-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'This exact operation is confined private/local server-owned image evidence; arbitrary user image ingestion, decoding, storage, malware scanning, privacy review, distributed worker identity, observability, recovery, and deployment remain separate gates.',
  'The current proven dependency closure is ARM64-only; an independently hash-pinned x86_64 image and multi-architecture manifest remain required.',
  'rembg, ONNX Runtime, the converted U2NetP checkpoint, and their dependency closure still require final security, compatibility, output-quality, attribution, and production license review before product or production promotion.',
] as const)

export interface PrivateOfflineRembgBackgroundRemovalRuntime { readonly image: OfflineRembgBackgroundRemovalImageEvidence; execute(value: unknown): Promise<OfflineRembgBackgroundRemovalExecutionResult> }
export async function activatePrivateOfflineRembgBackgroundRemovalRuntime(): Promise<PrivateOfflineRembgBackgroundRemovalRuntime> { if (arguments.length !== 0) throw invalid('rembg runtime activation accepts no caller input.'); const image = await inspectExistingOfflineRembgBackgroundRemovalDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineRembgBackgroundRemovalRuntime(): Promise<PrivateOfflineRembgBackgroundRemovalRuntime> { if (arguments.length !== 0) throw invalid('rembg runtime open accepts no caller input.'); const authority = await readPersistedOfflineRembgBackgroundRemovalRuntimeAuthority(); if (!authority) throw notReady('Verified private rembg runtime authority is unavailable.'); const image = await inspectExistingOfflineRembgBackgroundRemovalDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private rembg image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineRembgBackgroundRemoval(value: unknown): Promise<OfflineRembgBackgroundRemovalExecutionResult> { return executeWithImage(await inspectExistingOfflineRembgBackgroundRemovalDockerRuntime(), value) }
export async function readPersistedOfflineRembgBackgroundRemovalRuntimeAuthority(): Promise<OfflineRembgBackgroundRemovalRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_REMBG_BACKGROUND_REMOVAL_STORAGE_ROOT, relativePath: OFFLINE_REMBG_BACKGROUND_REMOVAL_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private rembg authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-rembg-background-removal-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_rembg_background_removal_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private rembg authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-rembg-background-removal-runtime-authority-v1' || authority.source !== 'private_local_offline_rembg_background_removal_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private rembg authority boundary is invalid.')
  return authority as unknown as OfflineRembgBackgroundRemovalRuntimeAuthority
}
async function executeWithImage(image: OfflineRembgBackgroundRemovalImageEvidence, value: unknown): Promise<OfflineRembgBackgroundRemovalExecutionResult> {
  const request = validateOfflineRembgBackgroundRemovalRequest(value); const result = await runOfflineRembgBackgroundRemovalContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private rembg background removal execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const modelIdentity = record(response.modelIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_REMBG_BACKGROUND_REMOVAL_PACKAGE_IDENTITIES.rembg
  if (response.schemaVersion !== OFFLINE_REMBG_BACKGROUND_REMOVAL_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_rembg_background_removal_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || packageIdentity.onnxRuntimeVersion !== expectedPackage.onnxRuntimeVersion || modelIdentity.modelId !== OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.modelId || modelIdentity.sha256 !== OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.sha256 || modelIdentity.byteLength !== OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.byteLength || modelIdentity.upstreamLicense !== OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.upstreamLicense || modelIdentity.productionLicenseReviewRequired !== true || response.requestEnvelopeSha256 !== offlineRembgBackgroundRemovalRequestSha256(request) || artifact.mimeType !== 'image/png' || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 100 || bytes.length > 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private rembg result identity is invalid.')
  validatePngArtifact(bytes); validateSemanticEvidence(semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private rembg semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-rembg-background-removal-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineRembgBackgroundRemovalRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_REMBG_BACKGROUND_REMOVAL_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-rembg-background-removal-execution-attestation-record-v1', source: 'private_local_checksum_protected_rembg_background_removal_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-rembg-background-removal-execution-result-v1', request, artifact: { mimeType: 'image/png', bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, onnxRuntimeVersion: expectedPackage.onnxRuntimeVersion, modelId: OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.modelId, modelSha256: OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.sha256, modelByteLength: OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.byteLength, modelUpstreamLicense: OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.upstreamLicense, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(evidence: Record<string, unknown>): void { if (evidence.actualPackageEntrypointExecuted !== true || evidence.zeroNetworkRuntimeRequired !== true || evidence.serverOwnedFixtureOnly !== true || evidence.callerMediaAllowed !== false || evidence.callerModelAllowed !== false || evidence.runtimeModelDownloadAllowed !== false || evidence.cpuExecutionProviderOnly !== true || evidence.entrypoint !== 'rembg.remove' || evidence.modelId !== 'u2netp' || evidence.modelSha256 !== OFFLINE_REMBG_BACKGROUND_REMOVAL_MODEL_IDENTITY.sha256 || evidence.modelByteLength !== 4_574_861 || evidence.sourceFixtureWidth !== 128 || evidence.sourceFixtureHeight !== 128 || evidence.outputWidth !== 128 || evidence.outputHeight !== 128 || evidence.outputMode !== 'RGBA' || evidence.alphaMinimum !== 0 || evidence.alphaMaximum !== 255 || evidence.alphaUniqueValueCount !== 160 || evidence.foregroundAlphaMean !== 226.802912 || evidence.backgroundAlphaMean !== 2.492606 || evidence.foregroundSeparationVerified !== true) throw notReady('Private rembg semantic evidence is invalid.') }
function validatePngArtifact(bytes: Buffer): void { if (bytes.length < 45 || !bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) || bytes.toString('ascii', 12, 16) !== 'IHDR' || bytes.readUInt32BE(16) !== 128 || bytes.readUInt32BE(20) !== 128 || bytes[24] !== 8 || bytes[25] !== 6 || !bytes.includes(Buffer.from('IEND'))) throw notReady('rembg PNG artifact structure is invalid.') }
async function persistAuthority(image: OfflineRembgBackgroundRemovalImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-rembg-background-removal-runtime-authority-v1' as const, source: 'private_local_offline_rembg_background_removal_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_REMBG_BACKGROUND_REMOVAL_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_REMBG_BACKGROUND_REMOVAL_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineRembgBackgroundRemovalRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_REMBG_BACKGROUND_REMOVAL_STORAGE_ROOT, relativePath: OFFLINE_REMBG_BACKGROUND_REMOVAL_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-rembg-background-removal-runtime-authority-record-v1', source: 'private_local_checksum_protected_rembg_background_removal_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private rembg response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private rembg response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private rembg response contains an invalid string.'); return value }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
