export type SupabaseResetRetryFailureDiagnosticsDecision =
  | 'recovery_path_supabase_support_packet'
  | 'recovery_path_manual_operator_review_required'
  | 'recovery_path_restore_backup_then_manual_review'
  | 'recovery_path_new_staging_project_approval'
  | 'recovery_path_ordered_apply_approval_required'
  | 'recovery_path_rejected_due_staging_data_risk'

export type SupabaseResetRetryFailureDiagnosticsBlocker =
  | 'pr269_reset_retry_execution_report_missing'
  | 'pr269_reset_retry_failure_evidence_missing'
  | 'staging_reset_retry_failed'
  | 'staging_sql_may_have_run'
  | 'staging_post_reset_migration_history_verify_failed'
  | 'staging_post_reset_schema_rls_verify_failed'
  | 'registry_migration_not_applied'
  | 'registry_schema_absent_after_reset_retry_failure'
  | 'reset_retry_failure_cause_not_proven'
  | 'support_packet_required_before_next_mutation'
  | 'manual_operator_review_required'
  | 'future_recovery_execution_approval_required'
  | 'staging_reset_retry_failure_diagnostics_not_confirmed'
  | 'staging_schema_readonly_inspection_not_confirmed'
  | 'staging_migration_history_audit_not_confirmed'
  | 'staging_db_url_unavailable_for_reset_retry_failure_diagnostics'
  | 'staging_db_url_target_ref_mismatch'
  | 'staging_db_url_unparseable'
  | 'psql_unavailable_for_reset_retry_failure_diagnostics'
  | 'readonly_reset_retry_failure_diagnostics_query_failed'
  | 'post_retry_failure_state_unknown'
  | 'post_retry_failure_state_partially_mutated'
  | 'backup_restore_scope_not_proven'
  | 'forbidden_confirmation_set'

export type SupabaseResetRetryRecoveryOption =
  | 'supabase_support_packet'
  | 'manual_operator_review'
  | 'restore_backup_then_manual_review'
  | 'new_staging_project_or_branch'
  | 'ordered_missing_migration_apply'
  | 'reject_due_staging_data_risk'
