import type { ArtifactRetentionClass, ArtifactRetentionRule } from './privacy-retention-types'

export const artifactRetentionPolicy: Record<ArtifactRetentionClass, ArtifactRetentionRule> = {
  source_media: {
    retentionClass: 'source_media',
    defaultPrivate: true,
    retentionDays: 365,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Never store source media in worker temp beyond the job lease.',
  },
  proxy_media: {
    retentionClass: 'proxy_media',
    defaultPrivate: true,
    retentionDays: 180,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Delete regenerated proxies after source deletion or project deletion.',
  },
  analysis_artifacts: {
    retentionClass: 'analysis_artifacts',
    defaultPrivate: true,
    retentionDays: 180,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Keep only sanitized summaries after deletion where audit policy allows.',
  },
  transcripts: {
    retentionClass: 'transcripts',
    defaultPrivate: true,
    retentionDays: 180,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Remove temporary transcript chunks after worker completion.',
  },
  masks: {
    retentionClass: 'masks',
    defaultPrivate: true,
    retentionDays: 90,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Delete local mask sequences after artifact write or failed job cleanup.',
  },
  generated_assets: {
    retentionClass: 'generated_assets',
    defaultPrivate: true,
    retentionDays: 365,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Clean intermediate worker outputs unless promoted to a private artifact.',
  },
  previews: {
    retentionClass: 'previews',
    defaultPrivate: true,
    retentionDays: 30,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Delete preview temp files after upload or job failure.',
  },
  final_exports: {
    retentionClass: 'final_exports',
    defaultPrivate: true,
    retentionDays: 365,
    deletionEligible: true,
    userDeletionRequired: 'cascade',
    tempCleanupBehavior: 'Final exports are never worker temp source-of-truth files.',
  },
  worker_temp: {
    retentionClass: 'worker_temp',
    defaultPrivate: true,
    retentionDays: 1,
    deletionEligible: true,
    userDeletionRequired: 'temp_cleanup_only',
    tempCleanupBehavior: 'Clean on job completion, retry exhaustion, lease expiry, and startup sweeps.',
  },
  qa_artifacts: {
    retentionClass: 'qa_artifacts',
    defaultPrivate: true,
    retentionDays: 180,
    deletionEligible: true,
    userDeletionRequired: 'preserve_audit_summary',
    tempCleanupBehavior: 'Keep sanitized QA summaries; delete raw temporary extracts.',
  },
}
