export type ProjectWorkflowStatus =
  | 'draft'
  | 'uploading'
  | 'uploaded'
  | 'prepping_footage'
  | 'footage_prep_ready'
  | 'clean_assembly_ready'
  | 'briefing'
  | 'planning'
  | 'plan_ready'
  | 'awaiting_approval'
  | 'approved'
  | 'generating'
  | 'qa_reviewing'
  | 'preview_ready'
  | 'revision_requested'
  | 'exporting'
  | 'export_ready'
  | 'failed'

export type FootagePrepStatus =
  | 'pending'
  | 'ingesting'
  | 'analyzing_media'
  | 'transcribing'
  | 'detecting_silence'
  | 'detecting_retakes'
  | 'building_cleanup_plan'
  | 'building_clean_assembly'
  | 'ready_for_brief'
  | 'failed'

export type EditCueStatus =
  | 'draft'
  | 'pending_cleanup_remap'
  | 'ready'
  | 'conflict'
  | 'included_in_plan'
  | 'adjusted_in_plan'
  | 'ignored'
  | 'used_in_render'
  | 'superseded'

export type RenderQaStatus =
  | 'queued'
  | 'running'
  | 'needs_attention'
  | 'passed'
  | 'failed'
  | 'preview_ready'
