import type {
  ProjectEditSessionHistoryItemKind,
  ProjectEditSessionHistorySafetyStatus,
  ProjectEditSessionHistoryScenario,
} from '../../types/project-edit-session-history'

function scenario(
  id: string,
  title: string,
  expectedWrites: ProjectEditSessionHistoryItemKind[],
  expectedSafetyStatus: ProjectEditSessionHistorySafetyStatus = 'safe_mock_history_update',
  expectedOk = true,
): ProjectEditSessionHistoryScenario {
  return {
    id,
    title,
    input: title,
    expectedOk,
    expectedSafetyStatus,
    expectedWrites,
    mockOnly: true,
  }
}

export const mockProjectEditSessionHistoryScenarios: ProjectEditSessionHistoryScenario[] = [
  scenario('history-policy-manual-checkpoint', 'History policy allows manual checkpoint.', ['snapshot', 'event']),
  scenario('history-policy-mock-version', 'History policy allows mock version.', ['version', 'snapshot', 'event']),
  scenario('history-policy-preview-placeholder', 'History policy allows preview placeholder.', ['preview', 'snapshot', 'event']),
  scenario('history-policy-blocks-real-render', 'History policy blocks real render.', [], 'blocked_real_render_required', false),
  scenario('history-policy-blocks-worker', 'History policy blocks worker-required action.', [], 'blocked_worker_required', false),
  scenario('history-policy-blocks-provider', 'History policy blocks provider-required action.', [], 'blocked_provider_required', false),
  scenario('history-policy-blocks-credit', 'History policy blocks credit-required action.', [], 'blocked_credit_required', false),
  scenario('manual-checkpoint-created', 'Manual checkpoint snapshot created.', ['snapshot']),
  scenario('revision-snapshot-created', 'Revision requested snapshot created.', ['snapshot']),
  scenario('version-snapshot-created', 'Version created snapshot created.', ['snapshot']),
  scenario('preview-snapshot-created', 'Preview created snapshot created.', ['snapshot']),
  scenario('snapshot-timeline-items', 'Snapshot timeline items created.', ['snapshot']),
  scenario('mock-version-created', 'Mock version created.', ['version']),
  scenario('mock-version-approved', 'Mock version approved state-only.', ['version', 'approval']),
  scenario('mock-version-rejected', 'Mock version rejected state-only.', ['version', 'approval']),
  scenario('prior-version-superseded', 'Prior version superseded.', ['version']),
  scenario('version-history-items', 'Version history items created.', ['version']),
  scenario('mock-preview-placeholder-created', 'Mock preview placeholder created.', ['preview']),
  scenario('preview-history-items', 'Preview history items created.', ['preview']),
  scenario('latest-preview-card-model', 'Latest preview card model created.', ['preview']),
  scenario('revision-from-message', 'Revision record from message created.', ['revision']),
  scenario('revision-history-items', 'Revision history items created.', ['revision']),
  scenario('revision-approval-reset-summary', 'Revision approval reset summary created.', ['revision', 'approval']),
  scenario('approval-state-summary', 'Approval state summary created.', ['approval']),
  scenario('approval-reset-after-revision', 'Approval reset after revision works.', ['approval']),
  scenario('mock-approval-requested', 'Mock approval requested state-only.', ['approval']),
  scenario('mock-approve-version-state-only', 'Mock approve version state-only works.', ['approval', 'version']),
  scenario('mock-reject-version-state-only', 'Mock reject version state-only works.', ['approval', 'version']),
  scenario('history-event-created', 'History event created.', ['event']),
  scenario('version-saved-event', 'Version saved event created.', ['event']),
  scenario('preview-placeholder-event', 'Preview placeholder event created.', ['event']),
  scenario('revision-captured-event', 'Revision captured event created.', ['event']),
  scenario('approval-state-event', 'Approval state changed event created.', ['event']),
  scenario('history-package-from-bundle', 'History package created from bundle.', ['snapshot', 'version', 'preview', 'revision', 'event']),
  scenario('timeline-items-created', 'Timeline items created.', ['snapshot', 'version', 'preview', 'revision', 'event']),
  scenario('history-summary-readable', 'History package summary readable.', ['event']),
  scenario('snapshot-summary-readable', 'Snapshot summary readable.', ['snapshot']),
  scenario('version-summary-readable', 'Version summary readable.', ['version']),
  scenario('preview-summary-readable', 'Preview summary readable.', ['preview']),
  scenario('revision-summary-readable', 'Revision summary readable.', ['revision']),
  scenario('approval-summary-readable', 'Approval summary readable.', ['approval']),
  scenario('debug-summary-readable', 'Debug summary readable.', ['event']),
  scenario('validation-action-plan', 'Validation passes for mock action plan.', ['event']),
  scenario('validation-history-package', 'Validation passes for history package.', ['event']),
  scenario('validation-blocks-provider', 'Validation blocks provider flag.', [], 'blocked_provider_required', false),
  scenario('validation-blocks-media-processing', 'Validation blocks media processing flag.', [], 'failed_validation', false),
  scenario('validation-blocks-worker', 'Validation blocks worker flag.', [], 'blocked_worker_required', false),
  scenario('validation-blocks-generation', 'Validation blocks generation request flag.', [], 'failed_validation', false),
  scenario('validation-blocks-render', 'Validation blocks render job flag.', [], 'blocked_real_render_required', false),
  scenario('validation-blocks-credit', 'Validation blocks credit flag.', [], 'blocked_credit_required', false),
  scenario('ui-history-panel-model', 'UI adapter creates history panel model.', ['snapshot', 'version', 'preview', 'revision', 'event']),
  scenario('ui-save-checkpoint-api', 'UI adapter can save manual checkpoint through API.', ['snapshot', 'event']),
  scenario('ui-save-version-api', 'UI adapter can save mock version through API.', ['version', 'snapshot', 'event']),
  scenario('ui-preview-placeholder-api', 'UI adapter can create preview placeholder through API.', ['preview', 'snapshot', 'event']),
  scenario('ui-approve-reject-api', 'UI adapter can approve/reject state-only through API.', ['version', 'approval', 'event']),
  scenario('no-qwen-call', 'No Qwen call made.', []),
  scenario('no-deepseek-call', 'No DeepSeek call made.', []),
  scenario('no-provider-worker-render-credit', 'No provider/worker/render/credit side effect.', []),
  scenario('no-supabase-write', 'No Supabase write made.', []),
  scenario('no-file-bytes-read', 'No file bytes read.', []),
]
