import type { VlmCandidateRecord } from './vlm-model-approval-types'
import { findVlmSourceEvidence } from './vlm-model-source-evidence'

export const vlmModelCandidates: VlmCandidateRecord[] = [
  {
    candidateId: 'qwen3_vl_8b_instruct',
    displayName: 'Qwen3-VL 8B Instruct',
    modelId: 'Qwen/Qwen3-VL-8B-Instruct',
    family: 'Qwen3-VL',
    role: 'Object-aware visual reasoning, safe-zone suggestions, frame understanding, and internal planning/QA signal.',
    runtimeRole: 'model_candidate',
    taskScope: [
      'image-text-to-text planning',
      'object-aware frame understanding',
      'safe-zone suggestion planning',
      'caption/render QA hints',
      'internal visual reasoning signal',
    ],
    firstReeditProScope: [
      'generated VLM fixture planning',
      'future controlled real-frame VLM planning',
      'Track B tool-planning hints after runtime evidence',
    ],
    sourceUrls: [
      'https://github.com/QwenLM/Qwen3-VL',
      'https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct',
    ],
    licenseName: 'Apache-2.0',
    reviewStatus: 'staging_approved_for_track_b_planning',
    downloadStatus: 'blocked_until_phase39b',
    runtimeStatus: 'blocked_until_phase39c',
    noDownloadInPhase39A: true,
    noRuntimeInPhase39A: true,
    noMediaProcessingInPhase39A: true,
    evidence: [
      findVlmSourceEvidence('qwen3_vl_repo_multimodal_vlm'),
      findVlmSourceEvidence('qwen3_vl_repo_apache2_license'),
      findVlmSourceEvidence('qwen3_vl_8b_hf_model_card_identity'),
    ],
  },
  {
    candidateId: 'qwen3_vl_family',
    displayName: 'Qwen3-VL model family',
    family: 'Qwen3-VL',
    role: 'Model-family planning context for future size/revision/file selection and risk comparison.',
    runtimeRole: 'model_family',
    taskScope: ['model-family evidence', 'revision selection planning', 'capability/risk comparison'],
    firstReeditProScope: ['Phase 39B exact revision/file manifest selection only'],
    sourceUrls: ['https://github.com/QwenLM/Qwen3-VL'],
    licenseName: 'Apache-2.0',
    reviewStatus: 'blocked_until_exact_revision_selected',
    downloadStatus: 'blocked_until_phase39b',
    runtimeStatus: 'blocked_until_phase39c',
    noDownloadInPhase39A: true,
    noRuntimeInPhase39A: true,
    noMediaProcessingInPhase39A: true,
    evidence: [
      findVlmSourceEvidence('qwen3_vl_repo_multimodal_vlm'),
      findVlmSourceEvidence('qwen3_vl_repo_apache2_license'),
    ],
  },
  {
    candidateId: 'vllm',
    displayName: 'vLLM',
    role: 'Primary runtime candidate for future private Qwen3-VL generated-fixture runtime verification.',
    runtimeRole: 'primary_runtime_candidate',
    taskScope: ['LLM/VLM serving', 'OpenAI-compatible API planning', 'structured JSON output planning', 'GPU runtime planning'],
    firstReeditProScope: ['Phase 39C generated VLM runtime verification planning only'],
    sourceUrls: [
      'https://docs.vllm.ai/en/latest/models/supported_models/',
      'https://github.com/vllm-project/vllm',
      'https://qwen.readthedocs.io/en/latest/deployment/vllm.html',
    ],
    licenseName: 'Apache-2.0',
    reviewStatus: 'planning_only',
    downloadStatus: 'not_applicable',
    runtimeStatus: 'blocked_until_phase39c',
    noDownloadInPhase39A: true,
    noRuntimeInPhase39A: true,
    noMediaProcessingInPhase39A: true,
    evidence: [
      findVlmSourceEvidence('vllm_supported_models_qwen3_vl'),
      findVlmSourceEvidence('qwen_vllm_docs_runtime_caveats'),
    ],
  },
  {
    candidateId: 'transformers',
    displayName: 'local Transformers fallback planning',
    role: 'Fallback runtime planning only if vLLM cannot satisfy future private local-path/no-download constraints.',
    runtimeRole: 'fallback_runtime_planning',
    taskScope: ['model definition support planning', 'offline local-path fallback planning'],
    firstReeditProScope: ['fallback planning only; no Phase 39A runtime execution'],
    sourceUrls: ['https://github.com/huggingface/transformers'],
    licenseName: 'Apache-2.0',
    reviewStatus: 'planning_only',
    downloadStatus: 'not_applicable',
    runtimeStatus: 'planning_only',
    noDownloadInPhase39A: true,
    noRuntimeInPhase39A: true,
    noMediaProcessingInPhase39A: true,
    evidence: [findVlmSourceEvidence('transformers_repo_apache2_multimodal')],
  },
  {
    candidateId: 'qwen_vl_utils',
    displayName: 'qwen-vl-utils',
    role: 'Future utility-dependency candidate for packaging Qwen visual inputs under bounded generated/controlled fixtures.',
    runtimeRole: 'utility_dependency',
    taskScope: ['visual input preprocessing planning', 'frame/image packaging planning'],
    firstReeditProScope: ['Phase 39C dependency planning only after version/hash pinning'],
    sourceUrls: ['https://pypi.org/project/qwen-vl-utils/'],
    licenseName: 'Apache-2.0',
    reviewStatus: 'planning_only',
    downloadStatus: 'not_applicable',
    runtimeStatus: 'planning_only',
    noDownloadInPhase39A: true,
    noRuntimeInPhase39A: true,
    noMediaProcessingInPhase39A: true,
    evidence: [findVlmSourceEvidence('qwen_vl_utils_pypi_apache2')],
  },
]

export function getVlmCandidate(candidateId: VlmCandidateRecord['candidateId']): VlmCandidateRecord {
  const candidate = vlmModelCandidates.find((item) => item.candidateId === candidateId)
  if (!candidate) throw new Error(`Unknown VLM candidate: ${candidateId}`)
  return candidate
}
