import { WEB_SHELL_SAMPLE_PROJECT_ID } from './web-shell-routes'
import type { ComputeRouteExample, WebShellArtifact, WebShellJob, WebShellProject } from './web-shell-types'

export const sampleProject: WebShellProject = {
  projectId: WEB_SHELL_SAMPLE_PROJECT_ID,
  name: 'Controlled Private Video Chain',
  status: 'controlled_private_test',
  ownerLabel: 'Internal staging review',
  sourceLabel: 'Sanitized controlled test asset',
  updatedLabel: 'Phase 44C shell fixture',
  safetySummary: 'Private-test posture with production, external beta, and broad real media blocked.',
  chainSummary: [
    'Speech and captions passed on one controlled private video.',
    'Smart cut and timeline manifest passed for the controlled chain.',
    'Private export, audio cleanup, and color correction passed within approved scope.',
    'BiRefNet mask frame preview and text-behind-subject frame preview passed.',
    'Real-ESRGAN runtime and bounded sample passed; broader enhancement remains blocked.',
    'SAM2 runtime remains blocked pending generated/synthetic verification.',
  ],
}

export const recentJobs: WebShellJob[] = [
  {
    jobId: 'job-speech-caption-controlled',
    label: 'Speech and caption pass',
    status: 'completed',
    routeCategory: 'cloud_cpu',
    summary: 'Completed in the controlled private chain.',
    details: ['Transcript artifact is private.', 'Caption QA passed with warning-only safe-zone review.'],
  },
  {
    jobId: 'job-smart-cut-controlled',
    label: 'Smart cut timeline',
    status: 'completed',
    routeCategory: 'cloud_cpu',
    summary: 'Completed for the controlled private chain.',
    details: ['Timeline manifest is private.', 'Meaning preservation QA has no blocking findings.'],
  },
  {
    jobId: 'job-real-esrgan-sample',
    label: 'Real-ESRGAN bounded sample',
    status: 'warning',
    routeCategory: 'cloud_gpu_l4',
    summary: 'Runtime verified and sample-first only.',
    details: ['Human review is still required before broader enhancement scope.', 'Full-frame and full-video enhancement remain blocked.'],
  },
  {
    jobId: 'job-sam2-runtime',
    label: 'SAM2 runtime verification',
    status: 'blocked',
    routeCategory: 'cloud_gpu_l4',
    summary: 'Blocked until a dedicated generated/synthetic runtime verification phase.',
    details: ['Temporal tracking is not approved.', 'Full-video masks remain blocked.'],
  },
  {
    jobId: 'job-local-worker-preview',
    label: 'Desktop local preview worker',
    status: 'queued_future',
    routeCategory: 'desktop_local_worker_future',
    summary: 'Future desktop path only.',
    details: ['No desktop runtime exists in Phase 44C.', 'No hardware scan or local AI execution is available.'],
  },
]

export const privateArtifacts: WebShellArtifact[] = [
  {
    artifactId: 'artifact-source-media-private',
    label: 'Private source media',
    kind: 'source_media',
    privacy: 'private',
    summary: 'Source media remains private and is not exposed as a public delivery asset.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-transcript-private',
    label: 'Transcript manifest',
    kind: 'transcript',
    privacy: 'private',
    summary: 'Transcript metadata is available for review without exposing transcript text in fixtures.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-captions-private',
    label: 'Caption tracks',
    kind: 'captions',
    privacy: 'private',
    summary: 'Caption artifacts remain private and review-only.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-timeline-manifest',
    label: 'Timeline manifest',
    kind: 'timeline_manifest',
    privacy: 'private',
    summary: 'Smart cut and caption timing state for the controlled private chain.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-private-export',
    label: 'Private export review',
    kind: 'private_export',
    privacy: 'private',
    summary: 'Private final export evidence remains blocked from public delivery.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-mask-preview',
    label: 'Mask frame preview',
    kind: 'mask',
    privacy: 'private',
    summary: 'Representative-frame mask and cutout evidence for review.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-text-preview',
    label: 'Text-behind-subject preview',
    kind: 'preview',
    privacy: 'private',
    summary: 'Single-frame preview evidence only; full-video text-behind-subject remains blocked.',
    userFacing: true,
  },
  {
    artifactId: 'artifact-qa-report',
    label: 'QA report',
    kind: 'qa_report',
    privacy: 'private',
    summary: 'Blocking and warning status for the controlled chain.',
    userFacing: true,
  },
]

export const computeRouteExamples: ComputeRouteExample[] = [
  {
    routeId: 'route-timeline-preview',
    label: 'Timeline preview',
    source: 'Timeline UI',
    destination: 'Browser preview now; local preview later',
    category: 'browser_preview',
    status: 'preview_only',
    executionEnabled: false,
    summary: 'Static timeline preview is browser-safe; no media processing occurs in Phase 44C.',
  },
  {
    routeId: 'route-caption-preview',
    label: 'Captions preview',
    source: 'Transcript/caption panel',
    destination: 'Browser preview now; local preview later',
    category: 'browser_preview',
    status: 'preview_only',
    executionEnabled: false,
    summary: 'Caption display can be previewed without running speech or render tools.',
  },
  {
    routeId: 'route-media-analysis',
    label: 'Media analysis',
    source: 'Future upload intake',
    destination: 'Cloud CPU',
    category: 'cloud_cpu',
    status: 'planned',
    executionEnabled: false,
    summary: 'Analysis belongs to server-owned CPU workers after approved backend integration.',
  },
  {
    routeId: 'route-speech-transcription',
    label: 'Speech transcription',
    source: 'Future project media',
    destination: 'Cloud CPU',
    category: 'cloud_cpu',
    status: 'planned',
    executionEnabled: false,
    summary: 'Speech transcription stays server-owned and model-policy gated.',
  },
  {
    routeId: 'route-birefnet',
    label: 'BiRefNet masks',
    source: 'Approved representative frames',
    destination: 'Cloud GPU L4',
    category: 'cloud_gpu_l4',
    status: 'planned',
    executionEnabled: false,
    summary: 'BiRefNet runtime is verified for bounded scopes, but web shell execution is disabled.',
  },
  {
    routeId: 'route-sam2',
    label: 'SAM2 temporal masks',
    source: 'Future generated/synthetic verification',
    destination: 'Cloud GPU L4',
    category: 'cloud_gpu_l4',
    status: 'blocked',
    executionEnabled: false,
    summary: 'Blocked until runtime verification; no temporal tracking is available from the web shell.',
  },
  {
    routeId: 'route-real-esrgan',
    label: 'Real-ESRGAN enhancement',
    source: 'Approved bounded samples',
    destination: 'Cloud GPU L4',
    category: 'cloud_gpu_l4',
    status: 'sample_first',
    executionEnabled: false,
    summary: 'Runtime verified and sample-first only; broader enhancement is blocked.',
  },
  {
    routeId: 'route-final-export',
    label: 'Final export',
    source: 'Approved project snapshot',
    destination: 'Cloud render',
    category: 'cloud_render',
    status: 'planned',
    executionEnabled: false,
    summary: 'Final export requires a backend job, private artifacts, and QA gates.',
  },
  {
    routeId: 'route-revideo',
    label: 'Revideo',
    source: 'Evaluation track',
    destination: 'Blocked by policy',
    category: 'blocked_by_policy',
    status: 'blocked',
    executionEnabled: false,
    summary: 'Revideo remains blocked/evaluation-only and is not a core runtime.',
  },
  {
    routeId: 'route-desktop-worker',
    label: 'Desktop local worker',
    source: 'Future desktop shell',
    destination: 'Desktop local worker future',
    category: 'desktop_local_worker_future',
    status: 'needs_approval',
    executionEnabled: false,
    summary: 'Local worker routing requires a later desktop framework and capability phase.',
  },
]
