import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineAudioFluxAnalysisDockerRuntime, runOfflineAudioFluxAnalysisContainer } from './offline-audioflux-analysis-docker-runtime'
import { OFFLINE_AUDIOFLUX_ANALYSIS_CONTAINER_PROTOCOL, OFFLINE_AUDIOFLUX_ANALYSIS_OPERATIONS, OFFLINE_AUDIOFLUX_ANALYSIS_PACKAGE_IDENTITIES, OFFLINE_AUDIOFLUX_ANALYSIS_TOOL_IDS, offlineAudioFluxAnalysisRequestSha256, validateOfflineAudioFluxAnalysisRequest } from './offline-audioflux-analysis-protocol'
import type { OfflineAudioFluxAnalysisExecutionResult, OfflineAudioFluxAnalysisImageEvidence, OfflineAudioFluxAnalysisRuntimeAuthority } from './offline-audioflux-analysis-types'

export const OFFLINE_AUDIOFLUX_ANALYSIS_STORAGE_ROOT = '/tmp/reeditpro-offline-audioflux-analysis-execution' as const
export const OFFLINE_AUDIOFLUX_ANALYSIS_AUTHORITY_PATH = 'runtime-authority/offline-audioflux-analysis-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'This exact operation is confined private/local server-owned fixture evidence; arbitrary user audio ingestion, decoding, storage, scanning, distributed worker identity, observability, recovery, and deployment remain separate gates.',
  'The current proven source build is ARM64-only; an independently hash-pinned x86_64 image and multi-architecture manifest remain required.',
  'AudioFlux and its native dependency closure still require recorded security, compatibility, output-quality, and production license review before product or production promotion.',
] as const)

export interface PrivateOfflineAudioFluxAnalysisRuntime { readonly image: OfflineAudioFluxAnalysisImageEvidence; execute(value: unknown): Promise<OfflineAudioFluxAnalysisExecutionResult> }
export async function activatePrivateOfflineAudioFluxAnalysisRuntime(): Promise<PrivateOfflineAudioFluxAnalysisRuntime> { if (arguments.length !== 0) throw invalid('AudioFlux runtime activation accepts no caller input.'); const image = await inspectExistingOfflineAudioFluxAnalysisDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineAudioFluxAnalysisRuntime(): Promise<PrivateOfflineAudioFluxAnalysisRuntime> { if (arguments.length !== 0) throw invalid('AudioFlux runtime open accepts no caller input.'); const authority = await readPersistedOfflineAudioFluxAnalysisRuntimeAuthority(); if (!authority) throw notReady('Verified private AudioFlux runtime authority is unavailable.'); const image = await inspectExistingOfflineAudioFluxAnalysisDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private AudioFlux image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineAudioFluxAnalysis(value: unknown): Promise<OfflineAudioFluxAnalysisExecutionResult> { return executeWithImage(await inspectExistingOfflineAudioFluxAnalysisDockerRuntime(), value) }
export async function readPersistedOfflineAudioFluxAnalysisRuntimeAuthority(): Promise<OfflineAudioFluxAnalysisRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_AUDIOFLUX_ANALYSIS_STORAGE_ROOT, relativePath: OFFLINE_AUDIOFLUX_ANALYSIS_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private AudioFlux authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-audioflux-analysis-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_audioflux_analysis_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private AudioFlux authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-audioflux-analysis-runtime-authority-v1' || authority.source !== 'private_local_offline_audioflux_analysis_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private AudioFlux authority boundary is invalid.')
  return authority as unknown as OfflineAudioFluxAnalysisRuntimeAuthority
}
async function executeWithImage(image: OfflineAudioFluxAnalysisImageEvidence, value: unknown): Promise<OfflineAudioFluxAnalysisExecutionResult> {
  const request = validateOfflineAudioFluxAnalysisRequest(value); const result = await runOfflineAudioFluxAnalysisContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private AudioFlux analysis execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_AUDIOFLUX_ANALYSIS_PACKAGE_IDENTITIES.audioflux
  if (response.schemaVersion !== OFFLINE_AUDIOFLUX_ANALYSIS_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_audioflux_analysis_operation_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || packageIdentity.sourceSha256 !== expectedPackage.sourceSha256 || packageIdentity.nativeArchitecture !== expectedPackage.nativeArchitecture || response.requestEnvelopeSha256 !== offlineAudioFluxAnalysisRequestSha256(request) || artifact.mimeType !== 'application/json' || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 2 || bytes.length > 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private AudioFlux result identity is invalid.')
  validateJsonArtifact(bytes); validateSemanticEvidence(semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private AudioFlux semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-audioflux-analysis-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineAudioFluxAnalysisRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_AUDIOFLUX_ANALYSIS_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-audioflux-analysis-execution-attestation-record-v1', source: 'private_local_checksum_protected_audioflux_analysis_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-audioflux-analysis-execution-result-v1', request, artifact: { mimeType: 'application/json', bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, sourceSha256: expectedPackage.sourceSha256, nativeArchitecture: expectedPackage.nativeArchitecture, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(evidence: Record<string, unknown>): void { if (evidence.actualPackageEntrypointExecuted !== true || evidence.zeroNetworkRuntimeRequired !== true || evidence.serverOwnedFixtureOnly !== true || evidence.callerMediaAllowed !== false || evidence.sourceBuiltNativeLibrary !== true || evidence.entrypoint !== 'audioflux.BFT+audioflux.Spectral.flux+energy' || evidence.bftExecuted !== true || evidence.spectralFluxExecuted !== true || evidence.spectralEnergyExecuted !== true || evidence.temporalEnergyExecuted !== true || evidence.frameCount !== 247 || evidence.frequencyBins !== 257 || evidence.sampleRate !== 16_000) throw notReady('Private AudioFlux semantic evidence is invalid.') }
function validateJsonArtifact(bytes: Buffer): void { let parsed: unknown; try { parsed = JSON.parse(bytes.toString('utf8')) } catch { throw notReady('AudioFlux artifact is invalid JSON.') } const document = record(parsed); const fixture = record(document.audioFixture); const bft = record(document.bft); const features = record(document.features); if (document.analysisProfileId !== 'approved_server_owned_beat_energy_fixture_v1' || fixture.channelMode !== 'mono' || fixture.durationSamples !== 32_000 || fixture.sampleRate !== 16_000 || fixture.sha256 !== '26459675c270530bbd3321ed50fc8bf4332cfb83aca95e8160101a49cf4ba666' || bft.frequencyBins !== 257 || bft.frameCount !== 247 || bft.fftLength !== 512 || bft.slideLength !== 128 || !Array.isArray(document.strongestFluxFrames) || document.strongestFluxFrames.length !== 8 || Object.values(features).some((value) => typeof value !== 'number' || !Number.isFinite(value))) throw notReady('AudioFlux JSON artifact is invalid.') }
async function persistAuthority(image: OfflineAudioFluxAnalysisImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-audioflux-analysis-runtime-authority-v1' as const, source: 'private_local_offline_audioflux_analysis_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_AUDIOFLUX_ANALYSIS_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_AUDIOFLUX_ANALYSIS_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineAudioFluxAnalysisRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_AUDIOFLUX_ANALYSIS_STORAGE_ROOT, relativePath: OFFLINE_AUDIOFLUX_ANALYSIS_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-audioflux-analysis-runtime-authority-record-v1', source: 'private_local_checksum_protected_audioflux_analysis_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private AudioFlux response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private AudioFlux response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private AudioFlux response contains an invalid string.'); return value }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
