import type { ActivationPhasePlan } from './activation-baseline-audit-types'

const commonMustNotDo = [
  'Do not mark production ready.',
  'Do not unblock external beta.',
  'Do not run provider calls, add secrets, download model weights, or process real user media.',
]

export const activationPhaseRoadmap: ActivationPhasePlan[] = [
  phase(18, 'Activation baseline audit', 'complete', 'Audit the M0-M17 dry-run runtime baseline and publish the activation roadmap.', 'This creates a controlled bridge from static readiness into human-run staging without launching production.', ['docs/activation-baseline-audit.md', 'docs/activation-phase-roadmap.md', 'server/activation/*'], ['Review this audit and confirm the repo still has no production launch approval.'], ['Activation docs exist.', 'Activation report keeps production, external beta, and real user media blocked.'], ['Do not build images or deploy.']),
  phase(19, 'Local full smoke/static readiness baseline', 'ready_to_start', 'Run all local smoke, summary, lint, build, and server build checks on the merged baseline.', 'This proves the branch is stable before any human-run container or cloud action.', ['package.json smoke scripts', 'server/smoke/*', 'server/cli/*summary.ts'], ['Run the full local validation suite and record failures/warnings.'], ['All required smoke/summary checks pass or have documented blockers.', 'No package install or lockfile churn is introduced.'], ['Do not run Docker, gcloud, providers, or real media.']),
  phase(20, 'Build production containers locally/human-run', 'human_run_required', 'Build production image templates locally after Phase 19 passes.', 'Actual image builds are the first environment-specific activation step and must be human-controlled.', ['scripts/docker/prod/01-build-*.example.sh', 'docker/prod/*/Dockerfile'], ['Choose image tag.', 'Run reviewed Docker build examples manually.'], ['Images build with reviewed tags.', 'No secrets are baked into images.'], ['Do not push images or deploy.']),
  phase(21, 'Container readiness validation', 'human_run_required', 'Run container readiness examples against human-built images.', 'This verifies expected tools inside images before staging deployment.', ['scripts/docker/prod/09-run-container-readiness-*.example.sh', 'docs/production-container-readiness-runbook.md'], ['Set explicit image variables and REEDITPRO_CONFIRM_CONTAINER_READINESS=true.', 'Run CPU/render/QA/GPU readiness examples.'], ['Readiness output is reviewed.', 'Missing tools, FFmpeg/libass, and model/license blockers are documented.'], ['Do not process user media or treat tool availability as model/license approval.']),
  phase(22, 'GCP staging foundation setup', 'human_run_required', 'Create reviewed staging resources after local and container readiness pass.', 'Staging resources are required before controlled cloud jobs can run.', ['scripts/gcp/prod/01-enable-apis.sh', 'scripts/gcp/prod/02-create-artifact-registry.sh', 'scripts/gcp/prod/03-create-gcs-buckets.sh', 'docs/google-cloud/production-gcp-setup-runbook.md'], ['Review target project/region.', 'Set REEDITPRO_CONFIRM_PROD_SETUP=true only for the intended staging project.', 'Run reviewed GCP setup scripts manually.'], ['APIs, Artifact Registry, private buckets, service accounts, secret placeholders, and IAM are reviewed.'], ['Do not add secret values, deploy services, or run jobs.']),
  phase(23, 'Push containers to Artifact Registry', 'human_run_required', 'Push reviewed images to the staging Artifact Registry.', 'Staging deployment needs immutable, reviewed image references.', ['scripts/docker/prod/07-push-images.example.sh', 'scripts/gcp/prod/07-build-image-commands.sh'], ['Review printed image names.', 'Push only approved image tags manually.'], ['Images exist in Artifact Registry with reviewed tags.', 'No latest-only or untraceable tag is used.'], ['Do not deploy Cloud Run or run jobs.']),
  phase(24, 'Deploy staging API and non-GPU worker jobs', 'human_run_required', 'Deploy API, CPU, render, and QA staging services/jobs after images and resources exist.', 'Non-GPU staging validates backend transport and private storage before GPU or real media testing.', ['scripts/gcp/prod/08-deploy-api-service.example.sh', 'scripts/gcp/prod/09-deploy-cpu-worker-job.example.sh', 'scripts/gcp/prod/11-deploy-render-worker-job.example.sh', 'scripts/gcp/prod/12-deploy-qa-worker-job.example.sh'], ['Deploy reviewed staging API and non-GPU jobs manually.'], ['Services/jobs deploy to staging only.', 'No real provider or user media path is enabled.'], ['Do not deploy GPU workers or external beta.']),
  phase(25, 'Staging generated-fixture E2E', 'blocked', 'Run generated-fixture E2E against staging services after non-GPU deployment.', 'Generated fixtures validate staging orchestration without user media.', ['production full E2E workflow scripts', 'staging run logs'], ['Run staging dry-run/generated-fixture E2E after deployment approval.'], ['Generated fixture passes approved snapshot, storage, worker, QA, and final blocker checks.'], ['Do not use arbitrary or real user video.']),
  phase(26, 'Model weight and license approval workflow', 'not_started', 'Review and approve required model weights, package licenses, and storage policy.', 'GPU and real video tests require explicit license/security approval.', ['docs/production-model-weight-readiness-plan.md', 'docs/production-gpu-model-weight-policy.md', 'server/model-weights/*'], ['Review each model/checkpoint license.', 'Record approved manifests and storage references outside Codex.'], ['Required manifests are approved for intended use.', 'Non-commercial/unknown/evaluation-only paths remain blocked.'], ['Do not download model weights from Codex or bypass license review.']),
  phase(27, 'Deploy staging GPU worker, L4 only', 'blocked', 'Deploy the first staging GPU worker after model/license approval.', 'GPU execution should start with the bounded L4 target and approved models only.', ['scripts/gcp/prod/10-deploy-gpu-worker-job.example.sh', 'scripts/gcp/prod/14-run-gpu-smoke-job.example.sh'], ['Deploy GPU worker manually after model approval.', 'Run GPU smoke against staging only.'], ['L4 GPU job deploys and smoke validates no unapproved model path.'], ['Do not use RTX future/evaluation path or real user video yet.']),
  phase(28, 'First controlled actual video test: speech/caption only', 'blocked', 'Run the first private real video test through speech/caption only.', 'This is the lowest-risk real-media entry point after staging/model/readiness gates.', ['docs/production-real-speech-caption-runbook.md', 'speech/caption workers'], ['Use one approved private test video after staging, readiness, storage, and model approvals pass.'], ['Transcript/caption artifacts are private and QA-reviewed.', 'No final export or public share occurs.'], ['Do not run smart cut, render, export, or arbitrary user media.']),
  phase(29, 'Controlled actual video test: smart cut + captions', 'blocked', 'Add smart cut and captions to the controlled private video path.', 'This validates timing and meaning preservation after speech/caption succeeds.', ['docs/production-real-smart-cut-runbook.md', 'smart-cut/timeline workers'], ['Run approved private test video through smart cut + captions.'], ['No mid-word cuts.', 'Timeline and caption QA pass or block.'], ['Do not final export or public share.']),
  phase(30, 'Controlled actual video test: private final export', 'blocked', 'Produce a private final export for a controlled test video.', 'Final export tests render/delivery gates before broader feature testing.', ['docs/production-final-render-runbook.md', 'render/export workers'], ['Run private final export after upstream QA passes.'], ['Final export remains private.', 'Final delivery/share stays blocked.'], ['Do not public deliver, share, or start beta.']),
  phase(31, 'Controlled actual video test: audio cleanup', 'blocked', 'Validate audio cleanup on a controlled private test video.', 'Audio tools need naturalness/loudness QA before broader use.', ['docs/production-real-audio-execution-runbook.md', 'audio workers'], ['Run audio cleanup only after approved staging/model readiness.'], ['Audio QA passes or blocks.', 'Source audio remains immutable.'], ['Do not use unapproved models or overwrite source media.']),
  phase(32, 'Controlled actual video test: color correction', 'blocked', 'Validate color correction on a controlled private test video.', 'Color QA must protect exposure, skin tone, and export space before wider tests.', ['docs/production-real-color-execution-runbook.md', 'color workers'], ['Run color correction after prior staging readiness gates.'], ['Color QA passes or blocks.', 'Private artifacts only.'], ['Do not final/public deliver without full go/no-go.']),
  phase(33, 'Controlled actual video test: masks/text-behind-subject', 'blocked', 'Validate mask/background/text-behind-subject execution on controlled private media.', 'Segmentation workflows need model/license and visual QA before use.', ['docs/production-real-mask-execution-runbook.md', 'mask/text-behind-subject workers'], ['Run controlled mask test with approved models only.'], ['Mask edge, temporal, and subject coverage QA pass or block.'], ['Do not use unapproved checkpoints or Revideo.']),
  phase(34, 'Controlled actual video test: enhancement/slow motion', 'blocked', 'Validate enhancement and slow-motion on controlled private media.', 'Enhancement can hallucinate or warp; sample-first QA must prove safety.', ['docs/production-real-enhancement-slowmotion-runbook.md', 'enhancement/slow-motion workers'], ['Run sample-first enhancement and selected slow-motion test.'], ['Artifact/warp QA passes or blocks.', 'Original media remains immutable.'], ['Do not run unapproved model weights or broad batches.']),
  phase(35, 'Full actual video E2E, private beta candidate', 'blocked', 'Run one full private actual-video E2E after all controlled tests pass.', 'This determines whether internal beta can be considered.', ['docs/production-full-e2e-workflow-test-suite.md', 'production E2E workflow reports'], ['Run full private E2E with approved test media and signoffs.'], ['All required QA, storage, cost, security, and fallback gates pass.'], ['Do not call this external beta or paid production.']),
  phase(36, 'Limited internal beta readiness', 'future', 'Evaluate limited internal beta after private full E2E succeeds.', 'Internal beta requires operational, support, legal, and privacy readiness beyond technical pass.', ['docs/production-beta-readiness-scorecard.md', 'docs/production-beta-readiness-runbook.md'], ['Review beta scorecard and operational ownership.'], ['Internal-only scope is approved.', 'Kill switches, cost controls, privacy, and support are ready.'], ['Do not open external beta.']),
  phase(37, 'External beta go/no-go', 'blocked', 'Make a strict go/no-go decision for external beta.', 'External beta should only happen after all human approvals and evidence are complete.', ['docs/production-go-no-go-checklist.md', 'production hardening and beta reports'], ['Review final go/no-go with required owners.'], ['Deployment, rollback, model/license, security, cost, privacy, storage, legal, and support approvals are complete.'], ['Do not approve paid production by default.']),
]

export function getActivationPhasePlan(id: ActivationPhasePlan['id']): ActivationPhasePlan | undefined {
  return activationPhaseRoadmap.find((phasePlan) => phasePlan.id === id)
}

function phase(
  id: ActivationPhasePlan['id'],
  title: string,
  status: ActivationPhasePlan['status'],
  goal: string,
  why: string,
  expectedFilesOrScripts: string[],
  humanRunActions: string[],
  acceptanceGates: string[],
  mustNotDo: string[],
): ActivationPhasePlan {
  return {
    id,
    title,
    status,
    goal,
    why,
    expectedFilesOrScripts,
    humanRunActions,
    acceptanceGates,
    mustNotDo: [...mustNotDo, ...commonMustNotDo],
  }
}
