import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineNativeImagePipelineDockerRuntime, runOfflineNativeImagePipelineContainer } from './offline-native-image-pipeline-docker-runtime'
import {
  OFFLINE_NATIVE_IMAGE_PIPELINE_CONTAINER_PROTOCOL, OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS,
  OFFLINE_NATIVE_IMAGE_PIPELINE_PACKAGE_IDENTITIES, OFFLINE_NATIVE_IMAGE_PIPELINE_TOOL_IDS,
  offlineNativeImagePipelineRequestSha256, validateOfflineNativeImagePipelineRequest,
} from './offline-native-image-pipeline-protocol'
import type { OfflineNativeImagePipelineExecutionResult, OfflineNativeImagePipelineImageEvidence, OfflineNativeImagePipelineRuntimeAuthority } from './offline-native-image-pipeline-types'

export const OFFLINE_NATIVE_IMAGE_PIPELINE_STORAGE_ROOT = '/tmp/reeditpro-offline-native-image-pipeline-execution' as const
export const OFFLINE_NATIVE_IMAGE_PIPELINE_AUTHORITY_PATH = 'runtime-authority/offline-native-image-pipeline-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'These exact operations are confined private/local fixture evidence; arbitrary user media, distributed worker identity, multi-architecture images, scanning, observability, recovery, and deployment remain separate gates.',
  'OpenColorIO and OpenImageIO still require recorded dependency, security, and production license review before product or production promotion.',
  'GStreamer remains an LGPL allowed-with-review readiness operation; production build, plugin closure, distribution, and pipeline coverage review remain mandatory.',
] as const)

export interface PrivateOfflineNativeImagePipelineRuntime { readonly image: OfflineNativeImagePipelineImageEvidence; execute(value: unknown): Promise<OfflineNativeImagePipelineExecutionResult> }
export async function activatePrivateOfflineNativeImagePipelineRuntime(): Promise<PrivateOfflineNativeImagePipelineRuntime> { if (arguments.length !== 0) throw invalid('Native image pipeline runtime activation accepts no caller input.'); const image = await inspectExistingOfflineNativeImagePipelineDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineNativeImagePipelineRuntime(): Promise<PrivateOfflineNativeImagePipelineRuntime> { if (arguments.length !== 0) throw invalid('Native image pipeline runtime open accepts no caller input.'); const authority = await readPersistedOfflineNativeImagePipelineRuntimeAuthority(); if (!authority) throw notReady('Verified private native image pipeline runtime authority is unavailable.'); const image = await inspectExistingOfflineNativeImagePipelineDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private native image pipeline image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineNativeImagePipeline(value: unknown): Promise<OfflineNativeImagePipelineExecutionResult> { return executeWithImage(await inspectExistingOfflineNativeImagePipelineDockerRuntime(), value) }
export async function readPersistedOfflineNativeImagePipelineRuntimeAuthority(): Promise<OfflineNativeImagePipelineRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_NATIVE_IMAGE_PIPELINE_STORAGE_ROOT, relativePath: OFFLINE_NATIVE_IMAGE_PIPELINE_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private native image pipeline authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-native-image-pipeline-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_native_image_pipeline_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private native image pipeline authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-native-image-pipeline-runtime-authority-v1' || authority.source !== 'private_local_offline_native_image_pipeline_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private native image pipeline authority boundary is invalid.')
  return authority as unknown as OfflineNativeImagePipelineRuntimeAuthority
}
async function executeWithImage(image: OfflineNativeImagePipelineImageEvidence, value: unknown): Promise<OfflineNativeImagePipelineExecutionResult> {
  const request = validateOfflineNativeImagePipelineRequest(value); const result = await runOfflineNativeImagePipelineContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private native image pipeline execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_NATIVE_IMAGE_PIPELINE_PACKAGE_IDENTITIES[request.toolId]; const expectedMimeType = request.toolId === 'streamer_render_pipeline_support' ? 'application/json' : 'image/png'
  if (response.schemaVersion !== OFFLINE_NATIVE_IMAGE_PIPELINE_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_native_image_pipeline_operation_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || response.requestEnvelopeSha256 !== offlineNativeImagePipelineRequestSha256(request) || artifact.mimeType !== expectedMimeType || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 2 || bytes.length > 8 * 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private native image pipeline result identity is invalid.')
  if (expectedMimeType === 'image/png') validatePng(bytes); else validateJsonArtifact(bytes)
  validateSemanticEvidence(request.toolId, semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private native image pipeline semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-native-image-pipeline-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineNativeImagePipelineRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_NATIVE_IMAGE_PIPELINE_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-native-image-pipeline-execution-attestation-record-v1', source: 'private_local_checksum_protected_native_image_pipeline_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-native-image-pipeline-execution-result-v1', request, artifact: { mimeType: expectedMimeType, bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(toolId: keyof typeof OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS, evidence: Record<string, unknown>): void {
  const entrypoints = { opencolorio: 'ocioconvert --lut', openimageio: 'oiiotool --resize', streamer_render_pipeline_support: 'gst-launch-1.0' } as const
  if (evidence.actualPackageEntrypointExecuted !== true || evidence.entrypoint !== entrypoints[toolId] || evidence.zeroNetworkRuntimeRequired !== true) throw notReady('Private native image pipeline semantic evidence is invalid.')
  if (toolId === 'opencolorio' && (evidence.approvedLutHashVerified !== true || evidence.cpuColorTransformExecuted !== true || evidence.inputColorSpace !== 'srgb' || evidence.outputColorSpace !== 'rec709' || evidence.width !== 64 || evidence.height !== 64)) throw notReady('OpenColorIO execution evidence is invalid.')
  if (toolId === 'openimageio' && (evidence.sequenceFramesProcessed !== 2 || evidence.resizeExecuted !== true || evidence.metadataPreserved !== false || evidence.outputFormat !== 'png' || evidence.width !== 64 || evidence.height !== 64 || typeof evidence.secondFrameSha256 !== 'string' || !/^[a-f0-9]{64}$/.test(evidence.secondFrameSha256))) throw notReady('OpenImageIO execution evidence is invalid.')
  if (toolId === 'streamer_render_pipeline_support' && (evidence.videoPipelineExecuted !== true || evidence.audioPipelineExecuted !== true || evidence.fixedTestSourcesUsed !== true || evidence.networkRequired !== false)) throw notReady('GStreamer execution evidence is invalid.')
}
function validateJsonArtifact(bytes: Buffer): void { try { const value = JSON.parse(bytes.toString('utf8')); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('not object') } catch (cause) { throw notReady('Native image pipeline JSON artifact is invalid.', cause) } }
function validatePng(bytes: Buffer): void { if (bytes.length < 256 || bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a' || bytes.readUInt32BE(16) !== 64 || bytes.readUInt32BE(20) !== 64) throw notReady('Native image pipeline PNG artifact is invalid.') }
async function persistAuthority(image: OfflineNativeImagePipelineImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-native-image-pipeline-runtime-authority-v1' as const, source: 'private_local_offline_native_image_pipeline_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_NATIVE_IMAGE_PIPELINE_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_NATIVE_IMAGE_PIPELINE_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineNativeImagePipelineRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_NATIVE_IMAGE_PIPELINE_STORAGE_ROOT, relativePath: OFFLINE_NATIVE_IMAGE_PIPELINE_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-native-image-pipeline-runtime-authority-record-v1', source: 'private_local_checksum_protected_native_image_pipeline_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private native image pipeline response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private native image pipeline response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private native image pipeline response contains an invalid string.'); return value }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
