import type {
  ProductionToolInputType,
  ProductionToolOutputType,
} from '../tool-registry'
import type {
  QualityGateType,
  ToolArtifactType,
} from '../../src/backend/contracts/production-tool-runtime-contracts'

export type ToolCallingArtifactType =
  | ProductionToolInputType
  | ProductionToolOutputType
  | ToolArtifactType

export interface ToolCallingOperationDefinition {
  operationId: string
  description: string
  inputArtifactTypes: readonly ToolCallingArtifactType[]
  outputArtifactTypes: readonly ToolCallingArtifactType[]
  qualityGateTypes: readonly QualityGateType[]
  previewRequired: boolean
  finalExportRequired: boolean
  futureAllowed: boolean
}

export const TOOL_CALLING_OPERATION_DEFINITIONS = [
  {
    operationId: 'media.inspect',
    description: 'Inspect source or proxy media for duration, streams, codecs, and basic readiness metadata.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video', 'audio'],
    outputArtifactTypes: ['analysis_report', 'qa_report', 'json_spec'],
    qualityGateTypes: ['render_asset_integrity'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'media.proxy.create',
    description: 'Create edit-friendly proxy media for preview and downstream analysis planning.',
    inputArtifactTypes: ['source_media', 'video'],
    outputArtifactTypes: ['proxy_video', 'qa_report'],
    qualityGateTypes: ['render_asset_integrity', 'export_duration_sync'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'media.audio.extract',
    description: 'Extract source audio for speech, timing, cleanup, and loudness operations.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video'],
    outputArtifactTypes: ['extracted_audio', 'audio', 'qa_report'],
    qualityGateTypes: ['audio_sync', 'render_asset_integrity'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'video.scene.detect',
    description: 'Detect scene and shot boundary candidates for cut planning.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video'],
    outputArtifactTypes: ['analysis_report', 'timeline_manifest', 'json_spec'],
    qualityGateTypes: ['cut_smoothness'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'video.frame.sample',
    description: 'Sample representative frames or keyframes for visual analysis and thumbnail planning.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video'],
    outputArtifactTypes: ['image_asset', 'representative_frame', 'analysis_report'],
    qualityGateTypes: ['render_asset_integrity'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'video.motion.score',
    description: 'Score motion intensity and candidate motion windows for pacing decisions.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video', 'frame_sequence'],
    outputArtifactTypes: ['analysis_report', 'json_spec'],
    qualityGateTypes: ['cut_smoothness', 'render_asset_integrity'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'video.blur.score',
    description: 'Score blur and frame quality for selection, enhancement, or QA decisions.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'video', 'frame_sequence'],
    outputArtifactTypes: ['analysis_report', 'qa_report', 'json_spec'],
    qualityGateTypes: ['render_asset_integrity'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'video.safe_zone.detect',
    description: 'Detect caption, overlay, and subject safe zones from visual evidence.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['analysis_report', 'qa_report', 'json_spec'],
    qualityGateTypes: ['caption_safe_zone', 'ocr_text_overlap'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'audio.transcribe',
    description: 'Transcribe speech into structured transcript artifacts.',
    inputArtifactTypes: ['audio', 'extracted_audio', 'source_media'],
    outputArtifactTypes: ['transcript_json', 'analysis_report'],
    qualityGateTypes: ['transcript_alignment'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'audio.word_align',
    description: 'Align words or caption tokens to source audio timing.',
    inputArtifactTypes: ['audio', 'extracted_audio', 'transcript_json'],
    outputArtifactTypes: ['word_timestamps_json', 'caption_segments_json', 'analysis_report'],
    qualityGateTypes: ['transcript_alignment', 'caption_timing'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'audio.loudness.normalize',
    description: 'Plan loudness normalization and sync checks for preview or export audio.',
    inputArtifactTypes: ['audio', 'extracted_audio', 'processed_audio'],
    outputArtifactTypes: ['processed_audio', 'qa_report'],
    qualityGateTypes: ['audio_loudness', 'audio_sync'],
    previewRequired: false,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'audio.cleanup',
    description: 'Plan speech cleanup, denoise, or fallback audio repair operations.',
    inputArtifactTypes: ['audio', 'extracted_audio', 'source_media'],
    outputArtifactTypes: ['processed_audio', 'cleaned_audio', 'qa_report'],
    qualityGateTypes: ['audio_naturalness', 'audio_loudness', 'audio_sync'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'caption.generate',
    description: 'Generate caption segments from transcript and aligned speech evidence.',
    inputArtifactTypes: ['transcript_json', 'word_timestamps_json'],
    outputArtifactTypes: ['caption_segments_json', 'caption_segments'],
    qualityGateTypes: ['transcript_alignment', 'caption_timing'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'caption.align',
    description: 'Adjust caption timing against speech and timeline evidence.',
    inputArtifactTypes: ['caption_segments_json', 'transcript_json', 'timeline_manifest'],
    outputArtifactTypes: ['caption_segments_json', 'qa_report'],
    qualityGateTypes: ['caption_timing', 'transcript_alignment'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'caption.style',
    description: 'Plan caption style, layout, readability, and safe-zone decisions.',
    inputArtifactTypes: ['caption_segments', 'caption_segments_json', 'render_manifest', 'json_data'],
    outputArtifactTypes: ['render_manifest', 'json_spec', 'qa_report'],
    qualityGateTypes: ['caption_readability', 'caption_safe_zone'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'caption.burn_in',
    description: 'Plan caption burn-in or rendered caption track composition.',
    inputArtifactTypes: ['caption_segments', 'caption_segments_json', 'render_manifest', 'video'],
    outputArtifactTypes: ['processed_video', 'final_export', 'qa_report'],
    qualityGateTypes: ['caption_readability', 'caption_timing', 'caption_safe_zone', 'render_asset_integrity'],
    previewRequired: true,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'timeline.smart_cut',
    description: 'Compose smart cut timing candidates from media, scene, speech, and pacing evidence.',
    inputArtifactTypes: ['analysis_report', 'transcript_json', 'source_media', 'proxy_media'],
    outputArtifactTypes: ['timeline_manifest', 'json_spec', 'qa_report'],
    qualityGateTypes: ['cut_smoothness', 'render_timeline_integrity'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'timeline.validate',
    description: 'Validate timeline structure, tracks, ranges, and render handoff integrity.',
    inputArtifactTypes: ['timeline_manifest', 'json_data'],
    outputArtifactTypes: ['timeline_manifest', 'qa_report', 'json_spec'],
    qualityGateTypes: ['render_timeline_integrity'],
    previewRequired: true,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'timeline.to_otio',
    description: 'Plan conversion to or from OpenTimelineIO-compatible structured timeline data.',
    inputArtifactTypes: ['timeline_manifest', 'json_data'],
    outputArtifactTypes: ['timeline_manifest', 'opentimelineio_manifest', 'json_spec'],
    qualityGateTypes: ['render_timeline_integrity'],
    previewRequired: false,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'render.preview',
    description: 'Plan preview rendering from timeline and render manifests.',
    inputArtifactTypes: ['timeline_manifest', 'render_manifest', 'image', 'audio', 'video'],
    outputArtifactTypes: ['preview_video', 'qa_report'],
    qualityGateTypes: ['render_asset_integrity', 'render_timeline_integrity', 'caption_safe_zone'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'render.compose',
    description: 'Plan deterministic render composition for layers, captions, assets, and templates.',
    inputArtifactTypes: ['timeline_manifest', 'render_manifest', 'image', 'audio', 'video'],
    outputArtifactTypes: ['render_manifest', 'processed_video', 'preview_video', 'qa_report'],
    qualityGateTypes: ['render_asset_integrity', 'render_timeline_integrity', 'caption_safe_zone'],
    previewRequired: true,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'export.mux',
    description: 'Plan final muxing, transcode, and container output from render/audio/video artifacts.',
    inputArtifactTypes: ['render_manifest', 'processed_video', 'processed_audio', 'video', 'audio'],
    outputArtifactTypes: ['final_export', 'qa_report'],
    qualityGateTypes: ['export_codec_format', 'export_duration_sync', 'audio_sync'],
    previewRequired: false,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'export.validate',
    description: 'Validate exported media container, stream sync, duration, and delivery readiness.',
    inputArtifactTypes: ['final_export', 'video', 'audio'],
    outputArtifactTypes: ['qa_report', 'analysis_report', 'json_spec'],
    qualityGateTypes: ['export_codec_format', 'export_duration_sync', 'final_delivery'],
    previewRequired: false,
    finalExportRequired: true,
    futureAllowed: false,
  },
  {
    operationId: 'mask.generate',
    description: 'Plan primary mask generation for foreground, object, or subject separation.',
    inputArtifactTypes: ['image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['mask_image', 'mask_sequence', 'image_asset', 'qa_report'],
    qualityGateTypes: ['mask_edge_quality', 'mask_subject_coverage'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'mask.refine',
    description: 'Plan mask refinement, edge scoring, temporal stability checks, or subject coverage repair.',
    inputArtifactTypes: ['mask', 'mask_image', 'mask_sequence', 'image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['mask_image', 'mask_sequence', 'qa_report', 'json_spec'],
    qualityGateTypes: ['mask_edge_quality', 'mask_temporal_stability', 'mask_subject_coverage'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'background.remove',
    description: 'Plan background removal and cutout creation with mask QA and fallback options.',
    inputArtifactTypes: ['image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['mask_image', 'mask_sequence', 'image_asset', 'processed_video', 'qa_report'],
    qualityGateTypes: ['mask_edge_quality', 'mask_subject_coverage', 'mask_temporal_stability'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'video.enhance',
    description: 'Plan video or frame enhancement, upscale, and artifact QA.',
    inputArtifactTypes: ['image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['image_asset', 'processed_video', 'enhanced_video', 'qa_report'],
    qualityGateTypes: ['enhancement_artifacts', 'render_asset_integrity'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'video.slow_motion',
    description: 'Plan slow-motion or interpolation effects with artifact and duration QA.',
    inputArtifactTypes: ['video', 'frame_sequence'],
    outputArtifactTypes: ['processed_video', 'interpolated_video', 'qa_report'],
    qualityGateTypes: ['slow_motion_artifacts', 'export_duration_sync'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'color.exposure.correct',
    description: 'Plan exposure and color-space correction for footage or generated visual assets.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'image', 'video'],
    outputArtifactTypes: ['processed_video', 'image_asset', 'qa_report', 'analysis_report'],
    qualityGateTypes: ['color_exposure', 'color_export_space'],
    previewRequired: true,
    finalExportRequired: true,
    futureAllowed: true,
  },
  {
    operationId: 'color.shot_match',
    description: 'Plan shot matching, skin-tone QA, and color consistency across source clips or generated assets.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'image', 'video'],
    outputArtifactTypes: ['processed_video', 'image_asset', 'qa_report', 'analysis_report'],
    qualityGateTypes: ['color_shot_match', 'color_skin_tone', 'color_export_space'],
    previewRequired: true,
    finalExportRequired: true,
    futureAllowed: true,
  },
  {
    operationId: 'ocr.detect_text',
    description: 'Plan OCR text-region detection for screen recordings, labels, documents, and overlay avoidance.',
    inputArtifactTypes: ['image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['ocr_report_json', 'analysis_report', 'qa_report', 'json_spec'],
    qualityGateTypes: ['ocr_text_overlap', 'caption_safe_zone'],
    previewRequired: true,
    finalExportRequired: false,
    futureAllowed: true,
  },
  {
    operationId: 'thumbnail.generate',
    description: 'Plan thumbnail or representative still generation from media or image artifacts.',
    inputArtifactTypes: ['source_media', 'proxy_media', 'image', 'video', 'frame_sequence'],
    outputArtifactTypes: ['image_asset', 'representative_frame', 'qa_report'],
    qualityGateTypes: ['render_asset_integrity', 'caption_safe_zone'],
    previewRequired: false,
    finalExportRequired: false,
    futureAllowed: false,
  },
  {
    operationId: 'qa.final_delivery',
    description: 'Plan final delivery QA gates across export, audio, timeline, render, and artifact integrity.',
    inputArtifactTypes: ['final_export', 'qa_report', 'timeline_manifest', 'render_manifest'],
    outputArtifactTypes: ['qa_report', 'analysis_report', 'json_spec'],
    qualityGateTypes: ['final_delivery', 'export_codec_format', 'export_duration_sync', 'audio_loudness', 'render_timeline_integrity'],
    previewRequired: false,
    finalExportRequired: true,
    futureAllowed: false,
  },
] as const satisfies readonly ToolCallingOperationDefinition[]

export type ToolCallingOperationId = typeof TOOL_CALLING_OPERATION_DEFINITIONS[number]['operationId']

const operationDefinitionById = new Map<string, ToolCallingOperationDefinition>(
  TOOL_CALLING_OPERATION_DEFINITIONS.map((operation) => [operation.operationId, operation]),
)

export function getOperationDefinition(operationId: ToolCallingOperationId | string): ToolCallingOperationDefinition | undefined {
  return operationDefinitionById.get(operationId)
}

export function listOperationDefinitions(): ToolCallingOperationDefinition[] {
  return [...TOOL_CALLING_OPERATION_DEFINITIONS]
}
