import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineNativeAudioProcessingDockerRuntime, runOfflineNativeAudioProcessingContainer } from './offline-native-audio-processing-docker-runtime'
import {
  OFFLINE_NATIVE_AUDIO_PROCESSING_CONTAINER_PROTOCOL, OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS,
  OFFLINE_NATIVE_AUDIO_PROCESSING_PACKAGE_IDENTITIES, OFFLINE_NATIVE_AUDIO_PROCESSING_TOOL_IDS,
  offlineNativeAudioProcessingRequestSha256, validateOfflineNativeAudioProcessingRequest,
} from './offline-native-audio-processing-protocol'
import type { OfflineNativeAudioProcessingExecutionResult, OfflineNativeAudioProcessingImageEvidence, OfflineNativeAudioProcessingRuntimeAuthority } from './offline-native-audio-processing-types'

export const OFFLINE_NATIVE_AUDIO_PROCESSING_STORAGE_ROOT = '/tmp/reeditpro-offline-native-audio-processing-execution' as const
export const OFFLINE_NATIVE_AUDIO_PROCESSING_AUTHORITY_PATH = 'runtime-authority/offline-native-audio-processing-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'These exact operations are confined private/local fixture evidence; arbitrary user audio ingestion, segmentation, metadata preservation, distributed worker identity, multi-architecture images, scanning, observability, recovery, and deployment remain separate gates.',
  'RNNoise and the embedded model still require recorded dependency, model, security, output-quality, and production license review before product or production promotion.',
  'Signalsmith Stretch still requires recorded dependency, adapter, security, output-quality, and production license review before product or production promotion.',
] as const)

export interface PrivateOfflineNativeAudioProcessingRuntime { readonly image: OfflineNativeAudioProcessingImageEvidence; execute(value: unknown): Promise<OfflineNativeAudioProcessingExecutionResult> }
export async function activatePrivateOfflineNativeAudioProcessingRuntime(): Promise<PrivateOfflineNativeAudioProcessingRuntime> { if (arguments.length !== 0) throw invalid('Native audio processing runtime activation accepts no caller input.'); const image = await inspectExistingOfflineNativeAudioProcessingDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineNativeAudioProcessingRuntime(): Promise<PrivateOfflineNativeAudioProcessingRuntime> { if (arguments.length !== 0) throw invalid('Native audio processing runtime open accepts no caller input.'); const authority = await readPersistedOfflineNativeAudioProcessingRuntimeAuthority(); if (!authority) throw notReady('Verified private native audio processing runtime authority is unavailable.'); const image = await inspectExistingOfflineNativeAudioProcessingDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private native audio processing image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineNativeAudioProcessing(value: unknown): Promise<OfflineNativeAudioProcessingExecutionResult> { return executeWithImage(await inspectExistingOfflineNativeAudioProcessingDockerRuntime(), value) }
export async function readPersistedOfflineNativeAudioProcessingRuntimeAuthority(): Promise<OfflineNativeAudioProcessingRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_NATIVE_AUDIO_PROCESSING_STORAGE_ROOT, relativePath: OFFLINE_NATIVE_AUDIO_PROCESSING_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private native audio processing authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-native-audio-processing-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_native_audio_processing_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private native audio processing authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-native-audio-processing-runtime-authority-v1' || authority.source !== 'private_local_offline_native_audio_processing_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private native audio processing authority boundary is invalid.')
  return authority as unknown as OfflineNativeAudioProcessingRuntimeAuthority
}
async function executeWithImage(image: OfflineNativeAudioProcessingImageEvidence, value: unknown): Promise<OfflineNativeAudioProcessingExecutionResult> {
  const request = validateOfflineNativeAudioProcessingRequest(value); const result = await runOfflineNativeAudioProcessingContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private native audio processing execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_NATIVE_AUDIO_PROCESSING_PACKAGE_IDENTITIES[request.toolId]
  if (response.schemaVersion !== OFFLINE_NATIVE_AUDIO_PROCESSING_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_native_audio_processing_operation_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || response.requestEnvelopeSha256 !== offlineNativeAudioProcessingRequestSha256(request) || artifact.mimeType !== 'audio/wav' || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 44 || bytes.length > 8 * 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private native audio processing result identity is invalid.')
  validateWav(bytes, request.toolId === 'rnnoise' ? 47520 : 60000); validateSemanticEvidence(request.toolId, semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private native audio processing semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-native-audio-processing-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineNativeAudioProcessingRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_NATIVE_AUDIO_PROCESSING_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-native-audio-processing-execution-attestation-record-v1', source: 'private_local_checksum_protected_native_audio_processing_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-native-audio-processing-execution-result-v1', request, artifact: { mimeType: 'audio/wav', bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(toolId: keyof typeof OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS, evidence: Record<string, unknown>): void {
  if (evidence.actualPackageEntrypointExecuted !== true || evidence.zeroNetworkRuntimeRequired !== true) throw notReady('Private native audio processing semantic evidence is invalid.')
  if (toolId === 'rnnoise' && (evidence.entrypoint !== 'rnnoise_demo' || evidence.embeddedModelVersion !== '0b50c45' || evidence.embeddedModelHashVerifiedAtBuild !== true || evidence.denoiseExecuted !== true || evidence.inputFrames !== 48000 || evidence.outputFrames !== 47520 || evidence.algorithmicLatencyFrames !== 480 || evidence.noiseReductionVerified !== true || evidence.voiceEnergyPreserved !== true || evidence.preserveVoicePolicyApplied !== true || !positiveNumber(evidence.inputNoiseRms) || !positiveNumber(evidence.outputNoiseRms) || !positiveNumber(evidence.outputVoiceRms) || Number(evidence.outputNoiseRms) >= Number(evidence.inputNoiseRms) || Number(evidence.outputVoiceRms) <= Number(evidence.outputNoiseRms) * 10)) throw notReady('RNNoise execution evidence is invalid.')
  if (toolId === 'signalsmith_stretch' && (evidence.entrypoint !== 'SignalsmithStretch.process' || evidence.timeStretchExecuted !== true || evidence.pitchShiftSemitones !== 0 || evidence.speedRatio !== 1.25 || evidence.exactLengthApplied !== true || evidence.inputFrames !== 48000 || evidence.outputFrames !== 60000 || !positiveNumber(evidence.outputRms))) throw notReady('Signalsmith Stretch execution evidence is invalid.')
}
function validateWav(bytes: Buffer, frames: number): void { if (bytes.length !== 44 + frames * 2 || bytes.subarray(0, 4).toString('ascii') !== 'RIFF' || bytes.readUInt32LE(4) !== bytes.length - 8 || bytes.subarray(8, 12).toString('ascii') !== 'WAVE' || bytes.subarray(12, 16).toString('ascii') !== 'fmt ' || bytes.readUInt32LE(16) !== 16 || bytes.readUInt16LE(20) !== 1 || bytes.readUInt16LE(22) !== 1 || bytes.readUInt32LE(24) !== 48000 || bytes.readUInt32LE(28) !== 96000 || bytes.readUInt16LE(32) !== 2 || bytes.readUInt16LE(34) !== 16 || bytes.subarray(36, 40).toString('ascii') !== 'data' || bytes.readUInt32LE(40) !== frames * 2) throw notReady('Native audio processing WAV artifact is invalid.') }
async function persistAuthority(image: OfflineNativeAudioProcessingImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-native-audio-processing-runtime-authority-v1' as const, source: 'private_local_offline_native_audio_processing_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_NATIVE_AUDIO_PROCESSING_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_NATIVE_AUDIO_PROCESSING_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineNativeAudioProcessingRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_NATIVE_AUDIO_PROCESSING_STORAGE_ROOT, relativePath: OFFLINE_NATIVE_AUDIO_PROCESSING_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-native-audio-processing-runtime-authority-record-v1', source: 'private_local_checksum_protected_native_audio_processing_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private native audio processing response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private native audio processing response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private native audio processing response contains an invalid string.'); return value }
function positiveNumber(value: unknown): value is number { return typeof value === 'number' && Number.isFinite(value) && value > 0 }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
