import type { OfflineNativeAudioProcessingRequest, OfflineNativeAudioProcessingToolId } from './offline-native-audio-processing-protocol'

export interface OfflineNativeAudioProcessingImageEvidence { imageTag: 'reeditpro-offline-native-audio-processing-execution:private-local-v1'; imageId: string; imageIdentityHash: string; pinnedBaseImage: 'python:3.13.11-slim-bookworm@sha256:20080e807bfc404f8450b185cf0fc95d553462673598549613735f70a5b4d5d0'; debianSnapshot: '20260623T000000Z'; sourceHashes: Readonly<Record<string, string>>; imageUser: '10001:10001'; imageEntrypoint: readonly ['python', '-s', '/app/runner.py']; imageEnvironmentNames: readonly string[]; rootFilesystemLayerDigests: readonly string[]; labels: Readonly<Record<string, string>> }
export interface OfflineNativeAudioProcessingConfinementEvidence { networkMode: 'none'; readOnlyRootFilesystem: true; capDropAll: true; noNewPrivileges: true; privileged: false; pidsLimit: 128; memoryLimitBytes: 1073741824; memoryAndSwapLimitBytes: 1073741824; nanoCpus: 2000000000; tmpfsPath: '/tmp'; tmpfsSizeBytes: 268435456; tmpfsNoExec: true; tmpfsNoSuid: true; tmpfsNoDevice: true; user: '10001:10001'; callerCommandPresent: false; callerBindsPresent: false; callerMountsPresent: false; callerEnvironmentPresent: false; secretLikeImageEnvironmentNames: readonly [] }
export interface OfflineNativeAudioProcessingExecutionResult {
  schemaVersion: 'offline-native-audio-processing-execution-result-v1'; request: OfflineNativeAudioProcessingRequest
  artifact: { mimeType: 'audio/wav'; bytes: Buffer; byteLength: number; sha256: string }
  evidence: { packageName: string; packageVersion: string; requestEnvelopeSha256: string; image: OfflineNativeAudioProcessingImageEvidence; confinement: OfflineNativeAudioProcessingConfinementEvidence; semanticEvidence: Readonly<Record<string, boolean | number | string>>; containerExitCode: 0; oomKilled: false }
  attestation: { schemaVersion: 'offline-native-audio-processing-execution-attestation-v1'; recordId: string; completedAt: string; toolId: OfflineNativeAudioProcessingToolId; imageIdentityHash: string; requestEnvelopeSha256: string; artifactSha256: string; confinementHash: string; attestationHash: string }
  readiness: { privateInternalOnly: true; exactStructuredPayloadOnly: true; canonicalDispatchIntegrated: false; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }
}
export interface OfflineNativeAudioProcessingRuntimeAuthority { schemaVersion: 'offline-native-audio-processing-runtime-authority-v1'; source: 'private_local_offline_native_audio_processing_runtime_authority'; activatedAt: string; image: OfflineNativeAudioProcessingImageEvidence; supportedOperations: readonly { toolId: OfflineNativeAudioProcessingToolId; operationId: string }[]; readiness: { privateInternalExecutionReady: true; exactStructuredPayloadOnly: true; canonicalDispatchMayReference: true; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }; blockers: readonly string[]; authorityHash: string }
