import {
  SAM2_CHECKPOINT_FILE_NAME,
  SAM2_CHECKPOINT_SOURCE_URL,
  SAM2_CONFIG_FILE_NAME,
  SAM2_CONFIG_SOURCE_URL,
  SAM2_MODEL_DOWNLOAD_GCS_PATH,
  SAM2_MODEL_DOWNLOAD_LOCAL_DIR,
  SAM2_MODEL_DOWNLOAD_TEMP_ROOT,
  sam2ModelDownloadExecutionDoesNotDo,
} from './sam2-model-download-policy'
import type { Sam2DownloadExecutionCommandPlan } from './sam2-model-download-types'

export function buildSam2ModelDownloadExecutionCommandPlans(): Sam2DownloadExecutionCommandPlan[] {
  return [
    {
      commandId: 'sam2_model_download_preflight',
      phase: 'preflight',
      commandString: [
        'gcloud auth list',
        'gcloud config get-value project',
        'gcloud projects describe reeditpro',
        'gcloud storage buckets describe gs://reeditpro-staging-reeditpro-generated-assets',
        'gcloud storage objects list gs://reeditpro-staging-reeditpro-generated-assets/model-weights/sam2/ --recursive --limit=20 || true',
      ].join(' && '),
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Read-only preflight commands; do not proceed unless project/env/source guards pass.'],
    },
    {
      commandId: 'sam2_model_source_license_verify',
      phase: 'source_evidence',
      commandString: 'TEXT_ONLY source/license verification runs inside the Phase 35B CLI before download.',
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Stops before download if official source/license evidence is unclear.'],
    },
    {
      commandId: 'sam2_model_download_checkpoint',
      phase: 'download',
      commandString: [
        'REEDITPRO_CONFIRM_SAM2_MODEL_DOWNLOAD=true',
        'curl -fL',
        `-o ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/${SAM2_CHECKPOINT_FILE_NAME}`,
        SAM2_CHECKPOINT_SOURCE_URL,
      ].join(' '),
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_SAM2_MODEL_DOWNLOAD',
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Execute only in Phase 35B after preflight; temp path is outside repo.'],
    },
    {
      commandId: 'sam2_model_download_config',
      phase: 'download',
      commandString: [
        'REEDITPRO_CONFIRM_SAM2_MODEL_DOWNLOAD=true',
        'curl -fL',
        `-o ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/${SAM2_CONFIG_FILE_NAME}`,
        SAM2_CONFIG_SOURCE_URL,
      ].join(' '),
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_SAM2_MODEL_DOWNLOAD',
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Download only the approved SAM2.1 tiny config; do not download repo code or other checkpoints.'],
    },
    {
      commandId: 'sam2_model_download_checksums',
      phase: 'checksum',
      commandString: `cd ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR} && shasum -a 256 ${SAM2_CHECKPOINT_FILE_NAME} ${SAM2_CONFIG_FILE_NAME} > file_checksums_sha256.txt`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Checksum output must use sanitized relative paths in tracked reports.'],
    },
    {
      commandId: 'sam2_model_download_upload_to_gcs',
      phase: 'upload',
      commandString: `gcloud storage cp ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/${SAM2_CHECKPOINT_FILE_NAME} ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/${SAM2_CONFIG_FILE_NAME} ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/file_checksums_sha256.txt ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/model_tree_manifest.json ${SAM2_MODEL_DOWNLOAD_LOCAL_DIR}/source_evidence.json ${SAM2_MODEL_DOWNLOAD_GCS_PATH}`,
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_SAM2_MODEL_DOWNLOAD',
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Upload only to the private generated-assets SAM2.1 tiny model-weight prefix.'],
    },
    {
      commandId: 'sam2_model_download_verify_gcs',
      phase: 'verify',
      commandString: `gcloud storage objects describe ${SAM2_MODEL_DOWNLOAD_GCS_PATH}${SAM2_CHECKPOINT_FILE_NAME} ${SAM2_MODEL_DOWNLOAD_GCS_PATH}${SAM2_CONFIG_FILE_NAME} ${SAM2_MODEL_DOWNLOAD_GCS_PATH}file_checksums_sha256.txt ${SAM2_MODEL_DOWNLOAD_GCS_PATH}model_tree_manifest.json ${SAM2_MODEL_DOWNLOAD_GCS_PATH}source_evidence.json`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Verification is read-only and must not create signed URLs.'],
    },
    {
      commandId: 'sam2_model_download_cleanup_temp',
      phase: 'cleanup',
      commandString: `rm -rf ${SAM2_MODEL_DOWNLOAD_TEMP_ROOT}/sam2.1-hiera-tiny`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...sam2ModelDownloadExecutionDoesNotDo],
      warnings: ['Remove local temp model files after upload and verification.'],
    },
  ]
}
