import type { ZodType } from 'zod'

import { ApiError } from '../errors/api-error'
import { buildOfflineContainerPackagingValidationApprovedRequest, openPrivateOfflineContainerPackagingValidationRuntime, readPersistedOfflineContainerPackagingValidationRuntimeAuthority, type OfflineContainerPackagingValidationExecutionResult } from '../tool-execution/container-packaging-validation-execution'
import type { ServiceContext } from '../types'
import { canonicalPrivateContainerPackagingValidationAuthoritySchema, canonicalPrivateContainerPackagingValidationResponseSchema, runCanonicalPrivateContainerPackagingValidationSchema, type CanonicalPrivateContainerPackagingValidationAuthority, type CanonicalPrivateContainerPackagingValidationResponse, type RunCanonicalPrivateContainerPackagingValidationInput } from '../validation/canonical-private-container-packaging-validation-execution-schemas'
import type { CanonicalExpectedArtifactLineage, PersistedArtifactResult } from '../validation/private-artifact-qa-authority-schemas'
import { createCanonicalExecutionReadinessService } from './canonical-execution-readiness-service'
import { persistCanonicalStructuredJsonArtifact, readCanonicalStructuredJsonArtifact } from './canonical-structured-json-artifact-storage'
import { createCanonicalPrivateToolDispatchAuthorityService } from './canonical-private-tool-dispatch-authority-service'
import { createCanonicalWorkerLeaseAuthorityService } from './canonical-worker-lease-authority-service'
import { createEditPlanningAuthorityService } from './edit-planning-authority-service'
import { createPrivateArtifactQaAuthorityService, type ServerInjectedArtifactQaAdapter, type ServerInjectedArtifactResultAdapter } from './private-artifact-qa-authority-service'
import { sha256ArtifactQaValue, stableArtifactQaStringify } from './private-artifact-qa-authority-store'
import { sha256AuthorityValue } from './private-edit-authority-store'
import { getRequiredAuthUserId } from './service-helpers'
import { authorizeWorkspaceAccess } from './workspace-access-service'

const RUNNER_CLASS = 'offline_container_packaging_validation_execution_v1' as const
const EDIT_TOOL_IDS = ['mkvtoolnix_container_validation', 'gpac_mp4box_packaging_validation'] as const
const CONTENT_TYPE = 'application/json' as const

export function createCanonicalPrivateContainerPackagingValidationExecutionService(context: ServiceContext) {
  return { async execute(input: RunCanonicalPrivateContainerPackagingValidationInput, serverAuthority: CanonicalPrivateContainerPackagingValidationAuthority): Promise<CanonicalPrivateContainerPackagingValidationResponse> {
    const body = parse(runCanonicalPrivateContainerPackagingValidationSchema, input, 'Container packaging validation execution identity is invalid.'); const injected = parse(canonicalPrivateContainerPackagingValidationAuthoritySchema, serverAuthority, 'Container packaging validation execution authority is invalid.')
    const actor = getRequiredAuthUserId(context); const access = await authorizeWorkspaceAccess(context, body.workspaceId, 'write'); if (actor !== access.userId) throw denied('Container packaging validation actor is outside this workspace.')
    const dispatch = (await createCanonicalPrivateToolDispatchAuthorityService(context).consume({ workspaceId: body.workspaceId, projectId: body.projectId, editSessionId: body.editSessionId, jobId: body.jobId, grantId: body.grantId, purpose: 'private_internal_canonical_tool_dispatch_consume', idempotencyKey: body.idempotencyKey }, injected)).toolDispatchConsumption; const binding = dispatch.grant.binding
    if (!(EDIT_TOOL_IDS as readonly string[]).includes(binding.canonicalToolId) || binding.leaseId !== injected.leaseId || binding.jobId !== body.jobId || binding.workspaceId !== body.workspaceId || binding.projectId !== body.projectId || binding.editSessionId !== body.editSessionId || (!dispatch.executionAuthority.newExecutionStartAuthorized && !dispatch.executionAuthority.resumeSameIdempotentAttemptOnly)) throw denied('Consumed dispatch grant does not match container packaging validation execution identity.')
    const readiness = (await createCanonicalExecutionReadinessService(context).inspectJob({ workspaceId: body.workspaceId, projectId: body.projectId, editSessionId: body.editSessionId, jobId: body.jobId, purpose: 'private_internal_dry_run_readiness' })).executionReadinessEnvelope
    const planning = createEditPlanningAuthorityService(context); const authority = await planning.loadApprovedExecutionAuthority(readiness.job.approvedPlanSnapshotId, access.workspaceId); const beforeHash = sha256AuthorityValue(authority)
    const workItem = authority.workItems.find((candidate) => candidate.id === binding.approvedWorkItemId); const expectedAsset = authority.assetManifest.entries.find((candidate) => candidate.id === binding.expectedAssetId && candidate.approvedWorkItemId === workItem?.id); if (!workItem || !expectedAsset) throw denied('Container packaging validation work-item or output lineage is missing.')
    const request = buildOfflineContainerPackagingValidationApprovedRequest({ toolId: binding.canonicalToolId as (typeof EDIT_TOOL_IDS)[number], operationId: binding.operationId, planningPayload: workItem.executionInput.structuredPayload })
    if (expectedAsset.contentType !== CONTENT_TYPE || binding.expectedOutput.contentType !== CONTENT_TYPE || expectedAsset.assetRole === 'final' || expectedAsset.previewPlaceholderAllowed || binding.expectedOutput.outputKey !== expectedAsset.outputKey || readiness.job.approvedWorkItemId !== workItem.id || binding.approvedPlanSnapshotId !== authority.snapshot.snapshotId || workItem.sourceSequenceItemIds.length !== 0 || workItem.dependencyKeys.length !== 0) throw denied('Container packaging validation execution is limited to the exact approved dependency-free non-final fixture output.')
    const runtimeAuthority = await readPersistedOfflineContainerPackagingValidationRuntimeAuthority(); if (!runtimeAuthority || !runtimeAuthority.readiness.privateInternalExecutionReady || runtimeAuthority.readiness.productReady || !runtimeAuthority.readiness.licenseReviewStillRequiredForProduction || !runtimeAuthority.supportedOperations.some((operation) => operation.toolId === request.toolId && operation.operationId === request.operationId)) throw denied('Container packaging validation runtime authority changed after dispatch.')
    const runtime = await openPrivateOfflineContainerPackagingValidationRuntime(); if (runtime.image.imageIdentityHash !== runtimeAuthority.image.imageIdentityHash) throw denied('Opened container packaging validation image does not match dispatch-time authority.')
    const leaseService = createCanonicalWorkerLeaseAuthorityService(context); const begun = await leaseService.beginInternalExecution({ workspaceId: body.workspaceId, projectId: body.projectId, editSessionId: body.editSessionId, jobId: body.jobId, leaseId: injected.leaseId, leaseCredential: injected.leaseCredential, runnerClass: RUNNER_CLASS }); const executionAttemptId = begun.executionFence.executionAttemptId
    const result = await runtime.execute(request); assertExecutionResult(result, request.toolId, request.operationId)
    const privateObjectIdentityHash = sha256ArtifactQaValue({ domain: 'canonical_private_container_packaging_validation_json_v1', workspaceId: body.workspaceId, snapshotId: authority.snapshot.snapshotId, jobId: body.jobId, expectedAssetId: expectedAsset.id, dispatchGrantId: body.grantId, executionAttemptId, contentSha256: result.artifact.sha256 })
    await persistCanonicalStructuredJsonArtifact({ localStorageRoot: context.env.localStorageRoot, privateObjectIdentityHash, bytes: result.artifact.bytes, expectedSha256: result.artifact.sha256 })
    const identity = { workspaceId: body.workspaceId, projectId: body.projectId, editSessionId: body.editSessionId, snapshotId: authority.snapshot.snapshotId, jobId: body.jobId, expectedAssetId: expectedAsset.id }
    const lineage: CanonicalExpectedArtifactLineage = { assetId: expectedAsset.id, outputKey: expectedAsset.outputKey, artifactType: expectedAsset.artifactType, assetRole: expectedAsset.assetRole, required: expectedAsset.required, previewPlaceholderAllowed: expectedAsset.previewPlaceholderAllowed, contentType: CONTENT_TYPE, segmentIds: [...expectedAsset.segmentIds], timingIds: [...expectedAsset.timingIds], rendererLayerIds: [...expectedAsset.rendererLayerIds], approvedWorkItemId: workItem.id, workItemKey: workItem.workItemKey, jobType: workItem.workItemType, jobAuthorityHash: readiness.authorityHashes.jobAuthorityHash, snapshotHash: readiness.authorityHashes.snapshotHash, approvedAssetManifestHash: readiness.authorityHashes.approvedAssetManifestHash }
    const adapterInput: AdapterInput = { localStorageRoot: context.env.localStorageRoot, identity, lineage, privateObjectIdentityHash, executionAttemptId, dispatchGrantId: body.grantId, runtimeAuthorityHash: runtimeAuthority.authorityHash, executionStartedAt: begun.executionFence.startedAt, result }
    const artifactAuthority = createPrivateArtifactQaAuthorityService(context, adapters(adapterInput)); const keyHash = sha256ArtifactQaValue({ domain: 'canonical_container_packaging_validation_idempotency_v1', body, executionAttemptId })
    const artifactResult = await artifactAuthority.recordArtifactResult({ ...identity, idempotencyKey: key('packaging-artifact', keyHash), purpose: 'record_server_verified_internal_artifact_result' }); const qaResult = await artifactAuthority.recordArtifactQa({ ...identity, artifactId: artifactResult.artifact.artifactId, idempotencyKey: key('packaging-qa', keyHash), purpose: 'record_server_verified_internal_artifact_qa' })
    const completed = await leaseService.completeInternalExecution({ workspaceId: body.workspaceId, projectId: body.projectId, editSessionId: body.editSessionId, jobId: body.jobId, leaseId: injected.leaseId, leaseCredential: injected.leaseCredential, runnerClass: RUNNER_CLASS, executionAttemptId }); const reconciliation = await artifactAuthority.reconcileArtifact({ ...identity, artifactId: artifactResult.artifact.artifactId, idempotencyKey: key('packaging-reconcile', keyHash), purpose: 'reconcile_server_verified_internal_artifact' })
    if (qaResult.qaEvaluation.outcome !== 'passed' || reconciliation.reconciliation.decision !== 'test_merged_not_live_authorized' || !reconciliation.reconciliation.privateTestDependencySatisfied || !completed.executionFence.commitAuthorizedAt || !completed.executionFence.completedAt) throw new ApiError('JOB_DEPENDENCY_NOT_READY', 'Container packaging validation output failed QA or reconciliation.', 409)
    if (sha256AuthorityValue(await planning.loadApprovedExecutionAuthority(authority.snapshot.snapshotId, access.workspaceId)) !== beforeHash) throw denied('Canonical authority changed during container packaging validation execution.')
    const container = request.toolId === 'mkvtoolnix_container_validation' ? 'mkv' as const : 'mp4' as const
    const responseWithoutHash = {
      schemaVersion: 'canonical-private-container-packaging-validation-execution-response-v1' as const, source: 'canonical_private_container_packaging_validation_execution_coordinator' as const, purpose: body.purpose,
      identity: { ...identity, approvedWorkItemId: workItem.id, dispatchGrantId: body.grantId }, tool: { canonicalToolId: request.toolId as (typeof EDIT_TOOL_IDS)[number], operationId: request.operationId, actualPackageEntrypointCompleted: true as const, approvedServerOwnedFixtureOnly: true as const, licenseReviewStillRequiredForProduction: true as const, providerCallMade: false as const, sourceObjectRead: false as const, renderExecuted: false as const, finalExportExecuted: false as const },
      lease: { leaseId: begun.lease.id, attemptNumber: begun.lease.attemptNumber, immutableLeaseHash: begun.lease.immutableLeaseHash, executionAttemptId, runnerClass: RUNNER_CLASS, executionStartedAt: completed.executionFence.startedAt, executionCommitAuthorizedAt: completed.executionFence.commitAuthorizedAt, executionCompletedAt: completed.executionFence.completedAt, credentialReturned: false as const, credentialHashReturned: false as const },
      runtime: { runtimeAuthorityHash: runtimeAuthority.authorityHash, imageIdentityHash: runtime.image.imageIdentityHash, executionAttestationHash: result.attestation.attestationHash, requestEnvelopeSha256: result.evidence.requestEnvelopeSha256, packageName: result.evidence.packageName, packageVersion: result.evidence.packageVersion, debianSnapshot: '20260623T000000Z' as const, zeroNetworkVerified: true as const, privateInternalOnly: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const },
      result: { artifactId: artifactResult.artifact.artifactId, qaEvaluationId: qaResult.qaEvaluation.qaEvaluationId, reconciliationId: reconciliation.reconciliation.reconciliationId, artifactVersion: artifactResult.artifact.artifactVersion, contentType: CONTENT_TYPE, sha256: artifactResult.artifact.content.sha256, byteLength: artifactResult.artifact.content.byteLength, container, trackCount: 3 as const, videoTrackVerified: true as const, audioTrackVerified: true as const, captionTrackVerified: true as const, privateObjectIdentityHash: artifactResult.artifact.storageIdentity.opaqueObjectIdentityHash, qaOutcome: 'passed' as const, reconciliationDecision: 'test_merged_not_live_authorized' as const, privateTestDependencySatisfied: true as const, liveRuntimeDependencySatisfied: false as const, finalRenderAuthorized: false as const },
      replay: { dispatchConsumptionReplayed: dispatch.consumptionReplayed, executionFenceBeginReplayed: begun.replayed, executionFenceCompleteReplayed: completed.replayed, artifactRecordReplayed: artifactResult.replayed, qaRecordReplayed: qaResult.replayed, reconciliationReplayed: reconciliation.replayed, sameIdempotentAttemptOnly: true as const }, permissions: { furtherWorkerDispatch: false as const, providerCall: false as const, sourceObjectRead: false as const, render: false as const, creditSpend: false as const, walletMutation: false as const, settlement: false as const, delivery: false as const }, persistence: { privateLocalCreateOnlyArtifact: true as const, contentAddressedArtifactAuthority: true as const, actualRunEvidenceVerified: true as const, actualQaEvidenceVerified: true as const, checksumProtectedAuthority: true as const, distributedAuthority: false as const, productionAuthority: false as const }, completedAt: reconciliation.reconciliation.createdAt, testOnly: true as const,
    }
    return canonicalPrivateContainerPackagingValidationResponseSchema.parse({ ...responseWithoutHash, responseHash: sha256AuthorityValue(responseWithoutHash) })
  } }
}
interface AdapterInput { localStorageRoot: string; identity: { workspaceId: string; projectId: string; editSessionId: string; snapshotId: string; jobId: string; expectedAssetId: string }; lineage: CanonicalExpectedArtifactLineage; privateObjectIdentityHash: string; executionAttemptId: string; dispatchGrantId: string; runtimeAuthorityHash: string; executionStartedAt: string; result: OfflineContainerPackagingValidationExecutionResult }
function adapters(input: AdapterInput): { producedArtifact: ServerInjectedArtifactResultAdapter; artifactQa: ServerInjectedArtifactQaAdapter } { return {
  producedArtifact: { adapterKind: 'server_injected_internal_artifact_adapter', async collectProducedArtifact(adapterInput) { assertLineage(adapterInput.identity, adapterInput.lineage, input); await assertStored(input); return { schemaVersion: 'server-internal-produced-artifact-evidence-v1' as const, evidenceOrigin: 'server_injected_internal_artifact_adapter' as const, evidenceClass: 'private_internal_test_attested' as const, artifactVersion: 1, attemptKind: 'initial' as const, content: { sha256: input.result.artifact.sha256, byteLength: input.result.artifact.byteLength, contentType: CONTENT_TYPE }, storageIdentity: { storageKind: 'private_local_test' as const, opaqueObjectIdentityHash: input.privateObjectIdentityHash }, placeholder: { isPlaceholder: false, scope: 'none' as const }, actualRunEvidence: { state: 'actual_run_evidence_verified_v2' as const, executionAttemptId: input.executionAttemptId, runnerClass: RUNNER_CLASS, runnerEvidenceHash: sha256ArtifactQaValue(input.result.evidence), startedAt: input.executionStartedAt, finishedAt: input.result.attestation.completedAt, exitCode: 0 as const, toolIds: [input.result.request.toolId], actualRunVerified: true as const, dispatchGrantId: input.dispatchGrantId, runtimeAuthorityHash: input.runtimeAuthorityHash, runtimeImageIdentityHash: input.result.attestation.imageIdentityHash, executionAttestationHash: input.result.attestation.attestationHash }, completedAt: input.result.attestation.completedAt } } },
  artifactQa: { adapterKind: 'server_injected_internal_qa_adapter', async evaluateArtifact(adapterInput) { assertLineage(adapterInput.identity, adapterInput.lineage, input); assertArtifact(adapterInput.artifact, input); await assertStored(input); return { schemaVersion: 'server-internal-artifact-qa-evidence-v1' as const, evidenceOrigin: 'server_injected_internal_qa_adapter' as const, evidenceClass: 'private_internal_test_attested' as const, gateResults: [{ gateId: 'asset_received_gate' as const, category: 'asset_integrity' as const, status: 'passed' as const, failureScope: 'none' as const, evidenceHash: sha256ArtifactQaValue({ content: adapterInput.artifact.content, storage: adapterInput.artifact.storageIdentity }), notesCode: 'container_packaging_validation_json_hash_size_structure_storage_match' }, { gateId: 'asset_quality_gate' as const, category: 'model_tier_policy' as const, status: 'passed' as const, failureScope: 'none' as const, evidenceHash: sha256ArtifactQaValue(input.result.evidence.semanticEvidence), notesCode: 'actual_container_packaging_validation_semantic_qa_passed' }], recovery: { state: 'none' as const, action: 'none' as const, approvedWithinSnapshot: true, reasonCode: 'container_packaging_validation_pass_no_recovery' }, evaluatedAt: new Date().toISOString(), actualQaEvidenceState: 'actual_structured_json_qa_verified_v1' as const, actualQaVerified: true as const } } },
} }
async function assertStored(input: AdapterInput) { const stored = await readCanonicalStructuredJsonArtifact({ localStorageRoot: input.localStorageRoot, privateObjectIdentityHash: input.privateObjectIdentityHash }); if (!stored || stored.sha256 !== input.result.artifact.sha256 || stored.byteLength !== input.result.artifact.byteLength || !stored.bytes.equals(input.result.artifact.bytes)) throw denied('Container packaging validation bytes changed before artifact authority.'); return stored }
function assertExecutionResult(result: OfflineContainerPackagingValidationExecutionResult, toolId: string, operationId: string) { if (result.request.toolId !== toolId || result.request.operationId !== operationId || result.artifact.mimeType !== CONTENT_TYPE || result.evidence.semanticEvidence.actualPackageEntrypointExecuted !== true || result.evidence.semanticEvidence.zeroNetworkRuntimeRequired !== true || result.readiness.productReady || !result.readiness.licenseReviewStillRequiredForProduction) throw denied('Container packaging validation result failed exact operation verification.') }
function assertLineage(identity: Record<string, unknown>, lineage: CanonicalExpectedArtifactLineage, input: AdapterInput) { if (stableArtifactQaStringify(identity) !== stableArtifactQaStringify(input.identity) || stableArtifactQaStringify(lineage) !== stableArtifactQaStringify(input.lineage)) throw denied('Container packaging validation adapter lineage changed.') }
function assertArtifact(artifact: PersistedArtifactResult, input: AdapterInput) { if (artifact.content.sha256 !== input.result.artifact.sha256 || artifact.content.byteLength !== input.result.artifact.byteLength || artifact.content.contentType !== CONTENT_TYPE || artifact.storageIdentity.opaqueObjectIdentityHash !== input.privateObjectIdentityHash || artifact.actualRunEvidence.state !== 'actual_run_evidence_verified_v2' || artifact.actualRunEvidence.runnerClass !== RUNNER_CLASS || artifact.actualRunEvidence.dispatchGrantId !== input.dispatchGrantId) throw denied('Persisted container packaging validation artifact does not match actual-run evidence.') }
function parse<T>(schema: ZodType<T>, value: unknown, message: string): T { const parsed = schema.safeParse(value); if (!parsed.success) throw new ApiError('VALIDATION_FAILED', message, 400, parsed.error.flatten()); return parsed.data }
function key(prefix: string, hash: string) { return `${prefix}-${hash.slice(0, 52)}` }
function denied(message: string) { return new ApiError('TOOL_NOT_READY', message, 409, { requiredGate: 'canonical_private_container_packaging_validation_execution_authority' }) }
