import type { VlmBlockerResolutionCommandPlan } from './vlm-blocker-resolution-types'

export function buildVlmBlockerResolutionCommandPlans(): VlmBlockerResolutionCommandPlan[] {
  return [
    {
      commandId: 'phase47b-preflight-report-only',
      phase: 'preflight',
      commandString: [
        'npm run smoke:activation-vlm-blocker-resolution',
        'npm run activation:vlm-blocker-resolution:report',
        'npm run activation:vlm-blocker-resolution:iam-plan',
        'npm run activation:track-integration-audit:report',
        'npm run activation:track-a-visual-readiness-closure:report',
        'npm run activation:vlm-runtime:report || true',
        'npm run activation:qwen-vlm-runtime:report || true',
        'npm run activation:visual-intelligence-runtime:report || true',
        'npm run prod:readiness:summary',
        'npm run prod:beta:summary',
      ].join(' && '),
      requiresConfirmation: false,
      textOnlyByDefault: true,
      warnings: ['Report mode is static and non-mutating.'],
    },
    {
      commandId: 'phase47b-execute-vlm-exclusion',
      phase: 'execute',
      commandString: [
        'GCP_PROJECT_ID=reeditpro',
        'GCP_REGION=us-central1',
        'REEDITPRO_ENV=staging',
        'REEDITPRO_CONFIRM_VLM_BLOCKER_RESOLUTION=true',
        'PROVIDER_EXECUTION_ENABLED=false',
        'REVIDEO_ENABLED=false',
        'PUBLIC_ACCESS_ENABLED=false',
        'FINAL_DELIVERY_ENABLED=false',
        'MEDIA_PROCESSING_ENABLED=false',
        'DOCKER_EXECUTION_ENABLED=false',
        'CLOUD_RUN_EXECUTION_ENABLED=false',
        'MODEL_DOWNLOAD_ENABLED=false',
        'REEDITPRO_PRODUCTION_READY=false',
        'REEDITPRO_EXTERNAL_BETA_READY=false',
        'REEDITPRO_PAID_PRODUCTION_READY=false',
        'REEDITPRO_BROAD_REAL_MEDIA_READY=false',
        'npm run activation:vlm-blocker-resolution -- --execute',
      ].join(' '),
      requiresConfirmation: true,
      textOnlyByDefault: true,
      warnings: [
        'Uploads private JSON blocker/exclusion artifacts only.',
        'Does not retry vLLM, run Docker, deploy Cloud Run, download models, process media, call providers, or enable VLM for initial internal testing.',
      ],
    },
    {
      commandId: 'phase47b-post-validation',
      phase: 'validation',
      commandString: [
        'npm run activation:vlm-blocker-resolution:report',
        'npm run smoke:activation-vlm-blocker-resolution',
        'npm run activation:track-integration-audit:report',
        'npm run activation:track-a-visual-readiness-closure:report',
        'npm run activation:vlm-runtime:report || true',
        'npm run activation:qwen-vlm-runtime:report || true',
        'npm run activation:visual-intelligence-runtime:report || true',
        'npm run prod:readiness:summary',
        'npm run prod:beta:summary',
        'npm run lint',
        'npm run build',
        'npm run build:server',
        'git diff --check',
      ].join(' && '),
      requiresConfirmation: false,
      textOnlyByDefault: true,
      warnings: ['Build/lint validation only; no model/runtime/media execution.'],
    },
  ]
}
