export type SupabaseStagingResetFailureTriageDecision =
  | 'recovery_path_retry_reset_after_fix'
  | 'recovery_path_restore_backup_then_retry'
  | 'recovery_path_ordered_migration_apply_without_reset'
  | 'recovery_path_manual_operator_review_required'
  | 'recovery_path_blocked_pending_supabase_support_or_cli_issue'
  | 'recovery_path_rejected_due_staging_data_risk'

export type SupabaseStagingResetFailureTriageBlocker =
  | 'pr259_reset_execution_report_missing'
  | 'pr259_reset_failure_evidence_missing'
  | 'pr259_post_verify_report_missing'
  | 'pr259_schema_rls_verify_report_missing'
  | 'reset_failure_cause_not_proven'
  | 'staging_reset_failed'
  | 'staging_sql_may_have_run'
  | 'staging_post_reset_migration_history_verify_failed'
  | 'staging_post_reset_schema_rls_verify_failed'
  | 'registry_migration_not_applied'
  | 'registry_schema_absent_after_failed_reset'
  | 'backup_restore_scope_not_proven'
  | 'manual_operator_review_required'
  | 'future_recovery_execution_approval_required'
  | 'staging_reset_failure_triage_not_confirmed'
  | 'staging_schema_readonly_inspection_not_confirmed'
  | 'staging_migration_history_audit_not_confirmed'
  | 'staging_db_url_unavailable_for_failure_triage'
  | 'staging_db_url_target_ref_mismatch'
  | 'staging_db_url_unparseable'
  | 'psql_unavailable_for_failure_triage'
  | 'readonly_failure_triage_query_failed'
  | 'forbidden_confirmation_set'

export type SupabaseStagingResetFailureRecoveryOption =
  | 'retry_reset_after_fix'
  | 'restore_backup_then_retry'
  | 'ordered_migration_apply_without_reset'
  | 'manual_operator_review'
  | 'supabase_support_or_cli_issue'
  | 'reject_due_staging_data_risk'
