import type { WebCapabilityFixture } from './webCapabilityProfileTypes'

const GIB = 1024 * 1024 * 1024

export const WEB_CAPABILITY_FIXTURES: WebCapabilityFixture[] = [
  {
    fixtureId: 'fixture-modern-web-high',
    description: 'Secure, isolated, high-capability browser with WebGPU, WebCodecs, WebGL2, OffscreenCanvas, high concurrency, and large storage.',
    rawSignals: {
      secureContext: true,
      crossOriginIsolated: true,
      workerAvailable: true,
      dedicatedWorkerAvailable: true,
      serviceWorkerAvailable: true,
      offscreenCanvasAvailable: true,
      platformCoarse: 'desktop',
      hardwareConcurrency: 12,
      deviceMemoryGb: 16,
      wasmAvailable: true,
      wasmSimdLikely: true,
      sharedArrayBufferAvailable: true,
      highResolutionTimerAllowed: true,
      webglAvailable: true,
      webgl2Available: true,
      webgpuAvailable: true,
      offscreenCanvas2dAvailable: true,
      offscreenCanvasWebglAvailable: true,
      webCodecsAvailable: true,
      videoEncoderAvailable: true,
      videoDecoderAvailable: true,
      audioEncoderAvailable: true,
      audioDecoderAvailable: true,
      mediaCapabilitiesAvailable: true,
      storageEstimateAvailable: true,
      storageQuotaBytes: 30 * GIB,
      storageUsageBytes: 50 * 1024 * 1024,
      persistentStorageAvailable: true,
      networkInformationAvailable: true,
      effectiveType: '4g',
      saveData: false,
    },
    expectedHints: ['browser_can_assist_preview_metadata', 'webgpu_present_but_unapproved'],
    expectedWarnings: ['webgpu_present_but_unapproved_for_execution', 'webcodecs_present_but_media_processing_blocked'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-mid-web-no-webgpu',
    description: 'Mid-capability browser with WebCodecs and WebGL2 but no WebGPU.',
    rawSignals: {
      secureContext: true,
      crossOriginIsolated: true,
      workerAvailable: true,
      dedicatedWorkerAvailable: true,
      serviceWorkerAvailable: true,
      offscreenCanvasAvailable: true,
      platformCoarse: 'desktop',
      hardwareConcurrency: 6,
      deviceMemoryGb: 8,
      wasmAvailable: true,
      wasmSimdLikely: true,
      sharedArrayBufferAvailable: true,
      highResolutionTimerAllowed: true,
      webglAvailable: true,
      webgl2Available: true,
      webgpuAvailable: false,
      offscreenCanvas2dAvailable: true,
      offscreenCanvasWebglAvailable: true,
      webCodecsAvailable: true,
      videoEncoderAvailable: true,
      videoDecoderAvailable: true,
      audioEncoderAvailable: true,
      audioDecoderAvailable: true,
      mediaCapabilitiesAvailable: true,
      storageEstimateAvailable: true,
      storageQuotaBytes: 8 * GIB,
      storageUsageBytes: 500 * 1024 * 1024,
      persistentStorageAvailable: true,
      networkInformationAvailable: true,
      effectiveType: '4g',
      saveData: false,
    },
    expectedHints: ['web_media_preview_possible', 'gpu_compute_unavailable'],
    expectedWarnings: ['webcodecs_present_but_media_processing_blocked'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-low-capability-mobile',
    description: 'Low-capability mobile-like browser with low compute, low storage, no WebGPU, and no WebCodecs.',
    rawSignals: {
      secureContext: true,
      crossOriginIsolated: false,
      workerAvailable: true,
      dedicatedWorkerAvailable: true,
      serviceWorkerAvailable: false,
      offscreenCanvasAvailable: false,
      platformCoarse: 'mobile',
      hardwareConcurrency: 2,
      deviceMemoryGb: 2,
      wasmAvailable: true,
      wasmSimdLikely: false,
      sharedArrayBufferAvailable: false,
      highResolutionTimerAllowed: false,
      webglAvailable: true,
      webgl2Available: false,
      webgpuAvailable: false,
      offscreenCanvas2dAvailable: false,
      offscreenCanvasWebglAvailable: false,
      webCodecsAvailable: false,
      videoEncoderAvailable: false,
      videoDecoderAvailable: false,
      audioEncoderAvailable: false,
      audioDecoderAvailable: false,
      mediaCapabilitiesAvailable: false,
      storageEstimateAvailable: true,
      storageQuotaBytes: 500 * 1024 * 1024,
      storageUsageBytes: 120 * 1024 * 1024,
      persistentStorageAvailable: false,
      networkInformationAvailable: true,
      effectiveType: '3g',
      saveData: true,
    },
    expectedHints: ['server_worker_preferred', 'avoid_browser_heavy_processing'],
    expectedWarnings: ['shared_memory_unavailable_cross_origin_isolation', 'low_storage_capacity', 'low_compute_capacity'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-cross-origin-not-isolated',
    description: 'Secure browser without cross-origin isolation, so shared memory and wasm threads are unavailable.',
    rawSignals: {
      secureContext: true,
      crossOriginIsolated: false,
      workerAvailable: true,
      dedicatedWorkerAvailable: true,
      serviceWorkerAvailable: true,
      offscreenCanvasAvailable: true,
      platformCoarse: 'desktop',
      hardwareConcurrency: 8,
      deviceMemoryGb: 8,
      wasmAvailable: true,
      wasmSimdLikely: true,
      sharedArrayBufferAvailable: false,
      highResolutionTimerAllowed: false,
      webglAvailable: true,
      webgl2Available: true,
      webgpuAvailable: false,
      offscreenCanvas2dAvailable: true,
      offscreenCanvasWebglAvailable: true,
      webCodecsAvailable: true,
      videoEncoderAvailable: true,
      videoDecoderAvailable: true,
      audioEncoderAvailable: true,
      audioDecoderAvailable: true,
      mediaCapabilitiesAvailable: true,
      storageEstimateAvailable: true,
      storageQuotaBytes: 12 * GIB,
      storageUsageBytes: 80 * 1024 * 1024,
      persistentStorageAvailable: true,
      networkInformationAvailable: true,
      effectiveType: '4g',
      saveData: false,
    },
    expectedHints: ['cross_origin_isolation_required_for_threads'],
    expectedWarnings: ['shared_memory_unavailable_cross_origin_isolation', 'webcodecs_present_but_media_processing_blocked'],
    expectedBlockedReasons: [],
  },
  {
    fixtureId: 'fixture-insecure-context',
    description: 'Insecure context where WebGPU and storage estimate paths must fail closed.',
    rawSignals: {
      secureContext: false,
      crossOriginIsolated: false,
      workerAvailable: true,
      dedicatedWorkerAvailable: true,
      serviceWorkerAvailable: false,
      offscreenCanvasAvailable: false,
      platformCoarse: 'unknown',
      hardwareConcurrency: undefined,
      deviceMemoryGb: undefined,
      wasmAvailable: true,
      wasmSimdLikely: 'unknown',
      sharedArrayBufferAvailable: false,
      highResolutionTimerAllowed: false,
      webglAvailable: false,
      webgl2Available: false,
      webgpuAvailable: false,
      offscreenCanvas2dAvailable: false,
      offscreenCanvasWebglAvailable: false,
      webCodecsAvailable: false,
      videoEncoderAvailable: false,
      videoDecoderAvailable: false,
      audioEncoderAvailable: false,
      audioDecoderAvailable: false,
      mediaCapabilitiesAvailable: false,
      storageEstimateAvailable: false,
      persistentStorageAvailable: false,
      networkInformationAvailable: false,
      effectiveType: 'unknown',
      saveData: 'unknown',
    },
    expectedHints: ['unknown_capability_fail_closed'],
    expectedWarnings: ['shared_memory_unavailable_cross_origin_isolation'],
    expectedBlockedReasons: ['insecure_context'],
  },
]
