export const SUPABASE_TABLE_GROUPS = {
  core: {
    plans: 'plans',
    profiles: 'profiles',
    userProfiles: 'user_profiles',
    workspaces: 'workspaces',
    workspaceMembers: 'workspace_members',
    subscriptions: 'subscriptions',
    projects: 'projects',
    editSessions: 'edit_sessions',
    chatSessions: 'chat_sessions',
    chatMessages: 'chat_messages',
    chatAttachments: 'chat_attachments',
    inlineChatCards: 'inline_chat_cards',
    chatActions: 'chat_actions',
    userConfirmations: 'user_confirmations',
    mediaAssets: 'media_assets',
    uploadedClips: 'uploaded_clips',
    sourceClipSequences: 'source_clip_sequences',
    sourceClipSequenceItems: 'source_clip_sequence_items',
    sourceSequenceItems: 'source_sequence_items',
    referenceAssets: 'reference_assets',
    clipAnalysisSnapshots: 'clip_analysis_snapshots',
  },
  planning: {
    intentAnalyses: 'intent_analyses',
    editIntentSnapshots: 'edit_intent_snapshots',
    editSettingsSnapshots: 'edit_settings_snapshots',
    sourceSequenceMaps: 'source_sequence_maps',
    sourceSequenceMapItems: 'source_sequence_map_items',
    recommendedEditStructures: 'recommended_edit_structures',
    editPlans: 'edit_plans',
    editPlanVersions: 'edit_plan_versions',
    planComponentSnapshots: 'plan_component_snapshots',
    storyBeatMaps: 'story_beat_maps',
    storyBeats: 'story_beats',
    editPlanSegments: 'edit_plan_segments',
    editOperations: 'edit_operations',
    signatureRoutes: 'signature_routes',
    editInstructions: 'edit_instructions',
    planningNotes: 'planning_notes',
    editPlanChatCards: 'edit_plan_chat_cards',
  },
  editQuality: {
    editQualityProfiles: 'edit_quality_profiles',
    pacingAnalysis: 'pacing_analysis',
    cutDecisions: 'cut_decisions',
    transitionPlans: 'transition_plans',
    audioEnvironmentAnalysis: 'audio_environment_analysis',
    ambientSoundPlans: 'ambient_sound_plans',
    musicPlans: 'music_plans',
    soundEffectPlans: 'sound_effect_plans',
    captionPlans: 'caption_plans',
    editQualityChecks: 'edit_quality_checks',
  },
  credits: {
    creditWallets: 'credit_wallets',
    creditGrants: 'credit_grants',
    creditLedgerEntries: 'credit_ledger_entries',
    creditEstimates: 'credit_estimates',
    creditEstimateItems: 'credit_estimate_items',
    creditEstimateLineItems: 'credit_estimate_line_items',
    creditApprovals: 'credit_approvals',
    creditReservations: 'credit_reservations',
    creditReservationLineItems: 'credit_reservation_line_items',
    creditRefunds: 'credit_refunds',
    refundRecords: 'refund_records',
    approvalRecords: 'approval_records',
    approvedPlanSnapshots: 'approved_plan_snapshots',
  },
  jobs: {
    jobBatches: 'job_batches',
    jobs: 'jobs',
    jobDependencies: 'job_dependencies',
    jobEvents: 'job_events',
    editingJobs: 'editing_jobs',
    jobSteps: 'job_steps',
    agentRuns: 'agent_runs',
    agentOutputs: 'agent_outputs',
    workerRuntimeConfigs: 'worker_runtime_configs',
    workerHeartbeats: 'worker_heartbeats',
    workerEvents: 'worker_events',
    eventLog: 'event_log',
  },
  strokeMotion: {
    strokeMotionPlans: 'stroke_motion_plans',
    strokeMotionMeaningExpansions: 'stroke_motion_meaning_expansions',
    strokeMotionBeats: 'stroke_motion_beats',
    strokeMotionCharacters: 'stroke_motion_characters',
    strokeMotionSymbols: 'stroke_motion_symbols',
    strokeMotionBeatCharacters: 'stroke_motion_beat_characters',
    strokeMotionBeatSymbols: 'stroke_motion_beat_symbols',
    strokeMotionTransitions: 'stroke_motion_transitions',
    strokeMotionTimingAnchors: 'stroke_motion_timing_anchors',
    strokeMotionStoryboardFrames: 'stroke_motion_storyboard_frames',
    strokeMotionGenerationSpecs: 'stroke_motion_generation_specs',
    strokeMotionPlanExamples: 'stroke_motion_plan_examples',
  },
  generation: {
    generationProviders: 'generation_providers',
    generationProviderCapabilities: 'generation_provider_capabilities',
    generationProviderModels: 'generation_provider_models',
    generationRequests: 'generation_requests',
    generationRequestInputs: 'generation_request_inputs',
    generatedAssets: 'generated_assets',
    generatedAssetVersions: 'generated_asset_versions',
    generatedAssetTimingMaps: 'generated_asset_timing_maps',
    generationEvents: 'generation_events',
    generationRequestCosts: 'generation_request_costs',
  },
  renderReviewExportQA: {
    renderJobs: 'render_jobs',
    renderJobInputs: 'render_job_inputs',
    renders: 'renders',
    renderEvents: 'render_events',
    exports: 'exports',
    exportVariants: 'export_variants',
    previewReviews: 'preview_reviews',
    reviewComments: 'review_comments',
    revisionRequests: 'revision_requests',
    revisionRequestItems: 'revision_request_items',
    qaReports: 'qa_reports',
    qaReportItems: 'qa_report_items',
    qaCheckResults: 'qa_check_results',
    finalExports: 'final_exports',
    auditEvents: 'audit_events',
    productionReadinessSnapshots: 'production_readiness_snapshots',
    licenseReviewSnapshots: 'license_review_snapshots',
  },
  sfxDirector: {
    sfxEventPlans: 'sfx_event_plans',
    sfxProviderRoutes: 'sfx_provider_routes',
    sfxPromptPlans: 'sfx_prompt_plans',
    sfxGeneratedAssets: 'sfx_generated_assets',
    sfxTrimPlans: 'sfx_trim_plans',
    sfxTimingAlignments: 'sfx_timing_alignments',
    sfxMixPlans: 'sfx_mix_plans',
    sfxQaReports: 'sfx_qa_reports',
    sfxQaIssues: 'sfx_qa_issues',
    sfxLibraryCandidates: 'sfx_library_candidates',
    sfxUsageRecords: 'sfx_usage_records',
    sfxPromptAdapterTests: 'sfx_prompt_adapter_tests',
  },
  storyTiming: {
    masterTimingMaps: 'master_timing_maps',
    storyTimingSegments: 'story_timing_segments',
    timingAnchors: 'timing_anchors',
    timingEvents: 'timing_events',
    timingDependencies: 'timing_dependencies',
    timingConflicts: 'timing_conflicts',
    timingConflictResolutions: 'timing_conflict_resolutions',
    storyTimingQaChecks: 'story_timing_qa_checks',
    renderTimingManifests: 'render_timing_manifests',
    renderTimingManifestTracks: 'render_timing_manifest_tracks',
    renderTimingManifestEvents: 'render_timing_manifest_events',
  },
} as const

export const TABLE_NAMES = {
  ...SUPABASE_TABLE_GROUPS.core,
  ...SUPABASE_TABLE_GROUPS.planning,
  ...SUPABASE_TABLE_GROUPS.editQuality,
  ...SUPABASE_TABLE_GROUPS.credits,
  ...SUPABASE_TABLE_GROUPS.jobs,
  ...SUPABASE_TABLE_GROUPS.strokeMotion,
  ...SUPABASE_TABLE_GROUPS.generation,
  ...SUPABASE_TABLE_GROUPS.renderReviewExportQA,
  ...SUPABASE_TABLE_GROUPS.sfxDirector,
  ...SUPABASE_TABLE_GROUPS.storyTiming,
} as const

export type SupabaseTableGroupName = keyof typeof SUPABASE_TABLE_GROUPS
export type ReeditProTableKey = keyof typeof TABLE_NAMES
export type ReeditProTableName = (typeof TABLE_NAMES)[ReeditProTableKey]
