export const TABLE_NAMES = {
  profiles: 'profiles',
  userProfiles: 'profiles',
  legacyUserProfiles: 'user_profiles',
  workspaces: 'workspaces',
  workspaceMembers: 'workspace_members',
  workspaceMemberships: 'workspace_members',
  projects: 'projects',
  editSessions: 'edit_sessions',
  chatSessions: 'chat_sessions',
  chatMessages: 'chat_messages',
  userConfirmations: 'user_confirmations',
  mediaAssets: 'media_assets',
  uploadedClips: 'uploaded_clips',
  sourceClipSequences: 'source_clip_sequences',
  sourceSequenceItems: 'source_sequence_items',
  sourceClipSequenceItems: 'source_clip_sequence_items',
  referenceAssets: 'reference_assets',
  intentAnalyses: 'intent_analyses',
  sourceSequenceMaps: 'source_sequence_maps',
  recommendedEditStructures: 'recommended_edit_structures',
  editPlans: 'edit_plans',
  editPlanSegments: 'edit_plan_segments',
  editQualityProfiles: 'edit_quality_profiles',
  strokeMotionPlans: 'stroke_motion_plans',
  creditEstimates: 'credit_estimates',
  creditReservations: 'credit_reservations',
  jobBatches: 'job_batches',
  jobs: 'jobs',
  generationRequests: 'generation_requests',
  generatedAssets: 'generated_assets',
  renderJobs: 'render_jobs',
  renders: 'renders',
  revisionRequests: 'revision_requests',
  qaReports: 'qa_reports',
  exports: 'exports',
  finalExports: 'final_exports',
  sfxGeneratedAssets: 'sfx_generated_assets',
} as const

export type ReeditProTableKey = keyof typeof TABLE_NAMES

export const SUPABASE_TABLES = {
  profiles: TABLE_NAMES.profiles,
  userProfiles: TABLE_NAMES.userProfiles,
  legacyUserProfiles: TABLE_NAMES.legacyUserProfiles,
  workspaces: TABLE_NAMES.workspaces,
  workspaceMembers: TABLE_NAMES.workspaceMembers,
  workspaceMemberships: TABLE_NAMES.workspaceMemberships,
  projects: TABLE_NAMES.projects,
  editSessions: TABLE_NAMES.editSessions,
  chatMessages: TABLE_NAMES.chatMessages,
  userConfirmations: TABLE_NAMES.userConfirmations,
  mediaAssets: TABLE_NAMES.mediaAssets,
  uploadedClips: TABLE_NAMES.uploadedClips,
  sourceSequenceItems: TABLE_NAMES.sourceSequenceItems,
  referenceAssets: TABLE_NAMES.referenceAssets,
  generatedAssets: TABLE_NAMES.generatedAssets,
  renders: TABLE_NAMES.renders,
  exports: TABLE_NAMES.exports,
  finalExports: TABLE_NAMES.finalExports,
  sfxGeneratedAssets: TABLE_NAMES.sfxGeneratedAssets,
} as const
