import type { OfflineVapourSynthFramePipelineRequest, OfflineVapourSynthFramePipelineToolId } from './offline-vapoursynth-frame-pipeline-protocol'

export interface OfflineVapourSynthFramePipelineImageEvidence { imageTag: 'reeditpro-offline-vapoursynth-frame-pipeline-execution:private-local-v1'; imageId: string; imageIdentityHash: string; pinnedBaseImage: 'python:3.13.11-slim-bookworm@sha256:20080e807bfc404f8450b185cf0fc95d553462673598549613735f70a5b4d5d0'; debianSnapshot: '20260623T000000Z'; sourceHashes: Readonly<Record<string, string>>; imageUser: '10001:10001'; imageEntrypoint: readonly ['python', '-s', '/app/runner.py']; imageEnvironmentNames: readonly string[]; rootFilesystemLayerDigests: readonly string[]; labels: Readonly<Record<string, string>> }
export interface OfflineVapourSynthFramePipelineConfinementEvidence { networkMode: 'none'; readOnlyRootFilesystem: true; capDropAll: true; noNewPrivileges: true; privileged: false; pidsLimit: 128; memoryLimitBytes: 1073741824; memoryAndSwapLimitBytes: 1073741824; nanoCpus: 2000000000; tmpfsPath: '/tmp'; tmpfsSizeBytes: 268435456; tmpfsNoExec: true; tmpfsNoSuid: true; tmpfsNoDevice: true; user: '10001:10001'; callerCommandPresent: false; callerBindsPresent: false; callerMountsPresent: false; callerEnvironmentPresent: false; secretLikeImageEnvironmentNames: readonly [] }
export interface OfflineVapourSynthFramePipelineExecutionResult {
  schemaVersion: 'offline-vapoursynth-frame-pipeline-execution-result-v1'; request: OfflineVapourSynthFramePipelineRequest
  artifact: { mimeType: 'application/json'; bytes: Buffer; byteLength: number; sha256: string }
  evidence: { packageName: string; packageVersion: string; requestEnvelopeSha256: string; image: OfflineVapourSynthFramePipelineImageEvidence; confinement: OfflineVapourSynthFramePipelineConfinementEvidence; semanticEvidence: Readonly<Record<string, boolean | number | string>>; containerExitCode: 0; oomKilled: false }
  attestation: { schemaVersion: 'offline-vapoursynth-frame-pipeline-execution-attestation-v1'; recordId: string; completedAt: string; toolId: OfflineVapourSynthFramePipelineToolId; imageIdentityHash: string; requestEnvelopeSha256: string; artifactSha256: string; confinementHash: string; attestationHash: string }
  readiness: { privateInternalOnly: true; exactStructuredPayloadOnly: true; canonicalDispatchIntegrated: false; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }
}
export interface OfflineVapourSynthFramePipelineRuntimeAuthority { schemaVersion: 'offline-vapoursynth-frame-pipeline-runtime-authority-v1'; source: 'private_local_offline_vapoursynth_frame_pipeline_runtime_authority'; activatedAt: string; image: OfflineVapourSynthFramePipelineImageEvidence; supportedOperations: readonly { toolId: OfflineVapourSynthFramePipelineToolId; operationId: string }[]; readiness: { privateInternalExecutionReady: true; exactStructuredPayloadOnly: true; canonicalDispatchMayReference: true; licenseReviewStillRequiredForProduction: true; productReady: false; externalBetaReady: false; productionReady: false }; blockers: readonly string[]; authorityHash: string }
