import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineVapourSynthFramePipelineDockerRuntime, runOfflineVapourSynthFramePipelineContainer } from './offline-vapoursynth-frame-pipeline-docker-runtime'
import {
  OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_CONTAINER_PROTOCOL, OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS,
  OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_PACKAGE_IDENTITIES, OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_TOOL_IDS,
  offlineVapourSynthFramePipelineRequestSha256, validateOfflineVapourSynthFramePipelineRequest,
} from './offline-vapoursynth-frame-pipeline-protocol'
import type { OfflineVapourSynthFramePipelineExecutionResult, OfflineVapourSynthFramePipelineImageEvidence, OfflineVapourSynthFramePipelineRuntimeAuthority } from './offline-vapoursynth-frame-pipeline-types'

export const OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_STORAGE_ROOT = '/tmp/reeditpro-offline-vapoursynth-frame-pipeline-execution' as const
export const OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_AUTHORITY_PATH = 'runtime-authority/offline-vapoursynth-frame-pipeline-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'This exact operation is confined private/local fixture evidence; arbitrary user media ingestion, caller scripts, third-party plugins, distributed worker identity, scanning, observability, recovery, and deployment remain separate gates.',
  'The current proven wheel is ARM64-only; an independently hash-pinned x86_64 image and multi-architecture manifest remain required.',
  'VapourSynth and every future plugin still require recorded dependency, security, output-quality, compatibility, and production license review before product or production promotion.',
] as const)

export interface PrivateOfflineVapourSynthFramePipelineRuntime { readonly image: OfflineVapourSynthFramePipelineImageEvidence; execute(value: unknown): Promise<OfflineVapourSynthFramePipelineExecutionResult> }
export async function activatePrivateOfflineVapourSynthFramePipelineRuntime(): Promise<PrivateOfflineVapourSynthFramePipelineRuntime> { if (arguments.length !== 0) throw invalid('VapourSynth frame pipeline runtime activation accepts no caller input.'); const image = await inspectExistingOfflineVapourSynthFramePipelineDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineVapourSynthFramePipelineRuntime(): Promise<PrivateOfflineVapourSynthFramePipelineRuntime> { if (arguments.length !== 0) throw invalid('VapourSynth frame pipeline runtime open accepts no caller input.'); const authority = await readPersistedOfflineVapourSynthFramePipelineRuntimeAuthority(); if (!authority) throw notReady('Verified private VapourSynth frame pipeline runtime authority is unavailable.'); const image = await inspectExistingOfflineVapourSynthFramePipelineDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private VapourSynth frame pipeline image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineVapourSynthFramePipeline(value: unknown): Promise<OfflineVapourSynthFramePipelineExecutionResult> { return executeWithImage(await inspectExistingOfflineVapourSynthFramePipelineDockerRuntime(), value) }
export async function readPersistedOfflineVapourSynthFramePipelineRuntimeAuthority(): Promise<OfflineVapourSynthFramePipelineRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_STORAGE_ROOT, relativePath: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private VapourSynth frame pipeline authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-vapoursynth-frame-pipeline-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_vapoursynth_frame_pipeline_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private VapourSynth frame pipeline authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-vapoursynth-frame-pipeline-runtime-authority-v1' || authority.source !== 'private_local_offline_vapoursynth_frame_pipeline_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private VapourSynth frame pipeline authority boundary is invalid.')
  return authority as unknown as OfflineVapourSynthFramePipelineRuntimeAuthority
}
async function executeWithImage(image: OfflineVapourSynthFramePipelineImageEvidence, value: unknown): Promise<OfflineVapourSynthFramePipelineExecutionResult> {
  const request = validateOfflineVapourSynthFramePipelineRequest(value); const result = await runOfflineVapourSynthFramePipelineContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private VapourSynth frame pipeline execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_PACKAGE_IDENTITIES[request.toolId]
  if (response.schemaVersion !== OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_vapoursynth_frame_pipeline_operation_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || response.requestEnvelopeSha256 !== offlineVapourSynthFramePipelineRequestSha256(request) || artifact.mimeType !== 'application/json' || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 2 || bytes.length > 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private VapourSynth frame pipeline result identity is invalid.')
  validateJsonArtifact(bytes, request.toolId); validateSemanticEvidence(request.toolId, semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private VapourSynth frame pipeline semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-vapoursynth-frame-pipeline-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineVapourSynthFramePipelineRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-vapoursynth-frame-pipeline-execution-attestation-record-v1', source: 'private_local_checksum_protected_vapoursynth_frame_pipeline_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-vapoursynth-frame-pipeline-execution-result-v1', request, artifact: { mimeType: 'application/json', bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(toolId: keyof typeof OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS, evidence: Record<string, unknown>): void {
  if (toolId !== 'vapoursynth' || evidence.actualPackageEntrypointExecuted !== true || evidence.zeroNetworkRuntimeRequired !== true || evidence.approvedServerOwnedFixtureOnly !== true || evidence.reviewedBuiltinPluginsOnly !== true || evidence.callerScriptAllowed !== false || evidence.entrypoint !== 'vapoursynth.core.std+resize' || evidence.blankClipExecuted !== true || evidence.cropRelExecuted !== true || evidence.resizePointExecuted !== true || evidence.firstAndLastFrameVerified !== true || evidence.frameCount !== 24 || evidence.frameRateNumerator !== 24 || evidence.frameRateDenominator !== 1 || evidence.outputWidth !== 64 || evidence.outputHeight !== 64) throw notReady('Private VapourSynth frame pipeline semantic evidence is invalid.')
}
function validateJsonArtifact(bytes: Buffer, toolId: keyof typeof OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS): void { let parsed: unknown; try { parsed = JSON.parse(bytes.toString('utf8')) } catch { throw notReady('VapourSynth frame pipeline artifact is invalid JSON.') } const document = record(parsed); const output = record(document.output); const frameRate = record(document.frameRate); const operations = document.operations; if (toolId !== 'vapoursynth' || document.pipelineProfileId !== 'approved_frame_preprocess_v1' || document.pluginPackProfileId !== 'reviewed_builtin_plugins_v1' || document.callerScriptAllowed !== false || document.frameCount !== 24 || output.format !== 'RGB24' || output.width !== 64 || output.height !== 64 || frameRate.numerator !== 24 || frameRate.denominator !== 1 || stableAuthorityStringify(operations) !== stableAuthorityStringify(['std.BlankClip', 'std.CropRel', 'resize.Point']) || !Array.isArray(document.firstFramePlaneSha256) || stableAuthorityStringify(document.firstFramePlaneSha256) !== stableAuthorityStringify(document.lastFramePlaneSha256)) throw notReady('VapourSynth frame pipeline JSON artifact is invalid.') }
async function persistAuthority(image: OfflineVapourSynthFramePipelineImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-vapoursynth-frame-pipeline-runtime-authority-v1' as const, source: 'private_local_offline_vapoursynth_frame_pipeline_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineVapourSynthFramePipelineRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_STORAGE_ROOT, relativePath: OFFLINE_VAPOURSYNTH_FRAME_PIPELINE_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-vapoursynth-frame-pipeline-runtime-authority-record-v1', source: 'private_local_checksum_protected_vapoursynth_frame_pipeline_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private VapourSynth frame pipeline response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private VapourSynth frame pipeline response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private VapourSynth frame pipeline response contains an invalid string.'); return value }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
