export type SupabaseCleanStagingTargetApprovalDecision =
  | 'approved_for_future_clean_supabase_staging_branch'
  | 'approved_for_future_clean_supabase_staging_project'
  | 'blocked_pending_human_review'
  | 'blocked_pending_cost_review'
  | 'blocked_pending_branching_availability_review'
  | 'blocked_pending_secret_reference_plan'
  | 'rejected_due_existing_staging_must_be_preserved'

export type SupabaseCleanStagingTargetApprovalBlocker =
  | 'pr276_support_ticket_submission_evidence_missing'
  | 'pr274_support_escalation_approval_missing'
  | 'pr271_reset_retry_diagnostics_missing'
  | 'pr269_reset_retry_evidence_missing'
  | 'pr252_owner_data_loss_acceptance_missing'
  | 'pr247_schema_parity_strategy_missing'
  | 'pr241_remote_schema_equivalence_evidence_missing'
  | 'pr223_transport_blocker_evidence_missing'
  | 'pr198_trackb_backfill_preflight_missing'
  | 'current_staging_repair_not_proven_unsafe'
  | 'existing_staging_data_preservation_required'
  | 'clean_staging_target_approval_not_confirmed'
  | 'clean_staging_replacement_review_not_confirmed'
  | 'clean_staging_cost_review_missing'
  | 'clean_staging_branching_availability_review_missing'
  | 'clean_staging_secret_reference_plan_missing'
  | 'forbidden_confirmation_set'
  | 'sensitive_payload_pattern_detected'

export type SupabaseCleanStagingTargetKind =
  | 'clean_supabase_staging_branch'
  | 'clean_supabase_staging_project'
  | 'existing_staging_repair'
  | 'support_ticket_wait'
