import {
  DEEPFILTERNET_CLI_FILE_NAME,
  DEEPFILTERNET_CLI_SOURCE_URL,
  DEEPFILTERNET_DOWNLOAD_GCS_PATH,
  DEEPFILTERNET_DOWNLOAD_LOCAL_DIR,
  DEEPFILTERNET_DOWNLOAD_TEMP_ROOT,
  DEEPFILTERNET_ONNX_ARCHIVE_FILE_NAME,
  DEEPFILTERNET_ONNX_ARCHIVE_SOURCE_URL,
  deepFilterNetDownloadExecutionDoesNotDo,
} from './deepfilternet-download-policy'
import type { DeepFilterNetDownloadExecutionCommandPlan } from './audio-ai-download-types'

export function buildDeepFilterNetDownloadExecutionCommandPlans(): DeepFilterNetDownloadExecutionCommandPlan[] {
  return [
    {
      commandId: 'deepfilternet_download_preflight',
      phase: 'preflight',
      commandString: [
        'gcloud auth list',
        'gcloud config get-value project',
        'gcloud projects describe reeditpro',
        'gcloud storage buckets describe gs://reeditpro-staging-reeditpro-generated-assets',
        'gcloud storage objects list gs://reeditpro-staging-reeditpro-generated-assets/model-weights/audio-ai/deepfilternet/ --recursive --limit=50 || true',
      ].join(' && '),
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Read-only preflight commands; do not proceed unless project/env/source guards pass.'],
    },
    {
      commandId: 'deepfilternet_source_license_verify',
      phase: 'source_evidence',
      commandString: 'TEXT_ONLY source/license verification runs inside the Phase 36B CLI before download.',
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Stops before download if official source/license evidence is unclear.'],
    },
    {
      commandId: 'deepfilternet_download_linux_cli',
      phase: 'download',
      commandString: [
        'REEDITPRO_CONFIRM_DEEPFILTERNET_ARTIFACT_DOWNLOAD=true',
        'curl -fL',
        `-o ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/${DEEPFILTERNET_CLI_FILE_NAME}`,
        DEEPFILTERNET_CLI_SOURCE_URL,
      ].join(' '),
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_DEEPFILTERNET_ARTIFACT_DOWNLOAD',
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Execute only in Phase 36B after preflight; temp path is outside repo.'],
    },
    {
      commandId: 'deepfilternet_download_dfn3_onnx_archive',
      phase: 'download',
      commandString: [
        'REEDITPRO_CONFIRM_DEEPFILTERNET_ARTIFACT_DOWNLOAD=true',
        'curl -fL',
        `-o ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/${DEEPFILTERNET_ONNX_ARCHIVE_FILE_NAME}`,
        DEEPFILTERNET_ONNX_ARCHIVE_SOURCE_URL,
      ].join(' '),
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_DEEPFILTERNET_ARTIFACT_DOWNLOAD',
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Download only the approved v0.5.6 DeepFilterNet3 ONNX archive; do not download datasets, RNNoise, Demucs, or unpinned snapshots.'],
    },
    {
      commandId: 'deepfilternet_download_checksums',
      phase: 'checksum',
      commandString: `cd ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR} && shasum -a 256 ${DEEPFILTERNET_CLI_FILE_NAME} ${DEEPFILTERNET_ONNX_ARCHIVE_FILE_NAME} > file_checksums_sha256.txt`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Checksum output must use sanitized relative paths in tracked reports.'],
    },
    {
      commandId: 'deepfilternet_download_upload_to_gcs',
      phase: 'upload',
      commandString: `gcloud storage cp ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/${DEEPFILTERNET_CLI_FILE_NAME} ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/${DEEPFILTERNET_ONNX_ARCHIVE_FILE_NAME} ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/file_checksums_sha256.txt ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/model_tree_manifest.json ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/source_evidence.json ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/license_evidence.json ${DEEPFILTERNET_DOWNLOAD_LOCAL_DIR}/download_report.json ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}`,
      textOnlyByDefault: true,
      requiresConfirmation: true,
      confirmationEnvVar: 'REEDITPRO_CONFIRM_DEEPFILTERNET_ARTIFACT_DOWNLOAD',
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Upload only to the private generated-assets DeepFilterNet v0.5.6 model-weight prefix.'],
    },
    {
      commandId: 'deepfilternet_download_verify_gcs',
      phase: 'verify',
      commandString: `gcloud storage objects describe ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}${DEEPFILTERNET_CLI_FILE_NAME} ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}${DEEPFILTERNET_ONNX_ARCHIVE_FILE_NAME} ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}file_checksums_sha256.txt ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}model_tree_manifest.json ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}source_evidence.json ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}license_evidence.json ${DEEPFILTERNET_DOWNLOAD_GCS_PATH}download_report.json`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Verification is read-only and must not create signed URLs.'],
    },
    {
      commandId: 'deepfilternet_download_cleanup_temp',
      phase: 'cleanup',
      commandString: `rm -rf ${DEEPFILTERNET_DOWNLOAD_TEMP_ROOT}/v0.5.6`,
      textOnlyByDefault: true,
      requiresConfirmation: false,
      doesNotDo: [...deepFilterNetDownloadExecutionDoesNotDo],
      warnings: ['Remove local temp artifact files after upload and verification.'],
    },
  ]
}
