export const LOCAL_WORKER_SIDECAR_GLOBAL_BLOCKED_SCOPES = [
  'route execution',
  'worker execution',
  'tool execution',
  'raw chat execution',
  'arbitrary subprocess execution',
  'shell string execution',
  'arbitrary local paths',
  'arbitrary GCS prefixes',
  'public artifacts',
  'signed URLs as source of truth',
  'media processing',
  'audio processing',
  'OCR runtime',
  'VLM runtime',
  'DeepFilterNet runtime',
  'Signalsmith runtime',
  'Demucs runtime',
  'model downloads',
  'provider calls',
  'web search provider calls',
  'Docker',
  'Cloud Build',
  'Cloud Run',
  'GPU jobs',
  'GCP mutation',
  'IAM mutation',
  'product-wide internal beta',
  'external beta',
  'paid production',
  'production',
  'Track A runtime/visual/render stack',
]

export function buildLocalWorkerSidecarPlanSnapshotPolicy() {
  return {
    policyVersion: 'track-b-plan-snapshot-policy-v1',
    requiredFields: [
      'planSnapshotId',
      'routeManifestVersion',
      'toolRouteEntryId',
      'toolId',
      'approvedCapabilityId',
      'inputArtifactScopeId',
      'outputArtifactScopeId',
      'requesterContext',
      'sourcePhase',
      'allowedExecutionPhase',
      'confirmationPhase',
      'maxDurationSeconds',
      'maxInputCount',
      'maxOutputSizeBytes',
      'auditReportPath',
    ],
    requiredBooleans: {
      publicOutputAllowed: false,
      broadMediaAllowed: false,
      arbitraryMediaAllowed: false,
      providerCallsAllowed: false,
      noRawChatExecution: true,
      failClosed: true,
    },
    blockedSources: [
      'raw_prompt_text',
      'arbitrary_commands',
      'arbitrary_file_paths',
      'arbitrary_gcs_prefixes',
      'public_urls',
      'signed_urls_as_source_of_truth',
      'tools_not_enabled_by_route_manifest',
      'demucs',
      'qwen3_vl',
      'vllm',
      'routeExecutionAllowed_false_entries_for_execution',
      'runtimeExecutionAllowed_false_entries_for_execution',
    ],
  }
}

export function buildLocalWorkerSidecarArtifactScopePolicy() {
  return {
    policyVersion: 'track-b-artifact-scope-policy-v1',
    approvedPrivateInputScope: 'private_activation_or_worker_temp_scoped_prefix_only',
    approvedPrivateOutputScope: 'private_activation_qa_or_worker_temp_scoped_prefix_only',
    approvedLocalTempScope: 'ephemeral_phase_scoped_temp_dir_only',
    redactionRules: ['bucket_prefix_only', 'hashes_allowed', 'object_counts_allowed', 'no_payload_bytes_committed'],
    cleanupRules: ['delete_local_temp_after_future_execution', 'write_cleanup_report', 'fail_closed_on_cleanup_failure'],
    blocked: [
      'public_artifact_paths',
      'public_urls',
      'signed_urls_as_source_of_truth',
      'arbitrary_user_paths',
      'arbitrary_gcs_prefixes',
      'broad_media_buckets',
      'committed_media_payloads',
      'committed_audio_payloads',
      'committed_model_payloads',
      'committed_private_payloads',
    ],
    requiredReports: ['private_artifact_manifest', 'audit_report'],
  }
}

export function buildLocalWorkerSidecarSecurityPolicy() {
  return {
    policyVersion: 'track-b-sidecar-security-policy-v1',
    rawChatExecutionAllowed: false,
    arbitrarySubprocessAllowed: false,
    shellStringExecutionAllowed: false,
    futureCommandPolicy: {
      allowlistedAdaptersOnly: true,
      explicitExecutablePath: true,
      explicitArgvArray: true,
      shellByDefault: false,
      boundedTimeoutRequired: true,
      boundedStdoutStderrRequired: true,
      controlledCwdRequired: true,
      scrubbedEnvironmentRequired: true,
      inheritedSensitiveEnvAllowed: false,
    },
    ipcSecretPolicy: {
      serviceRoleSecretsInFrontendAllowed: false,
      secretsOverIpcAllowed: false,
      environmentVariableDumpAllowed: false,
    },
    futureDesktopBridgePolicy: {
      electronContextIsolationRequired: true,
      preloadApiMustBeNarrow: true,
      directNodeAccessFromRendererAllowed: false,
      tauriShellNotAddedInPhase44G: true,
      sidecarCommandsMustBeAllowlisted: true,
    },
    failClosed: true,
    auditLoggingRequired: true,
  }
}

export function buildLocalWorkerSidecarLifecyclePolicy() {
  return {
    policyVersion: 'track-b-sidecar-lifecycle-policy-v1',
    states: [
      'uninitialized',
      'handshake_pending',
      'ready_metadata_only',
      'validation_only',
      'execution_blocked',
      'shutting_down',
      'terminated',
      'error',
    ],
    startupTimeoutMs: 5000,
    heartbeatPolicy: 'future_execution_phase_required',
    shutdownTimeoutMs: 5000,
    crashPolicy: 'fail_closed_write_blocker_report',
    retryPolicy: 'no_automatic_retry_in_phase44g',
    maxRuntimePolicy: 'no_long_running_process_in_phase44g',
    tempCleanupPolicy: 'ephemeral_temp_only_future_execution_cleanup_required',
    artifactCleanupPolicy: 'private_manifest_required_future_execution_only',
  }
}
