import { createHash } from 'node:crypto'

import { ApiError } from '../../errors/api-error'
import { readPrivateTextFileIfExistsWithinRoot, writePrivateTextFileAtomicWithinRoot } from '../../security/private-local-persistence'
import { sha256AuthorityValue, stableAuthorityStringify } from '../../services/private-edit-authority-store'
import { inspectExistingOfflineContainerPackagingValidationDockerRuntime, runOfflineContainerPackagingValidationContainer } from './offline-container-packaging-validation-docker-runtime'
import {
  OFFLINE_CONTAINER_PACKAGING_VALIDATION_CONTAINER_PROTOCOL, OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS,
  OFFLINE_CONTAINER_PACKAGING_VALIDATION_PACKAGE_IDENTITIES, OFFLINE_CONTAINER_PACKAGING_VALIDATION_TOOL_IDS,
  offlineContainerPackagingValidationRequestSha256, validateOfflineContainerPackagingValidationRequest,
} from './offline-container-packaging-validation-protocol'
import type { OfflineContainerPackagingValidationExecutionResult, OfflineContainerPackagingValidationImageEvidence, OfflineContainerPackagingValidationRuntimeAuthority } from './offline-container-packaging-validation-types'

export const OFFLINE_CONTAINER_PACKAGING_VALIDATION_STORAGE_ROOT = '/tmp/reeditpro-offline-container-packaging-validation-execution' as const
export const OFFLINE_CONTAINER_PACKAGING_VALIDATION_AUTHORITY_PATH = 'runtime-authority/offline-container-packaging-validation-runtime-v1.json' as const
const BLOCKERS = Object.freeze([
  'These exact operations are confined private/local fixture evidence; arbitrary user media ingestion, container mutation, distributed worker identity, multi-architecture images, scanning, observability, recovery, and deployment remain separate gates.',
  'MKVToolNix still requires recorded dependency, security, output-quality, compatibility, and production license review before product or production promotion.',
  'GPAC/MP4Box still requires recorded dependency, source-build, security, output-quality, compatibility, and production license review before product or production promotion.',
] as const)

export interface PrivateOfflineContainerPackagingValidationRuntime { readonly image: OfflineContainerPackagingValidationImageEvidence; execute(value: unknown): Promise<OfflineContainerPackagingValidationExecutionResult> }
export async function activatePrivateOfflineContainerPackagingValidationRuntime(): Promise<PrivateOfflineContainerPackagingValidationRuntime> { if (arguments.length !== 0) throw invalid('Container packaging validation runtime activation accepts no caller input.'); const image = await inspectExistingOfflineContainerPackagingValidationDockerRuntime(); await persistAuthority(image); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function openPrivateOfflineContainerPackagingValidationRuntime(): Promise<PrivateOfflineContainerPackagingValidationRuntime> { if (arguments.length !== 0) throw invalid('Container packaging validation runtime open accepts no caller input.'); const authority = await readPersistedOfflineContainerPackagingValidationRuntimeAuthority(); if (!authority) throw notReady('Verified private container packaging validation runtime authority is unavailable.'); const image = await inspectExistingOfflineContainerPackagingValidationDockerRuntime(); if (stableAuthorityStringify(image) !== stableAuthorityStringify(authority.image)) throw notReady('Private container packaging validation image changed after activation.'); return Object.freeze({ image, execute: (value: unknown) => executeWithImage(image, value) }) }
export async function executePrivateOfflineContainerPackagingValidation(value: unknown): Promise<OfflineContainerPackagingValidationExecutionResult> { return executeWithImage(await inspectExistingOfflineContainerPackagingValidationDockerRuntime(), value) }
export async function readPersistedOfflineContainerPackagingValidationRuntimeAuthority(): Promise<OfflineContainerPackagingValidationRuntimeAuthority | undefined> {
  const content = await readPrivateTextFileIfExistsWithinRoot({ rootPath: OFFLINE_CONTAINER_PACKAGING_VALIDATION_STORAGE_ROOT, relativePath: OFFLINE_CONTAINER_PACKAGING_VALIDATION_AUTHORITY_PATH }); if (!content) return undefined
  let parsed: unknown; try { parsed = JSON.parse(content) } catch { throw notReady('Private container packaging validation authority is invalid JSON.') }
  const envelope = record(parsed); const authority = record(envelope.authority)
  if (envelope.recordVersion !== 'offline-container-packaging-validation-runtime-authority-record-v1' || envelope.source !== 'private_local_checksum_protected_container_packaging_validation_runtime' || envelope.checksumSha256 !== sha256AuthorityValue(authority)) throw notReady('Private container packaging validation authority checksum is invalid.')
  const { authorityHash, ...withoutHash } = authority; const readiness = record(authority.readiness)
  if (authorityHash !== sha256AuthorityValue(withoutHash) || authority.schemaVersion !== 'offline-container-packaging-validation-runtime-authority-v1' || authority.source !== 'private_local_offline_container_packaging_validation_runtime_authority' || readiness.privateInternalExecutionReady !== true || readiness.exactStructuredPayloadOnly !== true || readiness.licenseReviewStillRequiredForProduction !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private container packaging validation authority boundary is invalid.')
  return authority as unknown as OfflineContainerPackagingValidationRuntimeAuthority
}
async function executeWithImage(image: OfflineContainerPackagingValidationImageEvidence, value: unknown): Promise<OfflineContainerPackagingValidationExecutionResult> {
  const request = validateOfflineContainerPackagingValidationRequest(value); const result = await runOfflineContainerPackagingValidationContainer({ image, serializedRequest: JSON.stringify(request) })
  if (result.exitCode !== 0 || result.oomKilled || result.stderr.trim()) throw notReady('Private container packaging validation execution failed.')
  const response = parseResponse(result.stdout); const artifact = record(response.artifact); const packageIdentity = record(response.packageIdentity); const semanticEvidence = record(response.semanticEvidence); const readiness = record(response.readiness)
  const bytes = Buffer.from(string(artifact.bytesBase64), 'base64'); const sha256 = createHash('sha256').update(bytes).digest('hex'); const expectedPackage = OFFLINE_CONTAINER_PACKAGING_VALIDATION_PACKAGE_IDENTITIES[request.toolId]
  if (response.schemaVersion !== OFFLINE_CONTAINER_PACKAGING_VALIDATION_CONTAINER_PROTOCOL || response.ok !== true || response.toolId !== request.toolId || response.operationId !== request.operationId || response.status !== 'actual_container_packaging_validation_operation_completed' || packageIdentity.packageName !== expectedPackage.packageName || packageIdentity.version !== expectedPackage.version || response.requestEnvelopeSha256 !== offlineContainerPackagingValidationRequestSha256(request) || artifact.mimeType !== 'application/json' || artifact.byteLength !== bytes.byteLength || artifact.sha256 !== sha256 || bytes.length < 2 || bytes.length > 1024 * 1024 || readiness.privateInternalOnly !== true || readiness.productReady !== false || readiness.externalBetaReady !== false || readiness.productionReady !== false) throw notReady('Private container packaging validation result identity is invalid.')
  validateJsonArtifact(bytes, request.toolId); validateSemanticEvidence(request.toolId, semanticEvidence)
  if (Object.values(semanticEvidence).some((entry) => !['boolean', 'number', 'string'].includes(typeof entry))) throw notReady('Private container packaging validation semantic evidence contains an unsupported value.')
  const typedSemanticEvidence = semanticEvidence as Record<string, boolean | number | string>; const completedAt = new Date().toISOString()
  const attestationWithoutHash = { schemaVersion: 'offline-container-packaging-validation-execution-attestation-v1' as const, completedAt, toolId: request.toolId, imageIdentityHash: image.imageIdentityHash, requestEnvelopeSha256: offlineContainerPackagingValidationRequestSha256(request), artifactSha256: sha256, confinementHash: sha256AuthorityValue(result.confinement) }
  const attestationHash = sha256AuthorityValue(attestationWithoutHash); const recordId = sha256AuthorityValue({ attestationHash, completedAt }); const attestation = { ...attestationWithoutHash, recordId, attestationHash }
  await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_CONTAINER_PACKAGING_VALIDATION_STORAGE_ROOT, relativePath: `attestations/${recordId.slice(0, 2)}/${recordId}.json`, content: `${stableAuthorityStringify({ recordVersion: 'offline-container-packaging-validation-execution-attestation-record-v1', source: 'private_local_checksum_protected_container_packaging_validation_execution', attestation, checksumSha256: sha256AuthorityValue(attestation) })}\n` })
  return { schemaVersion: 'offline-container-packaging-validation-execution-result-v1', request, artifact: { mimeType: 'application/json', bytes, byteLength: bytes.length, sha256 }, evidence: { packageName: expectedPackage.packageName, packageVersion: expectedPackage.version, requestEnvelopeSha256: String(response.requestEnvelopeSha256), image, confinement: result.confinement, semanticEvidence: typedSemanticEvidence, containerExitCode: 0, oomKilled: false }, attestation, readiness: { privateInternalOnly: true, exactStructuredPayloadOnly: true, canonicalDispatchIntegrated: false, licenseReviewStillRequiredForProduction: true, productReady: false, externalBetaReady: false, productionReady: false } }
}
function validateSemanticEvidence(toolId: keyof typeof OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS, evidence: Record<string, unknown>): void {
  const entrypoint = toolId === 'mkvtoolnix_container_validation' ? 'mkvmerge --output + --identify' : 'MP4Box -add + -info'
  if (evidence.actualPackageEntrypointExecuted !== true || evidence.zeroNetworkRuntimeRequired !== true || evidence.approvedServerOwnedFixtureOnly !== true || evidence.entrypoint !== entrypoint || evidence.packageWritten !== true || evidence.containerRecognized !== true || evidence.videoTrackVerified !== true || evidence.audioTrackVerified !== true || evidence.captionTrackVerified !== true || evidence.trackCount !== 3) throw notReady('Private container packaging validation semantic evidence is invalid.')
}
function validateJsonArtifact(bytes: Buffer, toolId: keyof typeof OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS): void { let parsed: unknown; try { parsed = JSON.parse(bytes.toString('utf8')) } catch { throw notReady('Container packaging validation artifact is invalid JSON.') } const document = record(parsed); const expectedContainer = toolId === 'mkvtoolnix_container_validation' ? 'mkv' : 'mp4'; const expectedTracks = toolId === 'mkvtoolnix_container_validation' ? ['audio', 'subtitles', 'video'] : ['audio', 'text', 'video']; if (Object.keys(document).sort().join('|') !== ['audioVideoSyncRequired', 'captionIntegrityRequired', 'container', 'packagingAndIdentificationExecuted', 'recognized', 'trackCount', 'trackTypes'].sort().join('|') || document.container !== expectedContainer || document.recognized !== true || document.trackCount !== 3 || document.audioVideoSyncRequired !== true || document.captionIntegrityRequired !== true || document.packagingAndIdentificationExecuted !== true || stableAuthorityStringify(document.trackTypes) !== stableAuthorityStringify(expectedTracks)) throw notReady('Container packaging validation JSON artifact is invalid.') }
async function persistAuthority(image: OfflineContainerPackagingValidationImageEvidence): Promise<void> { const withoutHash = { schemaVersion: 'offline-container-packaging-validation-runtime-authority-v1' as const, source: 'private_local_offline_container_packaging_validation_runtime_authority' as const, activatedAt: new Date().toISOString(), image, supportedOperations: OFFLINE_CONTAINER_PACKAGING_VALIDATION_TOOL_IDS.map((toolId) => ({ toolId, operationId: OFFLINE_CONTAINER_PACKAGING_VALIDATION_OPERATIONS[toolId] })), readiness: { privateInternalExecutionReady: true as const, exactStructuredPayloadOnly: true as const, canonicalDispatchMayReference: true as const, licenseReviewStillRequiredForProduction: true as const, productReady: false as const, externalBetaReady: false as const, productionReady: false as const }, blockers: BLOCKERS }; const authority: OfflineContainerPackagingValidationRuntimeAuthority = { ...withoutHash, authorityHash: sha256AuthorityValue(withoutHash) }; await writePrivateTextFileAtomicWithinRoot({ rootPath: OFFLINE_CONTAINER_PACKAGING_VALIDATION_STORAGE_ROOT, relativePath: OFFLINE_CONTAINER_PACKAGING_VALIDATION_AUTHORITY_PATH, content: `${stableAuthorityStringify({ recordVersion: 'offline-container-packaging-validation-runtime-authority-record-v1', source: 'private_local_checksum_protected_container_packaging_validation_runtime', authority, checksumSha256: sha256AuthorityValue(authority) })}\n` }) }
function parseResponse(value: string): Record<string, unknown> { try { return record(JSON.parse(value)) } catch (cause) { throw notReady('Private container packaging validation response is not valid JSON.', cause) } }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw notReady('Private container packaging validation response contains an invalid object.'); return value as Record<string, unknown> }
function string(value: unknown): string { if (typeof value !== 'string') throw notReady('Private container packaging validation response contains an invalid string.'); return value }
function notReady(message: string, cause?: unknown) { return new ApiError('TOOL_NOT_READY', message, 503, undefined, { cause }) }
function invalid(message: string) { return new ApiError('VALIDATION_FAILED', message, 400) }
