steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - ${_DOCKERFILE}
      - --tag
      - ${_IMAGE}
      - --build-arg
      - REEDITPRO_SOURCE_COMMIT_SHA=${_SOURCE_COMMIT_SHA}
      - --build-arg
      - REEDITPRO_SOURCE_TREE_HASH=${_SOURCE_TREE_HASH}
      - --build-arg
      - REEDITPRO_SOURCE_CLEAN=${_SOURCE_CLEAN}
      - .
images:
  - ${_IMAGE}
timeout: 1200s
